### ISSUE TITLE
VLAN Default Sort Order

### ISSUE THREAD

**Issue by powderedegg** [digitalocean/netbox#1004]
When viewing the VLAN's, could the default behaviour be set to list the VLAN's sorted numerically by VLAN number?

http://127.0.0.1/ipam/vlans/

**Comment by jeremystretch** [comment]
The default behavior is to sort VLANs by site, group, and VID, in that order. This follows the hierarchical arrangement of VLAN objects and I don't see any reason to change it. You can always order by VID by clicking the column header.

**Comment by powderedegg** [comment]
Thanks for the answer, I'll close the issue.
