### ISSUE TITLE
1 Click App/OVA/OVF?

### ISSUE THREAD

**Issue by Lonecrowe** [digitalocean/netbox#1006]
Not an issue really but a question as to whether this will ever be rolled into a VM for people?  So far the instructions have not worked for a Centos 7 install using direct means, and docker without much difficulty.  Also incorrect information in some cases. 

It would be ideal if this actually were added to the 1 click app section and or a VM we could spin up to at least get to try the product.  

There should be little to no effort in getting this into the hands of people to try and contribute to.

**Comment by northalpha** [comment]
If there is an interest, i can publish my "all in one docker container" config.

**Comment by jeremystretch** [comment]
People are welcome to start a third-party package that provides NetBox as a VM, but it's not something we're going to include in the core repo. The additional overhead of maintaining multiple release packages subtracts significantly from development time. I'd actually like to move the Docker stuff to a separate repo as well.
