### ISSUE TITLE
Issue with NGINX and docker install after updating to 1.9.3

### ISSUE THREAD

**Issue by BMH64** [digitalocean/netbox#1007]
### Issue type: Bug
After upgrading to 1.9.3 and trying to start my containers, as I'm using the docker version. I get the following:
Starting postgres
Starting netbox
Starting ad5c1c08b86a_nginx

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint ad5c1c08b86a_nginx (a893b4ae87c76579041b9c4791a92a9400d78e46f131cb5d2acdbce1302ab29a): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

I've rebooted several times, before the upgrade it would say "Starting nginx" not "Starting ad5c1c08b86a_nginx" not sure how to rectify this, any help is appreciated, thanks.

**Python version: 2.7**
**NetBox version: 1.9.3**

**Comment by jeremystretch** [comment]
Please post to the mailing list concerning installation issues.
