### ISSUE TITLE
Feature Request:  Separate Fields for Address, City, State, Country, and Postal Code.

### ISSUE THREAD

**Issue by sinewaveinc** [digitalocean/netbox#1009]
Please create separate fields for the captioned wherever possible; even shipping a default set of site names/addresses for well-known datacenters, e.g. NJ1, NY3, etc.

**Comment by jeremystretch** [comment]
Using a single text field allows for the flexibility that's required when dealing with non-conforming addresses. NetBox doesn't do any validation on this data anyway, so there's not much benefit to having separate fields.

**Comment by Zanthras** [comment]
As an alternative pre-existing solution, just create those fields yourself as a custom field attached to sites.

This currently has to be done in the admin interface as there isnt a native interface for it, but it will work as you expect it to.
