### ISSUE TITLE
Enable viewing unique ID of connections

### ISSUE THREAD

**Issue by mdomore** [digitalocean/netbox#101]
When we are in the connections section, is it possible to add a/the unique id of the connection it can be usefull for labelling cables.

**Comment by jeremystretch** [comment]
Are you referring to the primary key which represents the connection in the database? I would strongly recommend using this for anything real-world, as it's really only significant within NetBox.

We do plan to implement fields for patch cable labeling as part of the initiative to start tracking physical cable plants.

**Comment by mdomore** [comment]
I was using a personal ipam solution but i'm not a dev so there was a lot of bug and not a lot of features. But i was generating a single id for each connection/cable enter in the ipam so i can have a reference.

Using a template to generate a unique label for cables and save it in netbox for reference could be usefull.

**Comment by jeremystretch** [comment]
Closing this as a duplicate since it's sure to be covered by #20.
