### ISSUE TITLE
Feature Request:  Vendor Device Dictionary

### ISSUE THREAD

**Issue by sinewaveinc** [digitalocean/netbox#1010]
Would be great to have a reference dictionary of devices from vendors, without having to create it from scratch, or, to be able to create it en-masse from a CSV import.

Would be happy to slog through this for a bunch of devices; 

Was thinking of something like this for a CSV import:

vendor,devrole,model,partnum,rackheight,depth,ram,storage,interfaceordering,dataifacerange1,dataifacerange2,mgmtinterface
juniper,switch,qfx5100,qfx5100-48s,1,full,8192MB,32768MB,slot,xe-0/0/0-47,et-0/1/0-5,em0

**Comment by jeremystretch** [comment]
Sounds like a duplicate of #451

**Comment by sinewaveinc** [comment]
Yeah, it is… my bad.
