### ISSUE TITLE
Livesearch device_list and ipaddress_list query_urls invalid

### ISSUE THREAD

**Issue by benagricola** [digitalocean/netbox#1011]
### Issue type: Bug
**Python version: 2.7.5**
**NetBox version: v2.0-beta1**

The `query_url` settings for the Livesearch widget across various fields within the `Circuits`, `DCIM` and `IPAM` forms appear to refer to the old API naming convention where underscores were used (e.g. `dcim-api:device_list` vs `dcim-api:device-list`.

This causes any page utilising a livesearch field (which includes Add / Edit IP Address, Connect Interfaces etc) to throw a Fatal error, manifesting as something like:

```
NoReverseMatch: Reverse for 'ipaddress_list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

Commit 46b8f3e3470fe56e5bae4c899756997343ac8a21 resolves this - happy to submit a PR if this is deemed the correct fix.

**Comment by jeremystretch** [comment]
Looks like this has already been fixed in `v2-develop` as part of #997.
