### ISSUE TITLE
Can not change/delete rack reservations as non-super user.

### ISSUE THREAD

**Issue by afics** [digitalocean/netbox#1013]
### Issue type: bug report

**Python version:** 3.4.2
**NetBox version:** v2.0-beta1

1. Add a group which has the rack reservation {create,change,delete} permissions.
2. Add a non super-user user. 
3. Add this user to the newly created group.
4. Login as the new user.
5. Add a rack reservation.
→ Change/Delete buttons for the reservations are missing; expected: buttons are visible and functional

Same result when adding the permissions directly to the user.

**Comment by afics** [comment]
Appending /edit lets me edit the reservations, so it's probably just the view.

**Comment by jeremystretch** [comment]
Yep, omitted the `.dcim` part of the permission names in the template. Thanks for the report!
