### ISSUE TITLE
Connect Interfaces B-side search API doesn't exist

### ISSUE THREAD

**Issue by benagricola** [digitalocean/netbox#1015]
### Issue type: Bug
**Python version: 2.7.5**
**NetBox version: v2.0-beta1**

When attempting to connect an interface on one device to another, The B side user interface contains a Device search field and an Interface listing.

Upon searching for and selecting the correct device, the Interface field remains empty (containing only `---`).

This occurs because the API request which is made (to `/api/dcim/devices/<device_b_id>/interfaces/?type=physical"`) does not exist and returns a 404.

As far as I can identify, this feature isn't implemented in the new-style API and from browsing around the API docs right now it looks like similar functionality doesn't exist (yet).

**Comment by jeremystretch** [comment]
One more that was covered by #997 I think.
