### ISSUE TITLE
Devices under the Select menu in Connect Interfaces not populating

### ISSUE THREAD

**Issue by pleasantarmour** [digitalocean/netbox#1016]
**Python version: 2.7.5.**
**NetBox version: 1.9.3.**

When trying to add a connection to a device, the devices menu under Select on the B side seems broken. I can use the Search tab to search for a device and then select the interface, but when I go to Select, the sites and racks are populated, but the devices never get populated.

Could this be an issue with my database or is this a bug with NetBox? Just upgraded from 1.7.3 to 1.9.3.

With debug mode enables, no log messages appeared.

**Comment by jeremystretch** [comment]
I'm not able to replicate this on v1.9.3. Your browser might still have Javascript from the previous version cached. Does forcing a refresh (ctrl+F5 or equivalent) help?

**Comment by pleasantarmour** [comment]
You're a life saver, that fixed it. Thank you!

**Comment by jeremystretch** [comment]
Good stuff. This seems to be a recurring issue. I've been trying to figure out a way to force a refresh of static resources (JS, CSS, etc.) after an upgrade.
