### ISSUE TITLE
Generic, non-unique Device for passive rack unit usage.

### ISSUE THREAD

**Issue by depereo** [digitalocean/netbox#1018]
### Issue type: Feature Request

**Python version:**
**NetBox version:**

It would be helpful when using Netbox to track rack usage to be able to use a 'generic' object in a rack unit. Currently when assigning RUs to things like Cable Management or Patch Panels one must create a unique name per cable management rack unit. This leads to "site-row-rack-rack unit-Cable MGMT" or "site-row-rack-rack unit-SMF to Row 3 Rack 2A" naming which is mildly onerous.

Having a 'generic' object would be hepful for this - being able to drop a 'passive physical' device into the rack that removes the requirement to uniquely name physical items.

**Comment by dav3860** [comment]
Yes, I agree, it would be useful.

**Comment by jsenecal** [comment]
Why would you want to obscure documentation like this? I mean, isn't
defining what the device does a great thing?

**Comment by therealjoshuad** [comment]
I think he's talking about devices that don't need to be defined, for example if there is wire management in a few Us, all I need to know is that those Us aren't available, with a simple indicator as "wire menagament", each wire management doesn't need to be tracked.

But to OP, I think this is what unnamed devices are for, have you tried that yet?

**Comment by jeremystretch** [comment]
> Currently when assigning RUs to things like Cable Management or Patch Panels one must create a unique name per cable management rack unit.

Like @therealjoshuad said, you have the option of leaving the device unnamed. The device's make and model will be displayed in the rack elevation.

Seems like this is covered by #417 so I'm going to close it as a duplicate.
