### ISSUE TITLE
Feature request: Description for modules in inventory

### ISSUE THREAD

**Issue by VictorJ76** [digitalocean/netbox#1019]
Actually the modules in inventory have Name, Manufacturer, Part ID, Serial number criteria but we cant specify description.

 My demand is to have the same criteria in a module as a `show inventory `command in Cisco IOS.  

To be more precisely, on Cisco we have a Name, Description, PID, VID and the serial number.

**Comment by marc-us** [comment]
I already have a patch available for this request. Is is quite simple. 
Feel free to remove not needed fields.
https://github.com/digitalocean/netbox/issues/987

**Comment by VictorJ76** [comment]
Thank for replying, your patch looks great ! 
I've an issue when adding it. 
```
<class 'django.db.utils.ProgrammingError'>

column dcim_module.class_id does not exist
LINE 1: ...cim_module"."serial", "dcim_module"."discovered", "dcim_modu...
```

Do have I to add table in database ?

**Comment by VictorJ76** [comment]
Solved, thank for you patch, it's exactly what I wanted
