### ISSUE TITLE
Autostart the service

### ISSUE THREAD

**Issue by olejohanHB** [digitalocean/netbox#102]
Its probably just a ordinary linux question or related to another app, but will the service autostart if the server is rebooted? 

if not, is there an easy way to get it to autostart?
like add to the file /etc/supervisor/conf.d/netbox.conf
"autostart = true" ?

**Comment by jeremystretch** [comment]
The example supervisor configuration provided in the [getting started](develop/docs/getting-started.md) guide should suffice. `autostart` is true by default.
