### ISSUE TITLE
DeviceType filter missing in api2

### ISSUE THREAD

**Issue by maximebrun** [digitalocean/netbox#1025]
It seems device type filtering has been dropped with api2.
For exemple, in adding/editing a device, all device types are display when we select a Manufacturer.

**Comment by marc-us** [comment]
Could you share some API request and outputs? Because I was not able to reproduce it.

**Comment by maximebrun** [comment]
I forgot to mention i'm using branch v2-develop

For exemple:
<pre>
#curl http://10.44.81.5/api/dcim/device-types/?manufacturer_id=5
{
   "next" : null,
   "results" : [
      ...
      {
         "comments" : "",
         "id" : 2,
         "custom_fields" : {
            "serial-conf" : null
         },
         "is_console_server" : false,
         "model" : "DL160Gen9",
         "part_number" : "",
         "instance_count" : 7,
         "is_network_device" : true,
         "is_pdu" : false,
         "u_height" : 1,
         "is_full_depth" : true,
         "manufacturer" : {
            "id" : 4,
            "slug" : "hp",
            "url" : "http://10.44.81.5/api/dcim/manufacturers/4/",
            "name" : "HP"
         },
         "interface_ordering" : {
            "value" : 1,
            "label" : "Slot/position"
         },
         "slug" : "dl160gen9",
         "subdevice_role" : null
      },
      ...
   ],
   "previous" : null,
   "count" : 16
}</pre>

**Comment by marc-us** [comment]
https://github.com/digitalocean/netbox/pull/1023/commits/8e1a34c853f42158fdb1b8e8409c960514e8f8ea Here is it :-)

**Comment by jeremystretch** [comment]
I can't merge the linked commit as its part of a larger PR, but I'll make the change. Thanks for the report.
