### ISSUE TITLE
Invalid URL reference when creating/editing an IP address

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1028]
### Issue type: Bug report

**Python version:** 2.7.6
**NetBox version:** v2-beta

Navigating to the IP address create/edit view yields a server error:

```
Reverse for 'ipaddress_list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

This is due to an invalid URL name given in `IPAddressForm`.

**Comment by tmack8080** [comment]
Confirmed fix in the v2-develop build
