### ISSUE TITLE
v2 Beta Error When Adding an IP: "<class 'django.urls.exceptions.NoReverseMatch'>  Reverse for 'ipaddress_list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []"

### ISSUE THREAD

**Issue by tmack8080** [digitalocean/netbox#1029]
When Trying to add an IP from the menu: "IP Space > Add an IP" the following error is displayed:

<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'ipaddress_list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

![image](https://cloud.githubusercontent.com/assets/22790644/24633234/6e4227d2-1895-11e7-8598-b32cfed52441.png)

An IP address can be added via CSV but that entry cannot be modified as the same error is displayed when the entry is accessed.

**Comment by jeremystretch** [comment]
Beat you to it with #1028. Thanks though!
