### ISSUE TITLE
v1.9.4 - Model Migration Warning?

### ISSUE THREAD

**Issue by robclarkey** [digitalocean/netbox#1034]
### Issue type: Bug Report
**Python version:** 2.7.5
**NetBox version:** 1.9.4 (upgrading from 1.9.3

**Error Message:**
` Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.`

Got the above when upgrading from v1.9.3 to v1.9.4. Not sure if this is intentional (changes in the model that will be added in a future release), or if it's a bug.

**Upgrade Steps:**

1. Stopped Webserver (Apache).
2. Downloaded v1.9.4.zip file to /opt
3. Extracted zip to /opt/netbox-1.9.4
4. Copied configuration.py & ldap_config.py from /opt/netbox/netbox/netbox to /opt/netbox-1.9.4/netbox/netbox
5. Deleted /opt/netbox symlink.
6. Recreated /opt/netbox symlink pointing to /opt/netbox-1.9.4
7. Ran upgrade.sh inside /opt/netbox.
8. Started webserver.

**Comment by jeremystretch** [comment]
Sorry about that. I've created patch release [v1.9.4-r1](https://github.com/digitalocean/netbox/releases/tag/v1.9.4-r1) to fix this.

**Comment by robclarkey** [comment]
@jeremystretch Perfect! Thank you! 😃
