### ISSUE TITLE
Drop down showing syntax instead of Label

### ISSUE THREAD

**Issue by snazy2000** [digitalocean/netbox#1038]
### Issue type:

**Python version:** 2.7.12
**NetBox version:** 1.9.5-dev

When adding new device I am seeing this, also see this when connecting interfaces

![image](https://cloud.githubusercontent.com/assets/1378836/24710899/68848362-1a16-11e7-82e2-aed81f366c96.png)

**Comment by lampwins** [comment]
Confirmed also present when connecting interfaces on regular v1.9.4 (have not tried r1 yet).

**Comment by jeremystretch** [comment]
Django 1.11 changed the way certain form widgets are rendered. Downgrade to Django 1.10 for now; v2.0 will support only Django 1.11 and up.

**Comment by jeremystretch** [comment]
78b00720513ebd8c7f4236097c336777c8eeaeb4 will prevent Django 1.11 from being installed beginning with v1.9.5.

**Comment by snazy2000** [comment]
That fixed it, thanks would it be worth changing the requirements.txt??
