### ISSUE TITLE
Store PDF files linked to Circuits (Acceptance Certificates)

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1039]
Would it be a consideration to include the ability to attach PDF files to a Circuit. It would be really helpful to allow one to attach the acceptance certificate for a circuit and have reference to it within the same environment. 

The files can be uploaded and stored on disk, and only a link to the file stored in the DB and there is no real need to store the files in the DB for indexing etc.

Agreed that one could include a file share link to a file server, but to keep all relevant information stored in one location, it would make sense that it could be opened within the browser at the point of reviewing a circuit.

This might have some reference to issue #182

**Comment by jeremystretch** [comment]
I don't believe NetBox should act as a file store. An argument could be made to support file attachments for any of the primary models in NetBox, but that's not its purpose. #152 works because there's a lot of value in serving image media directly from NetBox, but there are much more suitable tools for storing miscellaneous attachments.

Alternatively, I suggest creating a custom URL field on the circuit model pointing to the document hosted elsewhere.

**Comment by InsaneSplash** [comment]
OK, would it be possible then to allow the creation of a custom field URL, but display a name and not the URL itself?
Sometimes these things (URLS) can get really long, and all that is required is a name to click on.

**Comment by lampwins** [comment]
@InsaneSplash Probably related to #969

**Comment by InsaneSplash** [comment]
Yeah that would be a big help if we are required to use external URLs to reference related data. I could write a separate tool to upload the pdf file, and then using the custom URL could map it to the file on the webserver. The only requirement would be to be able to apply a **custom URL for *all* circuits** with a variable of the circuit. Having to type in the URL for each circuit would defeat the purpose since it would add additional overhead that could be scripted.

**Comment by bellwood** [comment]
Perhaps a compromise could be dropbox/g-drive integration so one could *easily* link documents stored in "the cloud" ... API for these are quite robust and public ... if implemented in a such a manner, perhaps EU's could write integrations for other platforms as they see fit?

Just spit balling

**Comment by jeremystretch** [comment]
Seems like #969 could work for this. Closing this one out.
