### ISSUE TITLE
Feature request: Add drag-and-drop functionality to rack plan

### ISSUE THREAD

**Issue by vahem2lu** [digitalocean/netbox#1050]
Hi!

This is a feature request.

I am using Netbox 1.9 and this is fantastic! I am trying to get it working inside my company and I have some support among my colleagues.
Some are trying to say that Excel is still better IPAM than web based interface, but hey. :)

Anyway - I am looking for a opportunity to drag-and-drop devices inside my rack, so I wouldn't have to open each device if I need to reposition something.

Would that be possible in future versions?

Thanks!

**Comment by jeremystretch** [comment]
Duplicate of #124. Probably not going to be implemented any time soon.
