### ISSUE TITLE
Type error when accessing /api/docs

### ISSUE THREAD

**Issue by afics** [digitalocean/netbox#1051]
### Issue type: bug report

**Python version:** 3.4.2
**NetBox version:** v2.0-beta2

1. Go to `/api/docs`
2. Result:
```
<class 'TypeError'>

context must be a dict rather than RequestContext.
```
Expected: Swagger lists API calls, etc.

**Comment by jeremystretch** [comment]
requirements.txt wants `django-rest-swagger==0.3.10`. This should be changed to the lastest working version.

**Comment by eliezerlp** [comment]
Will this be merged into the v2 branches...? I was waiting for a writable API to start working with the API and now can't see the nice swagger based docs.
