### ISSUE TITLE
Help: LDAP authentication 

### ISSUE THREAD

**Issue by VictorJ76** [digitalocean/netbox#1053]
I have done the requirement's installation and created the conf's file and modify it. How do I test the connection ? Do I need to change something else or restart a service ? Do there are logs or something to test it ?

**Comment by jeremystretch** [comment]
GitHub issues are intended for reporting bugs and requesting features. For general discussion or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
