### ISSUE TITLE
Allow to switch to next/previous rack via cursor keys

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#1055]
It would be quite handy if you could switch the racks by left and right cursor keys instead to click on the "Next Rack" and "Previous Rack" buttons at the top of the page each time.

**Comment by jeremystretch** [comment]
I'm going to reject this FR for the same reason I closed #917: I want to avoid tacking on extra Javascript to the UI unless it's absolutely necessary. That has the potential to snowball into a huge mess very quickly. The current UI will eventually be replaced with an API-driven JS framework, at which point we can entertain enhancements such as this.
