### ISSUE TITLE
Adding Interface with a character class with one item taken literally

### ISSUE THREAD

**Issue by zevlag** [digitalocean/netbox#1065]
### Issue type: Bug

**Python version:** 2.7
**NetBox version:** v2.0-beta2
I tried adding this interface `GigabitEthernet0/0/2.[80]` and it was added literally instead of as `GigabitEthernet0/0/2.80`, even though a range such as `GigabitEthernet0/0/2.[80,81]` works properly.

Expected behaviour or bug?

**Comment by jeremystretch** [comment]
Expected behavior. The regex checks for the presence of a comma within brackets. Otherwise, it would be impossible to create an interface with brackets in the name.
