### ISSUE TITLE
Ability to change "Order interfaces by" option for a particular device (and/or propagate changes in Device Type to Devices)

### ISSUE THREAD

**Issue by eliezerlp** [digitalocean/netbox#1066]
### Issue type: feature request

Ability to change "Order interfaces by" option for a particular device (and/or propagate changes in Device Type to Devices).

I added a Device Type and didn't really understand what this meant. After adding a Device there is no way to change whatever option was inherited from the Device Type.

**Comment by jeremystretch** [comment]
From [the docs](http://netbox.readthedocs.io/en/latest/data-model/dcim/#device-types):

> A device type represents a particular hardware model that exists in the real world. Device types describe the physical attributes of a device (rack height and depth), its class (e.g. console server, PDU, etc.), and its individual components (console, power, and data).

Interface ordering is typically going to be the same for all instances of a device type, therefore it's defined on the parent device type rather than on each individual device. Does that make sense? Do you have a use case where this is not sufficient?

**Comment by eliezerlp** [comment]
I agree that defining it globally is good enough. The problem comes about when the global definition in Device Types is changed and it doesn't propagate to Devices that were created from it. At the same time there is no way to change it for an already created device so it forces deleting and re-adding devices...

**Comment by jeremystretch** [comment]
Each device references the `interface_ordering` setting of its parent device type. If you change the setting on the device type, it is effectively changed on all instances of that device type as well.
