### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by arraisfilho** [digitalocean/netbox#1068]
Is there any way to translate Netbox or how it was developed does not fit this upgrade?

I am willing to help with the translation process, especially for Portuguese (Brazil).

**Comment by eliezerlp** [comment]
Willing to contribute a Spanish translation

**Comment by jeremystretch** [comment]
While the Django framework [does support translations](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/), NetBox is not currently set up to use them. The first part of this would be to iterate over the entire code base and insert a translation wrapper around virtually every string. This wouldn't be difficult, but it would obviously take a good bit of time.

The second part of this is establishing the actual translation databases. These are essentially static mappings of natives (English) string to their equivalents in a different language, which means that every time a string is modified (even slightly), every translation has to be updated as well, or the translation for that string breaks. Considering the size of the NetBox code base, you can imagine how much maintenance this would require.

At this relatively early stage of development, I don't think it makes sense to support translations yet. It would introduce a _lot_ of development overhead, and translators would constantly be playing catch-up.

**Comment by arraisfilho** [comment]
Thank you for your clarification. When a translation is possible, I will be willing to contribute.

**Comment by jeremystretch** [comment]
Thanks for understanding. We'll get there one day, once the pace of development slows down a bit.

**Comment by cimnine** [comment]
There are nice tools to make translating a community effort, at least once the groundwork has been done. Two such services that I know off and which are free for opensource projects are [POEditor](https://poeditor.com/features/) and [LingoHub](https://lingohub.com/features/), but there are lots of other tools as well.

**Comment by lae** [comment]
It's been a year and a half since NetBox released 2.0. Do you think we're at a point where this would be feasible to implement now? I'd be willing to assist (and have implemented i18n for another Django project before).
