### ISSUE TITLE
Interface sorting broken in Device view

### ISSUE THREAD

**Issue by mweinelt** [digitalocean/netbox#1069]
### Issue type: Bug report

**Python version:** 3.6
**NetBox version:** 2.0-beta2

According to the Interface model the sorting for Interfaces is defined as follows:
```python
class Interface(models.Model):
    class Meta:
        ordering = ['device', 'name']
```

The table is being rendered in a for loop in https://github.com/digitalocean/netbox/blob/v2.0-beta2/netbox/templates/dcim/device.html#L445-L453:

```jinja
                 <table class="table table-hover panel-body">
                    {% for iface in interfaces %}
                        {% include 'dcim/inc/interface.html' with selectable=True %}
                    {% empty %}
                        <tr>
                            <td colspan="4">No interfaces defined</td>
                        </tr>
                    {% endfor %}
                </table>
```

However interfaces are currently not sorted by name:

![Interface panel in device view](https://i.imgur.com/4SmzqJa.png)

**Comment by jeremystretch** [comment]
Interfaces are ordered based on the ordering logic selected on the parent device type. Currently the interfaces are being ordered by numeric position (0, 1, 2). If you switch the device type's ordering to "name" the interfaces should appear as you want.

**Comment by mweinelt** [comment]
Oh yeah, that was fit. Thanks for the prompt explanation.
