### ISSUE TITLE
Proxy error in login Netbox 1.9.5

### ISSUE THREAD

**Issue by vahem2lu** [digitalocean/netbox#1076]
Hi

Today I noticed weird error on my Netbox.

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /login/.

Reason: Error reading from remote server
```

Did update to 1.9.5 and same error stayed.

**Comment by jeremystretch** [comment]
This appears to be an issue with your installation. Please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) for assistance.
