### ISSUE TITLE
Rack exports "Descending units" value blank if set to False

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#1082]
When you export a rack the "Descending units" column is not present.

IIRC export templates are stored in PG so this will need a migration to fix.

**Comment by bellwood** [comment]
So, the column actually is there, but it is blank if the rack uses False for the field.

If the rack does have Descending Units then True is displayed in this field.

The issue is, without a False being the field and it being the last column when you re-export the csv, that column is omitted and adds the need to massage the data to reimport it.

**Comment by jeremystretch** [comment]
This is just the nature of CSV. The same thing is true for objects for which the last field is an optional description. #655 will address this.
