### ISSUE TITLE
'django.db.utils.ProgrammingError' when i want to edit device

### ISSUE THREAD

**Issue by buffonj** [digitalocean/netbox#1083]
I have create a device in devices/DCIM. when i click the device name link, there is an error page after that.
the error information is below:
<class 'django.db.utils.ProgrammingError'>

error:  function concat(text, text) does not exist
LINE 1: SELECT (CONCAT(SUBSTRING(dcim_poweroutlet.name FROM '^[^0-9]...
                ^

so what's the problem?

**Comment by jeremystretch** [comment]
You have not provided sufficient detail for anyone to help you. Please provide the versions of NetBox and Django which you are running, as indicated by the bug report template, as well as the version of PostgreSQL you are using and some background on your installation.

**Comment by buffonj** [comment]
Netbox version: 1.9.5
Django version  1.11
PostgreSQL version: 8.4.20
I followed the installation documentation from GitHub. After I finish all the steps, I must manually execute the command "gunicorn -c /opt/netbox/gunicorn_config.py netbox.wsgi" to let Netbox start. But it is not important right now. the error page is below.
![image](https://cloud.githubusercontent.com/assets/26614245/25113502/875669ae-242a-11e7-9d79-653d2fceaa15.png)

**Comment by jeremystretch** [comment]
Your version of PostgreSQL has been [EOL](https://www.postgresql.org/support/versioning/) for nearly three years and does not support the `CONCAT` function. Please upgrade to a currently supported version (9.2 or better).
