### ISSUE TITLE
class 'django.template.exceptions.TemplateSyntaxError on main page

### ISSUE THREAD

**Issue by adamtbeames** [digitalocean/netbox#1087]
[debug.txt](https://github.com/digitalocean/netbox/files/929717/debug.txt)

### Issue type: bug report

**Python version:** 2.7.13
**NetBox version:** 1.9.5

After running an upgrade from v1.7.3 to v1.9.5, the main page shows a "Server Error" :

`<class 'django.template.exceptions.TemplateSyntaxError'>

`Invalid filter: 'contains'`

**Comment by jeremystretch** [comment]
Did you restart the WSGI process after upgrading?

**Comment by adamtbeames** [comment]
Doh!
Killed the procs off and restarted nginx.  All good now.
Thanks for the help and thanks for netbox.
