### ISSUE TITLE
Search panel inconsistently provides "none" as an option

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#1089]
### Issue type: Interface inconsistency

**Python version: 2.7**
**NetBox version: 1.9.5**

When viewing all racks, the search options on the right give me a searchable option for "none" under:

- Rackgroup
- Tenant
- Role

Oddly, Site doesn't have "none" even though this too is an optional field.

When viewing devices I have a searchable option for "none" under:

- Tenant
- Platform

So my question is, should "none" be there for all optional fields when searching or perhaps should "none" only exist IF there are racks/devices in the database that are associated to those optional fields with undefined values.

Data point, all my racks are assigned a rack group and role, yet "none" is an option for those. They are all also assigned to a site, but, "none" is not an option for site.

**Comment by jeremystretch** [comment]
> Oddly, Site doesn't have "none" even though this too is an optional field.

Site isn't an optional field. Every rack must be assigned to a site.

> So my question is, should "none" be there for all optional fields when searching or perhaps should "none" only exist IF there are racks/devices in the database that are associated to those optional fields with undefined values.

"None" is provided as a filter option for optional fields, regardless of what models are defined in the database.

**Comment by bellwood** [comment]
Thank you for the clarification.
