### ISSUE TITLE
Hide header menus when not logged in

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#109]
Granted you cant do anything if you are not logged in, but it looks like only some of the menu items are filtered if you aren't logged in.

I suggest hiding anything besides login in and the netbox "brand" in the header

**Comment by jeremystretch** [comment]
NetBox was designed with the intention of allowing anonymous users to access its data (except secrets, of course) but not make any changes. If you want to disable anonymous access entirely, you can set `LOGIN_REQUIRED = True` in [configuration.py](https://github.com/digitalocean/netbox/blob/develop/docs/configuration.md). This will only display a login page for unauthenticated users.

**Comment by bellwood** [comment]
With login required, when I view the page, I get all the menus with all the search options... they all route back to the login page, so why show them at all?
