### ISSUE TITLE
pip3 instead of pip in install docs

### ISSUE THREAD

**Issue by mzac** [digitalocean/netbox#1090]
### Issue type: Bug report

**Python version:** 3
**NetBox version:** 1.9.5

While reading the install docs I decided to use Python 3 however getting to the step of 'pip install -r requirements.txt' this failed, the documentation needs to have 'pip3 install -r requirements.txt' added if you are using python3.

**Comment by jeremystretch** [comment]
Can you please provide a detailed account of the installation procedure you followed?

**Comment by bellwood** [comment]
There was a discussion in the Google group about this as well:

https://groups.google.com/forum/#!topic/netbox-discuss/Sc3Bp2glPqs

**Comment by jeremystretch** [comment]
Turns out there are several issues when only Python 3 is installed (on Ubuntu, at least).

* Ubuntu has different packages for psycopg2 under Python 2/3
* Ubuntu does not provide `/usr/bin/python` (only `/usr/bin/python3`)
* Ubuntu does not provide `/usr/bin/pip` (only `/usr/bin/pip3`)

**Comment by mzac** [comment]
Glad you found the fix :)  I'm still quite new to python so I wasn't sure if I was missing something but it looks like I'll give it a retry on python 3 instead of python 2 now...

**Comment by bellwood** [comment]
Prior to releasing v2.0 which will require Python3 we should make sure that the docs for both Ubuntu and RHEL/Cent are firm otherwise I can foresee a large inrush of related issues.

**Comment by jeremystretch** [comment]
I've worked through a few Ubuntu and CentOS installations using Python 3 and I think this has been sorted. I'm going to close out this issue but please feel free to re-open or open a new one as appropriate for any outstanding issues.

> Prior to releasing v2.0 which will require Python3

NetBox v2.0 won't _require_ Python3 (although it's strongly encouraged). We'll still be on Django 1.11. Django 2.0 will drop support for Python3, but we probably won't move to Django 2.0 until sometime in early 2018. No promises, though.
