### ISSUE TITLE
Support writable custom fields in API 2.0

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1091]
API 2.0 supports only read access to an object's custom fields. We need to figure out a way to serialize custom fields for write operations while still treating a set of fields as though they belong to a single object.

**Comment by jeremystretch** [comment]
Still trying to figure this out. Any help is much appreciated. http://stackoverflow.com/questions/43591848/writing-to-a-set-of-objects-as-a-single-dictionary-in-django-rest-framework

**Comment by uZer** [comment]
Thanks!
