### ISSUE TITLE
Multiple devices in rack unit

### ISSUE THREAD

**Issue by mzac** [digitalocean/netbox#1096]
Has there been any though to having an option to add multiple devices to a rack unit? For example if you have a shelf (which I saw is in #417) with multiple devices sitting on it, like a few Raspberry PIs for example...

**Comment by puck** [comment]
I create a shelf with the appropriate number of slots and add the devices like the RPi's to the appropriate slot.

**Comment by jeremystretch** [comment]
The rack unit is considered occupied by the shelf (whether or not the shelf is holding any other devices). You can either take @puck's approach and define device bays for the shelf to house the devices, or just create those as unracked devices and note in the comments of each that it is located on the shelf.
