### ISSUE TITLE
Device not in rack; ceiling mount?

### ISSUE THREAD

**Issue by mzac** [digitalocean/netbox#1097]
Any thoughts on adding a function to define if a device is not in a rack, say:
- On a ceiling (wireless access point)
- On a wall (camera, sensors)
- Inside another device (management card inside UPS, AC Unit),
- Wall mount switch
- etc...

**Comment by eronlloyd** [comment]
Agreed. We have bakers racks with tower servers, and turning off the RU indicator would be nice.

**Comment by bellwood** [comment]
These would be considered unracked devices. Simply assign them to the site they are in and notate their location accordingly.

**Comment by jeremystretch** [comment]
As @bellwood suggested, assignment of devices to racks became optional in v1.9.0.
