### ISSUE TITLE
HTML code when creating device role?

### ISSUE THREAD

**Issue by mzac** [digitalocean/netbox#1098]
### Issue type: Bug

**Python version:** 2.7.12
**NetBox version:** 1.9.5

I just added a device role and in the green box after creation I got this:

`Created device role <a href="/dcim/devices/?role=storage">Storage</a>
 Add a device role
`

**Comment by mzac** [comment]
Same when creating a device type:

`Created device type <a href="/dcim/device-types/6/">DS216J</a>
`

**Comment by jeremystretch** [comment]
Looks potentially related to #1061, but that change was made in 1.9.6. Please upgrade to 1.9.6 and see if it resolves the issue.

**Comment by mzac** [comment]
Hmm.. ok I think I'm running 1.9.6, however at the bottom of the screen it still shows 1.9.5, even if I try flushing my browser, incognito, different browser... but when I look in settings:

<pre>
root@netbox1:~# grep VERSION /opt/netbox/netbox/netbox/settings.py
VERSION = '1.9.6'
</pre>

Am I missing something?

<pre>
root@netbox1:/opt/netbox# git pull
Already up-to-date.
</pre>

<pre>
root@netbox1:/opt/netbox# cat .git/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/digitalocean/netbox.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
</pre>

**Comment by jeremystretch** [comment]
Did you restart the WSGI service? E.g. `supervisorctl restart netbox`?

**Comment by mzac** [comment]
Ok yes restarting 'supervisor' did the trick for me!  I don't see the HTML code anymore.

I wonder if adding a note to the upgrade.sh to restart it manually or having it check to see if we are using supervisor and restart it?

**Comment by jeremystretch** [comment]
Restarting the WSGI service is already called out pretty prominently [in the docs](http://netbox.readthedocs.io/en/stable/installation/upgrading/). Unfortunately it's not something we can automate because not everyone implements it the same way.
