### ISSUE TITLE
[Bug] Editing multiple items causes an error

### ISSUE THREAD

**Issue by DHeckman85** [digitalocean/netbox#110]
When checking two items and editing those selected items, any changes to the attributes will result in an error when saving. 

To Reproduce:
Selecting 2 prefixes with the checkbox
Editing those prefixes
Changing any attribute
Saving

Results in:
Server Error 
There was a problem with your request. This error has been logged and administrative staff have been notified. Please return to the home page and try again.

Per Stretch in IRC 'Status' is missing from the form

**Comment by jeremystretch** [comment]
This bug was introduced when prefix/VLAN statuses were changed from custom objects to a static ChoiceField (pre-1.0.0). Need to correct the forms to re-include the status field.
