### ISSUE TITLE
Unable to set a Site in Interface Assignment in IP address page: bug v1.9.6?

### ISSUE THREAD

**Issue by gdouchet** [digitalocean/netbox#1101]
Hello,

I upgraded to 1.9.6 and noticed I'm unable to assign a site to an IP adress in Interface Assignment Page. 
I can choose the site in the Site list but when I go back to the page after saving, the field is "--".

Moreover, the drop-down list for Device and Interface is empty (see attachment). Maybe a link with the optional Rack field?

Gauthier
![capture d ecran 2017-04-22 a 08 05 27](https://cloud.githubusercontent.com/assets/20498096/25301932/b453a83a-2732-11e7-881d-ecce4d69f058.png)

**Comment by mzac** [comment]
Same issue here... I was able to get around the issue by using the admin interface for now

**Comment by snazy2000** [comment]
There is a bug here but its not assigning it to a Site, you are unable to get down to the Device Level because when selecting a Rack the API is not being called to check for the list of devices. So when you have it it will not save it as a Site, that's how its always been I believe.

**Comment by gdouchet** [comment]
mzac: I tried with admin login and same problem.

snazy2000: I had this problem too but normally the site field is optional so it should not create this problem.

**Comment by mzac** [comment]
When I said the admin interface I meant:

http://ipam.lab.local/admin/dcim/device/2/change/

And from there you can change all the settings..

![image](https://cloud.githubusercontent.com/assets/10270879/25313894/770d078a-2806-11e7-9163-57a2ab6c6650.png)

**Comment by gdouchet** [comment]
Ok thank you for the explanation.

But it remains a "bypass" solution..

**Comment by muddus** [comment]
Same here. The device list doesn't show up while adding a new IP address

**Comment by jeremystretch** [comment]
This bug also affects the console, power, and interface connection forms.

**Comment by snazy2000** [comment]
I believe this is still an issue, when I try and edit an interface it does not populate the devices anymore.
