### ISSUE TITLE
Prefix import does not include VLAN

### ISSUE THREAD

**Issue by royvegard** [digitalocean/netbox#1104]
### Issue type: Bug report

**Python version:** 2.7.12
**NetBox version:** 1.9.7-dev 861c8b29c0df07d2015fca0cd46bf1a6259ea48e

Importing a prefix with a valid VLAN does not include the VLAN.

### Steps to reproduce
1. Create a VLAN with and ID of 100.
2. Enter the following into the Prefix import form and submit:
`192.0.2.0/24,,,,,100,Active,,False,`

The prefix will be imported but it will not include the VLAN.

I believe this was introduced in d3b16ba443b0d1ca45299f6765cd92fc926c7ed0. Line 239 is always executed - setting `self.instance.vlan = vlan` which sets it to `None`. I'm guessing that it should only be executed if exeption `VLAN.MultipleObjectsReturned` happens.

**Comment by jeremystretch** [comment]
Thanks!
