### ISSUE TITLE
Inconsistent workflow adding IP to interface

### ISSUE THREAD

**Issue by LordBoBCUP** [digitalocean/netbox#1108]
### Issue type:

**Python version:** 2.7.12
**NetBox version:** v1.9.6

Hi, I believe that the workflow for adding a new IP to an interface from the Device->Add IP to Interface allows for you to create and add another, its unlikely that you would want to do this as interfaces typically would only have a single address added to them. If you are for instance going through and adding IPs to virtual interfaces on a newly deployed switch you could think that by clicking that button you can continue adding to more virtual interfaces, however, if you do, you end up at a place where you cannot select Site/Rack/Device/Interface, the options are only Site/Rack then Device/Interface are ---- 

Not sure if this is the intended workflow and removing the button and only having the create/cancel buttons is better, or if fixing the form presented after clicking create and add another is a better method.

Thanks
Alex

**Comment by jeremystretch** [comment]
Pre-population of the form should be covered by #648. Going to close out this one as a duplicate.

> its unlikely that you would want to do this as interfaces typically would only have a single address added to them

It's very common to have multiple IPs assigned to an interface. For example, one IPv4 and one IPv6 address.
