### ISSUE TITLE
Prefix Bulk editing, allow changing them to pools 

### ISSUE THREAD

**Issue by sylr** [digitalocean/netbox#1110]
Hi,

It would be handy when editing Prefix Bulk to be able to turn them into pools.

Regards.

**Comment by jeremystretch** [comment]
Several other bulk edit forms need to be expanded to include similar boolean fields. Here's the complete list I'm expanding:

* Racks (desc_units)
* DeviceTypes (is_full_depth, is_console_server, is_pdu, is_network_device)
* InterfaceTemplates (mgmt_only)
* Interfaces (mgmt_only)
* VRFs (enforce_unique)
* Prefixes (is_pool)
