### ISSUE TITLE
[Question] CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by salt-lick** [digitalocean/netbox#112]
Followed the Getting Started and got the frontend to load just fine. Trying to login to the admin area and I'm presented with 

Reason given for failure:
    Referer checking failed - $mydomainhere:5555/login/?next=/ does not match any trusted origins.

**Comment by salt-lick** [comment]
The CSRF token is being created in the form

ex: <input type="hidden" name="csrfmiddlewaretoken" value="Ypyceek9WojBPwdN1rWpQNtKlvO9Qr48">

**Comment by salt-lick** [comment]
Solved: 

I was using a custom port and that needed to be in the ALLOWED_HOSTS setting as part of the FSDN.

Thanks for the IRC help.

**Comment by jkldgoefgkljefogeg** [comment]
I have this issue when serving https with nginx. Every POST fails with CSRF verification failed

**Comment by rzig** [comment]
@jkldgoefgkljefogeg  did you ever figure out the solution?

**Comment by Eric2XU** [comment]
I ran into this issue doing reverse proxy via Azure. The trick was to set the server_name in the nginx.conf file to the dns name the clients see not the internal one.

**Comment by Dorisnov** [comment]
I'm having this same issue using RESTer: Can make GET request but not POST requests (_CSRF Failed: CSRF token missing or incorrect._) Anyone figured out how to make it work?

**Comment by DanSheps** [comment]
> I'm having this same issue using RESTer: Can make GET request but not POST requests (_CSRF Failed: CSRF token missing or incorrect._) Anyone figured out how to make it work?

This is not a place for requesting support, please check out the mailing list.

If you have a reproducible bug or a feature request, you can create a new issue here.
