### ISSUE TITLE
Add 'purchase date' and 'comment' to Inventory Item

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1121]
### Issue type: Feature Request

In Netbox, there are Inventory Items on a Device. In our company, we currently track the purchase date for disks and RAM. For some items, we also have an independent asset id, particularly for disks.
Furthermore, we track information that is rather specific to the kind of the inventory item. (Examples are the size of a disk as well as the size and the amount of (the same kind of) RAM sticks). Such information could simply be written to a Comment field, if there was one.

I therefore ask for the following optional fields to be added to the Inventory Item:
* Purchase Date (DateTime)
* Asset ID (Char, 50)
* Comment (Text)

In a separate issue, I also ask for custom fields to be made available on Inventory Items: #1120

**Comment by jeremystretch** [comment]
The asset ID and comment fields make sense to me. I think that adding purchasing information extends a bit beyond NetBox's scope. That information should be tracked in an external system along with purchase orders and collated by serial numbers.

**Comment by mlmingle** [comment]
Will this be configurable per item? I thought it would be nice to track spare line cards in the inventory of the device.

**Comment by jeremystretch** [comment]
Added `asset_tag` and `description` fields to the InventoryItem model in 5940feb

**Comment by alexjhart** [comment]
Does https://github.com/digitalocean/netbox/commit/5940feb64b3c3a72f6b72bcdba26023493c1fd41 actually solve https://github.com/digitalocean/netbox/issues/1120 (custom fields)?
