### ISSUE TITLE
Convert UserAction logging to use signals

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1127]
NetBox records use activity as UserAction objects. Currently, these are created explicitly inside views. In order to standardize their creation and integrate with the new API, we NetBox should utilize [Django's signals](https://docs.djangoproject.com/en/1.11/topics/signals/) to control the creation of UserActions.

**Comment by lampwins** [comment]
I like this approach a lot. It will tie nicely into #81.

**Comment by jeremystretch** [comment]
This should solve #403

**Comment by jeremystretch** [comment]
Actually, I'm not sure this is feasible. Django's `post_save` and `post_delete` signals unfortunately don't pass the request context, so we have no way of determining the user responsible for an action (which we need to record in the UserAction). We might just have to keep handling this in the views.

**Comment by lampwins** [comment]
Could we not create our own signals to handle this? I agree, it would be more elegant if `post_save` and `post_delete` were feasible, but I think there is still a way to do this and set it up for future extension via #81

**Comment by jeremystretch** [comment]
The [django-audit-log](https://github.com/Atomidata/django-audit-log/blob/master/audit_log/middleware.py#L26) project has a really clever way of handling this. It uses `process_request` in middleware to create a curried function which has been passed request data (the user) and connect it to the `pre_save` signal.

**Comment by jeremystretch** [comment]
Folding this into #1898
