### ISSUE TITLE
Swagger UI URL issue when Netbox is published behind a reverse proxy

### ISSUE THREAD

**Issue by dav3860** [digitalocean/netbox#1129]
### Issue type: feature request

**Python version:** 2.7.5
**NetBox version:** 2.0b3

We publish Netbox behind a reverse proxy in HTTPS. But in the Swagger UI, all the links and actions have a protocol set to http. So it doesn't work.
It would be nice if Swagger could use relative URIs or if we could specify the exposed URL of Netbox in the config file.

**Comment by jeremystretch** [comment]
I also run NetBox on HTTPS but don't have this problem. Can you please share you configurations and the version of Swagger you have installed?

**Comment by dav3860** [comment]
Here is the version of Swagger :
`django-rest-swagger (2.1.2)`

My server is named "netbox" and served behind https://netbox, but :
![capture](https://cloud.githubusercontent.com/assets/2794902/25695687/6443e4aa-30b4-11e7-886e-a293f5676483.PNG)

Here is my Apache configuration for this vHost :
```
<VirtualHost *:80>
  ServerName netbox
  Redirect permanent / https://netbox/
</VirtualHost>

<VirtualHost *:443>
  ServerName netbox
  ErrorLog logs/netbox_ssl_error_log
  TransferLog logs/netbox_ssl_access_log
  LogLevel warn
  Include /etc/httpd/includes.d/ssl_cert.conf

  Alias /static /opt/netbox/netbox/static

  <Directory /opt/netbox/netbox/static>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Require all granted
  </Directory>

  <Location /static>
    ProxyPass !
  </Location>

  ProxyPass / http://127.0.0.1:8001/
  ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>
```

**Comment by jeremystretch** [comment]
I'm not able to replicate this, but I'm using nginx as a frontend. Can you inspect the AJAX request in the browser to determine if it's being redirected?

**Comment by dav3860** [comment]
I managed to fix it. I just added `RequestHeader set X-Forwarded-Proto "https"` to the Apache configuration and it started working.
