### ISSUE TITLE
debian need zlib1g-dev package installed

### ISSUE THREAD

**Issue by nshopik** [digitalocean/netbox#1130]
Debian need `zlib1g-dev` package on minimal system, this need to be updated in documentation for installation on debian/ubuntu. Otherwise build will fail durring `pip3 install -r requirements.txt`

**Python version:3.5.3**
**NetBox version:2.0 beta3**

```

    i686-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-wQ6Jnc/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format
-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.5/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lrt -lz -lm -o build/lib.linux-i686-3.5/lxml/etree.cpython-35m-i386-linux-gnu.so
    /usr/bin/ld: cannot find -lz 
```

**Comment by jeremystretch** [comment]
Can you please provide the steps necessary to reproduce this installation failure?

**Comment by nshopik** [comment]
Steps already in your documentation, I've just followed them on debian9 and had to install this package to make installation finish
http://netbox.readthedocs.io/en/stable/installation/netbox/
