### ISSUE TITLE
No filter option via v2 API on tenancy

### ISSUE THREAD

**Issue by marc-us** [digitalocean/netbox#1131]
### Issue type: No filter option in v2 API

**Python version: 3
**NetBox version: v2-develop

Hi,

Unfortunately there is filter options on some APIs:
affected APIs:
 - tenancy/tenant-group
 - Patially: tenanct/tenant 
 - dcim/regions

Would be good if somehow the filtering would be unified...
The q variable is fine if it would be everywhere. The slug is also an option, but not at every place is accessible.

**Comment by jeremystretch** [comment]
Please enumerate the specific changes you'd like to make.

**Comment by jeremystretch** [comment]
Still not sure what the intention was here; filtering is supported for the listed models. Closing due to lack of response.
