### ISSUE TITLE
Allow Custom Field on DCIM->Regions

### ISSUE THREAD

**Issue by rgrcnh** [digitalocean/netbox#1133]
Hi
I wish I have a custom field on dcim->regions, if it's possible.
Thanks!

**Comment by jeremystretch** [comment]
I try to avoid adding custom fields to secondary models. Just out of curiosity, what would you use them for?

**Comment by jeremystretch** [comment]
I really want to avoid enabling custom fields on any secondary models. Closing this out.

**Comment by rgrcnh** [comment]
We use for Regions a code pretty like IATA airports codes (LAX, JFK etc..). The description field is just for those people are note familiar with.
Thanks
