### ISSUE TITLE
Server Error - value too long 

### ISSUE THREAD

**Issue by podber** [digitalocean/netbox#1134]
### Issue type:
During IP address import server error occures

<class 'django.db.utils.DataError'>

value too long for type character varying(100)

Data in UTF-8 with RU symbols.

**Python version:**
Version: 2.7.3-4+deb7u1
**NetBox version:**
v1.9.5

**Comment by jeremystretch** [comment]
What was the data you tried to enter?

**Comment by podber** [comment]
f.e. 
IP Space->Import IPs

10.8.0.48/16,,,Active,,,,Синяев Денис Вячеславович "Оптик-Инжинирин" ЦЗЛ - аппаратная С2000 о-п сигнализация 89518070926

decstiption somehow exceeds "character varying(100)", but there is no warning.

**Comment by jeremystretch** [comment]
Ok, thanks. Just wanted to ensure that it wasn't some strange Unicode problem. Will need to fix the length validation.

**Comment by jeremystretch** [comment]
I'm able to import an IP address with the exact description you provided, no error. Looks like a database issue; check that your database encoding supports Unicode. If you need further help, please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
