### ISSUE TITLE
Filter devices by rack

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1137]
### Issue type: feature request

I would like to be able to do a bulk update of devices in a particular rack, e.g. to set a custom attribute.

However right now:

* If you browse devices, you can filter by Rack Group but not by Rack
* If you drill down to the Rack itself, it draws the racked devices and lists the unracked devices, but doesn't have a bulk update option (e.g. a tab to show Devices with checkboxes beside them)

I think the simplest solution is to add a new filter on the RHS of the Device page (`/dcim/devices/`) to filter on Rack  - this should include option `None` to see unracked devices.

**Comment by Armadill0** [comment]
As a workaround you can currently go to the rack and click on the devices count at the "devices" section. This leads to the following URL:
https://yournetbox/dcim/devices/?rack_id=<rackid>

You can also append the "rack_id" parameter to the already existing filter-parameters of the device page to manually filter devices for a specific rack, e.g.:
https://yournetbox/dcim/devices/?q=&role=server&status=&mac_address=&cf_legacy_hardware=&cf_serviceid=&rack_id=

**Comment by candlerb** [comment]
That works, thanks!  And I note you can select multiple racks with `&rack_id=X&rack_id=Y`

However, I'd still like the filter available in the UI.  It would be a lot easier to use.

**Comment by jeremystretch** [comment]
We should be able to make this work similar to the nested filters for manufacturer and device type on the devices list.
