### ISSUE TITLE
Bulk update of 'Serial Number' not useful?

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1138]
### Issue type: trivial cleanup

(1.9.6)

The Device bulk update page `/dcim/devices/edit/` currently allows you to set Serial Number *en masse*

Is there any use case for setting the same serial number on multiple devices? If not, this field can be removed.

**Comment by Armadill0** [comment]
At least setting them back to null could be useful.

Another, although doubtful, scenario could be to enter a common prefix part of the serial number which is the same for a set of new devices and only the last two or three characters are different.

**Comment by jeremystretch** [comment]
The `serial` field on the Device model doesn't have a unique constraint, so we allow editing it in bulk. It may not be terribly useful but it's not hurting anything. And if I were to remove it someone would inevitably open a feature request to have it restored anyway.

**Comment by candlerb** [comment]
Except you can currently bulk update serial number but not asset tag :-)

**Comment by jeremystretch** [comment]
The `asset_tag` field has a unique constraint, since it's assumed that asset tags for all devices will be issued by a single authority (as opposed to serial numbers which are issued by various manufacturers).
