### ISSUE TITLE
Cannot assign IP address to interface of unracked device

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1139]
### Issue type: bug report

**Python version:** 2.7.12 (Ubuntu 16.04)
**NetBox version:** 1.9.6

Since v1.9.0 (#198) it has been possible to have unracked devices.

However you are no longer able to assign an existing IP address to such a device.  To reproduce:

* Create a device assigned to site but no rack, and with at least one network interface
* Create an IP address
* Edit the IP address
* Under "Interface Assignment", try to assign this address to the device

You can select the site, but you are next forced to select the Rack, and there is no option for "None".  This means that you are then unable to select the Device.

![image](https://cloud.githubusercontent.com/assets/44789/25707520/ac5fb382-30db-11e7-822e-a26a6a255654.png)

Workaround: delete the IP address, navigate to device, add new IP address to interface (in this case the necessary IDs are embedded in the URL)

Possible solutions:

1. Add a new "None" option to the Rack filter; and/or

2. Add a new "Any" option to the Rack filter - which means that the Devices drop down will show all devices in the site.  (This is helpful if you can't remember what rack a device is in, but it may be a very big list for a large site)

**Comment by jeremystretch** [comment]
Seems like you ran into #1101. Fixed in the `develop` branch; will be included in v1.9.7.
