### ISSUE TITLE
ZTE ZXR10 VSC (Virtual Switch Cluster)

### ISSUE THREAD

**Issue by zhaknafein** [digitalocean/netbox#1140]
# Issue type: feature request
Since we are using this switches in our datacenter, i would like to add the stacking ports. They use a 40GB MiniSAS cable and the ports are shown as "xlgei" ("gei" for 1GB ports, "xgei" for 10GB ports).
ZTE calls the stacking technology VSC (Virtual Switch Cluster).
Is it possible to add this kind of ports as MiniSAS or under the Stacking group?
Thanks!

**Comment by jeremystretch** [comment]
Can you provide a link to documentation of the interface specification? I can't seem to find anything.

**Comment by zhaknafein** [comment]
I have only offline documentation available, i have attached the pages related to the stacking expansion module with the 40GB ports ([ZTE_59_2L_SK.pdf](https://github.com/digitalocean/netbox/files/987378/ZTE_59_2L_SK.pdf)) and VSC configuration ([ZTE_VSC.pdf](https://github.com/digitalocean/netbox/files/987379/ZTE_VSC.pdf)), let me know if you need further informations.

**Comment by jeremystretch** [comment]
Given that these use a standard mini-SAS form factor, we probably don't want to define it as something specific to ZTE. But we also don't currently define storage interfaces. I'll leave this open for comment for now.

**Comment by zhaknafein** [comment]
Maybe just adding the interface type like Juniper VCP would be enough?

**Comment by jeremystretch** [comment]
My point is that (as far as I can tell) this isn't a ZTE-proprietary form factor: it's a standard mini-SAS form factor. We don't want to add it as a ZTE-specific stacking form factor since it might be in use by other vendors for the same purpose.

**Comment by jeremystretch** [comment]
It feels like we're starting to abuse the concept of network interface with regard to stacking interfaces. These are really proprietary connections that should be treated a bit differently from normal interfaces. I'm going to hold off on adding any more stacking types until we at least have a better idea where #99 is headed.
