### ISSUE TITLE
Asset tag generator

### ISSUE THREAD

**Issue by quentinsch** [digitalocean/netbox#1142]
Would be nice if an asset tag could be generated from a pre defined pattern.
For example we use a range from SVR00000 to SVRFFFFFF as an asset tag for a server.
Also ranges should be excluded from generation (reserved ranges or already used tags).

**Comment by jeremystretch** [comment]
This seems pretty out-of-scope for NetBox.

**Comment by quentinsch** [comment]
Well, I thought it could be relevant for some people because Netbox should be used as a primary and leading tool for defining rackspace and their assets. So I thought it might be a good idea to let Netbox also be in charge of the (unique) asset numbering if people decide to use that.

**Comment by jeremystretch** [comment]
It's a neat idea, but not something we want to build into NetBox.
