### ISSUE TITLE
Migration Steps missing

### ISSUE THREAD

**Issue by claughinghouse** [digitalocean/netbox#1146]
### Issue type:
Missing documentation.

**NetBox version: All
Markup page is below. 

## Migration from one host to another

Dump the database by first `su` to postgres user on the current netbox server

```# sudo su - postgres
# pg_dump netbox > netbox_db.bak
```

Copy the netbox_db.bak file from `/var/lib/psql` directory to the new machine.

On the new machine initialize a new database and netbox user with the same database password as before.

```no-highlight
# sudo -u postgres psql
psql (9.3.13)
Type "help" for help.

postgres=# CREATE DATABASE netbox;
CREATE DATABASE
postgres=# CREATE USER netbox WITH PASSWORD 'J5brHrAXFLQSif0K';
CREATE ROLE
postgres=# GRANT ALL PRIVILEGES ON DATABASE netbox TO netbox;
GRANT
postgres=# \q
```

You can verify that authentication works issuing the following command and providing the configured password:

```no-highlight
# psql -U netbox -h localhost -W
```

If successful, you will enter a postgres prompt. Type `\q` to exit.

Copy the netbox_db.bak file on the new to host to `/var/lib/pgsql`

Become the user and import the database

```# sudo su - postgres
# pg_dump netbox < netbox_db.bak
```

**Comment by jeremystretch** [comment]
You're describing the process of replicating a PostgreSQL database, which is well-defined elsewhere and is not specific to NetBox. There's no reason to include it in our documentation.
