### ISSUE TITLE
Administrative statuses for interfaces

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#1147]
### Issue type: feature request

Devices currently have a set of administrative statuses (active, offline, et. al. via recent commit). I use this plus a custom field to denote whether or not a device should be monitored (via a 3rd party system). I would like this same functionality for interfaces. I see these administrative states being immediately applicable to interfaces:

- Up (default)
- Down (disabled)
- Provisioned (configured but not in production)
- Reserved
- Deprecated

I would also like to ability to identify an interface as being in a monitored state. Without the use of custom fields, that may fall under #1041?

Overall I am not sure if this all falls under #1041 or should be treated as new request?

**Comment by jeremystretch** [comment]
I'd like to implement administrative state as just enabled or disabled. That maps cleanly to configured state on a device. The other states can be somewhat inferred by the connection state.

**Comment by jeremystretch** [comment]
Let's wrap this into #1041 since it looks like both will be implemented at the same time.
