### ISSUE TITLE
Python Error : deprecated function django.core.context_processors

### ISSUE THREAD

**Issue by salt-lick** [digitalocean/netbox#115]
``` /usr/lib64/python2.7/importlib/__init__.py:37: RemovedInDjango110Warning: django.core.context_processors is deprecated in favor of django.template.context_processors.
   __import__(name)```

Received error in the gunicorn logs.

**Comment by jeremystretch** [comment]
I believe this is related to [django-tales2](https://github.com/bradleyayers/django-tables2/issues/314). I've held off on upgrading to 1.2.2 because there seems to be some weird performance issue with it.

**Comment by jeremystretch** [comment]
Had this confused with a different issue. This is not related to django-tables2.
