### ISSUE TITLE
Can't upload image with unicode chars in name

### ISSUE THREAD

**Issue by tkald** [digitalocean/netbox#1150]
### Issue type: bug

**Python version:** 2.7
**NetBox version:** 2.0

Trying to upload device image with name "jõulukuusk.jpg" and gettin an error:
> <type 'exceptions.UnicodeEncodeError'>
> 'ascii' codec can't encode character u'\xf5' in position 1: ordinal not in range(128)

No issues with images containing plain ascii chararacters...

**Comment by jeremystretch** [comment]
This is due to `image_upload()` returning the file path as a string rather than Unicode under Python 2. (Python 3 is unaffected.)
