### ISSUE TITLE
name 'escape' is not defined

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1151]
### Issue type: Bug report

**Python version:** 3.4.3
**NetBox version:** 2.0.0

When creating or removing a console, power, or interface connection, the server may yield the following error:

```
NameError at /dcim/console-ports/<pk>/disconnect/

name 'escape' is not defined
```

This is due to the erroneous deletion of an import statement when the `v2-beta` branch was merged with the `develop` branch.

**Comment by elJoeyJojo** [comment]
hello,

i keep getting this issue when i remove connections from switch to switch. how can i fix this?

Thanks
