### ISSUE TITLE
Server error when try to search in language other than english

### ISSUE THREAD

**Issue by MikeGoltsov** [digitalocean/netbox#1153]
Issue type: Bug

Python version: 2.7.5
NetBox version: v2.0.0-release

When I try to search something in language other than english (i.e. russian), if object exist - I get server error.
If object not exist - all ok, No results found.

Server Error
There was a problem with your request. This error has been logged and administrative staff have been notified. Please return to the home page and try again.
If you are responsible for this installation, please consider filing a bug report. Additional information is provided below:
<type 'exceptions.UnicodeEncodeError'>
'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Home Page

**Comment by jeremystretch** [comment]
This is caused by the improper formation of the "more results" URL (which isn't always displayed). Easy fix. Thanks for reporting the bug!
