### ISSUE TITLE
Upgrade with docker

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#1155]
Hi,

When I wanted to upgrade the lastest version with docker the configuration docker file has been deleted (docker-compose.yml)

I can't run docker-compose build --no-cache now : 
```
root@Docker:~/netbox# docker-compose up -d
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

Thanks for your help

Regards,

Thomas V.

**Comment by cimnine** [comment]
The Docker things have moved to https://github.com/digitalocean/netbox-docker, but there's not yet a v2 release available.
