### ISSUE TITLE
Navigation Cutoff

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#1157]
If a users username is too long, the search field within the navigation bar is shifted down, causing the navigation bars element to overlap the pages content; this blocks any subnavigation controls on the page.
<img width="1270" alt="screen shot 2017-05-10 at 9 42 32 am" src="https://cloud.githubusercontent.com/assets/20648781/25901614/461f9cf2-3565-11e7-93f5-357837b27291.png">
<img width="1266" alt="screen shot 2017-05-10 at 9 42 58 am" src="https://cloud.githubusercontent.com/assets/20648781/25901618/48a756fe-3565-11e7-99eb-a2b8fd06e737.png">

**Comment by jeremystretch** [comment]
@swickstrom How wide is the browser viewport when this happens?

**Comment by t0i** [comment]
You can reproduce this issue on the Racks view easily. Open it up and shrink the window (drag the edge) until the Search bar is moved down to a new line, at that point the "Add rack"/"Import racks"/"Export racks" button is hidden under the new search bar location.
