### ISSUE TITLE
Unable to edit IP under connections unless you are a superuser.

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1159]
When trying to edit the IP address attached to a connection doesn't show the edit button, unless you have the superuser rights?

Am I missing something?

Which permission should I enable for a user to allow this?

**Comment by jeremystretch** [comment]
The button is displayed if the user has the permission "IPAM > IP address > Can add IP address."

**Comment by InsaneSplash** [comment]
OK. This is enabled for the group and was working prior to the update to version 2.0.1.
Maybe this permission is no longer being picked up?

**Comment by jeremystretch** [comment]
I've created a new user and assigned it the permission, and the button shows up as expected under 2.0.1 when logged in as that user.

**Comment by InsaneSplash** [comment]
Its the editing of the IP address which I am unable to do. One can add an address to an interface, but once its added, you can only remove it, not edit it.

eg: the blue pencil edit button is not displayed.

![image](https://cloud.githubusercontent.com/assets/16985649/25917470/788c484e-35c8-11e7-87e8-4b25eb591de2.png)

**Comment by jeremystretch** [comment]
Apologies, I was focusing on the "add" button. Yep, the permission is incorrectly named in the template.

**Comment by InsaneSplash** [comment]
awesome thanks!
