### ISSUE TITLE
Enable creation of QinQ VLANs

### ISSUE THREAD

**Issue by markve-sa** [digitalocean/netbox#116]
Ability to add SVLANs and CVLANs. Perhaps a parent child relationship

This and #105 and my life is complete

**Comment by jeremystretch** [comment]
This has been open for a long time with no movement. Unfortunately, this seems to be a very niche feature that probably doesn't justify the complexity it would introduce. I'm going to close this feature request.

**Comment by cre8rnz** [comment]
Any chance we can reopen this? 802.1ad is being used more and more...
We have to use VRFs for IPs and VLAN Groups to do this currently and it makes things a tad messy for us.
Not sure how complex it would be to effectively duplicate the VLAN functions, Call it ServiceTAG and add a new column for ServiceTAG under vlans?

**Comment by OsirisS13** [comment]
Another vote for re-opening this issue, Netbox is a great product for tracking enterprise level infrastructure and networks, but the addition of being able to represent 802.1ad will increase its usefulness in the service provider realm

**Comment by benmcnix** [comment]
+1 for reopening. Tagging cVLAN/sVLAN separately would make for tracking DSL / Fiber equipment and outside plant infrastructure easier.

**Comment by ruben-herold** [comment]
+1 for reopening

**Comment by netfreak98** [comment]
+1 for reopening
