### ISSUE TITLE
Search results for Tenants doesn't provide hyperlink to tenant's page

### ISSUE THREAD

**Issue by t0i** [digitalocean/netbox#1160]
### Issue type: Search results for Tenants doesn't provide hyperlink to tenant's page

**Python version:** 2.7
**NetBox version:** 2.0.1

![image](https://cloud.githubusercontent.com/assets/6345150/25911274/135e1070-3568-11e7-9fcf-01cb107b2f13.png)

The tenant results should be also be a hyperlink to that tenant page.

**Comment by jeremystretch** [comment]
Same issue with secrets.
