### ISSUE TITLE
Bulk add IP address with tenant fails

### ISSUE THREAD

**Issue by irishredbeard** [digitalocean/netbox#1166]
Trying to bulk add IP addresses within the IPAM

### Issue type:  
Bug

### Versions of stuff
* Python version:2.7.12
* NetBox version:v1.9.6
* OS: Ubuntu 16.04.2 LTS

### Installation
Installed via quick start [installation instructions](http://netbox.readthedocs.io/en/stable/installation/postgresql/)

### Steps to reproduce
<img width="529" alt="bulk_add1" src="https://cloud.githubusercontent.com/assets/28629008/25957353/21c9948e-363c-11e7-8420-4d8491e8b444.png">
<img width="539" alt="bulk_add2" src="https://cloud.githubusercontent.com/assets/28629008/25957354/21cda93e-363c-11e7-8c09-6b67b447275d.png">

From UI:
1. IP Space
1. IP address
1. Add an IP
1. Bulk
   1.  Address pattern: I have tried multiple patterns and all react same way
   1. VRF: Global
   1. Tenant: Irishredbeard
   1. Status: DHCP or Active
   1. Description

These steps fail with the error below. See attachment for screen shot. 
`<type 'exceptions.ValueError'>
The IPAddress could not be created because the data didn't validate.
`
<img width="348" alt="server-err" src="https://cloud.githubusercontent.com/assets/28629008/25956663/55467b4e-363a-11e7-955c-c07cd7f48b0b.png">

### Work around
1. Follow exact same steps as above but leave tenant field blank
1. Once all addresses have been added go back into IP space, bulk edit the newly added addresses and add tenant

**Comment by jeremystretch** [comment]
Looks related to #1103. Could you try upgrading to v2.0.1 and seeing the problem recurs? This may still be a separate bug but the fix from #1103 should at least return a proper validation error.

**Comment by irishredbeard** [comment]
Hey Jeremy,
Now running on v2.0.1. Same result but a different error is returned. 

<img width="619" alt="screen shot 2017-05-12 at 09 30 19" src="https://cloud.githubusercontent.com/assets/28629008/26000143/cdc0765e-36f5-11e7-9607-342c0637c207.png">

Work around still works in that I can simply remove the tenant and add the IP addresses in bulk.
