### ISSUE TITLE
Topology maps text color vs background

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#1179]
### Issue type: bug

**Python version:** 2.0.1
**NetBox version:** 2.7.11

I am not sure how much flexibility there is in the rendering of topology maps but when a device role is set to black, the text is not legible at the moment. It would be nice to set the text to white when a role is black. 

![screen shot 2017-05-15 at 11 18 49 am](https://cloud.githubusercontent.com/assets/1297132/26065277/68419312-3961-11e7-8f1c-90b413ead32c.png)

**Comment by jeremystretch** [comment]
There's actually a somewhat involved function for determining whether the ideal foreground color fir a given background color is white or black, I just haven't gotten around to implementing it: http://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color
