### ISSUE TITLE
New matching case for related devices UI

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#1180]
### Issue type:  feature request

There was some discussion on the networktocode slack the other day about how related devices are correlated. I know @jeremystretch mentioned wanting revisit this in a larger fashion but I was wondering if you would be open to adding one more case for matching in the mean time. 

This stems from the way I am currently representing switch stacks in netbox. Each member of the stack is named like so: `Access-Stack-1F--RE-N1`. In this scheme, `Access-Stack-1F` is the name of the stack and this node's role is `RE` and it is node 1 in the stack. This is denoted after the delimiter `--`. 

I really like the related devices feature but it obviously cannot match all members of a stack in this case when we factor in multiple roles (RE, LC, etc). Would it be possible to add a case to match anything up to a delimiter of `--`?

**Comment by jeremystretch** [comment]
The current approach of looking for devices with similar names was a "good enough" hack for when it was implemented. It should really be replaced with something more robust, but I don't have anything in mind.

**Comment by lampwins** [comment]
Coincidentally I ran across the python built in `difflib` library in some other work today. It immediately struck me a possible solution to this. Among other things, it can be used to calculate a percentile difference in two string. So for instance, you could say something two device names that are >=90% similar are related. http://stackoverflow.com/questions/17388213/find-the-similarity-percent-between-two-strings

**Comment by jeremystretch** [comment]
It's one way to go. We'd have to pull in the names from all devices from the database and then do the matching in Python, but that might not be too bad if we limit it to devices assigned to the same site.

**Comment by jeremystretch** [comment]
`difflib` has some really neat logic, but after some experimentation it can sometimes return very unexpected results. Probably best to keep things simple and just return a truncated list of devices in the same site with the same role.
