### ISSUE TITLE
Ordering of global search results

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1189]
### Issue type:

Feature request

This is a very minor suggestion!

The new global search facility (#159) is superb. However at the moment if you search for an individual IP address you get the results in the following order:

* Prefixes
* Aggregates
* IP Addresses

I think it would be more user-friendly to display from more specific match to less specific, which would be:

* IP Addresses
* Prefixes
* Aggregates

Additional suggestion: make the drop-down menu of object types arranged in the same order as the search results are displayed, for consistency.

**Comment by candlerb** [comment]
A related display issue:

Searching for device via global search doesn't show its IP address in the results listing, but searching via devices page does.

Results from global search:

![image](https://cloud.githubusercontent.com/assets/44789/26146908/b474bcc6-3ae9-11e7-9806-574f4c466aec.png)

Results from search under `/dcim/devices/`

![image](https://cloud.githubusercontent.com/assets/44789/26146934/cbe48a4e-3ae9-11e7-822e-9c87099e9bc4.png)

It would be nice if the global search results had the same columns as the specific searches.

**Comment by jeremystretch** [comment]
The order of objects returned from a global search is currently not enforced. I'll change this to an OrderedDict to ensure consistency.

> Searching for device via global search doesn't show its IP address in the results listing, but searching via devices page does.

We avoid pulling in too many related objects due to the breadth of the current global search implementation. For example, we also don't calculate rack utilization.
