### ISSUE TITLE
Bulk editing IPs within a prefix does not correctly filter "select all"

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1191]
I tried to update the description for a single prefix, and selected the all 200 IP addresses. When I checked after the change, it had updated all IP addresses in the system with the same description.

**Comment by jeremystretch** [comment]
> I tried to update the description for a single prefix, and selected the all 200 IP addresses.

This doesn't make sense. There is no mechanism to select IP addresses when you are editing a prefix. It sounds like you were editing IP addresses in bulk (at /ipam/ip-addresses/edit/), in which case this is intended behavior.

**Comment by InsaneSplash** [comment]
For example:
When viewing the IP Addresses allocated within a prefix 192.168.0.0/24, you have the option to select individually the IP Addresses you would like make changes to. If you select the top edit box, it will ask you if you would like to extend the selection to all IP's within the prefix you are working with and it presents a total number, ie 200. On choosing to expand your selection to the 200 IP addresses (ie more than 1 page worth) the system now selects ALL IP's within the system, unlike its previous behaviour of limiting the selection to the prefix you were working in.

**Comment by InsaneSplash** [comment]
![image](https://cloud.githubusercontent.com/assets/16985649/26157198/e32c333a-3b18-11e7-9de1-8f5429b0fbb2.png)

then

![image](https://cloud.githubusercontent.com/assets/16985649/26157228/03129c3e-3b19-11e7-9070-c766d2becff6.png)

**Comment by jeremystretch** [comment]
I'm not following. Please detail the exact steps needed to recreate this.

**Comment by InsaneSplash** [comment]
IP Prefixes --> 100.64.0.0/10 --> 100.64.4.0/16 --> 100.64.4.0/24 -- IP Addresses -- Select block next to heading "IP Address"

Refer to above screen captures from this point.
