### ISSUE TITLE
Unable to create an interface connection when searching for peer device

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1195]
### Issue type: Bug report

**Python version:** 3.4.3
**NetBox version:** 2.0.2

To reproduce:

1. Go to a device and click the "Connect" button
2. Search for and select a peer device, and select one of its interfaces
3. Submit the form
4. The form will be returned with no obvious errors. Click the "Select" tab and there will be an error assigned to the Device field:

> Select a valid choice. That choice is not one of the available choices.

This error does not occur when selecting a device using the dropdowns under the "Select" tab instead of searching for a device by name.

**Comment by phurrelmann** [comment]
I'm facing the same issue, but an error is shown:

**Comment by jeremystretch** [comment]
@phurrelmann This seems to happen only after submitting the form a second time.
