### ISSUE TITLE
Unable to create PDU outlet connections

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#1200]
When attempting to connect PDU outlets to devices I receive the following error message:
<img width="602" alt="screen shot 2017-05-18 at 9 52 38 am" src="https://cloud.githubusercontent.com/assets/20648781/26205794/d408d9ec-3bb0-11e7-8889-80c4cc5964bd.png">
This occurs with either the Search or Select method of connection creation.
After selecting/searching for the PDU I am presented with the available outlets, after selecting the one I want to connect and hitting the Connect button I am presented with that error and can no longer view the available outlets.
I have forcibly refreshed the page, cleared my browsers cache, attempted the connection in both Chrome and Safari and have had no luck.

**Comment by jeremystretch** [comment]
Please indicate the versions of Python and NetBox that you are running.

**Comment by swickstrom** [comment]
Netbox: v2.0.2
Python: v2.7.6
