### ISSUE TITLE
Allow to add child module interface to parent device LAG

### ISSUE THREAD

**Issue by zhaknafein** [digitalocean/netbox#1205]
### Issue Type: Feature Request

_Scenario:_ Cisco Catalyst 6500 with chassis as parent device, 2 x 24 ports SFP interface modules as children devices. There is a PortChannel configured with one port on each SFP module (say Gig1/1 and Gig2/1).

If i create a LAG interface on one module, i can only add its interfaces in it, the other module doesn't see the LAG.

It would be nice if i could create the LAG interface on the parent device (the chassis) and be able to add the children modules' interfaces to it.

This would also probably work for stacking devices where i can create the stack as a "virtual" device, with the physical units as children devices (let's say 2 Catalyst 3750).

**Comment by jeremystretch** [comment]
It sounds like you're using device bays to represent line cards. Device bays only hold child devices, which have their own control planes and thus cannot share interfaces among them (like blade servers within a chassis).

#824 has been opened to add the concept of a modular line card within a chassis, to which interfaces can be attached, but for now just create the interfaces on the chassis device. (Line cards can still be tracked for inventory purposes as InventoryItems.)
