### ISSUE TITLE
Expand installation docs to support Debian Jessie

### ISSUE THREAD

**Issue by XioNoX** [digitalocean/netbox#1208]
### Issue type: Initial setup issues
**Python version: 2.7**
**NetBox version: master/2.0.3**
**Debian GNU/Linux 8**

The initial setup of netbox on a test Debian Jessie server was a bit bumpy, here are the errors and how I worked around them, probably not in the most optimal way.

Error:
> unable to execute 'x86_64-linux-gnu-gcc': No such file or directory

FIx: 
> apt-get install build-essential

During pip install -r requirements.txt:

Error:
> The headers or library files could not be found for jpeg, a required dependency when compiling Pillow from source.

Fix:
> apt install libjpeg62-turbo-dev

Error:
> ImportError: No module named pyparsing

Fix:
> apt-get install python-pyparsing

(as pip can't run without pyparsing)

Error:
> ImportError: No module named appdirs

Fix:
> sudo apt-get install python-appdirs
as pip can't run without appsdir, then

> pip install -U appdirs

As pip requires a most recent version.

During: ./manage.py migrate

Error:
> ImportError: xxxxx

Fix:
> pip install pytz coreapi openapi_codec simplejson
> apt-get install python-pysasn1
> (pip install returns No distributions at all found for pysasn1)

**Comment by Armadill0** [comment]
Will be fixed with #1209.

**Comment by jeremystretch** [comment]
Do the proposed changes break the installation of NetBox on Debian 7?

**Comment by dmitrijsf** [comment]
On top of these steps, I needed to `pip install itypes coreschema uritemplate` in order for `./manage.py migrate` to succeed.

Python 2.7.9
NetBox version: master/2.0.3
Debian GNU/Linux 8

**Comment by jeremystretch** [comment]
Since the Debian installation appears to vary quite a bit, I'm going to constrain the installation documentation to only Ubuntu and CentOS. I don't want to start maintaining unique installation instructions for every major distribution.

If anyone is interested in maintaining an independent Debian installation doc, I'd be happy to link to it.

**Comment by doublemt** [comment]
Hi you might also run into that error:

ImportError: No module named django.core.management when using manage.py
FIX : python3 manage.py migrate
