### ISSUE TITLE
Enable to connect two ports

### ISSUE THREAD

**Issue by mdomore** [digitalocean/netbox#1217]
### Issue type: bug report

**Python version: 2.7**
**NetBox version: v2.0.2**

I have 2 device with each one a port of the same type 1G Base-T, i try to connect them and i have an error message 

<class 'django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist'>

InterfaceConnection has no interface_b.

**Comment by jeremystretch** [comment]
Sounds like #1195. Please upgrade to v2.0.3. If you are still encountering the issue when running v2.0.3 I'll reopen this issue.
