### ISSUE TITLE
Add form factors for wireless interfaces

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1218]
Would there be a consideration for a Wireless Interface within the interface list?

Could always use 802.11b/g/n and 802.11/ac

**Comment by jeremystretch** [comment]
Can you post an explicit list of interface form factors that you'd like to add?

**Comment by InsaneSplash** [comment]
I'd say the following covers the most popular standard wireless interfaces. They are the most common types within the IEEE 802.11 standard.

- 802.11a
- 802.11b/g/n
- 802.11ac
- 802.11ad

**Comment by jeremystretch** [comment]
Implemented in 68ebe85a98528b6db0582b0fc49de968dbd6198b
