### ISSUE TITLE
Supervisor and gunicorn install fails v2.0.3

### ISSUE THREAD

**Issue by vPackets** [digitalocean/netbox#1221]
Issue type: Bug report

Python version: 3.x
NetBox version: 2.0.3
OS: Ubuntu 16.04-2
`nicolas@srv-ubuntu-01:/opt/netbox$ uname -a
Linux srv-ubuntu-01 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

After docs has been rightfully followed,the installation of gunicorn and supervisor failed.

`nicolas@srv-ubuntu-01:/opt/netbox$ sudo apt-get install -y gunicorn supervisor
Reading package lists... Done
Building dependency tree
Reading state information... Done
gunicorn is already the newest version (19.4.5-1ubuntu1).
supervisor is already the newest version (3.2.0-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
6 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up python-pkg-resources (20.7.0-1) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-pkg-resources (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of python-setuptools:
 python-setuptools depends on python-pkg-resources (= 20.7.0-1); however:
  Package python-pkg-resources is not configured yet.

dpkg: error processing package python-setuptools (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python-gunicorn:
 python-gunicorn depends on python-pkg-resources; however:
  Package python-pkg-resources is not configured yet.
 python-gunicorn depends on python-setuptools; however:
  Package python-setuptools is not configured yet.

dpkg: error processing package python-gunicorn (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gunicorn:
 gunicorn depends on python-gunicorn (= 19.4.5-1ubuntu1); however:
  Package python-gunicorn is not configured yet.
 gunicorn depends on python-pkg-resources; however:
  Package python-pkg-resources is not configured yet.
 gunicorn depends on python-setuptools; however:
  Package python-setuptools is not confNo apport report written because the error message indicates its a followup error from a previous failure.
          No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                                    No apport report written because MaxReports is reached already
                                           igured yet.

dpkg: error processing package gunicorn (--configure):
 dependency problems - leaving unconfigured
Setting up python-meld3 (1.0.2-2) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-meld3 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of supervisor:No apport report written because MaxReports is reached already

 supervisor depends on python-meld3; however:
  Package python-meld3 is not configured yet.
 supervisor depends on python-pkg-resources; however:
  Package python-pkg-resources is not configured yet.

dpkg: error processing package supervisor (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              Errors were encountered while processing:
 python-pkg-resources
 python-setuptools
 python-gunicorn
 gunicorn
 python-meld3
 supervisor
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by KimmoJ** [comment]
Why was this closed without an answer? Because I'm seeing this exact behavior on Ubuntu 16.04. Solved it? if so, how?

**Comment by vPackets** [comment]
Netbox team said that it was not related to net box but to ubuntu … I reinstalled the whole server and then it worked ….

Not sure why /shrug.

Nic


On June 8, 2017 at 2:26:54 AM, KimmoJ (notifications@github.com) wrote:

Why was this closed without an answer? Because I'm seeing this exact behavior on Ubuntu 16.04. Solved it? if so, how?
