### ISSUE TITLE
Support Creating Custom Fields via the API

### ISSUE THREAD

**Issue by DerekTBrown** [digitalocean/netbox#1224]
I am creating an application which requires the use of several custom fields within NetBox.  It would be nice to be able to automate the creation of these custom fields upon installation.  Could this be added to the v2 API?

**Comment by jeremystretch** [comment]
The creation or modification of custom fields is analogous to modifying the database schema and should only be done with great care. It should also be a very infrequent operation. As such, I believe it's appropriate to restrict control over custom fields to the admin UI.

**Comment by DerekTBrown** [comment]
From an application design perspective, this is very limiting.  I have to ask my users to go into the NetBox panel and add these custom fields (there are a fair number) manually, as opposed to just verifying they exist on installation.

**Comment by jeremystretch** [comment]
If this is just for deployment purposes, you're probably better off scripting out the creation of custom fields using the Django shell (`./manage.py shell`). For example, to create a custom text field for devices:

```python
from django.contrib.contenttypes.models import ContentType
from dcim.models import Device
from extras.models import CF_TYPE_TEXT, CustomField

new_field = CustomField(type=CF_TYPE_TEXT, name='my_field', description='My custom field')
new_field.save()

content_type = content_type=ContentType.objects.get_for_model(Device)
new_field.obj_type.add(content_type)
```

**Comment by DerekTBrown** [comment]
@jeremystretch out of curiosity- is it possible to do the same thing with creating API Tokens?

**Comment by jeremystretch** [comment]
It's possible to do that with everything in NetBox; it's just the built-in Django shell. At some point I'd like to document it within the context of NetBox, but I want to develop a wrapper that preloads everything for convenience first.

Anyway, here's an example for creating tokens:

```python
from django.contrib.auth.models import User
from users.models import Token

usernames = ['tom', 'dick', 'harry']
for name in usernames:
    try:
        # Keys will be generated randomly if not specified
        t = Token(user=User.objects.get(username=name))
        t.save()
        print("Created token {} for {}".format(t.key, t.user))
    except User.DoesNotExist:
        print("User {} not found!")
```

Does this approach work for you as a substitute for extending the API?

**Comment by DerekTBrown** [comment]
Its good enough for automated testing, which was the real need.  It would definitely be a nicety in the future to automate other installations as well.

**Comment by DerekTBrown** [comment]
@jeremystretch just for future use, the code block for making custom fields needs to verify the custom field doesn't already exist
