### ISSUE TITLE
Exception thrown after updating custom field via API

### ISSUE THREAD

**Issue by patrickfish** [digitalocean/netbox#1226]
### Issue type: Bug report

**Python version:** 2.7.9
**NetBox version:** 2.0.3

1. Create custom field (I used a boolean) tied to dcim > site
2. Do a PUT/POST against a site writing to that custom field, example:
```
{
  "name": "206",
  "slug": "206",
  "custom_fields":{"anira_ready":true}
}
```
3. Attempt to load the site via web browser: $netbox/dcim/sites/206/

Error is:
```
<type 'exceptions.ValueError'>

invalid literal for int() with base 10: 'True'
```

**Comment by jeremystretch** [comment]
This is happening because custom field values are not being properly serialized when entered via the API.
