### ISSUE TITLE
Import Devices allows overlapping rack positions instead of erroring

### ISSUE THREAD

**Issue by HumanEquivalentUnit** [digitalocean/netbox#1232]
### Issue type: bug report

**Python version: 2.7.5 (CentOS 7 default)**
**NetBox version: 2.0.3**

 - I configured a device type (HP ProLiant Server) as a 2U device.
 - Imported devices, entered three lines of CSV data, putting them in rack positions 17, 16, 15 (clash!)
 - The import succeeded without errors, and then looking at the rack nothing was rendered in those U positions at all - the imported devices were invisible.

This was a mistake, the servers are actually 1U, and I corrected the device type to 1U and that fixed it, they rendered in the right places.

Expectation: the import would fail because the devices would overlap with each other. Or the rack would render with an error visible in the double-assigned U positions.

**Comment by jeremystretch** [comment]
This is occurring because validation is being performed on each imported device in bulk _before_ the devices are actually created. The bulk import logic is being overwritten in #655, which should resolve this bug once it's completed. Leaving this open for reference.

**Comment by jeremystretch** [comment]
This should no longer happen with the new per-object validation implemented as part of #655.
