### ISSUE TITLE
Non-superuser cannot edit/delete inventory items under device

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1235]
### Issue type: bug
**Python version: 2.7.12**
**NetBox version: 2.0.4**

If a normal user tried to edit or delete an inventory item within a device, they are not provided with the edit or delete buttons. Access has been grated through the admin permissions group for the user to add/edit/delete however they are only allowed to add. If you have admin permissions you are able to make all the relevant changes. This bug was also reported and resolved previously for managing IP's linked to interfaces.

![missing options](https://cloud.githubusercontent.com/assets/16985649/26575458/9ea0e3c0-4525-11e7-98ad-52c9760074ff.png)

**Comment by jeremystretch** [comment]
Typo in the permission name in the template

**Comment by InsaneSplash** [comment]
Thanks!
