### ISSUE TITLE
HTTP 500 when adding a VLAN Group with Site via API

### ISSUE THREAD

**Issue by MattBurgess** [digitalocean/netbox#1239]
### Issue type: bug report

**Python version:** 2.7.5
**NetBox version:** 2.0.4

Adding a VLAN Group via the API works fine, so long as I don't specify a 'site':

`curl -X POST -H "Authorization: Token $token" -H "Content-Type: application/json" -H "Accept: application/json; indent=4" http://$netbox_host/api/ipam/vlan-groups/ --data '{"name": "VG1", "slug": "vg1"}'`

However, if I specify a site ID in the data payload, I get an HTTP 500 error back:

`curl -X POST -H "Authorization: Token $token" -H "Content-Type: application/json" -H "Accept: application/json; indent=4" http://$netbox_host/api/ipam/vlan-groups/ --data '{"name": "VG1", "slug": "vg1", "site": "19"}'`

The error message is:

`<pre><strong>&lt;class &#39;django.core.exceptions.FieldError&#39;&gt;</strong><br />
Cannot resolve keyword &#39;slug&#39; into field. Choices are: created, custom_field_values, description, group, group_id, id, last_updated, name, prefixes, role, role_id, site, site_id, status, tenant, tenant_id, vid</pre>`

**Comment by lampwins** [comment]
You are passing the site ID as the `site` parameter which is expecting a slug. You need to pass your ID in the `site_id` parameter.

**Comment by jeremystretch** [comment]
@lampwins You may be thinking of the filters, where `site` takes a slug and `site_id` takes a primary key. The API calls @MattBurgess posted are both correct.

There's a bug in the [serializer validation](https://github.com/digitalocean/netbox/blob/develop/netbox/ipam/api/serializers.py#L135) that's preventing a VLANGroup from being created if a site is assigned.
