### ISSUE TITLE
TypeError when navigating site

### ISSUE THREAD

**Issue by nicke94** [digitalocean/netbox#1242]
### Issue type: bug report

**Python version:** 2.7.12
**NetBox version:** 2.0.3

LDAP Users have to be a Superuser to be able to navigate away from the homepage without getting a TypeError

**Steps to replicate:**
* Login with non superuser account that is in active and staff group
* Try to go to any link on homepage and get a TypeError
* Add user to LDAP Superuser group in the LDAP database
* Relogin user
* User is now able to access the entire site

**Example error:**

Exception Type: TypeError at /dcim/sites/
Exception Value: format requires a mapping
Exception Location:	/usr/local/lib/python2.7/dist-packages/django_auth_ldap/config.py in execute, line 163

**Comment by jeremystretch** [comment]
This looks like a bug in [django-auth-ldap](https://github.com/almet/django-auth-ldap). Try upgrading your installed version of the package, or raise a bug against that project.
