### ISSUE TITLE
Sorting the interfaces.

### ISSUE THREAD

**Issue by arraisfilho** [digitalocean/netbox#1247]
### Issue type: Sorting the interfaces (Devices / Device Types / Interfaces)

**Python version: 2.7.12**
**Python3 version:  3.5.2**
**NetBox version:2.0.4**

The ordering of the interfaces does not seem to sort by the name, in an attached image where we have interfaces with the name ether [1-10] and sfp1, see that the sfp is between the interfaces ether, I believe that it should obey the alphabetical ordering.

http://i.imgur.com/QOfML4w.png

Is there a parameter we can adjust or would it be a bug?

**Comment by jeremystretch** [comment]
Interface ordering is configurable on the device type. Interfaces can be sorted by position (the default) or alphabetically.

**Comment by arraisfilho** [comment]
Hello,

I found the option, thank you!
