### ISSUE TITLE
Lack of space validation for object placement on rear of rack

### ISSUE THREAD

**Issue by zevlag** [digitalocean/netbox#1248]
### Issue type: Bug

When I browse to a particular rack, I get this error:

http://netbox/dcim/racks/29/
```
<type 'exceptions.KeyError'>

28
```
![screenshot 2017-06-07 11 18 03](https://user-images.githubusercontent.com/7240045/26891664-0e056580-4b73-11e7-9ef1-6e059a68836c.png)

**Python version:** 2.7
**NetBox version:** (v2.0.5-dev)

**Comment by jeremystretch** [comment]
Not much to go on. Please set `debug=True` in configuration.py and try again, then post the full stack trace.

**Comment by zevlag** [comment]
The traceback is posted here:
http://dpaste.com/0YKTEV5

**Comment by zevlag** [comment]
By looking at the database I was able to determine what happened.  Let's see if I can explain it clearly.

If I start with a rack that looks like this:
![screenshot 2017-06-07 11 45 13](https://user-images.githubusercontent.com/7240045/26893044-6c7b977a-4b77-11e7-939f-d8be9b9c3728.png)

You will notice that the rear of the rack U27 is open.  Front of the rack, U27/28 is available.

If I place an object that is 2U on the Rear of the rack then  I get this error when viewing the rack.  Obviously there is an overlap.

Netbox doesn't validate there is sufficient space to place an object.

**Comment by zevlag** [comment]
Looking into this further, it appears that the list of available RU doesn't change when switching between Front/Back.  Netbox does give an error if I try to place 2RU item at U28 on the front.

**Comment by jeremystretch** [comment]
I haven't been able to replicate this. I created a rack and installed a half-depth 1U device in the rear of U28 just like your example. When I try to add a 2U device to U27 (front or rear), NetBox returns the following validation error as expected:

> U27 is already occupied or does not have sufficient space to accommodate a(n) 2U Box (2U)

I can mount a 2U box on the front of U27/28 only if the device type is half-depth.

Could you try replicating it from scratch (as opposed to starting with an already populated rack)? Please be sure to list the exact steps needed to reproduce the error from scratch, including the height and depth of devices you install.

**Comment by zevlag** [comment]
::sigh::

I can't reproduce it at the moment.  Let me restore a database backup to the state it was in before and see what I can do.

**Comment by jeremystretch** [comment]
@zevlag Maybe you installed a half-depth device and then changed its device type to be full-depth? I tried that and it doesn't raise a validation error (something that I might need to fix) but it also didn't generate a server error like you saw.

**Comment by jeremystretch** [comment]
Closing this out for now as we haven't been able to replicate the behavior. It may still be around, though.
