### ISSUE TITLE
Enable fuzzy search 

### ISSUE THREAD

**Issue by croax** [digitalocean/netbox#1252]
Been going through other issues/feature requests and I can't see that this has been mentioned at all. Is it possible to get fuzzy search / wildcard search working? Something along the lines of searching for 10.4.* would show all objects that include 10.4 - it's impossible to use the IPAM search now without knowing exactly what you're looking for - which isn't always the case...

**Comment by croax** [comment]
https://github.com/digitalocean/netbox/issues/787

**Comment by croax** [comment]
I would still like to see this as a feature, it's very hard to train a lot of people that aren't network engineers to figure out how the search works...

**Comment by jeremystretch** [comment]
Please see my comment [here](https://github.com/digitalocean/netbox/issues/787#issuecomment-271595837) explaining why we won't implement this sort of wildcard logic for IP/prefix search. The short answer is that it only works for /8, /16, and /24 prefixes.
