### ISSUE TITLE
Question - Scanning

### ISSUE THREAD

**Issue by spot88** [digitalocean/netbox#1257]
Will this scan existing network? If not anyone know a solution that does?

**Comment by cioby23** [comment]
This link will answer to your question https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#why-doesnt-netbox-scan-for-ips

**Comment by jeremystretch** [comment]
@spot88 We try to reserve GitHub issues for feature requests and bug reports, but if you have any further questions I invite you to raise the topic on [our mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
