### ISSUE TITLE
Increase circuit "name" field maximum length from 50 characters

### ISSUE THREAD

**Issue by akrus** [digitalocean/netbox#1258]
### Issue type:feature request

**Python version:**
**NetBox version:**

Hello!

Currently there is a limit for circuit names (50 symbols), can I request to change it to 100 (or more) symbols instead? (or add a setting to control this)

**Comment by jeremystretch** [comment]
The circuit ID field, like others, is intentionally limited in length to prevent users from including information other than the circuit ID. A description field has been provided for additional information.
