### ISSUE TITLE
Enable WHOIS Support ARIN, RIPE NCC, APNIC

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#126]
**Function**: Be able to provide basic WHOIS information (urls, owners, etc.) for Subnets & AS Numbers
**Use Case**: Allow for further verification of "asset owners," eventually allow for AS origin, and contact details

**Helpful Links**:
- https://www.arin.net/resources/whoisrws/whois_api.html
- https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API
- https://www.apnic.net/apnic-info/whois_search/using-whois

**Comment by doon** [comment]
Do you mean for doing integrated whois lookups on customer(end user) provided IP space? Or are you looking for the ability to do SWIP /RPSL via an RIR integration?

**Comment by ryanmerolle** [comment]
I think SWIP / RPSL is interesting for multitennacy, but with this I was only talking about pulling meta deta about subnets and ASNs to track usage of the public resources.

**Comment by doon** [comment]
Gotcha.  For us (Colo/Datacenter / Regional ISP), RIR integration is on of the biggest features we use on our current IPAM (6Connect provision) Since we need to keep track of report all our allocations back

**Comment by MrDragon** [comment]
Full integration (rwhois etc) would be sweet, but for now I'd settle for a customer-ID field per prefix - that way I could cross-reference with our customer database/CRM, shuffle the data, and create whatever I need (rwhois, SWIP, IRR, documentation, etc)
Or should this be a separate feature request?

**Comment by camwin** [comment]
I, too, would really like SWIPing. Currently, the only free IPAM I know of that offers SWIPing is IPPlan.

**Comment by The-Loeki** [comment]
Would RDAP not be a much better fit? It's basically billed as the JSON successor to whois, and it's actually already a requirement for name registries to provide it:
https://en.wikipedia.org/wiki/Registration_Data_Access_Protocol

**Comment by jeremystretch** [comment]
This feature request is pretty nebulous. I'm going to close out this issue as it lacks a clear definition and scope, but please feel free to propose a new, specific request including a detailed use case.
