### ISSUE TITLE
Install pillow on Debian 8.2

### ISSUE THREAD

**Issue by jaroslavsafranek** [digitalocean/netbox#1260]
### Issue type:

**Python version: 2.7**
**NetBox version: 2.06**

If I try install Netbox on Debian 8.2 - pip install -r requirements.txt crash on JPEG require.
I found this: https://www.gfairchild.com/2015/10/08/installing-the-requirements-for-pillow-3-on-debian/
It seems that in installation manual missing dependencies for Debian installation.

**Comment by jeremystretch** [comment]
Debian 8 introduced some very disruptive changes. We will be dropping it from the installation docs. Please see #1208.
