### ISSUE TITLE
Port/Outlet Connection Issues After 2.0.3 to 2.0.6 upgrade

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#1265]
After upgrading from 2.0.3 to 2.0.6 Netbox no longer will create interface connections, be they PDU outlet, SLC port, or switch ports.
Process for generating the issue is attempt to create connection, hit connect, page refreshes but still shows original selections, hitting connect a second time refreshes the page and presents the below errors.
<img width="483" alt="screen shot 2017-06-13 at 11 49 04 am" src="https://user-images.githubusercontent.com/20648781/27091702-f0df659e-502e-11e7-981f-bc112f0b3041.png">
<img width="485" alt="screen shot 2017-06-13 at 11 49 30 am" src="https://user-images.githubusercontent.com/20648781/27091705-f2d1d1de-502e-11e7-8028-3c35f16c7088.png">
<img width="420" alt="screen shot 2017-06-13 at 11 54 01 am" src="https://user-images.githubusercontent.com/20648781/27091729-046cdd1c-502f-11e7-8cd9-76978f22e417.png">
Once these errors are presented, no outlet/port/interface options exist under the dropdown menu.
OS info:
`Linux netbox0-01-ussnn1.prod.dc.dynback.net 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Python info:
`Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2`
Netbox info:
`v2.0.6`

**Comment by jeremystretch** [comment]
AFAICT this only occurs when using the "search" option to choose a device. Seems like this issue keeps resurfacing. The crux of the bug is that the form is trying to validate the parent device field, which doesn't get populated when a device is chosen via the search field. (After submitting the form, you can see the validation error under the "select" tab.)

Will need some time to figure out a permanent solution.

**Comment by swickstrom** [comment]
I seem to still be experiencing this issue after pushing v2.0.7 to our DEV instance:
<img width="422" alt="screen shot 2017-06-15 at 3 06 23 pm" src="https://user-images.githubusercontent.com/20648781/27197491-64440a54-51dc-11e7-8a25-e0aa646f7bd4.png">
<img width="459" alt="screen shot 2017-06-15 at 3 06 38 pm" src="https://user-images.githubusercontent.com/20648781/27197504-67e6802e-51dc-11e7-9e6e-7ea3915e49be.png">

**Comment by jeremystretch** [comment]
@swickstrom try forcing a refresh (ctrl+F5 or equivalent) to make sure the new javascript was pulled down.

**Comment by swickstrom** [comment]
Unfortunately that has not fixed said issue; tested on Chrome, Safari, and Firefox (Chrome is the default browser used).

**Comment by jeremystretch** [comment]
@swickstrom Are you sure the static files have been upgraded? Try running `./manage.py collectstatic`.

If you still have the issue after this, please post the explicit list of steps you're taking to reproduce the issue.
