### ISSUE TITLE
Circuit can be connected in-use device interface

### ISSUE THREAD

**Issue by mkerins** [digitalocean/netbox#1266]
To reproduce:
- create two access switch devices (sw1 and sw2) each with ifaces 0-10.
- connect iface 0 on sw1 on to iface 0 on sw2
- create a circuit and select iface 0 on sw1 for the A side and select iface 0 on sw2 for the B side

This only appears to be an issue when first creating the termination. If I edit the termination and change it to iface 5 on sw1, save and then try to change it back to iface 0 on sw1 it's grayed out.

**Comment by jeremystretch** [comment]
I've marked this as fixed because connected interfaces now show up as disabled in the selection lists, however I've opened #1269 to extend the API so that we can also check for circuit connections.
