### ISSUE TITLE
Enable tracking of AS numbers and assignments

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#127]
**Function**: AS Number tracking & assignments
**Use Case**: Start off with being able to assign and track ASNs.  

Further workflow and linkage of peering ASNs, advertised/received subnets, and etc could happen in future enhancements.

**Comment by bellwood** [comment]
Not sure if this applies to your request, but, it would have been nice if the software would allow you to enter an ASN and have it populate aggregates.

**Comment by doon** [comment]
@bellwood  where would these aggregates come from? BGP? Routing Registry (ALA RadDB?)

**Comment by bellwood** [comment]
RIR like Arin list all the NETS associated to an ASN or ORG...

**Comment by ryanmerolle** [comment]
I forgot their is an ASN field associated to sites.  What was the use case / thought process there?

**Comment by rackcentral** [comment]
If you are a carrier like ourselves - it would be handy to be able to add the customer ip space in the ipam section and link this to an AS number. 

We have been using phpipam for a long period of time, while this does not support this either we got around it by using custom fields section. 

Discussion? Thoughts?

**Comment by afenioux** [comment]
It would be great to have an ASN object "containing" the list of prefixes declared in ROUTE(6) objects from IRR (RADb should be an option, but not the only one).
A field with AS-SET for v4 and v6 would also be needed, and having a separated list of ROA (RPKI/ROA) would be nice.

I'm not really keen on having these prefixes created in the IPAM section, because these are only customer prefixes, not the ones of my company.

IMHO, adding some attributes in the ASN object with a list of comma (or space) separated prefixes would enough.

**Comment by ryanmerolle** [comment]
Adding some data modeling discussions from irc today:

Due to historical reasons, acquisition, regional segregation, & whatever other reason, providers may have multiple ASNs that they could use.  As such, it may be good to map ASNs in the IPAM tool.  We can associate them to providers/organizations/3rd parties (I would perfer we rename this given its not just providers).  We could then strip out ASNs from the providers table and roll up all ASNs mapped to a provider page kind of like we do for sites and number of racks.

When associating ASNs to circuits, bgp peers, or whatever else we decide to associate them to, you could assign the provider and then a qualified drop down would display showing the possible ASNs, with the default being empty or some ASN the user set as default in IPAM.  This would again be sort of like how rack creation allow you to select a rack group in a site after you select a site to associate the rack to.

**Comment by lukerussell** [comment]
I'm interested in tracking our private AS use and assigning them to sites.

**Comment by Krytical13** [comment]
I could be misunderstanding the usage of ASN's as I am trying to use Netbox to manage and document our own international network and not a customer network.

From the docs:
Replicate the Real World

Careful consideration has been given to the data model to ensure that it can accurately reflect a real-world network. For instance, IP addresses are assigned not to devices, but to specific interfaces attached to a device, and an interface may have multiple IP addresses assigned to it.

Following this model,
Maybe add more types of interfaces to be assigned to devices like BGP/OSPF/??

That way you assign the interfaces to the devices as per usual, but you are then also managing the ASN's on the routers where they are actually used.
Provided you have the routers in a site, it should be easy to allow sorting the ASN's by site or customer.

I would think documenting the ASN's connections to peers/circuits etc should go somewhere else like on the specific peer/circuit... or on the same page, but different tab as the Ethernet and power connections.

**Comment by daemian** [comment]
I would likewise like to be able to track ASN's. For our use, we would need to have multiple ASNs per VRF (we could also have 1 or more prefix's assigned to an ASN). We are a service provider and for some products we manage the customers' mpls vpn environments (managing CPEs). We need to track with private ASNs we are using inside of their MPLS VPN so we know which one to assign to the next site we bring online.

**Comment by darrelclute** [comment]
We need to be able to track an ASN per device as we are using eBGP in a Clos based layer 3 network, a la RFC 7938.  We also have some local ASN overrides inside VRFs on a device so having the ability to have ASN assignment per VRF on a device would be useful as well.

**Comment by hugoslabbert** [comment]
Use case here would be ASN assignment with an eBGP Clos network, so ASN per switch, basically.

**Comment by InsaneSplash** [comment]
Maybe the management of a Private ASN could be implemented in the same way as VLAN and VLAN groups as a start?

**Comment by rsaturns** [comment]
The goal is today I track all private ASN numbers in a spreadsheet then say ASN X is assigned to site Y. Today ASN is a free form field at the site level and doesn't tell me what the next available ASN would be or which ones are in use. It would be nice to be able to import the entire private range of ASNs and then attach them to the site. So I could readily see what is assigned and what is available.

**Comment by jeremystretch** [comment]
Reading through all the comments here again after more than a year of inactivity, it's evident that there are several different use cases being intertwined. Most of these are probably solved by the recently-introduced config context functionality, wherein users can assign arbitrary data to resources however they please.

I'm going to close this out as no specific model for this feature was agreed on. If someone would like to propose a _specific_ use case involving ASN assignment and its accompanying data model, please do so in a new ticket using the current feature request template.
