### ISSUE TITLE
IPv4 && IPv6 subnet calculator

### ISSUE THREAD

**Issue by rkutsel** [digitalocean/netbox#1271]
@jeremystretch thought It'd be great if netbox had subnet calculator. Did you ever consider adding that feature?

**Comment by jeremystretch** [comment]
There's no shortage of subnet calculators already available, and everyone has their own preference. I don't see any benefit to building one into NetBox.

**Comment by rkutsel** [comment]
Fair enough. I just thought of it as a value-added component that'd come in handy and was just wondering whether you had plans to add it as a feature.
