### ISSUE TITLE
Add RF connectors

### ISSUE THREAD

**Issue by fogtea** [digitalocean/netbox#1272]
I work in the 2-way radio industry and would to to see if its possible to add a connection type of RF into netbox. A lot of radios are computers with radios in them, so they have the standard connection types with the addition of a coax connection.

**Comment by jeremystretch** [comment]
What interface types are you proposing be added? Please list the exact names.

**Comment by fogtea** [comment]
For now, just a separate connector type that says RF, something i can add to a device type instead of interface,console, and power. I dont how important connector types are for netbox, but a few to start with are:
Type-N
BNC
PL-259 (UHF)

Thank you for the immediate follow up!

**Comment by jeremystretch** [comment]
What are these interfaces used for? NetBox is primarily an IPAM/DCIM application; if they're not used for networking I'm not sure it makes sense to add them.

**Comment by fogtea** [comment]
Jeremy,

Thank you very much for following up with this! 
A radio repeater is basically a server and very much needs to be part of DCIM and IPAM. We have racks of radios all serving different purposes. They can be 1U-4U and have all the connections of a regular server with the addition of a coax. The coax can route directly to an antenna or a multitude of other components like multicouplers, combiners, and duplexors (Rackable radio gear). Think of a device that has 8 coax connections in and 1 coax connection out. Adding coax will give me/users the ability to track/trace where coax lines go given netboxes awesome connecting capability in the web interface. Much like how I can connect server X interface ge/0/0/1 to Switch Y port fe/0/01, Id like the ability to do the same with coax. Radio X, interface coax 1 connects to combiner Y port coax 1. I hope that paints a picture. I know beggars cant be choosers, but so far netbox has been the best solution we have come across. Thank you again!

**Comment by jeremystretch** [comment]
@fogtea I'm referring specifically to the radio interfaces. It doesn't sound like they could be reasonably classified as data network interfaces, so it wouldn't make sense to add them as options for interface type. Afraid I have to reject this request.

I understand there's value in documenting these connections, but NetBox doesn't currently have a model which would support it. You might be interested in #968, which would potentially introduce a mechanism for adding arbitrary connections such as these. I invite you to document your use case there and give it a :+1:
