### ISSUE TITLE
Track Private BGP ASN in IPAM Module

### ISSUE THREAD

**Issue by rsaturns** [digitalocean/netbox#1277]
### Issue type: Feature Request

It would be nice within the IPAM module to be able to document the 64512 – 65534 range of Private AS Numbers. And then be able to assign to a site. This would allow us to see at a glance what AS Numbers are assigned and to where. And what AS numbers is available for assignment.

**Submition Form**
Essentially alter this form:

![image](https://user-images.githubusercontent.com/12532563/27190526-96e08236-51a9-11e7-8ca1-dd892771d5e6.png)

IP Address -> BGP ASN
Address -> ASN

Everything else remains the same.

**Menu Option**
Add to the drop down menu a block.
![image](https://user-images.githubusercontent.com/12532563/27190633-f36de52a-51a9-11e7-925e-8a13be0711b9.png)

BGP ASN
Add a BGP ASN
Import BGP ASNs

**Comment by hslabbert** [comment]
Is there a reason you would restrict this to only 16-bit private ASNs rather than also including 32-bit private ASNs?

**Comment by rsaturns** [comment]
There is not, we haven't used the 32bit range but yes ideally it would cover al of them. In fact, the ability to even enroll your public AS numbers and assign to a site would be desirable. The end goal would be to know what AS is assigned in the environment and to what location.

**Comment by jeremystretch** [comment]
I'm not clear on what's being proposed here. You typically would not assign individual IP addresses an AS number, and the site object already has a field for associating an ASN.

#127 has already been opened to implement some form of ASN tracking. Maybe it would be better to note your use case there?

**Comment by rsaturns** [comment]
I will re-phrase and attach to 127. The real goal is today we track all private ASN numbers in a spreadsheet then say ASN X is assigned to site Y. Today ASN is a free form field at the site level and doesn't tell me what the next available ASN would be or which one are in use really.

**Comment by conip** [comment]
any news on that? Thats exactly what I also was looking for.
I imagine having dedicated section (likewise "Associated VRFs") which could be ASN. Each one of the subnet I'm creating I'd like to have the option to correlate it with AS number. Starting from that section I mentioned above whenever I found one AS I wish to list all of the subnets being advertised with this AS and vice versa. When I go under the IP subnet details I wish to see what AS it has. 

I often need to assign new AS to newly created or going to be migrated into MPLS site. I need to search for unused AS number in EXCEL which is not the best way :)

**Comment by DanSheps** [comment]
Please see #127
