### ISSUE TITLE
[Feature] Display deployed verision

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#128]
When leveraging the gui, it would be nice to display in the gui some sort of reference to the deployed version number.

Bonus functionality would be to quickly lookup the current version vs the latest github version and show some sort of indicator of whether the deployment is the latest version available.

**Comment by jeremystretch** [comment]
This was implemented earlier today in 48d607fb966b33876f8f7f31cf0a7d607e40dca6. It's now included in v1.0.6.

**Comment by ryanmerolle** [comment]
Great! I have been providing feedback based on your hosted demo.  I'll deploy the latest version tonight to test all your new updates.
