### ISSUE TITLE
Incorrect Tooltips on Connection buttons

### ISSUE THREAD

**Issue by traveler3468** [digitalocean/netbox#1282]
### Issue type: Bug Report
**Python version: 2
**NetBox version: 2.0.4

When making connections I realized that the tooltip's on the connection buttons seem wrong to me. When the interface is connected and it displays the plug icon the tooltip says "Mark Connected" when the the button icon is displaying the circle with a line through it, the tool tip displays "Mark Disconnected"
![button bug](https://user-images.githubusercontent.com/29483942/27228695-adc6cfe6-5276-11e7-87c2-ceee54b86a3d.png)
![button bug2](https://user-images.githubusercontent.com/29483942/27228696-adca6ea8-5276-11e7-8635-060049abc8fa.png)

**Comment by traveler3468** [comment]
Update: it also sometimes displays "Mark Planned"

**Comment by jeremystretch** [comment]
It should read "mark connected" or "mark planned," to indicate whether the connection has been physically installed. Maybe "mark installed"/"mark planned" is more clear.

**Comment by traveler3468** [comment]
I think the wording is ok but maybe they should be flipped so that when you hover over the circle with the line through it, it displays "mark connected" and vice versa. That to me says that when I hover over it it should tell me what its going to do when I click the button.

**Comment by jeremystretch** [comment]
Planned connections are highlighted in blue. Clicking the circle marks an installed connection as planned. Clicking the plug marks a planned connection as installed.

**Comment by traveler3468** [comment]
Ahhh, I see. That does make more sense. I didnt even pay attention to the fact that the line turns green when the plug icon is clicked. Green means UP/connected. Am I understanding that correctly?

**Comment by jeremystretch** [comment]
Oh, I see what's happening. The Javascript is assigning the title to the wrong element, so you can end up with an icon that says "mark connected" inside a button that says "mark planned" after toggling a connection. Need to fix that.

> Green means UP/connected. Am I understanding that correctly?

Yep, but only after toggling a connection. If you reload the page, connections are no longer highlighted.
