### ISSUE TITLE
Region has no field named 'nmame'

### ISSUE THREAD

**Issue by beufanet** [digitalocean/netbox#1284]
### Issue type: FieldDoesNotExist after upgrading to v2.0
**Python version:** Python 2.7.9
**NetBox version:** Netbox 2.0.7

After upgrading from netbox 1.9.5 to 2.0.7, I tried to start using Regions features. And had the following error :

<class 'django.core.exceptions.FieldDoesNotExist'>

Region has no field named 'nmame'

**Comment by jeremystretch** [comment]
Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md), please provide the exact steps needed to recreate this behavior. Also, have you modified the code at all? The string "nmame" does not appear to be present anywhere in the code.

**Comment by beufanet** [comment]
You're right :( A bad substitution with vim on code. I will propose my change through push request.

Closed, sorry for the noise and one more time : thanks for the work !
