### ISSUE TITLE
QOS fields within circuit details form.

### ISSUE THREAD

**Issue by PaulWesthead** [digitalocean/netbox#1286]
Is it possible to make an addition to the circuits details tab allowing additions of feature information for a circuit?

The use case in the scenario I am looking at is our services have a CDR and associated QOS queue's.  I am looking to add this as additional information against a circuit ID.

Cheers

Paul

**Comment by andreas1o** [comment]
I would also like to so related circuits, ie one circuit depends on another.
Is that something that is doable ?



Från: PaulWesthead [mailto:notifications@github.com]
Skickat: Monday, June 19, 2017 11:37 AM
Till: digitalocean/netbox <netbox@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [digitalocean/netbox] QOS fields within circuit details form. (#1286)


Is it possible to make an addition to the circuits details tab allowing additions of feature information for a circuit?

The use case in scenario I am looking at is our services have a CDR and associated QOS queue's. I am looking to add this as additional information against a circuit ID.

Cheers

Paul

**Comment by jeremystretch** [comment]
This feature request lacks sufficient detail to be actionable. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md):

> When submitting a feature request on GitHub, be sure to include the following:
>
> * A detailed description of the proposed functionality
> * A use case for the feature; who would use it and what value it would add to NetBox
> * A rough description of changes necessary to the database schema (if applicable)
> * Any third-party libraries or other resources which would be involved

Please extend the request so that it meets all of  these requirements. If no response is received within a week, this issue will be closed.

**Comment by PaulWesthead** [comment]
Hi Jeremy,

I do apologise for not providing enough initial detail, I hope the below satisfies what you are after:

•A detailed description of the proposed functionality
We make use of a national MPLS network provided by a third party.  Within this network we are provided with a CDR (Committed Data Rate) of best effort bandwidth.   As an additional service offering the service provider allows us to apply QOS (Quality of Service) Markings i.e EF,AF1-4 and BE.  This is a billable item, however we are unable to establish what the provider is providing without trawling back through bills.  It would be ideal if we could track what we have made provision for.  We are currently using the comments field for tracking this for example: Circuit ABC12345 500Kbps of EF markings (For voice traffic)
•A use case for the feature; who would use it and what value it would add to NetBox
This is just an additional database field (I think) within netbox and could be used for calculating total QOS markings required at the remote site end as well as the datacentre end.  For example, EF should be used on an uncontended basis, so if we have 10 sites with 500Kbps EF access then the datacentre end would require 5000Kbps.  This is an addition to the exiting circuit CDR capability.
•A rough description of changes necessary to the database schema (if applicable)
N/A
•Any third-party libraries or other resources which would be involved
N/A

I hope this helps.

Thanks

Paul

**Comment by jeremystretch** [comment]
QOS markings get into configuration management territory, similar to prefix filters and firewall policies. This is a bit too far out of scope (and probably a bit esoteric) to add to the schema. However, you can easily create a [custom field](http://netbox.readthedocs.io/en/stable/data-model/extras/#custom-fields) to track this data for individual circuits. Hopefully that's a workable solution for your use case.
