### ISSUE TITLE
"Reverse for 'interface bulk_disconnect' not found." Problem adding Interfaces to Devices

### ISSUE THREAD

**Issue by 4fd81048a9cd8a3fd43f1f4e52f84181** [digitalocean/netbox#1287]
### Issue type: bug report

**Python version:** 2.7.5
**NetBox version:** 2.0.5

Created a Device and Added Interfaces with "LOM [1-2]" form factor: 1000BASE-T (1GE) and then I get the "Reverse for 'interface_bulk_disconnect' not found." error message.

![adding lom](https://user-images.githubusercontent.com/10030990/27285265-20a65126-54ca-11e7-80c8-c744bc7e8a51.PNG)
![interface_bulk_disconnect](https://user-images.githubusercontent.com/10030990/27285260-1dc88b5e-54ca-11e7-9a51-ee2f032b1bdc.PNG)

**Comment by jeremystretch** [comment]
The bulk disconnect feature was just added in v2.0.7. It looks like you've upgraded your code base but still need to restart the WSGI service.

**Comment by 4fd81048a9cd8a3fd43f1f4e52f84181** [comment]
Thank-you!  I restarted gunicorn and it's working fine.  Thanks again.
