### ISSUE TITLE
request to include IPAM script in extras

### ISSUE THREAD

**Issue by rkutsel** [digitalocean/netbox#1290]
@jeremystretch I was just wondering if there's a chance you could add this script [netbox-scripts](https://github.com/rkutsel/netbox-scripts) to **extras**? Thought it might be useful to some folks here.

**Comment by jeremystretch** [comment]
"Extras" is a bit of a misnomer: it's actually a Django application just like the DCIM and IPAM components. It's a collection of models and views that don't quite fit elsewhere (custom fields, for example).

I'd offer to link to your scripts in the README, but I strongly discourage the use of raw SQL when interacting with the database. NetBox fully employs [Django's ORM](https://docs.djangoproject.com/en/1.11/topics/db/), which provides crucial validation not available at the database layer.

I'm happy to discuss this further on the mailing list if you're interested, but I'm going to close this issue as we try to reserve GitHub issues for feature requests and bug reports.
