### ISSUE TITLE
Secrets in Chrome based browsers. "Invalid Session Key" after undetermined period of time.

### ISSUE THREAD

**Issue by phobiadhs** [digitalocean/netbox#1292]
Note: Currently testing in Firefox as well. No indication of the issue so far.

Currently using 2.0.6.

After an undetermined period of time, when trying to unlock secrets in Chrome based browsers (Chrome and Vivaldi), a popup saying "Invalid Session Key" comes up. There is no option like normal to reenter your private key and logging out and back into Netbox has no effect. Closing and opening the browser also seems to have no effect.

Resolution seems to be to clear browser cache/cookies and log into Netbox again. Then it will work for a time.

**Comment by jeremystretch** [comment]
When you unlock your user key, NetBox sends a cookie named `session_key` to the browser, which should last for the duration of the browser session.

When you receive the "Invalid session key" error, can you check whether the `session_key` cookie is still present and if it has a value? It seems like maybe an empty session key is being sent. (If the cookie is missing, NetBox should prompt you to unlock your user key again.)

**Comment by phobiadhs** [comment]
The cookie is there and has a value. As you said, deleting that particular cookie did kick off the user key prompt again. Trying to get it to break again so I can give you a bit more info.

**Comment by phobiadhs** [comment]
I have gotten it to fail again. It took several restarts of chrome to get it to die again but it did. With that being said, I don't see any commonality between the issue and my actions. 
Without being able to lock it down to specific actions, I am thinking we should probably table this unless it becomes a larger issue.

**Comment by jeremystretch** [comment]
Closing this out since there hasn't been any further activity.
