### ISSUE TITLE
Add Search functionality to Interface Assignment area of /ipam/ip-addresses/add/?address=x.x.x.x/xx

### ISSUE THREAD

**Issue by phobiadhs** [digitalocean/netbox#1293]
There used to be a way to search the device name and assign to the interface of the searched device once an IP was created. It appears that recent changes have removed that capability and now require a drill down approach to assigning IP's to an interface.

As it appears the logic behind this may have changed, might I suggest just adding a search field here that will prevent having to drill down for every IP add?

A search field above the Site dropdown should be sufficient. I believe it would be a good idea to have a successful search selection populate the Site, Rack and Device fields leaving the Interface field to be selected by the user.

![ipadd](https://user-images.githubusercontent.com/23314929/27445240-a271cb10-573e-11e7-8b4e-3f5a910f5807.png)

**Comment by jeremystretch** [comment]
Closing this out in favor of #1512 now that virtualization modeling has been added.
