### ISSUE TITLE
HE displayed wrong in edit mode

### ISSUE THREAD

**Issue by quentinsch** [digitalocean/netbox#1294]
The HE selection is displayed wrong in the edit mode. When you view a device it displays correct, but if you're in edit mode the layout is wrong in the selection bar.
See screenshots for clarification.
Happens on version 2.0.7 after upgrading of previous version (1.9.6).

Wrong in edit mode:
![schermafbeelding 2017-06-23 om 14 45 37](https://user-images.githubusercontent.com/7438854/27482762-febad9ea-5822-11e7-87ec-799f99509fb0.png)
![schermafbeelding 2017-06-23 om 14 45 43](https://user-images.githubusercontent.com/7438854/27482761-feba83d2-5822-11e7-86b1-98e8f1d1398b.png)

Good in view mode:
![schermafbeelding 2017-06-23 om 14 45 59](https://user-images.githubusercontent.com/7438854/27482763-fec137b8-5822-11e7-8781-27c826fe30f5.png)

**Comment by jeremystretch** [comment]
Not sure what you mean by HE; the position? It looks like you need to force a refresh of the Javascript. Try ctrl + F5 or the equivalent for your browser.

**Comment by quentinsch** [comment]
Yeah, sorry, HE = position.
Refreshing browser or other browsers (Safari/Firefox/Chrome) give the same result.

**Comment by jeremystretch** [comment]
It's possible the Javascript file did not get updated during the installation. Try running `./manage.py collectstatic --no-input`.

**Comment by quentinsch** [comment]
Didn't help unfortunately.
Output of the command was:
0 static files copied to '/opt/netbox/netbox/static', 263 unmodified.

**Comment by jeremystretch** [comment]
Try going to `http://<netbox>/static/js/forms.js`. Is that file the same as [this one](https://raw.githubusercontent.com/digitalocean/netbox/develop/netbox/project-static/js/forms.js)?

**Comment by quentinsch** [comment]
I did a diff on the file and the file you referred to on GitHub and they are the same.

**Comment by jeremystretch** [comment]
Sorry, I'm not sure what would be causing it then. It looks like your installation is still running old code. Try a clean install.

**Comment by quentinsch** [comment]
Strange indeed... I'll try the clean install...
In addition to the problem, when in editing mode if you choose another drop down f.e. front/rear the drop down of the Position corrects itself. Strange behaviour, but probably cache/browser related then... Thanks for looking in to it!
