### ISSUE TITLE
Allow addition of custom fields for sites

### ISSUE THREAD

**Issue by cwidhelm** [digitalocean/netbox#1296]
### Issue type: Enhancement

It would be helpful to add custom fields to the Site so we can track additional information specific to our workflows that may not be useful to others.

**Comment by jeremystretch** [comment]
This is already supported. Under the admin UI, to go Extras > Custom fields > Add and select "dcim > site" as the object type.

**Comment by cwidhelm** [comment]
Sorry, thought I looked through it. I guess I thought it would be at tenant.
