### ISSUE TITLE
Adding objects in API with "custom_fields" does not work.

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1297]
### Issue type:

Bug

**Python version:**
2.7.12

**NetBox version:**
2.0.6

I can use the API to create new sites just fine (via the `Swagger UI`), but when I try to add a new site with a  previously defined  `custom_field` (via the admin panel in the WebUI), I get the following error: `JSON parse error - Extra data: line 18 column 1 - line 18 column 2 (char 343 - 344)"`

This works:
```
{
    "name": "Jacksonville-FL",
    "slug": "jax",
    "region": "1",
    "tenant": null,
    "facility": "",
    "asn": null,
    "physical_address": "",
    "shipping_address": "",
    "contact_name": "",
    "contact_phone": "",
    "contact_email": "",
    "comments": ""
}
```

This does not work:

```
{
    "name": "Jacksonville-FL",
    "slug": "jax",
    "region": "1",
    "tenant": null,
    "facility": "",
    "asn": null,
    "physical_address": "",
    "shipping_address": "",
    "contact_name": "",
    "contact_phone": "",
    "contact_email": "",
    "comments": "",
    "custom_fields": {
        "ce_qos_type": "2"
        }
   }
}
```

The error that I receive is as follows (from `Swagger`):
```
Curl
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'X-CSRFToken: [REMOVED]' -d '{ \ 
     "name": "Jacksonville-FL", \ 
     "slug": "jax", \ 
     "region": "1", \ 
     "tenant": null, \ 
     "facility": "", \ 
     "asn": null, \ 
     "physical_address": "", \ 
     "shipping_address": "", \ 
     "contact_name": "", \ 
     "contact_phone": "", \ 
     "contact_email": "", \ 
     "comments": "", \ 
     "custom_fields": { \ 
         "ce_qos_type": "2" \ 
         } \ 
    } \ 
 }' 'http://[HOSTNAME]/api/dcim/sites/'

Request URL
http://[HOSTNAME]/api/dcim/sites/

Response Body
{
  "detail": "JSON parse error - Extra data: line 18 column 1 - line 18 column 2 (char 343 - 344)"
}

Response Code
400
```

I've used the `GET` function to ensure that the `custom_field` is a correct value.  For example:
```
curl -X GET --header 'Accept: application/json' --header 'X-CSRFToken: [REMOVED]' '[HOSTNAME]/api/dcim/sites/10/'

{
  "id": 10,
  "name": "Poughkeepsie-NY",
  "slug": "pok",
  "region": {
    "id": 1,
    "url": "[HOSTNAME]/api/dcim/regions/1/",
    "name": "[REMOVED]",
    "slug": "[REMOVED"
  },
  "tenant": null,
  "facility": "",
  "asn": null,
  "physical_address": "",
  "shipping_address": "",
  "contact_name": "",
  "contact_phone": "",
  "contact_email": "",
  "comments": "",
  "custom_fields": {
    "ce_qos_type": {
      "value": 2,
      "label": "6-cos"
    }
  },
  "count_prefixes": 0,
  "count_vlans": 0,
  "count_racks": 0,
  "count_devices": 0,
  "count_circuits": 0
}

**Comment by jeremystretch** [comment]
It looks like this might be an issue with the Swagger UI. When POSTing your example data with curl it works as expected:

```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Token <token>" -H "Accept: application/json; indent=4" http://localhost:8000/api/dcim/sites/ -d '{
    "name": "Jacksonville-FL",
    "slug": "jax",
    "region": "1",
    "tenant": null,
    "facility": "",
    "asn": null,
    "physical_address": "",
    "shipping_address": "",
    "contact_name": "",
    "contact_phone": "",
    "contact_email": "",
    "comments": "",
    "custom_fields": {
        "ce_qos_type": "2"
        }
}'
```

Just to confirm, you created the custom field as an integer field, correct?

**Comment by bdlamprecht** [comment]
No, it was created as a "Selection" field.

**Comment by jeremystretch** [comment]
POSTing the following works for me with a selection field:

```
"custom_fields": {
        "ce_qos_type": 6    
        }
}
```

Note that the value of the field is being passed as an integer. Passing the value as a string yields a validation error ("Invalid choice for field ce_qos_type: 6").

**Comment by bdlamprecht** [comment]
@jeremystretch 

I'm trying to get a string value to be stored in the dictionary "ce_qos_type" with one of two values.

Either:
1. "4_cos" (the default)
2. "6_cos"

I'm going to be using this with Ansible to setup QoS on our border devices, depending on whether the CE can handle `4 classes` or `6 classes`.

Perhaps I'm making this too complicated, if so, I'm open to suggestions.

**Comment by jeremystretch** [comment]
Selection fields have pre-defined values to choose from, created under the admin UI. You need to POST the primary key of the desired choice.

**Comment by bdlamprecht** [comment]
The value of "1" is the primary key for "4_cos" above and the value of "2" is the primary key for "6_cos".  This wasn't working in Swagger, and as you stated, it could be an error there, I'm not able to check today.

I'm a newbie on APIs, so tomorrow I'll investigate how to get a token in the CLI without using Swagger and report back.

Thanks for looking into this so quickly.

**Comment by bdlamprecht** [comment]
Well, I was able to test it and I **CAN** get it to work, although I don't understand an error I'm encountering.

I created a key for myself and used this on the CLI:
```
 curl -X POST -H "Content-Type: application/json" -H "Authorization: Token <token>" -H "Accept: application/json; indent=4" http://[HOSTNAME]/api/dcim/sites/ -d '{
    "name": "Jacksonville-FL",
    "slug": "jax",
    "region": "1",
    "tenant": null,
    "facility": "",
    "asn": null,
    "physical_address": "",
    "shipping_address": "",
    "contact_name": "",
    "contact_phone": "",
    "contact_email": "",
    "comments": "",
    "custom_fields": {
        "ce_qos_type": "2"
        }
}'
```
Which resulted in this error coming back:
```
{
    "custom_fields": [
        "Invalid choice for field ce_qos_type: 2"
    ]
}
```
So, I decided to try without the quotes around the value of `2` for the `ce_qos_type` and it **WORKED**.  What I don't understand is, why does the primary key for `region` work with quotes, but this `custom_field` does not?  I've triple-checked that all of my quotes have matching pairs and I'm not sure what else I'm missing.

Anyways, since I've got this to work, I'm happy to close this issue and I'm very appreciative for you walking me through this, however, I'm still curious about the error.  Let me know how you prefer me to proceed.

**Comment by jeremystretch** [comment]
> What I don't understand is, why does the primary key for region work with quotes, but this custom_field does not?

Custom fields are a bit odd because we're serializing the value of the field to emulate different data types (e.g. string, integer, or boolean). This inconsistency is likely due to enforcement of the integer type for select fields, if that makes sense. But to your point. NetBox should accept a number-as-a-string for custom fields if other primary key fields do. I'll have to look into it some more.
