### ISSUE TITLE
Enable linking circuits based on a common circuit service group

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#130]
Circuits seems to be specifically focused on a single end, but there is no way to link circuits tied to a single "service group."  A service group would be 1 or many circuits.

**Comment by rkwl1** [comment]
Circuits should be able to link the A and Z location.  Also a field for cross connect provider, as those can change from datacenter to datacenter.

**Comment by ryanmerolle** [comment]
Yep as the feature states this would be achieved given some sort of service group.  Service groups allow for not just A to Z, but A through Z and some.

**Comment by bradical987** [comment]
Just my two cents, since I was looking for this exact feature... The A to Z link of a circuit is what I was originally looking for, but I could certainly see how a service group would be more generally beneficial, since multi-point connections could be grouped together in this way. Either way, it would be great to see this feature added.

**Comment by alexjhart** [comment]
I was looking to solve connecting two ends of a circuit today and found this service group issue would likely solve that. I wonder if this is more of a short term feature request or more of a long term roadmap type item? I see it has been open for several months, yet has the minor feature tag.

**Comment by jeremystretch** [comment]
#49 has been completed to allow for both the A and Z sides of a circuit to be defined (this will be available in v1.8.0). I'm going to close this issue out as it seems to overlap heavily with this feature. Adding a mechanism for grouping circuits seems like it would be redundant to the existing combination of provider and type.

**Comment by ryanmerolle** [comment]
So how does this take care of carrier provided MPLS and VPLS circuits where there are multiple sides to a service?

**Comment by jeremystretch** [comment]
Each circuit has only two endpoints, regardless of the type of service it carries.
