### ISSUE TITLE
Related circuits

### ISSUE THREAD

**Issue by andreas1o** [digitalocean/netbox#1300]
#featurue request 
Hi !

It would very nice if you could related circuits to each other, For instance a circuit could a a darkfiber where a Internet circuit is using the darkfiber. Hence a relation between the darkfiber and the internet. 

Would that be stretching it or not ?

**Comment by jeremystretch** [comment]
One link would equate to one circuit in NetBox. Typically if you're buying dark fiber, you're acting as your own service provider.
