### ISSUE TITLE
Ability to view all rack diagrams for specific site on the same page

### ISSUE THREAD

**Issue by dgskwirut** [digitalocean/netbox#1302]
I think it would be nice to have a view of all racks from a specific site on the same page.

Eg. I can click on the Chicago site, and all my rack diagrams for Chicago are shown.

Lots of times I am looking for one or more devices, and I am not sure in which rack they are, or want to look at 2-3 racks from same site at same time.

Being able to view all rack diagrams for a site together on the same page would be very useful.

**Comment by jeremystretch** [comment]
This is provided by navigating to Racks > Rack Elevations and filtering the racks by site.

**Comment by dgskwirut** [comment]
Ahh, I was using older version (1.9.5) thats why I didnt see it.

After upgrading to 2.0.7 I see it now.

Thanks!
