### ISSUE TITLE
Feature Request: Keep background color on connected interfaces for instant recognition

### ISSUE THREAD

**Issue by traveler3468** [digitalocean/netbox#1303]
I was thinking that when you connected an interface the background color would stay green. When the page is reloaded the green color goes away. If you add this code to the interface.html file it will keep the green color on the connected interfaces. So when you load a device page page you can just glance at the page without having to read anything and see which interfaces have something connected(Green), which have planned connections (Blue) and which are open interfaces (White)

what it currently is:
`<tr class="interface{% if iface.connection and not iface.connection.connection_status %} info{% endif %}">`

What I changed it to to show the green for connected interfaces:
`<tr class="interface{% if iface.connection and iface.connection.connection_status %} success{% endif %}{% if iface.connection and not iface.connection.connection_status %} info{% endif %}">`

**Comment by cslingerland** [comment]
This would be awesome!

**Comment by bellwood** [comment]
@traveler3468 would this styling assertion be valuable elsewhere, power, etc? 

UI consistency is key =)

@jeremystretch if you're open to PR's on this one I'd be glad to help - just want to make sure we're on the same page for where this would be applicable.

**Comment by traveler3468** [comment]
@bellwood My thought here is that any easily recognizable information is better for users than having to look further into something if its not necessary. Obviously if you're looking for more specific information then you are going to look harder for it. I think that if this kind of styling could be applicable anywhere where that kind of "easy to see" differentiation would be helpful.

**Comment by Zorlin** [comment]
Massive +1, this could be a huge improvement.

**Comment by jeremystretch** [comment]
To be clear, you just want to see connected interfaces always highlighted in green? And keep the blue highlighting for those in the "planned" state?

**Comment by traveler3468** [comment]
Correct. That way when looking at a device page it is easily recognizable which interfaces are free(nothing connected or planned) and which interfaces either A: Have something connected and, B: Have a planned connection.
