### ISSUE TITLE
Redesign Serial storage in db

### ISSUE THREAD

**Issue by tvc-dps** [digitalocean/netbox#1304]
Feature Request:
create for Serials separate table:
 - name to be unique
 - link serial to device-type
 - assign serial to device
 - allow assign multiple serials to device
 - assign another information about serial eg. contract numbers/supported blax blax blax
...
 also helps to solve #182

**Comment by jeremystretch** [comment]
I'm closing this request as it does not meet the requirements of our [contribution policy](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md).

**Comment by tvc-dps** [comment]
Can you please specify what I missing?
Thanks in advance
