### ISSUE TITLE
error when "+ attach an image"

### ISSUE THREAD

**Issue by miklasz** [digitalocean/netbox#1305]
Hi, when attache image (in rack page) and click create i get error msg:

<type 'exceptions.OSError'>

[Errno 13] Permission denied: '/opt/netbox/netbox/media/image-attachments/rack_43_ll.png'

not sure if its bug?

I use puppet to build netbox vm, but proces in general is the same to your website tutorial, if you require any more information please let me know and I will provide.

many thanks

Bartosz

### Issue type:

**Python version:**
**NetBox version:**

**Comment by jeremystretch** [comment]
You need to make sure that your media path (e.g. /opt/netbox/netbox/media/) is writable by the user NetBox runs as. The error is occurring because NetBox doesn't have permission to write files to that path.

**Comment by ScrimForever** [comment]
Hello... this happened with me too. I change folder permission to www-data and done !

**Comment by ScrimForever** [comment]
chown -R www-data folder(media)

**Comment by LBegnaud** [comment]
and a permanent fix would be to move it out of the netbox folder and set the `MEDIA_ROOT` configuration variable.

**Comment by ScrimForever** [comment]
@jeremystretch can you reopen this ticket and change status to feature ?

**Comment by cimnine** [comment]
@ScrimForever this is already possible. See https://github.com/digitalocean/netbox/blob/develop/netbox/netbox/configuration.example.py#L101
