### ISSUE TITLE
[Enhancement] Patch Panel & Cross-Connect tracking

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#131]
This may be unnecessary, but single patch panel & cross-connect fields are not always idle given the multiple patch panels or cross-connects you may need for a circuit to be patched to your equipment.

**Example:** 350 East Cermak in Chicago has many co-location vendors in the same building.  At times you may need to setup cross-connects from a carrier's Equinix cage to a  TELX meet-me-room to your own cage.

It may also be useful to map out patchpanels in a rack similar to the way you would map out switch ports from a port and rack capacity perspective.

**Comment by jeremystretch** [comment]
This is roadmapped in #20

**Comment by ryanmerolle** [comment]
Sorry I missed this!
