### ISSUE TITLE
api/dcim/interface-connections allows duplicate connections via opposing directionality

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#1313]
### Issue type: bug report

**Python version:** 2.7
**NetBox version:** 2.0.7

Given two interfaces, create two connections by reversing `interface_a` and `interface_b`. The api allows this, thus creating the same connection twice but in different directions. I would expect the second request to fail saying one or both of these interfaces is already connected.

```
curl -X POST  -d '{ \ 
   "interface_b": "1970", \ 
   "interface_a": "1945" \ 
 }' 'http://netbox-dev.nw.cougars.int/api/dcim/interface-connections/'
```
```
curl -X POST -d '{ \ 
   "interface_b": "1945", \ 
   "interface_a": "1970" \ 
 }' 'http://netbox-dev.nw.cougars.int/api/dcim/interface-connections/'
```
![screen shot 2017-07-03 at 1 00 12 pm](https://user-images.githubusercontent.com/1297132/27802189-35b7dd24-5ff0-11e7-9ab3-3af46286f56d.png)

**Comment by jeremystretch** [comment]
This stems from the same root issue as #1285 (lack of model validation via the API). I'm going to close this issue to concentrate any discussion on the matter there.
