### ISSUE TITLE
Prefix import not working after upgrade from 2.0.4 -> 2.0.7

### ISSUE THREAD

**Issue by rkutsel** [digitalocean/netbox#1314]
Unable to import prefixes after upgrading from 2.0.4 to 2.0.7. It pups up with "Required column header "prefix" not found." error. I didn't find any one who had something similar to what I'm having here. I'm running my netbox instance on Debian 3.16.43-2, python2.7, django 1.11. 

I was trying to import it using this format:
169.254.0.0/30,,,,,,Active,,,comment

Am I missing something here or does it look like a bug to you?

**Comment by patrickfish** [comment]
Version 2.0.5 changed the behavior for importing, see
https://github.com/digitalocean/netbox/issues/655

See the text below the import box: Enter the list of column headers
followed by one line per record to be imported, using commas to separate
values. Multi-line data and values containing commas may be wrapped in
double quotes.

So your example would now be:

prefix,status
169.254.0.0/30,Active

**Comment by rkutsel** [comment]
@patrickfish oddly I get the same error. Not sure what to make of this but I'll spend some more time digging deeper into this and come back if find something.

**Comment by jeremystretch** [comment]
Closing this out as there does not appear to be anything actionable. Please ask for this issue to be reopened if you believe you've found a bug.

**Comment by rkutsel** [comment]
@jeremystretch so it looks like when doing an import the first line "prefix,status
" needs to be there. That was a bit confusing. Clearly not a bug, but perhaps it needs to be articulated in the message where it says "Enter the list of column headers followed by one line per record to be imported, using commas to separate values. Multi-line data and values containing commas may be wrapped in double quotes."
