### ISSUE TITLE
Topology map does not limit to devices in the selected site

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1317]
### Issue type: bug?

**Python version:** 2.7.12
**NetBox version:** 2.0.8

When generating a [topology map](https://netbox.readthedocs.io/en/stable/data-model/extras/#topology-maps) for a site, the devices shown are not filtered to the site selected.

For example, if you enter "rtr" as a pattern, then you get devices across all sites whose name includes substring "rtr", even if you have selected a single site for the topology map.

Is this intentional? The doc says:

> Each topology map is associated with a site. A site can have multiple topology maps, which might each illustrate a different aspect of its infrastructure (for example, production versus backend infrastructure).

If the devices are not filtered to the selected site, then there seems to be little point in selecting a site - apart from the fact that it controls which maps are offered when you browse to `/dcim/sites/<sitename>/`

I suppose it *might* be intended to have an upstream device from another site shown in a site-specific topology map; but this can also be done with a global topology map (one which is not associated to a site)

**Comment by candlerb** [comment]
Also lumping in here for good measure: I think there's a typo in the [documentation](https://netbox.readthedocs.io/en/stable/data-model/extras/#topology-maps):

> Note that you can combine multiple regexes onto one line using semicolons.

However, the example immediately above it uses a comma, not semicolon. 

```
access-switch\d+,oob-switch\d+
```

**Comment by jeremystretch** [comment]
> When generating a topology map for a site, the devices shown are not filtered to the site selected.

This is desired behavior. This way you can associate a map with a particular site but still include devices at other sites to provide additional context e.g. for circuits.

> I think there's a typo in the documentation

Yes, the example should use a semicolon. Will fix, thanks.
