### ISSUE TITLE
Support SAML2 for user authentication

### ISSUE THREAD

**Issue by merlinthp** [digitalocean/netbox#1323]
### Issue type: feature request

It'd be nice to be able to log in using a SAML2 single sign-on service.  This would be an alternative to LDAP for centralised user management.  SAML2 uses user-side browser requests to communicate between the SAML2 Service Provider (Netbox) and the central Identity Provider, which makes integration of applications simpler.

Like the LDAP support, new users would be automatically created in the local database, and local permissions could be assigned based on SAML2 attributes.

SAML2 support would be more intrusive to the UI than LDAP support, as the login form would be replaced with a button to generate a SAML2 login request to the Identity Provider.

pysaml2 will be sufficient to implement the SAML2 support, and works on both Python 2.7 and 3.x.

I'm willing to contribute this feature myself.

**Comment by jeremystretch** [comment]
Please see #118 for discussion on this topic. Marking this issue as a duplicate.
