### ISSUE TITLE
Speed abbreviation improvement

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1326]
### Issue type: request

**Python version:**
**NetBox version:2.0.8**

Provide the function to summarise both 1000000 and 1024000 values in human readable form as 1Gbs instead of showing it as 1024Mbs. This would apply to 10Mbs, 100Mbs, 10Gbs.

**Comment by jeremystretch** [comment]
FYI line rate is always expressed in bits. 1.024 Gbps is not the same as 1 Gbps.

**Comment by bellwood** [comment]
Throwing my .02 in, this would be very handy... 

I would argue though for any data imports, values would need to be provided in bits to simplify the process

**Comment by ktims** [comment]
Can I morph this to a request for accepting abbreviations in the input fields (e.g. '1g' or '10g')? Counting zeros (and there are a lot of them) and remembering that it is expecting kbps, not bps or mbps as I would consider more intuitive, is a bit annoying.

Hmm, and now that I think of it, maybe pulling in the speed from the interface type when an interface is selected for a circuit would be nice too. A 10GBASE interface is probably connected at 10G, and deleting one zero if not is preferable to typing 6 of them.

**Comment by jeremystretch** [comment]
> Can I morph this to a request for accepting abbreviations in the input fields (e.g. '1g' or '10g')?

We should be able to create a custom form field that accepts values like "100m" or "1g" and translates the value to an integer during validation.

> Hmm, and now that I think of it, maybe pulling in the speed from the interface type when an interface is selected for a circuit would be nice too.

That might be dangerous. It's common practice to set a 1GE interface to 100 Mbps to effect rate limiting, for example.
