### ISSUE TITLE
Allow for overlapping Aggregates

### ISSUE THREAD

**Issue by eacheach** [digitalocean/netbox#1329]
### Issue type:
Feature Request

**Python version:**
**NetBox version:**

We would like to see support for overlapping Aggregates.  We use Aggregates to show available subnets within the defined Aggregate.  We allocate address space hierarchically so we'd like the flexibility of scoping our output so the most appropriate aggregate for the task.  For instance:

10.0.0.0/8 is used for customer networks
10.0.0.0/9 is used in DC1
10.128.0.0/9 is used in DC2
10.1.0.0/16 is allocated to Customer X in DC1
etc...

If I need a new /16 for a new customer in DC1 we'd like to look at the 10/9 Aggregate.
If we need to allocate a new /24 network to Customer X in DC1 we'd like to look at the 10.1/16 Aggregate.

**Comment by jeremystretch** [comment]
This would defeat the purpose of aggregates. Aggregates define the top level of your IP space hierarchy. Use prefixes to organize space within aggregates.
