### ISSUE TITLE
Rack Groups - not visible in Sites #61

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#133]
This enhancement was released with 1.0.5

I have rack groups setup and this shows the rack groups box in the sites view but even though they group is assigned to the site it does not show this in the view.

**Comment by jeremystretch** [comment]
Sounds like the same root issue as #134: The updated templates are in effect but gunicorn needs to be restarted.

**Comment by mdlayher** [comment]
@rackcentral has this issue been resolved?

**Comment by rackcentral** [comment]
Hi Guys,

This is also now resolved and is working as expected :)
