### ISSUE TITLE
IP address assignment to device with no interface

### ISSUE THREAD

**Issue by Atoms** [digitalocean/netbox#1330]
**Python version: 3.4
**NetBox version: 2.0.9

When you create IP address within API, and then create device with that IP as primary IP, with not providing interface id you can see IP address in device view, but you don't see device attached in IP address view. 
![image](https://user-images.githubusercontent.com/9615/28056653-44a2f3aa-6626-11e7-9026-cf1010796405.png)

![image](https://user-images.githubusercontent.com/9615/28056677-6de1c476-6626-11e7-9afe-c26f590b62fc.png)

![image](https://user-images.githubusercontent.com/9615/28056870-2942e51a-6627-11e7-8cdd-d0d860698573.png)

**Comment by jeremystretch** [comment]
Looks related to #1285. Could you please see if you can recreate the issue under v2.1-beta1 (or the develop-2.1 branch)?

**Comment by Atoms** [comment]
Same behavior is in 2.1 beta version

**Comment by Atoms** [comment]
API requests with which i did that.
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Token xxxxxxx' -d '{ "address": "10.10.10.12/24", "tenant": "1" }' 'http://xxxxx/api/ipam/ip-addresses/'

echo

read -p "Provide id of ip:" ip_id

echo ${ip_id}

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Token xxxxxxx' -d '{ "serial": "xxxx", "device_role": "4", "tenant": "1", "site": "24", "name": "test-device", "primary_ip4": "'$ip_id'", "device_type": "139" }' 'http://xxxxxx/api/dcim/devices/'
`
