### ISSUE TITLE
Show object activity in object view

### ISSUE THREAD

**Issue by Atoms** [digitalocean/netbox#1331]
**Python version: 3.4
**NetBox version: 2.0.9

All activity is displayed in first page of netbox, but it would be nice to see each object activity from object view, and also log activity from API.

**Comment by jeremystretch** [comment]
Not all activity can be tied to a specific device. For instance, when a user edits multiple devices in bulk, the action does not record which specific devices were modified. This feature was never intended to provide an audit trail, only a sense of what was being done in NetBox.

Please see #151 for further discussion about tracking discrete changes to specific objects.

**Comment by Atoms** [comment]
I agree, that not all activity can be tied to device/object, but can you at least consider adding some activity when someone uses API to add/modify/delete object as now i can only see activity made in frontend, but our teams mostly use API to automate things, this should be fairly easy as some activity is already logging. 

The situation in our organization is that multiple teams use netbox, and we want to have track who changes what.

Also i think #151 is not the thing i was talking about, that is  - some journal where outside tools post things done with device.
