### ISSUE TITLE
device type - bulk edit - full depth is duplicated

### ISSUE THREAD

**Issue by miklasz** [digitalocean/netbox#1333]
Hi, just adding couple of devices and noticed I forgot to change some depth so i bulk edit device type, and for some reason it shows 2 fields "in full depth", the top one works when you click apply, the bottom one does nothig, i gues its a bug :D ?

screenshot attached

Bartosz

![screen shot 2017-07-11 at 17 15 45](https://user-images.githubusercontent.com/12444755/28078644-7bd1095c-665d-11e7-970d-c736e9328e6e.png)

### Issue type:

**Python version:**
**NetBox version:**

**Comment by jeremystretch** [comment]
The second field is mislabeled. It should read "Is a console server."
