### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#134]
Version number which was added to releases in the footer is not showing up on the footer.

All we see is (v)

**Comment by bellwood** [comment]
I can tell you it works for the develop branch, mine shows up at 1.0.7

If you "git pull" the master for 1.0.6 did you also run upgrade.sh which is the new upgrade script to handle things post pull?

**Comment by jeremystretch** [comment]
v1.0.6 is showing up on our production servers. Did you restart gunicorn (or whichever WSGI service you use) after the update?

**Comment by mdlayher** [comment]
@rackcentral has this been resolved?

**Comment by solalba** [comment]
Had the same issue after pulling and running the upgrade bash. Restarting services didn't help, but rebooting the server did.

**Comment by rackcentral** [comment]
Hi Guys,

This is now resolved - we can see the version number in the new 1.0.7 release.
