### ISSUE TITLE
Preserve image-attachments directory on upgrade

### ISSUE THREAD

**Issue by LBegnaud** [digitalocean/netbox#1341]
**Feature Request**:

I couldn't find it anywhere obvious, but during the upgrade process it is necessary to move the image-attachments directory contents to the new path. Also (at least for my installation) i have to chown to the netbox user on that folder. 

I'm curious if we could get the process bundled into the upgrade.sh (maybe just move the contents from the old netbox symlink?). I'd be happy with a config option to point the image-attachments directory somewhere else on the filesystem if not.

**Comment by jeremystretch** [comment]
This might get murky when dealing with symlinks (e.g. `media/ -> /opt/somewhere/else/`). Not really sure how best to approach this. Any ideas?

**Comment by LBegnaud** [comment]
I agree symlinks underneath the the /opt/netbox symlink would get hairy, but that seems like the simplest option

Looks like media/ is served by django directly, could we not just have a config option to point that elsewhere?

**Comment by jeremystretch** [comment]
Yeah, I think exposing it as a config option makes sense.

**Comment by Zorlin** [comment]
+1 for making it a config option. That seems the least insane way to handle this ;)

**Comment by lae** [comment]
There's a config option for this already, `MEDIA_ROOT` - for handling upgrades I'm actually [modifying `settings.py`](https://github.com/lae/ansible-role-netbox/commit/78c9d0eab58916c0556aebc0bf3f0fe997f7c16d) but preferably this would be configured within `configuration.py`.
