### ISSUE TITLE
Giving users acces to secrets

### ISSUE THREAD

**Issue by tdmike** [digitalocean/netbox#1342]
In the documentation at readthedocs it's stated that user can be given rights to secrets with secret roles. I can create secret roles and create secrets within these roles. But I cannot assign any users or groups to give them access.

Is this something that's not implemented yet or am I missing something?

Currently using:
Python version:  2.7.12
NetBox version: 2.0.9
OS: Ubuntu 16.04.2 LTS

**Comment by jeremystretch** [comment]
You're not missing anything. This functionality was originally handled via the admin UI, but many of the extraneous admin functions were removed recently in favor of the normal front end. Unfortunately it looks like the secret roles form was never updated to take over this function. That needs to be fixed.

**Comment by tdmike** [comment]
The functionality is still in the back-end? If that's the case I would be able to add it to the front-end?

**Comment by jeremystretch** [comment]
Fixed in the commit above. It will be available in v2.0.10.
