### ISSUE TITLE
Modelling Omni-Path Interfaces

### ISSUE THREAD

**Issue by fanie-riekert** [digitalocean/netbox#1343]
We are trying to add omni-path network interfaces, and are experiencing two difficulties:

1. Selecting the value for the 'Form factor', The closest match is the 'QSFP28 (100GE)' option since omni-path uses QSFP28 and is 100Gb/s but then it is not Ethernet. For the time being we use 'Other', is there a better option?

2. Since omni-path is not Ethernet the MAC address validation prevents us from adding the MAC addresses for these interfaces.
The MAC we used for testing was 80:00:00:02:fe:80:00:00:00:00:00:00:00:11:75:01:01:74:58:35 

Python 2.7.12                                                                                        
Netbox 2.0.8 

Many thanks.

**Comment by jeremystretch** [comment]
> Selecting the value for the 'Form factor', The closest match is the 'QSFP28 (100GE)' option since omni-path uses QSFP28 and is 100Gb/s but then it is not Ethernet. For the time being we use 'Other', is there a better option?

I'm not familiar with Omni-Path but it looks like the transceiver side is the same. Doesn't seem necessary to add a new form factor.

> Since omni-path is not Ethernet the MAC address validation prevents us from adding the MAC addresses for these interfaces. The MAC we used for testing was 80:00:00:02:fe:80:00:00:00:00:00:00:00:11:75:01:01:74:58:35.

PostgreSQL, and therefore NetBox, only supports 48-bit Ethernet MAC addresses.
