### ISSUE TITLE
Bulk CSV import for more object types

### ISSUE THREAD

**Issue by paravoid** [digitalocean/netbox#1347]
### Issue type: feature request

**NetBox version:** 2.0.9

I'm trying to migrate to NetBox from a legacy system (Racktables) with quite a bit of data in it (about 3000 pieces of equipment, in multiple racks/rows/sites/regions).

While looking into how to import the data, I noticed that while it's possible to import via CSV, the functionality is limited to a few specific object types (e.g. sites, tenants, racks, devices) and no such functionality exists for the others. I'm missing primarily manufacturers and device types (I have 86 models from various vendors) and rack groups (I have 15), but it'd be neat to have some of the others as well (regions, platforms, device roles).

Are there any plans to implement such a thing? Should I be looking at alternatives like e.g. using the API instead?

Note that #451 is a similar ticket but a) limited to device types and b) also trying to address the orthogonal problem of sharing a common base for device types between users. Finally, for my trial, I'm also missing the capability of importing custom fields, which is tracked separately as #568.

**Comment by jeremystretch** [comment]
PR #1359 has been merged into the `develop-2.2` branch and will be included in v2.2-beta2
