### ISSUE TITLE
Add option on "Add Interface" screen to go to "Add IP Address" for that new interface

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1350]
### Issue type:
Feature Request:

**Python version:**
2.7.12
**NetBox version:**
2.0.10

It would be convenient to have a button on the "Add Interface" screen to automatically go to the "Add IP Address" screen for that new interface.

To step through the process I'm suggesting be enhanced,  when you open a `device` detail screen and click on "Add Interfaces," there is currently the options for "Create", or "Create and Add More", or "Cancel".  What I'm requesting is there be another link to "Add IP address" which would create the new interface in the DB, and then go the screen for adding an IP address with the "Interface Assignment" fields pre-populated.

**Comment by jeremystretch** [comment]
How would you handle the creation of multiple interfaces? Seems odd to redirect the user to the first one, but maybe that's just me.

**Comment by bdlamprecht** [comment]
I guess I'm not following your question.  What I'm proposing is this new "Add IP Address" link wouldn't go to "the first" interface when that linked is followed, it would be adding the IP address to the newly creating interface similar to clicking the green plus sign labeled "Add IP Address" that appears next to the "new" interface (after clicking "Create).

This wouldn't replace the "Create and Add More" link that exists currently, it would simply reduce the number of "clicks" required when manually adding an interface.  

Here is a quick a mock-up:

![image](https://user-images.githubusercontent.com/7783306/28626898-7cb3aec0-71dd-11e7-9f33-6a3b10ea547e.png)

**Comment by jeremystretch** [comment]
Sorry, my point was that interfaces can be created in bulk. For example, I can tell NetBox to create `ge-0/0/[0-47]` on a device and it will create 48 interfaces. But we can only add one IP at a time per interface.

**Comment by bdlamprecht** [comment]
Riiiight, I forgot about that feature.

As a compromise, perhaps when clicking on the proposed option, it could check the `Name` field and if any "numeric ranges" are included, it would give an error that states that that option is "only supported on individual interface creation" (actual wording is a WIP).

**Comment by jeremystretch** [comment]
I've come back to this in a few times over the past month or two, but to be honest it never seems to be worth the added complexity. The issue has been idle for a while so I'm going to close is out.
