### ISSUE TITLE
no option for adding staff permision user to Secrects Roles

### ISSUE THREAD

**Issue by sacy80** [digitalocean/netbox#1351]
### Issue type:
well using 2.1beta there are no Users and Groups info under Secret role. After upgrade to v2.0.10, able to see User and Groups in secret role. But no option to add or remove users or groups 

**Python version:2.7.5
**NetBox version:v2.0.10

**Comment by jeremystretch** [comment]
> well using 2.1beta there are no Users and Groups info under Secret role

This change wasn't in v2.1-beta1. It has been merged into the develop-2.1 branch and will be included in v2.1-beta2 (if one is released) as well as the final v2.1.0 release.

> After upgrade to v2.0.10, able to see User and Groups in secret role. But no option to add or remove users or groups

Use ctrl/shift when clicking to remove items from the selection lists.

**Comment by sacy80** [comment]
![secrets](https://user-images.githubusercontent.com/30169265/28274734-60b93a72-6b44-11e7-832f-0e554517a02b.JPG)


Sorry is this page display correctly?
