### ISSUE TITLE
Cannot add interface in Devices Interface

### ISSUE THREAD

**Issue by sacy80** [digitalocean/netbox#1352]
### Issue type:
Not able to add device interfaces.

<class 'django.db.utils.IntegrityError'>

null value in column "enabled" violates not-null constraint
DETAIL:  Failing row contains (224, ETH-P0, 1000, f, , 39, null, null, null, null).

**Python version:2.7.5
**NetBox version:2.0.10

**Comment by jeremystretch** [comment]
This bug report needs more information. Per the [contributing guidelines](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md):

> When submitting a bug report, please be as descriptive as possible. Be sure to include:
> * The environment in which NetBox is running
> * The exact steps that can be taken to reproduce the issue
> * Any error messages generated
> * Screenshots (if applicable)

Please ensure that your issue includes all of the listed information. If no response is received within a week, this issue will be closed.

**Comment by sacy80** [comment]
hi Jeremy

think have found some leads. 

i have go into the database table " dcim_interface" and change table's Columns "enabled" to No "Not NULL?". and it allow for me to add interface in devices. 

Im not sure where is the script store so i go to change the DB. will doing this cause other issue?

**Comment by sacy80** [comment]
![netbox db enable](https://user-images.githubusercontent.com/30169265/28274301-1e4d70a0-6b43-11e7-9fd1-05ec3009ed63.JPG)

**Comment by sacy80** [comment]
sorry like like i accident closed this thread

**Comment by sacy80** [comment]
hi jeremy

The environment in which NetBox is running : CentOS 7

**Comment by jeremystretch** [comment]
> after upgrade from 2.1beta to 2.0.10

You shouldn't be downgrading from the beta to a production release. This requires rolling back the database migrations, though ideally you'd have used a different database entirely. This error is occuring because the 2.0.10 code isn't aware of the `enabled` column.

**Comment by sacy80** [comment]
thanks jeremy. got it, think i will disable for the enable column in the database. as i encounter some error on beta 2.1. stable release 2.0.10 work . 
Thanks alot for the info
