### ISSUE TITLE
Support Assistance

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#1354]
Hi,

I tried to motivate my RSI to put in place Netbox. I liked the product but, he asked me if there is a support assistance (not free)  in case of problems ? If not, is it planned ?

Thanks in advance.

Regards,

Thomas V.

**Comment by jeremystretch** [comment]
NetBox is developed as an open source product with development led primarily by DigitalOcean's network team. There is currently no commercial support option that I'm aware of. (Unfortunately, this is not something I'm able to offer.) However, I like to think that we're pretty good about addressing bugs in a timely manner, and we have a fairly active community.

If you have any further questions, feel free to bring them up on our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). Thanks.
