### ISSUE TITLE
Editing prefix to invalid value shows no warning

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#136]
I have `10.175.0.0/16` listed a prefix under the `10.0.0.0/8` aggregate

When I try to edit `10.175.0.0/16` to `10.175.1.1/16` it tells me:

```
Modified prefix 10.175.0.0/16
```

Presumably this is because `10.175.1.1/16` is invalid (which is fine) but it should be a catchable/reportable error.

**Comment by jeremystretch** [comment]
Good point. Makes more sense to display the likely intended prefix rather that silently fixing it.

![netbox_-_add_a_new_prefix_-_2016-06-30_17 07 39](https://cloud.githubusercontent.com/assets/13487278/16504405/c6f5805c-3ee5-11e6-83b5-f30fd5dad6f7.png)
