### ISSUE TITLE
Skip duplicates import

### ISSUE THREAD

**Issue by loopodoopo** [digitalocean/netbox#1360]
I'm migrating from an old IPAM tool to Netbox. For the migration, I'm writing a migration script which parses the old tool and creates a CVS which I can import in Netbox. 

While writing the script I would like to import all data once and do a sync (by manually pasting all records again) once I'm ready to switch over. 

Problem is that Netbox will import all items as duplicate, for that reason I would like to have a checkbox on import to ignore duplicates. 

For example, I'm trying to import IP addresses: 

```
address,status,description
1.0.0.3/32,Active, description
```

and then a second time:

```
address,status,description
1.0.0.3/32,Active, description
1.2.3.4/32,Active, description
```

Now I have 2 entries for 1.0.0.3/32. This behavior I would like to overwrite with a 'ignore duplicates' on import checkbox.

This feature would be useful on all import pages.

**Comment by jeremystretch** [comment]
You'll need to correct your data before importing it into NetBox. Some people need the ability to import duplicate prefixes/IPs. Please see the discussion in #1353.

**Comment by loopodoopo** [comment]
Some people need to import duplicates, some people don't for that reason I suggest a checkbox. I think the user who submitting #1353 would be helped just as much as I would with this feature.
