### ISSUE TITLE
Server error when uploading device image

### ISSUE THREAD

**Issue by benwut** [digitalocean/netbox#1361]
Hello,

When I attach an image on a device I got this error : 
![image](https://user-images.githubusercontent.com/14860737/28337594-5f944232-6c06-11e7-8397-99b6beb74f28.png)

I was in 2.0.9 netbox version and upgrade using the "upgrade.sh" script to 2.0.10 today.
It was the first time I attached an image to a device, never tried in 2.0.9 so I can't tell if it is since this update.

Here's the rights on the "image-attachments" rights : 

    root@netbox:/opt/netbox/netbox/media/image-attachments# ls -la
    total 12
    drwxr-xr-x 2 root root 4096 Jul 10 22:21 .
    drwxr-xr-x 3 root root 4096 Jul 10 22:21 ..
    -rw-r--r-- 1 root root   14 Jul 10 22:21 .gitignore

Netbox version: 2.0.10
Python version: 3.5.3
OS: Debian 9 4.9.0-3-amd64

**Comment by LBegnaud** [comment]
you need to chown the directory for whatever use the django app runs as, for me that is the netbox user:
`chown -R netbox:netbox /opt/netbox/netbox/media/image-attachments`

**Comment by Bill-Irvine** [comment]
https://netbox.readthedocs.io/en/latest/data-model/extras/#image-attachments

**Comment by jeremystretch** [comment]
Agreed, seems like a simple permissions issue. Closing this out.

**Comment by benwut** [comment]
Oops sorry guys :|

**Comment by sayching** [comment]
@benwut how did you solve this problem? Now I'm facing this problem too. And I'm a newbie in this field please help me. Thank you! :)

**Comment by benwut** [comment]
Hello @sayching, I solved the issue by doing what @LBengaud said in first answer.
