### ISSUE TITLE
Cannot generate token from site view

### ISSUE THREAD

**Issue by Atoms** [digitalocean/netbox#1362]
**Python version:** 3.4
**NetBox version:** 2.1.0

User cannot generate token for himself in site view, from admin panel token generation happens.
Also user who has all permissions cannot generate token in site.

enabled debug mode, got error:
![image](https://user-images.githubusercontent.com/9615/28365858-dd67420e-6c92-11e7-95f5-4e78c39df7f7.png)

**Comment by jeremystretch** [comment]
Can you provide the full stack trace please?

**Comment by Atoms** [comment]
Seems i found a problem, problem is if you want to put in token it requires predefined length, but when you put in not required length it throws this error, if i want to make own token ir should be written somewhere required length and maybe even counted when you input token, and proper error should be provided when length is not correct.

**Comment by jeremystretch** [comment]
Probably need to add a minimum length validator to the form field.
