### ISSUE TITLE
Enable - Interface Description to be serchable

### ISSUE THREAD

**Issue by miklasz** [digitalocean/netbox#1363]
how bad would be to add Interface Description to all object search?

Many thanks

Bartosz

**Comment by jeremystretch** [comment]
In what context? We could add it to the API filter, but adding it to the general device search would probably return too many results. For example, searching for "core" in devices would also return all devices with an interface named "Uplink to core."

**Comment by miklasz** [comment]
I was thinking to use it for cable labels, I know you are working on the big project #20, I also know it will gonna take some time on this one, so mean time i was thinking to add description of the cable id on both sides of interfaces, so when i go to rack in our dc and type cable id i am trying to find both ends i can search and get both side of the cable 

For example:
I have patch panel interface MMR1/B1/C1/P1 and Interface description of this port/interface: DC-01234
then I have device rt0.sal01.dc with port xe-2/0/1 and same interface description: DC-01234

so when i type in search DC-01234 it should return both ports or devices

is it something easy possible to do ?

we use pretty unique names for cables so search should only return interfaces to searched description ?

Many thanks Jeremy, really appreciate your work, netbox is a great software.

**Comment by jeremystretch** [comment]
The interface description field is intended to hold the description configured on the device. I recommend against trying to repurpose it.

**Comment by miklasz** [comment]
ok, thank you for advise, i guess I will wait for update with patch panels, can I ask how far is the work on #20 ? 

many thanks

Bartosz

**Comment by jeremystretch** [comment]
All work on #20 is being tracked in the issue. I am unable to provide an ETA on any feature.
