### ISSUE TITLE
RADb Integration

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#1365]
**Issue type:**
Feature Request

RADb has announced beta API support for their IRR service.

The following link contains all the details and usage examples:

http://radb.net/support/api.php

I'm not 100% on how the integration might work or look but we'd need to bring AS numbers into the mix at the Aggregate/Prefix/Provider level to properly do it and glue it all together - expanding on #127 perhaps

**Comment by jeremystretch** [comment]
Sounds neat, but this needs to be fleshed out more. How we'll need to extend the data model, what the workflow will look like, etc.

**Comment by bellwood** [comment]
I'll dedicate some thought cycles into this and try to have something useful to share next week

**Comment by ktims** [comment]
RIPE also has an API for the same functionality, and you don't have to pay them to use their IRR: https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API

Some thought should be put into generalizing whatever interface is designed.

**Comment by bellwood** [comment]
@ktims funny you mention that as the RADb API was modeled to be nearly the same as RIPE's - they state it on their API page:

> The API is similar to the RIPE API (see https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API-WhoisResources)

So supporting both shouldn't too much of a burden =)

**Comment by jeremystretch** [comment]
I have to close this out since it seems to have stagnated. However, feel free to submit a fresh FR with a detailed description, use case, etc. if you're still interested in working on it.

**Comment by bellwood** [comment]
Respectfully, FR’s are stagnating as core FR from 18+ months ago are getting no attention and there’s seemingly no clear path for where Netbox is going.

I’m all for seeing new functionality but if the basics the masses are asking for or other product-killer features have had no input from you in 18+ months the community won’t be engaged to keep these FR “fresh”.

Thanks 🙏🏻

**Comment by jeremystretch** [comment]
@bellwood The issue here is that this FR was never fleshed out to describe the proposed implementation; it's essentially just an observation that RADb has an API, which isn't actionable. The other FRs you refer to all have at least some high-level discussion of the proposed functionality. You're welcome to submit a new issue but it needs to describe what the proposed feature is, who would use it and why, what the workflow looks like, and so on.

**Comment by bellwood** [comment]
No contest this lacks substance, simply stating my observation.

I’ll move my other input to the discussion group as that’s the appropriate place for it.

Thank you 😁
