### ISSUE TITLE
Request ability to assign Vlans and default gateway to switches

### ISSUE THREAD

**Issue by jpatmore** [digitalocean/netbox#1367]
### Issue type:feature request

**Python version:**
**NetBox version:**

This may be related to feature request #1349 , but am raising it independently as I didnt want to dilute the excellent progress on that one (this is slightly different).

We too are developing Netbox as  'source of truth' for Ansible configuration management.  We would like to assign existing site Vlans to a Layer 2 switch, and also assign the default gateway IP address. 

For the Vlans. we are currently just manually creating virtual interfaces, and assigning them the ID of the Vlans (and then just leaving the IP field blank),  It would be beneficial to be able to select in bulk from a check list of Vlans that exist at the site, and automatically create the interfaces with that Vlan ID, and add the Vlans name as description?

It would also be beneficial to assign the physical interfaces of the switch to either tagged/untagged status (untagged would mean a dot1q trunk), and assign physical interfaces as members of specific existing site Vlans in bulk.

For the default gateway, we would like to be able to select the interface of another device, and add it in the 'critical connections' section, as the 'default gateway' for the device.

These elements could then be called via API to populate the configuration variables in Ansible.

Thanks again for all the effort that is going in to this application.

**Comment by jeremystretch** [comment]
> We would like to assign existing site Vlans to a Layer 2 switch

#150 is open to assign VLANs to interfaces (e.g. tagged or untagged). It'll happen, we just haven't decided how yet. Once implemented, that information can be used to infer which VLANs should be configured on a switch.

> and also assign the default gateway IP address

This is probably best handled by #1349. You _could_ create a custom field for this in the interim, but IMO this is one of those miscellaneous bits in the config that you might want to share across multiple devices.
