### ISSUE TITLE
Failed to upgrade from 1.9.1 to 2.0.10

### ISSUE THREAD

**Issue by perw07** [digitalocean/netbox#1370]
### Issue type: bug report

**Python version:2.7.6
**NetBox version:1.9.1

Host OS: Ubuntu 14.04.5 LTS

I was running the same steps as always (following the documentations "upgrade" section):

$ cd /opt/netbox
$ git checkout master
$ git pull origin master
$ git status

Then running ./upgrade.sh.

After upgrading a lot of stuff (it has been a while) this appears on the screen:

**Applying database migrations (python netbox/manage.py migrate)...
./upgrade.sh: line 50:  4913 Segmentation fault      (core dumped) python netbox/manage.py migrate**

Of course nothing works after this has happened. I have not been able to easily locate the mentioned core file, I wonder if it was actually created?

Any idea how to gather more information to try to pinpoint the problem?

**Comment by jeremystretch** [comment]
GitHub issues are intended for reporting bugs and requesting features. For general discussion or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
