### ISSUE TITLE
Feature Request: Filter on Available/Not Assigned Subnets

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#1373]
### Issue type: Feature Request

Netbox will show available subnets that can be allocated when I create an aggregate or container. I would like a way to search all those available subnets without having to enter into each aggregate or container. If that could be a filter type under the prefixes page even though its not an active prefix that would be great.

**Comment by jeremystretch** [comment]
Available prefixes don't actually exist as objects in the database, so we can't search for them.

**Comment by lancesdavis** [comment]
Displaying available prefixes in the top level prefix list when expanded would be a start - then the filter just needs to not display all of the other child prefixes !
