### ISSUE TITLE
Show duplicates IP in another colour for shared role

### ISSUE THREAD

**Issue by claudex** [digitalocean/netbox#1376]
### Issue type: feature request

With the new IP role added (thanks for that), would it be possible to change the duplication check when displaying an IP ? I would like to show the warning in another colour the duplicate addresses if the role is to be shared among several interface (VIP, anycast, VRRP...). I still think that it is usefull to show the other duplicate IP to see where it is allocated.

Here is an exemple of what I think. If you think this is OK, I will work on a pull request with cleaner code.

(code in ipadress.html)
~~~
        {% if duplicate_ips_table.rows %}
                        {% if ipaddress.get_role_display == 'VIP' %}
                                {% include 'panel_table.html' with table=duplicate_ips_table heading='Duplicate IP Addresses' panel_class='info' %}
                        {% else %}
                                {% include 'panel_table.html' with table=duplicate_ips_table heading='Duplicate IP Addresses' panel_class='danger' %}
                        {% endif %}
        {% endif %}
~~~

**Comment by jeremystretch** [comment]
I think it makes sense to simply ignore duplicate IPs with the "anycast" role, but for the rest of these you still want to know when you have duplicate IPs. For instance, you should typically only have one VRRP IP in a prefix, which is shared by multiple devices. (Note that we cannot currently map a VIP explicitly to multiple interfaces, though we'll probably implement something in the future.)
