### ISSUE TITLE
Every link in menu doesn't work after upgrade

### ISSUE THREAD

**Issue by quentinsch** [digitalocean/netbox#1377]
After upgrading from version v2.0.7 to v2.1.0 gives an error when switching to any item in the navigation menu.

The main screen displays just fine but clicking any item in the navigation menu displays this error:

![schermafbeelding 2017-07-27 om 10 29 27](https://user-images.githubusercontent.com/7438854/28661787-2652ba9a-72b8-11e7-814f-034b543eed7e.png)

Debug stack trace:

Environment:
Request Method: GET
Request URL: https://netbox.testurl.url/dcim/devices/

Django Version: 1.10.7
Python Version: 2.7.5
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'debug_toolbar',
 'django_filters',
 'django_tables2',
 'mptt',
 'rest_framework',
 'rest_framework_swagger',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'secrets',
 'tenancy',
 'users',
 'utilities')
Installed Middleware:
('debug_toolbar.middleware.DebugToolbarMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'utilities.middleware.LoginRequiredMiddleware',
 'utilities.middleware.APIVersionMiddleware')

Traceback:

File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/lib/python2.7/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/opt/netbox/netbox/utilities/views.py" in get
  126.             table.columns.show('pk')

Exception Type: AttributeError at /dcim/devices/
Exception Value: 'BoundColumns' object has no attribute 'show'

**Comment by quentinsch** [comment]
Ok, I did a step by step upgrade from version v2.0.7 to v2.0.8 and so on. It appears the issue occurs from version v2.0.9 to v2.0.10.

**Comment by jeremystretch** [comment]
You need to upgrade django-tables2 to v1.7.0 or higher as defined in requirements.txt. Using the included upgrade.sh script updates dependencies automatically.
