### ISSUE TITLE
Feature Request: [API] Filter Interfaces By mgmt_only

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1378]
### Issue type: Feature Request

**Python version:** 2.7.12
**NetBox version:** 2.1.0

I would like to filter the interfaces based on the value of the mgmt_only flag:

    # show only mgmt interfaces
    http://netbox/api/dcim/interfaces/?mgmt_only=true

    # don't show any mgmt interfaces
    http://netbox/api/dcim/interfaces/?mgmt_only=false

**Comment by lampwins** [comment]
Can this also be extended so that non-OOB management interfaces with the device's primary IP assigned are included?

**Comment by jeremystretch** [comment]
> I would like to filter the interfaces based on the value of the mgmt_only flag

This is already implemented in the current code. Use `?mgmt_only=True` or `?mgmt_only=False`.

> Can this also be extended so that non-OOB management interfaces with the device's primary IP assigned are included?

This endpoint only returns interfaces, without regard to any IP addresses assigned to them. `mgmt_only` is a boolean field on the interfaces table.
