### ISSUE TITLE
Search of MAC addresses

### ISSUE THREAD

**Issue by vanderaaj** [digitalocean/netbox#1379]
### Issue type: Feature Request

**Python version: 3.5**
**NetBox version: 2.1**

Would like to see the ability to search for MAC addresses that are input into Netbox. After spending some time loading the MACs into the tool, it would be helpful to search them in case the need arises to see where a MAC address lives. Such as a script to map out without the use of CDP/LLDP based on the mac address table.

**Comment by jeremystretch** [comment]
MAC address search is already supported. What specific functionality are you requesting?

**Comment by vanderaaj** [comment]
Then perhaps I should change to a bug request. :(. 
What I have done is go to a device that I have the MAC address for, copy the MAC address, then paste into the search bar. It comes back with no results found.  The search format is nn:nn:nn:nn:nn:nn that I am using to search.

Detailed python version is 3.5.2.

**Comment by mlorentz75** [comment]
Netbox 2.1 / Python 2.7.5 (stock CentOS 7) here. Also can't find a way to search for MAC addresses, or interface descriptions. Couldn't find mention of interfaces in SEARCH_TYPES in netbox/netbox/views.py - is this included in global search at all?

**Comment by mlorentz75** [comment]
@vanderaaj There's actually a way to search for MAC addresses, it's just not included in global search. MACs can be searched for on the Devices list. There is a dedicated input field on the bottom of the search box to the right of that page.

@jeremystretch Shouldn't MAC addresses, or other interface attributes like the description field, be included in global search? Personally I found it somewhat irritating that global search does not provide search results for interface attributes. What do you think?

**Comment by jeremystretch** [comment]
I've enabled this functionality. It does introduce a noticeable delay when searching globally, but the query is only extended to look at MAC addresses if the given value is a valid MAC address, so it's probably fine. Searching using the dedicated MAC filter is much faster, of course.

**Comment by jkrauska** [comment]
Q: Is this functionality NOT in 2.2.1?

It doesn't appear to work for me -- the dcim/filters.py code looks quite similar, but slightly different -- wondering if anyone can assist/confirm.

**Comment by jkldgoefgkljefogeg** [comment]
@jeremystretch I can't get MAC search to work in git master either. Searching for interface MAC (AA:BB:CC:DD:EE:FF format) in top right search box does not work. What is the dedicated MAC filter you mentioned?
