### ISSUE TITLE
Add VPN Support/IPSec Phase 2 encryption domains 

### ISSUE THREAD

**Issue by troxil** [digitalocean/netbox#138]
I have quite a lot of different IPSec tunnels leaving our environment and wish to be able to manage the different encryption domains properly.

Not all of the tunnels are using VTI addressing within the virtual device. 

Short of considering this a circuit and terminating on a virtual tunnel, which is not supported (circuits only on physical interface) - I'm not sure if this available already.

**Comment by Zmegolaz** [comment]
I'd like something like this too, a P2P Circuit. We have some CCC and dark fibers where a port on a device at site A is directly connected to a port on site B. One circuit terminated in two places. #130 is similar to this.

One alternative is to allow regular device connections across different sites.

**Comment by jeremystretch** [comment]
Circuits are intended only to represent physical connections. I definitely wouldn't try to use them for VPN tunnels.

A VPN tunnel is a pretty abstract concept, and probably delves too far into the realm of configuration management to be applicable to NetBox.

**Comment by wmclendon** [comment]
i'm not sure if it is verboten to comment on closed issues, but I think having an option to define a circuit as type VPN and tie them to a virtual interface / subinterface would be very useful.  Beyond IPSec VPNs this could apply to L2 Circuits, GRE Tunnels, etc.  I think there might be a way at least for now to encode most of the important information (for us, anyway) in some of the circuit fields that exist today (ie Tunnel interface as the Circuit ID, far-side 3rd party in comment, or something).

**Comment by jeremystretch** [comment]
Circuits are physical resources; tunnels are not. An IPsec VPN does not have a provider, port speed, commit rate, etc. It wouldn't make sense to use the Circuit model for this purpose.
