### ISSUE TITLE
Aggregate Utilization Incorrect 

### ISSUE THREAD

**Issue by AlJaMa** [digitalocean/netbox#1380]
### Issue type: bug report

**Python version: Python 2.7**
**NetBox version: netbox-2747806021-n03qx (v2.0-beta1) ** 

Hello Digital Ocean!

It appears that in netbox version 2.0-beta1 that the "Utilization" calculation within the "Aggregates" tab includes prefixes even if they are marked as "Container".

(The Utilization graph in the RiR calculates correctly)

Thank you for netbox!

**Comment by jeremystretch** [comment]
Yes, this is intended behavior. Container prefixes are considered to be allocated space.

> netbox version 2.0-beta1

This release is very out of date. The current release is v2.1.0.

**Comment by AlJaMa** [comment]
Thank you! 

Ah, I didn't catch the version out of date. I was using the latest image you have on docker hub. No issue, just built my own container.
