### ISSUE TITLE
Device info retrieval fails if device dual stacked, but netbox is not

### ISSUE THREAD

**Issue by wmclendon** [digitalocean/netbox#1381]
### Issue type:  Bug Report

**Python version: 2.7.12
**NetBox version: 2.1.0

Hello,

Upgraded to 2.1 today, and got NAPALM working with Junos devices -- great work!  Issue I came across is some of my Junos devices have primary IPv4 and IPv6 addresses defined (ie border router), however my Netbox server is not yet dual stacked, and has only link local IPv6 address.  When trying to pull LLDP neighbor or any NAPALM data for device, Netbox reports the following error:

{"detail":"Error connecting to the device: ConnectRefusedError(2001:db8::1)"}

Obviously it cannot reach the IPv6 address, however it never tries the IPv4 address as well

I suspect this is not an issue directly related to Netbox, however curious if something could be implemented where it either will try the IPv6 address first, then the IPv4 address if the IPv6 address fails, or allow some sort of user-defined preference as to which to try.

The workaround I have right now is to just uncheck the 'primary' setting for the IPv6 address for the given devices.

Thanks,

Will

**Comment by jeremystretch** [comment]
NetBox will default to the IPv6 address for a device if it has one, but you can override this behavior by setting [`PREFER_IPV4`](http://netbox.readthedocs.io/en/stable/configuration/optional-settings/#prefer_ipv4) to True in configuration.py.

**Comment by wmclendon** [comment]
Indeed, that fixed it right up -- sorry not sure how I missed that option.  Thanks for response!  i'll close the issue out
