### ISSUE TITLE
Error when upgrade from 1.4.2 to 2.1.0

### ISSUE THREAD

**Issue by azteam** [digitalocean/netbox#1383]
### Issue type:Lost Tenant , Devide Type when Add new Device. Could not map interface connection sites

**Python version:**
**NetBox version:**

**Comment by jeremystretch** [comment]
GitHub issues are intended for reporting bugs and requesting features. For general discussion or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
