### ISSUE TITLE
Update LDAP documentation

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1384]
Pretty straightforward request, but I noticed this is not called out in the documentation:

Currently, the `LDAP.md` file contains the following section:
```
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
}
```
I tried adding "email_address": "mail" as an additional `dict` value, but I needed to use the key name `email` instead of `email_address`.  

In summary, the page for LDAP documentation should be updated to reflect the following:
```
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}
```

**Comment by jeremystretch** [comment]
Looks good, could you put in a PR for this please?

**Comment by bdlamprecht** [comment]
Done.  Pull #1386

FYI - I also noticed that the links  on [netbox.readthedocs.io](http://netbox.readthedocs.io) to both "View" and "Edit" the page (bottom left corner under the heading "On GitHub") the page doesn't work properly.  Wasn't sure the exact problem, but manually found the .md file.

**Comment by jeremystretch** [comment]
Thanks!
