### ISSUE TITLE
Container prefix and caret are shown in different lines

### ISSUE THREAD

**Issue by luisepbueno** [digitalocean/netbox#1389]
### Issue type: bug report

**Python version: 2.7
**NetBox version: 2.1.0

In /ipam/prefix, the right caret and the container prefix are shown in different lines. Adding style "white-space: no-wrap" to span inside <td class="prefix"> should fix it.

![image](https://user-images.githubusercontent.com/5040750/28921999-c6efccc4-782e-11e7-9ddd-9782fdceaf43.png)

**Comment by jeremystretch** [comment]
I'm not able to recreate this. If the page is less than a certain width, the table should scroll horizontally.

**Comment by luisepbueno** [comment]
It seems to happen only in Google Chrome. I couldn't reproduce in Firefox.

Up to 767px screen width it works fine. For wider screens, the **white-space: nowrap** is removed due the media query below and the line breaks.

@media screen and (max-width: 767px)
bootstrap.css:2454
.table-responsive>.table>tbody>tr>td, .table-responsive>.table>tbody>tr>th, .table-responsive>.table>tfoot>tr>td, .table-responsive>.table>tfoot>tr>th, .table-responsive>.table>thead>tr>td, .table-responsive>.table>thead>tr>th {
    **white-space: nowrap;**
}
