### ISSUE TITLE
is it possible to also make a vagrant version?

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#139]
I know there is a docker version in the works but, can a vagrant also be made? For those that do more infrastructure type of things.

**Comment by doon** [comment]
Do you mean something like a chef or puppet recipe to build/deploy, or an actual vagrant box? (do people actually use vagrant in production?)

**Comment by chagara** [comment]
I will say all the above. Using a vagrant version we can test chef puppet ansible or any testing or config changes we decided to made before going to prod.

**Comment by chagara** [comment]
I made a vagrant box but, it looks like they charge to host it on their website. I'm not sure if they offer a free version to open source projects.

**Comment by chagara** [comment]
This has been created and a doc has been created. Made a pull request.
