### ISSUE TITLE
Add Fiber Types to Interface Form Factors

### ISSUE THREAD

**Issue by garysteers** [digitalocean/netbox#1392]
When setting up devices to be patch/panels/ODF it would be good to have the ability to select a Fiber type...

Suggested List (Based on data from https://en.wikipedia.org/wiki/Optical_fiber_connector)

E2000
E2000 APC (Angled version of above)
SC Simple
SC Duplex (A Pair)
LC Simplex
LC Duplex (A Pair)
MPO / MTP (You may need to be able to allow multiple connections on this type of connector)
ST Simplex
ST Duplex

<pre>
# Fiber
IFACE_FF_SCS = 6000 
IFACE_FF_SCD = 6010 
IFACE_FF_LCS = 6100 
IFACE_FF_LCD = 6110 
IFACE_FF_E2K = 6200
IFACE_FF_E2KAPC = 6210
IFACE_FF_MPOMTP = 6300
IFACE_FF_STS = 6400 
IFACE_FF_STD = 6410 

    [
        'Fiber',
        [
            [IFACE_FF_SCS, 'SC Simplex'],
            [IFACE_FF_SCD, 'SC Duplex'],
            [IFACE_FF_LCS, 'LC Simplex'], 
            [IFACE_FF_LCD, 'LC Duplex'],
            [IFACE_FF_E2K, 'E2000'],
            [IFACE_FF_E2KAPC, 'E2000 APC'],
            [IFACE_FF_MPOMTP, 'MPO / MTP'],
            [IFACE_FF_STS, 'ST Simplex'],
            [IFACE_FF_STD, 'ST Duplex'],
        ]
    ],
</pre>

**Comment by jeremystretch** [comment]
NetBox does not yet support patch panels or physical cable plant management. Please see #20.
