### ISSUE TITLE
Bug: generate-rsa-key-pair fails to authorize

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1395]
### Issue type: Bug Report

**Python version:** 2.7
**NetBox version:** 2.1.1

When I access the API endpoint `/api/secrets/generate-rsa-key-pair/`, I only ever get the following response:

    $ curl -H "Authorization: Token db5f9244f020abd5a1a4e1f22c50d0d621a7c867" -H "Accept: application/json; indent=2" https://netbox/api/secrets/generate-rsa-key-pair/
    {
      "detail": "Authentication credentials were not provided."
    }

When I access `/api/dcim/devices/` the same way, all works as expected, so the token is at least valid:

    $ curl -H "Authorization: Token db5f9244f020abd5a1a4e1f22c50d0d621a7c867" -H "Accept: application/json; indent=2" https://netbox/api/dcim/devices/
    {
      "count": 48,
      "next": null,
      "previous": null,
      "results": [
        ...
      ]
    }

**Comment by jeremystretch** [comment]
That's odd, it seems to work fine for me on v2.1.1. Is it possible that the authorization header is getting stripped by the httpd? That would explain the error you're getting. An invalid token will yield:

```
{
  "detail": "Invalid token"
}
```

What happens if you try the same request with a garbage token?

**Comment by cimnine** [comment]
Turns out we don't even require authorisation. This ...

    $ curl -H "Authorization: Token nothinguseful" -H "Accept: application/json; indent=2" https://netbox/api/dcim/devices/

... yields results, as well as ...

    $ curl -H "Accept: application/json; indent=2" https://netbox/api/dcim/devices/

It's just `/api/secrets/generate-rsa-key-pair` and `/api/secrets/get-session-key` that behave different.

We have the following options set in our config:

    ALLOWED_HOSTS = ['*']
    DATABASE = { ... }
    SECRET_KEY = 'blablabla'

Anything else is not configured and hence must be default config.

**Comment by jeremystretch** [comment]
By default, `LOGIN_REQUIRED` is not set, so most views (like `/api/dcim/devices/`) don't require authentication, and the passed token therefore isn't being validated. `/api/secrets/generate-rsa-key-pair` and `/api/secrets/get-session-key` always require authentication, which is why you're getting the error.

Can you provide your httpd (nginx/Apache) configuration?

**Comment by cimnine** [comment]
I can:

```
# SSL VHost
<VirtualHost *:443>
  ServerName netbox


  DocumentRoot /home/netbox/netbox-staging/current/public

  LogLevel warn
  ErrorLog /var/log/apache2/netbox.error.log
  CustomLog /var/log/apache2/netbox.access.log combined

  UseCanonicalName off

  SSLEngine on
  SSLCertificateFile /etc/ssl/certs/SSL_wildcard.crt
  SSLCACertificateFile /etc/ssl/certs/SSL_wildcard.chain.crt
  SSLCertificateKeyFile /etc/ssl/private/SSL_wildcard.key
  Alias /ssl-check/ "/var/www/"

    # S_apache2::Directive[s_apache2::vhost netbox directives]
    SetEnv RAILS_ENV staging
  SetEnv RACK_ENV staging
  ErrorDocument 503 /system/maintenance.html
  RewriteEngine On
  RewriteCond %{REQUEST_URI} !\.(css|gif|jpg|png)$
  RewriteCond %{DOCUMENT_ROOT}/system/maintenance.html -f
  RewriteCond %{SCRIPT_FILENAME} !maintenance.html
  RewriteRule ^.*$  -  [redirect=503,last]

    # S_apache2::Directive[netbox wsgi]
    Alias /static/ /home/netbox/netbox-staging/current/netbox/static/
    WSGIDaemonProcess netbox-staging user=netbox processes=5 maximum-requests=200 inactivity-timeout=1800 python-home=/home/netbox/netbox-staging/current/virtualenv python-path=/home/netbox/netbox-staging/current/netbox
    WSGIProcessGroup netbox-staging
    WSGIScriptAlias / /home/netbox/netbox-staging/current/netbox/netbox/wsgi.py

    # S_apache2::Directive[netbox sso]
    CASSSOEnabled On
CASAllowWildcardCert On

CASLoginURL https://sso/login
CASValidateURL https://sso/serviceValidate
CASProxyValidateURL https://sso/proxyValidate

<Location />
  CASScope /
  AuthType cas
  AuthName "netbox"
  Require expr %{REMOTE_USER} =~ /@company$/
</Location>


    # S_apache2::Directive[netbox api bypass]
    <Location /api/>
      Require expr "%{REMOTE_USER} =~ /@company$/"
      Require ip 1.1.1.81
      Require ip 1.1.1.125
    </Location>
</VirtualHost>
```

Somewhat redacted, but no Apache directives (besides some `ServerAlias`es) have been removed.

**Comment by jeremystretch** [comment]
According to [the docs](http://netbox.readthedocs.io/en/stable/installation/web-server/#option-b-apache) (I don't use Apache myself) you probably need:

```
    # Needed to allow token-based API authentication
    WSGIPassAuthorization on
```

Please try adding that to the VirtualHost config and restarting Apache.

**Comment by cimnine** [comment]
Thanks, that was the missing piece.
