### ISSUE TITLE
Search for IP without CIDR causes error

### ISSUE THREAD

**Issue by awfki** [digitalocean/netbox#1396]
### Issue type: bug report

**Python version: 2.7.5**
**NetBox version: 2.1.1**

Searched for an IP address in the top search box and got the following:

```
<class 'django.core.exceptions.ValidationError'>

[u'cannot switch EUI versions using copy constructor!']
```

If I include CIDR mask (e.g. /24) it works properly. Also works properly with less than four octets.

**Comment by jeremystretch** [comment]
Duplicate of #1388
