### ISSUE TITLE
Clouds in topology drawings

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1399]
### Issue type: Feature Request

I have been working with the topology maps and currently, I am using a "site" as my WAN and a "site" as the Internet that I can then assign my WAN and INET ISP provider devices interfaces as connected to these sites. Then with my equipment attached to the ISP equipment a topology map gives a visual representation from a user access switch, through the distribution block, through the WAN aggregation block, across my Internet WAN and out the other side down to the user access switch. This little map isn't really for me, it's more for the desktop folks within my organization so that they can follow the path while troubleshooting end points.

It would be really nice to have some sort of the WAN/Internet option or cloud option to complete the connectivity of multiple sites without having to create "sites" that are not real.

**Comment by jeremystretch** [comment]
The topology map feature in NetBox is intended only to provide a convenient mechanism for illustrating a specific set of links. It is not a suitable replacement for curated documentation. You're going to be much better off drawing real maps with labels applicable to the context.

**Comment by kopacko** [comment]
I have Visios. But this is more of a centralized way of displaying said data. It's also for the rest of the team to view without having to deal with Visio. I've attached the beginnings of what I am building to show how each site is topologically connected via the WAN. The bottom half of the map will have the other WAN connections, Internet connections, etc.
 
![Uploading NetBox Cloud.png…]()

**Comment by jeremystretch** [comment]
Do you want to extend the topology map rendering to include a "cloud" representing the provider of a circuit with only one termination? I think that would be reasonable.

> I have Visios.

You can export them as PNGs and upload them as image attachments to individual sites.

**Comment by kopacko** [comment]
Yeap that's exactly what I am trying to accomplish is a central "object" to represent public or private central points. Like a WAN object that I can add "interfaces" to in order to join all my sites together.

Yes I know I can export the Visios but with a simple regex, my WAN topology could be dynamically represented by that awesomeness that is NetBox.

**Comment by jeremystretch** [comment]
> Like a WAN object that I can add "interfaces" to in order to join all my sites together.

This would not be something we'd support in NetBox. NetBox is intentionally limited to defining real, concrete connections; it does not support abstraction.

**Comment by kopacko** [comment]
These are real, physical connections. These would be the Z side of Internet and WAN circuits collated into one object.

**Comment by jeremystretch** [comment]
"The WAN" isn't a discrete physical object, so it doesn't get modeled in NetBox. The topology mapping functionality in NetBox is an ancillary feature provided as a convenience. Extending the data model solely for the sake of more complex drawings is out of scope for NetBox.

**Comment by kopacko** [comment]
Well that is incredibly disappointing. Thanks.
