### ISSUE TITLE
Cannot edit prefixes or ip addresses 

### ISSUE THREAD

**Issue by mhmsh** [digitalocean/netbox#140]
I get server error whenever i try to edit a prefix or ip address. Im running the lastest version upgraded from a 1.0.0. Error was also present in v1.0.0

**Comment by mhmsh** [comment]
Im thinking its because i accientally used a local caracter, like æøå. Could that be the reason?

**Comment by mdlayher** [comment]
@mhmsh can you provide the exact steps you used to make this problem occur?

**Comment by augustocarlson** [comment]
When I edit anything that has accentuation on it, I get the error below:

" Server Error

There was a problem with your request. This error has been logged and administrative staff have been notified. Please return to the home page and try again.
If you are responsible for this installation, please consider filing a bug report."

For example, site with the name: "São José".

**Comment by jeremystretch** [comment]
I tweaked the way the status message was generated upon creating/editing an object in 2829303. I'm now able to create, edit, and delete a site named São José with no problem. Please clone the `develop` branch and let us know if it's still a problem.

**Comment by jeremystretch** [comment]
Going to close this one for now but please comment here or open a new issue if you find that this is still a problem.

**Comment by mhmsh** [comment]
Im still seeing issues with editing prefixes. Another symptom im seeing is that i cannot select a vlan when adding a prefix, the dropdown shows nothing.

**Comment by augustocarlson** [comment]
The problem still persists. I can't delete the VLAN. I also tried to add an Site and the same error occurs. Using the develop branch.

**Comment by mhmsh** [comment]
I still have issue in 1.1.0-dev

UnicodeEncodeError at /ipam/vlans/15/
'ascii' codec can't encode character u'\xa0' in position 5: ordinal not in range(128)
Request Method:	GET
Request URL:	http://netdoc-01.corp.systemhosting.dk/ipam/vlans/15/
Django Version:	1.9.7
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode character u'\xa0' in position 5: ordinal not in range(128)
Exception Location:	/opt/netbox/netbox/ipam/models.py in display_name, line 370
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/opt/netbox-1.1.0-dev/netbox/netbox',
 '/opt/netbox/netbox',
 '/opt/netbox-1.1.0-dev/netbox',
 '/usr/bin',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Thu, 7 Jul 2016 07:05:22 +0000

**Comment by mhmsh** [comment]
After re-populating the data it seems to be working.

Thanks

**Comment by augustocarlson** [comment]
Hi all!

I started all from scratch with v1.1.0 and it is now working fine.

Thank you!
