### ISSUE TITLE
Interface name length

### ISSUE THREAD

**Issue by Notum** [digitalocean/netbox#1402]
Trying to add new Interface with PowerShell I get this error: Invoke-RestMethod : {"name":["Ensure this field has no more than 30 characters."]}
We have Network Interface Names in Windows with more then 30 characters. 
Can you increase interface name length?

Ver. 2.1.2

**Comment by jeremystretch** [comment]
Can you provide a list of examples please?

**Comment by Notum** [comment]
You mean examples of long adapter names? Sure!
We have Hyper-V cluster which has a lot of virtual interfaces.
As an example: vEthernet (live-migration-network) (34 symbols)

**Comment by lampwins** [comment]
With the up coming virtualization feature, I will add here that in certain situations in VMware NSX, interface names are UUIDs. Specifically in some VTEP integrations.

**Comment by jeremystretch** [comment]
What is the field length being proposed?

**Comment by Notum** [comment]
50 symbols?

**Comment by bellwood** [comment]
64 characters should suffice.

That should cover most UUID and overly verbose labels.
