### ISSUE TITLE
Allow ip address to be assigned to multiple devices 

### ISSUE THREAD

**Issue by Atoms** [digitalocean/netbox#1405]
Feature Request

When UNIQ ip addresses is enabled there is no possibility to add one ip address to multiple devices (with disabled uniq you can add 2 times one address with different device), when ip address role is VIP/Anycast/VRRP/HSRP/GLBP

When i find ip address and it's role is one of those mentioned, i want to see devices it can float around.

**Comment by jeremystretch** [comment]
How are you proposing we alter the data model?

**Comment by Atoms** [comment]
We talked about this with college and got to point that we don't know the right solution, but one can be:
introduce table ip_addresses_interface as one to many relation (one ip address can be assigned to  multiple interfaces) and use in case role is one of those which will have this feature.. 

I don't know how easy or hard implementation and validation of this could be. 

In Frontend for ip address which is for this role can be some link to assign more devices to this ip or something like that.

**Comment by kopacko** [comment]
Since I am no programmer, from what I can tell is...the IP address is assigned to an interface. If you coded it such that an object (the IP address in this case) can have multiple assigned interfaces, that would allow for VIPs, HSRPs, etc to more easily assigned across multiple physical devices.

**Comment by jeremystretch** [comment]
The assignment of VIPs to interfaces isn't as simple as modifying the relationship. VIP assignment typically encompasses additional data as well (e.g. VRRP group and priority). I want to keep the direct relationship of IP address to interface. The representation of VIP associations is probably better achieved by introducing a new `VIPAssignment` model to accommodate the additional data.

**Comment by jeremystretch** [comment]
The issue of VIP group tracking can be addressed at a later time. We're going to keep the direct assignment of other IPs to interfaces.

**Comment by Phhere** [comment]
Any update on this ?

**Comment by DanSheps** [comment]
@Phhere It was closed with a reasoning.  I am not sure what kind of update you want.
