### ISSUE TITLE
Add Description or Comment to Inventory Items

### ISSUE THREAD

**Issue by netwavetech** [digitalocean/netbox#1407]
We would love to see a description or comment field available in inventory items.  This would allow for things like RAM to be labeled as DDR3-1600  etc   As this information is not always clear from a part number.  Makes for a good double check as techs are upgrading hardware.

**Comment by netwavetech** [comment]
As well as adding a date field.  (i.e. date added to the system)

**Comment by jeremystretch** [comment]
Duplicate of #1121. A description field has already been added.
