### ISSUE TITLE
Add Documents / Files Section (Update to Images)

### ISSUE THREAD

**Issue by netwavetech** [digitalocean/netbox#1408]
While we can upload images currently.  It would be great to be able to upload documents and or files to they system.   

Simply renaming Images sections to Files and allowing for PDF upload would be an easy fix.

**Comment by jeremystretch** [comment]
Document storage is out of scope for NetBox; we don't want to turn it into a file store. Images are nice because you can link them to specific contexts, but for general file storage you're better off linking to an external source. #969 should make this easier to do.

**Comment by InsaneSplash** [comment]
I'd like to add to this old issue in saying that to attach PDF files is a real must. It allows one to attach a diagram produced through visio as well as some images are stored in PDF files.

**Comment by altmind** [comment]
I also want to give 👍 to this idea. My usecase is attaching AIDA64 html hardware reports to netbox nodes. 
This feels like it belongs to netbox and fits in context well.
