### ISSUE TITLE
Add Hostname / Nameserver Options to devices.

### ISSUE THREAD

**Issue by netwavetech** [digitalocean/netbox#1409]
Currently we are putting the hostname / nameservers in comments.  Be nice to have it as option when editing a device. 

As well as be able to assign Nameservers to IP addresses

**Comment by jeremystretch** [comment]
Why wouldn't you use the `name` field for the device's name?

Miscellaneous attributes like name servers would be covered by #1349. Alternatively, you could create custom fields.

**Comment by netwavetech** [comment]
Devices often change hostname names,  so we name the device based off an internal naming system.  

As far as the nameservers, we provide nameservers to our clients using our whitelabel tld, so it would be nice to be able to track them like we do IPs as they get recycled sometimes.

**Comment by jeremystretch** [comment]
Yeah, sounds like custom fields are the way to go in your case.

**Comment by thefreakquency** [comment]
In our case, hostnames are related to an IP, not to a device. A single device can have multiple IP which can have multiple hostnames. 
It would be nice to have those hostnames showed on the Device page, based on the list of IP associated to this device.

**Comment by jeremystretch** [comment]
@thefreakquency You're describing DNS management (#166). Devices each typically have exactly one hostname defined locally (e.g. `hostname` on Linux).
