### ISSUE TITLE
Issue: Bug Report. When trying to attach an image to a site the website crashes

### ISSUE THREAD

**Issue by traveler3468** [digitalocean/netbox#1411]
Bur report: Attempting to add an image to a site and the website crashes every time.
I get this error messeage:

[Errno 13] Permission denied: '/opt/netbox-2.1.2/netbox/media/image-attachments/site_544_FEFCU.png'

**Python version: 2.7.13
**NetBox version:2.1.2

**Comment by jeremystretch** [comment]
Please see #1305
