### ISSUE TITLE
[ Feature Request ] Site Information

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1413]
### Issue type: Feature Request

**Python version:**
**NetBox version:**

This feature request is related to site and tenant information. In tracking our sites and providing data related to a site, it would be nice to have the ability to add custom sections or critical contact information related to power, HVAC, building management, etc. Most of this information is incredibly important from an outage/disaster perspective and would information that would apply to an entire building (not necessarily tenant specific, but maybe).

It would be nice to have the same ability within the tenant information for pertinent internal contact information, vendor support information, etc related to a location.

**Comment by jeremystretch** [comment]
You may want to add custom fields for some of this, but please keep in mind that NetBox is primarily an IPAM/DCIM application and does not address facilities management. #1344 has been opened to explore the possibility of more flexible contact assignment.

**Comment by kopacko** [comment]
Well add me to the list for the DC contact/support info request. That's pretty important for a site.

**Comment by slindermann** [comment]
Please add me to the list as well. More / Custom site information fields (optional!) would be very helpful in our scenario.
