### ISSUE TITLE
Selecting a site on the rack list view should update the available rack groups to filter by

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1414]
### Issue type: Bug report

**Python version:** 3.4.3
**NetBox version:** 2.1.2

1. Create several rack groups, each associated to different sites
2. Go to the list of racks
3. Select a site to filter by

When one or more sites have been selected, the list of available rack groups should be updated to include only those which belong to the selected sites. (This is similar to how selecting a manufacturer on the device list will update the list of device types to filter by.)

**Comment by bellwood** [comment]
This bug is still present.

While clicking on a site does filter the groups, etc - once you hit "apply" the filtering is lost.
