### ISSUE TITLE
Sites Mapping & navigation

### ISSUE THREAD

**Issue by thefreakquency** [digitalocean/netbox#1417]
### Issue type: Feature request
**Python version:**
**NetBox version:**
 
I would like to be able to have a visual representation of the sites location on a Map. 
Like: https://support.solarwinds.com/@api/deki/files/23574/m9.png

This could be represented at different levels: 
     *  On the site page (/dcim/sites/site_slug/) 
     *  On a Region page (/dcim/sites/?region=Region_slug)
     *  On the main page (/)

Site placement could be done automagically either via the physical address field or a Lat/Long custom property of some sort. 

In an ideal world, we should have the option to host internally the tile server as some users don't have internet access from their network, but I understand this would require a lot of work. As a starting point, showing a map from OpenStreetMap or similar provider should be a great start. 

I understand that a possible workaround would be to use the graph feature, but it's not available first hand on the page, nor feasible on a bigger scale (multi site placement for regions or main page). 

This feature would provide a great visual overview. Navigation could be enhanced if sites waypoints were clickable. This is something that gives my organization loves in some tools (Like SolarWinds NPM or internal apps).

**Comment by jeremystretch** [comment]
Geographical mapping was raised in #178. I'm going to close out this issue as a duplicate but you may want to copy your use case as a comment to that issue (and give it a +1).

**Comment by thefreakquency** [comment]
Oops ;) missed this one. Thanks for being thorough :)
