### ISSUE TITLE
 Mounting Nginx volume to NetBox (docker)

### ISSUE THREAD

**Issue by Mrcortez34** [digitalocean/netbox#1418]
I'm having issues with mounting my Nginx volume to the running Netbox volume.

I have set this up using docker. So, the Netbox is running just fine. I'm just having issues with getting the nginx to start. 

system # systemctl status nginx.service 
● nginx.service - Runs the nginx server
   Loaded: loaded (/etc/systemd/system/nginx.service; static; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2017-08-09 22:36:55 UTC; 3s ago
  Process: 29782 ExecStart=/usr/bin/docker run --rm --name nginx -v --volumes-from netbox -p 80:80 -t nginx:1.12 nginx -g daemon off; -c /etc/netbox-nginx/nginx.conf (code=exited, status=125)
  Process: 29776 ExecStartPre=/usr/bin/docker pull nginx (code=exited, status=0/SUCCESS)
  Process: 29768 ExecStartPre=/usr/bin/docker rm nginx:1.12 (code=exited, status=1/FAILURE)
 Main PID: 29782 (code=exited, status=125)
      CPU: 28ms

Aug 09 22:36:55 ip-10-1-59-.ec2.internal systemd[1]: nginx.service: Main process exited, code=exited, status=125/n/a
Aug 09 22:36:55 ip-10-1-59-.ec2.internal systemd[1]: nginx.service: Unit entered failed state.
Aug 09 22:36:55 ip-10-1-59-.ec2.internal systemd[1]: nginx.service: Failed with result 'exit-code'.

**Comment by Mrcortez34** [comment]
also, I'm not using docker-compose

**Comment by jeremystretch** [comment]
GitHub issues are intended for reporting bugs and requesting features. For general discussion or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
