### ISSUE TITLE
[ Feature Request ] Color Coded Connections

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1422]
### Issue type:feature request

**Python version:**
**NetBox version:**

I have attached a single ESX host server and built a quick topology map to represent it's connectivity to our private WANs, the Internal SANs, and to the Internet and the various paths that it follows. It would be really nice to assign colors (even if it is just primary colors) to a connection.

RED = SAN
BLUE = LAN
GREEN = MGMT
etc

![netbox connection colors](https://user-images.githubusercontent.com/1976185/29244253-281fd0ba-7f79-11e7-973b-c14268d6bf56.jpg)

**Comment by jeremystretch** [comment]
Like I said in #1399, the topology mapping feature is intended as a mere convenience for quickly illustrating a set of connections. It is not intended to convey information other than the basic layout of links. We won't be extending it beyond the functionality that is already in place. If you're interested in such a tool, you can copy the logic topology maps use in your own tool and integrate with the NetBox API to build custom maps.

**Comment by kopacko** [comment]
I am only asking for some customization options for the color of the lines. Circuits show up as blue and planned lines show up as dotted lines. It can't be that far of a reach to add some color options, can it?
