### ISSUE TITLE
Duplicate devices

### ISSUE THREAD

**Issue by maggnus** [digitalocean/netbox#1424]
It will be very convenient if we have ability to create duplicate devices.

**Comment by maggnus** [comment]
Purpose: We have few racks filled with the same type of server equipment. At this moment I have to add all servers one by one with the same fields (except unit assign) and it's bit annoying.

Implementation: It could be done in two ways.
1) Duplication button on device level.
[Edit this device] [Duplicate] [Delete this device]
2) Using numeric ranges on adding stage.
Add device => Name: Server[1-10]

**Comment by jeremystretch** [comment]
The first proposal would fall under #33. The second I don't think we want to implement natively, and would be better achieved via the API.
