### ISSUE TITLE
Formatting of data within status tab of devices

### ISSUE THREAD

**Issue by BMH64** [digitalocean/netbox#1429]
### Issue type: Bug

Properly format data under "status" tab within a device integrated with napalm

**Python version:** 3
**NetBox version:** 2.1.3

   Currently under device status when integrating with napalm the uptime is show as a large number which I'm assuming to be seconds. Should be human readable such as YEARS:MONTHS:WEEKS:DAYS:etc;
Also the memory is formatted incorrectly shows as 

Available | 28445500MB
-- | --
Used | 10729512MB

**Comment by jeremystretch** [comment]
We can probably do something with the uptime. It looks like your device is reporting memory in KB rather than MB. I'm not sure whether NAPALM's [`get_environment()`](http://napalm.readthedocs.io/en/latest/base.html#napalm_base.base.NetworkDriver.get_environment) takes a stance on unit.

**Comment by jeremystretch** [comment]
I'm just going to omit the memory unit for now since it seems to differ by platform.
