### ISSUE TITLE
New interface form factor: CX4

### ISSUE THREAD

**Issue by aaroneg** [digitalocean/netbox#1431]
We actually have some CX4 types, and I could not find an easy way to add this interface form factor. 
https://en.wikipedia.org/wiki/10_Gigabit_Ethernet#10GBASE-CX4

**Comment by jeremystretch** [comment]
I'm not familiar with 10GBASE-CX4 myself, but isn't it a physical medium specification similar to 10GBASE-SR/LR? NetBox is only concerned with the port type, which would probably be XFP or X2.

**Comment by aaroneg** [comment]
X2, if this Wikipedia article is to be believed.

On Aug 17, 2017 8:54 AM, "Jeremy Stretch" <notifications@github.com> wrote:

I'm not familiar with 10GBASE-CX4 myself, but isn't it a physical medium
specification similar to 10GBASE-SR/LR? NetBox is only concerned with the
port type, which would probably be XFP or X2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/digitalocean/netbox/issues/1431#issuecomment-323080420>,
or mute the thread

**Comment by zsandrus** [comment]
10GBASE-CX4 should be considered a fixed ethernet form factor. There are X2 and SFP+ modules available with 10GBASE-CX4 connectors, but they are also available on some NICs and switches.

See this card as an example: http://www.colfaxdirect.com/store/pc/viewPrd.asp?idproduct=956
