### ISSUE TITLE
Circuits Searchable by Committed Information Rate

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1432]
### Issue type: feature request

**Python version:**
**NetBox version:**

Would it be possible to get the CIR field native to the circuit info searchable or indexed in some way that is then searchable?

**Comment by jeremystretch** [comment]
The circuits view already supports a `commit_rate` filter. Are you asking for it to be added to the search form on the web interface?

**Comment by kopacko** [comment]
Yes sir, that's what I am curious about. Right now, I've created a second custom field that contains the same info in order to search for circuits based on bandwidth.
