### ISSUE TITLE
API - device_bay_templates - Filter key incorrect

### ISSUE THREAD

**Issue by lamiskin** [digitalocean/netbox#1433]
Netbox version: v2.1.3

https://github.com/digitalocean/netbox/blob/3aa072b4375750c0bbcd6bf9b2d849a5843b04d1/netbox/dcim/filters.py#L274

I believe the line above should be ``device_type_id`` and is a mistype.

![image](https://user-images.githubusercontent.com/11305491/29396841-d6f4d170-835d-11e7-8c62-71dfa7b0b6ba.png)

**Comment by jeremystretch** [comment]
Fixed in 7843a6b. Kept the filter name the same, just corrected the field it points to.
