### ISSUE TITLE
Add the possibility to create new IP roles

### ISSUE THREAD

**Issue by tdmike** [digitalocean/netbox#1434]
As the titel says, would it be possible to create custom roles for IP addresses. Currently it's only available for VLANs.

**Comment by jeremystretch** [comment]
IP address roles describe the type of IP address, not its function. There are a limited number of practically relevant roles (loopback, anycast, VRRP, etc.), which is why they are statically defined. What role(s) are you proposing be added?

**Comment by kopacko** [comment]
I'd have to agree that customizable roles would be very nice.

There are many good roles of an IP:
1 - BGP peering
2 - Failover
3 - Heartbeat
4 - Replication
5 - etc

The role of the IP, to me, is the purpose/reason that the IP exists.

**Comment by jeremystretch** [comment]
@kopacko You are confusing applications with the manner in which an IP address is assigned. For instance, BGP peering can be done on regular unicast IPs or on loopback IPs.

**Comment by kopacko** [comment]
That may be the case, but for those who do not understand unicast, multicast, etc (e.g. the local techs in each of my locations) will not.

Assigning a role that non-technical to understand makes it easier for them.

**Comment by tdmike** [comment]
Well I mainly request it since I can not clearly specify which IP is the gateway.

**Comment by jeremystretch** [comment]
Perhaps it would help to explain the existing IP roles:

* Default (none): A normal IP, optionally assigned to an interface
* Loopback: An IP assigned to a loopback interface
* Secondary: An IP assigned to an interface as a secondary IP (i.e. `ip address x.x.x.x secondary` in Cisco IOS)
* Anycast: An IP that has other instances assigned elsewhere (an intentionally duplicate IP)
* VIP: A floating IP address
* VRRP/HSRP/GLBP: A VIP managed by one of the respective NHRP protocols

@tdmike The qualification of an IP as the default gateway for a prefix is a related but different matter. Any of the above (with the exception of loopback) could be the default gateway for a prefix. There are other attributes you can use in determining the gateway IP. For example, whether it's the first or last usable IP in the prefix, whether it's assigned to an interface on a router, etc.

**Comment by sulisu** [comment]
@ jeremystretch  Please put this definition of ip address roles  into document. Someone using Fortigate firewall might think VIP as different meaning.

**Comment by sulisu** [comment]
@jeremystretch Please put this definition of ip address roles into document. Someone using Fortigate firewall might think VIP as different meaning.

**Comment by jeremystretch** [comment]
@sulisu Feel free to submit and issue for it if you'd like to contribute a PR.
