### ISSUE TITLE
Prefixes /w IPs in different VRFs

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1436]
### Issue type: bug report

**Python version:**
**NetBox version:**

Jeremy,
I am honestly not sure if this a bug or should be feature request. I noticed that as I get more IPs into our setup, that a prefix where two VRFs meet, do NOT show all IPs.

For example, in a /30 routed linked between me and a provider the .1 IP would be a part of one BGP ASN and the .2 IP would be a part of another BGP ASN. Not sure what I should do to account for that.

**Comment by jeremystretch** [comment]
VRFs and ASNs are entirely separate concepts. Prefixes and IPs are grouped by VRF; as in the real world, each prefix or IP can belong to only one VRF (or the global table). The assignment of ASNs has no effect on this.

**Comment by kopacko** [comment]
They are entirely separate concepts, sure. A VRF is just a organization of routes in a routing table.

"As in the real world" .... nice jab thanks.

Umm but multiple IPs, within a given prefix, can be members of different VRFs. A /24 could a 10 IPs in 10 different VRFs. Which is where my question came up. Several /30's in different VRFs within the same /24 prefix.

No idea why I mentioned AS, they had nothing to do with my train of thought.

**Comment by N-Mi** [comment]
Hi,

I'm evaluating Netbox 2.2.2 (I think about migrating from Racktables to Netbox), and I have the same issue/request.

I have many prefixes that have /31 or /32 IPs in differents VRFs, and I can't find a way to fit this into Netbox.

I think having to associate a prefix to a VRF is a bit rigid. Maybe adding an option like "Shared across multiple VRFs" would solve this.

**Comment by mvangoor** [comment]
@jeremystretch: Can you re-open this?
