### ISSUE TITLE
API returning 200 on POST, not saving new object

### ISSUE THREAD

**Issue by cslingerland** [digitalocean/netbox#1437]
### Issue type:

**Python version: 2.7
**NetBox version: latest

I'm using the following code in a python script to try and post to the API with no luck. Is this an issue with the system?

```
import requests

url = 'https://hostname/api/dcim/sites'
data = {"name" : "my new site" , "slug" : "my-new-site"}
headers = {'Authorization': 'Token f8581ac22fca6067ad1fa65sd1fa561c57138f08e8', 'Content-Type': 'application/json', 'Accept': 'application/json; indent=4'}
response = requests.post(url, json=data, headers=headers, verify=False)
```

**Comment by jeremystretch** [comment]
GitHub issues are intended for reporting bugs and requesting features. For general discussion or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
