### ISSUE TITLE
multiple same prefixes/addresses in IPAM for different system

### ISSUE THREAD

**Issue by loulasedna** [digitalocean/netbox#1438]
Hi, 

In my company, I have multiple separate sub-systems which have the same prefixes/addresses/vlans/VRFs. 
ex :
system-A_prefix-A(192.168.1.0/24)_server-A_192.168.1.1/24 (vlan=VRF=admin), 
system-B_prefix-A(192.168.1.0/24)_server-A_192.168.1.1/24(vlan=VRF=admin)

When I try to put that into IPAM section, I can add the same prefix two times (192.168.1.0/24), but there is logically a duplicate prefixe and if i had a sub prefixes like 192.168.1.0/25, this last has more than one parent.

How can I add multiple systems in netbox with the same prefixes/addresses/VRF/VLAN ?

Thanks you for your help :)

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
