### ISSUE TITLE
Enable import of InventoryItems

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#144]
Would make this process so much easier

**Comment by jeremystretch** [comment]
The original intention was to import modules automatically via SSH/NETCONF/SNMP/whatever. This works currently for most Cisco IOS and Juniper gear.

We can probably implement a manual import feature, but validation is going to be a bit tricky due to the hierarchical arrangement of modules.

**Comment by bellwood** [comment]
Well CSV import would be just fine, it doesn't have to be integrated

**Comment by jeremystretch** [comment]
19 months later...
