### ISSUE TITLE
API post new device custom_fields is and invalid keyword

### ISSUE THREAD

**Issue by Atoms** [digitalocean/netbox#1443]
### Issue type
[x] Bug report

### Environment
* Python version:  3.4
* NetBox version:  2.1.3

### Description
When using API trying to create new device with custom_fields got error:
`<pre><strong>&lt;class &#39;TypeError&#39;&gt;</strong><br />
&#39;custom_fields&#39; is an invalid keyword argument for this function</pre>`

Works in 2.1.2 version

**Comment by Atoms** [comment]
i think this commit introduced issue: https://github.com/digitalocean/netbox/commit/c394985b1be3f2126363782018af9acd3e4865cf

**Comment by jeremystretch** [comment]
Could you provide the exact request you made please?

**Comment by Atoms** [comment]
the post request i'm making: 
`{
  "tenant": "1",
  "platform": "8",
  "name": "test1",
  "device_type": "6",
  "site": "1",
  "device_role": "8",
  "custom_fields": { "ansible_groups": "xx,yyy,zzz" }
}`
