### ISSUE TITLE
Possibility of adding secrets without device

### ISSUE THREAD

**Issue by tdmike** [digitalocean/netbox#1446]
We sometimes have users/password which are assigned to multiple devices, so they are generic. I personally like to see the ability to add secrets which should not be assigned to a specific design.

**Comment by jeremystretch** [comment]
Tools like [Vault](https://www.vaultproject.io/) and [LastPass](https://www.lastpass.com/) are better suited for that. The only advantage of storing secrets in NetBox is being able to associate them with particular devices.

Also, in the future please use the [GitHub issue template](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md).

**Comment by tdmike** [comment]
We're not talking about passwords for applications or such, we're talking about generic passwords like snmp passwords which are kept the same for a reason. I would not like to have to assign them to every devices separately but I would like to add them to the secrets of netbox since it's related to the devices there.

**Comment by kopacko** [comment]
Adding secrets to sites, circuits, manufacturers, providers would be nice.

**Comment by candlerb** [comment]
There was some old discussion in #69, now closed.

When sharing passwords between devices, probably the best bet currently is to add a Custom Field containing just the password ID (e.g. "SWITCH-SNMP-4"), which you look up in a separate password application like Vault or [Passbolt](https://www.passbolt.com/faq)

It is also not yet decided whether Netbox will support secrets for [virtual machines](https://github.com/digitalocean/netbox/issues/142#issuecomment-326590192).
