### ISSUE TITLE
Connection required IP address 

### ISSUE THREAD

**Issue by bitratio** [digitalocean/netbox#1448]
Currently, the connections between devices require an IP address.

We have interfaces that are either part of MLAGS or LAGS or are just plain layer2 links between switching and routers and thus do not have address space assigned.

Can we have a feature where we can make a device interface part of a LAG or LACP or just select that it's a layer2 trunk or access port with no address space assigned?

Cheers

Will

**Comment by jeremystretch** [comment]
> Currently, the connections between devices require an IP address.

You can connect interfaces regardless of whether they have an IP address assigned. The button with a plus sign adds an IP address; the button with two arrows facing each other connects interfaces.
