### ISSUE TITLE
FR: Allow images to be attached at the Tenant level

### ISSUE THREAD

**Issue by traveler3468** [digitalocean/netbox#1449]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  2.1.2

### Description
I will start off by saying that I have read #1039 #1408 #1416 and #969.
I will also say that I have VERY little experience with regex.

These dont quite cover what I was hoping to have. I am with you that NetBox does not need to be a file/document repository but I feel that the image attachment at the site or device level doesnt quite capture the broader picture that Im hoping to get.

By having the image attachment at the Tenant level, you could have a fantastic place to upload a network map image to show the network topology of the Tenant as a whole. I know that there is the Topology Map feature in the admin section of the site but I feel that its to restrictive. First you are only able to access the admin section if you are a superuser and, Second, the map design is limited to the hierarchical layout that is offered by the regular expression format. Third (kind of joking) who likes regular expressions anyway? Also (and this may just be my lack of knowledge or drive to learn regex) each map may not need ALL the connections displayed that a certain device has. For example if I just want to show the circuits that connect different sites and not the connections on the LAN.
Having a image attachment at the tenant level would also allow users to be able to attach the files without needing a superuser to create the map.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by traveler3468** [comment]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   


### Environment
* Python version:  2.7
* NetBox version:  2.1.2

### Description
I will start off by saying that I have read #1039 #1408 #1416 and #969.
I will also say that I have VERY little experience with regex.

These dont quite cover what I was hoping to have. I am with you that NetBox does not need to be a file/document repository but I feel that the image attachment at the site or device level doesnt quite capture the broader picture that Im hoping to get.

By having the image attachment at the Tenant level, you could have a fantastic place to upload a network map image to show the network topology of the Tenant as a whole. I know that there is the Topology Map feature in the admin section of the site but I feel that its to restrictive. First you are only able to access the admin section if you are a superuser and, Second, the map design is limited to the hierarchical layout that is offered by the regular expression format. Third (kind of joking) who likes regular expressions anyway? Also (and this may just be my lack of knowledge or drive to learn regex) each map may not need ALL the connections displayed that a certain device has. For example if I just want to show the circuits that connect different sites and not the connections on the LAN.
Having a image attachment at the tenant level would also allow users to be able to attach the files without needing a superuser to create the map.

**Comment by jeremystretch** [comment]
This has already been addressed in the issues you referenced. Topology maps are not intended to replace traditional, detailed network diagrams, and there is no reason to store those in NetBox.

**Comment by InsaneSplash** [comment]
I don't see any reason not to allow images to be attached to tenants in the same way as it is exposed for sites and devices. I can think of a number of reasons why it makes sense to allow it, but ultimately it would be up to the user if its used or not.

**Comment by InsaneSplash** [comment]
I'd like to bump this, as I do think that attaching a image to a tenant is just as important as any other area. I also think this is adding flexibility to the project and the admin of their site can choose to use it.
