### ISSUE TITLE
When adding a device from Rack Elevation add a list of devices to choose from

### ISSUE THREAD

**Issue by traveler3468** [digitalocean/netbox#1451]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  2.1.2

### Description
I was thinking that it would be nice to have the ability to select from existing devices in NetBox when adding a device from the rack elevations view. I think the devices would show up in a drop down list and be filtered based in the tenant/site that the rack belongs too. This would allow for devices to be created and tracked in NetBox before they were racked and also allow the ease at which devices are added to the rack space.

Thoughts?

**Comment by jeremystretch** [comment]
How specifically would you implement this? Could you mock up some screenshots?

**Comment by cslingerland** [comment]
![addexistingdevice](https://user-images.githubusercontent.com/2353683/29892576-197ad816-8d9d-11e7-8802-34ab6e19f41b.png)

Here's what I mocked up. It's probably the sloppiest way of doing it, but it gets the job done. I've attached the files I edited as well.
/dcim/views.py
[views.txt](https://github.com/digitalocean/netbox/files/1264930/views.txt)
/templates/dcim/rack.html
[rack.txt](https://github.com/digitalocean/netbox/files/1264934/rack.txt)

**Comment by cslingerland** [comment]
What do you think? Is there anything else that we can provide on this request?

**Comment by jeremystretch** [comment]
To be honest this feels very redundant. There's negligible gain over just editing the device and selecting the desired face face and position there.

**Comment by cslingerland** [comment]
I can see where you're coming from. Where I see the value here is with a new implementation of NetBox where you import a bunch of devices (i.e. a list of devices in a datacenter) that need to then be put into rack assignments. Going back and pulling up every device, choosing edit, and placing it in the rack is a lot more time consuming than just pulling up the rack and placing all the devices where they need to be.

That's the thinking behind this one, but I can certainly see your perspective and not wanting to add it.

**Comment by jeremystretch** [comment]
Might revisit this at some point but it's unlikely to get any attention in the near future.
