### ISSUE TITLE
IPAM Address Searching

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1453]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description

Would it be possible to allow for searching device types and device names within the scope of IP addresses?

I would like to be able to search for all IP addresses assigned to a device type or in the case of a device with multiple VLANs and whatnot, see what all IP addresses are assigned to a device from the IP address search page.

**Comment by jeremystretch** [comment]
This isn't something we'd implement a built-in filter for because it spans too many relationships. However you can achieve this easily using the command shell:

```
$ ./manage.py nbshell
### NetBox interactive shell (jstretch-laptop)
### Python 3.4.3 | Django 1.11.4 | NetBox 2.1.4-dev
### lsmodels() will show available models. Use help(<model>) for more info.
>>> device_type = DeviceType.objects.get(manufacturer__slug='juniper', model='EX4300-48T')
>>> ip_addresses = IPAddress.objects.filter(interface__device__device_type=device_type)
>>> for ip in ip_addresses:
...   print(ip)
... 
10.1.0.2/24
10.1.0.3/24
10.1.0.4/24
...
```
