### ISSUE TITLE
Extend Image Attachments to DeviceTypes

### ISSUE THREAD

**Issue by wenners** [digitalocean/netbox#1454]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.5
* NetBox version:  2.1.3

#### A detailed description of the proposed functionality

Expand the added fuctionality of #152. Also DeviceTyes should have the ability to attach images.

#### A use case for the new feature

IMHO it is very useful to attach also images to DeviceTypes. We usually store a stock picture of servers, switches, line cards, etc. to have clarity about available interfaces and ports. Having this feature only at Device level we would need to attach these same pictures to every device so I think it makes more sense to attach it at DeviceType level.  

#### A rough description of any necessary changes to the database schema

No change needed, DB schema was already changed with #152, it only needs to be extended to DeviceType.

#### Any relevant third-party libraries which would be needed

Same as before.

**Comment by InsaneSplash** [comment]
I'd also like to propose that Image Attachments can be extended to Tenants. This would allow us to attach a network diagram for the customer, as an overview of all sites. This assists in seeing the big picture of the customers overall infrastructure and useful for reference in the future.

**Comment by lae** [comment]
PDF attachments for device types would be useful as well for storing documents like specification sheets and administration guides (came here to request this actually).

**Comment by jeremystretch** [comment]
@lae I've [added a section to the FAQ to](https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#user-content-why-does-netbox-support-only-image-attachments) address this since it keeps coming up.

**Comment by jeremystretch** [comment]
The goal of supporting the attachment of images to sites, racks, and devices is to enable photographic documentation of a user's particular installation. Since device types are typically not unique to a specific organization (e.g. everyone who owns a Juniper EX4300-48T has the exact same hardware), there should not be a need to store photos of them in NetBox. Instead, you can link to the manufacturer's documentation, or to photos stored elsewhere if you really want to.

**Comment by wenners** [comment]
Ok - understood.
