### ISSUE TITLE
Aliased hostnames

### ISSUE THREAD

**Issue by ognjen011** [digitalocean/netbox#1455]
Hi 

would it possible to add alias for the hostnames in Netbox and to make it a searchable field as well like the others. For example sometimes you set alias on the device which is what a customer sees and your hostname is how you refer to the device internally. It would be very helpful if you could find aliased hosts and what the default hostnames they are referencing.

**Comment by traveler3468** [comment]
You could add the alias for the device in the comments and that field is searchable. Works fine for us.

**Comment by jeremystretch** [comment]
I suggest setting the device's name to whatever its actual hostname is, and add a custom string field to hold its alias.
