### ISSUE TITLE
Automatic creation of devices when populating bays

### ISSUE THREAD

**Issue by wenners** [digitalocean/netbox#1459]
### Issue type
[x] Feature request 
[ ] Bug report       
[ ] Documentation    

### Environment
* Python version:  3.4.5
* NetBox version:  2.1.3

#### A detailed description of the proposed functionality

I am struggling a bit with the concept that I need to pre-create a device for e.g. every line card I want to populate to a switch.
For more conveniance there could be some auto-generated device if I populate a device bay. In my idea this would add a drop-down for the device type and a "auto-genarate" button to the populate menu - in addition to "save" and "cancel". Anybody who wants to do assign an existing device could just use the menu as before.
This button would then create a device with the same properies as the parent, the selected type and device name could be "parent devicename"-"bay name", size 0.

#### A use case for the new feature

Populate new infrastructure more quickly

#### A rough description of any necessary changes to the database schema

None, just UI change and coding

#### Any relevant third-party libraries which would be needed

No

**Comment by jeremystretch** [comment]
> I am struggling a bit with the concept that I need to pre-create a device for e.g. every line card I want to populate to a switch.

NetBox does not currently support modeling line card within a device; see #824. If you're trying to use the device model to represent line cards, it's not going to work well.

> For more conveniance there could be some auto-generated device if I populate a device bay.

You would still need to select a manufacturer, device type, and role, and likely set some other attributes as well. Trying to fit all this on the same page as creating a device bay would be convoluted.
