### ISSUE TITLE
Remove requirement for fully-qualified domains in custom URL fields

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1460]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:   2.1.2

### Description

I created a custom field URL to point do  a devices repository for configuration backups as well as to a direct REST API link from my Cisco Prime Infrastructure servers. One thing I noticed is that you have to supply a FQDN for the custom field. We have our internal domains as our search domain and I believe this field should be able to accept that form of short-hand.

For example: https://ciscoprime.domain.com (currently required)

Internally domain.com is the given search domain so https://ciscoprime (should be acceptable by this field)

I could not find any previous issues directly referencing this issue. If they exist, I apologize now.

**Comment by jeremystretch** [comment]
Validation of the URL is performed using Django's built-in [URLValidator](https://docs.djangoproject.com/en/1.11/_modules/django/core/validators/#URLValidator), which seems to enforce a domain name and TLD. We've already implemented [our own URLField](https://github.com/digitalocean/netbox/blob/develop/netbox/utilities/forms.py#L432) too allow for arbitrary schemes. It probably makes sense to ditch the built-in validator in favor of something more flexible.
