### ISSUE TITLE
Secrets as URLs

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1462]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:   2.1.2

### Description

I am curious if it would be possible to add URLs where they are automatically linked when you unlock a secret that has a URL in it?

The reasoning behind this is, as more teams get access, since there is not a mechanism in place to prevent basic read on device info, storing links to configuration backups, Cisco Prime Infrastruture REST API (by device), etc, is not something that we want "publicly" visible. As a side note, you are required to login just to even view data in NetBox but as an added layer of protection, we want to lock down links to external data/repositories/etc that are specific to the device.

**Comment by jeremystretch** [comment]
You wouldn't store an entire URL as secret data, only the relevant login credentials or other sensitive bits.

**Comment by kopacko** [comment]
We are storing the URL, it contains all the pertinent info in it and directly loads to a new page.

**Comment by kopacko** [comment]
The other things we are storing are management related URLs where there is custom ports, URI paths, etc.
