### ISSUE TITLE
information about extras/export device 

### ISSUE THREAD

**Issue by jeongminjang** [digitalocean/netbox#1463]
1. How can I create *.csv file template?
2. How can I get custom Fields vlaue?

Plesae give me more  templates example.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
