### ISSUE TITLE
Topology view in different way

### ISSUE THREAD

**Issue by Vladimir-Ilyin** [digitalocean/netbox#1467]
Hello!

  I saw how it is possible to display the topology of the network, maybe in a NetBox it can be done as well, and not as a picture?

  http://visjs.org/network_examples.html

  just an offer

**Comment by Vladimir-Ilyin** [comment]
simple example
[example.zip](https://github.com/digitalocean/netbox/files/1269846/example.zip)

**Comment by IPFox** [comment]
I have been looking to implement something like that, but so far I think the Cisco NeXt UI would fit the purpose rather well: https://developer.cisco.com/site/neXt/

**Comment by jeremystretch** [comment]
The topology mapping functionality in NetBox isn't going to be expanded any time in the near future. It was implemented as a minor convenience for depicting the graphical layout of a set of links and nothing more. Development needs to focus on adding and improving core functionality.

If you're interested in generating more dynamic maps, you can easily export data from NetBox via the API to an external application.
