### ISSUE TITLE
'BoundColumns' object has no attribute 'show'

### ISSUE THREAD

**Issue by vahem2lu** [digitalocean/netbox#1468]
Netbox 2.1.4 (just upgraded)
Homepage is fine, I can see my data, but whenever I move to another page I get this error

<type 'exceptions.AttributeError'>

'BoundColumns' object has no attribute 'show'

When I move to Admin page, I can move around.

I can move to Connections, but nowhere else.

**Comment by jeremystretch** [comment]
You need to run the upgrade script to update required packages. Please see #1377.

**Comment by vahem2lu** [comment]
I always do git pull and then start upgrade.sh. This time this did not work.
