### ISSUE TITLE
Rename: netbox/netbox to netbox/config

### ISSUE THREAD

**Issue by alsternerd** [digitalocean/netbox#1473]
### Issue type
[X ] Request for Change

### Description
Rename the netbox folder to config to avoid doubling in names and confusion when trying to get to the configuration-folder. Since it contains all config-files, this is the appropriate name for it.

so it's:

  netbox/config/configuration.docker.py
  netbox/config/configuration.example.py

 instead of 

  netbox/netbox/configuration.docker.py
  netbox/netbox/configuration.example.py

This may break something within an update but yould be fixed with an ln -s as a shortcut.

using config as the name makes this better for human reading.

**Comment by Zorlin** [comment]
This makes a lot of sense. +1.

**Comment by jeremystretch** [comment]
This is a convention of the [Django framework](https://docs.djangoproject.com/en/1.11/intro/tutorial01/#creating-a-project) and AFAIK cannot be easily changed. Besides, this directory does not merely hold configuration data: it also holds some core views and other bits. And changing it would unnecessarily complicate all existing installations.
