### ISSUE TITLE
Netbox Server Debug set to False Erroring

### ISSUE THREAD

**Issue by jpc2350** [digitalocean/netbox#1474]
### Issue type
[ X ] Bug report      

### Environment
* Python version:  3.5.2
* NetBox version:  2.1.4
Ubuntu 16.04
Saltstack 2016.11.7 (Carbon)
PostgreSQL 9.6
Nginx 1.10.3

### Description

Running a clone from the master repository, installing postgres and nginx as required with gunicorn and supervisor. Supervisor is up and running, and running Gunicorn (as per the documentation here: 
https://netbox.readthedocs.io/en/latest/installation/web-server/ ) 

With the Configuration variable DEBUG set to True in configuration.py, the Netbox works, producing the home screen, with a Django Debug tool bar ( as expected for debug)

With DEBUG set to False in configuration.py, I should expect the above without the Django Debug toolbar, however I get the following when browsing to the web page:
![screen shot 2017-09-06 at 14 13 47 2](https://user-images.githubusercontent.com/23191993/30113775-bbdd0b86-930d-11e7-9658-7a8db5de6682.png)

And in the logs (In Custom Logging, I've got a debug log to file setup)

```Exception while resolving variable 'starts_trans' in template 'debug_toolbar/panels/sql.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 882, in _resolve_lookup
    current = current[bit]
TypeError: 'SQLPanel' object is not subscriptable
```
The following is the whole extracted error:

[netbox_debug_error_debug_log.txt](https://github.com/digitalocean/netbox/files/1281174/netbox_debug_error_debug_log.txt)

**Comment by jpc2350** [comment]
The problem was actually occurring with ALLOWED_HOSTS = None (A Saltstack issue was not populating this in the configuration file). However, An odd problem to get only when DEBUG = False.

Setting DEBUG = True meant that I had access to Netbox, with ALLOWED_HOSTS = None

**Comment by jeremystretch** [comment]
`ALLOWED_HOSTS` must be defined as a list of hostnames as specified [in the docs](http://netbox.readthedocs.io/en/stable/configuration/mandatory-settings/#allowed_hosts). It is not evaluated when `DEBUG` is true because debugging disables request host validation.
