### ISSUE TITLE
Interface Template No Longer Available

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1478]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.12
* NetBox version:  2.1.4

### Description
When editing a "Device Type", there used to be a place where you could define interfaces that were specific to the device.  Now, when clicking on "Device Type" and selecting one to edit (or even add a new "type"), only "Console Ports", "Power Ports", and "Console Server Ports" are seen.

Was this removed intentionally?

**Comment by RyanBreaker** [comment]
It was moved instead to the specific type's page: 
![untitled](https://user-images.githubusercontent.com/1717238/30230551-66d7ec6e-94ac-11e7-87c5-449ee8f05bbb.png)

Open a device type after creating one and you'll see the Interfaces on the right which you can generate with ranges with ease.

**Comment by bdlamprecht** [comment]
Yeah, that's where it went, thanks @RyanBreaker .  Thought I was loosing my mind.
