### ISSUE TITLE
Standardizing data for testing

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#148]
It might be helpful to setup some process(es) to git clone the master or search for the latest stable release, deploy and run the upgrade process on a demo page (digital ocean or packetlife) on a daily basis.  Obviously this would be limited given that not all testers would have access to a remote console for troubleshooting.  It would also help give new users a view of the most recent version of the tool before installing.

This would allow for some cross collaboration when testing.  Another option would be to develop a standard test data set for distribution with these releases so we can all test using similar data sets.  A simple sql file could be used for this.  We could probably package up an export of the current db on the demo site with some tweaks here and there.

**Comment by jeremystretch** [comment]
In an effort to clean up the issues backlog, I'm closing all issues labeled as "dicussion." If there is interest in continuing this topic, please start a thread on the [NetBox subreddit](https://www.reddit.com/r/netbox). Thanks!
