### ISSUE TITLE
List and addition of Headers

### ISSUE THREAD

**Issue by DirtyCajunRice** [digitalocean/netbox#1483]
### Issue type
[X] Feature request 
[ ] Bug report      
[X] Documentation   

### Description
Could we get a documented list of headers allowed? The use case i have right now is writing a python script for pulling data and ?limit= is... well... ugly haha. Tried a few "Pagination: 1000" "limit: 1000" "Max_page_size: 1000" nothing seemed to respond to larger page sizes other than appending ?limit= to the end as implemented in: #1237 .

**Comment by jeremystretch** [comment]
API pagination is controlled using the `limit` and `offset` query parameters. NetBox does not support paging through the use of HTTP headers. Query parameters were chosen because this approach allows for linking to a specific page of results (e.g. in the browsable API).

**Comment by nschmalenberger** [comment]
How about http://docs.python-requests.org/en/master/user/advanced/#link-headers then?
