### ISSUE TITLE
Implement a Banner / Disclaimer for Login page

### ISSUE THREAD

**Issue by thefreakquency** [digitalocean/netbox#1485]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.x
* NetBox version:  2.1.4

### Description
**_A detailed description of the proposed functionality:_**
Please provide a way to add a login banner for the user to accept prior login.  Either thru:
* Some text being showed on the login page before the username/password field (accepting the disclaimer by filling credentials & clicking the login button).
or
 * A first page the user as to accept prior getting the login page. Ideally it should allow markup or HTML language to make it even more flexible... The look & feel of the page could be similar to the 404.html page 

  I would see 3 ways to achieve it: 

1. Implement a way to allow the TOP_BANNER to be displayed on the login page only, and reuse that field for the banner. 

2. Add another variable like LOGIN_BANNER to be configured in configuration.py for the login page 

3. Have a variable available for modification in the Admin site. This would be even more flexible, allowing an application admin to modify this behavior without needing a System Admin to do so. 

Don't hesitate to brainstorm or comment if you have a better approach :) 

**_A use case for the new feature:_**
This would help us to accommodate the corporate IT policy without trying to modify pages manually (and have to redo it at upgrades)... 
https://linux-audit.com/the-real-purpose-of-login-banners-on-linux/ 

It could also be used to advertise on the login page (i.e.: If you require access, please contact Mr X.)

**_A rough description of any necessary changes to the database schema:_**
I don't believe this would require any db work.

**_Any relevant third-party libraries which would be needed:_**
I don't believe this would require any libraries addition.

**Comment by jeremystretch** [comment]
Added a `BANNER_LOGIN` setting similar to `BANNER_TOP` and `BANNER_BOTTOM`.
