### ISSUE TITLE
Implement PoD extension in Organization component

### ISSUE THREAD

**Issue by vsvetlov** [digitalocean/netbox#1488]
Thank you Jeremy and the team for your great work!
I just started my Python way and hope join you a bit later)

Issue type
[x ] Feature request 

 Environment
Python version: 3.5.4
NetBox version: 2.1.4

 Description

I looked through the issues and have not found similar request (most similar thing is cluster in virtualisation module)
You know a big infrastructure is usually divided into the different blocks and sometimes there are many identical blocks that could contain differents resources such as compute, network, storage
The reason for such design is opportunity for independents maintenance (read as different failure domain), HA purposes, scalability etc

The idea is:
Define different types of resources
Create container of resources (performance container)
Assign container of resources to device type
Aggregate set of device types to PoD

Use cases

Storing info from vendor datasheet such as connection/packet rate, bandwidth, max conns, bgp max table size etc for a device/device type
IP Prefix can be considered as resource as well
Resources sizing/planing for specific environment by aggregating the different devices (device types) into PoD (PoD types)
Resource calculation per rack, site, using as thresholds in monitoring system
Cloning identical PoDs between different sites, for example CustomerAppA, InternalResourceB etc

**Comment by jeremystretch** [comment]
Sorry but this request is all over the place. What do you mean by "PoD?"

**Comment by vsvetlov** [comment]
https://en.wikipedia.org/wiki/Point_of_delivery_(networking)Point of delivery (networking)
A point of delivery, or PoD, is "a module of network, compute, storage, and application components that work together to deliver networking services. The PoD is a repeatable design pattern, and its components maximize the modularity, scalability, and manageability of data centers."
The PoD design pattern is especially important in service provider infrastructure, for instance in datacenters supporting cloud computing services, in order to sustain scalability as usage grows.
!
There are Sites and Racks modules to define physical location of devices
There is also Tenant model that describes management domain.
It seems PoD is missed part of hierarchy. PoD describes a pool of resources that are allocated to specific service or group of services.

Example1: Application PoD
Let's define pool of resources for the DevOps to test deployment to web-frontend services
Tenant: DevOps
2 servers from Rack A
2 servers from Rack B
switch in rackA/4 ports 
switch in rackB/4 ports 
firewall contextA
2 virtual machines in cluster B

Example2: Design pattern
Let's define pool of resources for a Point of presence
Tenant: Production
2 routers
2 switches
2 caching servers

**Comment by jeremystretch** [comment]
This would be far too abstract and complicated to implement in NetBox. You might be able to partially accomplish what your after with custom fields or tagging (#132) though.
