### ISSUE TITLE
Allow differential upload/download speeds on circuits

### ISSUE THREAD

**Issue by justinhippen** [digitalocean/netbox#149]
Would be nice to be able to document both the download & upload speeds on circuits. e.g DSL line has a DL of 5Mb & UL of 512Kb.

**Comment by ryanmerolle** [comment]
This could be a custom field ( #129 ) if it's not something that the group thinks would be useful as a new feature.  If you really wanted to model this sort of thing, you would look into including commited rates for normal upload and download along with burstsble rates for each direction.

**Comment by spencerryan** [comment]
I think this could be useful. Many of our sites have symmetrical primary connections with consumer (Cable/DSL) backups.

**Comment by peelman** [comment]
+1 asymmetric links are a fact of life now for most of us.

**Comment by jeremystretch** [comment]
Be sure to add a :+1: to the top post if you're interested.
