### ISSUE TITLE
Create initial data for virtualization models

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1491]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  v2.2-beta1

### Description

Simple enhancement: `loaddata initial_data` could include

* Initial cluster types: "Public Cloud", "vSphere", "oVirt", "libvirt", "lxd", "docker"
* Initial clusters: "Amazon EC2", "Google GCE" (of type "Public Cloud")
* New Device Role "VM Host"

Use case: makes it quicker to add your first VM when trying out Netbox.  Then the minimal work is to create one VM in "Amazon EC2", or to create a cluster + VM.

**Comment by RyanBreaker** [comment]
Just submitted the above pull request adding these items. I can easily add more if anyone has any additional suggestions before @jeremystretch accepts it.

**Comment by jeremystretch** [comment]
I'll leave this open for a couple days in case anyone has suggestions.

**Comment by darkstar** [comment]
hmmm, how about CEPH & Kubernetes as cluster types? And MS Azure as additional initial cluster?

**Comment by candlerb** [comment]
I wouldn't include Ceph because it's not a virtualization environment, it's a storage service (*).  The others are fine.

(*) Maybe some people might want to model non-virtualization clusters as Netbox "cluster", but that wasn't what it was intended for

**Comment by Zorlin** [comment]
In my opinion clusters should be limited to Compute workloads in Netbox.

**Comment by darkstar** [comment]
> In my opinion clusters should be limited to Compute workloads in Netbox.

That seems like an arbitrary decision and is not the way I'm using NetBox right now. Any reason behind your opinion?
We have virtualized storage systems that look and act like regular Virtual Machines.

**Comment by candlerb** [comment]
> We have virtualized storage systems that look and act like regular Virtual Machines.

Something that acts and looks like a Virtual Machine can be modelled as "Virtual Machine" - no problem with that.

However, a netbox "Cluster" is not a grouping of virtual machines; it's a grouping of virtualization hosts on which VMs can run. The database models the relation `Virtual Machine` : `(runs-on)` : `Cluster`

The issue raised was whether "Ceph" should be one of the options for "Cluster Type".  I'd say no, because Ceph is not a virtualization platform;  the database would let you mark VMs as executing on the Ceph cluster, which is not the case.

**Comment by darkstar** [comment]
@candlerb I agree with that. I think I was confused and actually meant something else but it doesn't matter ;)

**Comment by RyanBreaker** [comment]
So do we want to add Azure as another cluster option? Otherwise, if someone uses one or the other, it would be a simple rename.

**Comment by ktims** [comment]
Azure should be added, as should HyperV as a cluster type.

There are too many possible types of clusters to list here. I would again advocate for this to be added to the Admin panel and let the user decide how to use it.

**Comment by RyanBreaker** [comment]
Added those two.

**Comment by candlerb** [comment]
> There are too many possible types of clusters to list here. I would again advocate for this to be added to the Admin panel and let the user decide how to use it

The cluster types are already user-editable.  This ticket is just about creating sample data that can be [preloaded at install time](https://netbox.readthedocs.io/en/stable/installation/netbox/#load-initial-data-optional), like the pre-loaded set of [Manufacturers and Platforms](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/fixtures/initial_data.json#L83) for example.

**Comment by jeremystretch** [comment]
If we're going to list AWS and Azure as cloud providers, I feel somewhat obligated to list DigitalOcean too, given that they are NetBox's sole sponsor. However, I'm also very sensitive to potential conflicts of interest, so I wanted to propose it here. Any objections?

**Comment by rdegez** [comment]
Seems 100% fair to me and it's very nice of you to even ask, I would say!

**Comment by RyanBreaker** [comment]
Added.

**Comment by cimnine** [comment]
Since `libvirt` and `vSphere` are there, may I suggest `Xen` and maybe `kvm`?
And since `Docker` and `lxd` are there, may I suggest `Kubernetes`?

**Comment by jeremystretch** [comment]
@RyanBreaker Thanks. Ping me when you want this merged.

**Comment by RyanBreaker** [comment]
@cimnine I think it's already a bit extensive as it is, and it is only initial data that someone can optionally import, more or less as examples.

@jeremystretch If you're ready I'm ready, I think it's good.

**Comment by cimnine** [comment]
@RyanBreaker Yeah, I thought so minutes after I commented.

**Comment by jeremystretch** [comment]
Merged #1604
