### ISSUE TITLE
Create or extend functional roles for virtual machines

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1493]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  v2.2-beta1

### Description

I would like Virtual Machines to have a "Role", just like Devices.  They can be taken from the same set of Device Roles.

Use case:

* Being able to tag each VM that its primary role is "Database", "Web server", "Storage server", "Firewall" etc

**Comment by jeremystretch** [comment]
Does it make sense to use the same set of roles for VMs as for devices though? You wouldn't assign a VM the role of PDU, NAS, console server, etc.

We could either create a separate set of roles only for VMs, or we could extend the existing role model to include a boolean field indicating whether it's applicable for VMs.

**Comment by lampwins** [comment]
I like the boolean option on the existing model and I think it should also be extended to the platform model as the same argument could be made there.

**Comment by darkstar** [comment]
At least a NAS could very well be a VM (some hyperconverged solutions use VMs to serve CIFS/NFS to the outside world, and there are clustered and virtualized storage systems that provide multi-tenant capable isolated virtual NAS/SAN instances)

**Comment by jeremystretch** [comment]
Implemented the base relationship in 6243fbf. Will experiment with adding per-model flags to the DeviceRole model shortly.
