### ISSUE TITLE
Assign secrets to virtual machines

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1495]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  v2.2-beta1

### Description

Currently you can attach secrets to Devices but not Virtual Machines.

Use cases:

* Storing per-VM administrator/console logins
* Someone who uses secrets for Devices will probably want to use them for VMs too.
* Conversely, someone who finds they cannot use secrets for VMs (and hence needs an external solution) will likely use the external solution for Devices too.

---

Aside: I don't use netbox secrets myself for various reasons. I am entering this ticket so that a decision can be recorded either way.

It might be worth a poll to see who *does* use this feature; and if it's not widely used, consider removing it.

**Comment by darkstar** [comment]
It was made quite clear that NetBox is not intended for that. See https://github.com/digitalocean/netbox/issues/142#issuecomment-256086213 for a comment on secrets for VMs.

I would probably use that feature if it were available, but I don't particularly need it (I have other means to store the secrets for VMs, and I kind of agree with the fact that NetBox is not designed to reach that far into the administrative level of the VMs)

**Comment by jeremystretch** [comment]
@darkstar That comment was before the v2.2 beta introduced support for virtual machines and clusters. v2.2 will definitely have virtual machines; whether or not we want to extend secrets to them and other objects (see #1503) is still open for discussion.

**Comment by darkstar** [comment]
@jeremystretch I am aware of that but you later posted that you're still leaning towards "no" on the issue, and for the same reasons (see https://github.com/digitalocean/netbox/issues/142#issuecomment-326590192). Maybe I should have linked to that comment instead ;-)

The idea of #1503 never crossed my mind... it seems there are quite a few cases where secrets could be useful. If so, it certainly makes sense to also add them to VMs/Clusters

**Comment by jeremystretch** [comment]
Extending secrets from devices to multiple objects requires replacing the ForeignKey field tied to the Device model with a GenericForeignKey. This in itself is straightforward, however we have to consider how this relationship should be displayed in the API.

Currently, a secret retrieved via the API looks like this:

```
{
    "id": 1234,
    "device": {
        "id": 5678,
        "url": "http://localhost:8000/api/dcim/devices/5678/",
        "name": "MyDevice",
        "display_name": "MyDevice"
    },
    "role": <...>,
    "name": "root",
    "plaintext": null,
    "hash": "<hash>",
    ...
}
```

If we switch to a generic relationship, we need some way to indicate the type of the parent object, both while retrieving existing secrets and while creating new ones. The [DRF documentation](http://www.django-rest-framework.org/api-guide/relations/#generic-relationships) talks about this briefly, but does not suggest any particular approach.

**Comment by jeremystretch** [comment]
I'm going to close this issue for now in favor of #1503, which would cover extending secrets to VMs. If #1503 falls through, this issue can be re-opened.
