### ISSUE TITLE
Show the % of Utilization for Child Prefixes

### ISSUE THREAD

**Issue by tioan** [digitalocean/netbox#1499]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version: 2.1.4

### Description

IP Space -> Prefixes shows the % of Utilization for every Prefix.
I really like this feature, please add this also for every Prefix with Child Prefixes.
So that the % of Utilization for every Child Prefix would be displayed in the Child Prefixes Listing.

**Comment by darkstar** [comment]
That would indeed be a nice feature to have
