### ISSUE TITLE
"Export virtual machines" does not work

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1502]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  v2.2-beta1

### Description

When I select "Export virtual machines", nothing happens - the page is just redrawn, and the URL bar changes to `/virtualization/virtual-machines/?export=&export`

However if I select "Export devices" then I get a downloaded file (`netbox_devices.csv`) as expected.

**Comment by jeremystretch** [comment]
Model is missing the `csv_headers` property and the `to_csv()` method needed for export. Same issue with Clusters.

**Comment by jeremystretch** [comment]
Fixed in 9927ce1
