### ISSUE TITLE
Using VRF object instead of id in POST to api/ipam/prefixes/<pk>/available-ips/

### ISSUE THREAD

**Issue by alejandrosalinas** [digitalocean/netbox#1507]
When posting on api/ipam/prefixes/<pk>/available-ips/ the code uses the entire VRF object instead of the VRF ID on the serializer.

```
data = request.data.copy()
data['address'] = '{}/{}'.format(ipaddress, prefix.prefix.prefixlen)
data['vrf'] = prefix.vrf                                                  <=== HERE
serializer = serializers.WritableIPAddressSerializer(data=data)
```

which then fails with 

```"Incorrect type. Expected pk value, received VRF."```

**Comment by jeremystretch** [comment]
Thank you for the bug report, but in the future please be sure to use [the issue template](https://github.com/digitalocean/netbox/blob/develop/.github/ISSUE_TEMPLATE.md).
