### ISSUE TITLE
Optionally Assigning a Site to a VM Cluster

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1509]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  2.2-beta1

### Description
Each of our clusters is restricted to a certain site. Therefore I would like to optionally assign a site to a cluster.

**Comment by darkstar** [comment]
Just to clarify: This is for clusters that don't consist of physical devices, right? Like AWS or Azure clusters? 

Because if you assign a device to a cluster, that device has a physical location in a certain rack, and that rack is located in a site.

**Comment by cimnine** [comment]
I had physical devices in mind. You could also build a cluster across sites. Ultimately I want to be able to filter the clusters by site and ideally also to restrict it to devices of that site.

**Comment by jeremystretch** [comment]
Implemented in 2ca161f
