### ISSUE TITLE
No field to edit Cluster comments

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1514]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment

* Python version:  3.5.2
* NetBox version:  origin/dev-2.2 e93129f1

### Description

When you view Clusters you can see there is a 'comments' field.  However, when you create a Cluster there is no field to enter the comments. Ditto when you click Edit on an existing cluster (e.g. `/virtualization/clusters/1/edit/`).

**Comment by jeremystretch** [comment]
Fixed by #1517
