### ISSUE TITLE
Nested Groups for LDAP Authentication

### ISSUE THREAD

**Issue by larsuhartmann** [digitalocean/netbox#1515]
### Issue Type
[  ] Feature request 
[  ] Bug report 
[ x ] Documentation

### Description
Regarding the LDAP Part of the Installation Documentation, i would propose to use NestedGroupOfNamesType to support nested groups - i already prepared a patch in my git repo - so i would send a pull request if this is ok.

Cheers
Lars

**Comment by darkstar** [comment]
I am not sure, but I think not all LDAP servers support nested groups/NestedGroupOfNames ? So maybe it should be made optional

**Comment by larsuhartmann** [comment]
Fair Point! How about just adding the sentence

!!! When using Windows Server 2012, `GroupOfNamesType` can be replaced by `NestedGroupOfNamesType` to provide support for nested Groups.

**Comment by larsuhartmann** [comment]
i submitted pull request #1524
