### ISSUE TITLE
PyCrypto is dead; Use cryptodome

### ISSUE THREAD

**Issue by jdell64** [digitalocean/netbox#1527]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.2
* NetBox version:  Example: 2.1.3

### Description

To replicate, attempt to run this on a windows server / windows box. `pcrypto` won't install and is dead now. replacing it with `pycryptodome` gets you further in the process, but fails when referencing `XOR`

**Comment by jdell64** [comment]
Additionally, 

https://docs.openstack.org/bandit/latest/blacklists/blacklist_calls.html#b304-b305-ciphers-and-modes

states that `Crypto.Cipher.XOR.new` is insecure.

**Comment by jdell64** [comment]
Opened a PR #1528

I don't know enough about what the XOR function is doing to replace it properly

**Comment by jdell64** [comment]
opened a new PR #1531

**Comment by jeremystretch** [comment]
Was this issue opened to address a bug? If so, please file a bug report using the [issue template](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). Otherwise, these changes do not appear to be necessary.

**Comment by jdell64** [comment]
I'll fill out the form. The two issues it addresses is is that 

1) it won't run on windows because pyCrypto will not install on windows. The only way to make this work is to install packages defunct for 3 years and downgrade to a python version that is no longer supported.

2) pcrypto is dead. The application makes heavy use of some functions in there that have been dropped from it's replacement `pycryptodome`


### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.2
* NetBox version:  Example: 2.1.3


### Description

To replicate, attempt to run this on a windows server / windows box. `pcrypto` won't install and is dead now. replacing it with `pycryptodome` gets you further in the process, but fails when referencing `XOR`

**Comment by jdell64** [comment]
I have a monkey patch that works (passes the cibuild). Should I raise another PR or just let you review it in my fork?

**Comment by jdell64** [comment]
Thanks for all your hard work on this 👍
