### ISSUE TITLE
API data structure changes on upgrade

### ISSUE THREAD

**Issue by Comm4nd0** [digitalocean/netbox#1530]
Hi, please can you confirm if you will make data structure changes on new major and minor releases. 

Currently creating a system that depends on pulling data via the API but i'll need to document it if the Ansible playbooks will need revisiting should you change the data structures. 

thanks in advance.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
