### ISSUE TITLE
Add Contract Inforamtion for Devices

### ISSUE THREAD

**Issue by pgrofer** [digitalocean/netbox#1539]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version: Future 

### Description
Hi,

is it possible to add an additional text field for contract infromation of a specific device?
An additional point would be a backward timer with the rest of time this device is under contract.

The use case for us is to notice, if devices for example from cisco will get out of contrat or not. 

Is it possible to release this feature in a future version of netbox?

Thanks

**Comment by jeremystretch** [comment]
Please see #182
