### ISSUE TITLE
Expand device status beyond active/offline

### ISSUE THREAD

**Issue by peelman** [digitalocean/netbox#154]
Not so much an issue but a topic of discussion, as I am not sure where even I stand on this; right now Device->Status is defined as Bool, with two states, Active or Offline.  

Aside from the semantic differences (Use Online/Offline, Active/Inactive, or some other matching pair), should there be more than two states a device can be in?

```
[STATUS_ACTIVE, 'Active'],
[STATUS_INACTIVE, 'Inactive'],
[STATUS_DISABLED, 'Disabled'],
[STATUS_STORAGE, 'Storage'],
[STATUS_MISSING, 'Missing'],
[STATUS_LOANED, 'On Loan'],
[STATUS_DESTROYED, 'Destroyed'],
[STATUS_SOLD, 'Sold'],
[STATUS_Stolen, 'Stolen'],
```

I'll admit, I have a hard time not treating the Devices section as an Asset Management system (right now its tailored to Rack mounted gear, but there are lots of things in data centers to keep tabs and accountability on that don't go in racks). Each of those states represents a state of equipment we were tracking at one point or another.

Or should this be a lookup table that is configurable by the end user as needed?

**Comment by jeremystretch** [comment]
To lend a bit of context, the `status` field was originally just used to indicate whether NetBox should attempt to pull inventory/LLDP from a device, etc. But this is a really interesting idea and I'd love to hear what others think.

**Comment by bellwood** [comment]
Well if its active, then pull LLDP but having alternative statuses is a great idea.

A status for repair and/or RMA would be nice too so you can track those states

Are status changes going to be logged in the device history? That would be great so you could track how long a device was out for RMA or been active, etc.

**Comment by jeremystretch** [comment]
I think if we extend the concept of `status` beyond merely "online" or "offline," there's going to be too much variation among users to define a concise but inclusive list. (I'd also feel uncomfortable showing our leadership a tool that has "stolen" as a possible device status. :smile: )

I'm going to close this out in favor of #129 (custom fields), which should allow for exactly this functionality but as a completely customizable list.

**Comment by jeremystretch** [comment]
Reopening this feature request. I think there's merit for extending the status field, or at least adding a separate field to track this sort of state.

**Comment by puck** [comment]
While I really like the idea of having different status information, this does start to blend towards the asset management side of things. Not that i think this is a bad thing personally!

The benefit from my point of view is that when a device is no longer racked, we don't lose the history. Currently my colleagues will tend to delete a device as soon as it is de-racked.

**Comment by jeremystretch** [comment]
While I don't want to get into asset management territory, I do think it would be reasonable to include subsets of the "offline" status. For example, a state that would indicate hardware failure and another that would indicate that the device has been tagged for deinstallation.

**Comment by puck** [comment]
Yes, both of those examples would be very handy.

**Comment by jeremystretch** [comment]
Expanding the boolean field to include the following device statuses:

```
STATUS_OFFLINE = 0
STATUS_ACTIVE = 1
STATUS_PLANNED = 2
STATUS_STAGED = 3
STATUS_FAILED = 4
STATUS_INVENTORY = 5
```
