### ISSUE TITLE
Show interfaces provided by device bay on main device screen

### ISSUE THREAD

**Issue by bitratio** [digitalocean/netbox#1541]
### Issue type
[o] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description
Hello;

Please show interfaces provided by child devices on parent device page.

We have a large juniper routing estate and we are hoping that you might accommodate a feature for us.

Currently, we have a mixed estate of different Juniper routers with interfaces provided by MPC  or MIC Cards.

We have added these as child devices as the data schema suggests however to view the ports that these cards provide to the device you have to physically click into the child device, this seems clunky.

Is there a way that we can populate the main device interfaces list with the interfaces that are provided by the child device?

Obviously, we aren't going to populate the interfaces list for the main device as these devices do not come with any interfaces as standard, they are all provided by the child MICS.

**Comment by lampwins** [comment]
Child devices in netbox are intended for devices which are managed independently of the parent. In other words, the parent it just a chassis that provides power. In the case of Juniper MPC/MIC's these are not managed independently of the router chassis. The most common way in netbox to do this is to populate the "parent" (just the regular router) with the interfaces as normal. Netbox has some intelligence (for sorting and such) for the fpc/pic/port syntax. You can track asset information in the inventory section of the device at this point for things like the MPC's serial number.

Related to your query is #940 for switch stacking. But that would be for actual virtual chassis support in Juniper world.

**Comment by jeremystretch** [comment]
As @lampwins said, you wouldn't represent MPCs as child devices. #824 has been opened to represent discrete line cards in this manner.
