### ISSUE TITLE
Bulk IP-Address addition looses VRF

### ISSUE THREAD

**Issue by Zimeon-** [digitalocean/netbox#1549]
### Issue type
[X] Feature request
[X] Bug report
[ ] Documentation

### Environment
* NetBox version:  2.1.4

### Description
When adding an IP-Address from the prefix, VRF is automatically filled in as well as the prefix is added to the address field. When at this point the user clicks on "bulk", these fields are cleared due to the page reload. At least the VRF should remain selected when switching between forms.

**Comment by jeremystretch** [comment]
The "bulk" tab links to a new page. This isn't something we can adjust easily with the current UI scheme.
