### ISSUE TITLE
IPAM Section

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#155]
Hi Team,

Opening up a discussion as i am not sure how sensitive this is given that these 2 products are both outstanding but i definitely want to understand your vision moving forward.

I question how we can technically make the jump from phpipam over to netbox within regards to the ipam section, this is the only area that prevents us currently from using netbox as a one stop shop.. 

What are your intentions with this section, are you looking to be able to provide the same level of functionality and management phpipam does?

**Comment by ryanmerolle** [comment]
I'm not trying to speak for @strech here, but you should probably list out the requirements you have or the specific gaps you think you need addressed before adopting.

Being such a relatively new project, I have to say this IPAM tool has the potential to far surpass PHPIPAM on just the IPAM functionality.

I'll redeploy phpipam and provide some notes tonight or tomorrow.  I used to love it, but I replaced it with device42 given the far superior iPam and additional dcim functionality.

**Comment by peelman** [comment]
Really?  I like phpIPAM's IPAM far more than any other I have found, even netbox so far. But the ability to have a decent open source DCIM and have it integrate a proper IPAM solution makes me happy enough to see where netbox takes us. 

I think NetBox has a good v1 and I'm excited about it. But it'll be a while before I remove phpIPAM from our server.

**Comment by jeremystretch** [comment]
The best way to answer this question is to first enumerate the functionality you're missing from NetBox, and then compare those items against the (rather lengthy) list of feature requests that are currently open. The [roadmap](https://github.com/digitalocean/netbox/wiki/Roadmap) might be best place to start: these are feature requests that will almost certainly be incorporated into NetBox in the future. (Note that just because a feature request isn't on the roadmap right now doesn't mean it won't be soon.)

For any feature you'd like to see that both isn't currently implemented in NetBox and isn't on the roadmap, I invite you to file a new feature request. Please be sure to provide as much detail as you can regarding how you'd like NetBox to function. There's no guarantee that we can implement each feature, of course, but it gives us some data to help steer the development of NetBox overall.

**Comment by rackcentral** [comment]
HI Ryan/Everyone,

Thanks for getting involved in the discussion from our side we use phpipam as follows

_We have network and services in 70+ datacentres globally and our requirements may not be the same as everyone else using netbox and phpipam_

> * Setup sections based on region, for example AU-VIC, AU-NSW, NZ-AKL, US-SJC
> * Use a VLAN Layer2 Group and theoretically assign it to each section. 
> * Setup a master subnet for example could be 103.0.0.0/22 under a section. 
> * Create a subnet under the master subnet of 103.0.1.0/24, 103.0.2.0/24 etc

Once this is setup we then allocate smaller nested subnets under each /24 for customers. So if a customer signs up with a new colocation service they would typically get a /29 ipv4 and a /64 ipv6. 

When we create a new customer as a nested subnet the following things happen

> * Autocreation of PTR records which talks to our PowerDNS AnyCAST Platform
> * Assigning customer VLAN from our Layer2 VLAN Domain for that region
> * Provisioning of customer prefix on our routers (this is a custom script we wrote and not expecting netbox to do this automatically) 

**What we personally would like to see out of it?**

> * Allowing us to utilise netbox to manage the ipam much like what we do now in phpipam
> * Following a style of management with subnets/sections for interface flow on usability.
> * Adding in support for AS Numbers so we can include BGP customers and be able to allocate the prefixes in netbox to know exactly which device in which rack is advertising them. 
> * Adding in support for integration via API preferably or via SQL not preferred into PowerDNS.
> * Auto creation of PTR records when adding subnets, for example 1.1.0.103.au-vic.rackcentral.com the .au-vic could be taken from the section name and then the .rackcentral.com could be a default value that be entered in the DNS section for each netbox user to use their own domain name. 
> 

I am sure there are more to add on top of this and am interested in the discussion to see if others would benefit from this as well. I know that having the above would allow us to use netbox as a one stop shop for management.

**Comment by ryanmerolle** [comment]
Specific feature requests broken out:

- Region Support #164 (feel free to further add to this I get your section usage, but IDK if its useful to exactly mimic that setup as it can get confusing for some users)
- AS Support #127 
- Add multitenancy support #16
- Route Advertisement Support #165
- Basic DNS Support #166
- PowerDNS support (you'll need to list out the integration as I do not use the tool) - It feels like something that comes on the roadmap later on with other integrations.

Anything I missed, I would recommend you raise individual feature requests with an explanation of the basic functionality along with future roadmap of additional complexity.

**Comment by rackcentral** [comment]
Here is the PowerDNS API Docs
https://doc.powerdns.com/md/httpapi/README/#powerdns-api
Very common DNS platform used in hosting industry.

**Comment by jeremystretch** [comment]
Going to close this issue out as it's a bit too broad to be actionable. It looks like other feature requests have already been opened for most of what was covered. Feel free to open additional feature requests for specific functionality (but please remember to search existing issues first).
