### ISSUE TITLE
Add CPAK and CVR form factor

### ISSUE THREAD

**Issue by beufanet** [digitalocean/netbox#1551]
### Environment
* Python version:  2.7.9
* NetBox version: 2.1.5

### Description

Add new form factors for interfaces

Cisco CPAK and CVR are proprietary form factor for 100G optics.

https://www.cisco.com/c/en/us/products/collateral/interfaces-modules/transceiver-modules/data_sheet_c78-728110.html

We use it for Cisco N77 and ASR module, and sometimes running CVR (CFP2 to CPAK adapter). 

We propose this patch for the community ;) 

PR to come

**Comment by beufanet** [comment]
PR : https://github.com/digitalocean/netbox/pull/1552/files

**Comment by jeremystretch** [comment]
According to the data sheet, the CVR is an adapter for the CPAK form factor, and not a form factor itself. I'll add CPAK as a 100GE form factor.

**Comment by jeremystretch** [comment]
Also adding the CFP2 and CFP4 100GE form factors.

**Comment by beufanet** [comment]
So should I suggest another patch or you manage it ?

Thanks !

**Comment by beufanet** [comment]
Thanks !
