### ISSUE TITLE
Support for bulk creation of objects via API

### ISSUE THREAD

**Issue by DirtyCajunRice** [digitalocean/netbox#1553]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description
Multi-entry API calls would make automation much easier. I have scripted a "New Customer.py" which creates the Tenant, VRF, 10xVLANs, 10xPrefixes, and about 50 initial IPs. Currently, my options are to paste it out to CSV and import it section by section or to create a loop for the HTTP PUSH request which is a nightmare for error checking.

Browsable API example:
```
[
    {
        "name": "Cust 2",
        "slug": "cust-2",
        "group": 1
    },
    {
        "name": "Cust 3",
        "slug": "cust-3",
        "group": 1
    }
]
```

Thoughts?

**Comment by Zimeon-** [comment]
Ran into the same issue that it didn't accept multiple entries when posting a JSON. Your example is missing [] and a comma between the entries but none the less it doesn't support it. Ended up just making multiple post entries in the script but bulk data in a single json would be nice.

**Comment by DirtyCajunRice** [comment]
@Zimeon- fixed example. Thanks! Do you have request.error_code and request.response data from each push? And if so how are you logically checking those? Dict?

**Comment by Zimeon-** [comment]
I simply stored the response code and moved along. After that I manually verified the failed ones by hand as I just had to import stuff once from an old db to netbox.

**Comment by jeremystretch** [comment]
This seems [simple enough to implement](https://stackoverflow.com/questions/14666199/how-do-i-create-multiple-model-instances-with-django-rest-framework#answer-40253309) in the writable serializers. We might want to restrict the total number of objects able to be created in one request though: It might be reasonable to reuse the `MAX_PAGE_SIZE` configuration parameter for that purpose.

**Comment by DirtyCajunRice** [comment]
Yes i agree that MAX_PAGE_SIZE would safely limit to (500?) by default
