### ISSUE TITLE
Aggregate / Parent Prefix w/ no discernible difference

### ISSUE THREAD

**Issue by DirtyCajunRice** [digitalocean/netbox#1555]
### Issue type
[ ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  Python 3.5.2
* NetBox version:  2.1.5

### Description
Aggregates show child prefixes, but not the reverse. Without the reverse information, you have to create a prefix of the exact same as the aggregate. When both exist this makes the aggregate almost useless (other than a quick view of the top level of all things). 
I propose a change that at least shows prefixes within an aggregate with no parent to show the aggregate and preferably adding a section above "Parent Prefixes" that has the Top Level Aggregate.

**Comment by jeremystretch** [comment]
> Aggregates show child prefixes, but not the reverse.

The aggregate of a prefix (if one exists) is included in the attributes of the prefix, between Tenant and Site.
