### ISSUE TITLE
Cannot filter virtual machine interfaces

### ISSUE THREAD

**Issue by hamishforbes** [digitalocean/netbox#1557]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version: 2.7.5
* NetBox version:  2.2-beta2 

### Description

Not sure if this counts as a bug or a feature request, but as far as I can tell there's no way to filter the `/virtualisation/interfaces/` API endpoint?  
The only way to determine which interfaces a VM has is to get all the interfaces and iterate over them clientside.

**Comment by jeremystretch** [comment]
We should probably just ditch the `/api/virtualization/interfaces/` endpoint entirely. It's redundant to the DCIM-based endpoint.

**Comment by hamishforbes** [comment]
That seems reasonable, although it begs the question: should the
`/virtualization/` endpoint exist at all? Maybe virtual-machines should
just be part of dcim?

On 6 Oct 2017 20:59, "Jeremy Stretch" <notifications@github.com> wrote:

We should probably just ditch the /api/virtualization/interfaces/ endpoint
entirely. It's redundant to the DCIM-based endpoint.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/digitalocean/netbox/issues/1557#issuecomment-334855409>,
or mute the thread

**Comment by jeremystretch** [comment]
VirtualMachines and Clusters are their own discrete models with dedicated tables in the database, so they need their own endpoints. This is in contrast to the Interface model, which is actually shared by Devices and VirtualMachines.

**Comment by jeremystretch** [comment]
After pondering this a bit more, it's cleaner to maintain a separate endpoint for VM interfaces. In addition to being more efficient (since the DCIM endpoint only pulls in devices and the virtualization endpoint only pulls in VMs), there's enough difference between the two interface representations to justify separate filters.
