### ISSUE TITLE
device_role in import devices are not getting recognised 

### ISSUE THREAD

**Issue by wookdark** [digitalocean/netbox#1558]
While trying to import multiple devices device_role which is created is not getting recognized despite device role being created 

Error: Required column header "device_role" not found
<img width="876" alt="screen shot 2017-10-05 at 5 26 54 pm" src="https://user-images.githubusercontent.com/31650776/31226149-abd02fb0-a9f2-11e7-9bd9-a3ad606624f0.png">

**Comment by wookdark** [comment]
anyone the community who can help here, please? appreciate your time 
We are trying to import bulk of machines and for some reason the define device role is not getting picked up.

**Comment by LBegnaud** [comment]
when you import now, you have to define headers. If you reload the page you should see an example of the headers.

**Comment by wookdark** [comment]
Its isnt working properly, data are getting mismatched

**Comment by LBegnaud** [comment]
can you give me an example of a set of data? I'd venture a guess that you aren't lining up the headers properly

It may be useful for you to put the data into excel, save as csv, then open that csv in notepad to get the content to paste

**Comment by wookdark** [comment]
yeah you are right sorry about that , yes i messed up the headers a bot wrongly 
figured that out 
Thanks a lot friend
