### ISSUE TITLE
Device Monitoring - Observium, LibreNMS.....

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#156]
Hi Everyone,

Commercial DCIM platforms seem to do it all - the monitoring, alerting, asset management, subnet management, etc.

Unfortunately from past experience that they are very overpriced, are vendor specific and when implemented only 20% of the actual feature sets are used because their not implemented properly.

Not wanting to turn netbox into a monitoring tool and given that there are plenty of good monitoring tools out there, I would like to open discussion on the possibility of connecting netbox to a 3rd party monitoring system many of them out there that uses an API.

Currently i see a basic polling and graphing feature is in place for v1 of the release which means some thought has been put into this from the original idea.

What is your vision with this?

**Comment by mdomore** [comment]
Yes i can only dream to enter my device in netbox and it create an entry in my observium, and after pulling netbox get back for exemple inventory from observium :)

**Comment by bellwood** [comment]
There is a hooks system / API that will be available to tie things into external services once it is completed.

Netbox is not slated to be an all-in-one system as it's design is IPAM/DCIM  - not monitoring, ticketing, abuse, etc.

**Comment by mdomore** [comment]
Sure observium is doing a fine job and netbox is not observium but there is some informations in common.

**Comment by jeremystretch** [comment]
The API should provide all the information necessary to populate monitoring systems with node data. I'm going to close out this issue, but if you encounter a specific limitation with the API which isn't already being addressed, feel free to open a new issue.
