### ISSUE TITLE
ImportError: cannot import name 'is_authenticated' with Django REST Framework 3.7.x

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1563]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.3
* NetBox version:  2.1.5

### Description
Django REST Framework 3.7.0 was released today. This release [removes compatibility code ](https://github.com/encode/django-rest-framework/pull/5481) (originally added to support out-of-date Django versions) which we are using in one of the utility classes.

### Workaround
Install a DRF release prior to 3.7.0:

```
pip3 install djangorestframework==3.6.4
```

**Comment by DirtyCajunRice** [comment]
posted an hour before i could. This workaround does not apply to the beta 2.2 release. Installing and then reverting the framework is fine on 2.1.5. Causes a "reported to administrator error on beta2"

**Comment by jeremystretch** [comment]
@DirtyCajunRice I have no issue running v2.2-beta2 with DRF 3.6.4. What is the error being reported?

**Comment by DirtyCajunRice** [comment]
@jeremystretch 
Error:
![image](https://user-images.githubusercontent.com/15788890/31297742-d85a1b4e-aaac-11e7-9e41-210c233a9bf8.png)

**Comment by DirtyCajunRice** [comment]
Fixed it by forcing requirements.txt to djangorestframework==3.6.4

Seems that once the error occurs with 3.7.0 it does not run migrations.
