### ISSUE TITLE
Django error after Upgrade

### ISSUE THREAD

**Issue by davelaramee-ssense** [digitalocean/netbox#1581]
### Issue type
[ ] Feature request 
[X ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.1 
* Running Ubuntu 16.04
* Postgresql 9.5

### Description
Hi!

After upgrading netbox to 2.2.1 following the steps from readthedocs.io I get the following error and the pages won't load: 
See attachment for screenshot.
<img width="656" alt="screenshot 2017-10-12 23 30 07" src="https://user-images.githubusercontent.com/29760840/31529143-709becbe-afa5-11e7-9458-4049b317e1df.png">

<class 'django.template.exceptions.TemplateSyntaxError'>
Invalid filter: 'startswith'

It seems I may have screwed up something but sadly I have no experience with django/python so I do not know what I should look for, I was hoping you guys could help me out.

Thanks in advance!

**Comment by jeremystretch** [comment]
I can't find any instance of that filter being used in the code base. Have you made any modifications to the code? And could you please provide a full stack trace of the error (you can set `DEBUG=True` in the configuration to get this).

**Comment by davelaramee-ssense** [comment]
:)

Indeed I had the title changed and found out a trailing <<<<<<HEAD in templates/_base.html
I fixed that and your awesome product is back online!

Thanks Jeremy for your very fast answer, and also thanks for your networking blog, you've taught me quite a few things!
