### ISSUE TITLE
When creating Interfaces, allow more wildcard variants

### ISSUE THREAD

**Issue by darkstar** [digitalocean/netbox#1586]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.1

### Description
When adding interfaces to a device or device template, there is already a Syntax in place to have multiple numbered interfaces created with one single step: ```Eth1/[1-32]``` for example.

I am managing systems that do not have such a numbered syntax for the network interfaces. For example, I might have to create interfaces ```e0a```, ```e0b```, ```e0c``` and ```e0d```.

Currently, this involves 4 clicks on "create and add another", each with selecting the interface type from the list again, which is tedious.

My suggestion is to allow another syntax: ```e0a,e0b,e0c,e0d``` to create, in this case, 4 interfaces at the same time.

An alternative would be to allow letters in the brackets as well, which would enable a syntax like ```e0[a,b,c,d]``` which would also be fine. Even better, of course, would be ```e0[a-d]``` ... But I am fine with any of these options.

If that is not feasible, I would at least like to have the "Create and add another" button to remember all selections in the drop down lists for the next interface, to reduce clicking required. I can open a new case for this if it is necessary.

**Comment by netsiphon** [comment]
Besides being able to import interface definitions from outside documentation or import previous exports via csv, the ability to add multiple interfaces simultaneously that can't otherwise be easily entered via built-in wildcard is a plus. #1465

**Comment by RyanBreaker** [comment]
I have a working solution almost ready, I'll try to get it pushed this week.

**Comment by darkstar** [comment]
@RyanBreaker just curious, which syntax would your solution provide?

**Comment by RyanBreaker** [comment]
@darkstar It'll be the separated format:
```nohighlight
eth[0-3][a-c,f] => eth0a eth0b eth0c eth0f eth1a ... eth3f
```

**Comment by larsuhartmann** [comment]
Is there a chance for this Pull Request to be merged?
This would really come in handy!
