### ISSUE TITLE
Global search results not showing Virtual Machine primary IP address

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1587]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.1

### Description
When you do a global search, and you get tables for matching Devices and Virtual Machines, the Devices have an IP address column but the Virtual Machines do not.

Relates to #1496: if you go to the Virtual Machines listing and do a search there the IP address is now shown, but the corresponding update to global search results page was not made.

**Comment by darkstar** [comment]
Could you please describe what exactly you are searching for?

If I enter an IP Address (that exists and is attached to a VM) in the global search box, I get 3 tables, Aggregates, Prefixes and IP Addresses. The 3rd table correctly shows the IP Address, and shows the VM as "parent", no matter if it's the primary IP for the VM or not.

**Comment by candlerb** [comment]
Using the global search box on the home page, I search for a device or VM by name, entering part of its name.  For example, let's say I enter "ftp".

I then see devices with "ftp" in their name, and VMs with "ftp" in their name.

In this results page, the table of devices includes primary IP address; however the table of VMs is missing the primary IP address column.

**Comment by jeremystretch** [comment]
This was added for devices in #1561. We can add it for VMs too.

**Comment by darkstar** [comment]
Ah I see, yes, you are correct, that is indeed missing. I searched for an IP that's why I got a different result
