### ISSUE TITLE
"IP Address" section zeroed after upgrade from 2.1.5

### ISSUE THREAD

**Issue by ilyamoshkin** [digitalocean/netbox#1588]
### Issue type
[ ] Feature request 
[X] Bug report     
[ ] Documentation  

### Environment
* Python version:  3.4.5 
* NetBox version: 2.2.1 

### Description
After upgrade from 2.1.5 "IP Address" section is empty but on homepage of netbox counter of IP Addresses show some digits.
https://yadi.sk/i/s4LzW8px3NihJk
https://yadi.sk/i/q1bUGRwL3NihPt

**Comment by darkstar** [comment]
This works fine for me. I also upgraded from 2.1.5 to 2.2.1 today.

Where are you clicking to see the IP Addresses? For me it works with both, clicking "IP Adresses" in the main page or clicking "IPAM->IP Adresses" in the menu.

**Comment by jeremystretch** [comment]
Check that your installed version of `django-tables2` matches what's listed in `requirements.txt`. If you need further assistance, please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
