### ISSUE TITLE
Support for connections from virtual machine interfaces

### ISSUE THREAD

**Issue by irconan** [digitalocean/netbox#1589]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6.3
* NetBox version:  2.2.1 

### Description
While connections don't make sense for some virtual machine interfaces they do if, for example, the virtual machine has tunnel interfaces which connect it "directly" to other devices/VMs.
Interfaces on virtual machines should support connections like those on regular devices do.
I don't think this would require DB schema changes since both virtual machines and devices use the same Interface model so it should be a matter of just adding support in the UI.

Alternatively tunnel interfaces could be made a special case (looking at #1538 as well)

**Comment by jeremystretch** [comment]
Even if we decide to implement some logic for tunnel interfaces, it wouldn't look like physical connections (tunnels can have many endpoints). But that will be addressed in #1538.
