### ISSUE TITLE
Reload report code without restarting server

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1590]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.1

### Description
* You run a report from the web UI
* There's a bug in the python code (e.g. `self.log_fail` instead of `self.log_failure`) which causes an exception, or you just want to change the behaviour
* You fix the code, and re-test it from the command line (`python manage.py runreport <name>`)
* However if you re-run it from the UI, it still fails

At the moment you need to do a full shutdown/restart of netbox.  It would be nice if it could pick up that the report file has changed since it was last loaded, and reload it automatically.

**Comment by RyanBreaker** [comment]
@jeremystretch In what way are reports implemented? Is it a from-scratch feature or is it something built upon from a module?

**Comment by Yakelixir** [comment]
Help still wanted? I have been working on this issue in my own

**Comment by arsenakishev** [comment]
I just tested this recently. After fixing a bug that causes the exception, the reports page UI shows a passing result. Can anyone comment on this issue? It seems like it has been resolved.

**Comment by zelfix** [comment]
@jeremystretch  It's not an issue of NetBox. Users can use the option "reload" of gunicorn server for auto restarting gunicorn workers when source code changes. http://docs.gunicorn.org/en/19.0/settings.html#reload

**Comment by TakeMeNL** [comment]
Just a small update, running Netbox via docker-compose (ninech/netbox-docker) and i can edit report scripts live, not reload whatsoever.

**Comment by candlerb** [comment]
Yes, I can confirm the behaviour is correct now - tested with v2.5.2. I can break a report, run it in UI (get exception), fix it, run it in UI (and it works), without any restarts.

Maybe the fix happened in Netbox, maybe in Django.

**Comment by DanSheps** [comment]
I don't think this should be closed out yet.  gunicorn is not the only way to establish the workers.  For example mod_wsgi with Apache or uWSGI.

I will let @jeremystretch weigh in though perhaps.
