### ISSUE TITLE
Add Tenant ownership to Rack Reservations

### ISSUE THREAD

**Issue by DirtyCajunRice** [digitalocean/netbox#1592]
### Issue type

[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description
I propose an addition to the rack reservation table that allows association with a Tenant (Exactly like IP addresses) which would allow racks used for "Shared Colocation Environments" to have the ability to reserve less than an entire rack for a customer. E.g. 7-8U per customer. 

This would not matter if they were managed as devices are able to be assigned. But for environments where you only are keeping track of what section you have assigned the Tenant, it would be very helpful.

**Comment by DirtyCajunRice** [comment]
I am comfortable enough with python to make these changes myself but I do need a point in the right direction for files, to begin with. Much appreciated

**Comment by RyanBreaker** [comment]
@DirtyCajunRice Start by looking in the `dcim` directory and the models and everything to work on this should be in there.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DirtyCajunRice** [comment]
@RyanBreaker I have the tenants showing up as an option in the reservation_add, and the tenant showing up as part of the visible table when looking at a rack, but when when you look at the main rack reservations page (BulkDeleteView) it is empty. Any ideas?
https://github.com/DirtyCajunRice/netbox

**Comment by DirtyCajunRice** [comment]
ok figured that part out. Just need to figure out showing tenancy enumeration in the search box and a new box in the tenant main page

**Comment by DirtyCajunRice** [comment]
Ok, i have added the box to the tenant page as well and it is propagating properly. All that is left to figure out the tenancy enumeration in the FilterForm. Some help would be much appreciated.

**Comment by DirtyCajunRice** [comment]
@jeremystretch Sorry to ping you I would just love to make this pull request. 
In netbox/dcim/forms.py under `class RackReservationFilterForm(BootstrapMixin, forms.Form):`
the queryset for tenant currently is `queryset=Tenant.objects.annotate(filter_count=Count('racks__reservations'))`
Am i missing something to make this query rack reservation ownership instead of rack ownership?

**Comment by DirtyCajunRice** [comment]
@jeremystretch Tag 2.3?
