### ISSUE TITLE
CSV Import IP range

### ISSUE THREAD

**Issue by idiotproven** [digitalocean/netbox#1602]
### Issue type
[X] Feature request
[ ] Bug report
[ ] Documentation

### Environment
    Python version: 3.5.2
    NetBox version: 2.2.1

### Description
When using the IP Address Import (from CSV) you are today unable to add an IP range like in the bulk option when adding manually. 

Would be nice to be able to import ranges instead of individual IPs. 

E.g:
address,status
10.10.10.[50-60],active

**Comment by jeremystretch** [comment]
CSV import requires exactly one object per line. This is a fairly universal scheme and we won't deviate from it. If you need to replicate many addresses within a range, you'll need to either script out the generation of a CSV, or script out their creation directly within the Python shell.
