### ISSUE TITLE
Checkboxes on UI at "/ipam/vrfs/X" Not Linked to Any Action

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1603]
### Issue type
[X] Feature request 
[X] Bug report      

### Environment
* Python version:  2.7.12
* NetBox version:  2.2.1

### Description
When using the WebUI and looking at the URL `/ipam/vrfs/[X]/`, on the right of the page, this pane is shown:
![image](https://user-images.githubusercontent.com/7783306/31629709-aaf19b24-b271-11e7-8585-3392f69e3dab.png)
The checkboxes to the left of each line _aren't_ linked to any mass edit / delete option. 

This is request is to either remove those checkboxes or, more preferably, _enable_ a mass edit / delete option similar to what is available on at the URL `ipam/ip-addresses/`.

**Comment by huzichunjohn** [comment]
I think the reason of this bug is that in some views we set the visible attribute of the prefix table's pk column with True, like below:
![screenshot_20171018154051](https://user-images.githubusercontent.com/2769613/31706222-be5b0614-b41a-11e7-980a-d4d7034d897c.png)

**Comment by huzichunjohn** [comment]
![screenshot_20171018154632](https://user-images.githubusercontent.com/2769613/31706434-8ed10582-b41b-11e7-9a5f-edf9b3109c8f.png)
there are some tips about django-tables2.

**Comment by huzichunjohn** [comment]
I think the reason of this bug is that in some views we set the visible attribute of the prefix table's pk column with True, like below:
![screenshot_20171018154051](https://user-images.githubusercontent.com/2769613/31706875-080b99a2-b41d-11e7-877e-0c8c543784da.png)

**Comment by bdlamprecht** [comment]
Similar unused check boxes can be seen at the URL `dcim/device-types/X/interfaces/delete/`:

![image](https://user-images.githubusercontent.com/7783306/31907613-96cce682-b7f1-11e7-95da-7ee040564890.png)

Would this be due to the same bug previously identified?

**Comment by RyanBreaker** [comment]
I found a fix for this by accident while browsing the source, hope this helps!

**Comment by huzichunjohn** [comment]
[https://stackoverflow.com/questions/45856480/django-tables2-column-name-is-changed-after-refreshing-page](url)
