### ISSUE TITLE
Tenant - Custom Field search not returning expected results

### ISSUE THREAD

**Issue by t0i** [digitalocean/netbox#1606]
### Issue type
[ ] Feature request
[X] Bug report
[ ] Documentation

### Environment
* Python version:  2.7.6
* NetBox version:  v2.2.1

### Description
How to reproduce:
in Django admin > Custom Fields > Add Custom Field > Name: "CustomerID", Objects: select all objects, Type: Text. Hit Save.

In https://netboxurl.domain/tenancy/tenants/ > Create new tenant > Name client "Bob", under Custom Fields, enter "testing" in the CustomerID field. Hit Create.

Go to Top search bar, search for "testing" and we see no results on the page. URL for this page is "https://netboxurl.domain/search/?q=testing"

---
Expected results:
When I instead input the 'testing' text into the Comments field for the Tenant (Bob), then search for "testing", I get the expected search page which includes the Bob tenant.

**Comment by jeremystretch** [comment]
The generic `q` filter does not search custom field values, because this is often undesired behavior. When you add the `CustomerID` field, a new search field appears at the bottom of the right-hand pane on the tenants list. Use this field to search the custom field.

**Comment by t0i** [comment]
I have custom fields that cross all object types so its too much of a burden to search custom fields in the method netbox currently provides.
