### ISSUE TITLE
Allow amending of INSTALLED_APPS and MIDDLEWARE

### ISSUE THREAD

**Issue by Ichabond** [digitalocean/netbox#1607]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.1

### Description
settings.py currently imports several optional settings from `configuration.py`, but this does not include `INSTALLED_APPS` and `MIDDELWARE`. Adding this functionality would make customisation (such as monkey patching) of Netbox a whole lot easier, without having to modify `settings.py`, making sure this file remains consistent with upstream.
The change should only require a minor rewrite of `settings.py`. eg: `INSTALLED_APPS = INSTALLED_APPS + getattr(EXTENDED_APPS, configuration, ())`, the equivalent action for `MIDDLEWARE`

**Comment by jeremystretch** [comment]
While users are welcome to fork the project to extend it for their own needs, this isn't something we're going to actively encourage in the master code base. NetBox is packaged as a cohesive application, and is not intended to be modified arbitrarily.

**Comment by ferringb** [comment]
Offhand, there is a difference between 'encouraging' and 'making it a pain to do'.  Django app wise, it's semi standard to make it possible for people to add apps if they need it- sentry for example, does exactly this, and is "packaged as a cohesive application".

Other projects have found a way to accomplish what you're intending, while also protecting their time (IE, not having to debug some random broken application).

I'd strongly ask you to reconsider, and instead we work out a way that everyone is happy.  Forking the codebase for adding internal only functionality isn't going to make users lives 'fun', nor is it great for the netbox ecosystem.
