### ISSUE TITLE
Get virtual machine in interface from api endpoint /ipam/ip-addresses/

### ISSUE THREAD

**Issue by maximebrun** [digitalocean/netbox#1609]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7 
* NetBox version:  2.2.1 

### Description

In interface from API endpoint /ipam/ip-addresses/, we get only device, not the virtual machine.

**Comment by jeremystretch** [comment]
Fixed in 6f2f8697aec9470c036e400c5550ec6dce3a1907
