### ISSUE TITLE
Power options under racks and devices.

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1611]
Please add Power options under racks and devices:

Racks:
Maximum allowed power usage  (watts) per rack
Power circuits: A, B , A+B
PDU A
PDU B

Devices:
Max power consumption (watts)
NR of PSU-s (1-10)
each PSU connection to PDU in rack ( A or B )

PSU: amount, list 1-10
Power consumption: W

And now when adding devices into racks, the racks total power consumption (based devices amount & power consumption) should be calculated and shown.

**Comment by jeremystretch** [comment]
Duplicate of #54
