### ISSUE TITLE
Django: Server Error after update to v2.2.1

### ISSUE THREAD

**Issue by markhayes0338** [digitalocean/netbox#1613]
### Issue type
[ ] Feature request 
[ x ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5 
* NetBox version:  2.2.1 

### Description
I upgraded from 2.0.9 to 2.2.1 and when trying to view a device in any rack I get the following error.

<class 'django.db.utils.ProgrammingError'>

column ipam_service.virtual_machine_id does not exist
LINE 1: ...vice"."last_updated", "ipam_service"."device_id", "ipam_serv...
                                                             ^

I followed the upgrade instructions and ran ./upgrade.sh -2 and this was the result.

Let me know if you need any other logs or info.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
