### ISSUE TITLE
Adding support for Antenna & Dry Contacts mapping 

### ISSUE THREAD

**Issue by thefreakquency** [digitalocean/netbox#1615]
### Issue type
[ X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  Example: 3.5.4 
* NetBox version:  2.2.1

### Description
Please consider adding the following:
* Tracking of Antennas, the same way a network port or power is tracked. 
* Tracking of Dry Contacts, the same way a network port or power is tracked. 

These 2 new items would be mostly used by people in the Telco world. 

Antennas: Being able to track device to Antenna path would be beneficial. This could be used to track a GPS antenna of an NTP server or a transmit antenna from a Radio repeater. In both case, the device is hooked on the network and powered, it's just a matter of adding another level of granularity. 

Dry Contacts: The same way other connections are tracked, allow the tracking of dry contacts connections (ie: Alarm board on a server hooked to a monitoring device).

**Comment by jeremystretch** [comment]
This would be covered by #968
