### ISSUE TITLE
Normalize Interface Names in "LLDP Neighbors" Tab

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1621]
### Issue type
[X] Feature request 

### Environment
* NetBox version:  2.2.1

### Description
Currently, the "LLDP Neighbors" tab marks interfaces that don't match **_exactly_** with what NAPALM returns from the device as red (or incorrect).

On 'ios' devices, this is not helpful as the NAPALM (currently)[1] only supports returning the "short-name" of the interface.

This can be seen in the following screenshot:
![netbox lldp neighbors](https://user-images.githubusercontent.com/7783306/31739240-838a6184-b40a-11e7-8573-fbaf35f1eb3d.png)

Even though the interfaces **ARE** correct, but the names don't match exactly, which causes some confusion and second-guessing to occur.

[1] This all may be a moot point since apparently NAPALM has a proposal for [Hackathon 2017](https://github.com/napalm-automation/hackathon-2017/issues/5) to enable the option to return the normalized interface name

**Comment by jeremystretch** [comment]
The root issue seems to be that NAPALM only returns the port ID and not the full name. Here's what we see on a device:

```
Neighbour Information:
Chassis type       : Mac address
Chassis ID         : 88:5a:92:4e:12:ff
Port type          : Interface name
Port ID            : Te1/49
Port description   : TenGigabitEthernet1/49
System name        : cisco-switch
```

Here's what NAPALM reports:

```
"xe-0/0/4": [
    {
        "hostname": "cisco-switch",
        "port": "Te1/49"
    }
]
```

I think it would be sufficient for our purposes to also return the port description. Then, we could consider the neighbor "correct" so long as one of the two matches the local interface defined in NetBox.

**Comment by jeremystretch** [comment]
I've tweaked the LLDP validation Javascript a bit in 81ca6f7. It should now accept short forms reported via LLDP which match a configured long form (e.g. `Gi0/1` matches `GigabitEthernet0/1`). Please try it out and report back.

**Comment by bdlamprecht** [comment]
Yes, this change **did** fix the matching the "short-name" returned by Cisco IOS. Thanks for the fix!

**Comment by jeremystretch** [comment]
It seems that some Cisco IOS platforms return the full interface name and some return the abbreviated form. I'll need to adapt the row-highlighting Javascript to match either case.
