### ISSUE TITLE
Field character max length is too short.

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1622]
Hi,

Netbox limits service name length - "name": ["Ensure this field has no more than 30 characters."]

Why this is limited? This is too short for us (as service name contains FQDN and port number). Please limit this to max 100 characters, like comment field have etc.

Edit: Similar request (Interface name lenght) https://github.com/digitalocean/netbox/issues/1402 ) was accepted and changed, so I'm hoping the same result.

**Comment by jeremystretch** [comment]
The service name is only meant to hold a protocol, e.g. "SSH" or "HTTP." There is no reason to include a FQDN, as that is inferred from the device to which the service is assigned.
