### ISSUE TITLE
Ability to disable 'secrets'

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#1623]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version:  2.2.2

### Description

Since we are not using 'secrets', it would be nice to have a way to disable them entirely from the UI to reduce clutter and having to explain why it's there.

I note that when the user is not logged in, the secrets sections are already hidden from the main menu and on the Device page.

Looking at the code [1](https://github.com/digitalocean/netbox/blob/develop/netbox/templates/inc/nav_menu.html#L351), [2](https://github.com/digitalocean/netbox/blob/develop/netbox/templates/dcim/device.html#L175), right now it appears to be a checking only whether the user is logged in.  This could be factored out into a more general test which also checks a global flag in `settings.py`; or perhaps add a new "permission" type e.g. "can view secrets".

**Comment by jeremystretch** [comment]
Folding this in with #426
