### ISSUE TITLE
Adding Device depth tracking and visualisation

### ISSUE THREAD

**Issue by thefreakquency** [digitalocean/netbox#1627]
### Issue type
[ X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.4 
* NetBox version:  2.2.1

### Description
By tracking device length (depth) at the device type level, we could have the side view of the rack elevation.

It would help to visualize different server depths and help people at the planning level to not cram stuff in racks where it does not make sense, like putting a 20 inch long device like a switch or converter between 2 full length servers, where you could not put your hand in between to access plugs, etc... 

It might be related to issue #450 , but in this case, I dont mind about the rack overall footprint but rather equipment footprint visualization (from the front rail toward's the back). Issue #450 could help to display both front and back if rail spacing is configurable (as this can be fixed or manually adjusted on a per-rack basis), but starting with the front rail could be a good beginning.

**Comment by jeremystretch** [comment]
This would impose a large amount of new validation logic with very little gain. Tracking the exact depth of a device would require:

1. Defining the rack's rail-to-rail length
2. Checking that the device length is less than the rail-to-rail length for full-depth devices
3. Checking that the device length plus the device length of each device in the opposite face is less than the rail-to-rail length

I think it's sufficient to simply stick to "half-depth" and "full-depth" classifications: The former will accommodate a device on the opposite face and the later will not. A large part of this classification has to do with airflow anyway, not just physical length.

**Comment by thefreakquency** [comment]
Items 1 & 2 are not necessary as it's only validating data, but it would be obvious if there was to have an overlap on the drawing.

Tracking rail to rail lengh is a good thing, especially in DC that has different rack generations, rack models or where rails spacing is dictated by the different equipement to be mounted in those racks. 

In our world, we don't use much the back rail, and when we do, we are not putting anything on the other side of the rail except maybe a blank plate.

I was looking for basic representation, not a full validation of data, but I truly understand the point you are making. What I had in mind was something like this: 
![image](https://user-images.githubusercontent.com/25624251/31788924-5818d97a-b4de-11e7-8e5d-46352bffe115.png)

**Comment by jeremystretch** [comment]
After giving this some thought, I don't see it adding any real value to NetBox right now. It's something we might reconsider in the future but there are many other features to knock out before then.
