### ISSUE TITLE
 Field character max length is too short, explanation.

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1629]
Hi,

About the issue 1622 (https://github.com/digitalocean/netbox/issues/1622). Closing the issue, without getting change to explain my situation, left me with no other option, than make a new one.

You see, we are using load balancer, virtual service name is for example vs_www.domain.com_5896, the same IP can have hundreds of names with different ports. So our need is to describe in this field IP and port relation(s). Also for firewall IP -s, the more specific  description is needed. So yes, FQDN is not actually needed, plain text is OK as it is now, but the 30 character is length is too short.

Please extend it also to 64 characters, like You did with interface names.

**Comment by jeremystretch** [comment]
I explained in the first issue why this is not going to change.
