### ISSUE TITLE
Which exact web server do I need?

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#163]
In the getting started document does not specify which services you need exactly to be able to use netbox. I do understand you can either use apache or nginx as the http server but, I never used supervisor or gunicorn. Do you have to configure those too to work?

**Comment by paradoxni** [comment]
You need supervisor and gunicorn and then Apache or Nginx to proxy to these.

**Comment by chagara** [comment]
ok thanks. supervisor and gunicorn installed by pip ?

**Comment by jeremystretch** [comment]
If you're unsure of which components you want to use, please just stick to the exact installation outlined in the [getting started](https://github.com/digitalocean/netbox/blob/develop/docs/getting-started.md) guide.

**Comment by paradoxni** [comment]
docs/getting-started.md has the steps for supervisord and gunicorn, after the Apache/Nginx steps.

**Comment by chagara** [comment]
thanks. I was just trying to follow it but, was not sure if they were needed or not. They do not get installed with the requirements.txt and it does not mentioned that you need them and to install them. Thank you!

**Comment by chagara** [comment]
never mind last message. I missed a step. Thank you.
