### ISSUE TITLE
Extend reports to perform post-run actions

### ISSUE THREAD

**Issue by cslingerland** [digitalocean/netbox#1631]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description
Would it be possible to setup some form of emailing of reports, or an indication that a report was run? This would be good so that management doesn't have to go into Netbox and parse out what they're looking for, and then run the report. I don't think the database would need to be touched unless you wanted to track emails sent.

**Comment by jeremystretch** [comment]
There will likely be many things people want to do after running a report: sending an email, writing a log, calling a webhook, etc. These are all possible now by overriding the `run()` method, but it would be more convenient to add a `post_run()` method which report authors can more easily extend.

Related, here's an example showing how to [send email in Django](https://docs.djangoproject.com/en/1.11/topics/email/#quick-example). The configured list of administrators is available at `django.conf.settings.ADMINS`.

**Comment by lampwins** [comment]
Given there there is consensus that #81 will rely on Django signals, would it also be prudent is put in the effort here to fire signals on report completion?

**Comment by jeremystretch** [comment]
@lampwins I'll defer the signals work until we have a chance to take a look at the whole project and go through adding signals everywhere they need to be, for both #81 and #1127.
