### ISSUE TITLE
Reports not working

### ISSUE THREAD

**Issue by t0i** [digitalocean/netbox#1632]
### Issue type
[ ] Feature request
[X] Bug report
[ ] Documentation

### Environment
* Python version:  2.7.6
* NetBox version:  2.2.2

### Description
The following error is displayed when going to the Reports page ( https://netboxurl.tld/extras/reports/ )

"
<class 'django.db.utils.ProgrammingError'>

relation "extras_reportresult" does not exist
LINE 1: ...sult"."failed", "extras_reportresult"."data" FROM "extras_re...
"

This instance of netbox has been upgraded from older versions and isn't a new deploy. 

Thanks,

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by jeremystretch** [comment]
It looks like you have unapplied migrations. Please see the [common issues](https://github.com/digitalocean/netbox/wiki/Common-Issues#programmingerror-exception-following-a-recent-upgrade) page in the wiki.

**Comment by t0i** [comment]
Thank you. My bad, didn't read the part where I needed at least PostgreSQL 9.4 to upgrade to netbox v2.2.0 +.
