### ISSUE TITLE
Add support for bridge interfaces

### ISSUE THREAD

**Issue by patrick7** [digitalocean/netbox#1633]
### Issue type
[x] Feature request
[ ] Bug report
[ ] Documentation

### Description
On a router I have some bridges with multiple interfaces.
With Netbox it's possible to assign an IP address to the (virtual) bridge interface, but it is not possible to reflect which interface is in which bridge. There should be a possibility similar to the bonding devices.

**Comment by jeremystretch** [comment]
NetBox doesn't support modeling bridges. This is one of those things that crosses into general configuration management and we have to avoid falling down that rabbit hole.

**Comment by patrick7** [comment]
So how do you recommend to document the IPs on bridges? (virtual interfaces?) And how to reflect interfaces in a bridge?

There is a possibility for LAG interfaces, something similar for bridges would be perfect (like master / child interfaces).

**Comment by jeremystretch** [comment]
You can create a virtual interface named e.g. `BVI1` to represent a bridge group and assign IP addresses to it. NetBox does not model bridge groups, but maybe #150 will help once it's been implemented.

**Comment by patrick7** [comment]
That's possible for LAGs - why not for bridges? 
I need to reflect which interface is in which bridge, similar to LAGs & LAG members.

**Comment by jeremystretch** [comment]
Conceptually, a bridge group is the same as a VLAN. Let's see how #150 plays out and you can ask to reopen this issue if it still does not meet your needs.

**Comment by alexjhart** [comment]
#150 is implemented and works great. I'd love to see bridge modeling added. It would work almost identically to LAG modeling, so I expect most of the code would be recycled from that. There are network devices, like Mikrotik routers and switches, that heavily incorporate bridges into the VLAN and port configuration (ports are added to a bridge, VLANs are added to bridge and bridge ports, not the physical interfaces), so I don't see this as any less relevant to include than LAG and VLAN in Netbox. Right now, I'm trying to model a bridge, which contains LAGs and other ports which also manages VLANs for the bridge ports and CPU. I can almost fudge this with LAGs, but LAGs can't have parent LAGs. If I use a virtual interface, I can't track which bridge ports are part of. I would also like to show bridge configuration on hypervisors. Can we please re-open this?
