### ISSUE TITLE
Can't View Devices After Upgrading to 2.2.2

### ISSUE THREAD

**Issue by robduffy2010** [digitalocean/netbox#1636]
### Issue type
[ ] Feature request 
[ X ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:   2.2.2

### Description

After updating to version 2.2.2, I receive the following error message when attempting to view or edit any device.  

```
<class 'django.db.utils.ProgrammingError'>

column ipam_service.virtual_machine_id does not exist
LINE 1: ...vice"."last_updated", "ipam_service"."device_id", "ipam_serv...
```

**Comment by darkstar** [comment]
Are you sure you ran the upgrade.sh script? From which version did you upgrade? This is probably the same problem as reported in #1635 

You might need to upgrade your PostgreSQL installation

**Comment by robduffy2010** [comment]
It turned out I had two Postgres versions running and Netbox was using the old one (9.3).  I configured it to use the new version and everything is working now.  Thanks for the quick response and sorry for the noise!
