### ISSUE TITLE
Support for Regions

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#164]
1. At the very least, allow for support to introduce regions for sites.  It could later be expanded to auto assign sites to regions based on country logic (ie setup rules to auto assign a site to a region).
2. Regions could also be applied to subnets for better IPAM either directly like sites or indirectly via Region -> Site -> Rack/Rack Group -> Device(s) -> Interface(s) -> Subnet.  From Issue #155 this may not be enough as subnets could be assigned to a client but not on a netbox managed device (ie it could be advertised via a routing protocol and not directly connected).

**Comment by jeremystretch** [comment]
Implemented a new Region model in f3b9930dea3d7cd12051133b55e42083126628eb.
