### ISSUE TITLE
Allow upload of custom logo and and change title of each page from Netbox

### ISSUE THREAD

**Issue by snazy2000** [digitalocean/netbox#1641]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  2.2.2

### Description

Allow the ability to upload own logo and change the page titles 

Allow Netbox to be what ever, this could be done within the config file
<title>{% block title %}Home{% endblock %} - NetBox</title>

**Comment by jeremystretch** [comment]
I don't think it's appropriate to build whitelabel support into an open source project. If you really want to change the displayed name and logo, you'll need to fork the project and modify the base template to suit your needs.

**Comment by snazy2000** [comment]
No problem, that's what have been doing but was hoping to remove that part of the update process 👍

**Comment by thefreakquency** [comment]
For the logo, we simply overwrite the /static/img/netbox_logo.png file & the CSS for minimal UI tweaks (We are simply changing the menu bar color).

Having customized graphics help the business approval & end-user adoption of that great project. That being said, I totally understand @jeremystretch approach. I believe there would be easy ways to keep Netbox's fair publicity while providing a comfortable look & feel to the end users (Like having a logo or a mention like "Netbox (v2.2.2) on HOSTNAME) in the footer.
