### ISSUE TITLE
Uploading image gives 413 Request Entity Too Large error

### ISSUE THREAD

**Issue by iwroteascript** [digitalocean/netbox#1646]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.6
* NetBox version:  2.2.1

### Description

When trying to upload a 2.4Mb JPEG file and attach it to a rack, I get a "413 Request Entity Too Large" error.  If this is expected, I recommend redirecting to a 413 error page, with information on file size limits for uploads.  Screenshot of error is attached.

<img width="1435" alt="screen shot 2017-10-25 at 9 45 32 am" src="https://user-images.githubusercontent.com/536467/32002093-9b83e1de-b969-11e7-9f0d-0f8db5960482.png">

**Comment by jeremystretch** [comment]
This is a configuration of your HTTP daemon and is not controlled by NetBox. For example, you can increase the max request size for nginx by setting the `client_max_body_size` parameter ([more info](https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/)). The ideal setting will depend on your environment.
