### ISSUE TITLE
Interface ordering for interfaces that have no prefix

### ISSUE THREAD

**Issue by autonomic** [digitalocean/netbox#1650]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.1
* NetBox version:  2.2.2

### Description
We use Brocade ICX switches, based on FastIron, and the interface names do no have a prefix. Unless you show details of a specific interface using `show interfaces ethernet 1/1/1` the interfaces will always be listed based on STACKID/SLOT/PORT and in order (e.g. 1/1/1, 1/1/2, etc..).

In Netbox when I add all these interfaces to a device or device type, I see interfaces which are listed like so:

1/1/1
1/1/10
1/1/11
1/1/12
1/1/13
1/1/14
1/1/15
1/1/16
1/1/17
1/1/18
1/1/19
1/1/2
1/1/20
1/1/21
1/1/22

and so on ... (please see screenshot in the link below)

https://www.dropbox.com/s/weq5bxnlyrrv5em/Screenshot%202017-10-26%2007.20.43.png?dl=0

I would prefer to have them show up in Netbox ordered in sequence (e.g. 1/1/1, 1/1/2 .....1/2/1, 1/2/2, etc...), without having to prefix them with (e.g. "ge-"). In FastIron you don't show inteface using a prefix so it would great if I could list them in Netbox the same way.

Thanks for your help.

**Comment by oysteingy** [comment]
Hi, 

Same interface naming standard on Nokia platforms. 

I don't have access to Netbox < 2.2 currently, but I do believe that the ordering for these kind of interface names changed with the works done in #1523.

**Comment by MeisiCB** [comment]
Is it normal that the Interface Ordering "Name (alphabetically)" is not ordering by Name in the Device View? It's actual ordering by the Chars from the Interfacename until the first Number.       

querysets.py
TYPE_RE = r"SUBSTRING({} FROM '^([^0-9]+)')" 

The name "ge-1 b" results in _type  "ge-"
