### ISSUE TITLE
Additional Details on Import Errors

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1654]
### Issue type
[X] Feature request 

### Environment
* NetBox version:  2.2.2

### Description
When using the `Import` feature with large amounts of data, when duplicates exist, an error is correctly reported.  However, it would be helpful to provide (if possible) specific details on what item is causing that error besides the line number.

As an example, when attempting to import `region` information via the UI, this is seen:

![image](https://user-images.githubusercontent.com/7783306/32118701-e41934e2-bb0f-11e7-8462-f9a14d406f06.png)

While it is technically accurate, currently I have to spend time trying to find the duplicate entry.  With this new feature, it would make it easier to locate and remove the duplicate entry if the error text in red would report something along the lines of:
> Row 49 name: Region with Name "Estonia" already  exists.
> Row 49 slug: Region with Slug "es" already exists.

With that information, I could do a search on the current webpage and remove the offending entry instead of trying to count lines.

**Comment by jeremystretch** [comment]
I dug into this a bit, but it doesn't seem possible to implement without implementing a custom field class and declaring it for _every_ CSV import field in every form. (The field value isn't passed as a key for error message formatting by default.) The level of effort required isn't going to be worth the modest gain, unfortunately.

**Comment by bdlamprecht** [comment]
Yeah, no worries, this issue was originally opened as a "nice to have".
I'd work be done on other, more important issues, such as `DeploymentTemplate` (#1364).

(:electric_plug: , :wink:)
