### ISSUE TITLE
Extensions for custom fields

### ISSUE THREAD

**Issue by uncleVALERA** [digitalocean/netbox#1658]
Hello!

How do i can  create custom field for specific devices role?
How do i can to use list of devices from some role as type "select" of custom field?

Thank you!

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
