### ISSUE TITLE
Cannot see Virtual Interface information in API GET request

### ISSUE THREAD

**Issue by Comm4nd0** [digitalocean/netbox#1659]
Hi, i'm unable to understand how i get the virtual interface information about a device from an API GET request. 

I did find this: https://groups.google.com/forum/#!topic/netbox-discuss/CvZsSAiLthY which i believe this person is asking something similar. However, the answer doesn't seem to solve it. It says "you'll need to determine the prefix", but how do you do that when there is no reference to the virtual interfaces what so ever? As far as i can tell, if you were to do a GET request on a device there is no information to say that there are virtual interfaces for it. I've also tried searching for the device in the IPAM/ip-addressess area but nothing worked there either.

If there is any way i can do this, please tell me! otherwise i must list this as a bug as i believe it should show when doing a GET request.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
