### ISSUE TITLE
Manage VHID in IPAM

### ISSUE THREAD

**Issue by pep-un** [digitalocean/netbox#1660]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 
* NetBox version: 2.2.2

### Description
Hello and Thanks for the amazing work on netbox !

Is it possible to include a new field for CARP and VRRP addresses in order to manager the VHID. 
Few IPAM are able to manage VHID but avoiding conflict is as important as for IP addresses. 

It could also be nice to have a single page with all used VHID as for VRF/VLAN/... 

Best regards,

Stéphane

**Comment by jeremystretch** [comment]
Please describe in detail the modifications you are proposing be made tp the data model.

**Comment by jeremystretch** [comment]
Closing this out due to lack of activity.
