### ISSUE TITLE
Unable to assign vlan group to prefix

### ISSUE THREAD

**Issue by will-h** [digitalocean/netbox#1663]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3
* NetBox version:  2.2.2

### Description
Recently upgraded from 2.0.7 to 2.2.2.

After upgrading, I can no longer set a vlan group on a prefix. I can select the appropriate vlan group but this doesn't persist when i click 'Update'

![screen shot 2017-10-31 at 09 01 16](https://user-images.githubusercontent.com/2152161/32215734-b8cdab7a-be1a-11e7-88e9-aae02f968f4b.png)

This means I'm unable to associate that IP prefix with a vlan. I've tried disassociating existing prefixes from a vlan, and am then unable to add them.

**Comment by maximebrun** [comment]
Hello,

It seems to be a problem with django-filter 1.1.0. Downgrade to version 1.0.4 fix the problem for me.

**Comment by engageant** [comment]
I'm having a [similar issue](https://groups.google.com/forum/#!topic/netbox-discuss/lywG382f_NI).  I downgraded django-filter to 1.0.4 and it doesn't help.  Unsure if these issues are related, so I figured I'd tack on to this before opening a new issue.

**Comment by jeremystretch** [comment]
> After upgrading, I can no longer set a vlan group on a prefix.

NetBox has never supported assigning a prefix to a VLAN group. That wouldn't make sense. A prefix can only be assigned to a single VLAN. The VLAN group field is only there to help choose a VLAN.

**Comment by will-h** [comment]
@jeremystretch Apologies, my description of the problem was incorrect. The net result is the same, though - I was unable to select a vlan and associate it with a prefix.

@maximebrun thank you, downgrading django_filters ("pip3 install django_filter==1.0.4") resolved the problem for me.

**Comment by will-h** [comment]
Back on django_filters 1.1.0, as this problem appears resolved in version 2.2.4 #1671  - see #1649
