### ISSUE TITLE
Create and Add Another IP does not bring up next available IP

### ISSUE THREAD

**Issue by traveler3468** [digitalocean/netbox#1665]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  2.2.2

### Description
When adding an IP address you can select to "Create and Add Another IP". I believe this used to bring up the next available IP address in the prefix you were working in? However; when I select the option now the IP address field is returning to the first IP address I added when I started adding IP addresses using the form. For example if I start by adding ip address 10.10.29.1/24 and then I select the Add another button it brings up the ip address field pre-filled with 10.10.29.1/24. And it does the same thing after adding more addresses that way. I can add 10 different addresses in the same prefix and it will bring up the address that I started with on the new form.

**Comment by jeremystretch** [comment]
> I believe this used to bring up the next available IP address in the prefix you were working in?

I don't think NetBox has ever had this behavior.

> For example if I start by adding ip address 10.10.29.1/24 and then I select the Add another button it brings up the ip address field pre-filled with 10.10.29.1/24.

NetBox does not do this on its own. It's possible your browser or an extension may be pre-populating the form field for you.

At any rate, this enhancement would be covered by #648 so I'm going to close this out as a duplicate.
