### ISSUE TITLE
Rack reservations must be deleted before deleting a user

### ISSUE THREAD

**Issue by respawner** [digitalocean/netbox#1666]
### Issue type
[ ] Feature request
[X] Bug report
[ ] Documentation

### Environment
* Python version:  2.7.12
* NetBox version:  2.2.2

### Description

When trying to delete a user that has made some rack reservations, Netbox expects these reservations to be deleted before deleting the user.

#### Steps to reproduce

1) Create a user
2) Login as the created user
3) Create rack reservations inside a rack
4) Login as administrator
5) Delete the previously created user

#### Expected behavior

I'd expect the user to be deleted without needing to delete the rack reservations. For example, one of my colleague can do the some rack reservations but when he will leave the company (and remove his user account) reservations will most likely still be valid.

#### Screenshot

![rack_reservations](https://user-images.githubusercontent.com/736209/32235634-53bf2826-be60-11e7-8c2b-8f1f04670fd0.png)

**Comment by jeremystretch** [comment]
Rack reservations are intentionally tied to a specific user. This is to prevent reservations from becoming disassociated with an owner and stagnating. However, you raise a good point in that the UI should provide a mechanism for easily reassigning a reservation's owner.
