### ISSUE TITLE
Services view

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1673]
**Issue type**

[x] Feature request
[ ] Bug report
[ ] Documentation

**Environment**

Python version:
NetBox version: 2.2.2

**Description**

Services view:
 
Overview of services, to filter and search them etc. So that is possible to get overview of services what are defined in particular site or in group of devices.

**Comment by darkstar** [comment]
Somewhat related to #1591

**Comment by jeremystretch** [comment]
Implemented in 7819d9c on the `develop-2.4` branch
