### ISSUE TITLE
Support for device clusters

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1674]
**Issue type**

[x] Feature request
[ ] Bug report
[ ] Documentation

**Environment**

Python version:
NetBox version: 2.2.2

**Description**

Add support for device clusters in similar way like virtualization clusters have done.
Cluster device should have similar properties like normal device has. Ability have Virtual interfaces, IP-s and Services etc. Cluster device should show information about his member devices.

**Comment by jeremystretch** [comment]
See #99 (virtual chassis/stacked devices)
