### ISSUE TITLE
Fixed fibre form factors for interfaces

### ISSUE THREAD

**Issue by tvberlin** [digitalocean/netbox#1675]
### Issue type
[x] Feature request
[ ] Bug report
[ ] Documentation 

### Environment
* Python version:  3.4.2
* NetBox version:  2.2.4

### Description

We're documenting WDM system and patchpanels in Netbox and are missing fixed form factors as "LC/PC" (and more). We'd appreciate if you would add the following fixed interfaces form factors:

LC/PC
LC/APC
SC/PC
SC/APC
E2000/APC
ST/PC
FC/PC
MPO
MTP

Thanks,
Theo

**Comment by jeremystretch** [comment]
NetBox does not currently support modeling patch panels. Please see the comments in #20.

**Comment by tioan** [comment]
we use some intel nics (i350-f2) with fixed LC/PC ports instead of sfp slots, so it make sense to add this fixed fibre firm factor.
