### ISSUE TITLE
Internal Server Error, Upgrade from 2.1.2 to Master Branch 2.2.4

### ISSUE THREAD

**Issue by cjkupers** [digitalocean/netbox#1678]
### Issue type
[ ] Feature request 
[ X ] Bug report  
[ ] Documentation   

### Environment
* Python version:  2.7.13
* NetBox version:  2.1.2 Upgrading to v2.2.4 main branch via GIT
Ubuntu LTS 16.04

We had a couple custom fields added via Django administration, running everything as root and configured as per the documentation via GIT. Using NGINX for reverse proxying the HTTPS requests.
We also had a couple public keys for the "secrets" section, but didn't really use it.

### Description
While upgrading from 2.1.2 to latest master branch via GIT as per this documentation:
http://netbox.readthedocs.io/en/stable/installation/upgrading/ 
Starting from "Option B"

After finishing the last step of "supervisorctl restart netbox",
going to the site gives a straight "Internal Server Error"

Logs from /var/log/supervisor/netbox-stderr.....log:
https://pastebin.com/EMBkdeVc
[netbox-stderr---supervisor-K3pyDn.log](https://github.com/digitalocean/netbox/files/1435511/netbox-stderr---supervisor-K3pyDn.log)

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
