### ISSUE TITLE
IPAddress role display on device interface listing

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#1679]
### Issue type
[ x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description

It would be nice to include an IPAddress's optional role as a label on the IPAddress listing of a device interface. The specific use case came about from having multiple IPs assigned to an interface and needing to be able to identify which one was the primary preferred (in Juniper context) and which were secondary. Today we set the role of all the secondary IPs on an interface to secondary. So it would be nice to display this on the interface listing. Here is a mockup of how I think it should be:

![screenshot from 2017-11-01 16-42-21](https://user-images.githubusercontent.com/1297132/32298422-a3a6680e-bf28-11e7-931f-da519b770831.png)

**Comment by jeremystretch** [comment]
The interfaces table is cramped as it is. Need to expand it to take the full page width.
