### ISSUE TITLE
Middleware to intercept server errors related to installation issues

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1683]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.4

### Description
It may be worthwhile to implement a lightweight middleware to intercept common exceptions related to installation issues. For example, a `ProgrammingError` typically indicates that database migrations have not been applied following an upgrade. Returning hints at possible solutions to the user would help shorten the support cycle and cut down on invalid bug reports.

**Comment by lampwins** [comment]
I think you are on the right track. I have seem somewhat similar things done with https://docs.djangoproject.com/en/1.11/topics/http/middleware/#process-exception
