### ISSUE TITLE
Missing information by exporting (IP-addresse, custom fields)

### ISSUE THREAD

**Issue by hansapils** [digitalocean/netbox#1685]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3-1 
* NetBox version:  2.2.2 

### Description

The problem is, that I can create virtual machines, add interfaces and assign IP-addresses. When I export the virtual machines, the Interfaces and the IP-addresses are missing. By exporting, I am loosing these informations.

I got the same problem on custom fields, they are not exported either.

I have no idea, if this is a bug or a missing feature. Do you think, there is anything I could do about it?

**Comment by PeepOks** [comment]
One way to solve problem is using export templates. 
http://netbox.readthedocs.io/en/stable/data-model/extras/#export-templates

**Comment by jeremystretch** [comment]
The built-in CSV export functionality includes only the type of object being exported, which is sufficient for many cases. As @PeepOks pointed out, you can easily create custom export templates to extend this functionality and export objects in whatever format you like.
