### ISSUE TITLE
Custom fields to Services

### ISSUE THREAD

**Issue by 1stdemon** [digitalocean/netbox#1687]
[ ] Feature request

### Environment
Netbox v2.2.2
Python version:  3.6.3

FEATURE REQUESTS:

* Ability to add custom fields for Services. 
* 1) It can be used to set custom field Version to service and track how many Applications with same versions are installed.
   2) Or Alert template name witch can be then maped to Monitoring system allert template by custom script who will receive information from Netbox API and map it to Monitoring system

**Comment by jeremystretch** [comment]
Services are intended only to represent TCP/IP services available on a device. Additionally, NetBox does not allow for the assignment of custom fields to secondary models.

**Comment by jeremystretch** [comment]
Enabling custom fields for services now since Service now qualifies as a primary model.
