### ISSUE TITLE
Setup problems with Netbox on Apache + Debian 8 and 9

### ISSUE THREAD

**Issue by KaliszAd** [digitalocean/netbox#1688]
### Description

I get 404 Not Found after Netbox setup with Apache 2 and Debian 8 and 9 following the official documentation: https://netbox.readthedocs.io/en/stable/installation/
The test with python3 manage.py run ... works.

I had to install libapache2-mod-wsgi-py3 for Apache 2 to restart correctly with "WSGIPassAuthorization on" in the config.

This happens also on a clean Debian 9 install. What do I do wrong? How can I debug this reasonably?

### Issue type
[ ] Feature request 
[*] Bug report      
[ ] Documentation   

### Environment
* Debian 8 Jessie and Debian 9 Stretch, AMD64
* PostgreSQL 9.4 and 9.6
* Apache: 2.4.10, 2.4.25
* gunicorn
* no TLS/SSL (this is for testing)
* Python version:  3.4.2, 3.5.3 and
* NetBox version:  2.2.2
* pretty much verbatim config (changed BASE_PATH to netbox/)
* /opt children with www-data ownership

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by Kickimanjaro** [comment]
I found this thread while attempting to install NetBox on a fresh Debian 9 server. The docs still do not indicate the requirement for "libapache2-mod-wsgi-py3" on Debian (and I seeing what has been reported here) so I created an edit that would have helped me while following the installation docs.
