### ISSUE TITLE
Can't rebuild database?

### ISSUE THREAD

**Issue by jondkelley** [digitalocean/netbox#1690]
I am running netbox 2.2.2 and set things up on a VM and can't migrate this to a production database.

I run python3 manage.py migrate and get a blank database, and then ```pg_dump netbox --column-inserts --data-only > /tmp/x1.sql``` from my development server.

Importing the data on production causes errors, but no data imports. I'm concerned this app is not portable beyond the original installation?

ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(872) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(873) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(874) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(875) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(876) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(877) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(878) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(879) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(880) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"
DETAIL:  Key (id)=(881) already exists.
ERROR:  duplicate key value violates unique constraint "extras_useraction_pkey"

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
