### ISSUE TITLE
Exact match when searching for custom field

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1693]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  2.2.4

### Description

* Create a custom field:
  * Objects: dcim > rack
  * Type: Text
  * Name: test1
  * Is filterable: ✔️
* Take two racks and set the value of the custom field as follows:
  * Rack 1: `urn:bla:1`
  * Rack 2: `urn:bla:100`
* Go to the rack overview and put a `urn:bla:1` into the filter for the custom field

**Expectation:** I get one result.
**Current behaviour:** I get two results.

#### Suggestions

I suggest that all filtering on fields become exact and at the same time introducing a wildcard character for fuzzy searches, e.g. `*`.  (E.g. `urn:bla:1` would only match the one rack, whereas `urn:bla:1*` would still match both racks.)

An alternative suggestion is to add an option to the custom field's definition: Shall that field match exactly or not. (Similar to the "Is filterable" checkbox.)

Another alternative suggestion is to support the Google syntax for exact matches, i.e. everything that's wrapped in `"` must be an exact match. (E.g. `"urn:bla:1"` would only match the one rack, whereas `urn:bla:1` would still match both racks.)

**Comment by cimnine** [comment]
**Some context**

We're using custom fields to represent the IDs of our legacy system, which happen to be URNs. (These are all over the place, so we have to stick with them for a long time.) Currently, I'm writing a tool that copies any rack form the legacy system to Netbox and updates all already existing racks (until we have fully migrated). Hence I would appreciate if I could have a way to do exact-match lookups on custom fields.

**Comment by troxil** [comment]
@cimnine Isn't this how all existing filtering works? It's not exact at all. Prefixes, devices etc.

**Comment by cimnine** [comment]
Thanks for pointing this out, @troxil. I've changed it from a bug report to feature request.

**Comment by jeremystretch** [comment]
> An alternative suggestion is to add an option to the custom field's definition: Shall that field match exactly or not. (Similar to the "Is filterable" checkbox.)

This seems like a favorable approach over introducing a potentially ambiguous wildcard approach.
