### ISSUE TITLE
Allow assignment of custom fields to device roles

### ISSUE THREAD

**Issue by mf69** [digitalocean/netbox#1697]
Some of our custom fields apply only to specific device roles.
Today we cannot assign custom fields to anything more specific than devices. This ends up polluting the other devices edit and view.

**Comment by jeremystretch** [comment]
Custom fields won't be extended any time in the near future. Please see [the FAQ](https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models).

Also, please be sure to use the [rpovided template](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md) for any future issues.
