### ISSUE TITLE
Missing font package dependency for extras/topo maps feature on el7

### ISSUE THREAD

**Issue by raddessi** [digitalocean/netbox#1700]
### Issue type
[ ] Feature request 
[ X] Bug report      
[ ] Documentation   

### Environment
* Python version:  Python 3.6.2 :: Continuum Analytics, Inc.
* NetBox version:  7a64404299d7e541a2d92d32e540c48cd78e317e

### Description
I'm running netbox in a conda env on top of centos-7. Netbox itself runs fine but when using the topo maps feature it rendered images with empty boxes where characters should go on each node until the system package open-sans-fonts was installed.

[root@nope ~]$ rpm -q --requires fontpackages-filesystem
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1

[root@nope ~]$ rpm -q --whatrequires open-sans-fonts
no package requires open-sans-fonts

Conda env:
channels:
- activisiongamescience
- defaults
dependencies:
- cairo=1.12.18=6
- certifi=2016.2.28=py36_0
- font-ttf-dejavu-sans-mono=2.37=h6964260_0
- fontconfig=2.11.1=6
- freetype=2.5.5=2
- glib=2.53.6=h5d9569c_2
- graphviz=2.38.0=5
- harfbuzz=0.9.39=1
- icu=58.2=h211956c_0
- jpeg=9b=h376031c_1
- libffi=3.2.1=h4deb6c0_3
- libgcc-ng=7.2.0=h7cc24e2_2
- libiconv=1.15=h63c8f33_5
- libpng=1.6.32=hda9c8bc_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- libtiff=4.0.8=h90200ff_9
- libxml2=2.9.4=h6b072ca_5
- openssl=1.0.2l=0
- pango=1.39.0=0
- pcre=8.41=hc71a17e_0
- pip=9.0.1=py36_1
- pixman=0.32.6=0
- python=3.6.2=0
- python-graphviz=0.5.2=py36_0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- autoconf=2.69=0
- expat=2.1.1=0
- libtool=2.4.6=0
- pip:
  - asn1crypto==0.23.0
  - bcrypt==3.1.4
  - cffi==1.11.2
  - chainmap==1.0.2
  - chardet==3.0.4
  - coreapi==2.3.3
  - coreschema==0.0.4
  - cryptography==2.1.1
  - django==1.11.6
  - django-auth-ldap==1.2.16
  - django-cors-headers==2.1.0
  - django-debug-toolbar==1.8
  - django-filter==1.1.0
  - django-mptt==0.8.7
  - django-rest-swagger==2.1.2
  - django-tables2==1.13.0
  - djangorestframework==3.7.1
  - future==0.16.0
  - idna==2.6
  - itypes==1.1.0
  - jinja2==2.9.6
  - jtextfsm==0.3.1
  - junos-eznc==2.1.7
  - librouteros==1.0.4
  - lxml==4.1.0
  - markdown==2.6.9
  - markupsafe==1.0
  - napalm==1.2.0
  - napalm-base==0.25.0
  - napalm-eos==0.6.1
  - napalm-fortios==0.4.0
  - napalm-ios==0.8.1
  - napalm-iosxr==0.5.5
  - napalm-junos==0.12.0
  - napalm-nxos==0.7.0
  - napalm-panos==0.4.0
  - napalm-pluribus==0.5.1
  - napalm-ros==0.2.2
  - napalm-vyos==0.1.3
  - natsort==5.1.0
  - ncclient==0.5.3
  - netaddr==0.7.18
  - netmiko==1.4.3
  - olefile==0.44
  - openapi-codec==1.3.2
  - pan-python==0.12.0
  - paramiko==2.3.1
  - pillow==4.3.0
  - psycopg2==2.7.3.1
  - py-gfm==0.1.3
  - pyasn1==0.3.7
  - pycparser==2.18
  - pycryptodome==3.4.7
  - pyeapi==0.8.1
  - pyfg==0.50
  - pyiosxr==0.52
  - pyldap==2.4.37
  - pynacl==1.1.2
  - pynxos==0.0.3
  - pypluribus==0.3.1
  - pyserial==3.4
  - pytz==2017.2
  - pyyaml==3.12
  - requests==2.18.4
  - requests-toolbelt==0.8.0
  - scp==0.10.2
  - simplejson==3.11.1
  - six==1.11.0
  - sqlparse==0.2.4
  - uritemplate==3.0.0
  - urllib3==1.22
  - uwsgi==2.0.15
  - vyattaconfparser==0.5.1
  - xmltodict==0.11.0

**Comment by jeremystretch** [comment]
Looks like a dependency issue with the upstream graphviz package. I don't think it's our place to assume what graphviz will or won't need.
