### ISSUE TITLE
Tenant Inheritance

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#1707]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description

Would it be possible to add a tenant inheritance to anything added from the GUI once you are in a site?

If Site A is assigned to Tenant A then when I create a rack, that rack would the tenant info already setup.

Same within a rack, when adding a device.

I saw a previous request and it appear that the prefill/autopopulate piece was left out when it was tied to another request.

**Comment by jeremystretch** [comment]
The current UI doesn't allow for this without an unreasonable amount of development effort to enable API-driven forms. It's a good candidate for a future version where we've (at some point) moved to an API-driven UI powered by Angular/React/Ember/whatever, but that's still a ways off. For now, the best we can do is pre-populate initial data in a form using URL parameters (e.g. `/dcim/racks/add/?tenant=123`), but that's only possible when working from an established context (for example, creating an IP address from within a parent prefix).
