### ISSUE TITLE
Arista EAPI RPC Support

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#171]
Add Arista to the RPC support.

For testing purposes, Arista allows for virtualized instances of their EOS platform. https://eos.arista.com/tag/veos/

**Comment by laetrid** [comment]
I can help with Arista. 
What kind of integration with netbox?

**Comment by dinoocch** [comment]
Instead of writing new functionality for this, it may be more desirable to use a package like [netmiko](https://github.com/ktbyers/netmiko) instead of [paramiko](https://github.com/paramiko/paramiko), which will abstract out a lot of the logic that is built into the current RPC.

**Comment by jgill-arista** [comment]
netmiko is really nice for setting up the session and getting output, however using EAPI has an advantage in that almost all the responses are already parsed into JSON for easy digestion.

I am not familiar with netbox(yet) and what RPC calls are made where, but I can provide some assistance/testing if it helps.  I have vEOS and hardware switches to test.

Tip: you can see this jsonified output from the CLI by piping to ` | json`
```
co301...07:06:21#show version | json
{
    "modelName": "DCS-7150S-64-CL-R",
    "internalVersion": "4.16.6M-3205780.4166M",
    "systemMacAddress": "00:1c:73:xx:xx:xx",
    "serialNumber": "CCCNNNNNNNN",
    "memTotal": 3978148,
    "bootupTimestamp": 1467148049.71,
    "memFree": 1937212,
    "version": "4.16.6M",
    "architecture": "i386",
    "isIntlVersion": false,
    "internalBuildId": "373dbd3c-60a7-4736-8d9e-bf5e7d207689",
    "hardwareRevision": "01.03"
}
```

**Comment by laetrid** [comment]
Agree with jgill-arista, you can easily request data via JSON RPC from Arista, for example:
 ```
  from jsonrpclib import Server

   switch = Server( "https://username:passw0rd@myswitch/command-api" )
   response = switch.runCmds( 1, ["show version"] )
```
and get response in JSON.
As I understand netmiko is a nice tool for legacy devices that do not support structured output.

**Comment by dinoocch** [comment]
@jgill-arista I completely agree, the eapi is much nicer for many reasons! (I'm honestly disappointed that netmiko doesn't have the option to tie into api's, but I suppose it's beyond the scope of their project).  The advantage of netmiko is support for many different devices and vendors beyond what netbox wants to/can include on it's own. Vendor specific solutions like pyeapi may work much better, but depending on the functionality we're looking for, it may not make a difference...

**Comment by jeremystretch** [comment]
Closing this out because we're going to be removing built-in RPC support in version 2.0, in favor of API-driven population via external tools.
