### ISSUE TITLE
Unable to link IP to device interface.

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1710]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  <2.2.5>

### Description
Referring to issue #1512 which was closed, this is still a problem.

When an existing IP Address which is not bound to a interface is edited, you are still not able to select the site/device/interface to link it to an interface.

![image](https://user-images.githubusercontent.com/16985649/32823220-f706e2c8-c9e4-11e7-91f8-bfc7ce0a2b79.png)

**Comment by jeremystretch** [comment]
This is done by navigating to the parent device and clicking the button to add an IP to the desired interface. Click the "Assign IP" tab and search for the IP. This approach was chosen because it is much simpler than trying to select a device or VM and interface from within the IP address form.

**Comment by InsaneSplash** [comment]
Thanks for the pointer! 

I do feel though that one should also be able to link in the other direction. 

If one has navigated to the IP Address which needs to be linked to a device, one has to open a new tab and tackle it from the other direction which makes it a little less efficient.

Just something to consider.....
