### ISSUE TITLE
IP Address Inheriance not working properly

### ISSUE THREAD

**Issue by Zimeon-** [digitalocean/netbox#1712]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  Python 2.7.5
* NetBox version:  NetBox (v2.2.4)

### Description
Related to issue https://github.com/digitalocean/netbox/issues/1548 that was closed. The URL does contain tenant values, but they are not populated on page. Could be due to multiple tenant groups perhaps (just a wild guess).

Url is as following;
?address=10.10.10.0/24&vrf=1&tenant=2

**Comment by jeremystretch** [comment]
Please describes the steps you're taking to create this bug, and what is happening versus what you expected to happen.

**Comment by Zimeon-** [comment]
When clicking on "Add an IP-Address" from a prefix view, expected behaviour would be that the tenant value to be pre-filled using the prefix tenant value like vrf. At the moment the tenant is at the default, none "-------".

**Comment by jeremystretch** [comment]
This seems to happen only when the assigned tenant is assigned to a group.

**Comment by jeremystretch** [comment]
Fixed in 252be84bf07a27868c9e5548558834b2fd62e3d8

**Comment by andreasfreitag** [comment]
Hi Jeremy, thanks for fixing it with "Add an IP Address". But it has the same behavior when you add a IP Address direct from the IP Addresses List -> "xx IPs aivailable" (no tenant_group ID in the URL)... Thanks for all your work.
