### ISSUE TITLE
Slug for Virtualisation Clusters

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1713]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4
* NetBox version:  2.2.5

### Description

It would be nice to have the 'slug' field for virtualisation clusters as well, like it's already available on regions and sites.

**Comment by jeremystretch** [comment]
I can imagine cases where some people want slugs for clusters and some don't. Leaving this open for feedback.

**Comment by jeremystretch** [comment]
Six months later and zero feedback. Gonna have to close this out.
