### ISSUE TITLE
Enable CSV export for organizational objects (device roles, VLAN groups, etc.)

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1714]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4
* NetBox version:  2.2.5

### Description

It'd be nice to export/import _device roles_ the same way as _device types_.

**Comment by jeremystretch** [comment]
Support for CSV import of device roles was introduced in NetBox v2.2.0. Device roles can be exported via the API; I don't think there's much value in adding CSV export for them.

**Comment by cimnine** [comment]
I'd use it to be able to easily migrate them between staging/production.

On another note, the CSV import button is only present in the menu, but not on the `/dcim/device-roles/` page. That's why I didn't even realise there's the option for CSV import.

**Comment by esajo** [comment]
To migrate between servers easiest would be to just dump and restore the database instead of one by one export and import. But that's of course only the way I see it.

**Comment by jeremystretch** [comment]
> I'd use it for migrating easily between staging/production.

**Comment by jeremystretch** [comment]
> I'd use it for migrating easily between staging/production.

Just so I understand, are you running separate instances of NetBox for staging and production? Or what do you mean?

> On another note, the CSV import button is only present in the menu, but not on the /dcim/device-roles/ page.

Yeah we should add those. I'll open a separate bug for that.

**Comment by cimnine** [comment]
@esajo I don't want to overwrite any data that is already in production.

> Just so I understand, are you running separate instances of NetBox for staging and production? Or what do you mean?

Yes. Two instances. Plus devs usually spin up a local Docker-based instance for developing integrations.

**Comment by bdlamprecht** [comment]
I'd like to see this feature as well.

I'm doing the same thing as @cimnine is, my development boxes are based off of docker, which get thrown away frequently, so allowing a mass export would be very beneficial instead.

I was able to use the API to export the `device_roles` from my dev box and use an online `JSON to CSV` converter in the interim until this is implemented.

**Comment by jeremystretch** [comment]
So, this FR is really more for CSV-based export of _all_ organizational objects, not just device roles, right?

**Comment by cimnine** [comment]
Thanks!

**Comment by jeremystretch** [comment]
Did a lot of cleanup around CSV import/export. Still want to add some tests specifically for it.
