### ISSUE TITLE
Global VLAN Groups not available when Site is chosen

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1716]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4
* NetBox version:  2.2.5

### Description

* Preconditions: At least on existing site.
* Create a VLAN group, but don't assign it to a site.
* Create a VLAN:
  * Select any site
  * Try to select one of those 'global' vlan groups -> Their not listed.

My expectation was that VLAN groups, which don't belong to a site, are not dependant on the site assignment of the VLAN.

(PS: If I don't choose a site, all 'global' _VLAN Groups_ are certainly available.)

**Comment by jeremystretch** [comment]
A global VLAN group is intended to hold only global VLANs; that is, VLANs which are not assigned to sites. Groups are used to organize VLANs within their domain (either globally or within a site).
