### ISSUE TITLE
IP Interface Assignment Missing Global VRF

### ISSUE THREAD

**Issue by DirtyCajunRice** [digitalocean/netbox#1718]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version: 2.2.5

### Description
When assigning an IP address to an interface with the newly fixed IP mapping tab, you are unable to assign any public IPs directly to the firewall that are not assigned to a created VRF. As most public IPs are not assigned to a VRF as they are Global and unique, this means we still need to do the workaround for directly assigned public IPs. 

## Fix
To add the Global VRF as searchable option

**Comment by candlerb** [comment]
I only use the global VRF, and on testing it works fine for me; the "Assign IP" tab shows `VRF: --------` (implying global VRF)

I also tried creating a new VRF. Then the "Assign IP" tab has two options in VRF dropdown (`--------` plus the new VRF I created).  And it still works for me: with `--------` selected I can find IPs in the global VRF.

Can you explain how to replicate the problem?  Or is it just a question of changing the label `--------` to `Global` for clarity?

**Comment by jeremystretch** [comment]
As @candlerb said I think this is just a cosmetic issue where we're not labeling the "null VRF" as global. We definitely want to be consistent with the labeling though.
