### ISSUE TITLE
Import Failure Handling

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#172]
I am testing much of the functionality here and I noticed that if I import records using the csv format, the tool fails on the whole import.

Would it be useful for it to succeed on what it can and report out status of failed (with the current error details) vs successful entries?

**Comment by jeremystretch** [comment]
CSV import is intentionally all-or-none. Imagine you're importing a hundred interface connections. NetBox gets halfway through and finds an error. If it didn't roll back the transaction, you'd be stuck with half of your connections created and the other half still missing. This would require you to delete all of the successfully imported connections before attempting another import.

It's a lot simpler IMO to just fix the error and try re-importing the whole batch again, especially when you're exporting to CSV from Google Sheets or Excel.

**Comment by ryanmerolle** [comment]
Thanks for the insight into your thought process!
