### ISSUE TITLE
Include VM statistics in the site list

### ISSUE THREAD

**Issue by cantek86** [digitalocean/netbox#1722]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  v3.6.3
* NetBox version:  v2.2.4

### Description

Would like to see the VMs that are created on the hosts for a site visible at the site level. This would make visibility greater from a top down view as to what is located or hosted at each site. Basically just adding in the a VM number and link in the site under the stats dashboard section.

It would be useful for those that use vms as production servers and would like the visibility at the site level, instead of having to go through the vm section to get the vm details.

**Comment by jeremystretch** [comment]
A virtual machine isn't tied directly to a site. A VM is tied to a cluster, which in turn _may_ be assigned to a site. We can include a count of all VMs which belong to a cluster assigned to each site, but this will not include VMs belonging to clusters which have no site assignment.

**Comment by cantek86** [comment]
Yes. This makes complete sense and would make visibility of resources much easier. Thank you.

**Comment by cantek86** [comment]
could this be reopened and added to. The addition is great but could you propagate the information in the stats area of the site with the VM number as well.
