### ISSUE TITLE
Option to deploy Netbox on Minikube or Kubernetes cluster 

### ISSUE THREAD

**Issue by vishnoisuresh** [digitalocean/netbox#1723]
### Issue type
deploying netbox on Minikube or K8s cluster 
### Description
Hi guys,
I am exploring Kubernetes by trying to deploy **Netbox** on minikube. 
I have tried to write kubernetes manifest resources for **Netbox**.  These manifests will enable us to deploy netbox on Minikube. 

These manifest files can probably be improved. I think a lot of people are trying to learn and explore kubernetes therefore, This could be a good start.

[Netbox-Kubernetes](https://github.com/vishnoisuresh/netbox-kubernetes)
Let me know what you think!
Thanks

**Comment by jeremystretch** [comment]
Hi! We try to limit GitHub issues to feature requests and bugs, but please post this to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) where more people are likely to see it.

**Comment by MihaiAnei** [comment]
It would also be nice to have a Helm package for it :)

I'll be working on this on my k8s cluster, hopefully I will have time to make a pull request.

**Comment by gun1x** [comment]
There is a very good fork to this Kubernetes project: https://github.com/dustnic/netbox-kubernetes
Having this in the official documentation would help a lot.
