### ISSUE TITLE
A comments field for VLAN's

### ISSUE THREAD

**Issue by Freksen** [digitalocean/netbox#1724]
As it would be nice to be able to document more concerning a VLAN 
Eg. contact person, ACL's

So a field supporting larger amounts of text would be great

**Comment by zelfix** [comment]
You can configure  a "Custom Field" option in the Django administration mode.

**Comment by Freksen** [comment]
Yes, but it has a maximum of 255 characters. Too little if you want to document eg. ACL's

**Comment by jeremystretch** [comment]
The VLAN model already includes a description field to hold a reasonable amount of free-form data. NetBox doesn't support modeling access lists.
