### ISSUE TITLE
Interface Position

### ISSUE THREAD

**Issue by exabyte4** [digitalocean/netbox#1726]
Hi,

I'm not sure I would call this is "an issue", so please forgive me if this is wrong place to post this.
Ever since the upgrade (I'm using the latest version, 2.2.6), the interface list on each device is showing on the bottom of the page. 
To me, this is tedious as this section is the most important (and awesome) feature.
Is there any way to rearrange the layout in a device?
I think it would make an excellent feature with regards to customization and flexibility.

Please let me know if I can move the interface pane to a higher position on the page.

Thanks.

**Comment by jeremystretch** [comment]
The interface list was moved down to provide sufficient horizontal space to include more detail in the table (description, MAC address, etc.). We could maybe move some of the other panels (e.g. images and related devices below it), but there's not enough room to squeeze anything next to it.
