### ISSUE TITLE
M2M_FIELD_TYPES undefined error with Netbox 2.3-develop

### ISSUE THREAD

**Issue by madkiss** [digitalocean/netbox#1727]
[x] Bug report

### Environment
* Python version:  2.7.5
* NetBox version:  2.3-develop

### Description

We tried running develop-2.3 as we have use for the VLAN features added lately (not in production, so no worries). This seems to work great in general. We tried to add a VLAN interface to a machine, type "Other", on top of a bonding interface. When clicking the submit button, we see:

<class 'NameError'>
name 'M2M_FIELD_TYPES' is not defined

The interface is created nevertheless; but I am not sure if the correct entries are added to the database and also the error message should not appear.

**Comment by madkiss** [comment]
I can confirm that the created VLAN entry is incorrect. It doesn't have any VLAN information attached to it.

**Comment by madkiss** [comment]
I can also confirm that after creating the VLAN interface and seeind the error message, if I open the interface again and manually change the VLAN settings, it works and the proper VLAN is registered with the interface.

**Comment by jeremystretch** [comment]
Fixed in 859f891
