### ISSUE TITLE
Site Landlord

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#173]
I would have suggested a vendor type and used it to specify device manufacturers, circuit carriers, and site landlords.  Given you used individual entities for those types, I would recommend a Landlord type to consolidate contact details, show contracts & number of sites managed, etc.  It would then allow for the Facility field just reference the Landlord's site code/reference instead.

**Comment by rekeds** [comment]
yeah, this would be great outside the DC, like building landlords :>
contact info, etc.

**Comment by peelman** [comment]
Another one of those times where abstraction should be considered.

`Company` is the desirable entity, with Manufacturers, Landlords, Vendors/Resellers, etc. all being subsets of that.  Each Company can have multiple `Points of Contact`, which can be account execs, support contacts, technical contacts, facilities contacts (in terms of landlords that are data centers).

Abstract in the beginning, or duplicate effort later.

**Comment by jeremystretch** [comment]
#756 added simple contact details (name, phone, and email) to the Site model. I think that's a good place to set the perimeter of NetBox as it concerns administrative contacts.

In the case a user needs to track multiple sites belonging to a common landlord, it might be appropriate to define a custom field to track the assignment, and store the desired landlord data (which will vary a lot among use cases) elsewhere.
