### ISSUE TITLE
Update information on already registered devices

### ISSUE THREAD

**Issue by jjangmoo** [digitalocean/netbox#1730]
Hi, 
I have used Netbox v2.2.2.

I would like to update information such as tenant or platform. 
When I tried to use the import function, I found error messages because of the duplicated device name.
![image](https://user-images.githubusercontent.com/4304132/33128348-729dc0ec-cfcf-11e7-8cb8-399a2d08a035.png)

If I want to update information on multiple devices, what do you think I should do?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
