### ISSUE TITLE
DCIM>Interface Connection Export Template - Form Factor Label Blank

### ISSUE THREAD

**Issue by nathbooth** [digitalocean/netbox#1731]
When creating an export template for Interface connections, if you include the form factor label as per the API call reference interface_a.form_factor.label there is no output returned, example export template below

{% for connection in queryset %}
{{connection.interface_a.device|addslashes}},{{connection.interface_a.name|addslashes}},{{connection.interface_a.form_factor.label|addslashes}},{{connection.interface_b.device.name|addslashes}},{{connection.interface_b.name|addslashes}},{{connection.interface_b.form_factor.label|addslashes}}
{% endfor %}

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
