### ISSUE TITLE
Cannot update information using import feature

### ISSUE THREAD

**Issue by jjangmoo** [digitalocean/netbox#1732]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.2

### Description
I would like to update information such as platform, tenant or position at one time. 
It means I would like to use the import function when I update data. 

I think this import function is only working when I want to import new devices. 
But I need to update this information on multiple devices. 

What do you think about adding a flag field like import_role(value = new or update) in import format?

**Comment by esajo** [comment]
Optimally, after an initial import, you would use the API to import new devices. But I do agree that having an ignore existing option while doing csv import would be great.

**Comment by jeremystretch** [comment]
CSV import does not allow for modifying existing objects. NetBox provides a separate "bulk update" mechanism for most objects, or you can use the API as @esajo suggested.
