### ISSUE TITLE
After upgrading from 2.1.6 to 2.2.6 most pages give an error about nulls

### ISSUE THREAD

**Issue by Gunni** [digitalocean/netbox#1736]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.5
* NetBox version:  2.2.6
* PostgreSQL version: 10.1

### Description
After taking my Netbox instance and upgrading it and posgres from:

* PostgreSQL: 9.2 to 10.1
* Netbox: 2.1.5 to 2.2.6

Now most pages give this error:

![gg-1511813728](https://user-images.githubusercontent.com/358099/33287172-b9acd5ac-d3af-11e7-837c-4f8438c14559.png)

Not all pages give the error but i have not found anything in common with them.

List of broken pages from the front page:

* /dcim/devices/
* /ipam/prefixes/
* /ipam/ip-addresses/
* /ipam/vlans/

Traceback follows:

	Environment:

	Request Method: GET
	Request URL: https://x/ipam/vlans/

	Django Version: 1.11.5
	Python Version: 3.4.5
	Installed Applications:
	('django.contrib.admin',
	 'django.contrib.auth',
	 'django.contrib.contenttypes',
	 'django.contrib.sessions',
	 'django.contrib.messages',
	 'django.contrib.staticfiles',
	 'django.contrib.humanize',
	 'corsheaders',
	 'debug_toolbar',
	 'django_filters',
	 'django_tables2',
	 'mptt',
	 'rest_framework',
	 'rest_framework_swagger',
	 'circuits',
	 'dcim',
	 'ipam',
	 'extras',
	 'secrets',
	 'tenancy',
	 'users',
	 'utilities',
	 'virtualization')
	Installed Middleware:
	('debug_toolbar.middleware.DebugToolbarMiddleware',
	 'corsheaders.middleware.CorsMiddleware',
	 'django.contrib.sessions.middleware.SessionMiddleware',
	 'django.middleware.common.CommonMiddleware',
	 'django.middleware.csrf.CsrfViewMiddleware',
	 'django.contrib.auth.middleware.AuthenticationMiddleware',
	 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	 'django.contrib.messages.middleware.MessageMiddleware',
	 'django.middleware.clickjacking.XFrameOptionsMiddleware',
	 'django.middleware.security.SecurityMiddleware',
	 'utilities.middleware.ExceptionHandlingMiddleware',
	 'utilities.middleware.LoginRequiredMiddleware',
	 'utilities.middleware.APIVersionMiddleware')

	Traceback:

	File "/usr/lib/python3.4/site-packages/django/core/handlers/exception.py" in inner
	  41.             response = get_response(request)

	File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
	  187.                 response = self.process_exception_by_middleware(e, request)

	File "/usr/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
	  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

	File "/usr/lib/python3.4/site-packages/django/views/generic/base.py" in view
	  68.             return self.dispatch(request, *args, **kwargs)

	File "/usr/lib/python3.4/site-packages/django/views/generic/base.py" in dispatch
	  88.         return handler(request, *args, **kwargs)

	File "/opt/netbox-2.2.6/netbox/utilities/views.py" in get
	  85.             self.queryset = self.filter(request.GET, self.queryset).qs

	File "/usr/lib/python3.4/site-packages/django_filters/filterset.py" in qs
	  200.             if not self.form.is_valid():

	File "/usr/lib/python3.4/site-packages/django_filters/filterset.py" in form
	  225.                 for name, filter_ in six.iteritems(self.filters)])

	File "/usr/lib/python3.4/site-packages/django_filters/filterset.py" in <listcomp>
	  225.                 for name, filter_ in six.iteritems(self.filters)])

	File "/usr/lib/python3.4/site-packages/django_filters/filters.py" in field
	  159.                                                **field_kwargs)

	File "/usr/lib/python3.4/site-packages/django/forms/fields.py" in __init__
	  782.             help_text=help_text, *args, **kwargs

	Exception Type: TypeError at /ipam/vlans/
	Exception Value: __init__() got an unexpected keyword argument 'null_value'

**Comment by jeremystretch** [comment]
Looks like you need to upgrade `django-filter` to v1.1.0 or greater. If you continue to experience issues after doing so, please post to the mailing list.

**Comment by Gunni** [comment]
You were right, my bad not upgrading using pip3 first.

**Comment by loganbest** [comment]
@jeremystretch I've got this same exact issue and I do have django-filter (1.1.0) installed. Though I'm still on py2.7 since supervisorctl doesn't fully support py3 yet.
