### ISSUE TITLE
An ability to get a parent prefix from an ip address using API

### ISSUE THREAD

**Issue by zelfix** [digitalocean/netbox#1737]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.4.5
* NetBox version: 2.2.6

### Description
It is a continuation of NetBox-discussion https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/netbox-discuss/t7J_LL2jMcM/dOvZVqEYAQAJ
Would like to get the closest parent prefix for an IP address using API.

It would be useful for those that use a netbox with external tools. For example, I want to add a list of ip addresses to netbox from a core switch's arp table using API. For each ip address I must set a prefix length. If I could get a parent prefix using API than I could get a prefix length for this IP address.

**Comment by Gunni** [comment]
If you have the ip with mask on CIDR form, just do the following request:

    /api/ipam/prefixes/?parent=10.0.0.1%2F24

In my test it returns the parent prefix of 10.0.0.0/24.

**Comment by zelfix** [comment]
Yep, If I have the ip with mask, i can calculate the prefix and get it using API
But If I don't know a mask, I have to do something like this:
```
def get_prefix_length_for_ip(ip_address):
    for prefix_length in range(31, 0, -1):
        resp = requests.get(apiBaseUrl + '/ipam/prefixes/?parent=' + ip_address + '/' + str(prefix_length),
                            headers=headers).json()
        if resp['count'] > 0:
            return str(prefix_length)
    return None
```
This code gives a big load to the Netbox database that's why the function is executing slowly.

**Comment by Gunni** [comment]
> Just noticed that you said you didn't have the prefix length. But you do if you have ARP then you have a layer 3 interface and that interface has a mask set, right?

**Comment by icanhazpython** [comment]
> If you have the ip with mask on CIDR form, just do the following request:
> 
> ```
> /api/ipam/prefixes/?parent=10.0.0.1%2F24
> ```
> 
> In my test it returns the parent prefix of 10.0.0.0/24.
> 
> Edit: Just noticed that you said you didn't have the prefix length. But you do, if you have ARP then you have a layer 3 interface and that interface has a mask set, right?

It appears that this is incorrect.
For those looking for this feature, the query param is actually "?contains=".
