### ISSUE TITLE
Enable custom fields for secrets

### ISSUE THREAD

**Issue by evantheenginr** [digitalocean/netbox#1739]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.5
* NetBox version:  2.2.6

Many of our secrets involve the use of additional information in order to authenticate with a device or service on a device.  This is non-sensitive information related  to the secret.  It might be a connection endpoint for a service such as https://host:port/service or a information about a 2FA mechanism.  In extreme cases we may make notes about use or purpose of access related to a secret.  

We envision this could be accomplished any number of ways, the most flexible of which would be custom fields for secrets.  The addition of 2 fields, one for connection information and one for connection notes would help.

**Comment by jeremystretch** [comment]
The secret model is intended solely to hold sensitive data. Services and other ancillary data should be modeled elsewhere (in fact, there is a service model specifically for this). Could you explain exactly what it is you're trying to do?

**Comment by evantheenginr** [comment]
There are commonly other pieces of information hat are required in order to use a secret.  Specific examples follow:

1. Multiple instances of software such as MS SQL Server installed on a single device with different SQL user’s in each instance.  We have no way to document which secrets on the device tie to which instances of SQL server on that same device in netbox.

2. In 2FA scenarios, it is handy to know what apparatus, phone number, email address, etc is to be used to acquire the secondary authentication information.

3. Some secrets are only valid in certain scenarios on a device — for example against certain services.  For example a root account password might be accepted via console but not via SSH.  It would be handy to document this in some way — custom fields would go a long way on secrets.

**Comment by jeremystretch** [comment]
Enabled custom fields for secrets in 0c0799f for the v2.4 release.
