### ISSUE TITLE
Filter providers by site

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#174]
Each section seems to have inconsistent table views from a filtering perspective.  Some sections allow for filters, some do not.  I would recommend filter view be setup for every section.

**Comment by jeremystretch** [comment]
Each type of object has its own filters. Are there any specific filters you'd like to see added?

**Comment by ryanmerolle** [comment]
I think you could Manufacturer filter to Devices page.

If Manufacturers get linked to a platform, filtering by Manufacturer would be good on the Platform page.

When Regions get added to site, filter nearly everything you can filter by Site, but by Region would be helpful for larger shops. Filter Sites by Region.

Filter IP addresses by Aggregate and/or Prefix (optional given this adds UI complexity/clutter, minimizes user clicks, adds more flexibility for interacting with the system)

Filter Providers by Sites and Regions to show details about relationships and connectivity.

Its not a lot, and thinking about it now, I am sure this will mostly come naturally over the course of the next few releases.  Anything that doesn't is probably so unimportant.

**Comment by jeremystretch** [comment]
> I think you could Manufacturer filter to Devices page.

We have the device type filter, which includes manufacturer; you can select multiple types belonging to one manufacturer. Adding an additional manufacturer filter might be confusing.

> Filter IP addresses by Aggregate and/or Prefix

We have this ability using the "search within" field (optionally in combination with the VRF filter), it's just not prepopulated. Prepopulating all prefixes in a filter list probably isn't practical. We could filter by aggregate, but it might make more sense to add an "IP addresses" tab to the aggregate view instead (like we have on the prefix view).

> Filter Providers by Sites

Interesting, I like this idea. Will have to think about how to implement the filter.

**Comment by ryanmerolle** [comment]
I got confused by some of the terms.  I confused device type (I was think device model) with role type.  I withdraw my Manufacturer filter for devices.  Some people may not want to select every HP device type, but I agree with you, it could get confusing.

Other DCIM tools pre-populate these filters, but I agree not efficient.

I can rename this request if you like and just call it filter providers by sites to get a report of according relationships and inventory in a site or region(when you add it).
