### ISSUE TITLE
A secret can't have Unicode characters

### ISSUE THREAD

**Issue by Tangeek42** [digitalocean/netbox#1741]
### Issue type
[    ] Feature request 
[ X ] Bug report      
[    ] Documentation   

* Python version: 3.4.2
* NetBox version:  2.2.6

### Description

I've been experiencing some issues regarding secrets that contain any Unicode character. Or, as far as I can tell, any non-ASCII character. I can enter secrets that have 256 characters (or more, didn't try further than that :D ) without any issue if they have only ASCII characters. But, if there is one UTF-8 character, it all comes crashing down.

* ) I enter a new secret
* ) The secret can have a Unicode name, that's not an issue.
* ) The value of the secret contains only this : é. One character not in the ASCII table.
* ) The saving goes well.
* ) But when I try to unlock that secret, I get this response in a JS window.
![2017-11-29-114146_1033x161_scrot](https://user-images.githubusercontent.com/11335279/33371276-78484cda-d4fa-11e7-8810-dbc66ddb4cbf.png)

Now, I like my passwords to be like ×Uuë}kB.ßdClU@'´8OÏ(dú>o¿ä6G>1'-6, so I'm kind of disappointed right now. ^^ 

Anyway, have a good day. Keep up the good work, NetBox is an awesome tool and we're glad to have found out about it. :-)

**Comment by jeremystretch** [comment]
Should be fixed now; tested on both Python 2 and 3. Please comment here if you run into any further issues and I'll reopen this.
