### ISSUE TITLE
Tie options for 'platform' together with 'manufacturer' for new devices

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1744]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* NetBox version:  2.2.6

### Description
Per the discussion on the Slack `networktocode` channel on 29Nov2017:
>bdlamprecht [10:15 AM] 
Question...
I'm wondering if it would be possible to tie together the options for `platform` with `manufacturer` so that when creating a new device, only the applicable options would display?
For example, if the `manufacturer` was Cisco, only `Cisco IOS`, `Cisco NXOS`, `Cisco IOS-XR`, etc would be available and not `Juniper Junos`.
Understandably, this wouldn't be applicable to everything, but I _could_ see it being useful in some cases.

>jstretch [2:06 PM] 
eh, it works for network gear, but not so much for general purpose servers (e.g. Linux on Dell vs HP)
might be worth making it an optional association though

>bdlamprecht [2:10 PM] 
Yeah, didn't know how hard it would be
You want me to open a FR?

>jstretch [2:21 PM] 
sure

Any further discussion is welcome.

**Comment by jeremystretch** [comment]
Implemented in 9984238

**Comment by jennec** [comment]
I noticed a behavioral issue for this.

When your hardware manufacturer is different from your Operating System Manufacturer you are now not able to select the correct Platform for the physical hardware.  For example, a Server manufactured by Dell will not be able to select a Platform manufactured by VMWare (I know Dell own VMWare but that's not the point).  

I know I can dissociate the Platform from a Manufacturer and it will then appear, but this is untidy and can skew the result if you want to perform a report on how Many VMWare products are in use on a Site or for a Tenant.  

I'd appreciate it if could look into changing the Device template to allow selection of a Manufacturer for the OS which can be independent from the Hardware manufacturer.  This would then avoid the issue above whilst keeping the OP's request.  (I appreciate that this might not be as simple as it sounds)
