### ISSUE TITLE
VLAN Groups enhancement - VLAN list for specific device

### ISSUE THREAD

**Issue by vsvetlov** [digitalocean/netbox#1745]
Issue type

[X] Feature request 

Environment

Python version: 3.4
NetBox version: 2.2.5

Description

Sorry if it duplicates.
I would like to suggest to extend VLAN Groups use case to calculate a vlan list for particular device.

For example we have a group of the Access switches and every Access switch should have VLANs created with IDs: 10,20,30 (Vlan group A). Every Distribution switch should have VLANs: 210,220,230 (Vlan group D). And both the Access and Distribution switches should have some transit VLANs: 501,502,503 (Vlan group T).
It would be nice to have ability to link a device or group of devices to a Vlan group or several Vlan groups. In our example we need to associate all the Access switches with the Vlan groups A and T.
The use case is calculating list of VLANs for specific devices and it is pretty convenient to see a list of devices that is covered by specific VLAN group. Also it does not affect somehow main VLAN group functionality.
If it is too complex just close it ;)

Thank you!

**Comment by jeremystretch** [comment]
NetBox doesn't assign VLANs to devices. Rather, VLANs are associated with individual interfaces (coming in v2.3.0; see #150) and can be tagged or untagged. VLAN groups allow VLANs to be organized so that they are easier to manage, but there is no mechanism to assign VLANs to devices.
