### ISSUE TITLE
F5 load balancer with 8 nodes = 8 x duplicate information issue.

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1749]
Issue type

[x] Feature request
[ ] Bug report
[ ] Documentation

Environment

Python version:
NetBox version: 2.2.6

Description:

I have asked support for device clusters (#1674) but poorly explained the reason. I'm not talking about virtualized devices (VM) or stacks ((Cisco), I'm talking about load balancers (F5). We are using load balancers (F5), and one cluster can contain max 8 devices in a sync-failover device group. So every device has own uniq management and self IP but includes all same networks, vlan -s, virtual IP -s. Now when I add same service IP to multiple device, I get duplicate IP warning: 

IP Addresses 10.199.10.229/24 

 Duplicate IP Addresses
IP Address 	VRF 	Status 	Role 	Tenant 	Parent 	Interface 	Description
10.199.10.229/24 	Global 	Active 	VIP 	— 	FRLB08 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	FRLB07 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	FRLB06 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	FRLB05 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	FRLB04 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	FRLB03 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	FRLB02 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	FRLB01 	Trunk 	test-service

Also in IP addresses list I have duplicate IP -s:

Devices
	Name 	Status 	Tenant 	Site 	Rack 	Role 	Type 	IP Address
10.199.10.229/24 	Global 	Active 	VIP 	— 	— 	FRLB01 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	— 	FRLB02 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	— 	FRLB03 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	— 	FRLB04 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	— 	FRLB05 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	— 	FRLB06 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	— 	FRLB07 	Trunk 	test-service
10.199.10.229/24 	Global 	Active 	VIP 	— 	— 	FRLB08 	Trunk 	test-service

And this is only one example for one 8 node F5 HA cluster and one service. We have a lot multiple node clusters and every one contains hundreds of services. And having such duplicate data in view mode is disturbing and messing up the whole picture.

So please explain how should we handle this kind situations with Netbox? So that Netbox is still the ultimate source of truth and have real configuration elements but in same time IPAM doesn't contain duplicate IP objects? Can You suggest some way? Can You add some kind special HA device group, which is not visible in device view, but contains all HA members and does not warn on duplicate IP -s etc.

**Comment by oysteingy** [comment]
Have you looked into Netbox's support for anycast IP?

**Comment by jeremystretch** [comment]
As @oysteingy suggested, setting the IPs to a status of "anycast" will remove the duplicate warnings.

> Also in IP addresses list I have duplicate IPs:

NetBox will return a separate representation for each instance of the IP address defined.

I'm going to close out this issue but please feel free to raise the discussion on the mailing list if you're still not satisfied.
