### ISSUE TITLE
Docker+Netbox on Debian

### ISSUE THREAD

**Issue by madbutterflies** [digitalocean/netbox#1752]
Im working with Debian 8.0 on a virtual machine. Is there a way for me to install Netbox without using an image, which come with a limited functionality?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
