### ISSUE TITLE
Site Archive / Decommissioning Feature

### ISSUE THREAD

**Issue by rsaturns** [digitalocean/netbox#1758]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description
Provide the ability to mark a site and all associated attributes as "Archived / Decommissioned / Inactive".

**Rational:**
There might be a period wherein a location is no longer needed. However, you might want to track information about it for a period of time after it is decommissioned. For example, ensuring circuits are turned down, equipment is returned etc. It would be nice to have a way to denote the site is no longer around / active thereby excluding it from searches and providing visual acuity (Green check / red X / status field etc.) when looking at all listed sites / equipment / subnets / circuits.

**Proposal:**
At the site level, provide a default status of Active when a site is added. However, there could be a drop down or checkbox when editing the site would allow you to mark it and all child objects associated with it inactive. Until such time you then decide to delete it.

**Comment by rsaturns** [comment]
I would agree with @lampwins in the context of providing some visibility say in the bread crumbs. Also, I think the ability just to filter sites on their status would satisfy the requirement. So far most people tend to navigate from Site > (desired object) not the other way. So if they browse into an inactive site they should quickly know what's going on.

Thanks.

**Comment by jeremystretch** [comment]
Implemented in ed10a99
