### ISSUE TITLE
Custom fields for Services.

### ISSUE THREAD

**Issue by 1stdemon** [digitalocean/netbox#1762]
Issue type

[x] Feature request
[ ] Bug report
[ ] Documentation

Environment

Python version: 2.7.5
NetBox version: 2.2.6

Description

Services view:

Ability to add Custom fields to Services, can be used to specify additional info for the service, like provision mechanism (Puppet, Chif, Ansible), service status,  configuration path, add additional ports, and much more.

**Comment by jeremystretch** [comment]
We won't be extending custom fields in the near future. There's an explanation [in the FAQ](https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models).
