### ISSUE TITLE
No listings Site, Tenant, VRFs, Racks and Rack group in Search box

### ISSUE THREAD

**Issue by tdslot** [digitalocean/netbox#1765]
### Issue type
[ ] Feature request
[X ] Bug report
[ ] Documentation

### Environment
* Python version:  2.7.5
* NetBox version:  2.2.7

### Description
In ***VLANs*** https://netbox.company.com/ipam/vlans/ search box on the right no listing
   * Site
   * VLAN group
   * Tenant 

In ***VLAN Groups*** https://netbox.company.com/ipam/vlan-groups/ search box on the right no listing
   * Site

In ***VRFs*** https://netbox.company.com/ipam/vrfs/ search box on the right no listing
   * Tenant

In ***Prefixes*** https://netbox.company.com/ipam/prefixes/ search box on the right no listing
   * VRF
   * Tenant

In ***IP Addresses*** https://netbox.company.com/ipam/ip-addresses/ search box on the right no listing
   * VRF
   * Tenant

In ***Devices*** https://netbox.company.com/dcim/devices/ search box on the right no listing
   * Rack
   * Tenant

In ***Racks*** https://netbox.company.com/dcim/racks/ search box on the right no listing
   * Rack group
   * Tenant
   * Role

![](https://i.imgur.com/yyA0lcU.png)

Maybe is some problem with my installation or in DB?

Tadas

**Comment by jeremystretch** [comment]
As far as I can tell, this only affects the development server.
