### ISSUE TITLE
Access List per Menu

### ISSUE THREAD

**Issue by bazyar** [digitalocean/netbox#1769]
### Description
[X ] Feature request
[ ] Bug report      
[ ] Documentation 

### Environment
* Python version:  latest
* NetBox version:  latest

As for LOGIN_REQUIRED, it locks up the visibility of any part of Netbox, which is great. However, It would be nice if we could customize the view to show only the information that you want to display per each user. Take, for example:

Alice has to be limited to merely the Rack menu.
John needs to be confined to explore only the Devices menu.

**Comment by bazyar** [comment]
Any thoughts, guys?

**Comment by jeremystretch** [comment]
Covered by #323
