### ISSUE TITLE
Make Search Headers link to sub-searches

### ISSUE THREAD

**Issue by awfki** [digitalocean/netbox#1774]
### Issue type
[ X] Feature request 

### Environment
* Python version:  2.7
* NetBox version:  2.2.4

### Description
If do a search from the upper-right search box I get a page that includes results from various object types (Device, Prefix, etc).  It would be very handy if there were links from there to the same search on specific types.  So for instance, I do the global search for "dhcp" and get a page like this URL https://netbox/ipam/prefixes/?q=dhcp.  

The Devices header would be a link to https://netbox.rsglab.lan/dcim/devices/?q=dhcp.
The Prefixes header would be a link to https://netbox.rsglab.lan/ipam/prefixes/?q=dhcp.
et cetera

Alternately, there's a "Search Results" box on the right side of the results page where these links could be put instead of the current links that go to the sections on the same page.

**Comment by jeremystretch** [comment]
A button labeled "See all _n_ results" is added beneath each table if more results exist for that type of object. Otherwise, the displayed table already contains all relevant results. Adding a link to the same thing would be redundant.

**Comment by awfki** [comment]
For search results it's redundant but the functionality isn't the same on the global search page as on the type specific pages.  

For example once I've found the devices I'm looking for via the global search I want jump to the Devices search so that I can select them (or a subset) and then do things with them.  

Right now I'll global search, realize I can't do what I want (unless it's just to find a single thing) and then repeat the search on type page.

Obviously not a priority but it seems like it would be a simple change and it would smooth my workflow and I assume I'm not the only one with this issue.
