### ISSUE TITLE
Manage rack power consumption and heat dissipation

### ISSUE THREAD

**Issue by Maxkaha** [digitalocean/netbox#1777]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description

Definition of model specifications and materials used to view the detail by rack (number of free U, power consumption, calorific waste, flow Rate, weight)

For example, the plugin rack management for GLPI : https://github.com/InfotelGLPI/racks

Model device specifications
![image](https://user-images.githubusercontent.com/34587246/34064210-a60b35d8-e1f7-11e7-922b-8da2863b54e4.png)

Resume total Rack
![image](https://user-images.githubusercontent.com/34587246/34064239-d8d281f6-e1f7-11e7-926f-7cf5be9ed0eb.png)

Really very good job far ahead of all the others that i have been able to try
Regards

**Comment by jeremystretch** [comment]
Power management is covered by #54. Other than that this is far too broad to be an actionable feature request.
