### ISSUE TITLE
When bulk adding ips via a prefix, VRF should default to that of the prefix

### ISSUE THREAD

**Issue by explody** [digitalocean/netbox#1778]
### Issue type
[ ] Feature request 
[ X ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.2.8-dev (HEAD)

### Description

When one navigates to a prefix and clicks "Add an IP address", the single-ip form defaults to setting the VRF to the current VRF of the prefix.  However, if one switches to the 'Bulk Add' tab, the VRF selection resets to "Global".

Instead, it should default to the VRF of the prefix, as with the single-IP form.

Just follow the steps described to reproduce (confirmed on 2.2.7-dev - 2.2.8-dev)

<img width="860" alt="screen shot 2017-12-15 at 8 10 44 pm" src="https://user-images.githubusercontent.com/80896/34065878-d03d409e-e1d4-11e7-9f8a-734f91c13bba.png">

**Comment by explody** [comment]
Minor correction, 'Global' may be a VRF we added, I don't recall.  But, just checked this on a different vanilla instance and it defaulted to '---------'.   In both cases, it's the default VRF option and not the one specified in the query args.

**Comment by jeremystretch** [comment]
Fixed in #1780
