### ISSUE TITLE
Manage Server Room Location

### ISSUE THREAD

**Issue by Maxkaha** [digitalocean/netbox#1779]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description

Modify the current management of locations:
- Region
    - Region
         - Site 1
              - Rack Groups 1
              - Rack Groups 2
              - Rack Groups ...
         - Site 2
              - Rack Groups 1
              - Rack Groups 2
              - Rack Groups ...
         - Website ...
by a management of "server rooms":
- Region
    - Region
         - Site 1
              - Server Room 1
                     - Rack Groups 1 (Row 1)
                     - Rack Groups 2 (Row 2)
                     - Rack Groups ... (Row ...)
              - Server Room 2
                     - Rack Groups 1 (Row 1)
                     - Rack Groups 2 (Row 2)
                     - Rack Groups ... (Row ...)
         - Site 2
              - Server Room 1
                     - Rack Groups 1 (Row 1)
                     - Rack Groups 2 (Row 2)
                     - Rack Groups ... (Row ...)
         - Website ...

The goal being to add a grill for the server room for the layout of the rack in the room. (example : http://ralph-demo.allegro.tech/dc_view#/sr/196)

![image](https://user-images.githubusercontent.com/34587246/34068922-8634b4a2-e245-11e7-975a-777f479bfec8.png)

![image](https://user-images.githubusercontent.com/34587246/34068925-9aa79512-e245-11e7-8c8a-4d1cd100a58d.png)

**Comment by jeremystretch** [comment]
NetBox intentionally uses ambiguous language like "rack group" and "site" because organization schemes vary widely among organizations. Thus, we would not introduce a "server room" model. However, there has been talk of making rack groups recursive (like regions). Would this address your request?

**Comment by jeremystretch** [comment]
Closing this out as it should be covered by #1754
