### ISSUE TITLE
Virtualization Cluster Export

### ISSUE THREAD

**Issue by LBegnaud** [digitalocean/netbox#1787]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  Python 2.7.5
* NetBox version:  v2.2.7

### Description
Exporting clusters doesn't include the site in the data. I believe it's this file that's the culprit (i'm not terribly knowledgeable with django)

https://github.com/digitalocean/netbox/blob/develop/netbox/virtualization/models.py

I believe the issue is the `to_csv` definition under `Cluster` class needs to include `self.site` as the 4th entry to match the `csv_headers`

I don't want to embarass myself with a PR (as i don't know how to test my code), but hopefully this is enough for a quick fix by someone more comfortable.

**Comment by jeremystretch** [comment]
Yep, that's it. Will take care of it, thanks.
