### ISSUE TITLE
static folder missing in v2.2.8

### ISSUE THREAD

**Issue by paul-desvignes** [digitalocean/netbox#1790]
In the latest release v2.2.8 - 2017-12-20, the static folder is missing in the netbox folder. This breaks the webgui.

I have used the one from previous release v2.2.7 as a workaround.

**Comment by jeremystretch** [comment]
The static folder isn't tracked as part of the code base. It gets created when `./manage.py collectstatic` is run as part of the installation/upgrade process.

**Comment by paul-desvignes** [comment]
I believe `./manage.py collectstatic` is supposed to be run by the `./upgrade.sh` script. For some reason it did not in my case because there was no static folder after upgrading to v2.2.8.
Note that I followed the step mentionned in the official documentation: https://netbox.readthedocs.io/en/latest/installation/upgrading/
