### ISSUE TITLE
Multible Rack Cases as "one Rack" / More Dimension-Options

### ISSUE THREAD

**Issue by Grauhuat** [digitalocean/netbox#1791]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.4.5 
* NetBox version: 2.2.6  

### Description

Hello,
Firstly, my company uses two or three full-size rack (Closets) bolted together as "one rack".
I tried it with "Rack Groups" (Rack11 -> Rack11-1; Rack11-2;...) but it would be a lot easier to see the racks side-by-side like they are in real life. If i select "Rack 11" i would like to have all three closets side-by side with front and rear.
Maybe an additional option in "Dimensions" in either "Type" as "Multiple Racks/Cases[1-3]" or a new field altogether like "Number of Racks/Cases".

Thank you, and happy Holidays!

**Comment by jeremystretch** [comment]
You can view multiple racks side-by-side in the rack elevations view (DCIM -> Rack elevations) and filtering racks by group or name.
