### ISSUE TITLE
Setting an IP as Primary via API

### ISSUE THREAD

**Issue by cimnine** [digitalocean/netbox#1793]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6
* NetBox version:  2.2.8

### Description

I would like to set an IP as the primary IP when creating/updating an IP via the API.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by cimnine** [comment]
🤔 

Now that I look at the API again it seems, than what I requested is possible through the `/api/dcim/devices/` endpoint.
