### ISSUE TITLE
是否考虑中文支持

### ISSUE THREAD

**Issue by si7eka** [digitalocean/netbox#1795]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description
请问老大，是否考虑UI的中文支持呢？

**Comment by RyanBreaker** [comment]
Translation: They're asking if Internationalization for different languages can be considered, such as Chinese.

**Comment by jeremystretch** [comment]
Please see my comments in #1068. We're not able to add support for additional languages at this time.
