### ISSUE TITLE
Add additional field on interfaceconnection table

### ISSUE THREAD

**Issue by wwerther** [digitalocean/netbox#1796]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version: 2.2.8

### Description

* Add an additional field called connection_name to track e.g cable_numbers on interface_connections
* Support that additional field on bulk_import
* Display the connection_name in device_view
* Make connection editable to modify the configured connection_name

**Comment by jeremystretch** [comment]
Physical cabling support is being tracked under #20.
