### ISSUE TITLE
Topology maps 

### ISSUE THREAD

**Issue by MouadMimouni** [digitalocean/netbox#1799]
Hi, 
How to use the "topology maps" function ? I looked at the netbox documentation but I did not understand how to do it
Thanks

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
