### ISSUE TITLE
Overlay network support (notably VXLAN)

### ISSUE THREAD

**Issue by dzorgnotti** [digitalocean/netbox#1800]
### Issue type
[ X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.1
* NetBox version: 2.2.8

This has been a dupe several times, but I'll try to make a use case for it as this was missing the last time.

**Request support for overlay networks, especially with VXLAN. **

Use Case:
Overlay networks (e.g. managed by VMware NSX, Cisco ACI, etc.)  are now being deployed more often to decouple virtual machine from the physical network resources, to support multi-tenant and/or multi-security zone environments. With the upcoming of GENEVE as a potential successor to VXLAN the thing is on the road to mainstream (my2c).

Without a proper support for the abstraction layer, systems are in limbo when it comes to documentation We can create a VM, we can assign IP addresses but be cannot assign a (overlay) network to these systems.
The same goes for the network infrastructure managing the overlay/underlay, e.g. we would need to define a gateway as a routing in/out tunnel device but can only create the physical (VLAN) side with netbox.
We tried a custom field but we've hit limits as this isn't shown by default and we lack some support in find/sort etc.

Required fields:

1. Virtual Network Identifier (VNI) (perhaps additional to VLAN for assignment).
2. VNI group (as an alternative to VLAN group)

VNI is a neutral expression which holds true for VXLAN or GENEVE deployments. 
I would suggest to clone the VLAN field in the first instance but allow for an identifier of 24 bits (integer).

Optional (would be not as important today)

- VTEP as a feature of a network device (hypervisor host, switch, router) with an IP, VLAN, control plane and control plane mode (e.g. EVPN, multicast, etc.) as possible options
- Control Plane to VNI mapping

Examples:

- VM is assigned an interface and an IP. IP/IP subnet is linked to a VNI.
- A device can have VLAN interface but also one or more VNI interfaces.
- A VNI is local or spans multiple sites

- Best case: A hypervisor host has a VTEP A on VLAN B with IP C. Assigned to control plane D which is running in mode E. VNIs F-H are assigned to the control plane D. VMs I and J are running in the VNI, etc.

I am not sure I can contribute anything to Python, libraries etc.
#1725 #1058 #1324

**Comment by jeremystretch** [comment]
While this would be an amazing feature, attempting to model the myriad approaches to overlay networking on the market today is too big a bite for us to take at this stage of NetBox's development. Sadly, I have to reject this request.
