### ISSUE TITLE
Show elevations in Rack Groups view

### ISSUE THREAD

**Issue by thefreakquency** [digitalocean/netbox#1801]
### Issue type
[x] Feature request 
[ ] Bug report   
[ ] Documentation   

### Environment
* Python version:  3.5.4
* NetBox version:  2.2.7

### Description
It would be beneficial to be able to see rack elevations for a given rack group on the rack group page, under or above the rack listing. 

**Use case:**
Our sites contain one or a few groups, but group names are the same for multiple sites (i.e.: Shelter, roof-top, Cage1... ). Users are usually accessing the site page, then the site group from there. They have to go then in each racks, but are not provided an overview for the group from there. 

Elevations for rack groups are available by going to Racks / Elevation, then filter by rack group. When they go in the rack Elevation view, in our case, they can only filter by site name since rack groups names are repeated multiple time in the filter options... but then they are presented with all racks at a given site. 

Since the functionality is already present elsewhere in NetBox, would it be hard to implement?

**Comment by jeremystretch** [comment]
We can just replicate the AJAX field update from the rack list so that selecting a site only shows groups within that site.
