### ISSUE TITLE
Outer-VLAN-id added to vlan groups.

### ISSUE THREAD

**Issue by funzoneq** [digitalocean/netbox#1806]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version:  2.2.8

### Description
I'd like to see support for 'vpls' vlan tagging in the vlan groups. Basically VPLS can have an inner vlan tag and an outer vlan tag. The combination of these two can be used to identify a unique customer. For example a group of switches gets Outer vlan ID 121 and on those switches customers get vlan 1-4096. The resulting packet will (for example) have Outer VLAN 121 and inner vlan 432.

The only thing we would need to add is a unique OutervlanID to the netbox/ipam/models.py. I have a patch ready to support this.

**Comment by funzoneq** [comment]
https://github.com/digitalocean/netbox/compare/develop...paxio:183d93e0c802139435a37944fbc92124828dbe98

**Comment by jeremystretch** [comment]
Custom fields are not supported on secondary models. Please see [the FAQ](https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models).
