### ISSUE TITLE
Tenant not pre-populated when creating an available ip address or prefix

### ISSUE THREAD

**Issue by bashioo** [digitalocean/netbox#1809]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2 
* NetBox version: 2.2.8 

### Description
Steps to reproduce:

1. Create a new prefix and assign it to a tenant.
2. View the parent prefix and click the "ip addresses" tab or "child prefixes" tab.
3. Click one of the available addresses or prefixes to render the form to create a new address/prefix.

The tenant assignment is not pre-populated in the form.

Clicking "add ip address" or "add child prefix" button in the top right corner of the same page works as expected for both addresses and prefixes.

**Comment by jeremystretch** [comment]
Related to #1807.
