### ISSUE TITLE
Support for range expansion when creating IP addresses

### ISSUE THREAD

**Issue by makpe** [digitalocean/netbox#181]
Is it possible to add feature to Add IP addresses like 192.168.1.[1-254]/24 same works with device Interfaces? 

Basically I like that when you create new prefix it should automatically generate all possible IP addresses to specified prefix. Easier to see free addresses under prefix IP addresses list without description.

**Comment by jeremystretch** [comment]
Range expansion would be nice. You don't want to automatically create every IP because every IP probably isn't in use.

**Comment by eronlloyd** [comment]
Would it also be possible to display a progress bar that calculates IP pool depletion levels? Something like this would provide a quick way of seeing the number of remaining addresses:

![image](https://cloud.githubusercontent.com/assets/197778/18616899/a2570860-7d92-11e6-964f-72e1e9d846e1.png)

**Comment by specialcircumstances** [comment]
Hi - I see this was commited in 1.7.0 but is it usable in the Add IP Address view yet?

**Comment by dvinni** [comment]
What about this feature? How to use it?

**Comment by brianblac** [comment]
I noticed this on some commits, is this feature getting close? Very excited for it as well.
