### ISSUE TITLE
Normalize lldp devices (hostnames) in "LLDP Neighbors" Tab

### ISSUE THREAD

**Issue by tom-myny** [digitalocean/netbox#1810]
Issue type
[X] Feature request

Environment
NetBox version: 2.2.8
Description
Currently, the "LLDP Neighbors" tab represents lldp devices in a shorter name then given.

Example: 
A juniper switch configured as:
system {
    host-name spine1.bru-hdc.be;
    domain-name tigron.net;
    ...

Will be represented in netbox as 'spine0'.

This is not correct, juniper gives the following information to NAPALM:

root@spine0.bru-hdc.be> show lldp neighbors
Local Interface    Parent Interface    Chassis Id          Port info          System Name
et-0/1/1           ae0                 xx:xx:xx:xx:xx:xx   et-0/1/0           spine1.bru-hdc.be
et-0/1/0           ae0                 xx:xx:xx:xx:xx:xx   et-0/1/1           spine1.bru-hdc.be

NAPALM will give the following information to netbox:

`
{
    "get_lldp_neighbors": {
        "et-0/1/1": [
            {
                "hostname": "spine1.bru-hdc.be",
                "port": "et-0/1/0"
            }
        ],
        "et-0/1/0": [
            {
                "hostname": "spine1.bru-hdc.be",
                "port": "et-0/1/1"
            }
        ]
    }
}
`

However, netbox will return only spine1, resulting in a red (incorrect) field.

**Comment by jeremystretch** [comment]
IIRC NetBox strips off anything after a period in the hostname because some platforms will return a FQDN (e.g. router01.example.com):

```
var lldp_device = neighbor['hostname'].split(".")[0];  // Strip off any trailing domain name
```

However, I can't find any documentation of this change. It's also possible that the observed behavior has since been changed in the affected NAPALM driver(s). I'm ok with removing the alteration and seeing if anyone else complains. (If so, we can evaluate how best to satisfy both cases.)

**Comment by tom-myny** [comment]
I agree with this new behavior :)

**Comment by jeremystretch** [comment]
Testing suggests that many devices return their FQDN rather than just their hostname. To avoid breaking these, the current approach to stripping the domain name will stay in place.

**Comment by jkrauska** [comment]
I have a middle use case, where I want the final domain name stripped, but NOT the sub domain.

eg. I WANT
storage1.iad1 
to differentiate from
storage1.iad2

but I don't want the trailing example.com

How about making a configuration field of what domain(s) we'd like to strip?

**Comment by TvL2386** [comment]
I'm having this same issue.
Would it be a good idea to make this a configuration option at the Platform view?

Example: I create a Platform with napalm driver junos and disable "strip domain name".
This way there's a simple way to toggle this behaviour for sets of devices.

Kind regards!
