### ISSUE TITLE
Attach RFS documents to a circuit

### ISSUE THREAD

**Issue by loopodoopo** [digitalocean/netbox#1811]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

I would love the option to add ready for service (RFS) documents and other documentation I currently store on a shared drive for circuits in Netbox. This way I have all documentation regarding a specific circuit on one location available for my whole team. 

Below 'Termination - Z Side' I would like to have an extra listing for all the documents uploaded and a 'X' to delete them again. The name of the document could be clickable (URL) so it downloads the document or it could also do some javascript to display in the browser directly. 

I made a mockup of what I would like, I'm pretty sure this is also useful for a lot of other users: 

![d4924f3776e5f8a2](https://user-images.githubusercontent.com/17925078/34664693-5f63e30a-f45d-11e7-9cb7-d8ce2676435e.png)

I'm not 100% sure what alterations this change need in the database schema. I do think there is already a functionality to upload documents, perhaps parts of this code can be reused?

**Comment by jeremystretch** [comment]
NetBox isn't a great place to store miscellaneous documents. The recommended approach would be to create a custom field on the circuit object type and link to a related document stored externally. (This will be made easier with #600 and/or #969).
