### ISSUE TITLE
Add default report

### ISSUE THREAD

**Issue by Maxkaha** [digitalocean/netbox#1812]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.4
* NetBox version:  2.2.7

### Description
Hello, is it possible to integrate in the next version of the default reports in Netbox as an example in the doc:

- All top-of-rack switches have a console connection
- Every router has a loopback interface with an IP address assigned
- Each interface description conforms to a standard format
- Every site has a minimum set of VLANs defined
- All IP addresses have a parent prefix

Report writing remains complex?

Regards

**Comment by jeremystretch** [comment]
Reports are completely custom and will vary greatly from one organization to the next. People are certainly welcome to publish and share reports they've written, but any work in that regard will need to be maintained outside the main NetBox project.
