### ISSUE TITLE
Interface Connections Search

### ISSUE THREAD

**Issue by Maxkaha** [digitalocean/netbox#1813]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.4
* NetBox version:  2.2.7

### Description

Is it possible to add the interfaces in the global search or Interface Connections ?

The need is to be able to search the name of the interface of a patch panel for example to identify where this inferface is connected.

Regards

**Comment by jeremystretch** [comment]
NetBox does not yet support patch panels (see #20). Interfaces (and other components such as console and power ports) are grouped by parent device/VM; there is no aggregate search view for interfaces in the web UI. However, it is possible to filter the API endpoint at `/api/dcim/interfaces/` by name and other attributes.

**Comment by tiago-cruz-movile** [comment]
@jeremystretch ,

Is possible to filter using two arguments? some like this:

```
tiagocruz@konoha:~$ curl -s "$url/api/dcim/interfaces/?name=eth0" | jq . | grep display_name
        "display_name": "mcloud1"
        "display_name": "mcloud6"
        "display_name": "mcloud8"

tiagocruz@konoha:~$ curl -s "$url/api/dcim/interfaces/?display_name=mcloud8&name=eth0" | jq . | grep display_name
        "display_name": "mcloud1"
        "display_name": "mcloud6"
        "display_name": "mcloud8"

```

Thanks!
