### ISSUE TITLE
Increasing max. field lengths  

### ISSUE THREAD

**Issue by taka-psba** [digitalocean/netbox#1817]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  2.2.7

Hi

I see [here](https://github.com/digitalocean/netbox/issues/894#issuecomment-283676826) that you're generally happy with 64 character field limits, but we have things like:
- tenants (curr. max. 30):
  - "Department of Science Information Technology and Innovation" (59 chars)
  - "Department of Justice and Attorney General (42 chars)
- sites (curr. max. 50):
  - "Rockhampton Central Region Police Communications Centre and Police Station" (74 chars)
  - "Moa Island - St Pauls Community - Torres Strait Island Police Support Office" (76 chars)
- interfaces (curr. max. 64):
  - "Microsoft Network Adapter Multiplexor Driver-Microsoft Load Balancing/Failover Provider-0000" (92 chars)
  - "HP Ethernet 1Gb 4-port 331FLR Adapter #3-WFP 802.3 MAC Layer LightWeight Filter-0000" (84 chars)
  - "Intel(R) PRO/1000 MT Network Connection #2-Network Load Balancing Filter Driver-0000" (84 chars)

I'm importing stuff from an existing NMS, and since I can't really make changes to the source data, I've put in a translation layer for problematic values, but things like "Department of Science Information Technology and Innovation" had to be compressed down to "Dept. of Sci.Info.Tech.Innov.", which is not really acceptable to the client :-)

Any chance of these field lengths being increased?

Thanks

**Comment by jeremystretch** [comment]
The field lengths will not be increased. These values are included in object tables, and it would be ridiculous to have such long descriptors mangling the rendering of tables. I suggest using abbreviations for the names and including the long form, if necessary, in the object description or comments.
