### ISSUE TITLE
Add a "Description" field to Site object

### ISSUE THREAD

**Issue by LukeRussell** [digitalocean/netbox#1821]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7 
* NetBox version:  2.2.8 

### Description
We would like to add a "Description" field to the `site` object.

This would be implemented similar to Tenant Description, and have the same use case as a way of implementing a Long-form name. It would be an optional field, 100 characters, same labels. 

A custom field for `Description` is functional, and that is how we've started, but then the field shows up at the bottom of the site view instead of front and centre, like `Name`.

**Comment by LukeRussell** [comment]
Thanks, we'll get started.

**Comment by jeremystretch** [comment]
Implemented in 7378d82 for the v2.3 beta
