### ISSUE TITLE
Duplicate/Create new device types from existing

### ISSUE THREAD

**Issue by slindermann** [digitalocean/netbox#1822]
## Issue type
[x] Feature request 
[ ] Bug report 
[ ] Documentation

## Environment
Python version: 3.5
NetBox version: 2.2.8

## Description
Hi,
I thought it would be very handy to be able to create new device types based on existing models. I'm looking for some sort of "duplicate" button that allows me to copy interfaces, device bays and console ports over to a new device type in which I only need to adjust the model name etc.

For instance, this would save some time if one needs to create a range of Juniper switch models (EX4200-48T, EX4200-48PX, ...).

Let me know if this might be an easy implementation w/o too much of an effort for you guys.

Thanks,
Simon

**Comment by zevlag** [comment]
See #242 and #451 and #33

**Comment by slindermann** [comment]
Thanks Josh, should have been looking for the "clone" keyword :)
Any ETA when #451 is going to be implemented?

**Comment by jeremystretch** [comment]
#33 is more likely to happen soon. #451 is going to be pretty involved.
