### ISSUE TITLE
Circuit links to other areas

### ISSUE THREAD

**Issue by xonacs** [digitalocean/netbox#1832]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

We are using the Circuit IDs to also log Power Circuits, IP Bandwidth Circuits etc.  Currently, circuits are linked to an A/Z side but cannot be linked to anything else, such as devices, IP prefix etc.

As an example, we have the PDUs which we would like to link to these Power Circuits.  We would also like to link such Circuits with the rack numbers.

We tried to add custom fields to racks/devices/prefixes to have this info.  To eliminate double entry it would be good if we could choose a drop down list from a list of circuits for a custom field.

**Comment by jeremystretch** [comment]
> Currently, circuits are linked to an A/Z side but cannot be linked to anything else, such as devices, IP prefix etc.

Each side of a circuit can be terminated to a device interface, via which it can be associated with an IP address.

> As an example, we have the PDUs which we would like to link to these Power Circuits. We would also like to link such Circuits with the rack numbers.

Circuits represent only physical data links and are not related to power. NetBox does not currently support modeling power distribution; see #54.
