### ISSUE TITLE
Display rack name next to site name in a circuit page

### ISSUE THREAD

**Issue by VictorRaim** [digitalocean/netbox#1836]
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 2.7.12
* NetBox version: 2.2.8

### Description

In webGUI when you display circuit and its A and Z termination sides. Only the site, termination device and port is displayed. Could it be better to also add the rack name next to the site termination ?

Something like this : 
![netbox rack circuit request feature](https://user-images.githubusercontent.com/5525167/35383367-658f2204-01c2-11e8-80b2-ee301385b443.PNG)

With this it would be easier to find informations when you have multiple racks in one site.

**Comment by jeremystretch** [comment]
The rack is inferred from the device on which the circuit is terminated. It doesn't seem likely that a lot of people will need this information included next to the device name.

**Comment by manolab** [comment]
I'd actually like that 👍

**Comment by thefreakquency** [comment]
Me too! It would help to minimize the end users action (prevent another search and associated possible human erors) when troubleshooting a circuit.

Could this be implemented using an on/off flag to be flexible ?

**Comment by ryanmerolle** [comment]
I really have to agree with @jeremystretch here.  Does not seem like a bunch of ROI, and it starts a potential ui noise creep.

Click the device to see what rack it’s in, or generate a report if you need that view.  Maybe this gets added later as netbox addresses more major features.

Maybe if someone else besides Jeremy wants to implement this, they can do a PR, but this badly sounds like a nice to have.

**Comment by jeremystretch** [comment]
Yeah, I've got to reject this one as there's no direct relationship between a circuit and the rack in which the devices it's terminated to is installed. That information as well as any other information concerning the device is provided on the device view.
