### ISSUE TITLE
Add documentation for common PostgreSQL tasks common to NetBox administration

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#1837]
### Issue type
[ ] Feature request 
[ ] Bug report      
[X] Documentation   

### Environment
N/A

### Description
A comment in the `NetworkToCode` Slack channel took place yesterday about "network folks that are still trying to get the hang of the API/Programming world" and managing installations of NetBox.

I think it would be a good idea to provide some documented examples of common DB tasks related to the administration of NetBox.  I'm thinking something like a `FAQ` section would be the correct location but am open to other suggestions.

As a newcomer myself to the scene, I know I have to frequently use my `GoogleFu` to look up how to do the following tasks (and I don't think I'm alone in the regard):

1. How to backup the PostgreSQL DB correctly ideally using DigitalOcean `Spaces` (have to give a plug for your employer who allows you time to develop NetBox :100:) or Amazon `S3`
2. How to migrate from a development installation of NetBox to production installation (i.e. including `custom_fields` that have been defined and tested in a specific environment)

Not sure how common this one is, but I'll include it to be thorough.

3. How to "dump" the just schema of the DB for migrations, etc.

I'd be happy to submit a PR with what I recently learned on those three topics if you think it would be a good idea to include that in the official documentation on `ReadTheDocs`.  Additionally, perhaps there are more than just those mentioned above which would be important to include as well.

**Comment by jeremystretch** [comment]
I'm okay with this, but let's be cognizant of scope creep. I want to avoid overextending the scope of our documentation covering information that's readily available elsewhere.

**Comment by bdlamprecht** [comment]
Yeah, I completely agree that we shouldn't duplicate what is already available.

Do you think that a FAQ would be an appropriate place to document this?
Are there other things you or other people would like to see included besides the three I mentioned above?

**Comment by jeremystretch** [comment]
I'd prefer to avoid a FAQ format in the official docs and maybe establish a "general administration" section of the docs, or something in that vein. We do have a FAQ on GitHub but that pertains more to maintenance of the project rather than NetBox itself.

**Comment by jeremystretch** [comment]
I've added an "administration" section to the v2.4 docs, which includes instructions for replicating NetBox. We'll likely add other common tasks over time.
