### ISSUE TITLE
Getting an error when clicking on create virtual chassis without device selected

### ISSUE THREAD

**Issue by dgarros** [digitalocean/netbox#1838]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6
* NetBox version:  2.3-beta1

### Description
I'm getting an error when I'm clicking on `create virtual chassis` at the bottom of the device page if there are no device selected.

<img width="766" alt="screen shot 2018-01-25 at 11 36 08 pm" src="https://user-images.githubusercontent.com/304126/35429348-8e0b1470-0228-11e8-8385-1b1e9cad685a.png">

To reproduce, 
 - Go to the device page `Devices > Devices`
 - Go to the bottom of the page, without selecting anything
 - Click `create virtual chassis`

> BTW it took me some time to find this button since it's at the bottom of the page. I have more than 50 devices and buy default these buttons are not visible for me, I need to scroll down.

**Comment by nathbooth** [comment]
Ditto!

**Comment by jeremystretch** [comment]
Fixed in 8b6d731cb61cda10c76b6607a21e95dc3ee72d73
