### ISSUE TITLE
unix socket assignment to the device service

### ISSUE THREAD

**Issue by azatuni** [digitalocean/netbox#1839]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  2.2.8

    Description:
        * When you assign service to device it is only supports TCP/UDP sockets, but on *nix environment there are already exists unix sockets. Can add please unix socket support for new service, for example if I choose UNIX socket it'd also allow me to document path to unix socket file, for example: service => php-fpm => unix socket => /var/run/php5-fpm.sock

Thanks beforehand.

**Comment by jeremystretch** [comment]
NetBox is only intended to manage network resources. The advantage of the service model in NetBox is that it allows associating a network-enabled service with one or more IP addresses. Since sockets are only locally-reachable, defining them would be out of scope for NetBox.
