### ISSUE TITLE
Virtual Chassis LAG configuration 

### ISSUE THREAD

**Issue by flobe212** [digitalocean/netbox#1843]
**Issue type**
[X] Feature request 
[] Bug report 
[] Documentation

**Environment**
Python version: 3.6
NetBox version: 2.3-beta1

**Description**
The new virtual chassis function doesn't include the LAG configuration inside the virtual chassis. When you are adding a LAG interface on one of the VC member its not possible to choose the LAG on one of the other devices. Its possible to add this feature in a new version?

**Comment by lampwins** [comment]
I think this should also include virtual interfaces. The virtual chassis implementation is a great step forward, but I do not think in the current form, it solves the control plane model. In a virtual chassis, a physical interface may reside on a member, but it belongs to the virtual chassis, not that member, from a control plane perspective. LAG and virtual interfaces present an equally challenging case in that they _only_ belong to the virtual chassis. So I still think the interfaces actually need to be stripped from the individual members and assigned only to the virtual chassis. When viewing an individual member, it makes sense to be able to see the interfaces that physically reside on that member. But doing so would allow LAG and virtual interfaces to be assigned to just the virtual chassis and for LAG member interfaces to span all members.

**Comment by jeremystretch** [comment]
I did some work on this in 1cd629e; please try it out and let me know what you think.

For LAGs and virtual interfaces in general, the answer is going to be "only define them on the VC master." It's not ideal, but it's the most practical approach we have for now.

**Comment by jeremystretch** [comment]
This appears to be resolved. (Even if it isn't, please try any further testing on the `develop-2.3` branch as the VirtualChassis data model has been overhauled.)

**Comment by dgarros** [comment]
@jeremystretch do you have a summary of the changes you are planning to make to the VC data model ? 

I tried the current implementation in 2.3beta1 and I'm still trying to figure out the best way to consume a VC and easily collect all information needed to generate the configuration.

Thks
