### ISSUE TITLE
Add support for sub-packaging of reports

### ISSUE THREAD

**Issue by dougthor42** [digitalocean/netbox#1857]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version: 2.2.8

### Description
Reports are amazing. Since they're basically just Python packages, it makes sense that a user should be able to make an arbitrary number of sub-packages in the `reports` directory.

```
netbox/reports/
├───__init__py
├───assets.py
├───addresses.py
├───checks/
│   ├───__init__.py
│   ├───check_serials.py
└───inventory/
    ├───__init__.py
    ├───list_inventory.py
    └───list_ipv6.py
```

Reports above could be called via:

```
POST /api/extras/reports/checks.check_serials.CheckSerials/run/
```

**Comment by jeremystretch** [comment]
Each report is already a collection of related tests. I don't see the need to further group reports into directories, and fear doing so would complicate the UI.
