### ISSUE TITLE
[Question] NAPALM Login credentials static?

### ISSUE THREAD

**Issue by slindermann** [digitalocean/netbox#1862]
### Issue type
[x] Feature request
[ ] Bug report
[ ] Documentation

### Description
This is more likely a question rather than a feature request:

I've successfully connected to Juniper switches using NAPALM with netbox. However, it only seems to work when I store a static user and password in the configuration.py NAPALM_USER and NAPALM_PASSWORD variables. Since netbox allows to store login credentials per device I was under the impression that I could use these for logging into devices, as I won't be able to use a single user/passwd combination for all of them.

Am I wrong with this?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
