### ISSUE TITLE
API device name issue with hyphen

### ISSUE THREAD

**Issue by cslingerland** [digitalocean/netbox#1868]
### Issue type
[ ] Feature request 
[ x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6.4
* NetBox version:  <2.2.8

### Description
Unable to find devices by name in API when they have hyphen
For example: "server-1" cannot be found with the following URL:
/api/dcim/devices/?name=server-1

**Comment by jeremystretch** [comment]
Not able to replicate this on v2.2.9. Three things:

1. Try upgrading to the latest stable release (v2.2.9).
2. Make sure you're matching the exact name (use `?q=` for searching).
3. Maybe a hyphen got replaced with an [en-dash or em-dash](http://www.punctuationmatters.com/hyphen-dash-n-dash-and-m-dash/) somewhere?

**Comment by cslingerland** [comment]
Oh my, it was a virtual machine, not a device.
