### ISSUE TITLE
Make docker-compose not rely on local volumes

### ISSUE THREAD

**Issue by ChristianKniep** [digitalocean/netbox#187]
When deploying the docker-compose file on a remote SWARM cluster it (most likely) won't have access to the github repository, hence the default config can not be mapped into the container.
I reckon that either the config is backed into the original container (while volumes_from) could be used by the nginx container or the config is derived from a template (confd/consul-template/...) using environment variables.

I'll try to provide a version that could be deployed remotely, not sure when I'll find the time.

**Comment by jeremystretch** [comment]
Closing because I think this was resolved by merging #188. If not, please reply and I'll reopen.
