### ISSUE TITLE
Asset Tag link to exiternal system

### ISSUE THREAD

**Issue by cyberjacob** [digitalocean/netbox#1873]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3
* NetBox version:  2.2.9

### Description
Ability to create a link from the asset tag field of a device (or anything with an asset tag) to an external system (e.g. inventory tracking). This could be customised by having a configuration setting with a prefix and suffix that are prepended and appended to the asset tag as relevant.

For example, if `ASSET_LINK_PREFIX` was set to `http://example.com/inventory/` and `ASSET_LINK_SUFFIX` was set to `/view/`, the asset tag `123` would generate the URL `http://example.com/inventory/123/view/`

**Comment by cyberjacob** [comment]
I understand Netbox isn't trying to be a universal inventory tracking system, hence why having the link is probably more flexible.

On a similar note, this could also be used for a ticketing system or similar. As such, would it be more flexible to have an "external links" section with multiple links?

**Comment by cyberjacob** [comment]
Example UI:

![image](https://user-images.githubusercontent.com/161093/35978354-62ee81ae-0cdd-11e8-8ffc-c6b827670ac6.png)

**Comment by cimnine** [comment]
Sounds like https://github.com/digitalocean/netbox/issues/969 would solve this.

**Comment by cyberjacob** [comment]
Yup, must have missed that one.
