### ISSUE TITLE
Data Retrieval from external monitoring systems

### ISSUE THREAD

**Issue by cyberjacob** [digitalocean/netbox#1874]
### Issue type

[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3
* NetBox version:  2.2.9

### Description
Netbox provides an excellent overview of Layer 1-3 of a network, however the ability to see real-time status information alongside the plans would be very useful. Providing a full monitoring system is out-of-scope for Netbox, however it seems simple to load an external status (simply `OK` or `fault`) from another system. Ideally, this could be implemented similar to the reports section, as this would enable support for new monitoring systems to be easily implemented as necessary.

**Comment by cyberjacob** [comment]
Started working on this [here](https://github.com/cyberjacob/netbox/commit/cf22aa095d25463da14ccf5e8faf959a4d8f6775). Very rough at the moment, but putting something like the below into the monitoring folder makes devices look like this:

![image](https://user-images.githubusercontent.com/161093/36039206-b883985c-0db9-11e8-8d6f-02a9eb6074d6.png)

```python
from dcim.monitoring import Monitoring
    
class TestMonitoring(Monitoring):
    def get(self, object):
        self.log_default("Unknown")
        self.log_ok("OK")
        self.log_info("Hello, World")
        self.log_warning("Might break soon")
        self.log_failure("Just exploded!")
```

**Comment by jeremystretch** [comment]
I have to reject this feature request as out of scope for NetBox. #969 will allow for predictive linking to external NMS and other systems, but that's as far as we'll go. Implementing the ability for NetBox to directly pull information from other systems would open a Pandora's box of development, performance, and security issues.
