### ISSUE TITLE
Extension of available-prefixes api endpoint

### ISSUE THREAD

**Issue by DirtyCajunRice** [digitalocean/netbox#1875]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description
The available prefix endpoint is a wonderful implementation, but only works for pre-existing larger prefixes. When you have an aggregate of Public IPs e.g. /21 and want to pull a new public prefix from that, it is not currently possible.

Thoughts? If wanted, I can try to add this myself this weekend. (Templetizing Jeremy's previous prefix addition)

**Comment by jeremystretch** [comment]
Aggregates behave a bit differently than prefixes in that they define a swath of IP address space which exists but has not been allocated for anything yet (and may not ever be fully utilized). In most cases, users probably want to select specific top-level allocations from aggregates. But if you do need to provision prefixes automatically, you have the option of defining a container prefix the same size as its aggregate.

**Comment by diman512** [comment]
Hi Jeremy,
Basically, I am facing the same issue, where we have an aggrigate prefixes of /8 or /16 and we do allocations of /24 from that aggregated prefix.
I need a way to know what aggregate prefix is full utilization so I can move over to the next /16 aggregated prefix.
Can you add an API for that?
