### ISSUE TITLE
Change hardcoded colours to a jQuery based hex colour picker

### ISSUE THREAD

**Issue by base-zero** [digitalocean/netbox#1880]
### Issue type
[X] Feature request
[ ] Bug report
[ ] Documentation

### Environment
* OS version : Ubuntu 16.04
* Python version:  2.7.12
* NetBox version:  v2.3-beta2
   
### Description

When selecting colours for device roles in Netbox there is only hardcoded options for colours which is very limiting and causes some device roles to have the same colours making it more difficult to quickly differentiate the device roles. I prepose replacing the hardcoded colour options with a jQuery hex editor so users can select any hex based colour they want. This would give better clarity on the device role page and more flexibility on how users tag the devices.

There has been a past issue posted about this ( #672 ) which did result in changes to the hardcoded coded however I think a  jQuery hex editor should be added now to offer better flexibility as we have ran out of unique colours.

**Comment by jeremystretch** [comment]
As noted in [#672](https://github.com/digitalocean/netbox/issues/672#issuecomment-265215853), the list of available colors is intentionally limited to avoid assigning colors which are difficult to discern from one another.
