### ISSUE TITLE
Bulk editing of interface 802.1Q settings results in incorrect form validation.

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#1881]
### Issue type
[ ] Feature request 
[ x ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  develop-2.3

### Description
Bulk editing of interface 802.1Q settings results in incorrect form validation. The `InterfaceBulkEditForm` is only accounting for initial data for 802.1Q fields and thus bombs validation because no device context on form post. The interface create and edit forms do this correctly.

**Comment by jeremystretch** [comment]
Fixed in #1882
