### ISSUE TITLE
When creating/editing a Virtual Chassis, unnamed devices need more context 

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#1884]
### Issue type
[ ] Feature request 
[ x ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  develop-2.3

### Description
When creating/editing a Virtual Chassis with unnamed member devices, these devices need more context. Currently the string method on the Device model falls back to the device type name when the device has no name. This causes a problem when creating/editing a Virtual Chassis whith multiple unnamed devices. Such devices need more context; I suggest including their serial numbers.

<img width="802" alt="screen shot 2018-02-13 at 7 39 29 pm" src="https://user-images.githubusercontent.com/1297132/36182153-365beeb6-10f6-11e8-8051-d8f71994c043.png">

**Comment by jeremystretch** [comment]
Hmm, devices might not have a serial number set. Maybe we could assign each device a letter (rather than a digit, to avoid confusing it with stack position) to uniquely identify each device in the stack, just for the purposes of this form.

**Comment by lampwins** [comment]
When would the letter be set? I am thinking of this from the standpoint of, I have created a couple of new unnamed devices but now I can't differentiate between them in this form.

**Comment by jeremystretch** [comment]
It would be the first column in the table, and included next to each device in the selection list.

It would probably make more sense to just include the unique ID (primary key) that each device already has.

**Comment by jeremystretch** [comment]
Adding serial and rack/unit columns as well.

**Comment by jeremystretch** [comment]
Closed in e653f35
