### ISSUE TITLE
Allow device filtering based on presence of primary IP

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#1885]
### Issue type
[ x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7
* NetBox version:  develop-2.3 (also applies to 2.2.9)

### Description
With the impending drop of 2.3 and Virtual Chassis support, there is likely to be jump in the number of devices that users have in netbox that do not have primary IP's assigned. It would be nice to be able to filter in the device list view based on presence of a primary IP, much in the same way the `has_primary_ip` filter works in the API.

**Comment by sscotter** [comment]
+1

**Comment by sscotter** [comment]
Working for devices, but not for Virtual Machines. Would it be possible to add to Virtual machines too please?

Thanks
Steve
