### ISSUE TITLE
Feature Request - Spare Inventory

### ISSUE THREAD

**Issue by DirtyCajunRice** [digitalocean/netbox#1888]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description
I would like to add a status of "Inventory - Spare". I understand that Having a device in inventory assigned to a tenant could technically be considered a spare for that tenant, but doing this causes no harm as there are only 5-6 statuses and this disambiguates the difference.

If approved ill create a pull request

**Comment by jeremystretch** [comment]
I have to reject this as general inventory management is out of scope for NetBox. We already have the `Inventory` status for devices which are physically installed but unused: Devices which are sitting in a box or pile somewhere shouldn't be in NetBox. Instead, they should be tracked in a purpose-built asset management system.

The topic of which asset management systems integrate well with NetBox actually came up [on the mailing list](https://groups.google.com/forum/#!topic/netbox-discuss/Me_tqVgWj58) the other day and may be worth a look.

**Comment by DirtyCajunRice** [comment]
Understood. I have Snipe-It spun up for testing but its caca. Ill keep looking tho!

**Comment by ryanmerolle** [comment]
> Understood. I have Snipe-It spun up for testing but its caca. Ill keep looking tho!

@dirtycajunrice any updated expereince with a tool for spare inventory?  Snipe-It works for office/user gear, but not really for datacenters as you mentioned.
