### ISSUE TITLE
Create NetBox docker image on dockerhub and use CI to build new images

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/netbox#189]
From here: https://github.com/digitalocean/netbox/pull/107#issuecomment-230222850.

**Comment by jeremystretch** [comment]
@zachmoody Any interest in this?

**Comment by eliezerlp** [comment]
It seems that this appeared to be the thought originally in #107 (actually happened in #188). Later on in #255 it was made to work using the local Dockerfile.

Do you have any clue who admins https://hub.docker.com/r/digitalocean/ ?

**Comment by zachmoody** [comment]
Yeah, was thinking that'd be the ideal way forward when doing #255...no idea who admins the repo @eliezerlp found. Last time I checked I couldn't find anything like it. I'll poke around some.

**Comment by zachmoody** [comment]
Ok, we were able to take ownership of https://hub.docker.com/r/digitalocean/, but looks like we're going to need to use our CI process to push images. #471 should take care of that.

**Comment by jstoja** [comment]
Hello guys,
Do you think it's possible to start again pushing images there?
The last one pushed is 1.9.6.
Cheers!

**Comment by cimnine** [comment]
You can use the [`ninech/netbox`](https://hub.docker.com/r/ninech/netbox) image. It's actively maintained and all new versions are pushed to Docker Hub automatically.
