### ISSUE TITLE
Full Depth devices on rear are not accessible from Rack Elevation page

### ISSUE THREAD

**Issue by eliezerlp** [digitalocean/netbox#1890]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* NetBox version:   v2.1.3

### Description
When looking at the Rack Elevations page Full Depth devices which are racked on the rear are not clickable. Also you can't see the popup with additional device details for these rear mounted devices in the Rack Elevations page. It would be nice to have these full depth devices be accessible from the front face.

I don't think the should look any different than the do currently as to be clear that they are on the rear face.

Some might even want to allow a device on the rear face that is not full depth to be clickable from the front if there is nothing racked on the front face that would block it from view.

**Comment by jeremystretch** [comment]
Only the devices mounted on the near face are clickable on any rack elevation. You need to switch to the rear view using the toggle at top right.
