### ISSUE TITLE
Adding VOIP phone numbers section

### ISSUE THREAD

**Issue by wildc4t** [digitalocean/netbox#1893]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  Python 2.7.13
* NetBox version: 2.1.2

### Description
Hi. Thank you for Netbox, first of all.
Do you plan to implement VOIP phone numbers section to keep records of phone numbers of the voip provider?  Now i see that VLANs section  is suitable for this purpose except the VID field. It must be able to take values like 000123456. All other logic like tenants, vlan groups with uniqueness of records by vid field within the group perfectly suited. Maybe optional fields with phone model and phone MAC can also come in handy. That fields can be added using current functionality of Netbox.

Thank you again. With my best regards.

**Comment by jeremystretch** [comment]
Sorry, but dial plan management is wholly out of scope for NetBox.
