### ISSUE TITLE
Add VM Count to Clusters Export

### ISSUE THREAD

**Issue by iDemonix** [digitalocean/netbox#1894]
### Issue type
[x] Feature request 

### Description
When exporting clusters to CSV or similar, one of the most useful pieces of information is the VM Count (which is included in the default Clusters table). Would it be possible to add this (and maybe host count) either to the default export, or allow it to be pulled using an export template? 

There are counts on `virtualization/clusters/1/` but not `api/virtualization/clusters/1/`, maybe it'd be worth adding the counts to this too?

**Comment by mabazyar** [comment]
Yeah, confirming, this feature makes our life a lot easier too.

**Comment by jeremystretch** [comment]
The built-in CSV export is limited to data directly associated with each object; it is essentially the complement to the CSV import approach. This does not entail statistical information such as VM/host count, however NetBox allows you to create your own custom [export template](http://netbox.readthedocs.io/en/stable/data-model/extras/#export-templates) to retrieve this information.

As for the API serializer, AFAICT the only place we currently include counts of child objects is on the site model (`count_prefixes`, `count_devices`, etc.). (And incidentally, a count of virtual machines is missing from the serializer.) I'm not against adding similar counts to Cluster and other models, but we probably want to give more thought to how that data is conveyed.

**Comment by iDemonix** [comment]
Hi @jeremystretch, are you saying it's possible to have the count of VMs (for example) in an export template? I wasn't sure if that was possible, but if it is then that's all I was aiming to request - would you mind showing an example or pointing to the docs for that?

**Comment by jeremystretch** [comment]
In the admin UI, go to Extras -> Export Templates and create a new template for "virtualization > cluster". You can do something like this to get the VM count for each cluster:

```
{% for cluster in queryset %}{{ cluster.name }}: {{ cluster.virtual_machines.count }}
{% endfor %}
```

**Comment by iDemonix** [comment]
Thanks Jeremy!

I'll close this issue as that's the exact functionality I was after. Maybe it'd be worth mentioning that counts are possible in the docs for Export Templates as it seems both me and @mabazyar missed it.
