### ISSUE TITLE
Footprint retention post a user is gone

### ISSUE THREAD

**Issue by mabazyar** [digitalocean/netbox#1896]
### Issue type
[X] Feature request 
[X ] Bug report      
[ ] Documentation 

### Environment
* Python version: 3.5.2
* NetBox version: 2.2.9

### Description
1) Add a user in Netbox
2) Make some changes as the user
3) Delete the user
All the operations done by the user are gone along the way from "recent activity", and it is impossible to track them down in future.

**Comment by jeremystretch** [comment]
What change are you proposing?

**Comment by mabazyar** [comment]
It would be nice if we could have all the activities archived in "recent activity" for both active and removed users.

**Comment by jeremystretch** [comment]
Wrapping this into #1898.

**Comment by mabazyar** [comment]
Gr8, Thanks!
