### ISSUE TITLE
Advice on how to add componenets to hardware

### ISSUE THREAD

**Issue by greavette** [digitalocean/netbox#190]
Hello All,

Great system here..thanks very much for making it available for all to use!

I'd like to be able to add to my physical servers such components as:
Disk Information (Manufacture) Size, speed, Drive bay installed, Model #, Date installed, Warranty end date)
Ram Information (Manufacturer, Speed, DIMM slot, Model #, Date installed).

And I'd like to be able to add in as a hardware my Supermicro Fat Twin Servers (https://www.supermicro.com/products/nfo/FatTwin.cfm).  These aren't blade servers, but they have individual nodes (servers) installed so being able to identify the Fat Twin box and assign a node to each box (with the details of the CPU, Ram, Disks, Nics that come with each node).

Could someone point me in the right direction here on how I can configure netbox so I can get this level of detail.  

Thank you in advance for any advice you can provide.

**Comment by peelman** [comment]
FatTwins are, for all intents and purposes, blade servers.  #91 and #51 discuss that request in more detail.

Right now there isn't really a way to document things like the CPU speed, RAM, Disks, etc.  NICs certainly (though not their MAC addresses).

I think expanding the Component details has probably been discussed, but doesn't have an issue dedicated to it yet.

Fleshing out the DCIM component into a full blown asset-management system is on my agenda, but right now that is probably a 2.0 goal and not something that will happen in the near-term.

**Comment by jeremystretch** [comment]
Going to close this as a duplicate since it's covered by the individual issues @peelman linked above.
