### ISSUE TITLE
Not all fields exportable via GUI

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#1901]
### Issue type
[x] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* psycopg2 version:  2.7.4
* NetBox version:  2.2.9

### Description
I'm not sure if this is a bug or a feature given this is just via the GUI, but non custom fields are not exported by GUI.
Example for sites export, all but shipping address, physical Address, and comments are exportable.
I understand more complete exports would likely not be via GUI, but I am just bringing to your attention.

**Comment by jeremystretch** [comment]
This should be addressed by #1714 and included in v2.2.10.
