### ISSUE TITLE
Custom IP Address Roles

### ISSUE THREAD

**Issue by djmelik** [digitalocean/netbox#1904]
Hi,

I just want to start off by saying, thank you for this fantastic software. I would like to make a feature request, and I apologize if this has been requested before.

After playing with the software and using it to document all of our sites and facilities, I discovered that the IP Address Roles are fixed. I looked through the release change-logs and it appears that it was added in release v2.1.0 (#819)

It appears that these are all fixed constants: 

IPADDRESS_ROLE_LOOPBACK = 10
IPADDRESS_ROLE_SECONDARY = 20
IPADDRESS_ROLE_ANYCAST = 30
IPADDRESS_ROLE_VIP = 40
IPADDRESS_ROLE_VRRP = 41
IPADDRESS_ROLE_HSRP = 42
IPADDRESS_ROLE_GLBP = 43
IPADDRESS_ROLE_CARP = 44

---

Can we please have the ability to create custom IP Address Roles. I think it would be great to be able to extend and customize it to our needs, I'd love to be able to assign new roles ie. EGP, IGP (OSPF, etc). I don't imagine this will be too difficult to implement as the software already allows us to create custom VLAN/Device Roles. 

Thank you for your consideration.

Best,
Melik

**Comment by jeremystretch** [comment]
> I'd love to be able to assign new roles ie. EGP, IGP (OSPF, etc).

These aren't roles in the same context as e.g. loopback or anycast. A loopback IP may be used as a BGP source IP, for instance. The association of individual IP addresses with routing protocols would extend to configuration management and is out of scope for NetBox.

**Comment by djmelik** [comment]
Ah, I see. Thanks for the clarification! 

I'll go ahead and use the prefix/VLAN roles to capture this information. 
 
Best,
Melik
