### ISSUE TITLE
Unable to remove IP address as the primary IP for a VM by editing the IP

### ISSUE THREAD

**Issue by jvanderaa** [digitalocean/netbox#1907]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  Python 3.5.2
* NetBox version:  (v2.2.10)

### Description
1) Create test VM to be used for instance (name: MYTESTVM, type: Windows)
2) Assign an IP address from an existing IP address list (in this case a reserved unused IP)
3) Edit the IP address, moving to check the box **Make this the primary IP for the device/VM**
4) Save
5) Edit the same IP address again, moving to uncheck the box **Make this the primary IP for the device/VM**
6) Save
7) The IP address is still the **Primary IPv4** entry

**Comment by jeremystretch** [comment]
Workaround: The primary IPv4/IPv6 address can be changed or removed by editing the VM directly.
