### ISSUE TITLE
Rack U numbering from top to bottom

### ISSUE THREAD

**Issue by yasa1987** [digitalocean/netbox#191]
Hello, in all our datacenters we are using Knurr racks and U numbering is from top to bottom : U01 is at top of rack and U41 is at rack bottom. In NetBox it's inverted.
Would it be possible to have an option to invert that to have U01 at top ? A 9U device starting at U02 will still end on U10 like now.

**Comment by jeremystretch** [comment]
This would require a new boolean field on the Rack model, indicating the direction of increment (keeping bottom-to-top as the default). Rack elevations should be simple to flip upside down. I think the most confusing aspect is the treatment of multi-U devices.

Currently, multi-U devices are "attached" to the lowest-numbered RU that they occupy, which is also physically lowest RU. In a top-to-bottom numbering scheme, this would be the physically *highest* RU. It should be fine if we're very clear in the documentation to always use the lowest *numbered* RU, but might still lead to confusion.

**Comment by yasa1987** [comment]
Displaying something like "U2 to U10" in "Position" field of device instead just the starting U should remove any kind of confusion. By the way it would allow to remove positions that are impossible to start at regarding device's height.
