### ISSUE TITLE
Document Creating Virtual Chassis

### ISSUE THREAD

**Issue by jvanderaa** [digitalocean/netbox#1922]
### Issue type
[ ] Feature request 
[ ] Bug report      
[x] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3

### Update Documentation on How to Create a virtual chassis
Forking and working on making the update to match what was posted in Slack channel.

**Comment by jeremystretch** [comment]
Going to hold off on this as I'm hoping to overhaul the docs pretty soon.
