### ISSUE TITLE
Interfaces on virtual chassis slave get lost when modifying interface form factor

### ISSUE THREAD

**Issue by goebelmeier** [digitalocean/netbox#1926]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.4
* NetBox version:  2.3.0

#### Reproduce
* Create top-level device (e.g. Cisco Nexus)
* Create slave device (e.g. Cisco FEX)
* Create VC with both devices
* Create Interface on Nexus
* Create Interface on FEX
* On Nexus device page you will see both interfaces
* On FEX device page you will see the FEX interfaces
* Until this point everything is expected
* Now change the interface form factor on the FEX interface
* The Nexus device will continue to show both interfaces
* The interface list on FEX device is empty <-- that's the bug

**Comment by jeremystretch** [comment]
I'm not able to replicate this behavior. After modifying the form factor of a VC member device's interface, all interfaces still appear as expected.

**Comment by goebelmeier** [comment]
I just played around a bit with that issue. Seems like it just breaks when using bulk-edit on the master device to bulk-edit interfaces on a slave device.

i.e. mark two slave interfaces checkboxes and then hit the edit button on the lower left. Then change the form factor, confirm using 'Apply' button and then change from VC master device to VC slave device and recognize the interfaces are gone. Back on to VC master the interfaces will re-appear.
