### ISSUE TITLE
Feature request: Expand available ips

### ISSUE THREAD

**Issue by loopodoopo** [digitalocean/netbox#1932]
### Issue type
[ X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description

I would like to be able to expand available ips in a prefix and then click the 'add' button for one of the ip's in that prefix. Right now I need to click the '13  ip's available' and then subtract 13 from the last ip I use to get the first one... It is doable... but a hassle. 

To improve I would like to suggest a '+' sign to expand a list of available ip's as followed: 

![561ec6c56a2ff1d4](https://user-images.githubusercontent.com/17925078/36836374-6ec17a60-1d39-11e8-81ee-2c519010898b.png)

In IPv6 you might not want to expand the whole subnet but perhaps a subset of 100 or something.

**Comment by jeremystretch** [comment]
> Right now I need to click the '13 ip's available' and then subtract 13 from the last ip I use to get the first one.

This is a link to the IP address creation form with the address initialized to the first available IP, e.g. `?address=1.2.3.97/28`. If you want to use a different IP address, just enter the desired IP in the address field.

**Comment by loopodoopo** [comment]
Hi @jeremystretch I understand that but some of my users don't necessarily understand subnetting and don't know when a subnet starts or ends. When they use your url or they alter the textbox when adding a ip they could mess up and end up in a different subnet. Exploding the view would resolve these kinds of issue.
