### ISSUE TITLE
Upgrade from 2.2.9 to 2.3.0 fails - DB error

### ISSUE THREAD

**Issue by CDawson1** [digitalocean/netbox#1933]
### Issue Type

[x ] Bug report 

### Environment
* Python version:  2.7.12
* NetBox version:  2.2.9

### Description
Unable to upgrade to 2.3.0

I've run across this issue somewhere here yesterday as a known issue, but for whatever reason, I cannot for the life of me find it now, so please feel free to whack this with a referral to the other thread.  

In short, I'm unable to upgrade from 2.2.9 to 2.3.0.  I'm met with a server/DB error.  

![netboxerror](https://user-images.githubusercontent.com/32870121/36839050-c9f37a6a-1d38-11e8-8f51-3b437e443686.png)

And running the suggested steps yields no positive result.  For the record, PostgreSQL is 9.5.10.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by CDawson1** [comment]
This is a bug...following your steps to upgrade, ([here](https://netbox.readthedocs.io/en/latest/installation/upgrading/)) that's the error.  This is not an installation assistance request...

**Comment by lae** [comment]
Are you talking about #1892? That's a different issue (that was fixed prior to release).

**Comment by CDawson1** [comment]
Nope.  Let me dig a little more.

**Comment by CDawson1** [comment]
Cannot for the life of me find it anymore.  Must have been an alternate reality.  But the reality of this is following the documentation verbatim, the upgrade fails.
