### ISSUE TITLE
Export Templates produce error

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#1934]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  2.3.0

### Description
When running an export template against the results of a device search produces the following error.

![image](https://user-images.githubusercontent.com/16985649/36848514-205e44ee-1d6a-11e8-841e-ac1343d6e5e0.png)

Example:
```
{% for device in queryset %}{% if device.status and device.primary_ip %}define host{
        host_name               {{ device.name }}
        address                 {{ device.primary_ip.address.ip }}
}
{% endif %}{% endfor %}
```

**Comment by InsaneSplash** [comment]
I have tried a number of different templates with some just displaying a name and all produce the same error. This affected 2.2.10 and 2.3

**Comment by jeremystretch** [comment]
Note: This bug is triggered only when the object type has one or more custom fields assigned to it.
