### ISSUE TITLE
Validation fails when assigning a non-global VLAN to an interface via the API

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#1935]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.0

### Description
Validation fails when attempting to assign a non-global VLAN to an interface via the API. This is due to flawed logic in the WritableInterfaceSerializer.

**Comment by lampwins** [comment]
I will also add that the currently logic does not validate the `untagged_vlan` in any way.
