### ISSUE TITLE
csv format imoprt

### ISSUE THREAD

**Issue by elJoeyJojo** [digitalocean/netbox#194]
Hello Everyone!

Great work with Netbox! I was wondering if there was a way to configure the csv format import so that it requires less fields? I want to import all the data I already manually input in Racktables into Netbox and it keeps asking for other fields that I don't feel like creating in Racktables.

This is the error: Line 1: Field(s) missing (found 2; expected 5)

Thanks

**Comment by jeremystretch** [comment]
CSV by its nature must be used a fixed number of columns, as there are no headers to identify which fields are being provided. However, some fields are optional, and can be passed empty values (which appear in the CSV data as two consecutive commas).

I'd suggest manipulating the CSV data extracted from RackTables before it's imported to NetBox. What are you trying to import?

**Comment by elJoeyJojo** [comment]
hey Jeremy,

Thanks for getting back to me so quickly! I am trying to completely get rid of Rack Tables so I'd like to move EVERYTHING over to Netbox. I will do just that. Thanks

Greetings from Canada!

**Comment by ryanmerolle** [comment]
On a side note, other tools (non-DCIM) handle this by requesting a "header" line to define the contents of the below csv data.  That way you can define the structure to be imported.
