### ISSUE TITLE
Dropdown color support for Safari

### ISSUE THREAD

**Issue by callumstrubi** [digitalocean/netbox#1940]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.1
* NetBox version:  2.2.10

### Description

Drop-down coloured lists are not supported by Safari (Desktop MacOSX High Sierra (10.13.3))

![screen shot 2018-03-02 at 09 41 43](https://user-images.githubusercontent.com/5045779/36892837-f2d2d118-1dfd-11e8-8dfc-7a70825a06da.png)

**Comment by jeremystretch** [comment]
This is not something we can control.

**Comment by callumstrubi** [comment]
Well, no it isn't if you just go with the browser's wildly different implementation of HTML, but if you use a bootstrap-happy dropdown plugin:
https://select2.org
