### ISSUE TITLE
Upgrade to 2.3.1 dependency installation failed

### ISSUE THREAD

**Issue by cyberjacob** [digitalocean/netbox#1942]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.3
* NetBox version:  2.3.1

### Description
Upon upgrading to v2.3.1, the `upgrade.sh` script attempts to install `django-timezone-field` via pip, which fails with the following error:

```
Building wheels for collected packages: django-timezone-field
  Running setup.py bdist_wheel for django-timezone-field ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lezrwjdr/django-timezone-field/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2ox2t6rppip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for django-timezone-field
  Running setup.py clean for django-timezone-field
Failed to build django-timezone-field
```

Installing wheel with `pip install wheel` before running the upgrade script resolves the issue.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
