### ISSUE TITLE
VLAN assignments to Virtual Machines

### ISSUE THREAD

**Issue by millijuna** [digitalocean/netbox#1944]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3 
* NetBox version:  2.3.1 

### Description
The new VLAN to interface assignment is great, but it would complete the picture if I could assign VLANs to the interfaces of Virtual Machines. In my virtual environment, I have some VMs that are on a number of different VLANs (PacketFence comes to mind).

**Comment by jeremystretch** [comment]
Will work on this in conjunction with #1952
