### ISSUE TITLE
Easier upgrading documentation

### ISSUE THREAD

**Issue by goebelmeier** [digitalocean/netbox#1946]
### Issue type
[ ] Feature request 
[ ] Bug report      
[X] Documentation   

### Environment
* Python version: 3.6.4
* NetBox version: 2.3.1

### Description
I think it's better to replace `ln -sf netbox-X.Y.Z/ netbox` with `ln -sfn netbox-X.Y.Z/ netbox` in the upgrading documentation. Otherwise, the existing directory symlink won't be updated. Furthermore i would suggest to change from absolute to relative paths below the symlink update. This leads to easier copy & pasteable strings if netbox is not installed in `/opt`

**Comment by jeremystretch** [comment]
Closed in #1947
