### ISSUE TITLE
VC Member additon error.

### ISSUE THREAD

**Issue by DirtyCajunRice** [digitalocean/netbox#1948]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version:2.3.1

### Description
When adding a device to an existing VC, It is unpacking multiple values, and erroring out.
![image](https://user-images.githubusercontent.com/15788890/36988241-0971d0b4-2064-11e8-8436-1e88c80f060b.png)
![image](https://user-images.githubusercontent.com/15788890/36988279-1d7713a8-2064-11e8-8e1d-f1ecf32cb475.png)
![image](https://user-images.githubusercontent.com/15788890/36988287-245b9cd4-2064-11e8-99f6-e9b63ab0c7ef.png)

**Comment by arusso** [comment]
I'm also seeing this on a fresh installation w/Netbox 2.3.1 and Python 3.6.4

**Comment by arionl** [comment]
I'm seeing the same error. The steps to reproduce for me are:
* Create new VC with a single parent device (I specified it as 'position 0')
* Navigate to parent device details view and click "Add Member" to Virtual Chassis section
* If I try to add any additional device on the "Add New Member" screen, I get the `validate_vc_position` error above
