### ISSUE TITLE
Nagios Configuration?

### ISSUE THREAD

**Issue by elJoeyJojo** [digitalocean/netbox#195]
Hello Everyone!

Great work with Netbox! I really like the interface! Now to my question, is there anyway that Nagios can work with Netbox? I already have all our devices monitoring with Nagios Core and all the devices are already defined with IPs and what not. Anything that can work with Nagios? Just a question.

Thanks

**Comment by jeremystretch** [comment]
You can define custom export templates in NetBox to generate configuration files for other applications using NetBox data. The [documentation](https://github.com/digitalocean/netbox/blob/develop/docs/extras.md) provides this example for Nagios:

```
{% for d in queryset %}{% if d.status and d.primary_ip %}define host{
        use                     generic-switch
        host_name               {{ d.name }}
        address                 {{ d.primary_ip.address.ip }}
}
{% endif %}{% endfor %}
```
