### ISSUE TITLE
Virtual interfaces to VC

### ISSUE THREAD

**Issue by PeepOks** [digitalocean/netbox#1950]
### Issue type
[x] Feature request 
[ ] Bug report 
[ ] Documentation

### Environment
* Python version:  2.7.5
* NetBox version: 2.3.1

### Description
We would like to have ability to assign virtual interfaces with IP to Virtual Chassis. 
For example reth interfaces for SRX chassis clusters and VLAN interfaces for Cisco stacks. These interfaces are shared between all members of virtual chassis but are active only on master device.
If I would assign IP to that virtual interface then it should be assigned to only to virtual chassis master device. When I change master device of VC then assigned IP should show that it is assigned to new master device.

**Comment by jeremystretch** [comment]
> These interfaces are shared between all members of virtual chassis but are active only on master device.

Like physical interfaces, virtual interfaces from all VC members are included in the interfaces list when viewing the VC master device.

> If I would assign IP to that virtual interface then it should be assigned to only to virtual chassis master device. When I change master device of VC then assigned IP should show that it is assigned to new master device.

I'm sorry, I don't follow what you're proposing.

**Comment by PeepOks** [comment]
Overall I would like netbox to show in which device virtual interface is really active and forwarding packets.
Currently if VC has been configured and when I add new virtual interface to it then it will be assigned to one of VC member. 
I would be more reasonable if new virtual interface would be added to VC master device(if device is member of VC). If VC master changes then virtual interface relation to device should also change.
This info would help in network troubleshooting if I would know where some interface or IP are active in.

I did my test scenario like this. I added 2 devices to new VC. Under VC(selected VC master) I added new virtual interface. Then I changed VC master device. 
Next if I add VIP IP to virtual interface then it would be assigned to backup device. This results to that VIP IP is assigned to VC backup device.

**Comment by jeremystretch** [comment]
The recommended approach is to create virtual interfaces only on the master device. Changing the master device for a VC seems like too infrequent an action for it to warrant the additional (and potentially dangerous) logic needed to automatically reassign interfaces, but I'll leave this open for feedback.

**Comment by PeepOks** [comment]
Yes, that's true about infrequent master device changes with switches when they are formed into VC.
I try to apply VC logic also to firewall-routers (SRX, PaloAlot etc.) and other network equipment what are configured to work in HA configuration mode. There are master/active member changes more frequent.
Maybe I have misunderstood VC concept in netbox and it where ment to be used only for switches

**Comment by DanSheps** [comment]
> it where ment to be used only for switches?

I think it is only meant for "Stacked switches" really, as I don't see it working well for something like vPC either, where you have individual interfaces on each device and a shared IP via HSRP.

**Comment by PeepOks** [comment]
If VC is ment mostly for switch stacks then I really hope in future we would get better support for HA configurations in routers and firewalls. It's pretty common to have some sort HA setup in production environments.

**Comment by jeremystretch** [comment]
A virtual chassis represents a set of devices which share a single control plane. Whether something like an SRX cluster qualifies is debatable, but that debate is best held on the mailing list. Closing this out as there is no action to take.
