### ISSUE TITLE
Add availability status to PDU ports

### ISSUE THREAD

**Issue by raddessi** [digitalocean/netbox#1954]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.2 
* NetBox version: 2.2.9 

### Description
It would be nice if we could mark some ports on a PDU as Active/In Use even if we don't have a device in netbox connected to it.

The default state could still be Available of course so normal workflow would not change but if there is some device not in netbox or if a port is unusable for some reason it can be marked as such.

**Comment by jeremystretch** [comment]
This would undermine the purpose of modeling power connections. If a PDU outlet is in use, the connected device needs to be added in NetBox.
