### ISSUE TITLE
Worklist overview/request

### ISSUE THREAD

**Issue by deku-m** [digitalocean/netbox#1958]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.1

### Description
At our location we have a patch team. People go to the SERs/Racks and make the patch between the switch and patchpanel. We will give them a worklist with the patches that needs to be made and they will patch it. Is it possible to generate a worklist for those people for example the planned connection in a overview?
Worklist Overview:
- (from) rack/switchname + interface
- (to) rack/switchname + interface 
- (User) Who made the planned interface connection.

Worklist-request:
Maybe to expand it futher and make it possible to let users make a request for patches so that they are set to the worklist overview? What needs to be filled in a form could be: 
- switchname
- patch on the patchpanel
- endpoint
- reason?	
- contact information?

If you make a worklistform then the setup of the overview would change a bit and you will only get the filled formfield on the worklistoverview.

But yes this could be a request that maybe change the concept of netbox a bit.

**Comment by jeremystretch** [comment]
We are not currently accepting requests for major new features due to an excessive backlog. (This would be blocked by #20 anyway.)
