### ISSUE TITLE
Can't assign VLANs to interfaces

### ISSUE THREAD

**Issue by patrick7** [digitalocean/netbox#1960]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.13-2
* NetBox version: 2.3.1

### Description
I select VLANs which should be tagged on the interface and click Update. Netbox complains "Select a valid choice. X is not one of the available choices."

**Comment by Armadill0** [comment]
I can confirm that.

**Comment by jeremystretch** [comment]
This was resolved as part of the work on #1952.

**Comment by scotty00X** [comment]
Hi,
I have the latest commit from release v2.3.1including the merge pull request #1937 running. But I still observe the same behavior
![image](https://user-images.githubusercontent.com/37411806/37519201-880d3cd0-2918-11e8-92d2-fa8dd9bad204.png)

Regards,
Henrik
