### ISSUE TITLE
An identical virtual-cluster name in different sites

### ISSUE THREAD

**Issue by mabazyar** [digitalocean/netbox#1963]
### Issue type
[] Feature request 
[X] Bug report     
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version:  v2.3.1

### Description

Seemingly, there is no way to have an identical virtual-cluster name in different sites.

How to reproduce the error:
1) Go to virtualization > clusters 
2) push "Add" button
3) Create a new cluster under name "test" located in site "testlocation1"
4) Repeat step #1 and #2
5) Create a new cluster under name "test" located in site "testlocation2"

In this use case, the following error comes up:
Cluster with this Name already exists.

**Comment by jeremystretch** [comment]
There's a strong parallel between this and #238, which addresses a similar restriction on racks/groups.

**Comment by jeremystretch** [comment]
Folding this into #1943
