### ISSUE TITLE
Example of importing devices connection

### ISSUE THREAD

**Issue by gustavo-peres** [digitalocean/netbox#1964]
[X] Documentation   

### Environment
Python 3.5.3
Netbox v2.3.1

### Description
Can you add some examples of how to do some features?
I'm having trouble to add interfaces connections, when I try to connect two devices I receive an error message that I don't know where to go. Example:

In Interface Connection Import:

I've tried this sintax:

device_a,interface_a,device_b,interface_b,connection_status
"Core B",ten-2/3/0/1,"Switch 1",Ten-0/0/27,Connected

And I receive this message:

Row 1 interface_a: Invalid interface (Core B ten-2/3/0/1)

PS: I have copied the interface from the device. Probably I'm missing something, can you help me?

**Comment by gustavo-peres** [comment]
I saw now what was the problem I was trying to connect a port on the device bay to a interface in another device. This type of connection is possible? If so, how? Can you show me an example?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
