### ISSUE TITLE
Having more than 64 characters in virtual-machine-name field

### ISSUE THREAD

**Issue by mabazyar** [digitalocean/netbox#1965]
### Issue type
[X] Feature request 
[] Bug report     
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version:  v2.3.1

### Description
It would be great if the virtual-machine-name length could be bumped up to 100 to support super-long FQDNs.

Putting more details, I face the following API error for such use cases.

```
"name": ["Ensure this field has no more than 64 characters."]
 ```

**Comment by jeremystretch** [comment]
The name field is only for the VM's hostname, not its entire FQDN. 64 characters is sufficient for this purpose. Any implementation of a domain info would fall under #166.

**Comment by kartiksubbarao** [comment]
I don't see how you can add VMs named **test.domain1.example.com** and **test.domain2.example.com** into Netbox if you only use the hostname portion of the FQDN. Once you added the first one as 'test', Netbox would not allow you to add another VM named 'test'.

I think it would be highly valuable if Netbox tolerated FQDNs in the name field and correspondingly increased the name length to 255 (as per RFC 1035).
