### ISSUE TITLE
Having 2 VMs with the same name in 2 different clusters

### ISSUE THREAD

**Issue by mabazyar** [digitalocean/netbox#1966]
### Issue type
[] Feature request 
[X] Bug report     
[ ] Documentation   

### Environment
* Python version: 3.5.2
* NetBox version:  v2.3.1

### Description
A possibility which should be in place is that representing 2 VMs with identical name in two different clusters.

1) Go to Virtualization > Virtual Machines
2) Create a VM as "test" in cluser "testcluster1"
3) repeat step1
4) Create a VM as "test" in cluster "testcluster2"

It returns:
```
Virtual machine with this Name already exists.
```

**Comment by jeremystretch** [comment]
Like devices, each virtual machine must have a unique name. Removing this constraint would make it very difficult to unique identify virtual machines with the same name from one another. For example, importing IP addresses to be assigned to virtual machines would require specifying the name of each cluster as well as the VM itself.

**Comment by mabazyar** [comment]
Of use-cases is having a failover cluster contains idetntical VM instances to take over the traffic as needed. It can not be represented in Netbox.

**Comment by pm17788** [comment]
I'd like to second that - we run into this issue as well. Currently, I have to cheat a bit and append various things to the name of the VM to reconcile this, but that's clearly not a clean solution.

**Comment by mhmaw** [comment]
We would like this functionality changed aswell. Both our hypervisor platforms allows duplicate names, as these are just labels. VMs are identified by GUIDs instead.
And when there's customer selfservice access to these environments, the chance for multiple VMs called fx. SQL01 increases.

**Comment by Grokzen** [comment]
We solved this issue internally by adding 2 custom fields, hostname and dnsname. Then we use the name field as more of an asset-tag with the unique name constraint and we can set the same hostname and dnsname for different machines that belongs to different cluters.

**Comment by jeremystretch** [comment]
I'm going to wrap this into #2669, since I think it makes sense to ultimately ensure we have a consistent approach to both devices and VMs. I believe we're leaning toward simply removing the uniqueness constraints on device and VM names.
