### ISSUE TITLE
Feature Req: Possibility to define bridges and other virt. ifaces and attach these to LAGs, ...

### ISSUE THREAD

**Issue by scotty00X** [digitalocean/netbox#1972]
**Issue type**

[x] Feature request
[ ] Bug report
[ ] Documentation 

Hi,
I like to submit the following feature request:
- more specific virtual interfaces types aka 'Form Factor' for bridges, vlan other than the provided 'other'-type
- the possibility to attach these to a parent interface. Right now it is possible only to attach to 'Parent LAG'
- to connect LAGs to each other for documentation / visualization

Perhaps a picture says more ...
![netbox-define-bridge-on-lag](https://user-images.githubusercontent.com/37411806/37518580-08d64b5c-2916-11e8-838d-dd8ec745ded3.png)

Kind regards,
Henrik

**Comment by jeremystretch** [comment]
From [the contributing guide](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md):

> Good feature requests are very narrowly defined. Be sure to thoroughly describe the functionality and data model(s) being proposed. The more effort you put into writing a feature request, the better its chance is of being implemented. Overly broad feature requests will be closed.

Please modify your issue to address only one specific feature request.
