### ISSUE TITLE
Can't assign VLANs to interfaces - still not fixed?

### ISSUE THREAD

**Issue by scotty00X** [digitalocean/netbox#1974]
**Issue type**

[ ] Feature request
[x] Bug report
[ ] Documentation 

Hi,
I have the latest commit from release v2.3.1including the merge pull request #1937 running. But still I observe the same behavior as mentioned and fixed in #1960 
![image](https://user-images.githubusercontent.com/37411806/37519623-13b02f44-291a-11e8-8df7-121bdf897729.png)
Regards,
Henrik
P.S.: I've posted this msg to the closed #1960 also

**Comment by jeremystretch** [comment]
Please wait for v2.3.2 before re-opening this.

**Comment by scotty00X** [comment]
Ok, THX for the feedback.

**Comment by jkldgoefgkljefogeg** [comment]
Currently on 2.3.4 adding vlan to all tagged trunk is still not working. After update on Editing interface page (select vlan), vlan is not being added to the interface

**Comment by DanSheps** [comment]
Have you tried just the "tagged" setting?
