### ISSUE TITLE
Allow Clusters to span multiple sites

### ISSUE THREAD

**Issue by kasimon** [digitalocean/netbox#1976]
### Issue type
[X] Feature request

### Environment
* Python version:  2.7.13
* NetBox version:  2.3.1

### Description
We are running virtualization clusters that span several sites, which we currently can not elegantly represent in netbox. So if there is sufficient demand, we would be happy if the ability to assign multiple sites to a cluster could be added to netbox. Another possibility would be to completely rely on the site information provided by the cluster host devices and just display those.

**Comment by unixhaj** [comment]
We are not using netbox yet (but are looking into it), we are also planning on Stretch Clusters (using VMware) in the near future, so this change would be very welcome.

**Comment by jeremystretch** [comment]
This would conflict with #1943, which would allow for non-unique cluster names in different sites.

**Comment by jeremystretch** [comment]
Closing this out as it would greatly complicate the data model. Please note that the assignment of a cluster to a site is completely optional.
