### ISSUE TITLE
Can't add Tagged VLANs from different "VLAN group"

### ISSUE THREAD

**Issue by GitRost** [digitalocean/netbox#1979]
### Issue type
[X] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 2 
* NetBox version: 2.3.1  

### Description
When "Editing interface" can't add Tagged VLANs from different "VLAN group"

**Comment by jeremystretch** [comment]
This will be addressed in the v2.3.2 release.
