### ISSUE TITLE
Adding 802.1x Radius VLAN as 802.1Q Mode

### ISSUE THREAD

**Issue by cyberlu** [digitalocean/netbox#1986]
### Issue type
[X] Feature request
[ ] Bug report
[ ] Documentation

In our environment we have 802.1x with radius authentication.
It would be good if we had an option to add "802.1x" under "802.1Q Encapsulation" -> Mode 
as in our scenario no unath VLAN is selectet the Port of the Switch is in no VLAN if the client cannot authenticat. The Client will be in one of the VLAN's depending on its Group. (no need to display this in Netbox)
In other cases (not our environment) when you select an UNAUTH-VID there should be an option to combine the Mode: 802.1x with a Untagged VLAN.

To display the VLAN-Tagging on the switch i already added to another post (This would be the best way to Display the VLAN participation in my opinion): https://github.com/digitalocean/netbox/issues/1945 

The 802.1x would be displayed with an X instead of U for Untagged or T for Tagged.

Short Summary:
Please add under 802.1Q Encapsulation the Mode 802.1x and give the possibility to chose an Untagged VLAN for unauthorized Clients (use de Untagged VLAN Dropdown)

This should be easy to implement as it is just one entry more under 802.1Q Mode and with a little more work we could even get the unauthorized Untagged VLAN

With this implemented Netbox could hold the Data as we have it in our Running Config of our Switches.
We have Switches with clients and Access Points:
Port 1-20 is on 802.1x where Radius decides what VLAN will be used. Port 21 is fix Tagged to a few VLANs for the Access Point.

### Environment
* Python version: 3.5.2
* NetBox version: 2.3.1

**Comment by jeremystretch** [comment]
There isn't anything special about a VLAN used for 802.1X; it's just another tagged VLAN on the interface. You can use a different mechanism, such as a custom field or object tag (#132) to identify 802.1X VLANs for configuration rendering.
