### ISSUE TITLE
Add 2-Factor Authentication to netbox

### ISSUE THREAD

**Issue by wenners** [digitalocean/netbox#1989]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  2.3.2

#### A detailed description of the proposed functionality
Add 2FA to netbox. Users should be able to log in securely by utilizing 2FA. Most commenly this would be a software generator for TOTP like Google Authenticator.  It should also be possible for the Admin to enforce site-wide 2FA authentication, depending on the own paranoia / security demand.

#### A use case for the new feature
Netbox is holding the most crucial information about the site-wide infrastructure in the DC. This is very valuable information and should be protected and kept as secure as possible.
2FA will add an additional layer of security-

#### A rough description of any necessary changes to the database schema
No idea...

#### Any relevant third-party libraries which would be needed
Googling around I came across https://github.com/Bouke/django-two-factor-auth which is already a complete information of 2FA for Django which should fit very nicely to netbox. Reading through the documentation seemed like it should be no rocket-science to integrate this into netbox

**Comment by wenners** [comment]
Sorry - I missed in my initial search #118 but it looks like there the mentioned framework for Django was back then not taken into consideration/not available. Please have a look at it, if that would be a feasable way for 2FA.
Thanks
Sebastian

**Comment by LukeRussell** [comment]
https://github.com/digitalocean/netbox/issues/1677 would allow you to implement the MFA at the SAML provider, keeping Netbox out of it.

**Comment by kkirsche** [comment]
I'd recommend including support for universal second factor (U2F) to support hardware tokens such as the Yubikey. Today, U2F works with a number of publicly available and business-use services such as Google, Salesforce, Dropbox, Github, Gitlab, and Bitbucket accounts. As a result, having support for U2F would allow Netbox to integrate well with environments leveraging the extra security of hardware tokens

**Comment by jeremystretch** [comment]
Folding this into #2328.
