### ISSUE TITLE
Ability to clone entire sites

### ISSUE THREAD

**Issue by RustyBower** [digitalocean/netbox#1994]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

Similar to #33 and #1849, it would be nice to have the ability to clone an entire site. For instances where the same IP/hardware exists for a site (in my case a mobile rack), it would be super handy to be able to duplicate that configuration as many times as necessary.

**Comment by jeremystretch** [comment]
I don't think this is feasible to implement. You would have to contend with automatically renaming and renumbering myriad objects: racks, devices, prefixes, VLANs, IPs, circuits, etc. A non-trivial amount of additional logic is needed in the form of a renaming/renumbering policy, which NetBox cannot provide on its own. It would be much more practical to script out your own unique logic for replicating a site using either the REST API or local ORM.

**Comment by Yakelixir** [comment]
Agreed. I wrote something a bit back to help with nuke and pave of any instance since i didn’t see that out there and the structure of the data wouldnt allow this easily.
