### ISSUE TITLE
Rack view import/export?

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1995]
Issue type:

[x] Feature request
[ ] Bug report
[ ] Documentation

Environment:

Python version: 2.7.5
NetBox version: 2.3.2

Description:

As planning a rack setup involves multiple parties (asset, capacity, customer, ISP, etc) then it's easier (also due lack of possibility to limit access for some user for some rack only) to use offline excel sheet for rack planning. It's very convenient to design rack configuration in excel, change devices etc, calculate space, power and preserve the rack overview. So please add human readable excel sheet rack view import option. Also please add human readable rack view export to pdf and excel sheet also.

**Comment by jeremystretch** [comment]
NetBox already provides CSV import/export for devices, which enables exactly what you describe. If you'd like any assistance using this feature, please post on the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
