### ISSUE TITLE
Rack devices ordering drag and drop support?

### ISSUE THREAD

**Issue by ksuuk** [digitalocean/netbox#1996]
Issue type:

[x] Feature request
[ ] Bug report
[ ] Documentation

Environment:

Python version: 2.7.5
NetBox version: 2.3.2

Description:

Rack devices add & edit. Please add rack devices ordering drag and drop ajax support.

**Comment by jeremystretch** [comment]
Duplicate of #124. This won't be revived any time soon as we have a huge backlog of more pressing features to implement.
