### ISSUE TITLE
Edit description field for sites missing

### ISSUE THREAD

**Issue by Ikke** [digitalocean/netbox#1999]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6.3
* NetBox version:  2.3.1

### Description

On the page to edit a single site (dcim/sites/\<sitename>/edit/), there is no form field to edit the description of the site.

It is possible to set the description using bulk update, but the next time you edit the site individually, it will be empty again.

**Comment by jeremystretch** [comment]
Whoops, how did that happen?
