### ISSUE TITLE
Import Virtual Machines with Interfaces and IP's

### ISSUE THREAD

**Issue by speedyrazor** [digitalocean/netbox#2001]
Hi, I want to import 100+ Virtual machines. I have a CSV which includes all the info for each VM, including IP's. My question is related to, what is the easiest and correct way to import al these VM's, Interfaces with IP's please?

Kind regards.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
