### ISSUE TITLE
Custom attribute for uploading service history for devices

### ISSUE THREAD

**Issue by GMAzrael** [digitalocean/netbox#2004]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  
### Description
Having the ability to attribute a log of work done to devices with an upload or templatized documentation format (RST/Markdown etc.) would be handy. 

Use case 1. Bob uploaded a configuration change to a switch. His change management process dictates he have a document in txt format that shows the before and after configuration changes for the change. The document upload is timestamped. After making the change, Bob wants to see when the system changed prior to that one. 

Use Case 2. Jim is having a number of problem with a Server. Thinking back, he know a manufacturer technician has worked on a system a number of time. He logs in to NetBox and looks at the service history. He sees a number of parts have been replaced in the last 3 months. Recommends a replacement for the next time the system fails. 

Implimentation:

The ability to add an uploadable field for a device, similar to the media section for rack/device images. History is tracked by device ID and timestamped with the upload date. Files are some flavor of text base for small size.

**Comment by jeremystretch** [comment]
Sounds like this would be covered by #151
