### ISSUE TITLE
NAPALM Integration Bug

### ISSUE THREAD

**Issue by BlyatFirmeza** [digitalocean/netbox#2008]
When i try to do

> pip3 install napalm

it gives this output:

```
Collecting napalm
Downloading napalm-2.3.0.tar.gz (147kB)
100% |████████████████████████████████| 153kB 2.3MB/s
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "/tmp/pip-install-h1r3rl6y/napalm/setup.py", line 6, in 
from pip.req import parse_requirements
ImportError: No module named 'pip.req'

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-h1r3rl6y/napalm/

```
It is a fresh install so i don't know what is missing.
Both Python3 and Python2 are in the newest versions and i have installed both the old.requirements.txt and requirements.txt
 
Can someone give me a quick answer so i don't have to wait 10days in the group.google chat? Thank you

**Comment by jeremystretch** [comment]
This is not a NetBox issue. Please raise the issue with the NAPALM maintainers.
