### ISSUE TITLE
Add Site and Rack attributes to multiple device edit

### ISSUE THREAD

**Issue by dmcarmo** [digitalocean/netbox#2009]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2 
* NetBox version:  2.3.1 

### Description

When editing multiple devices there are no fields to change the Site and Rack attributes.
I added the following code to the _DeviceBulkEditForm_ class in _dcim\forms.py_ on my netbox install and it seems to have fixed it:

`site = forms.ModelChoiceField(queryset=Site.objects.all(), required=False, label='Site')`
`rack = ChainedModelChoiceField(queryset=Rack.objects.all(), required=False, label='Rack')`

**Comment by jeremystretch** [comment]
I'm not sure it makes sense to reassign site and rack in bulk. Additional logic would be needed to 1) validate the rack assignment, and 2) erase any existing rack face/position assignments. The potential for opaque destruction of data in this manner makes this unappealing IMO.

**Comment by dmcarmo** [comment]
I understand. Didn't thought about those points so my changes were very short and simple.
How should I move multiple devices to a single rack or to a different site?

**Comment by jeremystretch** [comment]
Doesn't look like anyone came up with a better alternative that will preserve the existing validation logic. Closing this out.
