### ISSUE TITLE
Implement pluggable extensions

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#201]
Similar to #81 except rather than hooks that fire on events, have modules that extend the systems capabilities internally.

For those of you familiar with WHMCS you can write your own custom modules/reports/etc that are available within the platform using it's data.

This would allow netbox users to self extend the functionality in almost endless ways and help alleviate the demand on the devs so they can focus on the core.

**Comment by jeremystretch** [comment]
Closing this as it's not something we're likely to implement in the near future.
