### ISSUE TITLE
BUG on NAPALM [FIX IN DESCRIPTION]

### ISSUE THREAD

**Issue by BlyatFirmeza** [digitalocean/netbox#2010]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2 
* NetBox version: 2.3.2 

### Description

By using pip 10 you CAN'T INSTALL NAPALM
You have to downgrade it to atleast pip version 9
``sudo pip install pip==9``

Once you do that you are able to install napalm just make sure to run it with ` --no-cache-dir`

**Comment by jeremystretch** [comment]
See #2008
