### ISSUE TITLE
Bug report while using NAPALM

### ISSUE THREAD

**Issue by BlyatFirmeza** [digitalocean/netbox#2011]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5
* NetBox version:  2.3.2

### Description

I'm getting a error with netbox while using napalm and I think its origin comes from [Netmiko](https://pynet.twb-tech.com/blog/automation/netmiko.html). 
Is it required to install Netmiko in the switch or as a intermediate SSH server for it to work properly?
I'm completly in the dark here, if someone could help i would be very much obliged

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
