### ISSUE TITLE
VLAN Groups enhancement - Allow assignments of VLANs to multiple groups

### ISSUE THREAD

**Issue by jsenecal** [digitalocean/netbox#2013]
### Issue type
[X] Feature request
[ ] Bug report
[ ] Documentation

### Environment
* Python version:  Python 3.5.2 
* NetBox version:  Develop branch [07364ab](https://github.com/digitalocean/netbox/commit/07364abf9e9ff193bad49b790e657382cf186f0c)

### Description
It would be great if it was possible to assign a vlan to multiple groups. This would allow for more efficient filtering when assigning vlans to interfaces in the UI and better grouping of such vlans for documentation purposes.

For instance, I can have vlan "Data(10), Voice(11)" assigned to the "Firewall" Vlan group but then, the same vlans are later grouped along with different Vlans on a "Switches" Vlan group. I.e: Along with "Security(20)"

[ipam/models.py#L562](https://github.com/digitalocean/netbox/blob/develop/netbox/ipam/models.py#L562) should be replaced to a ManyToMany relationship and relevant forms modified to allow this.

Makes sense?

**Comment by jeremystretch** [comment]
Groups are used to enforce uniqueness among VLAN IDs. For example, a group cannot have two VLANs with VID 100. Allowing a VLAN to be assigned to multiple groups would remove (or at best greatly complicate) this functionality.

**Comment by jsenecal** [comment]
I do not see why this ability could prevent or complicate the enforcement of uniqueness among VLAN IDs in a group as the uniqueness in any group would still be a requirement, the added feature only enables one tho have a specific VLAN object available to be made member to more than one group.

Maybe my explanation was not clear enough, I could work on a PR and submit it for evaluation ?

**Comment by clinta** [comment]
To bump this, here's the usecase where I would like this feature.

We have two datacenters with a layer 2 connection between them. VLAN groups can enforce unique VLANs inside each datacenter. But the one VLAN that holds the cross datacenter connection must not conflict with VLANs in either datacenter, so it would be useful if this VLAN could exist in both groups.
