### ISSUE TITLE
Unable to set untagged/tagged VLANs for VM interfaces through API

### ISSUE THREAD

**Issue by ppmathis** [digitalocean/netbox#2014]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.3 
* NetBox version: 2.3.2 

### Description
When trying to update the untagged or tagged VLANs of a virtual machine interface through the API, the request fails with an internal server error. This can be easily replicated in pynetbox, e.g.:

```python
iface = nb.dcim.interfaces.get(<ID of Virtual Machine Interface>)
iface.untagged_vlan = <ID of valid VLAN>
# or: iface.tagged_vlans = [<VLAN ID 1>, <VLAN ID 2>, ...]
iface.save()
```

The reason behind this can be easily found within the [source code](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/api/serializers.py#L732-L749), where the newly assigned VLANs are being compared against **device.site** - however in case of a virtual machine interface, the **device** attribute is always None, which leads to **AttributeError: NoneType object has no attribute site**.

**Comment by vink78** [comment]
I've the same issue with the webui.

For the REST API, I've a partial fix here  https://github.com/vink78/netbox/commit/619100e3d563b373b942d1f75d02393ff20e8d3d using virtualization/interfaces instead of dcim/interfaces (no validation check)

**Comment by jeremystretch** [comment]
> The reason behind this can be easily found within the source code

That links to the DCIM interface serializer. VM interfaces utilize a different set of serializers. As @vink78 points out, the `mode`, `untagged_vlan`, and `tagged_vlan` fields are missing from the virtualization serializers.

> I've the same issue with the webui.

This would need to be addressed under a separate issue.
