### ISSUE TITLE
IPAM - Prefix - Edit 

### ISSUE THREAD

**Issue by LordBoBCUP** [digitalocean/netbox#202]
Error when trying to edit a prefix/VLAN role. Normal error message: There was a problem with your request. This error has been logged and administrative staff have been notified. Please return to the home page and try again. Reverts you to the homepage. Delete is working so able to edit, but requires reassigning role for each prefix.

**Comment by bellwood** [comment]
Dupe of #140 ?

**Comment by LordBoBCUP** [comment]
Sorry, missed the 1.1.0 dev release, verified as working on that.
