### ISSUE TITLE
Implementation of VLAN in interface table

### ISSUE THREAD

**Issue by BlyatFirmeza** [digitalocean/netbox#2025]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.5.2  
* NetBox version: 2.3.2 

### Description

When seeing the interfaces on the device, you can't see the VLAN they are attributed to, a simple header in the table would allow for the person to view what VLAN is the interface connected to.

Example:
[IMGUR](https://imgur.com/KzjVt0y)

**Comment by pm17788** [comment]
I think issue #2060 is related?

**Comment by BlyatFirmeza** [comment]
Yes, it seems that for now you going to have to manually edit the Description field

**Comment by carwyn** [comment]
vlanS (plural) along with aggregation (e.g. LACP) would be useful.

That said when you get to this level it may arguably be better to pull this from switch APIs or integrate with config management tools (e.g. Ansible).

**Comment by Ichabond** [comment]
LACP associations are already shown in both the API as well as the UI

**Comment by jeremystretch** [comment]
The v2.4 release will include an interface view which includes all assigned VLANs and IP addresses. VLANs aren't included in the device interfaces list because the table is busy enough as it is.
