### ISSUE TITLE
IP Address Comment Field

### ISSUE THREAD

**Issue by rml596** [digitalocean/netbox#2026]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2 
* NetBox version: 2.3.2 

### Description
I would really love to be able to add comments to IP addresses, IP history, and other characteristics. I realize its possible to add this to devices the IPs are linked to, but I want it on the IP, not the device.

Use case: entering the FQDN on linked to an IP address (although this might be its own attribute in itself), adding contact info for said IP, or anything else someone would do in a comment section
Database schema: While I don't know the ER diagram of the database, I would assume there is an IP object with attributes such as description, just add a comment attribute to that.

This would be an awesome feature! Please add it!

**Comment by jeremystretch** [comment]
The IP address model already includes a description field. Comments are intended to include lengthy free-form text, which is generally not necessary for individual IP addresses. You could add a custom field for storing FQDN information, but also see #166.
