### ISSUE TITLE
add another Parent Layer to Parent/Child Construct?

### ISSUE THREAD

**Issue by vandlol** [digitalocean/netbox#2030]
Currently on v2.3.2

Would it be possible to add another Parent Layer to Parent/Child Construct?

I have Chassis housing 12 Blades - each Hosting 2 Nodes but sharing 1 Management Interface.
No clue how to manage this without loosing my Management Interface.

**Comment by jeremystretch** [comment]
You can just collapse the middle layer and show a single chassis with 12 child devices.

**Comment by vandlol** [comment]
So you tell me to just loose half of my devices? Not the smartest move in my opinion...
