### ISSUE TITLE
Interface numbering

### ISSUE THREAD

**Issue by deku-m** [digitalocean/netbox#2035]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2 
* NetBox version:  2.3.2 

### Description
Im not sure if it is a feature request or a bug so i posted it under feature.

When adding interfaces to a device and you use numbering for example only numbers  [1-20] or more. It shuffles the interfaces when sorted. 1/10/2/20/4/5/6/7/8/9/11/12/13/14/15/16/17/18/19. The 10 and 20 are then behind the 1/2. This is with using alphabetical or slot/position. When using text in front you dont have the problem. But when using for example a patchpanel and only use numbering. It doesnt sort it right on numbering.

**Comment by rml596** [comment]
Yes, I have seen this also in Rack numbering, I had to renumber the Racks to 01, 02, etc. Not the end of the world, but annoying none the less.

**Comment by bellwood** [comment]
Welcome to the ~~joys~~ hell that is nat sorting

**Comment by jeremystretch** [comment]
Wrapping this into #2165. We should include a test for this specific use case.
