### ISSUE TITLE
Device-Type update towards devices

### ISSUE THREAD

**Issue by deku-m** [digitalocean/netbox#2036]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.2

### Description
When updating the device-type the devices that use the device-type are not updated. Is this possible to implement when changing a value in the devicetype. As we use it mainly as "templates" for different devices. When changing one value it doesnt push the update towards the devices. Could be usefull when you have multiple devices with the same template and when adding interfaces in the device-type instead at the devices itself. You will then update all devices.

**Comment by bdlamprecht** [comment]
If you look at the documentation [here](http://netbox.readthedocs.io/en/latest/data-model/dcim/#component-templates) in the blue "Note" section, you'll see that this is not possible once the `device` has been created.

I think I asked for the same thing or some type of "template hierarchy" this past summer (2017), but there were more pressing needs that needed to be addressed so I never pushed the issue.

**Comment by jeremystretch** [comment]
> When updating the device-type the devices that use the device-type are not updated.

This is not practical to implement as it presents huge potential for ambiguity. For example, when you delete an interface named `eth0` from a DeviceType, should NetBox also delete it from all instances of that DeviceType? Or should it silently ignore those? Or should it throw an error if those interfaces are in use? Different use cases demand different actions.

You can add components to many devices at once by selecting the desired devices and clicking the "add components" button at the bottom of the list.
