### ISSUE TITLE
Can I get all available-ips from different Lan in API ?

### ISSUE THREAD

**Issue by NickWoo33** [digitalocean/netbox#2040]
Hello,

First, thanks the amazing tool.

I would like to know if I can get all available-ips from different Lan  by roles or site or something else in API ?

example:

I have 3 lans:
10.10.10.0/24
10.10.10.1/24
10.10.10.2/24

These are the same purpose, user get available ips form one of these 3 lans.
if one of them run out of available ip, I would like to get it from other lan in these big pools.

Now I  get ip from API by:
http://netbox/api/ipam/prefixes/$ID/available-ips/

I know this is not auto, I have to change the url ($ID need to be changed when this lan's ip is not enough anymore)

I try to list the ip by role or by site, it just didn't work out.

Hence, is there a smart way to get available ip from a big pool (maybe with diff lans) ?

Thanks.

### Issue type
[ ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5 
* NetBox version:  2.3.2

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by NickWoo33** [comment]
thanks
