### ISSUE TITLE
Auto-increment MAC address for bulk interface creation

### ISSUE THREAD

**Issue by KART35** [digitalocean/netbox#2044]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.5 
* NetBox version: 2.3.2 

### Description
Currently, if a MAC address is entered, and interfaces are created in bulk, lets say `GigabitEthernet1/0/[1-24]`, it is simply applied to all interfaces in the range.

If the MAC address were to increment by one for each interface given the starting MAC address, it would be extremely useful for devices like switches.

**Comment by jeremystretch** [comment]
Rejecting this as MAC addresses are not necessarily sequential. Potential use case for #822 if you want to add it there.
