### ISSUE TITLE
image filename max_length is too short

### ISSUE THREAD

**Issue by nschmalenberger** [digitalocean/netbox#2046]
### Issue type
[ X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.2

### Description
I want to attach the drawing of my cage sent to me by Equinix called "BLAHBLA - DC4 - Cage # 42360  - Cage, Cabinets, AC Power, Ladder Rack and Fiber Tray Layout - 4-1-17 v1.pdf"

I get the message "Ensure this filename has at most 100 characters (it has 107)."

Can the max_limit for this field please be increased to 200 maybe? I'd like to be able to keep the original filename if at all possible. Thanks!

**Comment by bellwood** [comment]
100 characters is the default filefield maxlength but it can be adjusted in the model:

https://stackoverflow.com/questions/26575635/django-increase-filefield-length

https://docs.djangoproject.com/en/dev/ref/models/fields/#filefield

**Comment by nschmalenberger** [comment]
That's useful information that it would require a database schema change, and would require a migration defined. If its too much trouble, this can be closed.

**Comment by jeremystretch** [comment]
Let's stick with the default limit.
