### ISSUE TITLE
Management/Console Interface within VC

### ISSUE THREAD

**Issue by tvberlin** [digitalocean/netbox#2047]
### Issue type
[x] Feature request
[ ] Bug report
[ ] Documentation

### Environment
* Python version:  3.4.2
* NetBox version:  2.3.3

### Description
When creating virtual chassis, e.g. w/ Juniper devices, some interfaces (Console, Management) have the same name across all members. Netbox displays them with their given name from the template (e.g. MGMT) w/o giving the user the possibility to distinguish between the different VC members

I'd recommend displaying the members name next to the interface when duplicate interface names are detected. We've found a workaround by naming interfaces "MGMT_LC0" for example.

**Comment by jeremystretch** [comment]
You'll need to rename the interfaces of each member device in the virtual chassis. NetBox cannot make assumptions about whether or how these interfaces should be renamed.
