### ISSUE TITLE
Rack Tenants 

### ISSUE THREAD

**Issue by flobe212** [digitalocean/netbox#2051]
### Issue type
[ X ] Feature request 
[ ] Bug report  
[ ] Documentation 

### Environment
* Python version:  3.4.8
* NetBox version: 2.3.3 

### Description

We are selling Colocation Space, 1/1 Racks, 1/2 Racks, 1/4 Racks and single Units. At the Moment we are facing a documentation problem in Netbox. We are creating for each customer a device and racking them into the rack but if we have to document the server setup with single servers, too we can't mount them on these Units because they are already in use. You can assign only a complete rack with a tenant.

Idea is that there is a tenant function 1:1 like the reservation function. 
It would be create if there is a function to assign single or multiple Units to a tenant.

**Comment by jeremystretch** [comment]
This would require substantial changes to the database schema as NetBox does not represent individual rack units as discrete objects. As an alternate solution, I suggest creating rack objects which represent only a portion of a real rack. For example, if Rack A123 is split in half between two tenants, create A123:1 and A123:2, and assign each to its respective tenant. It's not an ideal solution, but the value of implementing this relatively niche feature doesn't justify the development effort needed to rework the database scheme.

**Comment by tobzsc** [comment]
@jeremystretch Sad news... You are speaking about niche feature. How comes? Where do you have that information from that this may or may not be requested by other users?

**Comment by tobzsc** [comment]
@jeremystretch do you see a chance for a sponsoring here? We are really interested in such a feature.
