### ISSUE TITLE
Login Timeout

### ISSUE THREAD

**Issue by rml596** [digitalocean/netbox#2053]
### Issue type
[ X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description

Not sure if this is a feature request, or if it is more of a question, but is it possible to timeout a login session. Currently every time I go to the web gui, I am not required to log in (because I logged in already). Could I make it so after an hour, I am required to log back in?

**Comment by jeremystretch** [comment]
Django has a [`SESSION_COOKIE_AGE` setting](https://docs.djangoproject.com/en/2.0/ref/settings/#session-cookie-age) that defaults to two weeks. We can implement a `LOGIN_TIMEOUT` or similarly-named configuration setting to influence this. The user should be able to set this variable to zero to limit the login to the life of the browser session.

**Comment by Schillers** [comment]
@jeremystretch, Did this ever get followed up at all or is it still a Work in Progress?
