### ISSUE TITLE
Request: Interface protocols

### ISSUE THREAD

**Issue by avolmensky** [digitalocean/netbox#2055]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description

I am in the process of automating our network with Salt + Netbox. One limitation with Netbox is I am unable to build a complete interface configuration from the Netbox data. I need to be able to specify if  OSPF/MPLS is enabled on an interface, what OSPF area that interface should be in etc.

I would be able to get by with custom fields for interfaces, but at the moment I have to store this data externally which is getting messy fast

**Comment by ngrundler** [comment]
I am running into the same issue, but I believe #1349 is the direction the project is going to address these kinds of use cases.

**Comment by jeremystretch** [comment]
@ngrundler is correct; #1349 is intended to address this need.
