### ISSUE TITLE
Add filter to napalm config output

### ISSUE THREAD

**Issue by ChrisdAutume** [digitalocean/netbox#2056]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.4
* NetBox version:  2.3.2

### Description
It would be useful to add a filter before napalm config output. In fact, some firm have to conform to various rules for certification (PCI-DSS, etc ...) like hidding password, shared key ...

I propose to define a new global parameter NAPALM_CONF_FILTER where people can define a list of regex to remove match from config output.

**Comment by jeremystretch** [comment]
This would need to be implemented in whatever client is consuming the NetBox API to retrieve configs via NAPALM. It's not NetBox's place to process the data.
