### ISSUE TITLE
Interface connections overview include description

### ISSUE THREAD

**Issue by deku-m** [digitalocean/netbox#2057]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.3

### Description
As we handle fiberpanels/patchpanels as devices, we know its not the normal way but a workaround, 

We are making connections towards the switches (SER/MER principle). After that we want to make labeling for the cabling. One thing helps in this path and that is the overview from the interface connections. 

Only one thing we are missing now when we make a export froms this is that we are missing the descriptions as we use this to know where the connections goes too (from the fiber panel towards a other device/location) 
Location/Device >> Copper/Fiber panel >> Switch.

As it isnt possible to connect the same interface towards a other device. Or is it?

So the overiew should be looking like below or include it in the export if possible:

Device A       Interface A      Description        Device B               Interface B            Descriptions
FO01            05-06               XXX                   LAN-VSS-2           GI2/7/16               XXX              

This really helps in printing labels for cabling with the combination of the csv export.
Maybe it is also smart to also include the vlan tag then if possible?

**Comment by jeremystretch** [comment]
I don't normally condone any changes relating to (currently) unsupported features, but it seems reasonable to include the interface descriptions in the connections list.

**Comment by madeinoz67** [comment]
I have come across this issue as I too have been grappling how to deal with it and like the suggestion outlined however does not allow for capture of Cable ID (unless you use the port descriptions) as am trying to work out the best way to capture cable numbers. 

I think the patch panel form factory in conjunction parent/children relationships in Circuits so this would then allow: 

1) Physical Circuit identification mapped to devices, i.e. patch and cable numbers
2) Logical Link circuits identifications Connects Devices and is made up of physical circuits.  A- Z end determined by the child A-Z end at each end of the link.
3) Logical Path within a network identifiers (made up of multiple links) With A an Z end determined by child identifiers 
4) Logical Circuit as per current implementation but is made up of multiple Paths with A and Z ends determined my The Child Identifiers.

So effectively a Circuit is a tree structure at the top and descending down the tree made up of Paths, links and then Physical circuits at the bottom, having the ability to "pass through" on patch panels would allow these types outlined above to have more complete network documentation.

**Comment by snowie-swe** [comment]
It would be beneficial in the terms of CWDM network aswell.

Physically it looks like the following: Device1 -> CWDM1 -> fiber >CWDM2 -> Device2
Logically its Device1 -> Device2
An option would be to allow the "connection via" to be more then a circuits.
