### ISSUE TITLE
Error with Postgres request when opening Racks or Devices

### ISSUE THREAD

**Issue by omen89** [digitalocean/netbox#2058]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  2.3.3

### Description
Hello!
We noticed the problem on version 2.3.1, update to 2.3.3 did not help
Let's go to Organization > Sites > some site. 
![image](https://user-images.githubusercontent.com/24832262/39235116-b2ed2f1c-487d-11e8-9128-37477985dd37.png)

When you open Devices, an error occurs:

![image](https://user-images.githubusercontent.com/24832262/39234992-6cd3f3bc-487d-11e8-94a5-27c181d1e45d.png)

If you open Racks, then an empty list is opened
![image](https://user-images.githubusercontent.com/24832262/39235150-cd4dc2cc-487d-11e8-9449-5e32443c1b90.png)

In logs of Postgres I see errors with the query:
```
postgres[113893]: [10-3]  "dcim_device"."primary_ip6_id" AS Col17, "dcim_device"."cluster_id" AS Col18, "dcim_device"."virtual_chassis_id" AS Col19, "dcim_device"."vc_position" AS Col20, "dcim_device"."vc_priority" AS Col21, "dcim_device"."comments" AS Col22 FROM "dcim_device" INNER JOIN "dcim_site" ON ("dcim_device"."site_id" = "dcim_site"."id") WHERE "dcim_site"."slug" = E'l-rus-msk-kdr15') subquery

postgres[113893]: [10-2] < 2018-04-25 11:24:45.707 MSK > STATEMENT:  SELECT COUNT(*) FROM (SELECT DISTINCT (CAST(SUBSTRING(dcim_device.name FROM '(\d{1,9})$') AS integer)) AS "_dcim_device_name3", (SUBSTRING(dcim_device.name FROM '^\d*(.*?)\d*$')) AS "_dcim_device_name2", (CAST(SUBSTRING(dcim_device.name FROM '^(\d{1,9})') AS integer)) AS "_dcim_device_name1", "dcim_device"."id" AS Col1, "dcim_device"."created" AS Col2, "dcim_device"."last_updated" AS Col3, "dcim_device"."device_type_id" AS Col4, "dcim_device"."device_role_id" AS Col5, "dcim_device"."tenant_id" AS Col6, "dcim_device"."platform_id" AS Col7, "dcim_device"."name" AS Col8, "dcim_device"."serial" AS Col9, "dcim_device"."asset_tag" AS Col10, "dcim_device"."site_id" AS Col11, "dcim_device"."rack_id" AS Col12, "dcim_device"."position" AS Col13, "dcim_device"."face" AS Col14, "dcim_device"."status" AS Col15, "dcim_device"."primary_ip4_id" AS Col16,

postgres[113893]: [10-1] < 2018-04-25 11:24:45.707 MSK > ERROR:  invalid input syntax for integer: "d"
```

And in some Sites everything is OK. Found such a problem with 3 sites of 20, checked out selectively.

**Comment by jeremystretch** [comment]
No idea what could be causing that. It doesn't appear to be a reproducible issue. Have you made any modifications to the code base?

**Comment by omen89** [comment]
Hello! We did not change code and did not make any changes to the database

**Comment by akhmarov** [comment]
Hello, Jeremy

This issue is a bit critical. We have faced the same error opening several racks on several sites. How could we gather additional info to help debug process? What can help you to find root cause?

**Comment by jeremystretch** [comment]
@akhmarov Can you post the list of device names within the site which gives you the errror? I think this has something to do with the logic in [`NaturalOrderByManager`](https://github.com/digitalocean/netbox/blob/develop/netbox/utilities/managers.py#L6).

**Comment by omen89** [comment]
@jeremystretch Hello! I unloaded several problem names from the database:

'rus-msk-kdr15-133a-sw01'
'rus-msk-kdr15-133-ata01'
'rus-msk-kdr15-133a-ups01'
'rus-msk-kdr15-133-phone01'
'rus-msk-kdr15-211-ata01'
'rus-msk-kdr15-211-ata02'
'rus-msk-kdr15-211-phone01'
'rus-msk-kdr15-211-sw01'
'rus-msk-kdr15-211-ups01'
'rus-msk-kdr15-215-phone01'
'rus-msk-kdr15-215-sw01'
'rus-msk-kdr15-215-ups01'
'rus-msk-kdr15-237-ata01'
'rus-msk-kdr15-237-phone01'
'rus-msk-kdr15-237-sw01'
'rus-msk-kdr15-237-sw02'
'rus-msk-kdr15-237-ups01'
'rus-msk-kdr15-237-ups02'
'rus-msk-kdr15-42-phone01'
'rus-msk-kdr15-42-sw01'
'rus-msk-kdr15-42-ups01'
'rus-msk-kdr15-8-sw01'
'rus-msk-kdr15-8-ups01'

**Comment by omen89** [comment]
@jeremystretch Hello! Is there a solution to this problem?

**Comment by DanSheps** [comment]
@omen89 

You need to give him time to research this and play around with it.

**Comment by jeremystretch** [comment]
Sorry but I'm not able to recreate this locally. If you can recreate the error on a new install and post the exact replication instructions and sample data, I'll try digging into it more.

**Comment by omen89** [comment]
Hello @jeremystretch! 
We found problems and solved it. For another product in PostgreSQL the parameters were set:

```
escape_string_warning = off
standard_conforming_strings = off
```

Because of them, the netbox issued an error. You can close the bug. Perhaps this information will be useful.

**Comment by jeremystretch** [comment]
Interesting. Thank you for posting the follow-up!
