### ISSUE TITLE
Adding child prefixes using API is outdated with a lot of objects set to required compared to the Webui

### ISSUE THREAD

**Issue by JSystem1** [digitalocean/netbox#2059]
### Issue type
[ ] Feature request 
[X ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.12 
* NetBox version: 2.3.2  

### Description
I am trying to post child prefixes using the API at `/api/ipam/prefixes/{id}/available-prefixes/` there seems to be a lot of required fields with using the API and other features not there compared to the webui when adding a child prefix. 

Currently site,vrf,tenant and other fields are set to required while using the API. There is also no option to attach to a VLAN group when adding a child prefix through the API.

As I have a global VLANs defined I am running into a roadblock while trying to use the API to import my data into netbox.

**Comment by jeremystretch** [comment]
The only required parameter is `prefix_length`. This may have been addressed in a more recent release.
