### ISSUE TITLE
Custom field to hold json objects

### ISSUE THREAD

**Issue by vandlol** [digitalocean/netbox#2061]
### Issue type
[x ] Feature request 
[ ] Bug report     
[ ] Documentation   

### Description
I would love the ability to add a custom field for json objects.
Since it's a custom field use cases are diverse.

I guess complexity/depth should be limited.

**Comment by sdktr** [comment]
Did you notice https://github.com/digitalocean/netbox/issues/1349? Maybe that covers your use case? not sure how @jeremystretch is planning the structure around that, but it's an accepted feature request.

**Comment by vandlol** [comment]
Oh man, no i haven't seen this.
I love it - just what i need :) i'll head straight over and give it a thumpsup
