### ISSUE TITLE
API Docs - Typo error on /virtualisation/interfaces/

### ISSUE THREAD

**Issue by Keyhaku** [digitalocean/netbox#2065]
### Issue type
[ ] Feature request 
[ ] Bug report      
[X] Documentation   

### Environment
* Python version:  3.6.5
* NetBox version:  2.3.3

### Description
Hello,

On the API documentation it seems there is a little error.

On `/virtualisation/interfaces/` endpoint, method `POST`, the field `device` is marked as mandatory, but the API only respond to the field `virtual_machine`.

The error message returned by the API is also misleading :
```
{
 "non_field_errors": [
   "An interface must belong to either a device or a virtual machine."
 ]
}
```

It seems the error is also present on `/virtualisation/interfaces/{id}` methods `PUT` and `PATCH`.

**Comment by k-nishigaki** [comment]
I resolved my problem by this report.
thank you so much.

I hope to modified documentation.

**Comment by FrantisekLee** [comment]
Hi all,
what i do bad?
I want to create via API (curl) new virtual maschine. When i run this command;
POST -> virtualization -> virtual-machine
{
  "name": "ferod_testVM3",
  "status": 1,
  "role": 8,
  "tenant": 1,
  "cluster" : 1,
  "platform": 2,
  "vcpus": 4,
  "memory": 4096,
  "disk": 30,
  "comments": "test",
	  "interfaces": {
		"device": 17,
	        "name": "ensp0s25",
		"form_factor": 0,
		"enabled": true,
		"lag": 0,
		"mtu": 0,
		"mac_address": "00:00:00:00:00:00",
		"mgmt_only": true,
		"description": "string",
		"mode": 100,
		"untagged_vlan": null,
		"tagged_vlans": [
		   1
		 ]
		}
}

command ignore class "interfaces" but VM is creating without interfaces.

When i want to create only interfaces:
{{
  "device": 17,
  "name": "ensp0s25",
  "form_factor": 0,
  "enabled": true,
  "lag": 0,
  "mtu": 0,
  "mac_address": "00:00:00:00:00:00",
  "mgmt_only": true,
  "description": "string",
  "mode": 100,
  "untagged_vlan": null,
  "tagged_vlans": [
    1
  ]
}

output is:
{
  "non_field_errors": [
    "An interface must belong to either a device or a virtual machine."
  ]
}

can you help me please?

**Comment by lampwins** [comment]
This will be covered in #2665
