### ISSUE TITLE
API does not accept url encoded query strings

### ISSUE THREAD

**Issue by wrouesnel** [digitalocean/netbox#2070]
### Issue type
[x] Bug report      

### Environment
* Python version:  3.6.5
* NetBox version:  75465a340476 (v2.3.3)

### Description
Try querying a device type using the regular query syntax with a simple URL:
`/api/dcim/device-types/?q=&slug=unknown model`

Result - it'll work

Try the same query with a properly URL encoded string as produced by requests for example:
`/api/dcim/device-types/?q=&slug=unknown%20model`

Result - no results. A totally different query.

To make this query work I have to intentionally send malformed requests to the endpoint when using requests:
```
greq = requests.Request(method='GET', url=netbox_uri + '/api/dcim/device-types/')
prep = greq.prepare()
prep.url = netbox_uri + '/api/dcim/device-types/' + '?q=&slug={}'.format('unknown model')
r = s.send(prep)
```

Which is obviously far from ideal.

**Comment by jeremystretch** [comment]
Slugs generally use hyphens instead of spaces to avoid this problem. That said, NetBox relies on [django-filter](https://github.com/carltongibson/django-filter) for query filtering, so any requests for changes to this behavior would need to be submitted against that project.
