### ISSUE TITLE
why not add an authentication for the Whole Dashboard?

### ISSUE THREAD

**Issue by MoHD20** [digitalocean/netbox#2072]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5
* NetBox version:  latest

### Description
why not add an authentication for the Whole Dashboard?
I know that netbox isn't intended for the public facing but authentication is needed even in the private corporations. Is there a reason for using authentication only for the editing purposes?

**Comment by lampwins** [comment]
This is already implemented. See https://netbox.readthedocs.io/en/latest/configuration/optional-settings/#login_required which can be set in your `configuration.py`.

**Comment by jkldgoefgkljefogeg** [comment]
I created configuration.py and added `LOGIN_REQUIRED = True`, but it doesn't do anything. 
configuration.example.py is no longer shipped with netbox. has configuration.py been deprecated?
