### ISSUE TITLE
Increase VRF RD Length

### ISSUE THREAD

**Issue by hreeder** [digitalocean/netbox#2076]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  2.3.3

### Description
I would like to request the VRF RD be increased to 129 characters - we use Cisco ACI and that's the max length for RDs on the platform (as they are in the format `Tenant:VRF Name`) and I'd like to keep this for our consumption via NetBox rather than have to keep some form of mapping somewhere external. It could stand that two tenants have a VRF name the same, and we have some tenants with long names, so the current 21 characters is quite restrictive.

I have seen #1817 however given this is a technical reasoning I would like to request it's consideration aside from the previous discussion around this.

**Comment by jeremystretch** [comment]
The route distinguisher field represents an RD as defined in [RFC 4364](https://tools.ietf.org/html/rfc4364#section-4.2), which has a maximum length of 21 characters. It's not intended to be repurposed for proprietary systems, but you can create a custom field on the VRF model to hold this data.
