### ISSUE TITLE
Allow NAT inside address without IPAM entry of itself

### ISSUE THREAD

**Issue by CDawson1** [digitalocean/netbox#2078]
### Issue type
[X ] Feature request 

### Environment
* Python version:  2.7.12
* NetBox version:  2.3.1

### Description

For the sake of discussion, my public IP is what I want to populate with a private IP NAT inside.  

When creating an public IP address that has a need to reference a private NAT, that NAT seems to require it's own entry in IPAM before it can be populated as a NAT.  By default, that private IP entry would/should also have a NAT that references the public.  

As such, it's a recursive entry.  

I don't want/need the private IP to have its own listing.  We don't own this space, but our environment is such that we need to reference it.  It seems unnecessary to have two sides of the same coin represented.  

Essentially this seems to require this field to be an arbitrary field, but it should still be displayed on the main table view and searchable.  

While a custom field could fit the bill, that seems to require additional changes that essentially duplicate what the NAT IP inside field already is, in addition to additional work required to get the displays correct.  

Is this something that's easily changed without compromising any existing use of this field?

**Comment by jeremystretch** [comment]
> By default, that private IP entry would/should also have a NAT that references the public.

You'll need to create both the outside and inside IP addresses, but only the outside-to-inside relationship needs to be defined.
