### ISSUE TITLE
Prefix / IP address assignment history

### ISSUE THREAD

**Issue by TLMiot** [digitalocean/netbox#2079]
### Issue type
[ x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.12 
* NetBox version:  2.3.1 

### Description

I am evaluating the use of NetBox for IPAM inside the Internet Service Provider I work for.
One of the requirements I have is a history of changes for every Prefix or IP address.
This is for law compliance so it's mandatory.
I didn't find any info about this inside NetBox interface or in the documentation.
Is this feature implemented? If not, is this achievable in some way? (for example by enabling logging...)
Thank you

**Comment by jeremystretch** [comment]
NetBox does not currently support this. It is planned for future development but I have no ETA. It does not sound like NetBox meets your requirements.
