### ISSUE TITLE
Add an SSP field

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#208]
Helo,

In my organization we use a term called SSP (system security plan). This would be helpful if this is added under Management in the device field. Something like this >

Device
   Management
         SSP : netbox

Fore more information on SSP https://www.sans.org/projects/systemsecurity.php

**Comment by jeremystretch** [comment]
We won't be adding any custom fields to the NetBox code base, but #129 is planned to allow users to add their own custom fields.
