### ISSUE TITLE
Help - Question about Permissions

### ISSUE THREAD

**Issue by rml596** [digitalocean/netbox#2080]
### Issue type
[ ] Feature request 
[ ] Bug report      
[x ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description
I am trying to figure out if there is a way to allow users to have permissions for one site (add/delete/change/view inventory from one site) but not another. Is this possible?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
