### ISSUE TITLE
Cannot change MAC when editing interface

### ISSUE THREAD

**Issue by jasperla** [digitalocean/netbox#2081]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6.5
* NetBox version:  2.3.3

### Description

When adding a new interface to a device there is the option to set a MAC Address, along with the other options. However when editing the interface (select interface, then "Edit") there is no field available to set or modify the MAC address attribute for the selected interface.

![screen shot 2018-05-05 at 20 38 38](https://user-images.githubusercontent.com/637504/39666471-54283b96-50a4-11e8-97b1-696786744954.png)

**Comment by jasperla** [comment]
I now realise there's a difference between selecting an interface and clicking the yellow "Edit" button and clicking the blue "Edit interface" button, which does allow for changing the MAC address. While not quite obvious it _is_ possible to change the MAC address.

Feel free to close this if there's nothing more to add :-)

**Comment by jeremystretch** [comment]
Right, the yellow "edit" button at the bottom of the interfaces list is for bulk editing. It didn't really make sense to include the MAC address here as each interface typically has a unique MAC.
