### ISSUE TITLE
Again: There was an error generating the requested graph. Ensure that the GraphViz executables have been installed correctly.

### ISSUE THREAD

**Issue by omen89** [digitalocean/netbox#2086]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  2.3.3

### Description

Again, the problem is similar https://github.com/digitalocean/netbox/issues/1583

Before:
```
dot -V
dot - graphviz version 2.38.0 (20140413.2041)
```

I installed the latest available version:
```
dot -V
dot - graphviz version 2.40.1 (20161225.0304)

```
Update did not help

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
