### ISSUE TITLE
Modelling redundant port-channel devices like Cisco 9K's?

### ISSUE THREAD

**Issue by wrouesnel** [digitalocean/netbox#2092]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6.5
* NetBox version:  v2.3.3

### Description
The current virtual chassis implementation works for devices like HP5900 series switches where the redundant IRF configuration means two switches act as one logical device, including from a network perspective.

However it doesn't appear to be capable of handling Cisco 9000 series switches, which implement this quite differently - namely - you can have virtual port channel's spanning across two devices, which are linked via the vPC peer link, but managed independently (i.e. have separate network identities).

This means from a topology perspective the fact that the port-channel is being redundantly proxied around via the switches isn't going to be properly represented (and viewing the full configuration as a single unit can't be done).

I think the solution here would be to support "multi-master" virtual devices so this situation can be properly represented?

**Comment by jeremystretch** [comment]
Virtual chassis is intended only for devices which share a common control plane. Multichassis LAG is different from this: each switch has its own control plane and its own incantation of the LAG interface. The only sane way I've come up with to model this is to simply create the LAG interface on both switches (without putting them in a virtual chassis). This mostly closely resembles real world operation. For instance, you can disable the LAG interface on one switch but not the other.
