### ISSUE TITLE
Error editing connection from device interface

### ISSUE THREAD

**Issue by lancesdavis** [digitalocean/netbox#2093]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.8
* NetBox version:  2.3.3

### Description
Editing connection from device interface leads to 'The requested page does not exist' - I expected it to go to the edit connection page.

![20180515_094727](https://user-images.githubusercontent.com/38127506/40047491-898d930a-5827-11e8-9ec7-5a3e3432affb.jpg)

url is https://netbox.teledata.co.uk/circuits/circuit-terminations/3/edit/&return_url=/dcim/devices/2/

![netbox 404](https://user-images.githubusercontent.com/38127506/40047264-f2e09948-5826-11e8-8380-c7d5fe95a45a.PNG)

**Comment by jeremystretch** [comment]
Typo in the template.

`&return_url=/dcim/devices/2/`

should be

`?return_url=/dcim/devices/2/`
