### ISSUE TITLE
Secrets for virtual machines

### ISSUE THREAD

**Issue by lancesdavis** [digitalocean/netbox#2094]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:   3.4.8
* NetBox version:   2.3.3

### Description

Please add a _secrets_ block to virtual machines - the same as on _devices_

**Comment by DanSheps** [comment]
Duplicate of #1503

**Comment by lancesdavis** [comment]
Thanks for pointing me at that one - someone has indeed pointed out that vms need secrets  - I would have thought that a vm is just a special type of _virtual_ device and whilst other things could benefit from secrets - racks/tenants etc - with vms it is an obvious omission.

**Comment by jeremystretch** [comment]
FWIW secrets were introduced in NetBox before virtual machines, hence the disconnect.
