### ISSUE TITLE
Child prefix as container - utilization statistics incorrect

### ISSUE THREAD

**Issue by lancesdavis** [digitalocean/netbox#2095]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.8
* NetBox version:   2.3.3

### Description
A child prefix set to be a container should not be included within the utilization statistics for the parent but only active prefixes within the tree should be included.

To replicate - create a /20 prefix as a container, create a /21 prefix as a container within the 1st prefix - eg same starting ip , utilization of /20 shows as 50% whereas I expected it to be zero

![prefix1](https://user-images.githubusercontent.com/38127506/40053363-dcea3d58-5838-11e8-8221-cf8e06324455.PNG)
![prefix2](https://user-images.githubusercontent.com/38127506/40053365-dcfda834-5838-11e8-8091-6d0211e8bcb9.PNG)

**Comment by ktims** [comment]
I'm not responsible for making the decision, but i think this is as expected, and I would like to note that I prefer the current behaviour.

**Comment by DanSheps** [comment]
I am sorry but I don't see the bug here.  This is working as intended IMO.  Your container is using "5/10/50/80%" of the space, which is expected behaviour.

**Comment by lancesdavis** [comment]
Maybe I am missing the point of containers - but it seems a contradiction that an empty container uses up the space ?  It doesn't at the top level so why does it when it is a child ?

The attached shows 2 child level containers - utilization of the parent block is 100% - yet there are still 4096 ip addresses available to alllocate ?

![container2](https://user-images.githubusercontent.com/38127506/40101478-78b19bea-58df-11e8-8c8a-91dab621445c.PNG)
![container3](https://user-images.githubusercontent.com/38127506/40101479-78c570ca-58df-11e8-9de8-f37c4b3afb6f.PNG)
![container1](https://user-images.githubusercontent.com/38127506/40101481-78dc3c9c-58df-11e8-9d31-4ac8c56994f0.PNG)

**Comment by jeremystretch** [comment]
This is intended behavior. A container represents an allocation of address space. The only special significance of a container (versus a non-container prefix) is that it may not exist as a real network. For example, you may have multiple "real" /24s configured on interfaces within your network which all belong to a parent /20 container. This /20 might not actually exist in the routing table; it's just an allocation.
