### ISSUE TITLE
Delete "all" clusters still only deletes in pages of 50

### ISSUE THREAD

**Issue by pm17788** [digitalocean/netbox#2097]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.4
* NetBox version:  2.3.2

### Description
* Go to `Virtualization` -> `Clusters`, click on the checkbox by the `Name` column heading, and get prompted to *Select all XXYY clusters matching query*.
* Click `Delete All`
* The confirmation page which comes up shows only 50 clusters.
  * Confirming the delete action also only deletes just the 50.

**Comment by jeremystretch** [comment]
This affects all object types without a filter set under its bulk deletion view. Added the missing filter for virtualization.Cluster as well as dcim.Region, and tweaked BulkDeleteView to accommodate queryset-based deletion for objects without a filter.

Also raised #2101 to ensure that _every_ object gets a filter in the interest of consistency.

**Comment by jeremystretch** [comment]
Fixed in 399a633d9d3baa8f3a22998ea018bc5e82db31bc. Not sure what happened with the commit message.
