### ISSUE TITLE
Add support for a status field on racks

### ISSUE THREAD

**Issue by yarnocobussen** [digitalocean/netbox#2104]
### Issue type
[ X ] Feature request
[ ] Bug report
[ ] Documentation

### Environment
* Python version: 3.5.3
* NetBox version: 2.3.3

### Description
* A detailed description of the proposed functionality
Adding support for a status field on racks for the purpose of capacity management and tenant administration.

* A use case for the new feature
For our colocation services we do not only rent out space within a rack, but also racks as a whole.
For us a rack can have 3 statuses. These seem quite universal throughout the colocation business:
- Active (tenant is renting the rack)
- Reserved (tenant is not renting the rack, but has a priority reservation for it)
- Deprecated (tenant is renting the rack, but is in the process of moving out of it)

With these 3 statuses, we manage capacity and billing for colocation in our current (internal) tool. For capacity we use a dummy tenant and a reserved status to marks racks as available for real tenants. For billing purposes each status has a cost associated with it in our billing software. (which it reads by API) In Netbox, a fourth status with the type "Available" would make this even easier, although that may deviate to much from the status options in the rest of Netbox (?).

If implemented into Netbox, a status field for racks would significantly help us in our migration. I'm sure others are in a similar spot and would be able to make use of this as well. Also, we cannot see a way to make this work with /dcim/rack-reservations/, as it does not apply to entire racks and thus we cannot count how many racks with status X a tenant has.

* A rough description of any necessary changes to the database schema
This field already exists for other objects and I can't think of any conflicts with other functionality in Netbox. I guess it would simply mean adding a single column?

* Any relevant third-party libraries which would be needed
None

**Comment by jeremystretch** [comment]
We can try to get this in v2.4, however community feedback is required to solidify the exact set of rack status choices. I would suggest:

1. Active
2. Planned
3. Reserved
4. Deprecated

**Comment by jeremystretch** [comment]
I'd avoid getting too granular. Tenancy should be managed separately from status. For example, you can have a rack that is planned, active, or reserved, and in any of these states may or may not be assigned a tenant.

**Comment by bdlamprecht** [comment]
Yeah, good point about granularity.
I suppose the FR just made me think too much. :thinking:

I retract my above comment and go with yours.

**Comment by yarnocobussen** [comment]
The problem is that a rack can also simply exist, without an active use and without plans for it.
Like a device, they can be part of your inventory. For devices, Netbox already has a status for that.
Since the inventory state for devices is already in Netbox, I suggest a similar status for racks:

1. Active
2. Planned
3. Reserved
4. Deprecated
5. Available (Or Inventory, any word that gets the job done, really)

This is tenant neutral and covers all operational states I can think of. What do you guys think?
