### ISSUE TITLE
Find Next Available Prefix out of Aggregate

### ISSUE THREAD

**Issue by jvanderaa** [digitalocean/netbox#2105]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6
* NetBox version:  2.3.3

### Description
Would request implementing the next-available-prefix to also be able to get the next available prefix from an aggregate. Using the aggregate as the top level of address space allocated and able to go to the aggregate page to use as a report of available space is valuable. Thus looking to be able to get prefixes out of that space.

Probably a duplication/call to the same code used on prefixes.

**Comment by jeremystretch** [comment]
Aggregates define the top level of your IP space hierarchy. They're not really intended to be allocated directly other than by human-driven policy, so I don't think it makes sense to enable blind allocation like we have for prefixes. You can, however, create a container prefix the same size as your aggregate and allocate new prefixes that way.
