### ISSUE TITLE
Should devices in rack elevation use device.display_name property?

### ISSUE THREAD

**Issue by nschmalenberger** [digitalocean/netbox#2106]
### Issue type
[ X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.3

### Description
The rack elevations template shows the device role name of an unnamed device. It seems that since the time that code was written, the device.display_name property has been created to work in a similar way but also check if first if the device is a member of a virtual chassis and in that case show the virtual chassis master device name and the member id of the unnamed member device.

It seems like using device.display_name in the template could better show how an unnamed device in a rack is in fact related to some other significant devices. Since device.display_name has a different default though (the device type name instead of role name) changing to use device.display_name would mean a change in how all unnamed devices are shown in the rack elevation.

Does it make sense to do that? Is the display_name property right to use there or is better to keep defaulting to the role name in the rack elevation?

**Comment by jeremystretch** [comment]
`display_name` will return (in order):

1. Device name
2. Virtual chassis master name
3. Device type

I think it makes sense to stick with the role in the rack elevation.
