### ISSUE TITLE
Edit IP address, update/change device

### ISSUE THREAD

**Issue by fone** [digitalocean/netbox#211]
I am wanting to update the "Device" on IP addresses I've added. I can change the IP, but the Device field says "None" and does not have an area to edit. Am I missing something?

thank you

Using v1.
![editing_ip](https://cloud.githubusercontent.com/assets/36145/16632219/229cbf6a-4391-11e6-8c61-606a4d24f6ed.png)
0.7

**Comment by peelman** [comment]
Right now you assign IP addresses to devices; not devices to IP addresses.

So you would need to go to the device in question, and add the IP from there.

**Comment by Gelob** [comment]
I had the same problem yesterday and then I realized I was just dumb. You have to go to the device you want to assign an IP address to and then click assign IP address under IP addresses. Do not edit the device.

http://netbox-demo01.packetlife.net/dcim/devices/112/

![screen shot 2016-07-06 at 2 57 41 pm](https://cloud.githubusercontent.com/assets/422752/16632562/3e979b56-438a-11e6-9d26-c62361ba85ed.png)

**Comment by fone** [comment]
ok thanks for the quick replies gentlemen. I got it.

I understand 'why' its setup as it is now. it does make sense the more time you spend in here.

my trouble is I am moving from GestioIP (we're a small ISP) so I have a ton of devices/addresses. I was hoping to import IP address csv and then go back in and edit it, but as you know it doesn't like that as the device, and numerous other fields don't exist.

So I'm only able to import IP addresses along with a description. then will go back in and edit them when I have time.

I'm gonna stick with it though. thanks for the assistance.

**Comment by ryanmerolle** [comment]
Alternatively, you could just insert direct into the table(s) and play around that way.  I would only suggest if you feel comfortable with this all, but for instances where the import functions are too rigid or the UX is not there yet, it may help you get data out of GestioIP quicker.

Later on we could develop migration scripts for different DCIMs/IPAMs exports/imports.  But I see this as low priority.

**Comment by topranks** [comment]
Thanks guys.  When importing IPs via CSV I could include the device, the example CSV format given shows this:

192.0.2.42/24,65000:123,switch12,ge-0/0/31,True,Management IP

I do agree however it would nice to have the GUI functionality that you could select the device/interface when adding an IP manually, as well as having this ability via the device section.

**Comment by fone** [comment]
topranks- yeah that works if the device already exist.
So say this is what I want to import
` 10.10.251.18/32,,Virtual Machine,,,NetBox`

```
Enter one line per record in CSV format.
Record 1 (device): Device not found.
```
So I'd need to create each and every device before importing that way. I have quite a few that are virtual machines. Trying to figure out the easiest way for this right now.

**Comment by kenspi** [comment]
I'm running into a similar issue (also coming from GestioIP). We're a medium size company with 3 office sites plus some data centers, so we have hundreds more "non-racked" devices (desktop PCs, VoIP phones, printers, etc). I can import the used addresses via CSV, but the hostname field is what populates the "description" field in NetBox.

Importing all of these as devices first could be a possible option, but relatively few of these are racked in our case. Since a rack location is mandatory (see #198 for why this is sub-optimal), pre-importing all non-racked devices is not realistic.

**Comment by fone** [comment]
there has been mention of a "host name" field being added to the import section. if this happens that should resolve my trouble.

at the moment when I'm adding VMs, I'm adding them to a rack I called VirtualRack.

**Comment by cstueckrath** [comment]
We have a similar problem with this.
We have tons of VMs to add (I like the VirtualRack concept, thanks for the hint), so we added all used IP-Addresses and prefixes to get started.
But if I add a new device and assign an IP-address we previously added, a duplicate IP-address is generated. We would like to assign a device to an IP-address already in NetBox but cannot figure out, how to do that.

**Comment by Know1** [comment]
Issue #610 is sort of related. I think when adding a new device the ability to assign an IP easier would mean less need to go in reverse try to apply a device once the IP is created.
