### ISSUE TITLE
Semantic of port speed / upstream speed of a Circuit Termination

### ISSUE THREAD

**Issue by zorun** [digitalocean/netbox#2117]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.5
* NetBox version:  2.3.3

### Description

When creating a Circuit Termination, the semantic of "upstream speed" vs. "port speed" does not seem to be consistent:

- in the edition view, I understood that "port speed" is the speed of the physical port (10G in my case) while "upstream speed" is the actual speed of the circuit in the provider's network (1G in my case)
- but in the circuit view, it renders as if the termination has a different speed depending on the direction (inbound / unbound)

Here are the screenshots of each view:

![Circuit view](https://files.polyno.me/img/netbox-speed-edit.png)

![Edition view](https://files.polyno.me/img/netbox-speed.png)

What is the actual semantic of these two "speed" fields?

**Comment by jeremystretch** [comment]
The assumption is that if an upstream speed has been defined, the user wants to show allocated upstream and downstream rates, rather than line rate.

```
{% if termination.upstream_speed %}
    <i class="fa fa-arrow-down" title="Downstream"></i> {{ termination.port_speed|humanize_speed }}
    <i class="fa fa-arrow-up" title="Upstream"></i> {{ termination.upstream_speed|humanize_speed }}
{% else %}
    {{ termination.port_speed|humanize_speed }}
{% endif %}
```

**Comment by amuckart** [comment]
I can see two options for this. Rename "Upstream" to "Provisioned speed" or something similar, or model both up-and down stream speeds. 

I don't know if enough people are still stuck with asymmetrical circuits in this day and age to make the latter option worthwhile.

**Comment by jeremystretch** [comment]
Going to keep this as is for now. We might still modify the fields in the future.

**Comment by mgob** [comment]
> I can see two options for this. Rename "Upstream" to "Provisioned speed" or something similar, or model both up-and down stream speeds.
> 
> I don't know if enough people are still stuck with asymmetrical circuits in this day and age to make the latter option worthwhile.

There's plenty of cases still where this holds true, we for instance have a lot of SD-WAN based locations which utilize broadband circuits as one of the available paths such as Coax/DSL/FTTH/GPON and some of them are asymm still so reworking this would be quite useful to us.

https://groups.google.com/forum/#!topic/netbox-discuss/UyfaBTH1WXE
