### ISSUE TITLE
Add GPS coordinates of Site/Facility

### ISSUE THREAD

**Issue by zorun** [digitalocean/netbox#2118]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Description

It would be nice to add a field for the GPS coordinates of a site/facility.

Our use-case would be to pull all sites via the Netbox API, and display them on a map (along with circuits between sites).

**Comment by funzoneq** [comment]
I did this by adding two custom fields to the Sites model. Latitude and Longitude. They then show up on the API via the custom_fields option.

**Comment by jeremystretch** [comment]
Implemented in 258373f on the `develop-2.4` branch.
