### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#212]
Their are paths that are hardcoded in various files, this means if you want to run netbox in a subdirectory on an existing webserver you have to manually edit a lot of files.

**Comment by mdlayher** [comment]
To clarify, do you want to allow the root of the API to be specified via config?  So if you set the root as `/netbox/`, an API call would be something like `/netbox/api/ipam/vlans`?

**Comment by Gelob** [comment]
@mdlayher The goal would be to be able to run netbox in a subdirectory and also have that subdirectory be named whatever we want. The hardcoded /api/ paths are a good example where this is hardcoded. We are currently doing this and I've included a diff of all the files we had to edit. I've had to edit out some other changes so the diff line numbers are not 100% accurate. 

https://gist.github.com/Gelob/0914c3ee5219b70e63d15b2b70b9d9bc

My thought would be to have a variable in configuration.py to specify the path like BASE_URL but there may be better ways to handle this with Django or abstract it out so you don't have to specify.

**Comment by mdlayher** [comment]
Seems reasonable to me to have a base path like that prepended to NetBox paths.

**Comment by Gelob** [comment]
The upgrade.sh script should also detect the directory it is in and not hardcode paths

**Comment by marvnrawley** [comment]
Thanks for updating and linking my issue. I've ignored the API hardcodes as I don't use the API feature yet, but have had a dig around.

**Comment by marvnrawley** [comment]
Could we maybe get this roadmapped for 1.6? It's only a few variables which need to reference BASE_DN being either / or /netbox or /whatever_I_chose.

**Comment by marvnrawley** [comment]
Found a few more files with hardcoded paths for the API - the below prevent the 'Mark Connected' buttons from working.

`netbox/templates/dcim/device.html:    return toggleConnection($(this), "/api/dcim/console-ports/");
netbox/templates/dcim/device.html:    return toggleConnection($(this), "/api/dcim/power-ports/");
netbox/templates/dcim/device.html:    return toggleConnection($(this), "/api/dcim/interface-connections/");
`

And also in netbox/templates/_base.html you need to change this

'                <a class="navbar-brand" href="/">
                    <img src="{% static 'img/netbox_logo.png' %}" />
                </a>'

To this (adjust for your subdirectory as needed)

'                <a class="navbar-brand" href="/netbox">
                    <img src="{% static 'img/netbox_logo.png' %}" />
                </a>'

**Comment by jeremystretch** [comment]
833499f introduced `BASE_PATH` which allows the user to define an arbitrary URL path via which NetBox is accessed.

18a5a96 extended the `APISelect` widget to use `BASE_PATH`. This is a bit of a hack but should be sufficient until I get around to overhauling `APISelect`.
