### ISSUE TITLE
Netbox should show interface form factor in device view

### ISSUE THREAD

**Issue by raddessi** [digitalocean/netbox#2121]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6.2
* NetBox version:  2.3.3

### Description

When viewing a device the form factor of ports is no longer shown, I think this must have disappeared in the 2.3.2 or 2.3.3.

The only columns shown now are:

Name | LAG | Description | MTU | MAC Address | Connection

**Comment by jeremystretch** [comment]
The form factor is noted as title text when hovering over the interface name. It's been that way for a long time. It's not included in the table because interfaces with the same type/prefix typically have the same form factor.
