### ISSUE TITLE
Add documentation fields to connections

### ISSUE THREAD

**Issue by lancesdavis** [digitalocean/netbox#2122]
### Issue type
[ X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.8
* NetBox version:  2.3.3

### Description
Add a cross-connect id and a reference field to interface / console / power connections - these are needed to document the connection.  Could additionally add a 'cables' module including cross-connect ids of connections and circuits. 
Alternative would be to be able to link the connection to be both ends of a circuit and document as a circuit.

**Comment by jeremystretch** [comment]
Please see #20

**Comment by lancesdavis** [comment]
I saw that - but what I am proposing is much simpler - purely a reference field on a connection ?

Is #20 likely to see any progress towards implementation anytime soon ?

Thanks
Lance

**Comment by DanSheps** [comment]
#20 is slated for v2.5 according to the [milestones](https://github.com/digitalocean/netbox/milestones)
