### ISSUE TITLE
Error accessing status for device via napalm

### ISSUE THREAD

**Issue by lancesdavis** [digitalocean/netbox#2123]
### Issue type
[ ] Feature request 
[ X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.8
* NetBox version:  2.3.3

### Description
Error accessing status for device via napalm - error popped up on clicking status and status was not shown.
![netbox error](https://user-images.githubusercontent.com/38127506/40574987-9309aeae-60d4-11e8-963a-9f27d3c57ace.PNG)

**Comment by jeremystretch** [comment]
This is a bug in [the NAPALM driver](https://github.com/napalm-automation/napalm); not something we can fix in NetBox unfortunately. NetBox just acts as a proxy.
