### ISSUE TITLE
LAG interfaces can be connected via CSV import

### ISSUE THREAD

**Issue by mandarg** [digitalocean/netbox#2127]
An example scenario:
- There are two devices, `test1` and `test2`.
- `test1` has a LAG bundle `po1` consisting of `intf0/1` and `intf0/2`
- `test2` has a LAG bundle `po2` consisting of `intf0/1` and `intf0/2`
- `test1:intf0/1` is connected to `test2:intf0/1`
- `test1:intf0/2` is connected to `test2:intf0/2`

In order to represent that their LAG bundles are also "connected", I connected up `test1:po1` to `test2:po2` as well (connections displayed as below):

<img width="799" alt="interface-connections-view" src="https://user-images.githubusercontent.com/160992/40686809-914ed640-6366-11e8-8b4b-1ee61ed99f89.png">

Fig 1: **Devices > Interface connections** view

------------------------

_Note that this is not possible to easily do using the standard UI controls (there is no connection button on a LAG interface). However, it works as expected through "Import Connections" or the API._

At this point, I can view `test1:po1` and `test2:po2` as connected in the Interface Connections view, but if I go to the `test1` interface view or the `test2` interface view (both shown below), I cannot see the connection. 

<img width="1056" alt="test1-interfaces" src="https://user-images.githubusercontent.com/160992/40686836-a5a2ff04-6366-11e8-8443-e91195229eef.png">

Fig 2: `test1` Interfaces section

------------------------
<img width="1059" alt="test2-interfaces" src="https://user-images.githubusercontent.com/160992/40686842-a7b6541c-6366-11e8-8e17-1f0b3f7ba2a3.png">

Fig 3: `test2` Interfaces section

------------------------

Should this be rectified? For example, I would expect a connection to `test2:po1` to be shown against `po1` in the interfaces view of `test1` above (Fig 2.)

**Comment by jeremystretch** [comment]
This is a bug: it should not be possible to connect LAG interfaces, as they are virtual. It seems the validation is not being enforced during import.
