### ISSUE TITLE
Used ip filter for a prefix via the API

### ISSUE THREAD

**Issue by funzoneq** [digitalocean/netbox#2129]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  v2.3.3

### Description
In netbox we have the view of which IP addresses are used in a specific prefix: https://netbox.paxio.net/ipam/prefixes/4/ip-addresses/ . It uses the PrefixIPAddressesView and prefix.get_child_ips() function. However there isn't a similar function for the API.

I would like to get a filter on the /ipam/ip-addresses/ resource to be able to filter on the parent prefix ID.

**Comment by jeremystretch** [comment]
In the interest of consistency and to avoid redundancy, all API endpoints abide by the same index/filter strategy, which doesn't always mirror the web UI. To retrieve these IPs via the API, you'll need to call the IP addresses endpoint with the `parent` and `vrf` or `vrf_id` filters. For example:

    GET https://netbox/api/ipam/ip-addresses/?parent=192.0.2.0/24&vrf_id=10

**Comment by andrewsav-datacom** [comment]
@jeremystretch but what if we do not have virtual routing in our networks, how are they linked then?
