### ISSUE TITLE
Documentation for querying custom fields in API missing

### ISSUE THREAD

**Issue by friek** [digitalocean/netbox#2138]
### Issue type
[ ] Feature request 
[ ] Bug report      
[X] Documentation   

### Environment
* Python version:  3.6.2
* NetBox version:  2.3.4-dev

### Description
After hours of searching through documentation and source code how to query custom fields through the API, I eventually found out that this is actually possible by adding a `cf_customfieldname=search_value` as a query parameter.

This isn't very obvious unfortunately and I can't find anything in the documentation describing this functionality. Therefore, I think it'd be handy to add proper documentation on the API documentation site.

Thanks.

**Comment by a31amit** [comment]
@friek Thanks for even reporting here, I was struggling with the same thing. It is very useful.
