### ISSUE TITLE
Can't use NAPALM, "Status" "LLDP Neighbors" "Configuration" are disabled.

### ISSUE THREAD

**Issue by fomik2** [digitalocean/netbox#2139]
### Issue type
[ ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:   python --version
Python 2.7.5
 python3 --version
Python 3.4.8
* NetBox version:  (v2.3.3)

I've try to use NAPALM but can't do that, because "Status", "LLDP Neighbors" and "Configuration"tabs in particular device are disabled. I've assign primary ipv4 address for that device and added napalm username and password to configuration.py and reload server, but nothing changes.
![image](https://user-images.githubusercontent.com/7394246/40901155-9dd668d6-67d7-11e8-9224-a214d2b7a8e7.png)

**Comment by eriktm** [comment]
The tabs are typically disabled because some requirement is missing. Have you made sure to set the correct platform on the device, and set the NAPALM driver for that platform?

**Comment by fomik2** [comment]
I think I should select appropriate NAPALM driver, but how can I determine what driver should I select?
What should I type in NAPALM Driver section for IOS devices? I tried this - "napalm.ios.ios.IOSDriver" - but NetBox show me javascript message with server error title.
```
>>> from napalm import get_network_driver
>>> get_network_driver('ios')
<class 'napalm.ios.ios.IOSDriver'>
>>> 
```

**Comment by poofik** [comment]
Under **Platforms** you can assign NAPLAM driver "ios" or "junos" then assign a platform to a device.

**Comment by nrtc** [comment]
I am having the same issue as fomik2, it give me and error when I try to click those tabs, Not sure if missing some configuration. Attached is the screenshot of error.
![capture](https://user-images.githubusercontent.com/39968504/41039930-f0df04c4-6968-11e8-87f6-b9c513d5fcbe.PNG)

**Comment by fomik2** [comment]
you have to do that: Under Platforms you can assign NAPLAM driver "ios" or "junos" 
and make sure  ssh connection from netbox server to your devices is ok.

**Comment by jeremystretch** [comment]
> because "Status", "LLDP Neighbors" and "Configuration"tabs in particular device are disabled.

Hovering the mouse pointer over the tab will explain why it is disabled.

> I am having the same issue as fomik2

@nrtc This is a different issue. If you believe it is a bug, please open a new issue and complete the bug report template.
