### ISSUE TITLE
Netbox UI status and LLDP pages are not showing up, the API works fine

### ISSUE THREAD

**Issue by AmbicaY** [digitalocean/netbox#2142]
### Issue type
[ ] Bug report      

### Environment
* Python version:  3.5.2
* NetBox version:  v2.3.3

### Description
I am able to query the device status details via the API call:
http://sc-netbox-test-01/api/dcim/devices/402/napalm/?method=get_facts

But on the UI:
http://sc-netbox-test-01/dcim/devices/402/status/
I get the error:
{"detail":"Error connecting to the device at *****: "}

I checked this on a Cisco Nexus device (napalm driver: nxos_ssh)

Here is my napalm config:
NAPALM_USERNAME = '*********'
NAPALM_PASSWORD = '*********'
NAPALM_TIMEOUT = 60
NAPALM_ARGS = {
    'secret': NAPALM_PASSWORD,
}

Similarly, for LLDP Neighbors, there is no error, but it does not show up any data. But the API call works fine: http://sc-netbox-test-01/api/dcim/devices/402/napalm/?method=get_lldp_neighbours

The configuration tab opens up fine though.

**Comment by jeremystretch** [comment]
> I get the error:
> {"detail":"Error connecting to the device at *****: "}

This indicates that either NetBox cannot reach the device, or there is an issue with the NAPALM driver. (Neither of these can be addressed in NetBox.)

> Similarly, for LLDP Neighbors, there is no error, but it does not show up any data.

LLDP neighbors will only display if your device's interfaces are correctly named. You'll need to post the list of configured interfaces as well as the full API response (not a link).

**Comment by AmbicaY** [comment]
I think I understood the problem about the LLDP neighbors:
when I do a "show lldp neighbors", the interfaces are listed as like: "Eth1/50", but in the "show interface" command the interface name is like "Ethernet1/50". 

Is there anything netbox can do to fix this?

Coming to the netbox status page, if there was an issue with connectivity to the device or the NAPALM driver, even the api page should not work, right?

**Comment by jeremystretch** [comment]
> when I do a "show lldp neighbors", the interfaces are listed as like: "Eth1/50", but in the "show interface" command the interface name is like "Ethernet1/50".

You'll need to rename the interfaces as you have them defined in NetBox so that they match what the device is reporting. This can be scripted out in the shell to rename everything automatically.

**Comment by jwhitelan** [comment]
For some reason mine is trying to browse to the device and not ssh. 

![image](https://user-images.githubusercontent.com/37033178/46265463-a9861080-c4f4-11e8-9f72-11c2796fa421.png)
