### ISSUE TITLE
PUTs to Site Endpoint Requires Value for time_zone

### ISSUE THREAD

**Issue by zachmoody** [digitalocean/netbox#2143]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.6.7
* NetBox version:  2.4-dev, but includes previous versions as well.

### Description
More details over at digitalocean/pynetbox#59, but when the `time_zone` field is present and null we get an error saying it can't be null. Omitting the field doesn't return an error.

**Comment by zachmoody** [comment]
Empty string works too. The only thing causing pynetbox to go sideways is that GET returns a `null`. So if the field goes unchanged by the user, it simply gets added as-is to the PUT.

**Comment by jeremystretch** [comment]
The documentation for `[django-timezone-field](https://github.com/mfogel/django-timezone-field/blob/master/timezone_field/fields.py)` states that None should be a valid value for both input and output, so let's stick with your approach.

**Comment by nue-melexis** [comment]
Hi,

I still get this issue with version 2.4.3.
Check master commits https://github.com/digitalocean/netbox/commits/master?after=8d4329197a916ed5704ce774a77ec1f59c8a6328+279

Browsing files:
Still OK:
[Post-release version bump @jeremystretch committed on Jul 2](https://github.com/digitalocean/netbox/blob/302c14186a2020fa2a241cb0b0bbe1fd9dc0a367/netbox/dcim/api/serializers.py)

NOK:
[Closes #2211: Removed Python 2 instructions from the installation docs @jeremystretch committed on Jul 2
](https://github.com/digitalocean/netbox/blob/104bd1b45f6a6f3b5d94fef4126c3b49413b33a3/netbox/dcim/api/serializers.py)

Can you hint me? (This history for the file at that 2 revisions deviates from March 1st)
