### ISSUE TITLE
Nested Parent/Child Physical Devices

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#2145]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  Not relevant
* NetBox version: v2.3.3 

### Description
Proposed functionality:
Shift from a single parent to single child relationship for physical devices, to a single parent to multi-child configuration.

Use case:
Within the Juniper MX480 multi-line card chassis we've deployed, there are FPC line cards which host SFP MIC cards. In order to show proper layout (MX480->FPC line card->MIC), a second layer is required.
I believe this could be achieved by modifying the child device classification to allow device bays within it as well (check box stating the device has device bays); the parent node would simply be the top level device that cannot be placed in a device bay itself.

**Comment by jeremystretch** [comment]
Sounds like you want #824
