### ISSUE TITLE
NAPLAM Error

### ISSUE THREAD

**Issue by nrtc** [digitalocean/netbox#2146]
I am new to this
getting this error when clicking on Status and other tabs for NAPLAM
![err](https://user-images.githubusercontent.com/39968504/40999763-d573bb60-68d9-11e8-8043-24e622c61f70.PNG)

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
