### ISSUE TITLE
Allow netbox to generate circuit IDs.

### ISSUE THREAD

**Issue by nschmalenberger** [digitalocean/netbox#2151]
### Issue type
[ X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.3

### Description
The circuit ID field is mandatory when adding a circuit. In case of "circuits" used within the same organization, such as between cages of the same customer in a colo, it would be useful to have an option for Netbox to generate the ID.

No third party libraries should be needed. This could mean a schema change, or just to use the existing id column in circuits_circuit. In the GUI it could be a checkbox to use the Netbox circuit id, and in the API there could be some word to put in the field that means to use the Netbox id. If the box is checked maybe it would also put the word in the cid field since in the schema it is NOT NULL. Maybe there is a better way than a reserved word?

**Comment by jeremystretch** [comment]
Sorry but this is firmly out of scope for NetBox. Every organization has their own naming preferences, and I'm not about to go down that rabbit hole.

**Comment by nschmalenberger** [comment]
Currently I just identify these circuits by the cross connect ID given to me by the data center, but my provider circuits have those too as well as actual IDs from the provider. It also seems that if the physical cable plant feature is implemented, the cross connect IDs would belong there instead of as circuit IDs. So the analogous thing here would be for me to generate IDs and my preference would be just integers which Netbox already does anyway. So I'm just hoping for a way to use the Netbox circuit ID as my circuit ID.

I can just see what was the last used ID and increment in my head to fill in the cid field the same as the Netbox id will be. Is there a better way to think about this? Should I post to the mailing list and ask how other people do it? I know too there are lots of ways to make circuit IDs meaningful, but I'd be happy with just serial integers. Sorry to bother.
