### ISSUE TITLE
NAT - import addresses with nat 

### ISSUE THREAD

**Issue by cezaronne** [digitalocean/netbox#2153]
### Issue type
[ NAT import/export] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  <Python 3.4.8>
* NetBox version:  <2.3.3>

### Description
We are using netbox (v2.3.3)- we are trying to import Ip addresses with NAT - as described (https://netbox.readthedocs.io/en/latest/data-model/ipam/#ip-addresses) we select as  Role nat statement - error is : Select a valid choice. Nat is not one of the available choices 
Do you have some suggestion for adding NAT addresses - we have thousands addresses with nat correspondent and we are trying to use Netbox to manage the ip address pool.
Also if using the export option in IPAM, for addresses with NAT, the CSV does not include the NAT role, it just  exports both addresses with no additional field for NAT.

Thank you for your help.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
