### ISSUE TITLE
[Question] Parent / Child relationship

### ISSUE THREAD

**Issue by LordBoBCUP** [digitalocean/netbox#216]
Hi,

Im on v1.1.0-dev and I am struggling to assign a parent/child relationship to existing objects. I have a 10U device type (chassis) setup already and another device type (blade) setup as a child with 0U set. When I change the chassis device (still 10U) to be a parent, and the blade to be a child with 0U I cant set it to the same any of the already used chassis slots. Have I missed something silly somewhere, or is this in fact a bug?

**Comment by jeremystretch** [comment]
Sorry, I'm not sure I understand what you're trying to do, but the workflow generally goes like this:

1. Create a device type for your chassis. This is what will get mounted in the rack.
2. Assign a number of device bays to the chassis device type.
3. Create a device type for your subdevice. These devices will be installed within the chassis device.
4. Create a chassis device and mount it in a rack.
5. Create subdevices and install them in the chassis device.

Hope that helps!

**Comment by LordBoBCUP** [comment]
Thanks Jeremy! Yes I had missed a step which I hadn't seen in the new 1.1.0-dev release I was running. All sorted now!
