### ISSUE TITLE
Storing authentication metadata against services

### ISSUE THREAD

**Issue by wrouesnel** [digitalocean/netbox#2162]
### Issue type
[x] Feature request 

### Environment
* Python version:  3.6
* NetBox version:  2.3.3

### Description

Netbox already implements the concept of tracking notable network connected services on a device, an idea which I built out (in a flat file format) for tracking applications in our local environment. It is however missing a related concept which is storing a record of "how to authenticate" to that application on that device, presuming the user is the current one.

Against each application on devices (internally) we store structured data which describes in a loose-fashion what type of authentication system is being used for that application, and how the details should be acquired by the user (these are generally termed as "lookups").

By way of example this is a sample application structure for a server:
```json
      "application_services": [
        {
          "name": "sssd",
          "authentication": [
            {
              "type": "federated-password",
              "id": "ad-domain",
            },
            {
              "type": "local-password",
              "user_lookup": {
                "type": "literal",
                "value": "root"
              },
              "password_lookup": {
                "type": "vault",
                "uri": "https://vault.internal",
                "path": "/secret/apps/static/admins/production/root_cluster_password",
                "key": "value"
              }
            }
          ]
        },
        {
          "name": "sudo",
          "authentication": [
          {
              "type": "federated-password",
              "id": "ad-domain"
          },
          {
          "name": "ssh",
          "authentication": [
            {
              "type": "shared-authenticator",
              "authenticators": [
                "sssd"
              ]
            }
          ],
          "listens": [
            {
              "ip": "0.0.0.0",
              "port": 22,
              "protocol": "tcp"
            }
          ]
        }
      ]
```
Without being overly specific, this attaches some institutionally-specific authentication knowledge which can be stored in other systems - specifically the "type" of authentication implemented (local-password or federated-password are common for us, since simple systems like KVMs may not support or not be configured with LDAP/Kerberos auth) and an ID - again, institutionally specific - which allows client applications to pick a profile to use to authenticate - i.e. the federated-password is not _specifically_ LDAP, it's just a coding  that the password is not managed by the device itself.

**Comment by jeremystretch** [comment]
IMO this is out of scope for NetBox but I'll leave this open for discussion.

**Comment by candlerb** [comment]
Custom Fields on Service?

**Comment by jeremystretch** [comment]
> Custom Fields on Service?

Sure. #1687
