### ISSUE TITLE
Duplicate Devices

### ISSUE THREAD

**Issue by jenslink** [digitalocean/netbox#2164]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description

A customer just mentioned that it would be nice if you could duplicate devices in the GUI. e.g. Click duplicate change name and S/N and keep the rest (interfaces, descriptions, vlans, ...)

**Comment by jeremystretch** [comment]
See #33
