### ISSUE TITLE
Asset Tag field requires exact match in filtering

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#2166]
### Issue type
[ x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5
* NetBox version:  2.3.3

### Description
The `asset_tag` field on the Device model does not allow for partial string matching with filtering. This causes annoyances related to inconsistency because other fields like name and serial number support partial matching. While an asset tag is generally unique, for longer tag IDs, operators commonly wish to strip the first part of the tag which is not unique when searching.

I would like to see the `asset_tag` field use the icontains filter in the DeviceFilter
https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/filters.py#L512

**Comment by jeremystretch** [comment]
Just to clarify, this will enable partial matching of the `asset_tag` field in search only (e.g. `?q=ABC123`). Filtering directly on the `asset_tag` field (e.g. `?asset_tag=ABC123`) will still require an exact match.
