### ISSUE TITLE
Add Extreme Networks SummitStack as port types

### ISSUE THREAD

**Issue by tradiuz** [digitalocean/netbox#2168]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.5

### Description
Adding support for Extreme stacking ports is fairly easy, just requires updating the constants.py to include the SummitStack, SummitStack128, and SummitStack512 port types under stacking.

**Comment by candlerb** [comment]
I think it was unwise to have Cisco and Juniper stacking interfaces in the Netbox core, as this opens the door to every possible vendor's type of proprietary stacking port being requested.

A user-customisable table of interface types (similar to Device Type) would be the ideal solution.  Then if you have (say) GPON interfaces, you can document those too.

In the absence of that, I'd suggest adding a generic "Other" under Stacking Port.  That doesn't completely help people whose vendors have more than one port type, but there is already a free-form "Description" field that can say whether it's a type Foo or Bar.

**Comment by jeremystretch** [comment]
My rule is that if it's a legitimately unique physical interface type in common usage, we'll add it. Sometimes "stacking" ports are really just standard Ethernet interfaces which have been designated for a specific function. Extreme appears to use a combination of standard and proprietary interfaces, so we can add the proprietary ones (taken from [this data sheet](http://www.usedcomp.de/pdf/Extreme-Networks-SummitStack-Virtual-Chassis-Stacking-Technology-Technical-Brief.pdf)):

* SummitStack
* SummitStack-128
* SummitStack-256
* SummitStack-512

**Comment by tradiuz** [comment]
I agree with @candlerb that having a table would be the ideal solution (this is how RackTables does it).  That would give room for having server interconnects (SAS HBA -> Disk Shelf). 
However, in the interim, I'd like to add support for the platform I spend all day on.  I'll update my PR with SummitStack-256.
