### ISSUE TITLE
New Install on CentOs takes 10s to return a webpage

### ISSUE THREAD

**Issue by brianary1010** [digitalocean/netbox#2172]
### Issue type
[ ] Feature request 
[x ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.8
* NetBox version:  2.3.4
* Django 1.11.13

### Description
New Install on CentOS 7 VM using nginx. 
VM has 8GB of RAM and 4 processsors. 
The memory only appears to consume 400 500MB at any given time.
When I click on any web page it takes up to ten seconds to load.
When I run the following command: 
time curl -s -H "Content-Type: application/json" -H "Accept: application/json; indent=4" http://localhost:8000/api/dcim/devices/?limit=500 > /dev/null
real    0m10.549s
user    0m0.001s
sys     0m0.008s

Any help much appreciated!

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
