### ISSUE TITLE
Reserve/Book device ports

### ISSUE THREAD

**Issue by Za66ax** [digitalocean/netbox#2174]
Issue type

[ X ] Feature request 
[ ] Bug report 
[ ] Documentation

Environment

•	NetBox version: 2.3.4

Description
It would be nice to be able to connect an interface to an object that’s not in the database (i.e a host), today you’re required to have a device registered to be able to make a connection. For network devices/virtual machines that’s awesome. But if you are required to register all hosts I fear that the database would become cluttered with non-essential data. The port could maybe just be marked as either connected or reserved.
This would work perfectly with feature request #1957.

**Comment by jeremystretch** [comment]
NetBox supports "planned" connections. This is the most succinct way of representing a future connection. It does require that you add both hosts to the database, but the future host can also be designated as "planned."
