### ISSUE TITLE
Add the ability to map VLANs to clusters

### ISSUE THREAD

**Issue by kasimon** [digitalocean/netbox#2175]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 2.7.13
* NetBox version: 2.3.3

### Description
In order to keep track about which vlans are available on which clusters, a mapping vlans <-> clusters would be very helpful. We are using a lot of vlans to separate subnets (several hundreds) and these are connected to different clusters. So in case there is more demand for this feature, we certainly would appreciate it.

**Comment by jeremystretch** [comment]
I'm going to close this out as, although it appears to be popular, there hasn't been any discussion regarding the proposed data model changes. Please feel free to resubmit this issue if you'd like to propose a detailed schema change.
