### ISSUE TITLE
Add VLAN state 'planned'

### ISSUE THREAD

**Issue by kasimon** [digitalocean/netbox#2176]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 2.7.13
* NetBox version: 2.3.3

### Description
Please add the state 'planned' to VLANs. There already are the states Active, Reserved and Deprecated, but we would like to add VLANs to netbox once we requested their creation from our networking team, and tagging them as "Reserved" does not really fit well.

**Comment by jeremystretch** [comment]
"Planned" doesn't really make sense for a resource allocated from a finite number space. All VLANs (1-4094) are essentially planned already. Why does the "reserved" status not work?

**Comment by kasimon** [comment]
The use cases I'd like to differentiate would be "Reserved" = "This VLAN (-Range) was handed over to another department, they can do with it whatever they want, we have no control over it" and "Planned" = "We are currently preparing to use this, but it's not yet deployed to production".

**Comment by LBegnaud** [comment]
Could you not use "Active" and assign the other department as a tenant on the VLAN?

**Comment by kasimon** [comment]
Yes, that would certainly be a solution. Nevertheless if possible I would prefer states that represent their organisational purpose more directly without a 'mental mapping' required.

**Comment by DanSheps** [comment]
Your state should describe your state (whether it is active, deprecated or reserved), tenant should describe who it actually belongs to.

**Comment by jeremystretch** [comment]
Closing this out as I really don't see the use of a "planned" state.
