### ISSUE TITLE
Show serial number of device in rack view

### ISSUE THREAD

**Issue by chowell5** [digitalocean/netbox#2177]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  
* NetBox version:  

### Description

It would be useful if the popover that you receive when viewing a device in a rack view showed the serial number, and not just the asset tag. We use serial numbers more, and this will help us to verify that the information contained in Netbox is correct, more easily.

**Comment by chowell5** [comment]
Asset tag was added to bubble in #494

**Comment by jvanderaa** [comment]
Could this be expanded to a settings page that would allow it to be customized based on company preferences? Some may want asset tags, others may want serial numbers. Really make it a check box for the hover settings?

**Comment by chowell5** [comment]
I don't think it's worth the extra complexity to add a setting for this.

**Comment by jeremystretch** [comment]
Implemented in #2178 by @chowell5
