### ISSUE TITLE
Support CDP Neighbors

### ISSUE THREAD

**Issue by orgito** [digitalocean/netbox#2187]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.4.8
* NetBox version:  2.3.4

### Description
Add the option to list CDP neighbors beside LLDP neighbors.

The use case for that are networks that do not have LLDP enable. We have some legacy Cisco based network where enabling LLDP is not an option.

No need for extra libraries as napalm can be used for that.

**Comment by orgito** [comment]
I'd be happy to work on this if it is considered useful.

**Comment by dBitech** [comment]
I would be supportive of this feature as I too have legacy CDP

**Comment by jeremystretch** [comment]
NetBox doesn't interact with devices directly; live data such as LLDP neighbors is retrieved using the [NAPALM library](https://github.com/napalm-automation/napalm/), which does not support CDP. It's unlikely that NAPALM will introduce support for CDP as it's an obsolete proprietary protocol.

**Comment by orgito** [comment]
Napalm allows running arbitrary code. This can be solved by running `show cdp neighbors` against the device and parsing the output. 
CDP is a proprietary an obsolete protocol but unfortunately still being used in the real world. 
I added support for CDP to the `ios_interface` ansible module and would like to work on adding it to NetBox, if there is a chance of the PR being accepted.

**Comment by jwhitelan** [comment]
I am guessing that this idea never took off? I would use it as many of our Cisco core routers do not support LLDP.

**Comment by netpanic** [comment]
bump

**Comment by orgito** [comment]
Apparently, the solution is to get back to 
https://github.com/napalm-automation/napalm/pull/601

If the functionality is available in napalm it would be simple to add it to netbox.
