### ISSUE TITLE
Allow to set transport parameter for napalm driver in the platform definition.

### ISSUE THREAD

**Issue by orgito** [digitalocean/netbox#2188]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.4.8
* NetBox version:  2.3.4

### Description
The `ios` napalm driver has a transport argument that can be set to telnet. That would allow the "dynamic" functionalities of the UI that rely on napalm to work with Legacy IOS devices that do not support ssh but support telnet.

**Comment by jeremystretch** [comment]
Should be covered by #2029
