### ISSUE TITLE
Decrypting with password protected private key

### ISSUE THREAD

**Issue by Yentel** [digitalocean/netbox#2189]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  Unknown (no server access)
* NetBox version:  2.3.1

### Description
When a user uploads a self generated public key to Netbox and this key is approved, he should be able to decrypt passwords by pasting the private key inside the prompt box.

The issue here is that this user has created a public-private keypair protected with a password.
When he pastes his private key, the prompt is closed without any info.
When the keypair is changed to a selfgenerated one without password, this works like it should.

Is it possible to add a prompt for a password if the private key is password protected or to give a notification to the user that password protected private keys are not supported?

Thanks for all your work guys!
Yentel

**Comment by jeremystretch** [comment]
This seems like overkill. The key is only intended to be used with NetBox to begin with. I've actually been contemplating wrapping the public/private key pairing internally and just using a key passphrase to unlock secrets. I'll leave it open for discussion though.

**Comment by Yentel** [comment]
Yeah, that's correct, unlocking with a key passphrase would be even better concerning UX, but as long as it's allowed to upload self-generated keys, a pop-up with an error would be a nice addition to the UX if the private key you enter in the pop-up requires a password for the public/private keypair to be checked. Even if it would only say "Netbox does not support password protected private keys" instead of nothing right now :-)

Thanks for all the work!
Yentel

**Comment by jeremystretch** [comment]
> Even if it would only say "Netbox does not support password protected private keys" instead of nothing right now

Closing this out, but I'll add a note to the user key form indicating this.
