### ISSUE TITLE
A 0U device can be assigned to a rack unit

### ISSUE THREAD

**Issue by insertjokehere** [digitalocean/netbox#2192]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version: 3.6.5 
* NetBox version:  2.3.4 

### Description

When reducing the number of 'U' a rack contains, Netbox does not prevent you from leaving 0U tall devices 'outside' the new size of the rack. When you do this, you will be unable to view or edit the rack. Netbox should probably prevent you from editing the racks' height if doing so would put you into this state.

#### Reproduction
* Create a 2U tall rack
* Create a 0U tall device, add it to the rack in position 2
* Edit the rack to make it 1U high
* Observe that trying to view or edit the rack results in an error page:

```
<class 'KeyError'>

2
```

**Comment by jeremystretch** [comment]
It seems the problem is that we don't validate device type height on unit assignment. It shouldn't be possible to assign a 0U device to a rack unit.
