### ISSUE TITLE
Creating new prefix via API

### ISSUE THREAD

**Issue by vasil166** [digitalocean/netbox#2193]
### Issue type
[x ] Feature request 
[ ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.3
* NetBox version:  2.3.2

### Description

I am trying to create a new prefix via the API. However I am not able to find any documentation about it. I figured out how to create a child prefix on top of prefix ID, but not how to create a parent prefix. Is there such feature in the API?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
