### ISSUE TITLE
search for a single IP address via API

### ISSUE THREAD

**Issue by maznu** [digitalocean/netbox#2194]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

* NetBox version:  bleeding edge

### Description

I want to find out whether an IP address exists in NetBox via the API. Currently it doesn't seem possible to do that, because the only searches available either:

* match by string, which the needs client-side filtering because 192.0.2.1 matches 192.0.2.100 etc
* query by parent, but that can't query an IPv4 /32 or IPv6 /128 (no results returned), so instead you have to query /31 or /127 and again filter client-side for the address you actually wanted

I propose adding `?address=192.0.2.1` as a query endpoint.

**Comment by maznu** [comment]
Submitting a simple 12-line patch: https://github.com/digitalocean/netbox/pull/2195

**Comment by poofik** [comment]
`?q=192.0.2.1`

**Comment by maznu** [comment]
@poofik that will return 192.0.2.100 and about 109 other addresses, and anything that has 192.0.2.1 in the description (e.g. "new address replacing 192.0.2.199") :-(

**Comment by poofik** [comment]
put a slash for subnet and cut it off `/api/ipam/ip-addresses/?q=192.0.2.1/`

**Comment by DanSheps** [comment]
poofik is correct, there is a way to get exact prefixes.

**Comment by jeremystretch** [comment]
While @poofik's approach work, it's a hack. I don't see a reason not expose the `address` field itself.

It's important to note that the address fields includes the IP address _and_ its mask. It seems the most practical approach would be to match any IP address if the mask is omitted. That is, `?address=192.0.2.1` would return IPs 192.0.2.1/24 and 192.0.2.1/32, whereas `?address=192.0.2.1/24` would return only the former.

**Comment by maznu** [comment]
Thanks, @jeremystretch! I didn't like the hack because q=1.2.3.4/ will still return 11.2.3.4 and 21.2.3.4 etc?
