### ISSUE TITLE
Invalid rack group when importing

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#22]
When trying to use the text box for CSV to import racks I get:

```
Record 1 (group): Invalid rack group (site01 - group01)
```

So I manually added a single rack to the group, exported it, then tried re-importing it only to face the same issue.

```
site01,group01,r00,site01.r00,42
```

**Comment by jeremystretch** [comment]
Confirmed bug. This is due to an incorrect assumption during import that RackGroup names are unique. Fixing.
