### ISSUE TITLE
Handle inherited associations same as direct

### ISSUE THREAD

**Issue by alesz** [digitalocean/netbox#2202]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6
* NetBox version:  2.3.4

### Description

Steps to reproduce:
1. Add tenant A
1. Add vrf B and associate it with tenant A
1. Add prefix C and associate it with vrf B. Don't associate with tenant A.

Observed:

Displaying prefix C shows Tenant A with Inherited tag. Displaying tenant A counts prefix C in stats.  Prefix is associated with tenant via vrf object (inherited tag) if tenant field is not set. 
Clicking on prefixes in tenant A stats opens `/ipam/prefixes/?tenant=A`. 

Error:

List of prefixes is empty, tenant search filter shows A(0). Setting tenant to -- None -- displays prefix correctly.  

Expected:

prefix behaves in same way with inherited tenant as with associated one.

**Comment by jeremystretch** [comment]
I think this highlights how fragile the concept of inherited tenancy is, not to mention that it's completely absent in the REST API. I think we're better off just ditching it.
