### ISSUE TITLE
Webhook content type update not correctly taking effect

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#2203]
### Issue type
[ ] Feature request 
[ x ] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.6
* NetBox version:  develop-2.4

### Description
When a Webhook's content type (models for which the webhook is attached to) is updated, to remove the current model and add a new one, the old model is not removed from the Webhook and thus the Webhook still responds to events of the old model.

**Comment by jeremystretch** [comment]
I don't like the idea of introducing another dependency just to cache a single value. Why does it need to be cached in the first place? It's just one additional database query on save/delete, correct?

**Comment by lampwins** [comment]
Right, the idea was to cache the webhook instances so that extra query is not needed whenever a signal is fired. I suppose in hindsight it is a bit of a premature optimization. We can always rip the cache layer out for now, and add it back if the feature proves to be a performance bottleneck.

**Comment by lampwins** [comment]
Actually, we could just move the Webhook DB query inside the RQ worker, thus eliminating my own performance concern. I will work on that.
