### ISSUE TITLE
Circuits are not allowed to be terminated on LAG interfaces

### ISSUE THREAD

**Issue by Ichabond** [digitalocean/netbox#2205]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.10
* NetBox version:  2.2.7

### Description
Steps to reproduce:
* Use the API to attach a circuit to a LAG interface
* Try to update the interface
=> ```Virtual and wireless interfaces cannot be connected to another interface or circuit. Disconnect the interface or choose a suitable form factor.```

Expected behaviour:
LAGs should be allowed to have circuits terminated on, as certain circuits, such as L3 circuits with transit providers can be terminated and identified by a service id that is specific to the aggregated link.

**Comment by jeremystretch** [comment]
A circuit is a physical link and must be connected to a physical interface. While you may have a service delivered via an aggregated set of physical links, each of those is a separate circuit with its own ID.

**Comment by Ichabond** [comment]
If that's the case, then we should de-aggregate the L2 and L3 termination on circuits, and allow for the L3 termination of a circuit to land on a lag or vlan interface
