### ISSUE TITLE
Additional information for sites

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#221]
Phone, fax and perhaps basic contacts info for:

-noc
-support
-sales

**Comment by ryanmerolle** [comment]
I think this feature request can be added to the current feature request #158.  This request can probably be closed and details added to #158 accordingly.

**Comment by bellwood** [comment]
So per #158 you're supposing a contacts section where in contacts can be related to just about anything?

If so (kindly confirm?) then yes this would be dupe and I will close and append.

Thanks =)

**Comment by ryanmerolle** [comment]
Confirmed.

**Comment by bellwood** [comment]
Thank you sir - I shall do the needful =)
