### ISSUE TITLE
Voice VLAN Assignment to Access Port

### ISSUE THREAD

**Issue by DanSheps** [digitalocean/netbox#2215]
### Issue type
[X] Feature request
[ ] Bug report
[ ] Documentation
[ ] Housekeeping

### Environment
* Python version:  3.5.4
* NetBox version:  2.4.0-devel

### Description

In using netbox, one thing I have noticed is there isn't a way to assign a vlan to an access port for "voice".  I am not sure if this is something that is desired by everyone and may be a fairly niche request.  I think the best way to do it would be to continue to use the VLAN assignment interface and add a separate option for voice vlan.  The relationship may need to be edited to allow tagging a single vlan when using access ports.

#### Use Case
Use for documenting access ports where there phones or other media devices

#### Database Schema Changes
Allow tagging a single port on access ports, in addition to the untagged port.

**Comment by larsuhartmann** [comment]
This would be really nice as it would allow to use netbox for campus access switchs.

**Comment by jeremystretch** [comment]
NetBox already supports assigning tagged and untagged VLANs to interfaces. There's nothing special about a "voice" VLAN; it's just a shortcut configuration used to add a single tagged VLAN to an interface that's normally untagged. For example, this configuration:

```
switchport mode access
switchport access vlan 100
switchport voice vlan 200
```

would be modeled in NetBox as VLAN 100 untagged and VLAN 200 tagged.

**Comment by lampwins** [comment]
> There's nothing special about a "voice" VLAN; it's just a shortcut configuration used to add a single tagged VLAN to an interface that's normally untagged.
That's not true on all platforms. For example, in Juniper land, the switch will use LLDP to identify phones and place them on a specified VLAN.

That said, I do agree this does not need to be added to NetBox because such configuration is normally device-wide and thus can be accommodated with a custom field on the device (this is how I do this today). I comment, only to offer this solution to anyone looking for this feature in the future.

**Comment by DanSheps** [comment]
I guess I wasn't 100% clear, my thinking/problem is that when it is assigned as an access interface in Netbox, you cannot only assign one vlan to the interface.

This is one of the checks you perform
