### ISSUE TITLE
Assign Circuits to Virtual Interfaces or Multiple Circuits to single Interface

### ISSUE THREAD

**Issue by jvanderaa** [digitalocean/netbox#2216]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version: 3.6.5
* NetBox version:  2.3.4

### Description

Trying to model out provider ports, where there are effectively sub circuits within the single parent circuit. Ideally this could get tied as a child to a parent of the larger provider port. The A-side would be the parent, and the z-side would be a device. In order to do this today we would create a virtual interface tied to the primary interface. This however won't accept a circuit. So then we would have to create it as type physical interface, even though it would be a virtual.

**Comment by jeremystretch** [comment]
NetBox does not support modeling virtual circuits. Circuits in NetBox are physical link, and as such can only terminate to physical interfaces. Please see the discussion in #790 for more detail.
