### ISSUE TITLE
Add a "Retired" status to rack-mounted devices

### ISSUE THREAD

**Issue by computer045** [digitalocean/netbox#2220]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.5

### Description
It would be good to add a "Retired" status to rack-mounted devices.

### Use case
A server can be turned off and prepped to be removed, but is still sitting in the rack. In the infrastructure I am managing it is somewhat common when migrating from older systems to new ones.

### Changes required
Add 3 lines in the `dcim/constants.py` file and add a style for the "Retired" label.

**Comment by jeremystretch** [comment]
We already have the "offline" and "inventory" statuses to accommodate devices which are not in use. If a device has been retired, it should be removed from NetBox entirely and perhaps tracked in a separate inventory management system.
