### ISSUE TITLE
Object-name scaling in rack-view

### ISSUE THREAD

**Issue by MrXermon** [digitalocean/netbox#2221]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.2

### Description
It would be nice if the object names in the rack view would scale depending on the count of units and the width of the box.
![grafik](https://user-images.githubusercontent.com/8172056/42380400-1605259e-812e-11e8-839c-2eefb37bd89d.png)

**Comment by jeremystretch** [comment]
I can't think of a way to accomplish this elegantly in the current setup. It might be feasible under #2248.

**Comment by jeremystretch** [comment]
#2248 actually looks pretty promising. Closing this out as I don't want to spend any effort on further tweaks to the current rendering approach.
