### ISSUE TITLE
Export / Print Rack View

### ISSUE THREAD

**Issue by Phhere** [digitalocean/netbox#2223]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  
* NetBox version:  2.3.4 

### Description
It would be great to have an option to export or print the rack view as a single page.
I think that no changes at the database are required and also no third-party libraries.
A use-case would be to print out these pages and attach to the rack doors for some information about the content of the rack.
Maybe we could allow some customization by defining attributes which should be shown.

**Comment by yarnocobussen** [comment]
This is already accepted as #160
