### ISSUE TITLE
Feature request: Snapshot function

### ISSUE THREAD

**Issue by Knot3n** [digitalocean/netbox#2224]
### Issue type
[x] Feature request
[ ] Bug report     
[ ] Documentation   
[ ] Housekeeping   

### Description

Snapshot function

It would be nice if a user makes big changes to a prefix or in the box that you can do a snapshot before or, if necessary, this can be done every 15-30 minutes of snapshots from the current table.

Option 2. A 'reset function' of the last change. *Something like a compare option

Today I documented more than 2 hours and applied a wrong mouse click and deleted a complete prefix. Took hours to repair that.

**Comment by jeremystretch** [comment]
This can be accomplished by backing up the PostgreSQL database which NetBox uses. Such activity is out of scope for the application itself.
