### ISSUE TITLE
Make number of search results displayed a configurable value

### ISSUE THREAD

**Issue by reshippie** [digitalocean/netbox#2228]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  2.7.10
* NetBox version:  2.3.6-dev

### Description
Currently, when a search returns a large number of results the first 15 are displayed.  We group our hosts into clusters of 20, so it would be very convenient for us to see all hosts when we search for the prefix of 1 of them.  
For example: 
clusterA-00
clusterA-01
...
clusterA-18
clusterA-19
Right now if we search for 'clusterA' we see clusterA-00 - clusterA-14 on the first page and have to click through to see the final 5.  
No database changes or third-party libraries are needed.
I have forked the repository and confirmed my changes have the expected result and pass both `migrate.py test` and travis-ci tests, but documentation states that I should submit a feature request before submitting a pull request.

**Comment by jeremystretch** [comment]
Should be covered by #1870

**Comment by reshippie** [comment]
I'm not sure I explained my situation as clearly as I could.  #1870 uses PAGINATE_COUNT in netbox/netbox/settings.py.  I would like to take SEARCH_MAX_RESULTS out of netbox/netbox/views.py and add that into netbox/netbox/settings.py
