### ISSUE TITLE
Pre-populate "Date added" field or default date when adding aggregates

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#223]
It looks like something changed since last week in respect to dates for added aggregates.

When I added these last week, the date defaulted to the current date.

I added a new aggregate today, left the field blank and it did not use todays date as the default.

Regression?

**Comment by bellwood** [comment]
It appears there is a created date though?

**Comment by jeremystretch** [comment]
Ah, I can see the confusion. A while back we added `created` and `last_updated` fields to all of the core models, including Aggregate. These are simply to track the time of creation and most modification, respectively, of the record itself within NetBox.

Aggregate also happens to have a `date_added` field, which is meant to denote when the circuit it represents was installed. It should probably be renamed to `install_date` or something similar. (This field is optional has never been auto-populated.)

**Comment by bellwood** [comment]
Very weird, all my other aggregates have a "added" value in the table when viewing all my aggregates - none of which I entered on creation

/me shrugs

**Comment by jeremystretch** [comment]
After some thought I'd rather not pre-populate this field, since the actual date of allocation or assignment is unlikely to be the same day it's created in NetBox.
