### ISSUE TITLE
IP Address Role not accepting null value when parsing a JSON file 

### ISSUE THREAD

**Issue by JSystem1** [digitalocean/netbox#2236]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  2.6
* NetBox version:  2.3.2

### Description
So it seems when you parse a empty role at the endpoint `/ipam/ip-addresses/` using a JSON file to parse it returns with the following error:
`[{u'role': [u'"" is not a valid choice.']}]`

When doing just a normal API call this is allowed/bypassed by filling in the role value as null. I need to keep the role value when parsing due to some rows not being empty.

I have tried to fill the NaN rows with "null" but it returns the same error as above

**Comment by jeremystretch** [comment]
Please post the exact API request you are making.

**Comment by JSystem1** [comment]
Well I am doing the API posting from a JSON file `requests.post(url,data = contents,headers=head, verify=False)`  where contents is `contents = open('json/ipaddress.json', 'rb').read()` So the problem is when doing a curl or through Swagger UI it works when leaving role as null or empty. The API request works when I would let say set the role: 40 (VIP) it would post successfully

**Comment by jeremystretch** [comment]
I'm not able to assist you unless you post the exact API request being made.

**Comment by JSystem1** [comment]
{"address":".....","description":".....","status":"1","role":""} - Since its not a string and its left empty when I am converting CSV -> JSON an empty string appears
