### ISSUE TITLE
Allow Device role to assign Device Types/Models

### ISSUE THREAD

**Issue by a31amit** [digitalocean/netbox#2238]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  
* NetBox version:  

### Description
Please allow Device Roles to be assign on Device Types. A common example, that we have multiple model of PDU, UPS from various vendor. Though Both UPS and PDU is PDU flag true but it would really good to know how many model we have for UPS and PDU. Surely this would be the case for other roles as well. 

As of now, It seems netbox only allow device role to assign to devices itself, where we can also see model. But this would help to know role of device types as well which doesn't have any devices associate.

**Comment by mmahacek** [comment]
It would be nice to be able to assign a Device Role to a device type to help populate the field on the device, but then have the flexibility to edit the device role later.  The value would be copied to the device instance rather than linked back to the device type.

**Comment by jeremystretch** [comment]
This breaks down when you consider general purpose hardware: Many types of device serve multiple roles. For example, a Dell server might be classified as a hypervisor, application server, DNS server, etc. I don't think trying to establish a link between device type and device role is worth the headache.

**Comment by mmahacek** [comment]
I wouldn’t see it as a hard link but more of a way to pre-populate the most common option. The device could then be changed after creation, but there is a base role set by default from on the device type.

**Comment by a31amit** [comment]
I agree with your point that hypervisor or application server doesn't make sense, maybe those will be solved later with enhancement of tags https://github.com/digitalocean/netbox/issues/132

However netbox does similar for VM's by enable vm role flag assignment for VM. this can be solved by similar with enable flag for device types. Unless this is requires a lot of engineering hours.

**Comment by lampwins** [comment]
Would this not already be covered in https://github.com/digitalocean/netbox/issues/1364 or is there something new being requested here?

**Comment by mmahacek** [comment]
I think this sounds like a DeviceTemplate would cover my use case scenario.

**Comment by jeremystretch** [comment]
Yeah, I think #1364 offers a much more elegant solution.
