### ISSUE TITLE
Add A/Z side circuit ID field

### ISSUE THREAD

**Issue by mmahacek** [digitalocean/netbox#2240]
### Issue type
[X] Feature request 

### Environment
* Python version:  3.4.8
* NetBox version:  2.3.5

### Description

We have instances where the circuit ID on the Z side is different from the circuit ID of the A side.  If there was an ID field, or even an open Description/Notes for each of the termination sides, that would be helpful.

**Comment by jeremystretch** [comment]
> We have instances where the circuit ID on the Z side is different from the circuit ID of the A side.

These are different circuits and should be modeled as such.
