### ISSUE TITLE
New hierarchy for ordinary companies

### ISSUE THREAD

**Issue by andershagman** [digitalocean/netbox#2241]
### Issue type
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.6.5
* NetBox version:  2.3.5

### Description
Netbox is great and is a software I have bin locking for for a long time. But, as we say, it uses a hierarchy like "world -> country -> town and last site and the devices. This is probably the right way for service providers but does not fit ordinary company's or organisations like ours that is healthcare. I know that you kan use regions in what way you want but regions are only placeholder and all the information is inside the site object.
As an example we have only one region, and the name is really "Region Kalmar". Next level is typically the site with all the info regarding contact, address and what kind of type of healthcare we have. Next we have buildings, floors, rooms, racks and last devices.
In my attempt to fit our organisation in Netbox I have user rack groups as rooms and ignored buildings and floors using naming like Buildingxx-Flooryy-Roomzz. It works but is not ideal. Also a rack group is not searchable by text and with around 500 rooms it is a long list.
It would be  nice with a model like Company -> site -> building -> floor -> room as we have in Cisco Prime.

**Comment by jeremystretch** [comment]
Hierarchical rack groups are addressed in #1754
