### ISSUE TITLE
Additional "form factor" interface  - Bridge

### ISSUE THREAD

**Issue by uncleVALERA** [digitalocean/netbox#2242]
**Issue type**
[X] Feature request
[ ] Bug report
[ ] Documentation
[ ] Housekeeping 

**Environment**
Python version: 3.5.2
NetBox version: 2.3.5

**Description**
Needs to have type of interface BRIDGE with possibility to add physical and virtual (as vlan) interfaces.
It seem as physical interface attach to LAG.

**Comment by jeremystretch** [comment]
Bridges can be represented using the "virtual" interface type. NetBox does not support modeling bridged interfaces within a device.
