### ISSUE TITLE
Device view is empty in 2.3.6

### ISSUE THREAD

**Issue by computer045** [digitalocean/netbox#2245]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.6

### Description
I just upgraded to version 2.3.6 from version 2.3.5. I executed the `upgrade.sh` script and the db migration before launching the new version. The Device view is empty as shown in the image below. I have 239 devices.

<img src="https://preview.ibb.co/cofCby/Capture_du_2018_07_17_09_29_58.png" alt="Capture_du_2018_07_17_09_29_58" border="0">

When a filter is active the device view is populated.

**Comment by jeremystretch** [comment]
Please post your installed Python packages (`pip freeze` or `pip3 freeze`).

**Comment by jeremystretch** [comment]
I'm not able to replicate this issue with the specified environment. Do you have any unusually named devices? Does this happen with any other object lists?

**Comment by computer045** [comment]
I'm sorry, it's my bad. I had bad value in one of my devices in one site. It caused a server side error. The whole device list could not be created because of it.
