### ISSUE TITLE
Make Topology Maps only work per Site

### ISSUE THREAD

**Issue by vandlol** [digitalocean/netbox#2246]
[x] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Description
Since Topology Maps are associated with a site - make them only use devices from the site its associated with.
Maybe split into Site Maps and Global Maps.

**Comment by jeremystretch** [comment]
There are many instances where it is helpful to include devices from other sites in a topology map. What is the benefit of arbitrarily limiting what devices can be included?

**Comment by vandlol** [comment]
Since you can only group servers via name regex naming conventions would be annoying.
If you could address sites or even racks as an address space for name regex you would be fine i guess.

**Comment by mmahacek** [comment]
What about a field on the topology map definition that sets whether the map is filtered only to resources at that site or not?  This would keep the current behavior, and allow this kind of filtering only on specific maps as needed?

**Comment by jeremystretch** [comment]
Closing this out as it hasn't gotten any interest.
