### ISSUE TITLE
Python 3 migration docs say to use pip after removing it

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#2249]
### Issue type
[ ] Feature request 
[ ] Bug report      
[ x ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.5
* NetBox version:  2.3.6

### Description
The first step in the python migration [docs](https://netbox.readthedocs.io/en/latest/installation/migrating-to-python3/) say to remove python-pip but later tell you to use pip.

```
# apt-get remove --purge -y python-dev python-pip
...
# pip uninstall gunicorn
```

**Comment by jeremystretch** [comment]
`apt-get install ... python3-pip` should install pip3 as `/usr/local/bin/pip`:

```
$ pip -V
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg (python 3.5)
```

It's all something of a crapshoot honestly...

**Comment by lampwins** [comment]
Probably a non-issue anyway. Uninstalling gunicorn with pip failed for me obviously, but I continued to install it again with pip3 and it was all fine.

**Comment by jeremystretch** [comment]
Tweaked this in the `v2.4-docs` branch as part of the ongoing refresh for the v2.4 release.
