### ISSUE TITLE
Provide CSV code when adding a device and/or dupe content when adding another

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#225]
When adding a device and "creating another" it would be nice to have the option of either:

a) having it pre-populate the fields with the current data in case all you need to change is a dropdown or two (adding multiple switches, servers, etc)

b) a little textbox below that builds the associated csv code that could be used for importing

...or maybe both?

Nothing fancy but might speed up the workflow for those can "cant be bothered" to "figure out" the csv stuff or who want to rapidly add a few items to the same rack.

**Comment by jeremystretch** [comment]
I considered doing this early on, but was hesitant to introduce it because it's very easy for users to forget to updated all fields that need updating.

**Comment by bellwood** [comment]
Perhaps you could show the CSV in the "success" alert with a "show CSV" toggle that way you know you're getting a complete line of csv

**Comment by jeremystretch** [comment]
This should be covered by #33 and #648.
