### ISSUE TITLE
extended data in  Recent Activity / User actions 

### ISSUE THREAD

**Issue by uncleVALERA** [digitalocean/netbox#2251]
**Issue type**
[X] Feature request
[ ] Bug report
[ ] Documentation
[ ] Housekeeping 

**Environment**
Python version: 3.5.2
NetBox version: 2.3.5

**Description**
Is it possible to make the data in the "Recent Activity" more extensive?
I would like to see in an additional field what exactly was changed 
I am interested in following fields : name, role, asset tag, comments.

**Comment by jeremystretch** [comment]
User activity is being replaced with change logging in v2.4 (see #1898).
