### ISSUE TITLE
mac address available in IPAddressInterfaceSerializer

### ISSUE THREAD

**Issue by jagter** [digitalocean/netbox#2252]
### Issue type
[x] Feature request
[ ] Bug report
[ ] Documentation
[ ] Housekeeping

### Environment
* Python version:  3
* NetBox version:  v2.3.5

### Description

It would be nice to have the mac address in the IP address interface section. With this change the mac IP combination direct available.

https://github.com/digitalocean/netbox/blob/93ce0ce67098f6341c1907caf41d6e40512c6e6e/netbox/ipam/api/serializers.py#L278

**Comment by jeremystretch** [comment]
Nested serializers return only enough information to reference the child object. This is consistent through the entire API.
