### ISSUE TITLE
Permit KMZ/KML attachments on circuits?

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#2253]
### Issue type
[X] Feature request

### Environment
* Python version:  3.6.6
* NetBox version:  2.3.5

### Description
Similar to other attachments but permit/allow attaching KMZ/KML files for circuits. 

These files show the actual path a circuit (Fiber, etc) would traverse geographically in Google Earth. Most carriers will provide their ISP customers with these for mapping/diversity/build purposes.

KML is essentially XML:
https://googlemaps.github.io/kml-samples/interactive/index.html

Edit: clarified Carrier/ISP

**Comment by jeremystretch** [comment]
I really want to avoid attaching miscellaneous files to objects in NetBox, which isn't really suitable as a document store. An alternative approach would be to link to the file(s) hosted elsewhere using a custom field on the circuit object. #969 would even allow for the use of a templatized link.

**Comment by bellwood** [comment]
The issue there is storing confidential/proprietary/protected information on a third-party system could/would be in violation of SOC.

Given that a KMZ/KML is directly related 1:1 on a circuit its hardly miscellaneous, its the "source of truth" for a circuit.

Just my .02 but Netbox would be more attractive if it had some additional convenience functions that would help me as an IT administrator reduce the number of programs/systems I need to have. 

Not saying Netbox needs to be a bloated beast, but, for those of us who are under strict and tight audit/compliance guidelines reducing the number of in-scope systems makes our lives so much easier and Netbox has the potential to do that.

**Comment by jeremystretch** [comment]
> The issue there is storing confidential/proprietary/protected information on a third-party system could/would be in violation of SOC.

It wouldn't need to be a third-party system. Any file store accessible from the client accessing NetBox would work.
