### ISSUE TITLE
Report results not being displayed on righthand side of reports list

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#2255]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.6

### Description
When reviewing the reports list at `/extras/reports/`, the list on the righthand side should show "passed" or "failed" for each report. It currently shows "N/A" for each report due to a bug in the template.

**Comment by mmahacek** [comment]
Confirmed that making the changes works on my install too.  Thanks.
