### ISSUE TITLE
Changelog overview on home page not very descriptive 

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#2258]
### Issue type
[ x ] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.6
* NetBox version:  2.4-beta1

### Description
The changelog overview panel on the right of the home page is great, but it looks like the title of each entry is only including the str method of the object in the change. This causes the entries to be rather vague. For example, in the screenshot below, the models created are: Device Type, Manufacturer, Rack, Rack Group, and Site. It would be much clearer to include the model name in the title of the entry.

<img width="505" alt="screen shot 2018-07-20 at 8 06 50 pm" src="https://user-images.githubusercontent.com/1297132/43029989-65dacdc2-8c59-11e8-81c5-fd5fdb9a72d6.png">

**Comment by jeremystretch** [comment]
Fixed in 86a67e7
