### ISSUE TITLE
Changelog entry link on interface view

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#2259]
### Issue type
[ x ] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  3.6
* NetBox version:  2.4-beta1

### Description
I see that interface change logs are listed alongside their parent device's entries on the device's changelog tab, but for ease of use, it would be nice to include the changelog tab on the new interface view itself. I foresee people spending a great deal of time on the new interface view, and since the changelog is a very important auditing tool, it should be easily accessible from this view for each interface.

**Comment by jeremystretch** [comment]
Closed in b7c2a26
