### ISSUE TITLE
Add IP address for Interfaces in Virtualization for VM using API

### ISSUE THREAD

**Issue by sanjeevma** [digitalocean/netbox#2261]
Issue type
[ x ] Feature request 
[ ] Bug report 
[ ] Documentation 
[ ] Housekeeping

Environment
Python version: 3.6
NetBox version: 2.3.1

Description
I been integrating My system with netbox 2.3.1 and most of the tasks is accomplished via API,
i am trying to execute Virtualization > Virtual Machine > Interfaces > add ip to interface [ Issue via API ],
API allows to create a Virtual Machine and create Interface too, but i am not able to find any process to add IP addresses for the Interface for associated Virtual Machine using API,

did any one had similar issue , i tried to look for similar issue but didn't find anything related to it

Thanks

**Comment by HaanJde** [comment]
@sanjeevma : Can't you do it the other way around, like assign an interface to an ip address?
/api/docs/#!/ipam/ipam_ip_addresses_update,
/api/ipam/ip-addresses/{id}/

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
