### ISSUE TITLE
Show VLANs on ports on device detail view

### ISSUE THREAD

**Issue by baldoarturo** [digitalocean/netbox#2262]
### Issue type
[x] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  
* NetBox version:  

### Description
Now that we have the functionality described on #150 i think it would be useful to have a quick reference of the vlans assigned to a port, something like the option to see the ip addresses
I think this would be especially useful for switches

**Comment by uncleVALERA** [comment]
I agree with you.
Needs some visual map of vlan for devices.

**Comment by jeremystretch** [comment]
Release v2.4 will introduce an interview which includes a list of all assigned VLANs and IP addresses.
