### ISSUE TITLE
Child device positioning information is lost on data export

### ISSUE THREAD

**Issue by chowell5** [digitalocean/netbox#2269]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* NetBox version:  2.3.7

### Description

Hi,

It appears that child devices are not associated with a parent device on exporting device information from Netbox.

When I import data (dcim/devices/import/  I can choose 'Racked devices' or 'Child Devices', but there seems to be no way to get the information on child devices out of Netbox when exporting.

I would expect to be able to export devices from a rack and import them into another Netbox instance without any loss of data, but that does not currently seem to be possible.

**Comment by DanSheps** [comment]
Upon review of this issue, it appears related to exporting racked devices and importing them into another Netbox instance.  Testing on the most current Netbox version, exporting devices and importing them into a new instance will maintain the rack assignment.

Apart from that, exporting and importing the parent/child relationship will give very little gain and there has been very little activity on this FR in almost a year.  As such, this FR will be closed out as the rack import/export is working as intended.
