### ISSUE TITLE
Add support for bulk child device assignment

### ISSUE THREAD

**Issue by ronniefalcon** [digitalocean/netbox#227]
I am trying to use the import to import child devices to a parent device:

bl002,Renderblade,XXX,I7,,,XLOCATIONX,RACK-TM-005,,

I see this error:

Record 1: Child device types cannot be assigned a rack face or position.

Am I going about this wrong way or is it not possible yet?

**Comment by jeremystretch** [comment]
This is intentional. Child devices can only be installed into a parent device.

**Comment by ronniefalcon** [comment]
OK, so I cannot mass import when using child / parent device?

Can you see how this would be beneficial with a high number of devices? (I am trying to assign 700 renderblade hosts to various chassis units)..

**Comment by jeremystretch** [comment]
Yes, this would be beneficial, unfortunately bulk import of child devices isn't yet supported.

**Comment by ronniefalcon** [comment]
OK, thank you. I greatly appreciate the ability to use parent/child.

**Comment by ronniefalcon** [comment]
Thank you!
