### ISSUE TITLE
Duplicate prefixes but in Isolated Networks 

### ISSUE THREAD

**Issue by JSystem1** [digitalocean/netbox#2270]
### Issue type
[X] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

### Environment
* Python version:  2.6
* NetBox version:  2.3.2

### Description
Currently I have  three DCs all have separated isolated networking so we have the same ranges that are been used within our separate networks. 

We are currently not using the VRFs feature for ease of use and have opted for Global VRFs which you have stated means that the specific prefix is used within our three networks in this case. 

So if you define three duplicate prefixes and isolate them within there own site and tenant they still come up as duplicates.

It would be nice when creating regions or sites to have an option that it is a separate network so for example separate networks would have there own global routing table which takes out the problem.

The only way around this is creating VRFs at this moment of time but I think there should be some defined method to state if the networks are different

**Comment by jeremystretch** [comment]
> Currently I have three DCs all have separated isolated networking so we have the same ranges that are been used within our separate networks.

This is the exact use case for VRFs.

> We are currently not using the VRFs feature for ease of use and have opted for Global VRFs

This isn't a thing. A prefix is said to belong to the _global table_ if it is not assigned to a VRF.

Please post to the mailing list if you need any further guidance.
