### ISSUE TITLE
Cable Identifier

### ISSUE THREAD

**Issue by martinpsiddall** [digitalocean/netbox#2271]
[X ] Feature request 
[ ] Bug report      
[ ] Documentation   
[ ] Housekeeping    

Hi I'd like to request a new feature which would allow us to identify cables within the Netbox system.

In our datacentres all cables are labelled with a unique cable ID, so that when patching equipment in an engineer can ascertain what cables are in use and where. 

I'd like a new field to be added to the dcim_interfaceconnections table as "cable_id" which is a unique field and would allow us to populate a cable ID when making a connection between two interfaces.

I've already made the changes in a fork of the main code... but would prefer to keep with the NetBox official release.

Many thanks

Martin

**Comment by martinpsiddall** [comment]
Can see this is similar to #20 but that doesn't seem to be making any progress, been open since 2016 !!

**Comment by lampwins** [comment]
@martinpsiddall this sort of thing is best served under #20. You will find there has been quite a lot of activity on that issue lately. You can also find that it has been tagged for v2.5. Yes, #20 is currently the oldest FR, but it is also by far one of the most complex to implement, so great care must be taken in its design.
