### ISSUE TITLE
Button with modal pop up to custom fields

### ISSUE THREAD

**Issue by andershagman** [digitalocean/netbox#2278]
### Environment
* Python version:  3.6.5
* NetBox version:  2.3.7

### Proposed Functionality
Add a button to custom fields, or any field,  as done with traffic graphs that trigger a modal pop up. 
The function will hand over object information imbedded in an url.

### Use Case
Simple way to make interactive registrations in foreign systems.
Ex: DNS, DHCP or ISE mac registration
The url trigger a foreign systems form inside the modal.
In this way it can support any system as long as the form can be shown correctly in the modal. 

### External Dependencies
Non as I can see.

**Comment by jeremystretch** [comment]
This seems needlessly complicated. Why not just link to the external form?

**Comment by mmahacek** [comment]
I would like to have a way to include links to outside systems, but the link should open in a new window, not inside Netbox.  I think this would fall as a use case for having externals links available. 
https://github.com/digitalocean/netbox/issues/969

**Comment by mmahacek** [comment]
Did you take a look at issue 969 I linked in my previous message?
