### ISSUE TITLE
Role based - Custom Fields

### ISSUE THREAD

**Issue by snowie-swe** [digitalocean/netbox#2283]
**Issue type**
[ x ] Feature request
[ ] Bug report
[ ] Documentation
[ ] Housekeeping

Netbox version: (v2.3.7)

**Description:**
Give the possibility to add custom fields based on what "roll" a virtual machines have, or what "type" a cluster belongs to.

This will limit the amount of text for each device and give greater custom abilities for none coders.

**Comment by jeremystretch** [comment]
Custom fields are intended to hold only data which is generally applicable to the associated type of object. When you find yourself wanting to distinguish among related attributes, it's a sign that you're trying to squeeze too much out of custom fields. Additionally, the overhead to implement this functionality would greatly outweigh the minimal benefit of toggling the displayed fields.

**Comment by snowie-swe** [comment]
Currently the virtual machines has very limited information as start.
Yes we adding information with custom fields like, OS, Patch, Owner, Backup, Dates when its installed etc.
This is the same for many devices, but then you also have very specific information if you would like to add more products like loadbalancers, virtual firewalls where the information is not applicable for a normal VM server. 

Currently we solves this by adding tabs for each device under the virtual machines.
I think there are more then us that would like to add more types of products within netbox to keep it as a single source of truth instead of needing a second CMDB for LB and Virtual Firewalls.

But if the custom fields was decided on what type of role the virtual machine have it would be much more clean for a user.

Thanks :)
