### ISSUE TITLE
Device power outlet mark as installed broken

### ISSUE THREAD

**Issue by TakeMeNL** [digitalocean/netbox#2286]
### Environment
* Python version:  3.6.6
* NetBox version:  2.3.6

### Steps to Reproduce
Create a PDU device with some outlets.
Then connect 1 of the outlets to a other device, but mark it as planned.
Go to the PDU power outlets section and there should be a connection ready to be marked installed.

### Expected Behavior
Power outlet should be marked installed on clicking the button.

### Observed Behavior
The mark as installed button doens't work.
The debug console prints: `PATCH http://netbox/api/dcim/console-ports/3/ 404 (Not Found)`

It button has the wrong class this should be powerport-toggle: https://github.com/digitalocean/netbox/blob/524da5a2ff11d3e5d1f8cd7d1c3615f776a1517f/netbox/templates/dcim/inc/poweroutlet.html#L30

**Comment by jeremystretch** [comment]
Thank you for the fix!
