### ISSUE TITLE
Devices type not populating

### ISSUE THREAD

**Issue by hrv231** [digitalocean/netbox#2289]
### Environment
* Python version:  2.7.5 and 3.4.8
* NetBox version:  2.3.6

### Steps to Reproduce
I spin up a VM with CentOS 7 with kernel 3.10.0-862.9.1.el7.x86_64 and is only for netbox. I followed the guide to install netbox, everything went perfect, so far everything works except that when I go to Devices - Add - choose manufacturer, and when I click the arrow to choose Device type nothing appears, therefore the system doesn't let me add a device.

### Expected Behavior
The system to work, but is not showing any device type.

### Observed Behavior
Attached is the picture with the problem.

I'm really happy with the system, brand new and starting using it, I haven't installed anything else, IPAM works great so far.
Thank you Jeremy for all your work!!
![device type netbox](https://user-images.githubusercontent.com/41212308/43475757-98a88802-94ab-11e8-99d4-b90364dce762.png)

**Comment by jeremystretch** [comment]
You need to add these.

Devices > Device types > Add

Please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you need any further assistance.
