### ISSUE TITLE
Unable to assign interface to IP address via API

### ISSUE THREAD

**Issue by explody** [digitalocean/netbox#2299]
### Environment
* Python version:  3.6.5, 3.5.x
* NetBox version:  2.4-beta1

### Steps to Reproduce

Using the API, attempt to PUT or PATCH an existing IP address including an interface id.

```
postman CURL output. Both IP and iface ID #'s exist and are correct
curl -X PATCH \
  https://ourhost/api/ipam/ip-addresses/11111/ \
  -H 'authorization: Token XXXX' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: XXXX' \
  -d '{
    "interface": 2222
}'
```

### Expected Behavior

The IP would now be assigned to the given interface.

### Observed Behavior

From postman, the following error:

```
{
    "interface": {
        "non_field_errors": [
            "Invalid data. Expected a dictionary, but got int."
        ]
    }
}
```

We additionally tried to pass interface data as a nested hash, but encountered a variety of other errors. It appears that the shown approach should work, so this may hint at the base problem.

**Comment by jeremystretch** [comment]
Fixed in #2300. Thanks @explody!
