### ISSUE TITLE
Is there a way to do mass updates?

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#230]
like for example, if I want to change all the platforms in all devices how do I do that? Also is it possible to do mass rack change? like moving from one rack and rack group to another?

**Comment by jeremystretch** [comment]
It's possible to script out changes to the data model using the built-in shell provided by Django. However, I haven't even started documenting it and would discourage anyone from using it on data they care about before getting very familiar with it. It's essentially as dangerous as issuing raw SQL commands, only much more convenient. I hope to get around to documenting some examples soon.
