### ISSUE TITLE
Updating of ConfigContexts via API fails when related objects are assigned

### ISSUE THREAD

**Issue by prx-nvdm** [digitalocean/netbox#2301]
### Environment
Python version: 3.5.2
NetBox version: last git version (33e45a2)

### Steps to Reproduce
1. Attempt to patch an existing ConfigContext via a PUT request to the API, with changes to one or more sites/tenants etc.

```
curl -X PUT \
-H "Authorization: Token <TOKEN>" \
-H "Content-Type: application/json" \
-H "Accept: application/json; indent=4" \
http://localhost:8000/api/extras/config-contexts/ \
--data '{"tenants":[83],"id":5,"name":"Tenant_ConfigContext","description":"Tenant_ConfigContext","weight":2000,"is_active":true,"data":{}}'
```

### Expected Behavior
The given ConfigContext should be updated succesfully.

### Observed Behavior
An exception is raised:
`Direct assignment to the forward side of a many-to-many set is prohibited. Use tenants.set() instead.`

**Comment by jeremystretch** [comment]
You need to use the URL for the existing ConfigContext in your request:

```
http://localhost:8000/api/extras/config-contexts/5/
```

The endpoint without a primary key is used only for listing all ConfigContexts or creating a new one.

**Comment by jeremystretch** [comment]
This stemmed from an error in `ValidatedModelSerializer`.

**Comment by prx-nvdm** [comment]
Thanks for the quick fix! @jeremystretch
