### ISSUE TITLE
Add the ability to view the list of VLANs on the device interface

### ISSUE THREAD

**Issue by nborisenkov** [digitalocean/netbox#2313]
### Environment
* Python version:  3.5.3
* NetBox version:  2.4.0

### Proposed Functionality
Add the ability to view the list of VLANs on the device interface

### Use Case
![netbox](https://user-images.githubusercontent.com/2655014/43775740-696db53e-9a56-11e8-95bb-558ad07867af.png)

**Comment by jeremystretch** [comment]
One sentence is not a legitimate feature request. Please extend your request with sufficient detail per the template.

**Comment by nborisenkov** [comment]
I want to see which vlans, IP addresses and tenants are connected to the device port. Summary table.

For example: I received a message that the device was unavailable and I want to find out which services and tenants suffered from this.

Now I have to go into each interface separately to find out what vlans and ip-addresses are configured on this device.

I need information about interface numbers, VLANs, IP addresses and tenants in one place.

With summary information, i can quickly find tenants who work through a specific device port. And just see all the tenants, IP addresses and vlans who work through this device.

I attach a new screenshot

 Perhaps it can be done somehow differently or in another place.
![netbox2](https://user-images.githubusercontent.com/2655014/43779437-159da526-9a61-11e8-8ebd-2e7de41b60e3.png)

**Comment by jeremystretch** [comment]
This isn't a practical approach, as interfaces often carry dozens or hundreds of VLANs and the interfaces table is already very busy. Alternatively, the individual interface view lists the VLANs for each interface individually.
