### ISSUE TITLE
Cannot view reports after upgrade to 2.4.0

### ISSUE THREAD

**Issue by konaya** [digitalocean/netbox#2315]
### Environment
* Python version:  3.5.3
* NetBox version:  2.4

### Steps to Reproduce
* Run a report from the command line with manage.py runreport. Note the apparent success:
```
[12:41:37] Running device.BackupStatus...
	test_backup_config: 689 success, 0 info, 89 warning, 0 failure
	test_backup_status: 689 success, 0 info, 146 warning, 0 failure
	test_backup_success: 256 success, 0 info, 2 warning, 0 failure
[12:42:09] device.BackupStatus: SUCCESS
[12:42:09] Finished
```
* Navigate to the Reports view in the web interface. The timestamp and the results overview in the right-hand column match with the returned output from the previous command.
* Click on the report in question to read it.

### Expected Behavior
The report, having been successfully run and acknowledged as such in the prior view, should open and show the details.

### Observed Behavior
A page with the words `No results are available for this report. Please run the report first.` appear.

This bug is distinct from #2312 in that I can run reports but not view them, whereas the other reporter can view reports but not run them.

**Comment by jeremystretch** [comment]
What is your `REPORTS_ROOT` setting (in `configuration.py`)?

**Comment by konaya** [comment]
No variable by that name is set in that file.

**Comment by jeremystretch** [comment]
#2312 should be fixed now and it's very likely this is related. Can you please try v2.4.1 and see if you still have this issue?

**Comment by konaya** [comment]
Thank you, it works!

(Re edit: 3.5.3, as per the original post.)
