### ISSUE TITLE
role field cannot be null when changing ip address via API

### ISSUE THREAD

**Issue by orgito** [digitalocean/netbox#2321]
### Environment
* Python version:  3.4.8
* NetBox version:  2.4.0

### Steps to Reproduce
Change an IP address with the role field as null.

### Expected Behavior
Should save the IP address

### Observed Behavior
Fails with the errror:

```python
{"role":["This field may not be null."]}
```
Adding `allow_null=True` to https://github.com/digitalocean/netbox/blob/f59682a7c955baa6b336ebe927d69c26f725ad67/netbox/ipam/api/serializers.py#L261 solves the issue

**Comment by jeremystretch** [comment]
I've found this same issue in several places where ChoiceField is used on a nullable field.
