### ISSUE TITLE
Add Color Picker for New 'Tag' Feature

### ISSUE THREAD

**Issue by WilliamMarti** [digitalocean/netbox#2324]
### Environment
Python version: Python v3.5.2
NetBox version: v2.4.1

### Proposed Functionality

Add Color picker, similar to what currently exists with 'Device Roles' already.  

### Use Case

Currently all tags have a grey background, would be helpful if we could more quickly visually discern which is which.  

### Database Changes

Assuming we need a new field for the Tag model.

### External Dependencies

No new external dependencies required.

**Comment by jeremystretch** [comment]
> Assuming we need a new field for the Tag model.

We're actually using the stock Tag model from [django-taggit](https://github.com/alex/django-taggit/blob/master/taggit/models.py#L79). We would need to implement our own model inheriting from TagBase. Should be fairly straightforward with a migration though, I think.

**Comment by jeremystretch** [comment]
@iDemonix it would be implemented in the regular frontend.

**Comment by tb-killa** [comment]
Doesn't we could use Select2 for this? We could use the "Multi-select boxes (pillbox)".

**Comment by tb-killa** [comment]
@lampwins nice thanks for the answer.
Found this sample.. Looks great 
https://next.plnkr.co/edit/Btjj5IrE9C4G7UO0mdRY?p=preview&utm_source=legacy&utm_medium=worker&utm_campaign=next&preview

**Comment by lampwins** [comment]
Implemented in the develop-2.6 branch.
