### ISSUE TITLE
API response for Prefixes to nest child prefixes within prefix containers

### ISSUE THREAD

**Issue by gregbuehler** [digitalocean/netbox#2325]
### Environment
* Python version:  2.7.12
* NetBox version:  2.3.6

### Proposed Functionality

Currently the user interface view supports a parameter called `expand` which displays prefix containers expanded with their children. It would be useful to have this functionality in the API. The feature would entail nested prefix objects in the response.

### Use Case
_note: fields omitted for clairity_
```
/api/ipam/prefixes/
[
  {
    "prefix": "10.0.0.0/16",
    "status": {
      "label": "Container",
      "value": 0
    }
  },
  {
    "prefix": "10.0.15.0/24",
    "status": {
      "label": "Active",
      "value": 1
    }
  }
]

/api/ipam/prefixes/?expand=on
[
  {
    "prefix": "10.0.0.0/16",
    "status": {
      "label": "Container",
      "value": 0
    },
    "children": [
      {
        "prefix": "10.0.15.0/24",
        "status": {
          "label": "Active",
          "value": 1
        }
      }
    ]
  }
]

**Comment by jeremystretch** [comment]
The API is intentionally structured to avoid referencing child items in the interest of performance. To retrieve the prefixes contained within a parent, do one of the following:

```
GET /api/ipam/prefixes/?within=10.0.0.0/16&vrf=0
GET /api/ipam/prefixes/?within_include=10.0.0.0/16&vrf=0
```

The later will include the parent prefix itself (if one exists).
