### ISSUE TITLE
Adding permission by Sites Geographic locations

### ISSUE THREAD

**Issue by Maxkaha** [digitalocean/netbox#2329]
### Environment
* Python version:  3
* NetBox version:  2.4.0

### Proposed Functionality
The goal is to have rights management in netbox for all objects from a geographic site rather than giving rights and being able to manage all sites.
As an example, an admin user of the site XX can manage all the objects of his site but can not intervene on the objects site YY
### Use Case
NC
### Database Changes
NC
### External Dependencies
NC

**Comment by jeremystretch** [comment]
NetBox does not support object-based permissions. See #554 for discussion on this.
