### ISSUE TITLE
Add the possibility to have the “Patch Panel/Port” as a device.

### ISSUE THREAD

**Issue by snowie-swe** [digitalocean/netbox#2331]
**Feature Request.**
Add the possibility to have the “Patch Panel/Port” as a device.

**Environment**
Netbox v2.4.1

**User Case:**
 
![image](https://user-images.githubusercontent.com/41901413/43835936-f9c2d5a2-9b13-11e8-9d28-d83e34b51555.png)

In this case it’s a passive CWDM filter, meaning it works just like a patch panel.
Currently you will need to pick how to document this. 

**Option1.**
Connect Device 1 and Device 3 via a circuit.
And then use free text on patch panel/port.

**Option2.** 
Device 1 > port 1611 CWDM0001A
CWDM0001A port 1310 -> Port 1310 CWDM0001B
CWDM0001B port 1611 -> Device 3

We would like the possibility to use a device and port on the “Patch Panel/Port”
Or to add a new field where the option is selectable.

This way to can have the devices connected to eachother via a circuit
And have it documented correctly in a physical way.
 
![image](https://user-images.githubusercontent.com/41901413/43835946-004ec4d0-9b14-11e8-97ea-0310533f7c45.png)
![image](https://user-images.githubusercontent.com/41901413/43835951-0411d8dc-9b14-11e8-8d7e-6ac9533f02eb.png)

**Comment by jeremystretch** [comment]
See #20

**Comment by steffann** [comment]
I think this is a duplicate of https://github.com/netbox-community/netbox/issues/3288 (or vice versa). I'm working on that.
