### ISSUE TITLE
Erroneous Group Requirement on Rack Endpoint

### ISSUE THREAD

**Issue by zachmoody** [digitalocean/netbox#2335]
### Environment
* Python version:  2.7
* NetBox version:  2.4.1

### Steps to Reproduce
Create a rack in the API yields a 400 that says group is required.

### Expected Behavior
Create the rack without a group association.

### Observed Behavior
```
curl -XPOST -H "Content-type: application/json" \
	-H "Authorization: Token 1234" \
	-d '{"name": "1234", "site":11}' \
	http://localhost:8000/api/dcim/racks/

{"group":["This field is required."]}
```

**Comment by jeremystretch** [comment]
This is related to #238. The UniqueTogetherValidator on the Rack serializer is registering `group` as a required field:

```
UniqueTogetherValidator(queryset=Rack.objects.all(), fields=('group', 'name'))
```

This is due to a bug where unique validation for some reason can't happen against null fields.
