### ISSUE TITLE
View Layout/Rendering Issues

### ISSUE THREAD

**Issue by mikeloosbrock** [digitalocean/netbox#2339]
I'm having several Django view layout/rendering issues after upgrading from v2.3.3 to v2.4.2. These display issues are replicated in multiple browsers, on multiple machines. Sample screenshot attached.

Upgrade procedure (per the documentation):
$ cd /opt/netbox
$ git checkout master
$ git pull origin master
$ ./upgrade.sh
$ sudo supervisorctl restart netbox

I also tried this in case it's a python module version compatibility issue:
$ pip install -r requirements.txt --upgrade --upgrade-strategy eager

![netbox-render-bug](https://user-images.githubusercontent.com/15373437/43868220-30c1d21a-9b32-11e8-8e96-d6a2be9b8fb6.png)

**Comment by anhnvme** [comment]
did you run `supervisorctl restart netbox` ?

**Comment by jeremystretch** [comment]
Your installation is missing a static file named `/static/css/base.css`. Try running `python3 manage.py collectstatic`. Please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you need further assistance with this.

**Comment by mikeloosbrock** [comment]
I actually tried `manage.py collectstatic` after my OP and before @jeremystretch's response. The static file `/static/css/base.css` does exist.

In terms of etiquette, am I supposed to ask about these sorts of things on the mailing list first, and only bring them here if the mailing list decides it's a bug?

**Comment by mikeloosbrock** [comment]
For anyone else who may come across this issue...

The permissions on /opt/netbox/netbox/static/ seemed to have changed after the upgrade such that nginx could no longer serve up content from that directory. After issuing `chgrp www-data -R /opt/netbox/netbox/static`, nginx could once again access the static files, and the netbox web ui then rendered correctly.
