### ISSUE TITLE
API erroneously requiring manufacturer when submitting inventory through /api/dcim/inventory-items/

### ISSUE THREAD

**Issue by frankfarmer** [digitalocean/netbox#2340]
### Environment
* Python version:  2.7.15rc1
* NetBox version:  2.4.2

### Steps to Reproduce
POST a json body without manufacturer to /api/dcim/inventory-items/, e.g.:
```
$ curl -d '{"device": 2171, "name": "RAID Controller", "description": "LSI Logic MegaRAID"}' netbox-s2/api/dcim/inventory-items/ -H 'authorization: Token 00deadbeef00' -H 'Content-Type: application/json; version=2.4;' -sv
```

This seems similar to the issue reported in #2305

### Expected Behavior
The item should be created successfully with a null manufacturer

Sending the same payload to netbox 2.3 works fine -- a 201 created response comes back

Creating an inventory item through the UI at /dcim/devices/<ID>/inventory/
accepts items without manufacturer just fine (and when queried via the API, they appear with a null manufacturer)

### Observed Behavior
```
 HTTP/1.1 400 Bad Request
{"manufacturer":["This field is required."]}
```

**Comment by jeremystretch** [comment]
Similar issue to #2335, where UniqueTogetherValidator is forcing `manufacturer` as a required field. Adding `default=None` to the field relaxes this requirement.
