### ISSUE TITLE
Device Management URL Fields

### ISSUE THREAD

**Issue by PackeTsar** [digitalocean/netbox#2348]
### Environment
* Python version:  **2.7.5**
* NetBox version:  **2.3.7**

### Proposed Functionality
Add fields to device page where you can define the GUI and CLI management URLs. These would contain something like (https://mydevice.domain.com) and (ssh://myuser@mydevice.domain.com).

These URLs would then be made into hyperlink buttons on the device's page, and on its row when listed under */dcim/devices/*.

### Use Case
This will give users the ability to click a button (either from the device's page or from */dcim/devices/*) and it will open a browser tab to that device's management page (or connect using the SSH scheme's preferred application)

**Comment by PackeTsar** [comment]
BTW I am currently solving this by using markdown in the device comments. It works fine, but cannot be seen from the */dcim/devices/* page and is difficult to keep consistent from device to device.

**Comment by jeremystretch** [comment]
This is probably best handled under #969, possibly in conjunction with the service model.
