### ISSUE TITLE
Device Types Height Field

### ISSUE THREAD

**Issue by DuaneWayne** [digitalocean/netbox#2349]
### Environment
* Python version:  3.5.2
* NetBox version:  2.4.3

### Proposed Functionality

When adding devices, is it possible to enable non-integer RU values?  I'm adding in my estate and my c6524ME boxes are 1.5RU.  Not a big deal, but it would be nice for me at least and maybe others.

### Use Case

Put devices into inventory that aren't integer values of RUs.

### Database Changes
I don't know enough to answer this or the external dependency question....

### External Dependencies

??

**Comment by jeremystretch** [comment]
Please see #51
