### ISSUE TITLE
Prefix Role / VLAN Role

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#236]
Hi Guys,

Just looking at the work flow here as per below

1. Create VLAN - give it a number for example 100
2. When creating a VLAN it asks you for a role - this role could be Management.
3. We then go to create a prefix which could be 192.168.1.0/24
4. You assign the VLAN 100 as created previously.
5. You then have the option to set a role again?

Isn't this redundant since the VLAN already defined the role? 

I know in our case we provide a VLAN per customer or if internally VLAN per role.

Thoughts?

**Comment by bellwood** [comment]
Prefixes and VLAN's can have separate roles

E.g you can have a prefix that is a "private network" role but then have multiple vlans within that have additional roles "pdus", "upss" etc

**Comment by rackcentral** [comment]
Hi Bell,

OK ... fair enough - I will close this issue as it is designed to be this way.

Thanks
Shaun

**Comment by bellwood** [comment]
No worries, I assume it's the intended functionality - I hope I'm right =)
