### ISSUE TITLE
inherit user changes before deleting user

### ISSUE THREAD

**Issue by azatuni** [digitalocean/netbox#2361]
### Environment
* Python version:  Python 2.7.5
* NetBox version:  Netbox 2.4.0
### Proposed Functionality
Hi,

When deleting user, all changes done by him are disappearing. It will be nice that there will be function that will inherit that changes to any other user.

Thanks beforehand.

**Comment by jeremystretch** [comment]
Changes cannot be reassigned to other users. If you need to retain the change history for a user, disable the account instead of deleting it.
