### ISSUE TITLE
Filter Prefixes when Role is null

### ISSUE THREAD

**Issue by gregbuehler** [digitalocean/netbox#2366]
### Environment
* Python version:  2.7.12
* NetBox version:  2.3.6

### Proposed Functionality
As a user I would like to filter prefixes with no role set.

### Use Case

Listing containers with no specified role:
`curl -vLk https://netbox.example.com/api/ipam/prefixes/&role=&site=foo&status=0`

Or using `pynetbox`:
```
import pynetbox
nb = pynetbox.api(
    'https://netbox.example.com',
    ssl_verify=False
)

for prefix in nb.ipam.prefixes.filter(role=None, site='foo', status=0):
    print(prefix)
```

Currently, there is post processing required to filter:
```
>>> raw = nb.ipam.prefixes.filter(site='foo', status=0)
>>> len(raw)
111
>>> e = [x for x in raw if x.role == None]
>>> len(e)
14
```

### Database Changes
No expected changes required

### External Dependencies
No external dependencies required.

**Comment by jeremystretch** [comment]
Filtering with `role=0` will return only prefixes with no role assigned. `0` is used as a special value to signify `null` for many filters.
