### ISSUE TITLE
Deleting bay takes back to netbox home page. 

### ISSUE THREAD

**Issue by a31amit** [digitalocean/netbox#2370]
### Environment
* Python version:  3.4
* NetBox version:  2.4.3

 Deleting All the bay in Chassis Device or Parent Device redirect to Netbox HomePage

### Steps to Reproduce

Create a Parent Chassis Device Type
Create a Device Based with same Device Type Model
Open Device Page and Select All Bay and Delete 

### Expected Behavior

It should redirect to Device page itself.

### Observed Behavior
 
Taking back to Netbox Home Page rather Device page.

**Comment by jeremystretch** [comment]
> Multiple Problems :

Multiple problems require multiple bug reports. Please revise this to address only a single issue, and open another issue for any separate suspected bugs.

**Comment by a31amit** [comment]
@jeremystretch split into two bug report. Thanks.
