### ISSUE TITLE
Patch Panel Position in Rack Space

### ISSUE THREAD

**Issue by Shogun8** [digitalocean/netbox#2371]
### Environment
* Python version:  
* NetBox version:  06eed1e03dfc (v2.3.3)

### Proposed Functionality
Changing the way that the patch panels in a rack are positionally aligned. 

In the current version, a panel is positioned in the rack according to bottom left screw of the device: it's position enumeration is  "The lowest-numbered unit occupied by the device ." I propose that the positioning of devices in the rack should be in alignment with the ANSI TIA-606-b-5.1.3.1.3.1 standard (please review figure 9) which proposes that it is the TOP left screw of the patch panel that is positionally aligned, rather than the bottom.
For instance a 3u patch panel that is located in the top of a 42u rack, would be in position 42, and not in position 40.

**Comment by jeremystretch** [comment]
This would be a completely arbitrary change requiring substantial modification to the rack elevation logic while yielding no practical benefit.

Also, NetBox does not currently support modeling patch panels (a feature to be introduced in v2.5).
