### ISSUE TITLE
Device Type edit seems to be affect Device itself

### ISSUE THREAD

**Issue by a31amit** [digitalocean/netbox#2375]
### Environment
* Python version:  3.4
* NetBox version:  2.4.3

Changing Device Type Templates also have the effect on Device itself. As per understanding from net box documentation that device types are being used when someone creates the device and changing device type doesn't have the effect on the device itself. However in this case device type seems to have some effect on the device.

Split from - https://github.com/digitalocean/netbox/issues/2370

### Steps to Reproduce
Create a Parent Chassis Device Type
Create a Device Based with same Device Type Model
Delete Bay in Device Type and Edit Device type from Parent to None
Open Device created with the same template and Select All Bay and Delete

### Expected Behavior
it should redirect to Device page itself and also it should give the option to create/add device bay as well.
As per understanding from net box documentation that device types are being used when someone creates the device and changing device type doesn't have the effect on the device itself.

### Observed Behavior
Taking back to home and when you open the device page for the same device, device bay area is missing from that device.

**Comment by jeremystretch** [comment]
This is expected behavior. The device type is no longer designated as a parent device, so NetBox doesn't give you the option to add device bays. (Device bays are displayed if they've already been created, though.)
