### ISSUE TITLE
API: retrieve a prefix by prefix

### ISSUE THREAD

**Issue by ebusto** [digitalocean/netbox#2377]
### Environment
* Python version:  3.5.4
* NetBox version:  2.4.3

### Proposed Functionality
Modify the ipam filter to allow retrieving a single prefix by name, `/api/ipam/prefixes/?prefix=10.0.0.0/8`.

### Use Case
This allows anyone using the API (either directly, or indirectly by using `pynetbox` et al) to unambiguously retrieve the prefix record, which can then be displayed, updated, etc.

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
It's a perfectly valid use case to have multiple instances of 10.0.0.0/8. The prefix alone cannot be employed as a unique identifier.
