### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by vzaletny** [digitalocean/netbox#2378]
### Environment
* Python version:   2.7.5
* NetBox version:  2.4.3
* CentOS Linux release 7.5.1804 (Core)
* Google Chrome 68.0.3440.106

### Steps to Reproduce
Hi guys!

Wheh I try to open VM inteface configuration, button "Edit this interface"  I'm getting an error.

### Expected Behavior
Change an interface configuration.

### Observed Behavior
There was a problem with your request. Please contact an administrator.
The complete exception is provided below:
<class 'AttributeError'>
'NoneType' object has no attribute 'get_vc_master'

**Comment by jeremystretch** [comment]
Unable to reproduce on v2.4.3. Please list the exact steps someone else can take to reproduce this bug, beginning with the creation of a new virtual machine.

**Comment by vzaletny** [comment]
I am sorry, that was my PC environment, but on NetBox are running:
CentOS Linux release 7.5.1804 (Core)
Python 2.7.5.

1. Create VM.
2. Add an interface.
3. Click on the interface name.
4. Click button "Edit this interface".
5. Get above error.

But if I click on the pencil icon "Edit interface" on the right , the editing interface page comes out as it should. 
Thanks.

**Comment by candlerb** [comment]
How to reproduce:

* Navigate to any VM
* In the table of interfaces, click on the *name* of the interface (e.g. "eth0" - *not* the icons on the right). This takes you to `/dcim/interfaces/NN/`
* Click on "Edit this interface" button
* You get an exception when it tries to display `/dcim/interfaces/NN/edit/` (where NN is an interface on a VM, not a device)

I believe the solution is:

1. The interface name should link to `/virtualization/vm-interfaces/NN/` not `/dcim/interfaces/NN/`
2. This page doesn't exist yet, so it needs to be created
