### ISSUE TITLE
Unique VM identifier - UUID in NetBox

### ISSUE THREAD

**Issue by vzaletny** [digitalocean/netbox#2385]
Hello.

### Environment
* Python version:  2.7.5
* NetBox version:  2.4.3

### Proposed Functionality
Add unique identifier field "UUID" for VMs such as a serial number for devices.

### Use Case
There are huge CRUD operations on a daily basis with VMs running on virtualization platform and it would be nice to synchronize all changes made on it to NetBox, but after rename or recreate VM there is no way to match instance in NetBox and virtualization platform.
I know about custom fields for storing VMware VM UUID, but that is not so convenient to operate and they are not unique.

### Database Changes
Add UUID field for VM object to store unique value sach as "42381b9f-36aa-af15-49f9-23f8634bd0a7".
It's 36 characters - 32 hex digits + 4 dashes. 

### External Dependencies
I don't know.

Thanks.

**Comment by jeremystretch** [comment]
If you're populating the UUID from an external system, a custom field will work fine. If you need to obtain a unique ID for each VM from NetBox, use the VM's integer primary key (the `id` field from the API object).
