### ISSUE TITLE
Update services that need to be restarted after upgrade.

### ISSUE THREAD

**Issue by jchristopher327** [digitalocean/netbox#2389]
### Change Type
[ ] Addition
[X ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

Finally, restart the WSGI service to run the new code. If you followed this guide for the initial installation, this is done using `supervisorctl`:
 ```no-highlight
- # sudo supervisorctl restart netbox
+ # sudo supervisorctl restart netbox:netbox-core
```
 If using webhooks, also restart the Redis worker:
 ```no-highlight
- # sudo supervisorctl restart netbox-rqworker
+ # sudo supervisorctl restart netbox:netbox-webhook-backend

**Comment by jeremystretch** [comment]
The current documentation is correct. `netbox-core` was defined at one point in a beta release of v2.4.
