### ISSUE TITLE
Tenants import: impossible with special characters

### ISSUE THREAD

**Issue by gdouchet** [digitalocean/netbox#2393]
### Environment
* Python version:  2.7
* NetBox version:  2.4.4

When trying to import this kind of tenant with special characters, I get an error.
If I add this tenant with the webpage and same contents, it's ok.

### Steps to Reproduce
Import these lines with tenant import page:
name,slug,group,description,comments
UNIV,univ,customers,Université,

This error appears:
<type 'exceptions.UnicodeEncodeError'>
'ascii' codec can't encode character u'\xe9' in position 29: ordinal not in range(128)

**Comment by jeremystretch** [comment]
Please specify your Python version as indicated by the template.

**Comment by gdouchet** [comment]
Sorry, I didn't have the information when I created the issue and forgot to specify it later...

Repaired!

**Comment by gdouchet** [comment]
I tried with Python in 3.6.5 version and the bug is not present with this version.

I let you close the issue if it's ok for you.
