### ISSUE TITLE
Status Field add Decommissioned

### ISSUE THREAD

**Issue by MeanKty** [digitalocean/netbox#2394]
Is there a way to change depreciated to decommissioned or is there a way to add decommissioned to the IP List Status?  We want to keep a list of the decommissioned items as well as the current ones.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
