### ISSUE TITLE
Markdown syntax partially not working in Sites - Comment 

### ISSUE THREAD

**Issue by dadmoscow** [digitalocean/netbox#2397]
### Environment
* Python version:  3.4.8
* NetBox version:  2.4.1

### Steps to Reproduce
1. View any Organization - Sites
2. Press Edit this site
3. Add to Comments field markdown unordered list (with asterisks):
\* One
\* Two
\* Three
4. Press Update

### Expected Behavior
* One
* Two
* Three

### Observed Behavior
\* One
\* Two
\* Three

**Comment by jeremystretch** [comment]
Works normally for me. Note that you need a blank line before and after the list. NetBox uses the [py-gfm](https://py-gfm.readthedocs.io/en/latest/) library to render markdown.

**Comment by dadmoscow** [comment]
Thank you. The string before and after helped.
