### ISSUE TITLE
Primary IP Assignment isn't removed when the IP address itself is removed from a VM interface

### ISSUE THREAD

**Issue by hensoko** [digitalocean/netbox#2399]
### Environment
* Python version: 3.5.4
* NetBox version: 2.4.3

### Steps to Reproduce
 * Create a VM
 * Assign IP address
 * Set IP as primary
 * Remove IP address from VM

### Expected Behavior
 * The IP address is updated and the primary assignment was removed

### Observed Behavior
 * The IP address is still configured as primary ip address

See https://github.com/digitalocean/netbox/issues/2342#issuecomment-412362156

**Comment by jeremystretch** [comment]
I'm not able to replicate this in v2.4.4. Please upgrade and try again.

**Comment by mabazyar** [comment]
The happens here on v2.4.4

**Comment by hensoko** [comment]
@jeremystretch Seems to be fixed with v2.4.4. Sorry for the inconvinience.
