### ISSUE TITLE
Searching by tag

### ISSUE THREAD

**Issue by rgrueebler** [digitalocean/netbox#2401]
Hi everyone,

### Environment
* Python version:  2.7.5
* NetBox version:  2.4.4

### Proposed Functionality
It would be nice if I could search by tags. 

### Use Case
 I add the same tag to different things like rack, device and ip address. Then I navigate to the rack and click on the tag. I expect NetBox to show the device and the ip address. With this feature it would be possible to group different things together. For example, I could group a customer to all the associated switch ports.
An alternative would be to add the "tenant" field to the interfaces. So it would be possible to associate a customer to the particular interfaces.

**Comment by rgrueebler** [comment]
I'd like to know which customer is connected to which switch port. In our case this would be great, because we charge our customers the number of ports they use in our datacenter. So if I could click on the particular customer and see how many switch ports are associated to him, it would be much easier for us.
I think the easiest way to achieve this is if it is possible to add a "tenant" to an interface. Another solution would be if I can add a tag to a tenant and an interface. By clicking on the tag I would like to see the tenant and the corresponding interfaces. In my opinion this is the more flexible way.

Thank you 
Remo

**Comment by jeremystretch** [comment]
Are you modeling the customer devices as well, or just "marking" each interface as being occupied by a particular customer?

**Comment by rgrueebler** [comment]
We don't document the customer devices. This would be too much work. We only would like to mark the interface as being occupied by a customer.

Thank you
Remo

**Comment by vsvetlov** [comment]
I have some thoughts about that.
Currently, the only way to find a prefix or IP address is using prefix or IP address as the value for search. But there is a use case when you want to find all the prefixes/address for example associated with mail-servers using tags or custom fields feature. For that you should use filtering feature by clicking on the specific tag or choosing custom field's value in a list. When you have a lot of tags it is not the best way to search and implementing a search feature for tags looks reasonable in that case.

**Comment by jeremystretch** [comment]
Closing this out as it is not sufficiently detailed.
