### ISSUE TITLE
Documenting (Cisco) ServiceInstance EVC/efp 

### ISSUE THREAD

**Issue by DaWaKo** [digitalocean/netbox#2404]
### Environment
* Python version:  2.7.1
* NetBox version:  2.3.1

### Proposed Functionality

Greetings!
To decouple the customer VLAN tag's integer from the bridge-domain integer could the documentation of Service-Instance/EVC interfaces be added to NetBox sometime please?
Eg:
Allow us to document that we have the following configured on a single router:
Interface Gi0/0/2efp1234 with vlan 998 and associated with bridge-domain 100
Interface Gi0/0/2efp1235 with vlan 999 and associated with bridge-domain 101
Interface Gi0/1/8efp1234 with vlan 998 and associated with bridge-domain 888
Interface Gi0/1/8efp1235 with vlan 999 and associated with bridge-domain 889

### Use Case

Since the introduction of carrier ethernet services on service-provider routers the VLAN id of tagged frames ingressing/egressing an interface is decoupled from the bridge-domain id on the router. 
On cisco, this is done with their MEF based Service-Instance/EVC interface configuration.
We have situations where multiple customers whose connections terminate on a common router use the same VLAN tags. In order to discriminate between their frames requires numerically different bridge-domains on the router for each customer. 

### Database Changes
The closest I can come to answer is to say that the following will need to be supported:
An new interface definition/type/attribute (I think either would work) that allows us to define the following on a single router: (excuse the repetition)
Interface Gi0/0/2efp1234 with vlan 998 and associated with bridge-domain 100
Interface Gi0/0/2efp1235 with vlan 999 and associated with bridge-domain 101
Interface Gi0/1/8efp1234 with vlan 998 and associated with bridge-domain 888
Interface Gi0/1/8efp1235 with vlan 999 and associated with bridge-domain 889

### External Dependencies
I'm sorry but I don't know how to answer this.

Thanks very much!

**Comment by jeremystretch** [comment]
This has been proposed in the past and we have decided not to model bridge domains as they can be highly platform-specific.

**Comment by DaWaKo** [comment]
Thanks for considering this Jeremy I can see your point about the bridge-domains. 
But could you allow for a new interface form factor called EVC (matching the MEF 3.0 definition for Ethernet Virtual Connection) that I can use with my efp interface Gi0/0/2efp1234?

Appreciate that you already have form factor "virtual", but I would like to discriminate.

All the best, and thanks for excellent tool.
Dana
