### ISSUE TITLE
Netbox Vlan drop-down window ONLY approx. 1000 vlan will be listed

### ISSUE THREAD

**Issue by sp-heinrichsra** [digitalocean/netbox#2406]
![screenshot_netbox_editprefix2](https://user-images.githubusercontent.com/42870642/44976858-c3205080-af66-11e8-8991-cd24dd1ddea0.png)

### Environment
* Python version: Python 3.6.5
* NetBox version: 2.4.4 (moved from different server from version: 2.3.1)

### Steps to Reproduce
 When editing a netbox prefix adding a VLAN from a "VLAN group" under the "Site/VLAN Assignment" the drop-down window wants to show any Vlans of the Vlan group.

### Expected Behavior
 In the Vlan drop-down window _ANY_ vlan should be listed, regardless the amount of vlans (or lines in the drop-down window)

### Observed Behavior
 In the Vlan drop-down window _ONLY approx. 1000_ vlan will be listed. A Vlan group could have max. 4096 vlans (just think any vlan id is in use) with the result that only the first approx 1000 vlan are listed and there is no chance to choose e.g vlan 2018.

**Comment by jeremystretch** [comment]
This is expected behavior. What is the specific modification being proposed?

**Comment by sp-heinrichsra** [comment]
Due to the technical definition that a vlan pool could be in a range of 1 .. 4095 vlans, I would expect that the drop-down should be able to list all of the vlans in a vlan group to have the possibility to choose one vlan out of 4095 possible vlans.
Actually only the first approx. 1000 vlan are shown and there is no way to choose a vlan which is not listed within the approx. 1000 entries.

**Comment by jeremystretch** [comment]
There can be more than 4095 VLANs assigned to a site (VLAN IDs don't necessarily need to be unique).

**Comment by sp-heinrichsra** [comment]
yeah. but this is not the issue the issue is the limited number of listed vlans in the drop-down windows. 
Just play with the thought we have 4000 vlan used in a vlan group; how to choose a vlan (e.g. 2000) when it is not listed in the approx. 1000 line of the drop-down window?
