### ISSUE TITLE
'Recent Activity' not logged when using API

### ISSUE THREAD

**Issue by etiensilvio205** [digitalocean/netbox#2407]
I'm actually building a client web app to work with Netbox and i am using Pynetbox to achieve this. My issue is that i need users to authenticate while doing a POST onto Netbox. I have noticed that when i am manually creating devices onto Netbox, i see a new log into "Recent Activity ". BUT if i create a device via the API, the activity is not logged into "Recent Activity". Even though they have a valid token for the API, it is not logged onto Netbox home interface. For security purposes, i would like to track the activities to allow transparent transactions by users.

Thanks for your help!

**Comment by lampwins** [comment]
Please upgrade to the latest version of NetBox. Recent Activity has been replaced by Changelogging which does log changes in the API. In the future, please use of the provided GitHub issue templates when filing reports, otherwise this issue will be marked as invalid and closed.
