### ISSUE TITLE
Rack roles

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#241]
Would it be possible to allow rack name aliases?

We often refer to racks internally by their purpose (hosting, VPS, cloud, backup, demarc, etc) or by the colo customers name/company who is occupying the rack.

**Comment by ryanmerolle** [comment]
You could also base the primary key and slug on netbox assigned IDs.  That way naming can overlap if needed.  It allows flexibility.  I'm not a huge fan, but it's an option.

**Comment by bellwood** [comment]
Would be nice, I have multiple colo customers with multiple racks

**Comment by jeremystretch** [comment]
Would this be addressed by a combination of #132 (tagging) and #16 (multitenancy)?

**Comment by bellwood** [comment]
Potentially universal search would - not sure on multi-tenancy

Would depend on implementation I suppose

**Comment by jeremystretch** [comment]
After some discussion, we'd like to implement roles for racks, similar to the roles we have for prefixes and VLANs. These will be user-defineable and optional.

Roles could be combined with multitenancy to cover the customer/colocation aspect.
