### ISSUE TITLE
Mac addresses missing from interfaces on device page

### ISSUE THREAD

**Issue by waynster** [digitalocean/netbox#2411]
### Environment

* NetBox version: 2.4.3

Since the latest upgrade we cannot see the mac addresses on the interfaces as we did before - to access them we have to click on the individual interface link to view this. 

### Steps to Reproduce
Search on any physical device
Scroll down to interfaces
Mac address is no longer visible

I expected to see the Mac address. 

The mac address is no longer there

Additional notes
If this is a modification to the tool can you please undo it? We have to track a large number of connections - when running a comparison between multiple mac addresses between 2 screens the necessity to clink on the interface link to manually search makes it impossible

**Comment by jeremystretch** [comment]
The MAC address column was removed from the list to allow for screen space for the interface description and other fields.

**Comment by doubleshot** [comment]
@jeremystretch +1'ing this request. We changed our templates to add back this mac address field, and there was plenty of space. I'm not sure what other people are using for their "description" field for where they need a bunch of space, but all other fields are very small.

Let me know if I could open a PR on this issue. Thanks!

**Comment by waynster** [comment]
I think a PR would be a good idea - this change has hindered us greatly truing everything up

Thanks



On Sep 20, 2018, at 11:39 PM, Anthony <notifications@github.com<mailto:notifications@github.com>> wrote:


@jeremystretch<https://github.com/jeremystretch> +1'ing this request. We changed our templates to add back this mac address field, and there was plenty of space. I'm not sure what other people are using for their "description" field for where they need a bunch of space, but all other fields are very small.

Let me know if I could open a PR on this issue. Thanks!

**Comment by DanSheps** [comment]
While I don't disagree with removing the MAC address, perhaps there might be an option to allow it to be a tunable in the config file based on the end users desired layout.

**Comment by jeremystretch** [comment]
FYI the interfaces list is changing a bit in v2.5 to include more detail.

**Comment by mrosun** [comment]
Very nice!  

Thanks for all the hard work by the way.  It's very appreciated that you guys are willing to take our input and Netbox is very nice!
