### ISSUE TITLE
Request external whois/geoip services if search in Netbox failed for IP address or prefix

### ISSUE THREAD

**Issue by vsvetlov** [digitalocean/netbox#2412]
### Environment
* Python version:  3.5.4
* NetBox version:  2.4.4

### Proposed Functionality
That is a really convenient feature in some IPAM solutions.
It would be cool to see it in NetBox.
When you search for IP address or IP prefix and there is no such entry in NetBox DB we could request external services for information about IP/Prefix.

### Use Case
You can forget about the services like whois and use IPAM to resolve any external and internal IP addresses.

### Database Changes
None

### External Dependencies
https://ipwhois.readthedocs.io/en/latest/

**Comment by jeremystretch** [comment]
This strikes me as an extraneous feature that's going to be much more work to maintain than it's worth. In general you should already know whether an IP address is part of your assigned space or not, and if not, performing a manual WHOIS lookup is trivial. Additionally, many users run NetBox in an isolated environment, rendering such a feature useless and necessitating the need for yet another configuration option. It's a neat idea, but we have too much in the backlog right now for extra features.
