### ISSUE TITLE
Feature request: Adding custom fields to device roles

### ISSUE THREAD

**Issue by mxxxc** [digitalocean/netbox#2413]
### Environment
* Python version:  3.4
* NetBox version:  2.4.4

### Proposed Functionality
Allowing the addition of custom fields to device role objects.

### Use Case
We'd like to provision different devices automatically (OS, configuration) according to their role in NetBox, through external automated systems that can hook into the API and web hooks. In order to to do that we need to store the ID mapping from roles to those external systems' databases, so they can be looked up from the single source of truth by the tooling we use. :)

This seems very synonymous with the example named in [the documentation](https://netbox.readthedocs.io/en/latest/additional-features/custom-fields/), which is also an external system ID associated with the entity. As such it seems like a natural fit for NetBox integration.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by mxxxc** [comment]
Ah, apologies! The issue text has been updated.

**Comment by jeremystretch** [comment]
Per the [FAQ](https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models) we are not adding custom fields to any additional models at this time.
