### ISSUE TITLE
Tags field missing completely from virtual interface handling

### ISSUE THREAD

**Issue by jord-bh** [digitalocean/netbox#2416]
### Environment
* Python version:  Python 3.6.6
* NetBox version:  2.4.4

### Steps to Reproduce
1. Add an interface to a virtual machine
2. The field for tags is missing, same as #2414 
3. Save the interface
4. Edit the interface
5. The field for tags is still missing

### Expected Behavior
That the field is rendered while both adding or editing a virtual interface

### Observed Behavior
The field is not rendered in either types of operations

**Comment by jeremystretch** [comment]
Fixed in #2414
