### ISSUE TITLE
Have circuits capable of hosting services

### ISSUE THREAD

**Issue by oskaregils** [digitalocean/netbox#2417]
We are interested in having a list of "services" assigned to a circuit.
This would be a new container in the GUI similar to what exists on devices.

We could use the current services configuration fields even though it is not directly applicable to my use-case. 
I have another concept I´m trying to put together that relates to idea of Netbox managing a new object called services  ...but that is perhaps too extensive.

It would be useful to be able to assign/refrence a backup/secondary circuit to the service.
Assume same could apply to services hosted on devices?

The usecase relates to our setup.
We could have circuits either failing or being reported to go to scheduled down time (maintenance).
For this I want to see a list of services transported across that circuit and would be affected.
Also useful to see what services are being routed over secondary circuit as backup so they will be protected.

Assume this is a minor add-on as this feature already exists for devices and is to be applied to circuits the same way. At least for the simple version, without reference to secondary/backup device/circuit

**Comment by jeremystretch** [comment]
NetBox models TCP/UDP services only as they relate to specific devices. Tracking higher-level modeling of dependencies is out of scope for the project.
