### ISSUE TITLE
Add a page related to community projects based on netbox

### ISSUE THREAD

**Issue by sieben** [digitalocean/netbox#2419]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes

Add a page related to community projects based on netbox

Example: 

https://github.com/sieben/netbox/blob/docs_community/docs/development/community.md

**Comment by jeremystretch** [comment]
You're welcome to submit a PR adding these to the README but let's keep the documentation focused on NetBox itself.
