### ISSUE TITLE
Add ability to clone device types

### ISSUE THREAD

**Issue by kenspi** [digitalocean/netbox#242]
Once I've created a model of one device type, it would be nice to quickly create different device types with similar features. e.g. Once I've created an EX4200-48T, it would be nice to clone this to an EX4300-48T, then make the limited changes between models (add/delete interfaces).
On the /dcim/device-types/ page, a "clone selected" button could facilitate this.

**Comment by jkldgoefgkljefogeg** [comment]
Clone feature can be useful in DCIM, adding it to the "Action" dropdown which currently has only delete?

**Comment by jeremystretch** [comment]
This sort of functionality will be covered by introducing JSON import/export for device types in #451.
