### ISSUE TITLE
Adding a performance improvement guide

### ISSUE THREAD

**Issue by sieben** [digitalocean/netbox#2420]
### Change Type
[ X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

I would like to have a guide in the documentation about how to improve netbox performance once the amount of objects is scaling up.

How can performance can be audited? Where should I start digging when my API calls are slows? etc...

**Comment by jeremystretch** [comment]
Are you volunteering to write this guide? Can you provide a rough outline?

**Comment by tyler-8** [comment]
It should be noted that since Netbox is built on the Django framework, a user can search out "Django performance improvements" to get relevant tips for Netbox.

**Comment by sieben** [comment]
Yes but where do you start? Also, keep in mind that users are not necessarily developers that know how to develop with Django.

**Comment by tyler-8** [comment]
I'd start with the [official Django documentation](https://docs.djangoproject.com/en/2.1/topics/performance/).

Performance tuning is a complex beast and is going to require (likely a lot of) self-started research to tackle. Perhaps as the Netbox userbase (and scale) increases and there's an idea of what the most common performance issues people are running in to are, then some Netbox-specific tuning ideas could be put forth.

Maybe it's already there - but considering the bulk of the application is Django-code, I'd say start there.

**Comment by jeremystretch** [comment]
I don't think it's feasible to produce a static document on performance troubleshooting. The developers take reasonable efforts to optimize performance as it is, and while I'm sure there's room for improvement, if we knew what additional steps we could take, we would have taken them already. As @tyler-8 suggests, the Django documentation offers some excellent advice on general performance; for anything more specific it's probably best to share your specific issue on the mailing list for guidance.
