### ISSUE TITLE
lexicographical sorting order of device bays

### ISSUE THREAD

**Issue by Zanthras** [digitalocean/netbox#243]
Minor issue but slightly annoying. If I create say a blade chassis container and add device bays with the names Server[1-16]. It creates them as expected, but then displays the sort order in a technically correct, but unrealistic way. aka Server1, Server10, Server11... Server16, Server2.

**Comment by bellwood** [comment]
@jeremystretch this should have been ... sorted ... in #9 right?

**Comment by jeremystretch** [comment]
That fix only applied to interfaces and interface templates. We could use an additional, more generic natural sort manager for this sort of thing. The same problem applies to device names, console ports, etc.

**Comment by jeremystretch** [comment]
Merged #248 which should address this. Need to `pip install natsort` or run `upgrade.sh`.

**Comment by jennec** [comment]
After updating today I still see that all Device interfaces I've created are ordered incorrectly.  Seems very Random.  Device Type Template Interfaces are ordered OK, but any devices created from them get a random sort.  Does this fix apply to devices you've already created?

**Comment by jeremystretch** [comment]
The [same ordering](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/models.py#L98) is used for both Interfaces and InterfaceTemplates. This issue is only for `natsorted` objects; we don't use natsort on interfaces because they're ordered by position rather than by name.

**Comment by jennec** [comment]
OK, so a different ordering for interfaces regardless of on the device or
in a template.  But Interfaces on a device template are sorted in reverse
order and also in the order in which they were added.  So for example if I
add "[1-48]" followed by "Management" virtual interface followed by
"[49-52]" then they appear in the imterface list in the order in which they
were added.  But if I create a device from that template the order is
randomised (or so it seems), such as in the included screen shot.


[image: Inline images 1]

If you would prefer I could log this as a separate issue, so you can track
it easier.  I appreciate I have kind of hijacked this issue thread.



Chris Jenner
Mob: 07739712218
