### ISSUE TITLE
Please display VLANs in Device -> Interface List

### ISSUE THREAD

**Issue by tpo** [digitalocean/netbox#2430]
### Environment
* Python version:  2.7.5
* NetBox version:  2.3.1

A device includes a list view of its devices. it'd be very useful, if one could see in that view which VLAN(s) are on that interface.

### Proposed Functionality

Allow the user to easily see the VLANs that are on an interface.

### Use Case

I am configuring a device and assigning VLANs to its interfaces. Prior to deploying the changes into production, I want to make sure that the correct interfaces are assigned to each interface. Instead of iterating over each and every interface and clicking the edit button on each of the interfaces, just to see the VLANs attached to it I simply hover the mouse over the interface.

### Database Changes

None

### External Dependencies

None

**Comment by tpo** [comment]
Instead of using my meager implementation, I suggest to use Paxio's version here: https://github.com/paxio/netbox/commit/293b2ea721f75acdafc5c78261328733ae1f5315 (see also the follow-up patches which fix and improve the functionality)

**Comment by lampwins** [comment]
A new Interface view was implemented in v2.4.0 that includes the list of associated VLANs. Please upgrade to the latest version to use this view (currently 2.4.4).

In the future, only open issues and bug reports against the latest version of NetBox. This ensures the issue or bug being referenced has not already been resolved in the latest version.

**Comment by tpo** [comment]
> A new Interface view was implemented in v2.4.0 that includes the list of associated VLANs. Please upgrade to the latest version to use this view (currently 2.4.4).

Thanks!

> In the future, only open issues and bug reports against the latest version of NetBox. This ensures the issue or bug being referenced has not already been resolved in the latest version.

Will try
