### ISSUE TITLE
Please allow jumping to the connected interface directly from a devices interface list

### ISSUE THREAD

**Issue by tpo** [digitalocean/netbox#2432]
### Environment
* Python version:  2.7.5
* NetBox version:  2.3.1

### Proposed Functionality

Allow to jump directly to the connected interface (i.e. the "other side of the connected cable") from a device's interface.

### Use Case

When assigning VLANs or changing interface properties it'd be nice to be able to jump from an interface in the list of interfaces of a device directly to the conected interface of the other device, in order to be able to assign the required properties to the other device.

The same can be achieved now by looking at the interface in the list, memorizing the name of the interface of the connected device. Clicking on the device, finding the interface and finally clicking on that interface. If one has to change many interfaces this workflow is really tedious.

### Database Changes

None

### External Dependencies

None

**Comment by lampwins** [comment]
Now that the Interface view has been implemented, we should link interface connections to this view.

**Comment by lampwins** [comment]
Closed in 57b225b6807e49ecef6014fae20c36c0c2443eb6
