### ISSUE TITLE
Optimize CSS for printing

### ISSUE THREAD

**Issue by bbock** [digitalocean/netbox#2435]
### Environment
* Python version:  3.5.2
* NetBox version:  2.4.4

### Proposed Functionality
The current screen layout includes many elements that make no sense for printing,
e.g. the search panel for lists or buttons. These should not be shown on
printouts.

The changes required would be mostly limited to the CSS, although a couple of additional class attributes would need to be added to the templates.

This does not include or interfere with #160.

### Use Case

Sometimes I need to print netbox views, e.g. for disaster recovery documentation
or audt. For me, list views are the most relevant, but the issue is applicable
for other views as well.

### Database Changes
none.

### External Dependencies
none.

**Comment by bbock** [comment]
I would be willing to work on this and provide a PR if maintainers agree that it makes sense.

**Comment by jeremystretch** [comment]
@bbock Can you do so without significantly altering the screen layout as it exists today? And are you willing to commit to handling any relevant bugs that pop up over the next few months?

**Comment by bbock** [comment]
The changes shouldn't be very invasive. I'm also willing to handling bugs related to my code.

I'll give it a shot and prepare a PR. I'll report back as soon as I have some code to show/discuss.

**Comment by candlerb** [comment]
In addition to sane device lists and IP address lists, printing rack elevations would also be hugely useful.

**Comment by jameswhite4684** [comment]
A printer friendly view would be great, like excluding search bar and navigation links.
