### ISSUE TITLE
FR: Default "undefined" types for new vendor entries

### ISSUE THREAD

**Issue by unquietwiki** [digitalocean/netbox#2439]
### Environment

* Python version:  3.6 
* NetBox version:  2.4.4 

### Proposed Functionality

Default "undefined" or "to-be-defined" types for new device vendor entries.

### Use Case

Most small businesses with a rack (or more), may have a mix of devices thrown together. It'd be more useful in these situations to be less verbose, and have default vendor types for use in these situations.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
The NetBox data model necessitates the definition of a device type before you can add a device.
