### ISSUE TITLE
Ignore carriage return on serial number entry fields for barcode scanner support

### ISSUE THREAD

**Issue by callumstrubi** [digitalocean/netbox#2440]
### Proposed Functionality
Text boxes that are for input of serial numbers ignore the "Enter/Return" key default functionality of submitting a form.

### Use Case
Often users will enter serial numbers or part numbers by scanning a barcode, and almost all barcode scanners come pre-configured to send a return key after the barcode scan. Used when entering a series of different serials/part numbers during adding or editing of an inventory or similar item.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
This is expected behavior for an HTML form. You'll need to reconfigure the scanner not to send a line feed.
