### ISSUE TITLE
Is python3-pip required ?

### ISSUE THREAD

**Issue by oza4h07** [digitalocean/netbox#2448]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
Is python3-pip required before installing Python requirements ?
A quick run on Debian Stretch suggests such addition (but I didn't check for Ubuntu  16.04 itself).

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
