### ISSUE TITLE
Is netbox user creation required at this stage of installation doc ?

### ISSUE THREAD

**Issue by oza4h07** [digitalocean/netbox#2449]
### Change Type
[X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
Doc [1] mentions changing ownership of /opt/netbox/netbox/media/ to netbox user but this user created yet at this stage.
Did I miss something ?
[1]  https://netbox.readthedocs.io/en/latest/installation/2-netbox/

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
