### ISSUE TITLE
Add custom filed on platform [ device > platform ] 

### ISSUE THREAD

**Issue by learn3r** [digitalocean/netbox#2451]
### Environment
* Python version:  <Python 3.5.2> 
* NetBox version:  <v2.4.4> 

### Proposed Functionality
If we have option to add custom fields on device : platform it will more useful to update details about the OS image which we are using on devices 

### Use Case
if i use centos 6 as platform for my server devices, i like to keep track of the package on OS image & bugs 

Details of OS [kind of packages & bugs ] we can keep track for the with customs platform field .Adding  

### Database Changes
New filed for on platform table

### External Dependencies

![image](https://user-images.githubusercontent.com/15086883/45994973-a5e92880-c0b3-11e8-92d5-a86d3d482b43.png)

**Comment by jeremystretch** [comment]
Custom fields are not supported on organizational models such as Platform. Additionally, the use case you shared sounds pretty out of scope for NetBox.
