### ISSUE TITLE
Circuit A/Z end not showing racks under sites

### ISSUE THREAD

**Issue by bhannah** [digitalocean/netbox#2454]
### Environment
* Python version: v3.5.2
* NetBox version: v2.4.4

### Steps to Reproduce
1. Create or Edit a Circuit
2. Click "Add" for either A or Z end
3. Select a "site" with racks assigned to them
4. Click "rack"

### Expected Behaviour
A return of racks assigned to that site to select from

### Observed Behaviour
No racks are returned

### Additional notes

From what I can tell, there is no pattern. Some sites have 1/2 racks and wont return the racks assigned, but others will. This is also the same for sites which have 10-100 racks.

![failed-return](https://user-images.githubusercontent.com/43499880/45919180-99818780-be89-11e8-835e-c428c09e525f.PNG)
![successful-return](https://user-images.githubusercontent.com/43499880/45919181-99818780-be89-11e8-975a-5fb88b945005.PNG)

**Comment by jeremystretch** [comment]
Unable to replicate this on v2.4.6. Seems like it's probably a symptom of #2406, which was resolved in v2.4.5. Please upgrade to the latest release and see if it's still an issue. If so, comment here and I'll re-open this.
