### ISSUE TITLE
Alternative to gunicorn & supervisord via Nginx Unit & systemd

### ISSUE THREAD

**Issue by unquietwiki** [digitalocean/netbox#2457]
### Proposed Changes

- https://github.com/unquietwiki/netbox/blob/develop/scripts/netbox-rqworker.service
- https://github.com/unquietwiki/netbox/blob/develop/scripts/netbox-unit.json
- https://github.com/unquietwiki/netbox/blob/develop/scripts/nunit-redis-install.sh

### Justification

**supervisord** began crashing repeatedly trying to run the "manage.py rqworker" task. I don't think redis likes running alongside NetBox in a container, so probably going to move my own install. But in troubleshooting that, I was able to deprecate use of gunicorn + supervisord, in favor of an Nginx Unit install; and setup a separate systemd service for the task that was crashing. Having the redis task in a systemd service also lets one set the correct LOCALE; which may have been contributing to the failure.

**Comment by jeremystretch** [comment]
I'd like to avoid collecting alternative installation methods. As with any Django project, there are multiple valid approaches to running it, and although the documentation provides one example, we ultimately leave that choice to the user. Introducing additional scripts, while useful, increases the maintenance burden and will inevitably lead to confusion among novice users. Also note that the scripts as you've written them make some assumptions about the installation environment that may or may not be valid.

**Comment by unquietwiki** [comment]
@jeremystretch I am disappointed, but understand your need to maintain a level of expected consistency. This is the 2nd time you've had to close one of my suggestions / reports: I hope this will not prejudice you against considering any further from my end.

**Comment by candlerb** [comment]
> I'd like to avoid collecting alternative installation methods

Although the documentation currently gives two alternatives for webserver frontend - Apache and Nginx :-)
