### ISSUE TITLE
Ability to configure napalm_username and napalm_password on a per platform basis 

### ISSUE THREAD

**Issue by quantumzedno** [digitalocean/netbox#2459]
### Issue type

[x] Feature request
[ ] Bug report
[ ] Documentation 

### Proposed Functionality
Currently you must configure napalm_username and napalm_password in configuration.py 
I would like the ability to configure these options independently when creating a platform in netbox, either as part of the optional napalm parameters already configurable when creating a platform, or with separate fields which would ideally be encrypted once configured. 

### Use Case
This would allow managing of various devices/platforms that do not share the same static username/password across devices and platforms. which isn't ideal for security. i.e password abc123 for cisco routers and password 321cba for aruba switches etc.

If this is already possible using the optional args field in the platform creation menu, i haven't been able to figure out how and would appreciate some clarification.
Google Group Discussion I created already: [https://groups.google.com/forum/#!topic/netbox-discuss/t-qGWrlVtwM](url)

Thank you,

Ben Lockwood

**Comment by jeremystretch** [comment]
This has already been raised. Whatever we end up doing will likely not be limited to the platform model specifically.

**Comment by quantumzedno** [comment]
Ah, sorry about that! My thinking on the platform model was simply because there is already some napalm config that can be done there and I figured you could always just have more platforms but in the case of globally unique passwords this could be quite a pain. 

I like the ideal of having it ties to secrets in some way if you could work out how to allow decryption without introducing a security hole

Great software, I'm still quite new to the platform but would love to help out where I can.

Cheers,

Ben
