### ISSUE TITLE
Docker Docs Issue

### ISSUE THREAD

**Issue by zachmoody** [digitalocean/netbox#246]
Ran into an issue with `docker-compose` wanting to download `digitalocean/netbox:latest` from docker hub I think because of the `image: digitalocean/netbox` directive in `docker-compose.yml`.

```
docker-compose up -d
Creating network "repo_default" with the default driver
Creating volume "repo_netbox-static-files" with local driver
Pulling netbox (digitalocean/netbox:latest)...
Pulling repository docker.io/digitalocean/netbox
```

I had to build the netbox container first with `docker build -t digitalocean/netbox:latest .` in order for it to work. I pushed a branch that updates the install docs with this step. Just wanted someone to confirm they have the same behavior before submitting a PR. 

Can someone test after doing a `docker rmi digitalocean/netbox:latest`. Entirely possible it's something I'm doing wrong on this end (running `docker-compose 1.7.0`).

**Comment by daveram** [comment]
Yep just ran into the same thing

`Pulling netbox (digitalocean/netbox:latest)...
Pulling repository docker.io/digitalocean/netbox
ERROR: Error: image digitalocean/netbox not found`

Tried running the build first, that did the trick, so not just you

**Comment by twm1010** [comment]
confirmed here as well, have to build that image first.
