### ISSUE TITLE
Customize View

### ISSUE THREAD

**Issue by eloquentheit** [digitalocean/netbox#2460]
Environment
* Python version:  2.7.5
* NetBox version:  2.4.3

Proposed Functionality

Opportunity to add Custom fields as columns in overviews. For example adding a custom filed as column in the overview  Virtualization >> Virtual Machines, which were created before in the admin settings.

Use Case

To have a custom filed in the overview or to customize the overview in general is very helpful to see all information directly that are relvant for own needs.

Database Changes

not sure 

External Dependencies
none

**Comment by DanSheps** [comment]
Do you mean the list view or the per-machine overview?

**Comment by eloquentheit** [comment]
I mean the list view. For example an option to add/remove columns which I have in the per-machine view (there are the custom fileds already)

________________________________
  [cid:image001.jpg@01D455B0.7B735CB0]

Michael Grimm
Systemadministrator
Open Doors Deutschland e.V.
Postfach 11 42, 65761 Kelkheim
T 06195 6767-119  F  06195 6767-252
E Michael.Grimm@opendoors.de <mailto:Michael.Grimm@opendoors.de>
I  www.opendoors.de <http://www.opendoors.de/>



[Klicken, um Link zu folgen]<https://www.opendoors.de/aktiv-werden/beten/weltweiter-gebetstag-fuer-verfolgte-christen?pk_campaign=mail-wwgt>
Von: Daniel Sheppard <notifications@github.com>
Gesendet: Mittwoch, 26. September 2018 15:45
An: digitalocean/netbox <netbox@noreply.github.com>
Cc: Michael Grimm <Michael.Grimm@opendoors.de>; Author <author@noreply.github.com>
Betreff: Re: [digitalocean/netbox] Customize View (#2460)


Do you mean the list view or the per-machine overview?

**Comment by jeremystretch** [comment]
Please see #492
