### ISSUE TITLE
"latest" version formatting broken at netbox.readthedocs.io

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#2471]
### Change Type
[ ] Addition
[ ] Correction
[ ] Deprecation
[X] Cleanup (formatting, typos, etc.)

### Proposed Changes

The layout used at readthedocs has changed, and now when I browse in either Chrome 69 or Firefox 62 under macOS, the top part of the page is obscured by the navigation banner.

The following example is https://netbox.readthedocs.io/en/latest/api/authentication/

![image](https://user-images.githubusercontent.com/44789/46242798-b277c480-c3c4-11e8-8131-22799af93efa.png)

I can stretch my window fit the full screen width, and the banner gets shorter, but still obscures part of the page.

![image](https://user-images.githubusercontent.com/44789/46242807-d9ce9180-c3c4-11e8-93b2-2030a4673c63.png)

Workaround: switch to "stable" instead of "latest" gives the old formatting (all navigation on left) which works fine.

Proposed change: revert latest to old formatting, or debug the CSS.

**Comment by jeremystretch** [comment]
I'm not sure why the theme changed. We don't specify a theme in `mkdocs.yml`. It looks like ReadTheDocs may have changed their default theme, which is weird because the original default theme is custom to them.

**Comment by candlerb** [comment]
Maybe [this](https://github.com/rtfd/readthedocs.org/issues/4448):

> The theme setting in mkdocs.yml is now required. That is a good thing and should make things easier going forward.

i.e. maybe it's now falling back to the mkdocs [default theme](https://mkdocs.readthedocs.io/en/stable/#theming-our-documentation)
