### ISSUE TITLE
Batch IP Address Record Update

### ISSUE THREAD

**Issue by branbot3000** [digitalocean/netbox#2480]
### Environment
* Python version:  3.7
* NetBox version: 2.4.5

### Proposed Functionality

Enable enhanced REST functionality - 
specifically, add PATCH method for HTTP interactions. 
![image](https://user-images.githubusercontent.com/43684815/46379655-5cb94b80-c654-11e8-9dc2-f9b44868dc75.png)

### Use Case

This specific use case proposes that a feature be added that would allow batch updates to IP address records. For example, in this instance I would be utilizing the REST API to edit several thousand of them at once - updating their description fields to contain their hostnames. 

The benefit of this feature would be increased ease of use. I work for a company with thousands of end users and this would greatly increase efficiency when recording updates to our network environment. We recently switched to your IPAM system and are missing host names as a result of human error during our initial data migration. I have been working around this through scripting but it's been a chore, and it seems like this enhancement wouldn't necessarily be something too difficult to implement on your end, but I could be wrong. Let me know what you think!

**Comment by cimnine** [comment]
That's one more spot where GraphQL would shine. But it's most probably never going to happen. See #2007

**Comment by candlerb** [comment]
GraphQL looks cool.  I guess you would create Mutations to allow the batch updates the OP was asking for.

Then all you have to do is rewrite the UI in Javascript to talk to GraphQL, and you have re-implemented the whole application :-)

**Comment by cimnine** [comment]
> Then all you have to do is rewrite the UI in Javascript to talk to GraphQL, and you have re-implemented the whole application :-)

It would indeed be useful for this: One request to fetch all information required to render the content.

**Comment by jeremystretch** [comment]
NetBox employs the [Django REST Framework](https://www.django-rest-framework.org/) (a third-party extension to the Django framework) for its API. I don't believe this functionality is currently supported by DRF. There was some work done on an external package called [django-rest-framework-bulk](https://github.com/miki725/django-rest-framework-bulk) but it is no longer maintained and almost certainly incompatible with recent releases. We can revisit this if support is introduced in DRF, but it's probably not something we want to tackle directly.

Regarding your specific use case, it is inadvisable to record hostnames in the description field of IP addresses: The device name is already accessible at `ipaddress.interface.device`. But if you really want to, you can easily perform one-off bulk updates using the local Python console (`./manage.py nbshell`). Something like this should work:

```
for ip in IPAddress.objects.select_related('interface__device').filter(address__net_host_contained='10.0.0.0/8'):
    if ip.interface and ip.interface.device:
        ip.description = ip.interface.device.name[:100]
        ip.save()
```
