### ISSUE TITLE
Adding complex interfaces results in server error

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#25]
When attempting to add interfaces:

```
xe-[0-1]/[0-3]/0
```

Results in a modal and server error which kicks me back to the homepage

```
There was a problem with your request. This error has been logged and administrative staff have been notified. Please return to the home page and try again.
```

**Comment by bellwood** [comment]
Figuring may it only likes on set of ranges I tired this:

```
xe-0/[0-3]/0
```

No go... Perhaps ranges can only be at the end of the string?

**Comment by jeremystretch** [comment]
Excellent guess! This is indeed a bug that triggers when one or more ranges have been given, but the string does not end in a range. Fixing.
