### ISSUE TITLE
Can we make sure Netbox runs on FreeBSD 10.3

### ISSUE THREAD

**Issue by MaXwellFalstein** [digitalocean/netbox#250]
I am a very keen user of FreeBSD. I use Netbox on FreeBSD; however, I would like DO to fully test Netbox on FreeBSD for the many users they have on the FreeBSD droplets and other users of FreeBSD.

**Comment by jeremystretch** [comment]
This isn't something we at DO are likely to undertake. Others in the community are of course welcome to contribute their efforts.

**Comment by MaXwellFalstein** [comment]
@jeremystretch is there any particular reasons why this is the case?
I am happy to do so in my spare time. It might require a few more people to keep up with your own developments.

How accepting of external developers are DO for Netbox?

**Comment by jeremystretch** [comment]
> Is there any particular reasons why this is the case?

We don't have any need to run NetBox on FreeBSD. That said, NetBox is essentially just like any other Django project. If you can [run Django on FreeBSD](http://linoxide.com/linux-how-to/install-django-gunicorn-nginx-freebsd-10-2/), you can run NetBox.

> How accepting of external developers are DO for Netbox?

Only three of the ten contributors listed in Github work for DO.
