### ISSUE TITLE
Elaborate on design choices that disallow Custom fields for interfaces

### ISSUE THREAD

**Issue by altmind** [digitalocean/netbox#2510]
### Change Type
[X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
Issues #1254 and #2281 were proposing to add custom fields to interfaces. The issues were closed with 'This issue has been discussed and closed.'

Can we please have some commentary what challenges can we face when implementing this feature? 
Will the patches to enable this be accepted?
What ideological and technical problems make this feature not implementable?
Is undesirability of this feature a sign of a larger design principle?

Nudge @jeremystretch
Thanks.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by cimnine** [comment]
https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models
