### ISSUE TITLE
API backed model selection fields

### ISSUE THREAD

**Issue by TLMiot** [digitalocean/netbox#2516]
### Environment
* Python version:  Example: 3.5.4
* NetBox version:  Example: 2.4.6

### Proposed Functionality

Make the Tenant select an input text field with suggestion, when editing/adding a new Ip 

### Use Case

Having 1k+ tenants scrolling trough the list every time we have to edit an IP becomes obnoxious. Having an input text, maybe even with suggestion/autocomplete, would be a great improvement for us.

### Database Changes

None

### External Dependencies

None that I know of but here's and example of a JQuery plugin that does it, as an example 
https://github.com/indrimuska/jquery-editable-select

**Comment by jeremystretch** [comment]
I was looking into [Select2](https://select2.org/) recently. It looks like a candidate for replacing API-driven select fields in many areas.

**Comment by lampwins** [comment]
I am working on this in the select2-ui branch.

**Comment by lampwins** [comment]
This will be covered in #2753 and is actually already partially implemented in the `select2-ui` branch.

**Comment by lampwins** [comment]
Implemented in `develop`
