### ISSUE TITLE
[FEATURE REQUEST] Custom Fields Selection Boxes

### ISSUE THREAD

**Issue by kopacko** [digitalocean/netbox#2522]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
Currently if any object has some common items that are being tracked but not all have all items multiple drop down lists have to be created with the same info. Making a list based off selection boxes would allow for 1 custom field that only displays the items checked.

### Use Case

The elimination of multiple drop-down lists with the same items.

### Database Changes

Unknown

### External Dependencies

None

**Comment by jeremystretch** [comment]
Best I can tell, you're asking that we implement the ability to reference a custom field choice from multiple custom select fields. This is not supported by the schema, and the need to do so strongly suggests that you're trying to squeeze more functionality out of custom fields than they were intended to provide.

**Comment by kopacko** [comment]
I am only asking for a custom field type that uses check boxes to say, select 4 of 5 items vs having to build 5 drop down lists and select one at a time per drop down list.
