### ISSUE TITLE
Tenant object is not iterable

### ISSUE THREAD

**Issue by ntengler** [digitalocean/netbox#2527]
### Environment
* Python version: 3.6.6
* NetBox version:  2.4.4

### Steps to Reproduce
1. Post to /api/ipam/ip-addresses/
2. JSON:
```
{
	"family":4,
	"address":"10.16.0.15/21",
	"tenant": 1
}
```

### Expected Behavior
I expected the IP to be created assigning the tenant correctly.

### Observed Behavior
I received a server error:
```
The complete exception is provided below:
<class 'TypeError'>
'Tenant' object is not iterable
```

**Comment by jeremystretch** [comment]
I'm not able to reproduce this behavior on v2.4.6; the IP address is created with the tenant assignment as expected. Please upgrade to v2.4.6 and try again.

**Comment by ntengler** [comment]
I tried the POST again after updating to 2.4.6 and same behavior.  Am I submitting the right JSON to associate our Tenant to this IP?

**Comment by ntengler** [comment]
That update worked!  Thanks for helping out.  I can now add the tenant to an IP.

 

Nate

**Comment by SesquipedalianDefenestrator** [comment]
Just hit this as well, but with TypeError: 'Interface' object is not iterable

This comment is mostly for future searchers:  if you get any sort of "not iterable" error, there's a good chance you have the wrong djangorestframework, and it has to be precisely 3.8.1.  If you install 3.8.2, everything breaks.
