### ISSUE TITLE
Move cluster to different site

### ISSUE THREAD

**Issue by Atoms** [digitalocean/netbox#2533]
### Environment
* NetBox version:  

### Proposed Functionality
Ability to move cluster with all devices and virtual machines to other site. 
### Use Case
If we just relocate physical host to other Datacenter we need to be able to move that cluster to different site with all devices and virtual machines.

**Comment by jeremystretch** [comment]
This can already be done. You'll need to remove the hosts from the cluster and change the cluster's assigned site. Then, update the site/rack assignment for the devices as appropriate and re-assign them to the cluster.
