### ISSUE TITLE
Make available to show only own ports of Stack master

### ISSUE THREAD

**Issue by igorrev** [digitalocean/netbox#2534]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
Make available to show only own interfaces of Stack master in contrast to show all interfaces of stack.

### Use Case
I name interfaces how I see it on the physical device. So if I have stack of two Cisco switches I make two devices with different names but the same interface names. It looks like:
Switch-1: GE0, GE1, ...
Switch-2: GE0, GE1, ...
It's not a problem. But if I combine these switches to stack via Virtual Chassis and select, for example, Switch-1 as Master, then go to Switch-1 page, I see all stack interfaces in list:
Switch-1:
GE0,
GE0,
GE1,
GE1,
...
The first entry of each interface relates to Switch-1, the second entry - to Switch-2. But it's impossible to indicate relation from this page. It's very difficult to maintain connections.

I can name interfaces how I see it in device configs, for example, GE1/0/1, GE1/0/2, GE2/0/1, GE2/0/2, ... But in this case it's more difficult to identify interface on device because labels on device doesn't match names in NetBox. Also I need to rename all interfaces if I change switch number in stack, move it to another stack or install it stand-alone.

Additionally it will be great to see internal interface name (how it named in config) and external name (how it labeled on device)

**Comment by jeremystretch** [comment]
> I can name interfaces how I see it in device configs, for example, GE1/0/1, GE1/0/2, GE2/0/1, GE2/0/2, ...

This is the recommended approach.

> But in this case it's more difficult to identify interface on device because labels on device doesn't match names in NetBox.

But they _do_ match how the master device references its interfaces, which is far more important. Further, having e.g. multiple interfaces named `GE0` doesn't help, because you have no way of knowing which is which.
