### ISSUE TITLE
Allow binding vlan/vlan-group/prefixes to Region instead of a specific site.

### ISSUE THREAD

**Issue by dxks** [digitalocean/netbox#2538]
### Environment
* Python version:  2.7.5
* NetBox version:  2.4.4

### Proposed Functionality
Possibility to  assign a vlan-group/vlan/prefix to a region instead of a site.

### Use Case
At the moment you have only the possibility to assign a vlan/vlan-group to a site. To assign a vlan to an interface the vlan has to be assign to the site or be global. When you have several networks in different regions (like germany, netherlands, usa) where the vlan's can overlap you cannot assign the group or the vlan to this region and so you have all vlans global and need to pick the correct one.

The same issue is if you want to have a vlan on several sites but not in all regions.

**Comment by bdlamprecht** [comment]
I'd like to see if this can be expanded to include binding on `device_role` as well.
Not sure if the Django ORM supports this relationship, but thought I'd ask.

**Comment by jeremystretch** [comment]
VLAN groups can be used to accomplish this. Simply create a group to represent the desired region(s).
