### ISSUE TITLE
itemcount not clickable

### ISSUE THREAD

**Issue by tonoitp** [digitalocean/netbox#2540]
Hi,

Not sure if this is something missing, or e feature request, but:

We started using tags and found that if you go to **organization -> tags** you get the list of tags including item count. But unlike **devices -> device types -> instances** the item count is not click-able to get to a list of tagged devices.  Can we get that too ?

Kind regards,
Tonny

**Comment by jonasalexandersson** [comment]
Jeremy: Why is this question invalid?
/ Jonas

**Comment by cimnine** [comment]
> Jeremy: Why is this question invalid?

you didn't use the provided template.
