### ISSUE TITLE
Linking interfaces with inventory items

### ISSUE THREAD

**Issue by swwolf** [digitalocean/netbox#2541]
### Proposed Functionality
Hi there, I'd like to be able to link interfaces to one inventory item of the device.

### Use Case
Interfaces have a mac address as an identifier and I know netbox is not an inventory system but since we have inventory items it would be nice to put them to good use here :smiley: . For instance think of replacing a broken nic, if you could link it to an inventory item you get serial number and part id for the interface. Note that you need to be able to link multiple interfaces to one inventory item (e.g. motherboards provide oob + nic). The feature would be optional to use and I think it would be pretty painless to implement.

### Database Changes
Interface model needs a relational field to inventory items

**Comment by jeremystretch** [comment]
This behavior would be out of scope for NetBox. The InventoryItem model exists only to represent modular components currently installed within a device.
