### ISSUE TITLE
CSV export/import of cable model not consistent

### ISSUE THREAD

**Issue by vink78** [digitalocean/netbox#2543]
### Environment
* Python version:  3.5.2-2ubuntu0~16.04.4
* NetBox version:  develop-2.5

### Steps to Reproduce

  * Go to the cable list (menu Devices -> Connection -> Cables)

Fields are:

ID | Label | Termination A |   | Termination B |   | Status | Type | Color | Length
-- | -- | -- | -- | -- | -- | -- | -- | -- | -

  * Click on export

Fields are: 

termination_a_type | termination_a_id | termination_b_type | termination_b_id | type | status | label | color | length | length_unit
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

  * Go to the cable list *import* (menu Devices -> Connection -> Cables import)

Fields are:

side_a_device | side_a_type | side_a_name | side_b_device |side_b_type | side_b_name | type | status | label | color | length | length_unit
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

### Expected Behavior

 * The expected behavior is to have an export CSV file which use the same format than import cable function.

### Observed Behavior

termination_a_type | termination_a_id | termination_b_type | termination_b_id | type | status | label | color | length | length_unit
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
dcim.interface | 1031 | dcim.interface | 41 |   | Connected |   |  

Only termination ID are displayed.

**Comment by jeremystretch** [comment]
What specifically are you requesting be changed? If we replace the (`side_x_device`, `side_x_type`, `side_x_name`) sets with (`termination_x_type`, `termination_x_id`) it would require the user to first collect the primary keys of all components being connected when importing new cables.

**Comment by vink78** [comment]
Agree.

I'ld like to have (`termination_x_type`, `termination_x_id`) replaced by (`side_x_device`, `side_x_type`, `side_x_name`).

**Comment by jeremystretch** [comment]
This wouldn't allow for the export of cables connecting circuit terminations.

**Comment by vink78** [comment]
Ok. Now I understand why you choose to export `termination_x_type` and  `termination_x_id` field.

An alternate solution for my problem is to define a custom export template for the cable model (thus I could re-import data on a second netbox installation). Do you have this feature on the roadmap?

Regards,

Vincent

**Comment by jeremystretch** [comment]
> Do you have this feature on the roadmap?

It's supposed to be working right now, but it appears I neglected to add the model to the list. I've opened #2563 for this.

Can we close this out?

**Comment by a31amit** [comment]
I did a fresh install of netbox-2.5-beta1 and it seems Import button is missing from cables view. 

Also, It would be really easier if we have exact import and exports csv column. This help will user when working on the DC floor for configuring cable or swapping them. otherwise looking at other things or fill them manually leads to more time spend on prepare proper CSV file.

Is that something nativelly added to netbox itself ?

**Comment by jeremystretch** [comment]
> I did a fresh install of netbox-2.5-beta1 and it seems Import button is missing from cables view.

Yes, it's only fixed in the `develop-2.5` branch.

> Also, It would be really easier if we have exact import and exports csv column.

This is exactly what was just discussed above.

**Comment by jeremystretch** [comment]
Added the button to the list view in c29ae9b. The import view was accessible via the navigation menu but not from the list view.

**Comment by ChrisWilkins82** [comment]
Thanks Jeremy, but that really wasn't what I was driving at; I guess that I wasn't very clear. However, you'll be happy to hear that this was a PEBKAC error. One of the lines in my data-set was causing my import problem.

My apologies, and thanks for a great tool.
