### ISSUE TITLE
Firmware field for DCIM/devices items

### ISSUE THREAD

**Issue by Comm4nd0** [digitalocean/netbox#2547]
### Environment
* Python version:  3.6.6
* NetBox version:  2.4.7-dev

### Proposed Functionality
Within the 'Hardware' section that already exists, there would be a models.FileField field, 'firmware'. Its would then be uploaded to a media folder.

### Use Case
With someone as the NetBox administrator keeping the firmware field up to date, an auto provisioning system would send a GET request for information about the system/device to be built. One of the pieces of information would be the firmware version and even the download link to retrieve it.

### Database Changes
Addition of 1 new field.
```
firmware = models.FileField(
        max_length=255,
        blank=True,
        verbose_name='Firmware version',
        help_text='The firmware version to be installed on this device'
    )
```

### External Dependencies
N/A

**Comment by Comm4nd0** [comment]
I have made the changes that are required already. Will do a pull request upon authorization.

**Comment by jeremystretch** [comment]
Directly serving firmware images is out of scope for NetBox. However, you can employ custom fields or config contexts to provide a URL to an external file server.
