### ISSUE TITLE
overview tagged devices

### ISSUE THREAD

**Issue by tonoitp** [digitalocean/netbox#2550]
### Environment
* Python version:   2.7.13 
* NetBox version:  v2.4.6

### Proposed Functionality
If one goes to **devices -> device types**  you can click the number in the column **instances** to see all devices of that type.

I'd like the same for the column **instances** at the page **organization -> tags** so we can get a page with all devices bearing that tag.

### Use Case
We are gonna use tags in our network automation, beginning with specifying when and how often a backup is taken from each device. It will be very useful to be able to see  which devices have the same tag.

### Database Changes
None expected

### External Dependencies
None expected

**Comment by jeremystretch** [comment]
The number of devices assigned to each tag is included in the tags list on the devices list view (Devices > Devices). You can also view the total number of objects assigned to each tag under Organization > Tags.
