### ISSUE TITLE
Offer a Global view for Tagged objects. 

### ISSUE THREAD

**Issue by Bill-Irvine** [digitalocean/netbox#2557]
### Environment
* Python version:  3.5
* NetBox version:  2.4.6

### Proposed Functionality

At the moment we are only able to view tags by object type. i.e. Just circuits or just routers with a specific tag. yet we are able to tag multiple types of object with the same tag.

When clicking a tag we remain within the object that the tag was selected in. I.e if the tag was in circuits then clicking "TESTTAG" would result in https://netbox/circuits/circuits/?tag=TESTTAG

This request is to create a view that allows us to view tags applied to multiple objects similar to how the search function currently looks. The proposed view would list all objects types with that same tag applied.

https://netbox/extras/tags/?tag=TESTTAG

![image](https://user-images.githubusercontent.com/5893433/48109774-aaf1e800-e2ad-11e8-990d-724c31b38d86.png)

In the admin view we are able to see multiple objects with the same tag applied, so making a view with this same functionality shouldn't require any database changes as the functionality looks to already exist.

![image](https://user-images.githubusercontent.com/5893433/48110418-e3df8c00-e2b0-11e8-85ca-ff2e088f674e.png)

From here we could link the current tags view to a list of all objects under that tag.

![image](https://user-images.githubusercontent.com/5893433/48110284-0f15ab80-e2b0-11e8-867c-80119be72b87.png)

Or linkable from the object itself that is tagged to see the rest of the objects that have this tag.

![image](https://user-images.githubusercontent.com/5893433/48156817-0adea200-e333-11e8-8448-412a82e251c2.png)

### Use Case

We are looking at implementing tags to track what objects make up a service. This can include interfaces, routers, vlans, sites, etc. 

Being able to click on a tag and have all of these tagged objects show up would make this a great visual reference of what objects have been linked together. This could also be used to see what part of a network impacts another part if they are tagged together.

### Database Changes

None, this is already viewable under the Taggit page in the admin panel, it should only require a view and url addition.

### External Dependencies

None. This will leverage the current Taggit dependency.

**Comment by jeremystretch** [comment]
To be clear, you're proposing a complete list of all objects assigned to a *single* tag, correct? As opposed to a view which lists all objects assigned to all tags?

Also, a tangent: The current admin UI should have been removed in the v2.4 release. Manually assigning tagged objects in that manner obviously isn't very user-friendly.

**Comment by Bill-Irvine** [comment]
Correct. A view that shows a complete list of all objects assigned to a single tag.

The admin view was just an example of how this functionality could be seen at the moment. I wont be planning on using this to assign objects to tags going forward.

Thanks.
