### ISSUE TITLE
Search for multiple tags in url

### ISSUE THREAD

**Issue by ossark** [digitalocean/netbox#2558]
### Environment
* Python version:  2.7.10
* NetBox version:  2.4.4

### Proposed Functionality
It would be nice to be able to search for multiple tags (or other keywords) like so:
https://netbox/api/ipam/prefixes/?tag=vpn1&tag=vpn2

This should yield a list of items that matches both tags. Currently the above URL only returns the items that match tag"vpn2".

### Use Case
If one has multiple customers and wants a list of resources that affects a few specific customers this could come in handy. Also, if you want to highlight prefixes that are link nets between sites, tags are appropriate to find the link nets that span over two (or more) specific sites.

**Comment by jeremystretch** [comment]
I'm marking this as a bug (as opposed to a feature request) as I think it's reasonable to _expect_ that tags should work this way already.

As for the implementation, there's some discussion around different approaches [here](https://github.com/carltongibson/django-filter/issues/137), but we'll probably just make a custom `TagFilter()` to be reused across all models.

**Comment by ossark** [comment]
If one would like it to be OR instead of AND. How would that me modelled? I am also seeing a case where you would want to list the items that match tag "vpn1" OR "vpn2" in a single call. I prefer the AND notation though. Not sure what is customary in REST.

**Comment by jeremystretch** [comment]
The behavior exhibited by existing filters is OR. For example, `/devices/?site=foo&site=bar` will return devices from either site. (The problem with the tag filter is that only the last tag specified in a list is being considered.)

I don't think there's any inherent mechanism for implying OR vs AND in [django-filter](https://django-filter.readthedocs.io/en/master/).

**Comment by ossark** [comment]
I understand. What I would prefer for the "?tag=" filter is AND.

**Comment by jeremystretch** [comment]
I've implemented this with the AND logic, such that `?tag=foo&tag=bar` will return only objects with both tags assigned.

**Comment by alimoghrabi** [comment]
Is this functionality working properly? I have tested it in my environment and it doesn't seem to be returning the correct data.

**Comment by ossark** [comment]
Works for me as specified. Are you running a proper version?
