### ISSUE TITLE
Please add 200G interfaces.

### ISSUE THREAD

**Issue by cmacnevin** [digitalocean/netbox#2561]
We're running 

### Environment
* Python version:  3.5.4
* NetBox version:  2.5.7

### Proposed Functionality

200G interfaces are out in the wild now, and 400G and 800G are close behind. DWDM (Coherent)
and straight Ethernet are now available. eg: https://www.finisar.com/optical-transceivers/ftlc3322x3nl

I don't know what database change are necessary, as I'm primarily just a user trying to use this, but it seems an lot like you'll have to add a single line somewhere :) 

### 

No new packages, I don't believe.

### External Dependencies

You might have to look at the link I supplied to check I'm not lying, I suppose :)

Please let me know if there's anything else you need to know, it seems pretty straight forward..

**Comment by berahtlv** [comment]
As I understood, transmission network is outside of the Netbox scope, where those interfaces are already available as pluggable and fixed interfaces. If data equipment will start using those, then they should be available and can be labeled as "OTN" in form factor list:
- 100G (DP-QPSK)
- 150G (DP-8QAM)
- 200G (DP-16QAM)

**Comment by cmacnevin** [comment]
These are actually being used on Arista ethernet-based routers. 

Look at hte bottom line card on this page: https://www.arista.com/en/qsg-7500n-series/7500n-series-line-cards

We have them in production right now.

**Comment by berahtlv** [comment]
Then for clarity also sub-ports are needed, like "QSFP+ sub-port (10GE)", at least tried to make connection of assumed 40GE interface to 2x 10GE through patch panel (v2.5-beta1) and encountered an error:
> <class 'django.db.utils.IntegrityError'>
>
> duplicate key value violates unique constraint "dcim_interface__connected_interface_id_key"
> DETAIL:  Key (_connected_interface_id)=(14) already exists.

Just curious, how 12x 10GE or 3x 40GE are possible from 100GBASE-SR10 ... additional lanes are activated?

**Comment by DanSheps** [comment]
@berahtlv That is because, to my knowledge, the connected interface table has a 1:1 constraint on it.  I believe this is changing once 2.5 comes out however.

**Comment by cmacnevin** [comment]
The 12x10Ge thing is probably because tha was the physical architecture in the first versions of 100Gig - it was electrically 12 10Gig channels. This was before it became 4 x 25Gig channels. I guess that explains the 3 x 40 also, since the switch bandwidth was always there. 

By that same logic, the 200Gig CFPX is actually a pair of 100Gig channels, which is annoyingly visible in the config. But I believe it cannot be broken out as a 100Gig separately, because of the style of the optic.

**Comment by jeremystretch** [comment]
What is the exact change being proposed? How would you define this under [IFACE_FF_CHOICES](https://github.com/digitalocean/netbox/blob/develop/netbox/dcim/constants.py#L105)?

**Comment by bendywendy** [comment]
I'd suggest adding:

'Ethernet (modular)',
        [
+             [IFACE_FF_200GE_QSFP56, 'QSFP56 (200GE)'],
+             [IFACE_FF_400GE_QSFP56-DD, 'QSFP56-DD (400GE)'],
        ]
    ],
