### ISSUE TITLE
Connecting Circuit Termination to RearPort Issue

### ISSUE THREAD

**Issue by mmahacek** [digitalocean/netbox#2564]
### Environment
* Python version:  3.6
* NetBox version:  2.5 beta 1

### Steps to Reproduce
Connect circuit termination to a RearPort of a patch panel.  Select patch panel device, select rear_port, select the port instance.

### Expected Behavior
A new cable should be created connecting the circuit to the device.

### Observed Behavior
I see a new cable is created, but receive the following error:
```
<class 'django.db.utils.IntegrityError'>

duplicate key value violates unique constraint "dcim_interface__connected_circuittermination_id_key"
DETAIL:  Key (_connected_circuittermination_id)=(126) already exists.
```
In addition, when looking at the device connected to the corresponding FrontPort, I see a cable connected but there is no far end device.  If I trace the connection, it does properly trace to the circuit.

~~On a separate/slightly related issue, there is no button to disconnect  a circuit termination from a specific port.  I deleted the cable and was able to reconnect to a new port.  However, the device is currently showing that the old port is still connected to the circuit but does not have a cable attached. (see screenshot)  
![image](https://user-images.githubusercontent.com/26419758/48162379-c222dc80-e291-11e8-873d-9d7aa908fdf0.png)~~

**Comment by jeremystretch** [comment]
> Connect circuit termination to a RearPort of a patch panel. Select patch panel device, select rear_port, select the port instance.

I'm not able to recreate this. Connecting the cable works as expected. Please see if you can work out the entire workflow needed to reproduce the bug. It likely involves an interface connected at some point in the path.

> On a separate/slightly related issue

Needs a separate GitHub issue.

**Comment by jeremystretch** [comment]
This might be related to #2571

**Comment by mmahacek** [comment]
Moved second part of original message to https://github.com/digitalocean/netbox/issues/2572

**Comment by mmahacek** [comment]
I am not able to reproduce the issue now.  Not sure if I am following the same steps or if I was trying too many things at once.  🤷‍♂️   I guess this can be closed and I'll see if I can break beta 2 when it comes out.

**Comment by bsteinert** [comment]
i run into this issue today, and have a slightly differnt scenario:

i have created a cwdm system with one rear and a lot of front ports. we conneted a circuit (darkfiber in our case) to the rear port.

by adding the first front port, everything looks good.
after adding the second port i get the same error like above.

--> i think there is a 1to1 relationship between circuits and it's connected items. after adding a second front port there is a problem with this object and how it is designed to work.

**Comment by bsteinert** [comment]
@jeremystretch should i open a new issue for that, or can you re-open this one for validation?
