### ISSUE TITLE
Markdown Table Formatting

### ISSUE THREAD

**Issue by mdaviesnz** [digitalocean/netbox#2565]
### Environment
* Python version:  3.5.2
* NetBox version:  2.4.7

### Proposed Functionality
Improve/add formatting of markdown tables in comments fields. 

Currently tables from markdown in comment fields appear without formatting and nice spacing making it difficult to read. Applying the already loaded bootstrap CSS style on the table improves this. 

Using chrome dev tools I added class="table" to the second table tag for this example:
![netbox-table-style](https://user-images.githubusercontent.com/4390830/48166688-33c06080-e34e-11e8-8752-1bc70adc2207.png)

Not sure if it taking the full width of the panel is desirable but this approaches the extent of my CSS knowledge already. There might be a more suitable style in bootstrap and perhaps there's a better way to do this with CSS otherwise?

### Use Case

I use tables to document information given by circuit providers which doesn't otherwise go into existing fields on the circuit objects.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
It seems that Markdown [doesn't support table classes](https://github.com/Python-Markdown/markdown/issues/312), so simply adding `class="table"` to rendered Markdown won't work. However, we can add a bit of custom CSS to clean things up.

**Comment by mdaviesnz** [comment]
Thanks Jeremy, looks great!
