### ISSUE TITLE
Cable connections same device validation missing

### ISSUE THREAD

**Issue by a31amit** [digitalocean/netbox#2566]
### Environment
* Python version:  3.7
* NetBox version:  2.5-beta1

There seems to be some bug in cable connection, It lets a user connect the same device and same port
It should generate some error message for the user, as in the real world someone cannot attach the same cable to the same interface; another side of the cable has to go somewhere.

There are chance's that someone has a cable in one interface and other side doesn't go anywhere but those cases for future planning or some temporary purpose. 

Not sure if this behavior exists in API as well.

### Steps to Reproduce
Create a Device
Click on Connect a cable
Select same device and interface -> same port

### Expected Behavior
It should generate some error message for the user, as in the real world you cannot the same cable to the same interface, another side of the cable has to go somewhere

### Observed Behavior
It let me add cable connection to the same device and same interface - 

![capture](https://user-images.githubusercontent.com/6764613/48179143-7c3a3880-e2d2-11e8-8c2a-95eba30f3d43.JPG)

**Comment by jbakklund** [comment]
This bug/feature could be used to describe a loopback connection. Those are though not part of the intended state in our networks, but you could actually find a use-case for it.
