### ISSUE TITLE
Add python django-rq package to requirements.txt 

### ISSUE THREAD

**Issue by madeinoz67** [digitalocean/netbox#2568]
### Environment
* Python version:  any
* NetBox version:  current

### Proposed Functionality

Adding this python package as part of default requirements.txt will simplify webhook enablement as python packages will already be installed in correct env when netbox is installed.  So all that is left for user to do is install redis and add config.

### Use Case
Webhook enablement

### External Dependencies
django-rq

**Comment by jeremystretch** [comment]
It's an optional package, like NAPALM, so it isn't included in `requirements.txt`. There's no reason to force someone to install something they're not necessarily going to use.
