### ISSUE TITLE
Add more fiber connector

### ISSUE THREAD

**Issue by vink78** [digitalocean/netbox#2569]
### Environment
* Python version:  3.5.2-2ubuntu0~16.04.4
* NetBox version:  2.5-beta1

### Proposed Functionality

Add more fiber termination:
 * LSH connector (CEI 61754-15, also known as E2000® in some european country)

LC, SC, LSH may be simplex or duplex and APC or UPC.

### Use Case

Most of my single-mode patch panels use LSH/APC connector.

### Database Changes

Only define new constants. See https://github.com/vink78/netbox/commit/b22dd4bfaf8a5569603d1acfd2871f7c7af07771

**Comment by jeremystretch** [comment]
Going to add LSH as a type and drop the simplex/duplex designation from SC. I'm not sure we want to support that level of granularity at this time. Same with APC/UPC.

**Comment by vink78** [comment]
Thank you for the LSH connector.

Is it possible to have `pigtail` as fiber connector too?

I will use this connector to model patch panel:
  * front connector is a real connector (LC/LSH/LC/SC/ST)
  * back connector is a pigtail which is spliced to a fiber cable
