### ISSUE TITLE
Improve color picker form widget

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#2590]
### Environment
* Python version:  3.5.2
* NetBox version:  2.4.7

### Proposed Functionality
Replace the stock `<select>` widget with something capable of displaying colors for ColorFields.

### Use Case
Most browsers don't render background colors for `<select>` items, so the user sees only a list of colors referenced by name ("Dark red", "Red", "Pink", etc.). This makes it difficult to find the desired color, especially if you're not familiar with the more obscure colors like cyan and indigo.

### Database Changes
None

### External Dependencies
This might involve a third party UI package like [Select2](https://select2.org/), which was also mentioned in #2516.

**Comment by lampwins** [comment]
This has been implemented in the select2-ui branch
