### ISSUE TITLE
Support for Nested Sites

### ISSUE THREAD

**Issue by DanSheps** [digitalocean/netbox#2591]
### Environment
* Python version: 3.5.4
* NetBox version: 2.4.7 / 2.5.0-beta1

### Proposed Functionality

This feature would add the ability, similar to Regions, to nest sites.

This would allow the modelling of a building "site" and room "site" (could also include specific area's within a building to further segregate).

This might also be particularly useful now that #20 is going to be implemented in v2.5.0 as it might be more relevant if you are currently using sites for "buildings" but you need a panel in a specific room.  Additionally, the metadata allowed to be carried in site's is far more relevant to rooms compared to rack groups/racks.

### Use Case

Currently the site object allows other objects to be tied to a specific site.  Currently regions allows nested regions and rack groups are planned to get nested rack groups in #1754.  However sites, which I would view as either a building or a room within a building, currently do not allow for nesting of rack groups.

If you use Rack Groups to represent sub-areas(area, room, etc) within a building, there will be no way to attach a device that isn't in a rack to a specific area like a room within a building.

This also allows you to model the vlans within a building site and room site more effectively.

Specific use case (assuming the following structure):

City (Region)
Building (Site)
Area (Site)
Room (Site)

* Attach racks to a building
* Attach devices to a building (with or without a rack)
* Attach devices to a area (with or without a rack)
* Attach devices to a room (with or without a rack)
* Potentially allow inheritable VLANs

### Database Changes

This would require a foreign key referencing the parent site.

### Design Considerations

Currently, VLAN are tied into sites, when dealing with devices that are assigned vlans based on the site.  For example, you might want to look at the site as well as all parent sites.

There may be other objects which look at sites in a similar vein and would also need to be considered.

### External Dependencies

No external dependencies

**Comment by jeremystretch** [comment]
I think we've struck a good balance as it is with nested regions and rack groups. Allowing nested sites as well is bound to introduce unnecessary complexity and confusion.

**Comment by DanSheps** [comment]
To further add, I just did some preliminary testing, and it seems to work by just switching to a TreeForeignKey & MPTT type field.  If you don't mind, I think basic functionality of nested sites could be added then the far reaching impact of parent sites for things like vlans could be added.  I would like to program this and then submit a PR.

Thoughts?

**Comment by jeremystretch** [comment]
I'm going to close this out as we need to evaluate community feedback after implementing #1754 before we consider any further modifications to the region/site/group/rack hierarchy. Unfortunately I don't an ETA for #1754.
