### ISSUE TITLE
Filter prefixes by aggregate

### ISSUE THREAD

**Issue by Jamie-** [digitalocean/netbox#2592]
### Environment
* Python version:  3.6.6
* NetBox version:  2.4.7

### Proposed Functionality
Add ability to be able to filter prefixes by aggregate using the search pane on the right-hand side.

### Use Case
When using multiple RFC 1918 private IP spaces it would be nice to be able to filter down the list of prefixes by the scope of private space. For example show only the 10.0.0.0/8 prefixes or only the 192.168.0.0/16 prefixes.

### Database Changes
I don't believe so, all the data required exists already. All this feature adds is a new filter.

### External Dependencies
None

**Comment by jeremystretch** [comment]
The `within` and `within_include` filters are available for this purpose. For example:

```
/ipam/prefixes/?within_include=10.0.0.0/8
```

**Comment by Jamie-** [comment]
Is there a way to do this only from the filter pane on the right hand side?
