### ISSUE TITLE
Custom Field Logic Migration Doesn't Support EnterpriseDB (Commercial PostgreSQL)

### ISSUE THREAD

**Issue by tyler-8** [digitalocean/netbox#2603]
### Environment
* Python version:  3.6.7 
* NetBox version:  2.4.7 

### Steps to Reproduce
Using EnterpriseDB 10.5 (commercial PostgreSQL)...

`./manage.py migrate`

### Expected Behavior
Migrations applied successfully

### Observed Behavior
Exception is raised due to [this line](https://github.com/digitalocean/netbox/blob/master/netbox/extras/migrations/0001_initial_squashed_0010_customfield_filter_logic.py#L26):
`pg_version = re.match(r'^PostgreSQL (\d+\.\d+(\.\d+)?)', row[0]).group(1)`

This is due to the output of `SELECT VERSION();` starting with "EnterpriseDB" instead of "PostgreSQL". Rest of the output matches.

### Proposed Fix:
`pg_version = re.match(r'^(PostgreSQL|EnterpriseDB) (\d+\.\d+(\.\d+)?)', row[0]).group(2)`

**Comment by jeremystretch** [comment]
NetBox officially supports only the PostgreSQL database. While I realize that what you're requesting is a trivial change, please understand that I don't want to imply that we guarantee support for other databases, even if they are PostgreSQL-compatible. All database functions and migrations must be thoroughly tested, and we don't have the ability to test against commercial databases.

As a workaround, you can add a `return` line at the top of `verify_postgresql_version()` to effectively bypass the validation. The migration is only called once: Once it's applied, you can revert the modification to maintain parity with the official code base if you like. However, please keep in mind that we cannot assist with any issues you encounter relating to the use of an unsupported database.

**Comment by jeremystretch** [comment]
@tyler-8 I'm fine with that. Will re-open.
