### ISSUE TITLE
2.5-beta1: passthrough port component

### ISSUE THREAD

**Issue by LukeLR** [digitalocean/netbox#2605]
### Environment
* Python version:  unknown
* NetBox version: 2.5-beta1

### Steps to Reproduce
The changelog of the 2.5-beta1 release says:

> NetBox now supports modeling physical cables for console, power, and interface connections. The new pass-through port component type has also been introduced to model patch panels and similar devices.

But I can't find anything related to passthrough port components when adding a new device type, neither in front/rear ports, interfaces or anywhere else. Am I missing something?

### Expected Behavior
Pass-through port components are visible as a port type when adding front or rear ports.

### Observed Behavior
No pass-through port components can be selected when adding new ports.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by LukeLR** [comment]
Besides having used the template, using the mailing list is not possible for people without a Google account. But thanks, anyways.

**Comment by LBegnaud** [comment]
it is free to create a google account. You also need an account to post this issue here... so I'm not sure what your point is.

**Comment by LukeLR** [comment]
Not everyone is comfortable with Google collecting their data. Not everyone would even agree if Google accounts are free or paid by your data... But my question was solved, thanks.
