### ISSUE TITLE
KeyError when creating rack via API with width as string

### ISSUE THREAD

**Issue by Loopbackconnector** [digitalocean/netbox#2609]
### Environment
* Python version:  3.5.3
* NetBox version:  v2.5 Beta1

### Steps to Reproduce
```
curl -X POST -H "Authorization: Token <token>" -H "Content-Type: application/json" -H"Accept: application/json; indent=4" http://netbox.server.com/api/dcim/racks/ --data '{"site": 1, "name": "My New Rack", "width": "19", "u_height": "42"}'
```

### Expected Behavior
Expected a successful post

### Observed Behavior
Object created even though error.  Also Error is not descriptive as to what the issue is.

```
<pre><strong>&lt;class &#39;KeyError&#39;&gt;</strong><br />
&#39;19&#39;</pre>
```

</html>

**Comment by jeremystretch** [comment]
This is happening because the `width` and `u_height` values are being passed as strings rather than integers. NetBox should still accept them, but for an immediate solution, simply remove the quotes around the values:

```
'{"site": 1, "name": "My New Rack", "width": 19, "u_height": 42}'
```
