### ISSUE TITLE
Autocomplete Tags

### ISSUE THREAD

**Issue by snowie-swe** [digitalocean/netbox#2612]
**Environment**
NetBox version:2.4.6

**Proposed Functionality**
When assigning tags to equipment, it would be great if netbox "autocompleted" names to avoid duplicates variation of tags.

**Use Case**
User friendliness
Enables users to quickly find and select from a pre-populated list of values as they type, leveraging searching and filtering.

**Database Changes**

**External Dependencies**

**Comment by asand3r** [comment]
Hi @snowie-swe 
In my environment it does, but needs to type at least 3 symbols - v2.4.8 and v2.5.1.
![default](https://user-images.githubusercontent.com/13959303/49985062-aa6b0200-ff7b-11e8-90d3-9634111d938c.png)

**Comment by snowie-swe** [comment]
> Hi @snowie-swe
> In my environment it does, but needs to type at least 3 symbols - v2.4.8 and v2.5.1.
> ![default](https://user-images.githubusercontent.com/13959303/49985062-aa6b0200-ff7b-11e8-90d3-9634111d938c.png)

Updated to 2.4.8 now and you are absolutely right :) working just fine now.
