### ISSUE TITLE
Permissions are being created for proxy console/power/interface connection models

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#2626]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5-beta2

### Steps to Reproduce
1. Apply database migrations for v2.5

### Expected Behavior
There are three new proxy models used to represent console, power, and interface connections. These are only used to represent connections, and cannot be manipulated directly. Thus, only the `view` permission is needed for these models.

### Observed Behavior
View, add, change, and delete permissions are created for each of the three proxy models.

**Comment by bdlamprecht** [comment]
Following

**Comment by jeremystretch** [comment]
Related to #2624

**Comment by jeremystretch** [comment]
It seems this stems from a [long-known issue](https://code.djangoproject.com/ticket/11154) concerning the treatment of permissions in Django for proxy models.
