### ISSUE TITLE
Fonts not working correctly when using nginx

### ISSUE THREAD

**Issue by duncan25** [digitalocean/netbox#263]
Hi Guys,

I have finished my installation of netbox, however, when i run it up using nginx, the fonts are not available and i get a basic looking web page instead of the one shown in the screenshots page of this project.
If i run a test server locally, the fonts are correct using ./manage.py runserver 0.0.0.0:8000 --insecure

Does anyone know how to get this back?  I have attached a screenshot of my issue.

Thanks ,

![netbox_basic](https://cloud.githubusercontent.com/assets/18476162/16753231/7e0300a0-482b-11e6-8f33-c3037992e3af.jpg)

**Comment by jvolt** [comment]
Hi,

You need copy a folder called "static".
When I installed netbox I have tried various releases because I was
receiving error 500 in a page (I was using non English characters in
description field and I did not realized it was the bug). When I finally
realized the accents was the problems I configured nginx to be a proxy and
got in the same problem you got.

So I noticed that was because there is a missing folder in the project, a
folder called "static", then I copied that folder from another app version
that I have used to test before.

Look inside the older versions of the app for a folder called "static" and
copy that to your project. I am not able give you more details right now,
because I am afk.


Em segunda-feira, 11 de julho de 2016, duncan25 <notifications@github.com>
escreveu:

**Comment by duncan25** [comment]
Thanks, that makes sense.

I will take a look and see what i can find.

**Comment by ventris** [comment]
Did you run the "./manage.py collectstatic"? It should load your static folder.

**Comment by jeremystretch** [comment]
99% sure this is/was the problem.

**Comment by duncan25** [comment]
Hi Guys,

after i run the "./manage.py collectstatic" command, the fonts are the same as in the screenshot above.  

below is the output from when i run the collectstatic.

I have also removed the static folder to have it recreated after running the command but to no avail

OUTPUT:

Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/urlify.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE-XREGEXP.txt'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE-JQUERY.txt'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/fonts/README.txt'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Regular-webfont.woff'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Light-webfont.woff'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Bold-webfont.woff'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/css/fonts.css'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/README.txt'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/LICENSE'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/sorting-icons.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-unknown-alt.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-addlink.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-deletelink.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/calendar-icons.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-clock.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-unknown.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/search.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-changelink.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-no.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-add.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/selector-icons.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-calendar.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-alert.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-yes.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-delete.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.svg'
Copying '/usr/lib64/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.svg'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/css/print.css'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/css/toolbar.css'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/img/ajax-loader.gif'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/img/back.png'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/img/back_hover.png'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/img/close.png'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/img/close_hover.png'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/img/djdt_vertical.png'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/img/indicator.png'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/jquery_existing.js'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/jquery_post.js'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/jquery_pre.js'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/toolbar.js'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/toolbar.profiling.js'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/toolbar.sql.js'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/toolbar.template.js'
Copying '/usr/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/toolbar.timer.js'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/bootstrap.css'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/css/screen.css'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/arrow-active-down.png'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/arrow-active-up.png'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/arrow-inactive-down.png'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/arrow-inactive-up.png'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/false.gif'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/header-bg.png'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/missing.png'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/pagination-bg.gif'
Copying '/usr/lib/python2.7/site-packages/django_tables2/static/django_tables2/themes/paleblue/img/true.gif'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/bootstrap-tweaks.css'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/bootstrap.min.css'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/default.css'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/prettify.css'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.eot'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.svg'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.ttf'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.woff'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.woff2'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings-white.png'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings.png'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/grid.png'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/ajax-form.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/bootstrap.min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/csrf.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/default.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/jquery-1.11.3.min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/prettify-min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/index.html'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/o2c.html'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/swagger-ui.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/swagger-ui.min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/css/atelier-dune.light.css'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/css/highlight.default.css'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/css/rest_framework_swagger.css'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/css/screen.css'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/images/explorer_icons.png'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/images/logo_small.png'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/images/pet_store_api.png'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/images/throbber.gif'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/images/wordnik_api.png'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/backbone-min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/handlebars-1.0.0.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/highlight.7.3.pack.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/highlight.8.0.pack.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/jquery-1.8.0.min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/jquery.ba-bbq.min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/jquery.cookie.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/jquery.slideto.min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/jquery.wiggle.min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/shred.bundle.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/swagger-oauth.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/swagger.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/underscore-min.js'
Copying '/usr/lib/python2.7/site-packages/rest_framework_swagger/static/rest_framework_swagger/lib/shred/content.js'


thanks for your help

**Comment by duncan25** [comment]
all done.

turns out it was SELinux blocking it.

**Comment by nzjc** [comment]
I'm using Debian 8 and Apache 2.2.22. I found the same issue was corrected by removing 'Require all granted' from my netbox apache conf file(s). I had 2 files as I used certbot to auto-ssl-erize the thing. Works well now.

**Comment by Mercusio** [comment]
Hi,

I am having a very similar issue.
The static folder is created. I work with nginx on ubuntu 16.04.
The page is displayed exactly as above.

I tried the solutions here but nothing worked so far.
