### ISSUE TITLE
Is there a forum  where one could ask basic NetBox API questions?

### ISSUE THREAD

**Issue by davmaroyo565** [digitalocean/netbox#2631]
Is there a forum  where one could ask basic NetBox API questions?

**Comment by davmaroyo565** [comment]
I'm having a problem where using POST I'm getting a code 200 successful return but I'm not seeing the change in the gui.  I'm asking here because I can't find another resource.

**Comment by davmaroyo565** [comment]
Found one.

**Comment by DanSheps** [comment]
In the future: Github issues is for reproducible bug, feature requests, etc.  Not general assistance.
