### ISSUE TITLE
FieldError at /admin/dcim/devicetype/

### ISSUE THREAD

**Issue by breed808** [digitalocean/netbox#264]
Hi all,

I've installed Netbox (v1.1.0) on a CentOS 7 box, following the instructions in the _getting started_ documentation (modifying it slightly for CentOS).
I've installed Gunicorn and Apache with proxypass, and that all appears to be working fine. I'm able to access all of Netbox save for the **devicetype** page in the admin area.

I am greeted with the "server error" page when attempting to reach that page, and am emailed the following error report: http://pastebin.com/6CKp6SaS

I've checked the SELinux audit log, and there aren't any AVC denials. As I'm able to use the rest of Netbox successfully, I don't believe that the issue is with Apache or Gunicorn, it seems to be something internal to Django or Netbox.

Have I screwed up somewhere, or is this a legitimate bug?

**Comment by Zanthras** [comment]
It was a bug that was fixed just earlier today in fact. See issue #260

**Comment by breed808** [comment]
Wonderful! I attempted to search for this earlier, but apparently not hard enough.
