### ISSUE TITLE
Favorites Sorting

### ISSUE THREAD

**Issue by jvanderaa** [digitalocean/netbox#2640]
### Environment
* Python version:  3.5.6
* NetBox version:  2.4.6

### Proposed Functionality

Ability to **Favorite** information to raise it to the top of the information searches.

### Use Case

As networks expand, it would be helpful to be able to get to information that you would find valuable quickly. Such as a high visibility project site or just the project sites that you are assigned to. This would be a per user setting request, so each user could have their particular favorites

### Database Changes

Unsure at this point of what it would take, maybe a user:favorites tag?

### External Dependencies

Favorite button

**Comment by jeremystretch** [comment]
NetBox already provides plenty of mechanisms for sorting and filtering objects. The ability to tag things as "favorites" already exists if you want to do that; we don't need a special button for it.
