### ISSUE TITLE
Add description field for console and power components

### ISSUE THREAD

**Issue by esapozhnikov** [digitalocean/netbox#2643]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
Add a Description column to console ports on the console devices.

### Use Case
A Description field would be very useful especially for Opengear switches where each port can have an IP address assigned to it.
The Description field can also be used to store console connection form factor info

### Database Changes
I believe this will require an addition of a new field to console port table

### External Dependencies
None that I am aware of.

**Comment by jeremystretch** [comment]
This will be merged into `develop-2.6` soon.
