### ISSUE TITLE
Netbox migration/exporting files

### ISSUE THREAD

**Issue by Ra1esh** [digitalocean/netbox#2644]
Hi,
I am trying to migrate netbox but I am failing at the restoring part.
I ran the command "sudo -u postgres psql netbox < netbox.sql" for restoring and I am getting the following error. I think it has to do with some permissions but not sure. I am not much familiar with postgres db, docker etc. but somehow I was able to get netbox running. Can anyone please help?

Thanks.

After I run the command I am getting the following error

sudo -u postgres psql netbox < db_dump_2018-12-03.sql
could not change directory to "/root/netbox-docker"
SET
SET
ERROR: unrecognized configuration parameter "idle_in_transaction_session_timeout"
SET
SET
SET
SET
ERROR: unrecognized configuration parameter "row_security"
S

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
