### ISSUE TITLE
PUTs to Site Endpoint Requires Value for time_zone

### ISSUE THREAD

**Issue by nue-melexis** [digitalocean/netbox#2645]
Hi,

[https://github.com/digitalocean/netbox/issues/2143](https://github.com/digitalocean/netbox/issues/2143) is closed, but it was only done for netbox 2.3.4 - 6.

I still get this issue with version 2.4.3.
Check master commits https://github.com/digitalocean/netbox/commits/master?after=8d4329197a916ed5704ce774a77ec1f59c8a6328+279

Browsing files:
Still OK:
[Post-release version bump @jeremystretch committed on Jul 2](https://github.com/digitalocean/netbox/blob/302c14186a2020fa2a241cb0b0bbe1fd9dc0a367/netbox/dcim/api/serializers.py)

NOK:
[Closes #2211: Removed Python 2 instructions from the installation docs @jeremystretch committed on Jul 2
](https://github.com/digitalocean/netbox/blob/104bd1b45f6a6f3b5d94fef4126c3b49413b33a3/netbox/dcim/api/serializers.py)

@jeremystretch 
Can you hint me? (This history for the file at that 2 revisions deviates from March 1st)

Best Regards,
Norman

**Comment by jeremystretch** [comment]
This issue is being closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose).
