### ISSUE TITLE
Add variable option to bulk-edit feature

### ISSUE THREAD

**Issue by swerveshot** [digitalocean/netbox#2650]
### Environment
NetBox version: 2.4.8

### Proposed Functionality
It would be really nice to have the ability to add a variable option to the bulk-edit feature. This feature would work sort of like the range option that is available with the naming of ports.

So how would this work in practice?

Let's say I have a large number of VLANs and wanted to edit the names of the selection to have them include the VLAN ID.

1. First I select the appropriate VLANs and then hit the edit link.
2. Then on the actual edit page I'd like to have a dropdown menu containing every text field and below that a field where one can enter a value.
3. The value could be static or contain variables like such: `[vlanname]-[vid]`

Maybe using the square brackets is confusing because they are also used for ranges. But it's just an example.

### Use Case
I recently ran into issue #1823 and wanted to quickly change a large number of VLAN names to make them unique. The proposed feature would accomplish this in the UI rather than having to do this via the API.

You _could_ also reconsider re-opening issue #1823 but I can think of other use cases where this feature might be useful. 😆

### API changes
You could make this feature available through the API but my use case is mostly for the UI.

**Comment by jeremystretch** [comment]
I don't like the idea of implementing this much complexity in the bulk edit feature. It was only ever intended to be a convenience. Once you get to the point of doing variable substitution inside properties, you really should be working with the API or shell.

**Comment by jeremystretch** [comment]
Closing this out as there's been no additional feedback, and honestly it's not a path I want to go down.
