### ISSUE TITLE
Feature Request: Editable Webhook POST format

### ISSUE THREAD

**Issue by berahtlv** [digitalocean/netbox#2651]
### Environment
* Python version:  Example: 3.5.4 ->
* NetBox version:  Example: 2.4.8 ->

### Proposed Functionality
Editable Webhook POST format to ensure compatibility with different REST APIs. At the moment direct API to API calls are not possible because of JSON keys incompatibility.

### Use Case
Netbox object change triggers defined webhook which sends POST request to some API for configuration synchronization or informative message generation.

### Database Changes
Maybe some minor additions.

### External Dependencies
No additional.

**Comment by jeremystretch** [comment]
Webhooks are not intended to be exported directly to another API. Some intermediary processing will be needed to adapt the data, and this is well outside the scope of NetBox. We just send as much information as we have with the request.

**Comment by berahtlv** [comment]
If feature will be requested as PR you accept it?

Idea is to add to admin/webhook-edit page check like 'API to API' which will activate raw mapping template area, something like Contexts, so users by themselves can edit output format. 

Can look something like that. Addition to netbox/netbox/extras/webhooks_worker.py

Mappings:
```
from string import Template
key_map = {'default':Template('{"text":"$r_model is $r_event at $r_timestamp"}'),
           'prefix':Template('{"text":"$r_model $prefix is $r_event at $r_timestamp"}'),
}
```
Renaming to flatten sent object dictionary:
```
payload = json.loads(params.pop('data'))
obj_event = {'r_model':payload['model'].title(),
            'r_event':payload['event'],
            'r_timestamp':payload['timestamp']
}
```
Map sent JSON data according to template:
```
payload['data'].update(**obj_event)
params['data'] = key_map.get(payload['model'], key_map['default']).substitute(**payload['data'])
```
