### ISSUE TITLE
Allow modeling VPLS-based circuits

### ISSUE THREAD

**Issue by michaelarnauts** [digitalocean/netbox#2659]
### Proposed Functionality

Currently, it's possible to define a circuit that goes from A to Z, but it's not possible to model a VPLS-based network where you have a circuit that arrives in multiple locations.

If the circuit could be expanded so it can have more then two endpoints (B, C, D, ... maybe), this would solve this usecase.

This is actually requested in #130.

### Use Case
Be able to model a network were you have a multi-site connection. Example: You have one circuit in the main HQ, and one circuit in each of the 8 side offices.

You can see on the device in the main office that this connection connects to multiple endpoints.

### Database Changes
Not sure

### External Dependencies
Not sure

**Comment by jeremystretch** [comment]
NetBox models only physical circuits, not overlays. This would be out of scope for the product.

**Comment by kmiller7851** [comment]
I'll definitely agree that overlays shouldn't try to be modeled, as it would be hugely complicated and out of netbox's scope, but I personally still feel some grouping mechanism for circuits would be a fantastic addition. Consider this example:

I have 100 sites spread out across the US. For certain reasons, I have 10 separate VPLS services from the same exact provider, with 10 sites on each VPLS service. I add all 100 of these separate physical circuits to netbox.

How do I now tell which site belongs to which VPLS instance? I now have 100 circuit ids with the same provider and type, making it very confusing which one belongs to which. Just having a very basic grouping mechanism would be extremely helpful, just for organization purposes.

This grouping system doesn't even need to be solely for vpls/multipoint type circuits. Some people may find it helpful to group primary vs backup circuits, or just based off some other criteria that helps them keep things organized.

I made a small mockup of what I would personally love to see:

![netbox-circuit-groups](https://user-images.githubusercontent.com/26152849/49768950-0f300f00-fc93-11e8-91c0-60bdb65a6176.png)

@jeremystretch would you possibly consider including something like this?

**Comment by nschmalenberger** [comment]
On Mon, Dec 10, 2018 at 04:00:44PM -0800, kmiller7851 wrote:
> I'll definitely agree that overlays shouldn't try to be modeled, as it would be hugely complicated and out of netbox's scope, but I personally still feel some grouping mechanism for circuits would be a fantastic addition. Consider this example:
> 
> I have 100 sites spread out across the US. For certain reasons, I have 10 separate VPLS services from the same exact provider, with 10 sites on each VPLS service. I add all 100 of these separate physical circuits to netbox.
> 
> How do I now tell which site belongs to which VPLS instance? I now have 100 circuit ids with the same provider and type, making it very confusing which one belongs to which. Just having a very basic grouping mechanism would be extremely helpful, just for organization purposes.
> 
> This grouping system doesn't even need to be solely for vpls/multipoint type circuits. Some people may find it helpful to group primary vs backup circuits, or just based off some other criteria that helps them keep things organized.
> 
> I made a small mockup of what I would personally love to see:
> 
> ![netbox-circuit-groups](https://user-images.githubusercontent.com/26152849/49768950-0f300f00-fc93-11e8-91c0-60bdb65a6176.png)
> 
> @jeremystretch would you possibly consider including something like this?
>
What about tags or custom fields?
-Nick
