### ISSUE TITLE
Assign IPs to VLANs

### ISSUE THREAD

**Issue by MrDragon** [digitalocean/netbox#266]
We have a ton of Extreme Networks switches/routers (OK, more of an L3 switch). They're a little different in the initial setup - you don't assign an IP address to a port, you assign an IP address to a VLAN, which might not even have an assigned port.
Do you think it might be possible to add a VLAN field to the IP address, so we'd have "Device/Interface/VLAN"? Of course I could add a pseudo-Interface to the device, call it "VLAN-357" and attach the IP to that interface.
Just throwing that out there :)

    Frank

**Comment by jeremystretch** [comment]
> Of course I could add a pseudo-Interface to the device, call it "VLAN-357" and attach the IP to that interface.

That's essentially what's happening when you assign an IP to a VLAN. The switch creates an SVI with a special MAC address to which the IP is assigned. This is how you want to define it in NetBox as well: a virtual interface named after the VLAN.

**Comment by MrDragon** [comment]
Oh, well... In that case it's all good ;) Sorry to have bothered!
