### ISSUE TITLE
Migrate phpIpam database to netbox

### ISSUE THREAD

**Issue by graytonio** [digitalocean/netbox#2661]
### Environment
* Python version:  3.5
* NetBox version:  v1.8.3

### Proposed Functionality
A way to import the database dump from phpIpam into netbox

### Use Case
We are currently changing to netbox from phpIpam and cannot find a good tool that we can use to migrate all the existing data to the new box

**Comment by respawner** [comment]
I don't think that NetBox should specifically allow to import the database from one tool (being PHPIPAM or anything else) into it.

That said, I think importing a PHPIPAM database into NetBox for the IPAM use should be simple enough with a script going through the PHPIPAM database and then making proper NetBox's API calls.

**Comment by jeremystretch** [comment]
This would be wholly out of scope for NetBox, as it requires keeping up to date with both NetBox _and_ phpIPAM development. There are also sure to be many places where the translation of specific data is subjective. If anything, it would be best implemented as a standalone tool.

**Comment by chicks-net** [comment]
I'm working on something similar for migrating racktables into netbox.  My plan was to create a github repo for the translator.  I'm not planning on covering every version of either product either.  I will pick one racktables and one netbox version and start with those.
