### ISSUE TITLE
VLAN Members shows same interface multiple times

### ISSUE THREAD

**Issue by Limb** [digitalocean/netbox#2663]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.0

### Steps to Reproduce
1. Create a device with (3) interfaces gi-[0-2]
2. Create (3) VLAN's [id 1,2,3]
3. Set gi-0 802.1Q Mode to Tagged and add VLAN 1 as untagged, VLAN2 and 3 as tagged.
4. Set gi-1 802.1Q Mode to Tagged and add VLAN 1 as untagged, VLAN 2 as tagged.
5. Set gi-2 802.1Q Mode to Access and add VLAN 1 as untagged.
6. View VLAN 1 Members

### Expected Behavior
The members table for VLAN 1 should list interface gi-0, gi-1 and gi-2 as members of the VLAN.

### Observed Behavior
Interface gi-0 is listed twice, follow by gi-1. If the table is sorted in reverse (sort=-name) the three individual entries appear.

**Comment by jeremystretch** [comment]
> Create VLAN (id 1000 in this case)and then assign multiple different interfaces from a device to that VLAN.

Please revise your issue to include the exact steps that can be taken to reproduce this issue.

**Comment by DanSheps** [comment]
I checked our production netbox and I am not seeing this issue on our production.  Do you have duplicate interfaces?
