### ISSUE TITLE
Web UI search results with one item should go to the item

### ISSUE THREAD

**Issue by mmahacek** [digitalocean/netbox#2668]
### Environment
* Python version:  2.5.0
* NetBox version:  3.6.x

### Proposed Functionality
When using the web interface to search, if there is only one object returned, go directly to that item instead of showing the search results.

### Use Case
If there are not multiple items found, this will help the user get directly to what they are searching for.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
The current behavior was implemented so as not to confuse a user who expects to see multiple results. For example, suppose you know there should be two core switches named core1 and core2, but one has been been mistakenly renamed. When you search for "core" you'd be automatically directed to the only result. It's not immediately apparent why.

While admittedly not as efficient, it is consistent. (There was discussion around this a while back but I can't find it.)

**Comment by tyler-8** [comment]
If the search box were something more dynamic I would say this could be better visualized in a live search result dropdown beneath the search bar, but with the current UI that behavior would be unexpected/unclear to me.

**Comment by jeremystretch** [comment]
Alrighty. We don't have the resources at the moment to do any substantial work on the search feature, so I'm going to close this out.
