### ISSUE TITLE
Virtual Switch Interfaces

### ISSUE THREAD

**Issue by rdujardin** [digitalocean/netbox#267]
It would be interesting to create a VSI object for trunk interfaces. It's useful in the IXP use case.

The VSI would have a foreign key on a vlan, and its own vlan-id (to take into account the mapping between customer vlan id and internal vpls id), and it would have a foreign key on the interface (physical) it belongs to, and a foreign key on a IP (several VSIs on the same physical interface can have different IPs).

Interface should have a new boolean field indicating if it's tagged or not (access mode or trunk mode).

Before implementing this we'd need to take into account how we would handle ethereal channels, because in the case of a new object describing these, VSI should point at such an object and not at a physical interface directly...

**Comment by jeremystretch** [comment]
I'm not clear on the concept being conveyed, but it seems a bit too complex to take on in the near term.

**Comment by jeremystretch** [comment]
In an effort to clean up the issues backlog, I'm closing all issues labelled as "discussion." If there is interest in continuing this topic, please start a thread on the [NetBox subreddit](https://www.reddit.com/r/netbox). Thanks!
