### ISSUE TITLE
DCIM LLDP Neighbor issue after 2.5 upgrade.

### ISSUE THREAD

**Issue by VeNoMouS** [digitalocean/netbox#2673]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.0

After upgrade from 2.4 to 2.5 we are getting the following error when trying to view a devices lldp neigbhours.

```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'device' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['dcim/devices/(?P<pk>\\d+)/$']
```
### Steps to Reproduce

DCIM -> devices -> lldp-neighbours

### Expected Behavior
For it to work, as in 2.4

### Observed Behavior

![image](https://user-images.githubusercontent.com/597545/49829500-7cf34c80-fdf3-11e8-9e4c-57a388d3a7d6.png)

**Comment by jeremystretch** [comment]
I'm not able to replicate this on v2.5.0. Going to `http://localhost:8000/dcim/devices/<pk>/lldp-neighbors/` works as expected. Please revise your issue to include the exact steps needed to replicate the error on a fresh installation.

**Comment by VeNoMouS** [comment]
We deleted the device and re-created it, and the issue went away, however the issue still only occurred after we upgrade from 2.4 to 2.5, so perhaps there is an issue in the upgrade migration process somewhere...

I am happy for this to be closed as we can not replicate the issue ourselves unless we restore the db and do a 2.4 to 2.5 upgrade again.

**Comment by bsteinert** [comment]
i run in to the issue. In my netbox install this only happens when there is a circuit configured on one port. If there a no circuits everything works like before.

perhaps somthing is broken because of the new "cables" feature...

**Comment by jeremystretch** [comment]
Re-opening to test @bsteinert's scenario.

**Comment by bsteinert** [comment]
@jeremystretch i have changed the "device_lldp_neighbors.html" like in "40cb576" on my netbox install and can confirm it works perfect! thank you for the quick fix of this issue!
