### ISSUE TITLE
Deleted device roles get wrong user in changelog

### ISSUE THREAD

**Issue by elsobrino** [digitalocean/netbox#2679]
### Environment
* Python version:  3.5.3
* NetBox version:  2.5.0

If a device role is deleted under /dcim/device-roles/ a wrong user gets assigned in changelog, probable the user who had created the role before.

### Steps to Reproduce

1. User A creates a device role.
2. User B deletes it afterwards.

### Expected Behavior

Changelog should say that User B deleted the role.

### Observed Behavior

Changelog says that User A deleted the role.

**Comment by jeremystretch** [comment]
I'm not able to replicate this on v2.5.0. The object shows deleted by user B as expected. Please retest.

**Comment by elsobrino** [comment]
Well, it's not reproducible anymore for us either. Definitely we had three cases that showed the described behaviour.
