### ISSUE TITLE
Support for 32-bit ASNs

### ISSUE THREAD

**Issue by DaKnOb** [digitalocean/netbox#268]
Currently adding a 32-bit ASN throws an error message in the "Add Site" page:

```
Ensure this value is less than or equal to 2147483647.
```

However you are using a signed integer in this check. The BGP ASN can be a 32-bit **un**signed integer, which means it can accept values from `0` to `4294967296`. This error can render some ASNs unmanageable. Although RIRs have not allocated an ASN this large yet, the 32-bit ASN Private Range (`4200000000` - `4294967294`) is not supported.

**Comment by jeremystretch** [comment]
The `asn` field is currently defined as a [PositiveIntegerField](https://docs.djangoproject.com/en/1.9/ref/models/fields/#positiveintegerfield) which as  @DaKnOb points out behaves as a signed integer. We might need a custom field to support unsigned 32-bit integers.
