### ISSUE TITLE
v2.5 POST to API /dcim/interface-connections fails

### ISSUE THREAD

**Issue by awlx** [digitalocean/netbox#2680]
### Environment
* Python version: 3.6-alpine3.8
* NetBox version:  2.5.0

When calling api/dcim/interface-connections with corresponding interface IDs there appears an error about the interface not belonging to a device or virtualmachine:

> The request failed with code 400 Bad Request: {'non_field_errors': ['An interface must belong to either a device or a virtual machine.']}

### Steps to Reproduce
`curl -X POST -H "Authorization: Token <token>" -H "Content-Type: application/json" -d '{"interface_a": <iface_a>, "interface_b": <iface_b>, "connection_status": true}' https://netbox.dev.test.net/api/dcim/interface-connections/`

### Expected Behavior
The connection should be created as in Netbox 2.4.9

### Observed Behavior

> The request failed with code 400 Bad Request: {'non_field_errors': ['An interface must belong to either a device or a virtual machine.']}

**Comment by jeremystretch** [comment]
The `/dcim/interface-connections` endpoint is now read-only. All connections are now created via the `/dcim/cables/` endpoint. Marking this as a bug because the endpoint shouldn't accept a POST request at all.
