### ISSUE TITLE
Tracing Cabling Path with Circuits

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#2689]
Hello,

I want to attach a circuit ID between two Rear port of a Patch Panel but the trace stop to the Circuit ID. I don' see the other side (The Both sides are attached): 

![image](https://user-images.githubusercontent.com/20238377/49992256-d1c5cd00-ff83-11e8-9286-9d9c79ce14ba.png)

Below the circuit corresponding : 

![image](https://user-images.githubusercontent.com/20238377/49992427-5a446d80-ff84-11e8-8b16-627c3b2f8bdd.png)

Is it normal ?

Regards,

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
