### ISSUE TITLE
Use Napalm to point out inconsistencies

### ISSUE THREAD

**Issue by brianatlarge** [digitalocean/netbox#2690]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.1

### Proposed Functionality
Use Napalm to access live data and compare the live environment with what is in Netbox. Any inconsistencies will be pointed out in Napalm to be rectified.

### Use Case
If you have entered in an MTU setting of 9396 on an interface in Netbox but Napalm detects that interface is actually set for 1500, a warning/notice will show next to that interface in Netbox indicating an inconsistency with the Netbox data and the live environment. This will allow you to bring the environment into compliance.

### Database Changes
Unknown at this time.

### External Dependencies
Napalm

**Comment by jeremystretch** [comment]
This is well outside NetBox's scope, and there are already well-established tools for this (Ansible, Salt, etc.). You can, however, leverage NetBox's REST API as a proxy to NAPALM for access to live devices.
