### ISSUE TITLE
Connection between interface and 8P8C port

### ISSUE THREAD

**Issue by baldoarturo** [digitalocean/netbox#2699]
### Environment
* Python version: 3.6.7
* NetBox version: 2.5.0

### Steps to Reproduce
Add a device with a 8P8C front port and a SC rear port (a media converter in real world)
Add a device with 1Gb interfaces
Connect a interface from this device to the 8P8c port of the other device

### Expected Behavior
See the cable and the termination endpoint when using the dcim/devices/ID/ template

### Observed Behavior
Cable shows, but there is no termination. Example image is attached

![image](https://user-images.githubusercontent.com/30608412/50106576-fb465900-020e-11e9-9b97-849d8044746f.png)

**Comment by jeremystretch** [comment]
Please upgrade to NetBox v2.5.1 and see if this issue has been addressed.

**Comment by baldoarturo** [comment]
Thanks a lot for the **fast** reply Jeremy! 
I just updated and the behavior is the same, screenshot is attached
![image](https://user-images.githubusercontent.com/30608412/50107366-48c3c580-0211-11e9-87a2-976be19b28c5.png)

The cable looks allright 
![image](https://user-images.githubusercontent.com/30608412/50107455-8a547080-0211-11e9-80c2-12c2bc9297e9.png)

**Comment by jeremystretch** [comment]
This is intended behavior. There is no end-to-end connection: The cable is connected to a pass-through device with no connection on the far end. You'll need to complete the cable to show a completed connection.

**Comment by baldoarturo** [comment]
Great, I got it now
Thanks a lot for your time!
