### ISSUE TITLE
"select all" checkbox results in CSS failure within the grid

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#27]
To duplicate, go to:

```
/dcim/racks/
```
...and check the box that selects all entries.

I have two pages of rack entries if that makes a difference

**Comment by jeremystretch** [comment]
Doesn't seem to do anything out of the ordinary for me. Can you provide a screenshot? Also, what browser are you using?

**Comment by bellwood** [comment]
![before](https://cloud.githubusercontent.com/assets/2453632/16390708/1edc3e62-3c72-11e6-98bf-172ca9480d5c.png)
![after](https://cloud.githubusercontent.com/assets/2453632/16390707/1ed4e25c-3c72-11e6-857d-936cdbfae426.png)

**Comment by jeremystretch** [comment]
Hmm, that's really weird. Wasn't able to replicate with Chrome 49.0.2623.108-1 or 51.0.2704.106-1. Maybe a bug in Chrome 51.0.2704.103; can you try 106-1?

I can't think of anything that would be causing it, as checking the top box simply checks all the others using vanilla jQuery/Bootstrap.

**Comment by bellwood** [comment]
Still happening in 106 but in the latest Safari it's fine... Might be an extension in Chrome causing it

Can close for now, I'll re-open when I get a chance to disable plugins and if it still persists

Thanks =)
