### ISSUE TITLE
Reverse Cable Direction

### ISSUE THREAD

**Issue by sasschary** [digitalocean/netbox#2700]
### Proposed Functionality

Provide a button or something within the cable editing window which will allow the user to easily swap the A and B terminations of a cable, instead of having to recreate the cable.

### Use Case

A user connected most of his cables so that the A termination is server-side and B termination is switch-side. However, a couple of them ended up the other way around. He wants to be able to easily switch the direction so that when he looks at the list of cables, all of them go from the server to the switch, but does not want to delete the connections and put them in again.  By including a swap direction button, this could be done significantly faster.

### Database Changes

I could be wrong, but I don't think this would require any database changes.

### External Dependencies

Again, could be wrong, but I doubt this will require anything additional.

**Comment by jeremystretch** [comment]
Cables are non-directional: A and B are just labels to differentiate the ends. They don't imply any significance.
