### ISSUE TITLE
Assigning Vlans in Vlangroups to prefixes no more possible after upgrade to newest version

### ISSUE THREAD

**Issue by hotschmaster23** [digitalocean/netbox#2704]
### Environment
* Python version:  3.6
* NetBox version:  2.5.1

### Steps to Reproduce
Assigning Vlans in Vlangroups to prefixes no more possible after upgrade to newest version.
We have a lot of datacenters and assign to every datacenterlocation one VLAN Group with same VLANS. After that we assign our Prefixes (Private and Public) to these different Groups and Vlans.
After upgrade to newest version of netbox 2.5.1, you are able to choose the Vlan group when a new Prefix is created, but no Vlan choice is possible in the dropdown menu, but the vlans are in these groups.

### Expected Behavior
Please resolve it that this function is possible again

**Comment by hotschmaster23** [comment]
Steps to reproduce this issue:
1.) Click on menu entry IPAM and navigate to "Vlan Groups", choose "+" to add a VLAN Group.
2.) Create a new Vlan Group Name 
3.) Click on menu entry IPAM, navigate to "VLANS" and click on "+" to new VLANS for this new VLAN Group. 
4.) In the field VLAN navigate to Group and click on the drop down menu to choose the new created VLAN Group
5.) After the new VLANs and VLAN Group are created go to VLAN and click on "+Add a prefix" in the field Prefixes on the right site.
6.) Add a Prefix, to reproduce this issue, choose a dummy Prefix like 192.168.0.1/24
7.) Navigate to Site/VLAN Assignment and choos the new VLAN Group which you created in step 3.)
8.) Now you will notice that no VLAN can be selected in the drop down menu "VLAN", only a "+" character will be displayed also when you wait 10 minutes no vlan will be displayed
This happens with every VLAN Group we have and with every constellation
- with or without Tenancy -> Tenant Group -> Tenant 
- with or without Site in Site/VLAN Assignment
- with every Prefix and we are a service provider who has a lot of prefixes

hope this helps to reproduce the issue

**Comment by rgrueebler** [comment]
Hi everyone,

I have the same issue. When I navigate to IPAM -> Prefixes -> select a prefix -> click "Edit this prefix".
Under the section "Site/VLAN Assignment" I can select a VLAN group but I am unable to select a specific VLAN in that group. 
I expect that I can assign a VLAN-group and a VLAN to a prefix. This was possible in the previous versions.

Best regards
Remo

**Comment by baldoarturo** [comment]
I can confirm this happens on v2.5.1

![image](https://user-images.githubusercontent.com/30608412/50236493-5015db00-0399-11e9-8cf1-aef6a01cc5cb.png)

It looks like the issue is on the template rendering, I have no way to debug it now, but I tried to create the prefix using the Import option, using the vlan_group and vlan_vid fields

**Comment by hotschmaster23** [comment]
thank you very much Jeremy
