### ISSUE TITLE
Swagger API Browser No Longer Filters By Endpoint

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#2705]
### Environment
* Python version:  3.6.5
* NetBox version:  v2.5.1

### Steps to Reproduce
Browse to `/api/docs/` and attempt to filter on `dcim`.
The only filter that functions now is `api` which is not very helpful as they **_all_** being with `api`

See screenshot below from `v2.5.1`.

With no filter applied:
![image](https://user-images.githubusercontent.com/7783306/50170612-88d88600-02ad-11e9-8788-a5768ea7cc60.png)

Attempting to filter on `dcim`:
![image](https://user-images.githubusercontent.com/7783306/50170663-aad20880-02ad-11e9-8a90-4fd2e3925512.png)

Versus the previous behavior on `v2.4.8`:

With no filter applied:
![image](https://user-images.githubusercontent.com/7783306/50170740-d94fe380-02ad-11e9-9e17-e7d55298f6a1.png)

Filtering on `dcim`:
![image](https://user-images.githubusercontent.com/7783306/50170781-f389c180-02ad-11e9-886f-dc3de80baead.png)

### Expected Behavior
It should correctly filter on the named endpoints.

### Observed Behavior
Endpoints are no longer filterable.

**Comment by jeremystretch** [comment]
Swagger has been rife with problems since it was introduced. We're soon replacing it with either the DRF built-in docs (#2665) or custom code. If you want to submit a PR for a short-term fix I'll leave this open. Otherwise, I don't think we're going to expend any more effort on Swagger unless it's a critical bug.

**Comment by jeremystretch** [comment]
Fixed this by excluding the root API view from Swagger UI.

**Comment by bdlamprecht** [comment]
That appears to have been a simple fix, thanks!

**Comment by jeremystretch** [comment]
Yeah, it was a pleasant surprise. :)
