### ISSUE TITLE
ConfigContexts Failed To Load After Updating Value on CustomField for 'dcim.devices' Object

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#2706]
### Environment
* Python version:  3.6.5
* NetBox version:  2.5.1

### Steps to Reproduce
Using `pynetbox` version `4.0.5`, attempt to save a value of a predefined `custom_field` on the `dcim.devices` object and call the `save()` function. That completes successfully.

However, when browsing to the URL `/dcim/devices/<pk>/config-context/`, this error is subsequently displayed:

![netbox_config_context_error](https://user-images.githubusercontent.com/7783306/50183002-204dd100-02ce-11e9-8885-ea6fef1975d6.PNG)

### Expected Behavior
To display the compiled `config_context` form the `local_config_data` with the rest of the defined `config_context` data as appropriate.

### Observed Behavior
The WebUI failed as well as all calls for the device in the API.

### Other Comments ###
I'm not sure exactly _**where**_ this error is occurring so please let me know what other information you need from me to reproduce the issue.

**Comment by jeremystretch** [comment]
Please provide the exact steps needed to recreate this bug without using pynetbox (a `curl` command is preferrable).

**Comment by bdlamprecht** [comment]
Let me see if I can figure out the translation from `pynetbox` into `curl` and I'll post submit the lines to recreate the error.

**Comment by bdlamprecht** [comment]
So I can't seem to find the commit where I saw this occur consistently (perhaps I didn't _**actually**_ do a commit).

Since I've worked around the issue (it was me probably sending invalid data to the API), I'm going to close this bug report.
