### ISSUE TITLE
recover Deleted Device using changelog

### ISSUE THREAD

**Issue by a31amit** [digitalocean/netbox#2714]
### Environment
* Python version:  3.6
* NetBox version:  2.5.1

### Use Case
It would be nice to see if Changelog view section can get a recover a deleted device option. 
As netbox got the changelog which saves a JSON form of data. Having a recover state option would be nice. 

This would be super helpful  if the device was accidentally deleted by the user.

### Database Changes
Not sure

### External Dependencies
Not Sure

**Comment by jeremystretch** [comment]
Recovering an object involves quite a bit more logic than simply copying the record into the database. Foreign keys need to be resolved, uniqueness constraints satisfied, etc. This would require more development effort than can be reasonably allocated for a convenience function.
