### ISSUE TITLE
Add Cable Type for SAS

### ISSUE THREAD

**Issue by mmahacek** [digitalocean/netbox#2715]
### Environment
* Python version:  3.6
* NetBox version:  2.5.1

### Proposed Functionality
Add a cable type for SAS to for documenting storage array connections.

### Use Case
We have multiple SAN arrays that have expansion shelves and I would like to not have them as undefined cable types.

### Database Changes
None that I am aware of. May require a change to the Cable model.

### External Dependencies
None that I am aware of.

**Comment by jeremystretch** [comment]
Storage connections are out of scope for NetBox at this stage in development. We may reconsider this at some point in the future.
