### ISSUE TITLE
Allow searching for cables based on termination end

### ISSUE THREAD

**Issue by mmahacek** [digitalocean/netbox#2716]
### Environment
* Python version:  3.6
* NetBox version:  2.5.1

### Proposed Functionality
On the Web UI for looking at cables, you can search by cable name or type.  My proposal is to have an additional search box to filter the list of cables based on attached device name.

### Use Case
As cables are are new feature, I would like to be able to search the cables for part of a device name to see cables attached to multiple devices that fit the search term.  This would allow searching for multiple devices to verify their cabling is consistent.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Searching across generic foreign key relationships, which are used to represent cable terminations, is not supported. Even if we came up with a hack to make it work, it would be horribly inefficient.
