### ISSUE TITLE
Cable tracing starting from patch panels

### ISSUE THREAD

**Issue by coloHsq** [digitalocean/netbox#2718]
### Environment
* Python version:  3.6.5
* NetBox version:  2.5.1

### Proposed Functionality

Add cable tracing starting from devices that have pass-through ports, generally patch panels.

### Use Case

In my case where I have to manage devices located in multiple sites is a very useful feature in case you need detailed reports of devices that use patch panels between two sites.
I've already developed "cable tracing" (including this feature) on Netbox < 2.5 and for me it's very useful
In my custom app all the cable tracing functions are displayed in tables (separated from the device page) to have a complete vision of the situation and not to open the single trace, starting from device 
I actually prefer your version, but for this feature, which would actually serve as a report, it would be great have a view like this : 
![pptrace_li](https://user-images.githubusercontent.com/46020242/50335219-def63500-050a-11e9-9cb5-0f39af847fee.jpg)
On the first column the end of the trace starting from the front port, in the middle the port name and in the last column the end of the trace starting from the rear port.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
This information is available in the current view. Front and rear port connections are not displayed on the same line both to allow sufficient space and because they are not necessarily mapped one-to-one.

**Comment by coloHsq** [comment]
> This information is available in the current view. Front and rear port connections are not displayed on the same line both to allow sufficient space and because they are not necessarily mapped one-to-one.

Forgive me, but I think you haven't correctly understand my request, this feature, that I'm currently using on older version, was designed, in anticipation of some work on a bridge where our fibers pass, to know which devices would have been impacted in case of damage to the fiber (there were not any cables yet, so I made it based on patch panel's interface relations) 
Regarding the initial request I realize that it is not so clear. I'll try to explain it better, starting from a patch panel I do the complete trace , like the actual netbox version, but in both directions (first from front, and then from rear), and I display only the terminations (the devices), for example, in the screenshot I've posted, starting from the front port "6",  the connection goes through four patch panels and arrives on a fiber channel switch on port 10 (swfc01-b1306 : 10), and this is the termination of the front port trace, while for rear port trace do the same thing on the patch panel connected by trunk to the examinated patch panel. 
I hope this is more clear, so you can understand my request.
