### ISSUE TITLE
Migrating to 2.5.0+ dcim_interface__connected_interface_id_key duplicate key

### ISSUE THREAD

**Issue by anx-ag** [digitalocean/netbox#2719]
### Environment
* Python version:  3.4.2
* NetBox version:  2.4.9

### Steps to Reproduce
I've upgraded a clone of my netbox system to Debian Stretch with Python 3.5 and when I try to run the database migrations as part of the upgrade from 2.4.9 to 2.5.0 I'm getting the following errors:

Running migrations:
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying dcim.0064_remove_platform_rpc_client... OK
  Applying dcim.0065_front_rear_ports... OK
  Applying dcim.0066_cables...
    Adding console connections... 208 cables created
    Adding power connections... 72 cables created
    Adding interface connections... Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "dcim_interface__connected_interface_id_key"
DETAIL:  Key (_connected_interface_id)=(23550) already exists.

When I delete the connection in the old database and retry the migration again after a restore, it fails on a different ID. The newly introduced key constraint seems to be stumbling upon issues in our database that have not been handled by the older netbox versions.
The upgrade then fails and cannot be restarted (at least not with the manage.py script on the CLI). Can I somehow identify all records that will be problematic for the new DB scheme?

### Expected Behavior
Working DB migration.

### Observed Behavior
Non-working DB migration.

**Comment by jeremystretch** [comment]
You have overlapping interface connections defined in the database. Please see my comment [here](https://github.com/digitalocean/netbox/issues/2696#issuecomment-448649820) for the steps needed to resolve this.

**Comment by anx-ag** [comment]
Thanks, I figured that - but is there a way to find out all possible duplicates with one query? Doing that by trial and error (removing the duplicate, restoring database on the new system, run upgrade again, etc.) could take quite some time depending on the amount of duplicates hidden in the database.

**Comment by anx-ag** [comment]
The following query can be used to identity the overlapping interfaces (thanks Admir):

SELECT * FROM dcim_interfaceconnection ic1
JOIN dcim_interfaceconnection ic2 ON ic1.interface_a_id = ic2.interface_b_id
JOIN dcim_interface iface1 ON ic1.interface_a_id = iface1.id
JOIN dcim_interface iface2 ON ic1.interface_b_id = iface2.id
JOIN dcim_device d ON d.id = iface1.device_id
