### ISSUE TITLE
Connect wireless interfaces in backhaul (PtP) networks

### ISSUE THREAD

**Issue by x-drum** [digitalocean/netbox#2730]
As stated in #2067 by @jeremystretch:

> Interface connections are necessarily limited to one-to-one relationships. Modeling wireless "connections" was never a goal given their typically one-to-many and dynamic nature.

This is a feature request for a new connection type (different from the interface one) in order to document and maintain relations between wireless devices in a backhaul (or PtP) link.

### Environment
* Python version:  3.6.7
* NetBox version:  2.5.0

### Steps to Reproduce
- Create two wireless devices (every device has at least one IEEE 802.11ac interface, eg: wlan0)
- Try to connect device A wlan0 to device B wlan0 using the interface connect form, 

### Expected Behavior
Establish a connection between the two interfaces

### Observed Behavior
You are not allowed to connect the two wireless interfaces

**Comment by jeremystretch** [comment]
This was already proposed and rejected in #2067.

**Comment by x-drum** [comment]
@jeremystretch there will ever be an **alternative way** to handle this kind of devices/relationship in Netbox? 

Take Backhaul/PtP wireless networks as an example, should we give up with this kind of usage scenario or there is a way?.

Thanks and sorry for necrobumping this one.
Regars.
