### ISSUE TITLE
Bulk Update VLAN Tags

### ISSUE THREAD

**Issue by thefathacker** [digitalocean/netbox#2734]
### Environment
* Python version: 3.6.7
* NetBox version: 2.5.2

### Proposed Functionality
Bulk Update VLAN Tags of "Tagged" Device Interfaces

### Use Case
Allows Quicker VLAN Tag Assignment when creating Switch Devices

### Database Changes
Not Required Functionality/Data Already Exists

### External Dependencies
Not Required Functionality/Data Already Exists

**Comment by lampwins** [comment]
Duplicate of https://github.com/digitalocean/netbox/issues/2160
