### ISSUE TITLE
Fetch all filter values with AJAX in list views

### ISSUE THREAD

**Issue by Anthony25** [digitalocean/netbox#2735]
### Environment
* Python version:  3.7
* NetBox version:  2.5.2

### Proposed Functionality

In views like `/dcim/devices/` or `/dcim/racks/`, that include a search bar with filters, values inside each filters could be fetched asynchronously with AJAX, instead of waiting for the server to fill them before rendering the page.

### Use Case

If in one of these filters, there is a lot of objects (multiple thousands), currently the page takes time to render, as it is single threaded and heavy on CPU (in the python code, not necessarily in database if you disable the natural ordering sort). 

The most important when listing some objects in a view is the table of objects, there is no really need to wait for the filters to be rendered. These filters could be fetched in AJAX, and marked as disabled as long as the query is not over.

The page would be a lot quicker to render. For me, with 150K devices and 4K racks, by doing that for the devices view, django-debug-toolbar indicates a reduction from 3s CPU time to 800ms.
Also, it would allow to multithread each filter, and would work even better if the user has a cluster of Netbox servers.

### Database Changes

None

### External Dependencies

None

**Comment by DanSheps** [comment]
I imagine this will come when there is  front-end rewrite done, like v3 or something.

**Comment by Anthony25** [comment]
I already started to work on this, if someone is interested.

**Comment by lampwins** [comment]
If this were to be done, it would be rolled into the select2 UI changes which are under active development in the select2-ui branch.

**Comment by lampwins** [comment]
This has been wrapped into #2753 and is currently implemented for the DCIM app in the `select2-ui` branch.

**Comment by lampwins** [comment]
Implemented in `develop`
