### ISSUE TITLE
Conserve/preselect the current cluster membership when editing a device

### ISSUE THREAD

**Issue by rdegez** [digitalocean/netbox#2742]
### Environment
* NetBox version:  2.5.2

### Steps to Reproduce

1 - Create a device
2 - Add the device to an existing cluster
3 - Edit the device (and observe that the cluster fields, `Cluster group` & `cluster`, are set to empty values : the currently assigned values are not recalled)
4 - Save the device without altering any field
==> The device is removed from the cluster

### Expected Behavior

When editing a device, only a modified field should be changed after saving.

### Observed Behavior

When editing a device assigned to a cluster and saving without touching anything, the device is removed from the cluster.

**Comment by jeremystretch** [comment]
This seems to occur only when the assigned cluster belongs to a cluster group.
