### ISSUE TITLE
Add a cable type for backplane connections

### ISSUE THREAD

**Issue by kasimon** [digitalocean/netbox#2743]
### Environment
* Python version: 3.5.3
* NetBox version: 2.5.2

### Proposed Functionality
Add a cable type for backplane connections.

### Use Case
When documenting for example bladecenters with blade servers in them, the (logical) network interface is located on the blade server (device) and is connected over the bladecenter backplane to the pysical port on the blade center chassis (device). This can be perfectly modeled with netbox 2.5's new cable resource, but the existing cable types do not apply to this use case. Having a "backplane" cable type would make it possible to better describe and document these connections.

### Database Changes
None.

### External Dependencies
None

**Comment by jeremystretch** [comment]
It doesn't make sense to create a "backplane" cable type, as backplane connections of course aren't cables. (This would invalidate NetBox's design principle of replicating the real world.)

I'd recommend against using cables to model relationships between chassis blades and backplane interfaces: If these are one-to-one connections, the relationship should be inherent (e.g. port 1 maps to slot 1, etc.). But if you want to, you can simply leave the cable type blank.

**Comment by kasimon** [comment]
Understood. I agree that using a cable is quite a hack for this use, but being able to use the trace functionality from the blade server to the switch port provides a lot of value to us, so we can live with the extra "virtual cable" objects. Maybe netbox will get an even better solution for this in the future.
