### ISSUE TITLE
cable duplicate label ; or Feature Request?

### ISSUE THREAD

**Issue by ak4443** [digitalocean/netbox#2746]
### Environment
* Python version:  
* NetBox version:  

It is possible to provide cables with the same label.

As an an example:

At the switch 1 port 1 the cable with the label NET0001 is connected.
It is now possible to connect to port 2 a cable with the same label NET0001.

At this point, from my point of view, would have to be checked if there is a duplicate label.

**Comment by jbakklund** [comment]
A label should ideally only have to be unique within the perimeters of a given site, allowing you to use e.g. label 'NET0001' in both London and Paris.

**Comment by ak4443** [comment]
That's true.

Then at least below a site would have to be checked for duplicates.

**Comment by jeremystretch** [comment]
Cabling labels are entirely arbitrary and every organization uses whatever system works for them. It would be inappropriate for NetBox to assume any particular uniqueness requirement. If you need to check for duplicate labels, I suggest writing a validation report, which allows complete flexibility.

**Comment by ak4443** [comment]
Thanks ....

my workaround are in postgres DB:

create unique index unique_label on dcim_calbe(label) ;

Thus, a label can only be created once and Postgres reports a readable error.
