### ISSUE TITLE
Disconnect cable without deleting it

### ISSUE THREAD

**Issue by runeka** [digitalocean/netbox#2747]
### Proposed Functionality
I miss the option to disconnect a cable from a device without deleting it.

### Use Case
Moving one cable end to a different device is the typical scenario. As it is in v2.5.2, the cable is deleted and you will have to remake it giving it a new ID.

**Comment by jeremystretch** [comment]
If a cable is not connected at both ends, it should not be defined in NetBox. That is simply where we've drawn the demarcation line between modeling and inventory.

**Comment by runeka** [comment]
I might have explained myself in a bad way. My goal would be to be able to edit a cable end., move it to a different end. The typical scenario is patching mistakes in Netbox. In a large cable plant with many patch panels it is easy to make a mistake. Correcting the mistake by moving one end to the correct place without having to re-add all details on the cable would be nice.
