### ISSUE TITLE
Simple feature request: add OOB as ip adddress role

### ISSUE THREAD

**Issue by klaver** [digitalocean/netbox#2748]
Within NetBox it's possible to select a primary IP address for each device, mostly this is a Loopback interface. For emergency purposes it would be really nice to also have an Out-of-Band (OOB) address listed. At this moment we use the tag mechanism, but that's sub-optimal.

**Comment by jbakklund** [comment]
There is already an option available allowing you to mark an interface as only being used for "OOB Management", then you simply ad the IP address to this interface.
