### ISSUE TITLE
Rear Port bulk create Positions

### ISSUE THREAD

**Issue by TakeMeNL** [digitalocean/netbox#2754]
### Environment
* Python version:  3.6
* NetBox version:  v2.5.2

### Steps to Reproduce
Bulk create a RearPort with 
Name: RackB-A[1-12] 
Type: any
Positions: 1

### Expected Behavior
Bulk created 
RackB-A1 - position 1,
RackB-A2 - position 2,
and so on.....

### Observed Behavior
Bulk created 
RackB-A1 - position 1,
RackB-A2 - position 1,
RackB-A3 - position 1,
and so on.....

**Comment by jeremystretch** [comment]
This is expected behavior. The name pattern applies only to the name. Position identifiers are unique to their respective ports.

**Comment by TakeMeNL** [comment]
Oke thanks for the clarification, but if i have to make 32 rear ports is have to open every single one to update the position? Why is there a bulk option anyway then :/

**Comment by jeremystretch** [comment]
The positions for each rear port always start at one. You do not need to renumber them.

**Comment by TakeMeNL** [comment]
Ah, know you what. I have read the docs now 20 times, i get it now...
I have a hard time figuring out text/theorie stuff to practical operations.
I'm sorry if this was any waste of time. But thank you 💯
