### ISSUE TITLE
Add cable trace button to front/rear ports

### ISSUE THREAD

**Issue by runeka** [digitalocean/netbox#2758]
### Proposed Functionality
View trace on patchcable between patchpanels.

### Use Case
When patching through multiple patch panels it is tricky to view the end device using the patch. Would it be possible to add a link to the trace of the entire path in the cable view?

**Comment by TakeMeNL** [comment]
Just to be shure, the little blue stripe is a button. It leads to `dcim/interfaces/<id>/trace/`
Is this what you mean? 
![image](https://user-images.githubusercontent.com/980978/51037125-a26ca500-15af-11e9-960a-04279bf7a392.png)

**Comment by runeka** [comment]
Hi

That is from the device interface view I guess.
I mean from the cable view like: http://netbox.example.com/dcim/cables/201/ You can see where it is terminated, but not the end point interfaces and the entire trace. So if this patch cable is between two patch panels you will need to click through the panel path to view the path.

**Comment by TakeMeNL** [comment]
Oke fair point we have indeed a trace per interface, not for a cable.
But i think it's the same page to view the trace, only there is missing a quick link to that page?
Just trying to help out :)

**Comment by DanSheps** [comment]
@runeka You can't do this with a cable, as a cable is a link between two devices.  You need to go to the parent device (patch panel device) and initiate the trace from there under either the "front ports" or the "rear ports"

**Comment by runeka** [comment]
A cable is not necessary a link between two devices, and that is the point. When a cable is a link between two front ports it is confusing to see the device interfaces. Adding a quick link to the trace between the device interfaces, that the cable is part of would be perfect.
The reason I am asking for it is that I have some long patches like: DeviceInterface - Cable#144 - FrontPort - RearPorts - FrontPort - Cable#145 - FrontPort - RearPorts - FrontPort - Cable#146 - DeviceInterface. When searching in Netbox for cable that is physically labeled Cable#145 it is hard to see what device is using the cable and if it is in use or not. Cable#145 is connected to FrontPorts and seems to be in use, but might not be.

**Comment by tb-killa** [comment]
From my point of view I agree @runeka here.
We also have several hops about patch fields in many places.

What is actually requested here is an extension of the "Trace" view with the possibility to perform a search or input with a jump into the trace.
Say: I have e.g. the Device XYZ with the interface XYZ and see the Trace view always in the complete path (if available!).
For example, if I am in the cable view, I can also click on a link and jump to the trace view and see the complete path (if available!).
At the first the interface is passed as search, at the second the cable-ID or the label.

Am I right here with my guess @runeka ??

**Comment by runeka** [comment]
You are right. The "Trace" button should be available for all FrontPorts and cables in the path.

**Comment by tb-killa** [comment]
See my Post above, from my point of view it should display the same results as given by the search of an interface as start point. Maybe this could be some sort of modal box who use ajax request to generate the result display.

**Comment by runeka** [comment]
I agree, the exact same view as when clicking the trace on an interface. I thought this was an easy task, but I am not a software engineer.

**Comment by DanSheps** [comment]
You guys still are not answering, how do you determine the stop point?  If you are not taking interfaces into account, how do you know when to stop?  What if you loop a connection together and create a ring, you could have an infinite loop so there has to be protection in there.

**Comment by tjdavis3** [comment]
It stops when it hits an interface vs a front/back port

**Comment by DanSheps** [comment]
@tjdavis3 There might not always be an interface, that is what I am saying.  With a interface, there is a clear defined end, because an interface cannot loop onto itself, you cannot have weird splitting networks either.  IF you are just using front ports and rear ports, you can do all sorts of crazy things.

**Comment by tb-killa** [comment]
@DanSheps yes your right .. for the Ports (Front /Rear) there has to be some logic implemented who would detect collision (loop).  But how to model this ... This need some more considerations.

**Comment by tb-killa** [comment]
After review the closed issue there is a implementation for this type included and closed: Fixes #2721: Detect loops when tracing front/rear ports.

We need a simple test but this would help to close one of your arguments.

**Comment by tvberlin** [comment]
@jeremystretch thanks for implementing!
