### ISSUE TITLE
Changelog backup

### ISSUE THREAD

**Issue by alisarwan** [digitalocean/netbox#2759]
### Environment
* Python version:  
* NetBox version:  v2.5.2

### Steps to Reproduce

First I apologies to report this as an issue. 
Is there any way to backup and later restore that Changelog. 
Sorry I am very new to servers, just installed netbox with installation steps on website. 
I need to keep the record of changes that is why I need to make sure Changelog are available ever after upgrade, or when installing on a new server.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
