### ISSUE TITLE
Database Issues: Entries disappear sometimes

### ISSUE THREAD

**Issue by N4unch0rch** [digitalocean/netbox#2761]
Good Day!

I´ve got some problems with my netbox installation.
I imported the interface connections between my patchpanels with csv-files created by Excel.

After the import, everything was fine.
But now, sometimes the entries disappear (image attached).
After a few reloads the data is back again.

Used version: 2.5.2

Any ideas ?

![netbox](https://user-images.githubusercontent.com/20942888/50830923-8cf64180-1349-11e9-8343-6f811d29af24.PNG)

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
