### ISSUE TITLE
umlauts doesnt work 

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#2764]
### Environment
* Python version:  3.6
* NetBox version:  2.5.2

### Steps to Reproduce
Go to: Organization 
Submenu: Tenants
Klick "Add" on top right.

Inside "Name" paste "öäüÖÄÜ"

### Expected Behavior
The Input umlauts should be parsed in the "Slug" Input field like this:
oeaeueOeAeUe

### Observed Behavior
Nothing: The Slug is empty. If someones Name is with umlauts the specific alphabetic character is missing.

**Comment by jeremystretch** [comment]
This is expected behavior. Those characters are removed because they aren't matched by the regex `\w` pattern. The slugify convenience function (below) doesn't perform arbitrary character substitution, but you can always modify the slug manually.

```
function slugify(s, num_chars) {
    s = s.replace(/[^\-\.\w\s]/g, '');          // Remove unneeded chars
    s = s.replace(/^[\s\.]+|[\s\.]+$/g, '');    // Trim leading/trailing spaces
    s = s.replace(/[\-\.\s]+/g, '-');           // Convert spaces and decimals to hyphens
    s = s.toLowerCase();                        // Convert to lowercase
    return s.substring(0, num_chars);           // Trim to first num_chars chars
}
```
