### ISSUE TITLE
Search for interface is not working when creating connection

### ISSUE THREAD

**Issue by Simonpiro** [digitalocean/netbox#2765]
### Environment
* Python version:  3.6.8
* NetBox version:  2.5.2

### Steps to Reproduce
If i pick any interface on the device and click connect, i will get to interface connection page. 
When i am trying to search for terminating interface in side B form, dropdown list is unpopulated.

### Expected Behavior
Expected is to see list of all interfaces on terminating device.

### Observed Behavior
Seems like API URL is not created correctly with new choices added to Port Type.
Broken URL: 
/api/dcim/18s/?device_id=74&limit=0&brief=1

Correct URL: 
/api/dcim/interfaces/?device_id=74&limit=0&brief=1

Looks like it should be taking api-value to url and its taking value from "termination_b_type" option:
`<option value="18" api-value="interface">Interface</option>`

dcim/forms.py : 

`termination_b_id = forms.IntegerField(
        label='Name',
        widget=APISelect(
            api_url='/api/dcim/{{termination_b_type}}s/?device_id={{termination_b_device}}',
            disabled_indicator='cable',
            url_conditional_append={
                'termination_b_type__interface': '&type=physical',
            }
        )`

**Comment by TakeMeNL** [comment]
I can't reproduce it, have you reloaded you're browsers cache? 
Maybe this is just a jQuery thing because it was changed.

**Comment by jeremystretch** [comment]
Also check that you remembered to run `./manage.py collectstatic` as part of the last upgrade. (The upgrade script will handle this for you.)

**Comment by Simonpiro** [comment]
Hello, i tried to run `./manage.py collectstatic` again. But it didnt copy anything new.
I also cleared cache and tried other browsers and computers. 
I still think its caused by `{{termination_b_type}}` taking `value` from form option instead of `api-value` for URL creation.

**Comment by Simonpiro** [comment]
You are right. Seems like our JS files did not get upgraded. We are running netbox in docker image. Is there a way to upgrade files when `./manage.py collectstatic` didnt help?
Thank you

**Comment by Simonpiro** [comment]
Its all set now. Just deleted all old static files.
Thank you for your help.
