### ISSUE TITLE
Enhancement for PopUp Content (Rack-View)

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#2767]
### Environment
* Python version: 3.6
* NetBox version: 2.5.2

### Proposed Functionality
Enhancement for PopUp Content (Rack-View) with own definable show context (Admin-Site / Global Settings).
Actually we display at hovering on Device inside a Rack-View the 
* Management - Role
* Device - Device Type
* Device - Serial Number

**(Sadly without the titling before every Value!)**
It should be show as (e.g) / (maybe cutting the titling Value?) :
* Management-Role: OOB Switch
* Device - Device Type: Opengear CM4148 (1U)
* Device - Serial Number: 98273942938

As everyone use another part of needing Informations who has to be displayed in the PopUp we should implement something dynamic selectable.

I thought about something like we actually do for e.g. webhook (Admin-Page / Add).
We could bring in a new Sektion on the Admin-Page named e.g. Device-Tooltip and show the "Object types" as a selectable Menu.

Inside this multiselection we should show all the Object Types for:
* Device
* Management
* Tags
* Own builded custom field from (dcim>device) and (dcim>rack)

### Use Case
As every Use Case is difficult, some Organisations need other Informations on ToolTip for quick showable. 

With this Implementation the Admin(s) define Global Showable Content for the PopUp.

### Database Changes
Yes

### External Dependencies
Maybe not, Maybe Yes with something external like "Two-side Multi Select"

**Comment by jeremystretch** [comment]
No further work on rack display will be done until #2248 has been implemented. Closing this out; please feel free to revisit the topic after #2248.
