### ISSUE TITLE
Documentation Typo Error?

### ISSUE THREAD

**Issue by odcheck** [digitalocean/netbox#2768]
The documentation reads

```
location /static/ {
        alias /opt/netbox/netbox/static/;
    }
```
but correct would be

```
location /static/ {
        alias /opt/netbox/netbox/project-static/;
    }
```

**Comment by jeremystretch** [comment]
The documentation is correct. Please be sure to use one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) for any future issues.
