### ISSUE TITLE
Update 3-httpd-deamon Apache Configuration Static Path Location

### ISSUE THREAD

**Issue by kadonnelly13** [digitalocean/netbox#2773]
### Change Type
[ ] Addition
[X] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

Update the file path on the sample Apache configuration file in the documentation on lines 70 and 75.

https://github.com/digitalocean/netbox/blob/master/docs/installation/3-http-daemon.md

Current
`/opt/netbox/netbox/static`

Proposed
`/opt/netbox/netbox/project-static`

**Comment by lampwins** [comment]
The documentation is correct. When you run the `manage.py collectstatic` command the static assets are rendered in `/static`. The upgrade script does this for you.
