### ISSUE TITLE
Cannot create host addresses (/32) as prefixes. These should be IPv4 addresses instead.

### ISSUE THREAD

**Issue by rekeds** [digitalocean/netbox#278]
Hi,
if it's a /32 loopback prefix/address.

Looking under Prefixes gives a /32 an Available spot, but the IP is assigned under IPs.
Can't fill the Available ip except importing a /32 entry in Prefixes.

Maybe we could somehow have the /32 marked differently if there is an IP assigned or adding /32 prefixes should be allowed.

(sorry for the english)

**Comment by jeremystretch** [comment]
A /32 is an individual IP address, not a prefix. IPv4 prefixes can only be /31 or larger.

**Comment by rekeds** [comment]
but that doesn't work.

two /32 loopbacks on different devices, yet I have to show in netbox that it's a /31 prefix? 
so that in the Prefix view the IPs are not marked as "Available"? :[

**Comment by jeremystretch** [comment]
> two /32 loopbacks on different devices, yet I have to show in netbox that it's a /31 prefix?

No, not at all. In most cases, you'll define a container prefix from which you allocate loopback addresses. For example, if I allocate a loopback IP for each device at a site from 192.0.2.0/24, I'll define that prefix as a container and each of the loopbacks as an individual IP. This is optional of course: You don't strictly need to define a prefix to hold these.

> also, the prefix importer allows /32.

Thanks, will get that fixed.
