### ISSUE TITLE
upgrade.sh error not detecting Python 3.6

### ISSUE THREAD

**Issue by chuckcastle** [digitalocean/netbox#2780]
I'm currently offline after attempting to upgrade to the latest release of NetBox. It was initially deployed with Python 3.4.9 but the upgrade wants 3.5 or higher (according to the error output). I installed Python 3.6 and was able to migrate most requirements but still have the following problem:

`
[root@netbox netbox]# python3.6 netbox/manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
Running migrations:
  No migrations to apply.
[root@netbox netbox]# python3.6 netbox/manage.py collectstatic --no-input

0 static files copied to '/opt/netbox/netbox/static', 280 unmodified.
[root@netbox netbox]# ./upgrade.sh
Cleaning up stale Python bytecode (find . -name "*.pyc" -delete)...
Removing old Python packages (pip3 uninstall -r old_requirements.txt -y)...
Skipping django-rest-swagger as it is not installed.
Skipping psycopg2 as it is not installed.
Skipping pycrypto as it is not installed.
Updating required Python packages (pip3 install -r requirements.txt --upgrade)...
Requirement already up-to-date: Django==2.1.4 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (2.1.4)
Requirement already up-to-date: django-cors-headers==2.4.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (2.4.0)
Requirement already up-to-date: django-debug-toolbar==1.11 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (1.11)
Requirement already up-to-date: django-filter==2.0.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (2.0.0)
Requirement already up-to-date: django-mptt==0.9.1 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (0.9.1)
Requirement already up-to-date: django-tables2==2.0.3 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (2.0.3)
Requirement already up-to-date: django-taggit==0.23.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (0.23.0)
Requirement already up-to-date: django-taggit-serializer==0.1.7 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (0.1.7)
Requirement already up-to-date: django-timezone-field==3.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 9)) (3.0)
Requirement already up-to-date: djangorestframework==3.9.0 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 10)) (3.9.0)
Requirement already up-to-date: drf-yasg[validation]==1.11.1 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 11)) (1.11.1)
Requirement already up-to-date: graphviz==0.10.1 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 12)) (0.10.1)
Requirement already up-to-date: Markdown==2.6.11 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 13)) (2.6.11)
Requirement already up-to-date: netaddr==0.7.19 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 14)) (0.7.19)
Requirement already up-to-date: Pillow==5.3.0 in /usr/lib64/python3.6/site-packages (from -r requirements.txt (line 15)) (5.3.0)
Requirement already up-to-date: psycopg2-binary==2.7.6.1 in /usr/lib64/python3.6/site-packages (from -r requirements.txt (line 16)) (2.7.6.1)
Requirement already up-to-date: py-gfm==0.1.4 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 17)) (0.1.4)
Requirement already up-to-date: pycryptodome==3.7.2 in /usr/lib64/python3.6/site-packages (from -r requirements.txt (line 18)) (3.7.2)
Requirement already satisfied, skipping upgrade: pytz in /usr/lib/python3.6/site-packages (from Django==2.1.4->-r requirements.txt (line 1)) (2018.9)
Requirement already satisfied, skipping upgrade: sqlparse>=0.2.0 in /usr/lib/python3.6/site-packages (from django-debug-toolbar==1.11->-r requirements.txt (line 3)) (0.2.4)
Requirement already satisfied, skipping upgrade: django-js-asset in /usr/lib/python3.6/site-packages (from django-mptt==0.9.1->-r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3.6/site-packages (from django-taggit-serializer==0.1.7->-r requirements.txt (line 8)) (1.12.0)
Requirement already satisfied, skipping upgrade: inflection>=0.3.1 in /usr/lib/python3.6/site-packages (from drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (0.3.1)
Requirement already satisfied, skipping upgrade: ruamel.yaml>=0.15.34 in /usr/lib64/python3.6/site-packages (from drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (0.15.85)
Requirement already satisfied, skipping upgrade: coreapi>=2.3.3 in /usr/lib/python3.6/site-packages (from drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (2.3.3)
Requirement already satisfied, skipping upgrade: coreschema>=0.0.4 in /usr/lib/python3.6/site-packages (from drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (0.0.4)
Requirement already satisfied, skipping upgrade: uritemplate>=3.0.0 in /usr/lib/python3.6/site-packages (from drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (3.0.0)
Requirement already satisfied, skipping upgrade: flex>=6.11.1; extra == "validation" in /usr/lib/python3.6/site-packages (from drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (6.13.2)
Requirement already satisfied, skipping upgrade: swagger-spec-validator>=2.1.0; extra == "validation" in /usr/lib/python3.6/site-packages (from drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (2.4.1)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3.6/site-packages (from py-gfm==0.1.4->-r requirements.txt (line 17)) (39.0.1)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3.6/site-packages (from coreapi>=2.3.3->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (2.21.0)
Requirement already satisfied, skipping upgrade: itypes in /usr/lib/python3.6/site-packages (from coreapi>=2.3.3->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (1.1.0)
Requirement already satisfied, skipping upgrade: jinja2 in /usr/lib64/python3.6/site-packages (from coreschema>=0.0.4->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (2.10)
Requirement already satisfied, skipping upgrade: validate-email<2,>=1.2 in /usr/lib/python3.6/site-packages (from flex>=6.11.1; extra == "validation"->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (1.3)
Requirement already satisfied, skipping upgrade: rfc3987<2,>=1.3.4 in /usr/lib/python3.6/site-packages (from flex>=6.11.1; extra == "validation"->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (1.3.8)
Requirement already satisfied, skipping upgrade: strict-rfc3339<1,>=0.7 in /usr/lib/python3.6/site-packages (from flex>=6.11.1; extra == "validation"->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (0.7)
Requirement already satisfied, skipping upgrade: PyYAML<4,>=3.11 in /usr/lib64/python3.6/site-packages (from flex>=6.11.1; extra == "validation"->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (3.13)
Requirement already satisfied, skipping upgrade: jsonpointer<2,>=1.7 in /usr/lib/python3.6/site-packages (from flex>=6.11.1; extra == "validation"->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (1.14)
Requirement already satisfied, skipping upgrade: click<7,>=3.3 in /usr/lib/python3.6/site-packages (from flex>=6.11.1; extra == "validation"->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (6.7)
Requirement already satisfied, skipping upgrade: jsonschema in /usr/lib/python3.6/site-packages (from swagger-spec-validator>=2.1.0; extra == "validation"->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (2.6.0)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/lib/python3.6/site-packages (from requests->coreapi>=2.3.3->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (2.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/lib/python3.6/site-packages (from requests->coreapi>=2.3.3->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (2018.11.29)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->coreapi>=2.3.3->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->coreapi>=2.3.3->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (3.0.4)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/lib64/python3.6/site-packages (from jinja2->coreschema>=0.0.4->drf-yasg[validation]==1.11.1->-r requirements.txt (line 11)) (1.1.0)
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 13, in <module>
    "NetBox requires Python 3.5 or higher (current: Python {})".format(sys.version.split()[0])
RuntimeError: NetBox requires Python 3.5 or higher (current: Python 3.4.9)
Collecting static files (python3 netbox/manage.py collectstatic --no-input)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 13, in <module>
    "NetBox requires Python 3.5 or higher (current: Python {})".format(sys.version.split()[0])
RuntimeError: NetBox requires Python 3.5 or higher (current: Python 3.4.9)
[root@netbox netbox]#
`

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
