### ISSUE TITLE
Update to 2.5.3 DB issue

### ISSUE THREAD

**Issue by DrMxxxxx** [digitalocean/netbox#2784]
**Environment**
Python version: 3.5.3
NetBox version: v2.5.3
Postgresql version: 9.6.10
**Steps to Reproduce**
run ./upgrade.sh to upgrade to v2.5.3
Log:
Applying database migrations (python3 netbox/manage.py migrate)...
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, tenancy, users, virtualization
Running migrations:
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying dcim.0064_remove_platform_rpc_client... OK
  Applying dcim.0065_front_rear_ports... OK
  Applying dcim.0066_cables...
    Adding console connections... 0 cables created
    Adding power connections... 0 cables created
    Adding interface connections... 0 cables created OK
  Applying circuits.0013_cables...
    Adding circuit terminations... 0 cables created OK
  Applying circuits.0014_circuittermination_description... OK
  Applying dcim.0067_device_type_remove_qualifiers... OK
  Applying dcim.0068_rack_new_fields... OK
  Applying extras.0015_remove_useraction... OK
  Applying extras.0016_exporttemplate_add_cable... OK
Collecting static files (python3 netbox/manage.py collectstatic --no-input)...

280 static files copied to '/opt/netbox-2.5.3/netbox/static'.

restart netbox with supervisorctl restart netbox
Try to open the Website from Netbox
**Expected Behavior**
Website is still reachable and the DB is working

**Observed Behavior**
The Website is not reachable with a DB issue:
![snipimage](https://user-images.githubusercontent.com/41616347/51112661-bdcdef00-17ff-11e9-9fb5-bcca5e06efd8.JPG)

When I look into the DB, I cannot find the table "dcim_interfaceconnection".

**Comment by DanSheps** [comment]
I just performed an upgrade on netbox myself.

What version were you coming from?  Did you restart gunicorn/the wsgi service?  (supervisord unless you customized it)

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
