### ISSUE TITLE
available-ips should return /32 if is_pool flag in prefix is set

### ISSUE THREAD

**Issue by s11-charendt** [digitalocean/netbox#2785]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.2

### Proposed Functionality
When requesting an ip-address via API/available-ips and the is_pool flag is set in the used prefix, netbox should return the ip-address with a /32 mask, instead of the mask of the prefix. The behaviour, if the is_pool flag is not set, should not change.

### Use Case
We use netbox to assign ip-addresses to virtual machine interfaces. We are in a completely routed environment. So every ip is independent from each other, the only mask making sense is a /32. This is our understanding of an ip-pool, but I 'd like to read other thoughts on that.

### Database Changes
none

### External Dependencies
none

**Comment by s11-charendt** [comment]
Thats strange, as I have searched for templates, but they did not show up, when creating a new ticket. Your direct link works though, so I've updated the issue.

**Comment by jeremystretch** [comment]
> When requesting an ip-address via API/available-ips and the is_pool flag is set in the used prefix, netbox should return the ip-address with a /32 mask, instead of the mask of the prefix.

I see no justification for this. There may be instances where you want to retain the prefix mask, so the API provides it. And in cases where you don't, it's trivial to swap out the provided mask for a /32 (or /128).

**Comment by s11-charendt** [comment]
What is the use case of assigning 192.168.1.255/24 to an interface then?
