### ISSUE TITLE
drop-down menu limitation

### ISSUE THREAD

**Issue by alisarwan** [digitalocean/netbox#2787]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.2

I am working in a ISP having around 10000 customers of different categories at the moment, customer will increase with time. Customers are differentiated by a unique 9-digit number. 

I have 5000 tenants under a particular tenant group, these are to be increased with time as customers increases. When assigning a /32 IP address to any customer, I cannot see more than 1000 tenants of that group from drop-down menu, whereas I must be able to select/see all tenant under particular tenant group.
See image here https://groups.google.com/group/netbox-discuss/attach/12d099802b9dec/002.png?part=0.2&authuser=0&view=1

### Proposed Functionality

There can be two possibilities for that.

1. Drop-down shows all tenants of the group selected, let it be 10,000+
2. There should be a field to fill manually, but for this option entered tenant must be created earlier. 

I'm sure this is not due to any limitation on my system, from where I am viewing. I have used multiple browsers, different systems, but I am facing issue everywhere. 

This could be due to limitation of database or something.

**Comment by DanSheps** [comment]
This will probably be taken care with Select2, which @lampwins is working on in the select2-ui branch.

**Comment by lampwins** [comment]
This is fully covered in https://github.com/digitalocean/netbox/issues/2516
