### ISSUE TITLE
DISREGARD - Device Templates

### ISSUE THREAD

**Issue by chonty** [digitalocean/netbox#279]
DISREGARD -

If we have several fixed-configuration devices of the same type (e.g. Cisco Nexus 3064), it'd be great to define its interfaces at this level rather than on each individual instance of the device separately.

**Comment by chonty** [comment]
DISREGARD - SPOKE TOO SOON,  Wasn't in the device creation creation screen so made the assumption it wasn't a feature

**Comment by bellwood** [comment]
Chonty, if this is a non-issue feel free to close it out =)

**Comment by chonty** [comment]
ah there it is
