### ISSUE TITLE
The possibility of linking Virtual Interfaces of a VM to a physical interface

### ISSUE THREAD

**Issue by sleeplessnight2** [digitalocean/netbox#2790]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.2

### Proposed Functionality

The possibility of linking Virtual Interfaces of a VM to a physical interface.

Example: Vmware ESXi has Virtual Switches. Documenting this, in which one can associate a VM machine with a physical interface, makes a great deal of work easier, since ESXi can only assign MAC addresses to the physical interface and there is usually never a MAC on the Ethernet port.

### Use Case

That would be very helpful, because otherwise you would have to make the connection in a very confusing way (by interface name and / or only in the description).

When you look at the physical machine you can see which virtual machines are involved, should you disconnect the physical connection X.

This is very helpful if you want to use Netbox to document racks and their contents to perform maintenance on specific machines.

### Database Changes

I believe this will require an addition of a new field.

**Comment by jeremystretch** [comment]
Different virtualization platforms have different ways of representing interface associations and attempting to accomodate them all would be a never-ending chore. It's also pretty firmly outside NetBox's role as an IPAM/DCIM system. Closing as out of scope.

**Comment by sleeplessnight2** [comment]
Sorry, that's not true. They all have to follow the same principle: One phyiscal Port to one or many Virtual Interfaces. This solution is platform independent.

But if that is not Netbox's role as IPAM then I wonder why it has a cable management on board. Or a Rack Managment.
I do not want to argue, but that's exactly what made netbox so interesting for me / us. Using a different system for each case is impractical and does not make much sense. Maybe also a reason why the topic of documentation is always avoided.

In any case, Netbox is no longer pure IPAM in the current range of functions.
Too bad that this is not desirable. Anyway, I can give an answer to the question of why Netbox can not do that simple function: It is not desired by you.
