### ISSUE TITLE
Add a comment field for tags

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#2791]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.3

### Proposed Functionality
Extend the Tag model to include an arbitrary comment/description field.

### Use Case
It would be very helpful to have the ability to record a description or note for each tag. For example, a tag `foobar9k` might have the description "This resource is monitored by the FooBar9000 NMS."

A description can be set only once a tag has been created.

### Database Changes
This will involve migrating away from the stock model provided by the `django-taggit` package. Further research is needed to determine how disruptive this will be, but probably not very.

### External Dependencies
None

**Comment by jeremystretch** [comment]
Related: #2324

**Comment by lampwins** [comment]
Implemented in the develop-2.6 branch.
