### ISSUE TITLE
Normalize Interface Names in "LLDP Neighbors" Tab nxos

### ISSUE THREAD

**Issue by runeka** [digitalocean/netbox#2792]
### Environment
* NetBox version:  2.5.3 

This is almost the same issue as #1621 but on nxos Cisco Nexus. Napalm for Nexus LLDP returns a short interface name for local device and full interface name for remote device. This makes it impossible to match interface naming in Netbox.

leaf2# sh lldp neighbors 
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID            Local Intf      Hold-time  Capability  Port ID 
leaf1.example.com
                     **Eth1/47**         120        BR          **Ethernet1/47**

### Steps to Reproduce
1. LLDP Neighbors tab on Cisco Nexus Switches.

### Expected Behavior
I expected that interface naming matching LLDP naming would work.

### Observed Behavior
Impossible to match interfaces correctly.

**Comment by jeremystretch** [comment]
We're not going to keep tweaking the logic to accommodate the quirks of different platforms. You'll need to name your interfaces the way the platform reports them if LLDP validation is important. If a platform is reporting interfaces inconsistently, that's an issue to be raised with the vendor.

**Comment by runeka** [comment]
I do see your point. But it is impossible to match it as Cisco report local (Eth) and remote (Ethernet) interfaces differently. It is possible to match local, but remote will never match.
