### ISSUE TITLE
Multi Site Use

### ISSUE THREAD

**Issue by dwojcAVI** [digitalocean/netbox#2794]
I was hoping to use netbox for an IPAM for the 100+ sites we have to track their WAN IP usage, carrier info,  and also their internal network usage.  From what i'm seeing this would be a bit cumbersome as we only have 3 may be 4 devices that would be in place and the networks overlap in some places.  The only way around this that i'm seeing is to use a VFR for each site.  Is there another feature or method to set this up that would allow a pure site division setup where when you choose a site you are working in that site and that site alone.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
