### ISSUE TITLE
Paginator appears twice on child prefixes/IPs view

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#2795]
### Environment
* Python version: 3.5.2
* NetBox version: 2.5.3

### Steps to Reproduce
1. Find a prefix with one or more child prefixes
2. Click the "prefixes" tab to view the child prefixes

### Expected Behavior
The list pagination widget should be displayed only once.

### Observed Behavior
The list pagination widget appears twice. This also occurs when viewing child IP addresses within a prefix.

**Comment by mmahacek** [comment]
I was just coming here to post this.  My uneducated guess makes me think there is something with both `netbox/templates/utilities/obj_table.html` and `netbox/templates/panel_table.html` having references to including the paginator.

**Comment by mmahacek** [comment]
This doesn’t seem to be a breaking issue, and I haven’t found it happening on any other page.

**Comment by jeremystretch** [comment]
For reference, here's the current template tree. Note that the paginator gets included twice.

```
- ipam/prefix_prefixes.html
    - utilities/obj_table.html (with table_template='panel_table.html')
        - panel_table.html
            - inc/paginator.html
        - inc/paginator.html
```
