### ISSUE TITLE
Add support for virtual networks

### ISSUE THREAD

**Issue by LukeRussell** [digitalocean/netbox#2797]
### Environment
* Python version:  3.6
* NetBox version:  2.4.8

### Proposed Functionality
Add support for virtual networks.
* vSwitches
* Connecting VM interfaces to vSwitch interfaces
* Connecting vSwitch interfaces to physical interfaces
* Assigning VLANs to vSwitches

### Use Case
Accurately modelling virtual networks.

### Database Changes
Probably a new virtual switch object, which would be very similar to a normal network device.

**Comment by jeremystretch** [comment]
This would amount to a major new feature, and unfortunately we're not currently accepting requests which would extend NetBox's scope (see the [contributing guide](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md)). It's a topic we'll almost certainly revisit at some point in the future once the current backlog of feature requests has been addressed.

**Comment by sleeplessnight2** [comment]
> ### Environment
> * Python version:  3.6
> * NetBox version:  2.4.8
> 
> ### Proposed Functionality
> Add support for virtual networks.
> 
> * vSwitches
> * Connecting VM interfaces to vSwitch interfaces
> * Connecting vSwitch interfaces to physical interfaces
> * Assigning VLANs to vSwitches
> 
> ### Use Case
> Accurately modelling virtual networks.
> 
> ### Database Changes
> Probably a new virtual switch object, which would be very similar to a normal network device.
> 
> ### External Dependencies

Luke, ist there a possibility to do this as a own fork?

I'm recieving the same answer as you and it smells like laziness, because a vswitch and a real switch does not make any difference to Netbox. IP's are IP's. Used virtual or not. And IP's are a core function of a IPAM. And IP's are part of the core of an IPAM.

**Comment by ryanmerolle** [comment]
You can totally fork this or submit a PR with a proposed model, that is your freedom given the open source nature of this project.  Many users actually just model the virtual switches and routers as physical devices for now and apply a tag as "virtual".

@jeremystretch was providing a clear answer, and I do not see any laziness here.  To quote the link he provided you:

> Due to an excessive backlog of feature requests, we are not currently accepting any proposals which substantially extend NetBox's functionality beyond its current feature set. This includes the introduction of any new views or models which have not already been proposed in an existing feature request.

The reality is that:
- The project contributors would not look to simply just implement a "quick implementation" given the impact to user base if the data model is not done well
- A virtual switch model would extend  NetBox's functionality beyond just IPs (how do you map physical ports, virtual ports, bare metals, and everything else to a V-Switch
- This new feature set would need to be iterated, improved, and patched
- It is possible the current contributors have a ton of v-switch experience and would be able to provide the best insight into this model.

Given all the above, the focus should be to stabilize the current feature set, fix any bugs, and implement the already agreed features.  Adding this one feature can open up the flood gates to more requests like this.  It is purely a time and focus problem.

@sleeplessnight2 it seems a little hypocritical for you to call anyone contributing to this project lazy.  Do you even know how to view the data model?  Have you forked and attempted to PR your changes into the project?
