### ISSUE TITLE
Clarification on devices, device types and how interfaces work

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#28]
I've added a device type for one of my edge routers and added all the line card ports.

When I add the actual device and associate it to the device type I am left needing to define all the ports again.

What is the purpose of populating ports on the device type if I'll need to redefine the ports when creating the device?

I presumed device type was a template such that when associating it to an actual device the interfaces would be there by default?

Thanks =)

**Comment by jeremystretch** [comment]
> I presumed device type was a template such that when associating it to an actual device the interfaces would be there by default?

That is the intended behavior: You define a device type with its console/power ports and interfaces, and each instantiation of that device type should have those components created automatically.

It seems to be working normally as far as I can tell. Can you walk me through exactly what you did?

**Comment by bellwood** [comment]
@jeremystretch I ended up deleting/recreating and interfaces showed up as intended

Thanks... I'll try to slow down on these... 

Trying to figure out the workflow with mandatory fields, menu positions, etc.

**Comment by jeremystretch** [comment]
No worries, thanks for all the feedback!
