### ISSUE TITLE
Editing a device type with populated device bays throws error

### ISSUE THREAD

**Issue by chonty** [digitalocean/netbox#280]
1. create device type and put something in the device bay field
2. Click 'Edit this device type'
2. Edit device type and click 'Update'.  Get this error:
`Must delete all device bay templates associated with this device before declassifying it as a parent device.`   no parent/child stuff defined

You need to clear the device bay area before you can edit it.  This does not affect devices created using the template.

**Comment by jeremystretch** [comment]
I feel like the error message is pretty clear. Only a parent device type can have device bays. If you want to change a parent to child or neither, you need to delete its device bays first. What are you asking to change?

**Comment by chonty** [comment]
Ah.  Maybe the 'Parent/child status' field should automatically change to Parent upon addition of a device bay then.  The problem I had was that 'Parent/child status' is None by default and trying to rename the device type was giving this error.
