### ISSUE TITLE
Add VXLANs/VNIs to IPAM

### ISSUE THREAD

**Issue by hellerve** [digitalocean/netbox#2800]
### Environment
* Python version:  3.7.2
* NetBox version:  2.4.3

VXLANs are not representable in Netbox. There have been issues opened that talk about adding them (e.g. #1725, #1800), but they’ve either been abandoned or were too general. This issue tries to provide a more focused, pragmatic solution in the hopes that this is generally useful.

Nota bene: if there is sufficient interest, I’d be open to work on this feature myself.

### Proposed Functionality

The IPAM part of Netbox is currently able to handle VLANs and assign them to tenants. Often these VLANs are internally connected via VXLAN IDs (VNI), though, and having them be representable would help giving an overview over which VLANs are connected in such a way.

Concretely, VLANs would be connected to a VXLAN; these new entities have a connection to multiple VLANs and their view would provide an overview of which VLANs are part of them.

### Use Case

A user wants to find out which VLANS are internally connected by a specific VXLAN. They go to the VXLAN view, find the VXLAN they want to examine, and see the VLANs that are potentially tagged with that VXLAN.

Optionally, there could also be a connection to a tenant, though I’m not sure how generalizable this is.

### Database Changes

This change would require a new model in the database, and create/edit/delete views. Ideally they would also be part of the API.

### External Dependencies

Probably none.

Cheers

**Comment by jeremystretch** [comment]
This would amount to a major new feature, and unfortunately we're not currently accepting requests which would extend NetBox's scope (see the [contributing guide](https://github.com/digitalocean/netbox/blob/develop/CONTRIBUTING.md)). It's a topic we'll almost certainly revisit at some point in the future once the current backlog of feature requests has been addressed.

**Comment by hellerve** [comment]
Fair enough. I was aware of the contributing guide, but apparently didn’t read the second part of the sentence.

Out of necessity, I will work on this feature in a fork of Netbox. Should you ever revisit this, feel free to notify me and we can talk about getting this back into mainline!

**Comment by sipstar** [comment]
Oh no, this is sad news. Was looking to map VLAN to VNI ID's. I will use the description field for now. Fingers crossed it may be added one day.
