### ISSUE TITLE
Can't import cables - Cable has no termination_a_type

### ISSUE THREAD

**Issue by 4fd81048a9cd8a3fd43f1f4e52f84181** [digitalocean/netbox#2801]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.0

### Steps to Reproduce
1. Import a cable between two rear ports

Example Data
```
side_a_device,side_a_type,side_a_name,side_b_device,side_b_type,side_b_name
Panel R1A,Rear port,R1-2,Panel R9A,Rear port,R1-2
```

Import the cable.

```
<class 'dcim.models.Cable.termination_a_type.RelatedObjectDoesNotExist'>

Cable has no termination_a_type.
```

**Comment by jeremystretch** [comment]
> NetBox version: 2.5.0

The current release is v2.5.3. Please upgrade, as it's likely this has already been fixed. Please ask to re-open if you can reproduce the issue on the current release.
