### ISSUE TITLE
Make VRF RD nullable

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#2805]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.3

### Proposed Functionality

Make the RD field of VRF nullable.

A VRF is essentially a namespace for IP addressing.  There are plenty of use cases where you want VRFs but you are not interested in RDs.

The current config requires you to allocate fake RDs, which is a bit pointless.

(Supercedes #2804)

**Comment by Mabuchin** [comment]
Thank you for creating Issue!
