### ISSUE TITLE
Enhancement and rework "ADD-Device"

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#2806]
### Environment
* Python version: 3.6
* NetBox version: 2.5.2

### Proposed Functionality
In connection with the work on the html5 Rackview https://github.com/digitalocean/netbox/issues/2248 the adding of devices should be simplified.

There should be a general button to add a device and not single links within the rack.

### Use Case
![image](https://user-images.githubusercontent.com/932481/51606387-15600f00-1f12-11e9-9308-cfb3a2cd9395.png)

Since in the future SVG view possibly the individual links per empty device 1HU will be omitted, this type should be revised foresightedly.
For this there should be a general "Add Device" button in the rack view.
Maybe For this the idea of https://github.com/digitalocean/netbox/issues/1830#issuecomment-453016039 could also be included too.?

### Database Changes
No

### External Dependencies
No

**Comment by jeremystretch** [comment]
> Since in the future SVG view possibly the individual links per empty device 1HU will be omitted, this type should be revised foresightedly.

The individual rack units within an SVG rendering will still be linked. No need for yet another button.
