### ISSUE TITLE
Prefix table within VRF detail page not limited

### ISSUE THREAD

**Issue by synackray** [digitalocean/netbox#2809]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.3

### Steps to Reproduce
1. Create a VRF, VRF1
2. Create more than 1,000 prefixes and assign them to VRF1
3. Navigate to IPAM > VRFs > VRF1. The page will either load with every prefix loaded into the prefix table, or the page will generate a "504 gateway error". I modified the timeout values of gunicorn and nginx to see what generated the 504. 

I expected the VRF details page to load with a sample of the prefixes (say 50) and offer navigation to see additional prefixes. This would mirror the table design of the IPAM > IP Addresses page.

The page failed to load after 60 seconds and generated a 504. This triggered with 11,598 prefixes generated. By modifying the timeout values I was able to see the page load all prefixes under the prefix table,

**Comment by synackray** [comment]
Thank you very much for your time reviewing this issue. NetBox is a wonderful platform and it's clear how much effort has gone into it. Please let me know if I can answer any specific questions regarding this issue.

**Comment by jeremystretch** [comment]
I'm not sure it's worth keeping the prefixes list under the VRF. It might be better to remove the list completely and just provide a count of assigned prefixes with a link to the filtered list.

**Comment by DanSheps** [comment]
I honestly did not know there was a prefix list under the VRF.  However, I think it could be useful if it was just an extension of /ipam/prefixes/?vrf= instead
