### ISSUE TITLE
Add description fields to interface connections export

### ISSUE THREAD

**Issue by dberube1** [digitalocean/netbox#2810]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.3

### Proposed Functionality

Include the interface descriptions for both the A-side and B-side interfaces in the exported csv file generated from the interface connections page. Currently when you export the interface list to csv the descriptions are omitted. 

I know this was originally blocked in request #614, but I feel with the added virtualization features that it would be useful to include this data on the export. 

### Use Case
This would be useful when giving the exported file to anyone that is having to physically work on the equipment, such as cabinet migrations, or server/switch replacement. I use the interface description heavily to document individual network interface name to the PCI slot/port on servers in my environment. 

Example: in a VMware environment the physical adapters are named vmnic[0-14]. The interface name vmnic4 is not useable for tracing the physical port on the back of the server. In this case I've used the  description field to indicate the following information on servers: "Card type: PCI Slot # / Port #". 

### Database Changes
No database changes required.

### External Dependencies
No external dependencies are required.

**Comment by jeremystretch** [comment]
Accepting this enhancement to maintain parity with the built-in list since custom export templates aren't supported for connection lists.
