### ISSUE TITLE
Poduct Enhancement Request

### ISSUE THREAD

**Issue by jimbod777** [digitalocean/netbox#2812]
I am new to using Netbox and I love this product!!  It would be nice to see in the 'STATUS' in IP Addresses to have an option to select Not Used.  Take for example I have a subnet, 192.168.1.0/30.  Of course the first available IP address would be 192.168.1.1 up to 192.168.1.2.  Those are your available IPs you have in this subnet.  The 192.168.1.0 would be your network and 192.168.1.3 would be your broadcast, which are both un-usable.  It would be nice to have this option available, or at least have Netbox Identify when you are using a Network and Broadcast address and have those tagged automatically as unavailable or Not Used.

**Comment by tb-killa** [comment]
Please edit your Issue with using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose).
I like your Idea but you have to use one of the templates (Yours would be the "Feature Request") otherwise this issue will be closed.

**Comment by jimbod777** [comment]
###Environment
*Python version: 3.6
*NetBox version: 2.5.3

###Proposed Functionality
Feature Request.
In IP Addresses have the ability to choose Not Used or auto tag Network and Broadcast Address as Not Used.

###Use Case
It would be nice to see in the 'STATUS' in IP Addresses to have an option to select Not Used. Take for example I have a subnet, 192.168.1.0/30. Of course the first available IP address would be 192.168.1.1 up to 192.168.1.2. Those are your available IPs you have in this subnet. The 192.168.1.0 would be your network and 192.168.1.3 would be your broadcast, which are both un-usable. It would be nice to have this option available, or at least have Netbox Identify when you are using a Network and Broadcast address and have those tagged automatically as unavailable or Not Used.

###Database Changes
Yes

###External Dependencies
No

**Comment by jeremystretch** [comment]
If an IP address is unused, it should not be created in NetBox. Please post to the mailing list if you'd like further clarification on the object's intended use.
