### ISSUE TITLE
Add tenant group filter to sites list

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#2813]
### Environment
* Python version: 3.6
* NetBox version: 2.5.2

### Proposed Functionality
On the acutally Views (list see below) you could only show "Tenant".
The "Tenant-Groups" doesn´t show up.

Extend the following Views with "Tenant-Groups" and include also the "Tenant-Group" Search on the right Side of every selected View-Template.
In the Table View you should see the Tenant-Group Member by show a Hover-Popup if you move the mouse on the Name of the Tenant-Group inside the "Table-View".

dcim/sites/
dcim/racks/
dcim/rack-elevations/
dcim/rack-reservations/
dcim/devices/
ipam/ip-addresses/
ipam/prefixes/
ipam/vrfs/
ipam/vlans/
virtualization/virtual-machines/
circuits/circuits/

### Use Case
If you use different Tenant-Groups because actually you could only select ONE Tenant you wouldn´t see them in the actually views.

For example on Sites it should also show up like this:
![image](https://user-images.githubusercontent.com/932481/51827001-aeaf6c80-22e8-11e9-8e7e-fb939fc27abf.png)

and on the Search-Bar (right Side):
![image](https://user-images.githubusercontent.com/932481/51827159-fe8e3380-22e8-11e9-8eb7-7c8709ee472a.png)

### Database Changes
Dont know.

### External Dependencies
No.

**Comment by Grokzen** [comment]
@jeremystretch Should tenant-group value be visible in the API call to these endpoint? Basically update the class of `NestedTenantSerializer` to output somethiing like

```
"tenant": {
    "id": 314,
    "url": "http://localhost:32770/api/tenancy/tenants/314/",
    "name": "Tenant A",
    "slug": "tenant-a",
    "group": "Customers"
},
```

**Comment by Grokzen** [comment]
Another question i have is that adding more columns always takes up a lot of screen width in the table. Would it be better to mangle both the name and the group into the already existing table Tenant by formatting it something like `Tenant A -- Customers` or `Tenant A (Customers)` or any other variant that would look good.
