### ISSUE TITLE
Extend Rack-Group Listing on Rack-View

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#2814]
### Environment
* Python version: 3.6
* NetBox version: 2.5.2

### Proposed Functionality
Extend the distinguish Rack-Group List Name with the SiteName on 

dcim/racks/ 
dcim/rack-elevations/

for the Search-Box (Right Sidebar)

### Use Case
If you build the same Rack-Group-Names per Site and want to Filter by the dcim/racks/ Site on the Right Side (Search-Bar) you see the Names of the Rack-Groups duplicated which is correct, since each site has the rack group name of the same name. With this Extension you could see the Parent-Side-Name of your assigned Rack-Group.

![image](https://user-images.githubusercontent.com/932481/51827816-832d8180-22ea-11e9-98fe-a256666eb487.png)

### Database Changes
No. 

### External Dependencies
No.

**Comment by jeremystretch** [comment]
Rack group is already available as a separate filter field. If selected, the rack field will be limited to racks assigned to the selected group.

**Comment by tb-killa** [comment]
This feature request is for build Distinguishable name inside the filter field.
Its not that I want to build something new. 
Sry if my request isn't clear understanding.
