### ISSUE TITLE
Allow Tenant to be in multiple Tenant-Groups

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#2815]
### Environment
* Python version: 3.6
* NetBox version: 2.5.2

### Proposed Functionality
Allow Tenant to be in multiple Tenant-Groups.
Actually if you select a Tenant to one Tenant-Group you couldn´t allow the to be in another Group too.

### Use Case
If you have multiple Tenant wo you would assign for Documentation into Groups you could only allow the to one Tenant-Group. If you have multiple customers who you would documentate withing different Groups it wouldn´t work actually.
Maybe with the new "select2" we could bring in some Sort of Multi-Select-Boxes like with Tags.

### Database Changes
Yes

### External Dependencies
No

**Comment by jeremystretch** [comment]
I have to reject this as it would upset a long-established relational model. Groups are intended to serve as organizational units for tenants, not classifications. I'd recommend using tags for the later.

**Comment by tb-killa** [comment]
@jeremystretch:
First of all many thanks for your feedback.
It's a pity that we don't go into it further here.

For your understanding:
There are Tenant and Tenant-Group.
A Tenant may be entered e.g. Pro Site.
A tenant group may also be entered e.g. Pro Site.

A tenant may only be the only one in a tenant group, whereby the name associates tenant group, here are several, therefore also group.

If I follow your logic, then a tenant group is currently no different than another name by a container for a tenant.

So the tenant group is superfluous for me and should not be listed in this form in the software.

Also interesting is the kind of documentation of Netbox itself:
https://netbox.readthedocs.io/en/stable/core-functionality/tenancy/

tenant groups
Tenants can be organized by custom groups. For instance, you might create one group called "Customers" and one called "Acquisitions." The assignment of tenants to groups is optional.

Important here is the last sentence .. tenants is plural.

I see here already in the future the possibility of wanting to add several tenants in a group, because the documentation (see quote above) makes it seem so for an outsider.

Please reopen the ticket again, maybe this feature request can be implemented in the future.
