### ISSUE TITLE
Allow System and Motherboard Serial Number for Devices

### ISSUE THREAD

**Issue by a31amit** [digitalocean/netbox#2820]
### Environment
* Python version:  3.7
* NetBox version:  2.5.3

### Proposed Functionality

Currently, Netbox Have a Single Serial Number which has a description as "Chassis Serial Number". For servers which are Commodity Hardware vendors such as Supermicro, There is not a real way to know this because they either don't update these values or update with useless values Neither it is consistent. 

We have lots of Commodity Hardware & Custom Assembled where we are tracking them based on Motherboard Serial Numbers, System Serial numbers, Chassis Numbers, So either all 3 or partial information help us to uniquely found the server. Also in Blade Servers for they have Same Chassis / System Numbers for all of the blade, So Only things left is Motherboard Serial number. 

So it would great if Netbox allows all 3 serial number field natively in devices. While this can be added to the custom field but I see its make more sense in devices 

- It will allow lookup servers based on all serial numbers as we could have either all / partial / one
- Because we needed this for all devices, Custom fields will add up to extra queries and native support could be better for it.

### Use Case

To see Serial numbers for Motherboard, System, Chassis all together 

### Database Changes
Yes, New fields required. However seems to easy to implement.

### External Dependencies
None

**Comment by jeremystretch** [comment]
The serial number field is to hold whatever you designate as the system serial number of a device. This is the one typically used e.g. for warranty purposes. Individual components should be tracked as inventory items, each of which can be assigned its own serial number. Please post to the mailing list if you'd like further assistance with this approach.

**Comment by a31amit** [comment]
@jeremystretch  I guess Custom Fields are better choices for our case. but Can you please reconsider to change Description for Serial Number From "Chassis Serial Number" To just "Serial Number". Something more generic name would be helpful for WebUI User to not to confuse.
