### ISSUE TITLE
Request: add other non-Anycast/Loopback types to IP address records

### ISSUE THREAD

**Issue by unquietwiki** [digitalocean/netbox#2823]
### Environment
* Python version:  3.6.x
* NetBox version:  2.5.x

### Proposed Functionality & Use Case

Edit [constants.py](https://github.com/digitalocean/netbox/blob/develop/netbox/ipam/constants.py) to support **Unicast, Broadcast, Multicast, and Geocast**; for additional IP documentation. Most virtual machines & servers utilize **Unicast**; IPv6 makes heavy use of **Multicast** (indicating subnets on router & VPN devices could use this); and the other types may also be worth documenting in certain environments. https://en.wikipedia.org/wiki/Anycast has examples of these types, compared against the existing **Anycast** entry in Netbox.

### Database Changes

https://github.com/digitalocean/netbox/tree/develop/netbox/ipam/migrations would need an extra script. Constant numbers **31-34 after Anycast 30** may be a good fit.

### External Dependencies

None required

**Comment by jeremystretch** [comment]
Unicast is the default state. Broadcast and multicast IPs are qualified by their address and mask; neither is a state which can be designated arbitrarily. "Geocast" isn't a thing as far as I can tell, but it's presumably used to describe anycast rouitng.
