### ISSUE TITLE
Racks > Elevations

### ISSUE THREAD

**Issue by robbagithub** [digitalocean/netbox#2824]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.4

### Steps to Reproduce
1. Navigate to the rack elevations list (Racks > Elevations)

### Expected Behavior
A list of all rack elevations should be displayed.

### Observed Behavior
An exception is raised:

```
<class 'django.template.exceptions.TemplateDoesNotExist'>

dcim/inc/filter_rack_group.html
```

**Comment by GitRost** [comment]
Same problem, updated from 2.5.3 to 2.5.4

**Comment by jeremystretch** [comment]
I'll try to get a new release pushed out shortly to fix this. As an interim workaround, you can create an empty file at `netbox/templates/dcim/inc/filter_rack_group.html` to suppress the exception.
