### ISSUE TITLE
Include directly connected device for front/rear ports

### ISSUE THREAD

**Issue by tvberlin** [digitalocean/netbox#2825]
### Environment

* Python version:  3.5.3
* NetBox version:  2.5.4

### Proposed Functionality

We highly appreciate the introduction of the cables/traces feature. But since we migrated all our panels from "interfaces" to front/rear ports my team complained about limited visibility about the connected devices/ports. You have to click on each cable in order to show the connected device.

Would it be possible to add the connected device/port in two columns behind "Connected Cable"?

Furthermore, showing the cable trace is only possible from the device view, not from the connected circuit. Would it be possible to add a "trace" button in the circuit view?

### Use Case

Missing overview / details when viewing a patchpanel.

### Database Changes

None.

### External Dependencies

None.

**Comment by tb-killa** [comment]
Hi @tvberlin .. i think your request could be some Sort of Duplication from: https://github.com/digitalocean/netbox/issues/2758
Please check and commit with thumbs up on the other Issue.

**Comment by tvberlin** [comment]
@tb-killa Thanks. Yeah, I guess the trace-issue is duplicated by #2758. But the additional device/port information in the patchpanel front/rear port view, w/o viewing the trace, comes extra.

**Comment by jeremystretch** [comment]
This request is to list the device and interface/port/etc. on the other end of the cable, correct? That's different from #2758, which entails adding the ability to trace to the end of the cable path from a patch panel.

**Comment by tvberlin** [comment]
@jeremystretch thanks for implementing. Now the front/rear ports shows Termination B of the cable. Which is the patchpanel/port itself. Would it be possible to always show the distant device/circuit the port connects to? From my point of view thats the important information when viewing patchpanels.

**Comment by jeremystretch** [comment]
Thanks, I've opened #2844 to address this.
