### ISSUE TITLE
Circuit selection from a patchpanel not working 

### ISSUE THREAD

**Issue by lcioltan** [digitalocean/netbox#2826]
### Environment
* Python version:  Python 3.5.3
* NetBox version:  Netbox 2.5.4

### Steps to Reproduce
1. Use a version of a patchpanel with interfaces (let us name it "Patchpanel-A").
2. The rear port (Port-1) is connected to a distant patchpanel ("Patchpanel-B") via a carrier circuit ("Carrier-1"). The "Carrier-1" circuit has been defined in Netbox and it's listed under Circuits.
3. On the "Patchpanel-A" overview, under column "Connection", the distant "Patchpanel-B" is outputted and below it, with small letters, this circuit that connects the two panels (via "Carrier-1").
4. When you click on the circuit "Carrier-1", instead of being redirected to the circuit details,
you land once again on the "Patchpanel-A"

Note: the problem doesn't appear with the front/rear ports patchpanels.

### Expected Behavior
I expect to be redirected to the "Carrier-1" circuit.

### Observed Behavior
I land on the exact same patchpanel (acts as a "refresh")

**Comment by lcioltan** [comment]
Hi Jeremy, 

I meant the patchpanel with interfaces (not with front/rear ports).

**Comment by jeremystretch** [comment]
Please edit your issue to include the exact steps that someone else can take to recreate the issue you're describing.

**Comment by lcioltan** [comment]
I just update the description (Steps to reproduce).

**Comment by lcioltan** [comment]
![circuit selection from a patchpanel not working](https://user-images.githubusercontent.com/47182087/52486679-09d04180-2bbc-11e9-9b46-c40e92dd7e1d.png)

**Comment by lcioltan** [comment]
Hi Jeremy, 

I've attached a picture to better highlight the issue. If you need extra information, just let me know.

**Comment by jeremystretch** [comment]
I believe this was addressed under #2844 and will be fixed in v2.5.6. If you still have the issue on the new release, please ask for this to be reopened.

**Comment by lcioltan** [comment]
Hi Jeremy, 

the issue persist after the v2.5.6 release. Can we re-open this ticket or should I create a new one? 

Kind regards,
Lucian

**Comment by tvberlin** [comment]
@jeremystretch this is duplicated (and fixed now in 2.5.7) by #2914 and can now be closed, thanks.
@lcioltan FYI
