### ISSUE TITLE
Add tests to check all views

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#2827]
### Proposed Changes
We should add a set of tests under each app to check that each view renders successfully. Nothing too involved, just a normal GET request, maybe invoking a filter where applicable.

### Justification
This should be pretty simple to do, and would catch bugs like #2824.

**Comment by candlerb** [comment]
Ideally it would also click on all active elements in the page, like column sort headers.  This would have caught #2901.

**Comment by jeremystretch** [comment]
I've started work on this in the [2827-view-tests](https://github.com/digitalocean/netbox/tree/2827-view-tests) branch.
