### ISSUE TITLE
Allow create MLAG across multiple switches

### ISSUE THREAD

**Issue by s-fu** [digitalocean/netbox#2830]
### Environment
* Python version:   3.6.7
* NetBox version:   4.0.5

### Proposed Functionality
Allow multiple switches sharing a Multi-Chassis Link Aggregation (MLAG). 

There should be a function allowing multiple independent switches have a shared MLAG. Currently only LAG is available, which allows the the bonding of multiple ports on one switch.

The switches sharing the MLAG are independent (not belong to a virtual chassis). They will have the port like 0/[1-24] on all switches instead of [0-1]/[0-24] in a stack

### Use Case
Almost all the vendors have their own proprietary MC-LAG [implementations](https://en.wikipedia.org/wiki/MC-LAG#Vendor_Implementations). The use case is usually like this:

```
                  |-----------------|                     |-----------------|
                  |     coresw1     |=====================|     coresw2     |
                  |                 |                     |                 | 
                  -------------------                     -------------------
                                \                              /
                                 \                            /
                                  \                          /
                                  |---------------------------|
                                  |        access switch      |
                                  |---------------------------|
```
The bond between core switches is LAG, e.g LACP.
The connection from access switch to both core switches shares the same MLAG number.

You can't have the LAG shared by two switches now, unless using virtual chassis. However, it causes inconsistency of port number.

**Comment by jeremystretch** [comment]
To model multichassis LAG, you'll need to create the LAG interface with the same name/ID on both switches. There isn't really anything else for NetBox to model: The multichassis functionality is accomplished by proprietary hacks performed on the forwarding plane, which vary in their implementation among platforms and are out of scope for NetBox.
