### ISSUE TITLE
Select2 not filtering certain fields

### ISSUE THREAD

**Issue by DanSheps** [digitalocean/netbox#2835]
### Environment
* Python version:  3.6
* NetBox version:  2.5.4
* Browser version: Chrome 71.0.3578.98

### Steps to Reproduce
1. Go to /dcim/devices
2. Start attempting to filter "Device Roles"

### Expected Behavior

The list of available roles will be filtered based on what is input into the filter box

### Observed Behavior

The list of roles stays consistent, does not filter based on what is typed

### Affected Endpoints

* Device Role
* Device Type
* Manufacturer
* Tenant Group
* Rack Position
* VLAN Group
* RIR (Add Aggregate)
* VM Cluster Group
* VM Cluster Type
* Circuit Type
* Secret Role
* Rack Role
* Front Ports
* Rear Ports

**Comment by DanSheps** [comment]
Per @lampwins:

> Looks to be a filter problem, not select2. Hitting the API directly has the same result.

**Comment by lampwins** [comment]
Turns out several model filter classes are missing the search method (`q` param).
