### ISSUE TITLE
Add support for spliced pigtails / punched cable to rear ports

### ISSUE THREAD

**Issue by ktims** [digitalocean/netbox#2839]
### Environment
* Python version: 3.6.3
* NetBox version:  2.5.5

### Proposed Functionality

Add support for patch panels that do not use connectors on the rear side.

### Use Case

It is common for both fibre and copper patch panels to be 'hard wired' to another 'rear port' on another panel. Presently the model both enforces a connector on the rear port, and doesn't provide an appropriate connector type to model this.

### Database Changes

I'm not sure the best nouns to use, but suggest the addition of two connector types to the cabling model, for 'pigtail fibre' and 'punched copper'. Perhaps just making the field nullable satisfies this, too, if connections to 'null' connectors are allowed. It should also be allowed to connector either of these types on one end to a connectorized panel on the other end.

**Comment by DanSheps** [comment]
'punched copper' is still 8P8C
'pigtail fibre' is going to break out into individual strands (I always do color coded strands anyways, I never use the "position" for fiber)

**Comment by ktims** [comment]
> Don't want to argue with you, but there is a 8P8C connector somewhere right? Just because the connector is on the front and you are punching down to the back doesn't make it any less of a 8P8C connector.

The way Netbox models patch panels, there are two connectors for each circuit. One on the front, one on the rear. There is no physical connector on the rear (unless you count the IDC punch block as a connector... in which case it should appear in the list of options), therefore it doesn't make sense for the model to require one, which is the present state. Obviously the front port is 8P8C.

> (I am assuming you actually mean MPO/MPT fan-out or MPO/MPT to LC/SC cassettes)

I don't know why you would assume such when I have clearly stated that's *not* what I'm talking about... this case is clearly supported. Let me reiterate the request is to add support for *spliced pigtails*.

> The other "other good point", I simply put a "Simplex/Duplex" converter object on my switches/interface modules and label them "Upstream/Downstream" (For example, TenGigabitEthernet1/1/1.Upstream and TenGigabitEthernet1/1/1.Downstream" and link the single interface to the LC connector with a "zero length" cable.

This is a clumsy workaround. Better support would be appreciated.

**Comment by DanSheps** [comment]
> I don't know why you would assume such when I have clearly stated that's not what I'm talking about... this case is clearly supported. Let me reiterate the request is to add support for spliced pigtails.

You don't need a new connector for spliced pigtails, as they will still either have a ST/SC/LC/etc connector.

**Comment by ktims** [comment]
Mea culpa. @DanSheps is right, I'd never actually closely examining the splice trays, but of course the pigtails terminate in connectors, for some reason I thought they were spliced directly to the bulkhead connectors. Sorry guys.

> You can model duplex and simplex links on the same device. For example, we have fiber ports named 1/2 and 3/4 for duplex links (two strands per port), and 5 and 6 for simplex links.

Hmm, I guess this works. It does tie the logical 'connection' a little closely to the physical plant for my liking (the modelling of the connectors / cables depends on what type of connection they are used for, not how the cable is built), but it's a decent compromise.

**Comment by jbakklund** [comment]
Here is an example showing a patch panel delivered with factory mounted pigtails prepared for splicing incoming cable. This panel has 48 mounted LC/APC pigtails for single mode.
![panel75-lc-apc-pigtail-03](https://user-images.githubusercontent.com/33431806/52814863-77d5a680-309d-11e9-8118-66f043f9200e.jpg)
I have one such panel where port 1-24 is spliced to a 24-strand single mode multi-cable in one direction, and port 25-48 spliced to another 24-strand multi-cable running in opposite direction. NetBox 2.5.5 allowed me to modell two rear ports, named "1-24" and "25-48", both as type "LC" with 24 positions each, where position 25-48 at the near end, ended in port 1-24 in the far end. Tracing a connection all the way from one switch, via port 29 at the near end, via the fifth component in the multi-cable, out via port 5 in the far end, and into the far end switch - worked just fine, but NetBox 2.5.6 breaked it.

**Comment by DanSheps** [comment]
@jbakklund what is the model of that cassette?
