### ISSUE TITLE
Key Error when adding Front Panel Ports

### ISSUE THREAD

**Issue by gavmckee80** [digitalocean/netbox#2843]
### Environment
* NetBox version:  v2.5.4

![image](https://user-images.githubusercontent.com/17826993/52125903-80d16d00-25f3-11e9-934d-96a39fb3c0ad.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/17826993/52125986-afe7de80-25f3-11e9-979b-32cf447c8ebe.png)

### Expected Behavior

Key Error thrown

**Comment by jeremystretch** [comment]
Duplicate of #2833, fixed in v2.5.5
