### ISSUE TITLE
Front/reat port connection always shows B side of connected cable

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#2844]
### Environment
* Python version: 3.5.2
* NetBox version: 2.5.5

### Steps to Reproduce
1. Create or find a front or rear pass-through port with a connected cable.

### Expected Behavior
The "front ports" and "rear ports" tables on the device view should list the far end of each attached cable.

### Observed Behavior
The B side is always listed. This is due to a bug in the `get_cable_peer()` method:

```
def get_cable_peer(self):
    if self.cable is None:
        return None
    if self._cabled_as_a:
        return self.cable.termination_b
    if self._cabled_as_b:
        return self.cable.termination_a
```

The `_cabled_as_x` methods each return a generic relation manager, whereas what we need is the queryset.

**Comment by tvberlin** [comment]
@jeremystretch thanks for implementing!
