### ISSUE TITLE
Search queries do not filter results in the manufacturer field when adding a device into dcim/devices

### ISSUE THREAD

**Issue by superthing** [digitalocean/netbox#2847]
### Environment
* Python version:  Python 3.5.2
* NetBox version:  2.5.4

### Steps to Reproduce
1. Add a new device
2. Select Manufacturer
3. Insert search query into Manufacturer field

### Expected Behavior
The search results are supposed to be filtered by the search term.

### Observed Behavior
The results are not filtered by the search term and the entire list is displayed.

**Comment by superthing** [comment]
Here's a screenshot to illustrate the issue
![devices don t filter in netbox add devices](https://user-images.githubusercontent.com/4330944/52156867-d29fe480-263f-11e9-8c45-afee0642f97f.png)

**Comment by lampwins** [comment]
This has been fixed in v2.5.5. Please upgrade to the latest version.
