### ISSUE TITLE
Finding devices in Racks which are "Non-Racked" (no position)

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#2852]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.5

### Proposed Functionality

I would like to be able to identify all devices in a site which are in racks but are "non-racked" - i.e. they have been assigned to a rack but have no rack position recorded.  Examples would be devices on shelves.

Currently the the way I am doing this is to browse to the detail page for each rack in turn, and look at the the list of non-racked devices down the page.  This is tedious across many racks.

I have thought of some possible approaches:

* A new search filter, e.g. `/dcim/devices/?position=null`.  This would make the search column even busier than it already is.
* In the Devices list, change the "rack" column to show "rack and position": e.g. instead of "407" show "407 U34 F", but non-racked devices would show as just "407".  Then if you sort on this column, you'd see all the devices grouped by rack, and the non-racked ones grouped together too
* In the Rack Elevations view, show a list of the non-racked devices underneath each rack

### Use Case

* Rack Elevations are a handy visual guide to the equipment in each rack, but are missing information about non-racked equipment within each rack, so don't provide a complete list of all the devices
* Quick data quality check - identify devices which should have been given a position

### Database Changes

None

### External Dependencies

None

**Comment by hSaria** [comment]
@candlerb, `/dcim/devices/?rack_id=null` already does that. If you're using the selector on the right side of the page, then search for None.

**Comment by candlerb** [comment]
I'm not looking for `rack_id=null`.  I want to search for devices which have been assigned a rack, but not a *position* within the rack.

These are the ones listed as "Non-Racked Devices" on the detail page for a given rack `/dcim/racks/<id>/`

**Comment by jeremystretch** [comment]
There seems to be a limitation in django_filters where it won't allow a null value for a NumberFilter. Not sure how best to get around that.

**Comment by candlerb** [comment]
This now works if I manually construct a URL like `/dcim/devices/?site=<name>&position=null` to find these devices in a site.  But there doesn't seem to be a way to do this via the UI in the Search box. (Netbox 2.5.9)
