### ISSUE TITLE
Bulk edit front/rear descriptions

### ISSUE THREAD

**Issue by deku-m** [digitalocean/netbox#2854]
### Environment
* Python version:  3.5.2 
* NetBox version:  2.5.5 

### Proposed Functionality
We want to add descriptions after all the front or rear ports but its mostly the same for example on 10 ports you need to be added the same description. Now you need to do this port by port (rule by rule). So if it is possible to edit the selected ports and add the same description to all 10 ports at the same time.

### Use Case
Same as above. Select multiple ports from front or rear and add same description to all selected ones.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by tb-killa** [comment]
How about create new Button below the Table of the Connections with new Button (Bulk-Actions) who only active if more then two Rows a selected with the select-boxes on the Table-Front (nomaly the button is disabled).
![image](https://user-images.githubusercontent.com/932481/52397011-2aad6f80-2ab4-11e9-92e6-cac27368d5a7.png)
From there you could click on this button and get new page (redirect) called bulk-actions who you could do multiple things like "bulk-edit" -discriptions or -connections or something else if we wish more bulk-stuff.
This could close #2855 too ?
