### ISSUE TITLE
Option to select ip directly from prefix/vlan for management primary ip

### ISSUE THREAD

**Issue by deku-m** [digitalocean/netbox#2858]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.5

### Proposed Functionality
In our environment we configure on the switch the vlan interface with a IP address. This is then reachable as management. So if it is possible, that we directly select the IP address when editing the switch for its primary ip and then the option to select the ip from the prefix/vlan. As now you first need to configure an interface with an IP address. So we now configure them on the port channel.

### Use Case
As above

### Database Changes
Don't know what has to change

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
I don't follow what's being proposed here. Could you elaborate on exactly what you're trying to do please?

**Comment by deku-m** [comment]
To clearify a bit hope this helps:
When you edit a device you can assign a ip address under the section management as primary/secondary IP. This is only allowed when you assign this to an interface for example a portchannel, etc.  Then you can select this address at the primary ip.

What im trying to explain is, if it is possible to assign it directly when you enter or select the ip address as primary IP. So that it doesn't have to be assigned to a interface. Just directly select from the ip addresses. As in our environment we didn`t assign it to the a physical interface but assigned it to a vlan interface (management).

**Comment by DanSheps** [comment]
@deku-m 

If this is what you are talking about, this is a support question and should be redirected to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) or the [NetworkToCode Slack](https://networktocode.slack.com/) in the #netbox channel

You would want to model that in Netbox, by naming it whatever it is named in your switch.  For example, on Cisco switches, you would have the following configuration:

```
interface Vlan1212
 ip address 10.12.12.1 255.255.255.0
```

You would model this in Netbox by creating a interface named Vlan1212 and assigning it the IP address 10.12.12.1/24.  The type would be "Virtual".

**Comment by jeremystretch** [comment]
As @DanSheps points out, IP addresses must be assigned to an interface before they can be designated as the primary IP for a device. There is no mechanism by which to create _and_ designate an IP in one action, as that would greatly complicate validation.
