### ISSUE TITLE
Power port to Power outlet connection

### ISSUE THREAD

**Issue by andre-lx** [digitalocean/netbox#2859]
### Environment
* Python version:  3.6.8 
* NetBox version:  2.5.5

Hi. When I try the connection between a power port and a power outlet, netbox returns an error.

### Steps to Reproduce
1. create a power port in a device
2. create a power outlet in a pdu
3. try to do a connection

### Expected Behavior
Cable connection created.

### Observed Behavior
If I didn't specify a length:

IntegrityError at /dcim/power-ports/59/connect/
null value in column "length_unit" violates not-null constraint
DETAIL:  Failing row contains (11, 2019-02-06, 2019-02-06 11:06:36.054882+00, 59, 1, 5000, t, , , null, null, null, 27, 25).

If I specify a length:

DataError at /dcim/power-ports/59/connect/
value too long for type character varying(2)

**Comment by jeremystretch** [comment]
I'm not able to replicate this on v2.5.5. Looks related to #2616, which was raised during the v2.5 beta. Did you try upgrading from a beta to the current release? This would result in missing migrations.

**Comment by jbakklund** [comment]
I'm not able to replicate this either.
