### ISSUE TITLE
Text colour in rack elevations not dependent on background

### ISSUE THREAD

**Issue by ktims** [digitalocean/netbox#2861]
### Environment
* Python version:  3.6.3
* NetBox version:  2.5.5

### Steps to Reproduce
1. Create a Device Role with a light colour (e.g. White or Yellow)
2. Create a device of this Role and rack it
3. View the rack elevation

### Expected Behavior
Text labels on devices in the rack elevation are legible; ie. their colour (black/white) depends on the device role colour.

### Observed Behavior
In the Device Role list, black text is appropriately used on the light background, while white text is inappropriately used in the rack elevation. The same appropriate text colour selected in the Device Roles view should be used in rack elevations. On white Device Roles the text is totally illegible unless hovered, while on other colours it is merely somewhat illegible.

**Comment by jeremystretch** [comment]
No new work is being done on the current rack elevation rendering logic. Please add this as desired behavior under #2248.
