### ISSUE TITLE
When adding cable, direct back to original device

### ISSUE THREAD

**Issue by mgob** [digitalocean/netbox#2862]
### Environment
* Python version:  3.5.1
* NetBox version:  2.5.5

### Proposed Functionality
When adding a new cable, you are directed to the cable/cables section and not back to the original device you were adding the cable connection to.  We would like to request an enhancement to direct back to the A-side or, the previously viewed device once the connection is made instead of directing to the cable(s) section.  

### Use Case
The user finds themselves having to make a few clicks to get back to the device they were working on which if you're adding a bunch of connections becomes very time consuming.

**Comment by jeremystretch** [comment]
This is actually a bug; that was the intended behavior.
