### ISSUE TITLE
Date custom field not supporting data format on entry

### ISSUE THREAD

**Issue by robbagithub** [digitalocean/netbox#2863]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.4

### Steps to Reproduce
1. Set date format to desired format in configurations.py (screenshot below).  I've chosen 'j-M-y'. Save file.
2. Add custom field to dcim > device
3. Set type to Date and Create name, description.
4. Leave label, required not checked, filter logic = loose, no default and weight = 100
5. Select a device and enter date into custom field using format that was set int he configurations.py file.
6. Error occurs stating that wrong date format is being used. Only the standard system one can be used successfully, 'Y-m-d' or '2019-Feb-2'

**Changes made to configurations.py file below**

![configurations](https://user-images.githubusercontent.com/22147754/52395988-2610a780-2b04-11e9-90d2-26716748911a.jpg)

**Custom field creation**

![create custom](https://user-images.githubusercontent.com/22147754/52395812-9f5bca80-2b03-11e9-9716-a798bfda5666.jpg)

### Expected Behavior
I expected to be able to enter in the date in the device page in the format that I had specified in the configurations.py file.

### Observed Behavior
The device page would only except field input using the standard format of 'Y-m-d'
![create custom error](https://user-images.githubusercontent.com/22147754/52395854-bc909900-2b03-11e9-87f2-13cef99c22e4.jpg)

**Comment by tb-killa** [comment]
Hi @robbagithub please read this: https://groups.google.com/forum/?nomobile=true#!topic/netbox-discuss/0_LOtVUYtdM
