### ISSUE TITLE
Form factor for coax connectors

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#2865]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.5

### Proposed Functionality

Add form factors for [RF connectors](https://en.wikipedia.org/wiki/List_of_RF_connector_types): either just generic "Coax", or common specific ones like Belling-Lee, BNC, F, N, UHF.

### Use Case

I have a data centre where we have satellite feeds presented on F connectors into multiswitches, and the multiswitches in turn have coax connections to tuner cards dedicated satellite receivers and servers with multi-input PCI tuner cards.  Also DVB-T into tuner cards.

### Database Changes

None.  The form factors are a static list of integers in code.

### External Dependencies

None.

**Comment by pernwall** [comment]
I would also have good use of this, I'm about to implement Netbox for a TV Broadcaster, and we have a lot of video equipment with COAX cables and SDI connections. Would it also be possible to add video (eg. different types of SDI) as an interface form factor? I'm very new to Netbox, therefor I'm not really sure what would be the best way to do it?

**Comment by jeremystretch** [comment]
This sounds out of scope for NetBox. We've made the conscious decision to support only network interfaces to limit scope creep.

**Comment by candlerb** [comment]
> This sounds out of scope for NetBox. We've made the conscious decision to support only network interfaces to limit scope creep.

What about PON interfaces?  Does that count as a "network interface" or not? I need these too.

It seems fairly arbitrary distinction, and it's currently implemented very inconsistently.  Note that:

* Several types of non-IP 'interface' are already included: e.g. stacking cables, fibre channel.  You can't assign an IP address to a stacking cable port.  You can argue whether or not fibre channel is a "network interface", but SAS and SATA cables are functionally very similar.
* A 'frontport' or 'rearport' has a physical interface type (e.g. LC or 8P8C), whereas an 'interface' has a layer 2 type (e.g. 1000baseT) or a modular type (e.g. SFP).  However, you create a cable with SFP at one end and (single) LC at the other.  This is mixing layers: one end is network, the other end is physical.
* Console ports and power ports are not network interfaces

I think it would make more sense to have a single physical "port" with a physical form factor: if it's C13 it's power, if it's LC it's fibre, if it's SFP it takes an SFP module - with an optional IP interface attached.  You could have a checkbox to indicate if the port or connector type is IP-capable (in the same way that certain Device Roles can be marked as usable for Virtual Machines)

The MAC and IP settings could be fields on the port (ignored for non-IP ports), or on a separate interface object linked to a parent port.  Separating them has some advantages:

* an IP interface with no port is a virtual interface
* multiple IP interfaces on one physical port => tagged VLANs
* multiple IP interfaces on one physical port => QSFP
* the IP interface may be known to the OS by a different name than the physical port.  (For example: FreeBSD and various flavours of Linux and FreeBSD name their ethernet ports differently)

But sorry, I digress from the topic of this ticket.

**Comment by jeremystretch** [comment]
All we're talking about in this issue is the proposal to add coaxial connectors. Let me phrase it this way: Are these interfaces being used to send and receive packets of data which are forwarded based on a destination address?

**Comment by candlerb** [comment]
> Are these interfaces being used to send and receive packets of data which are forwarded based on a destination address?

They are being used to carry MP4-encoded digital TV transmissions.  The MP4 frames are multiplexed onto higher bitrate streams and then modulated onto RF carriers.  However there is no "destination address", it's broadcast.

At layer 1, they are also black cables which plug into ports on boxes (hundreds of them).  When somebody asks me "what is plugged into port 4 on box A?" I want to be able to tell them what's on the other end of the cable.

**Comment by tb-killa** [comment]
> Are these interfaces being used to send and receive packets of data which are forwarded based on a destination address?

We use Micro DSLAM Technology where a coaxial cable is used instead of a network cable between Switches or other active network components.
This sort are often used in various hotels.

**Comment by DanSheps** [comment]
Could someone provide a list of form factors

**Comment by candlerb** [comment]
Oooh, there are [loads](https://en.wikipedia.org/wiki/List_of_RF_connector_types) :-)

The ones I deal with regularly:

* *RF connector*
    * Belling-Lee
    * BNC
    * F-type
    * N-type
    * SMA

That plus "Other" would probably cover quite a wide range of uses.  These would also need to be available as Front Ports and Rear Ports as well as Interfaces, to allow for RF patch panels.

I can completely understand the reluctance to add these, given that the logical follow-on is to add [audio connectors](https://en.wikipedia.org/wiki/Audio_and_video_interfaces_and_connectors) (RCA, quarter-inch jack, XLR etc).

Hopefully you can understand why: Netbox *does* make a good match for broadcast suites.  They use almost exclusively the same 19" racks as data centres, and they have patch panels plus a ton of cabling to manage.  It's just that the cabling isn't all ethernet and serial.

I wonder if it's time to reconsider #84 and make the port types customisable?  After all, nobody would expect a hard-coded list of Platforms or Manufacturers.

**Comment by jeremystretch** [comment]
> Hopefully you can understand why: Netbox does make a good match for broadcast suites. They use almost exclusively the same 19" racks as data centres, and they have patch panels plus a ton of cabling to manage. It's just that the cabling isn't all ethernet and serial.

I get that, I do. But this use case unfortunately isn't in scope for NetBox. I've said this before: As an IPAM/DCIM application, NetBox is inherently vulnerable to scope creep, because it's so easy to start tacking on things that are only tangentially related to its core purpose. In order to ensure the long-term maintainability of the product, the DCIM component of NetBox is intentionally limited to modeling network, console, and power objects. Any proposal to add anything even slightly outside this definition must be rejected. Otherwise, the scope of the product stretches that much further, inviting yet more slightly-out-of-scope proposals in a perpetual cycle.

It's clear from the description you provided above that these are not network interfaces, so it would not make sense to model them using an object expressly intended to represent network interfaces.
