### ISSUE TITLE
netbox 2.5.5 "NAPALM is not installed"

### ISSUE THREAD

**Issue by jakegroves** [digitalocean/netbox#2867]
### Environment
* Python version:  3.5.3
* NetBox version:  2.5.5

We upgraded netbox from 2.0.5 (python 2.7) to netbox 2.5.5 (python 3.5), and now we are trying to make use of the napalm integration.
I have the pip package installed, and I can manually run the command on the CLI to get it working. However, when setting the napalm username, password i get the error:
`{
    "detail": "NAPALM is not installed. Please see the documentation for instructions."
}`
I have the platform setup to use the eos napalm provider.
I have also gone into the nbshell and i can import napalm.
Is there a possibility that netbox is trying to use python2.7 when making the napalm request?
### Steps to Reproduce
1. upgrade netbox 2.0.5 to 2.5.5, pip3 install napalm, set credentials, set platform napalm to be eos
2. pip3 install napalm
3. set napalm credentials
4. set napalm platform to be eos provider
5. https://netbox.example.com/api/dcim/devices/4594/napalm/?method=get_facts

### Expected Behavior
Expected to return json of device information.

### Observed Behavior
Napalm is not installed, but verified that it is

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
