### ISSUE TITLE
Change Provider NOC/Admin Fields to GitHub-Flavored Markdown

### ISSUE THREAD

**Issue by hSaria** [digitalocean/netbox#2870]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.5

### Proposed Functionality
In `circuits/providers/`, change the NOC and Admin contact fields to be GitHub-Flavored Markdown fields (similar to the Comments field).

### Use Case
The NOC and Admin fields may contain information related to more than one person/department. For instance, you may have different admin contacts for different roles. Markdown would help structure those two fields.

### Database Changes
None.

### External Dependencies
None.

**Comment by Bill-Irvine** [comment]
I've got a similar feature request that has been accepted. Maybe this will fit your purpose?

https://github.com/digitalocean/netbox/issues/1344

**Comment by hSaria** [comment]
It does fit the purpose, though I'm very sure it requires a bit more effort (new object type, likely to change database structure, etc...). For this request, I simply ask that those two fields are formatted similar to the comments section. This change, as far as I can tell, should be quite simple.

Long term, I'd prefer your approach as it is way more scalable, though it seems the devs are busy with other things, so I tried suggesting a middle-ground solution.
