### ISSUE TITLE
Error when upgrading from 2.5-beta1

### ISSUE THREAD

**Issue by oroomans** [digitalocean/netbox#2871]
### Environment
* Python version: Python 3.6.7 (default, Oct 22 2018, 11:32:17)
* NetBox version:  2.5-beta-1
* Postgresql version : PostgreSQL 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1)

### Steps to Reproduce
1. git checkout master
2. git pull 
3. ./upgrade.sh

### Expected Behavior
Netbox still working after upgrade

An error on the main page appears, stating that a Database error occurred  (see screenshot). 

I tried to manually re-run the django migration script, but it says that everything is up to date

> root@lnx-dcim:/opt/netbox/netbox# python3 manage.py migrate
>Operations to perform:
>  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, taggit, >tenancy, users, virtualization
>Running migrations:
>  No migrations to apply.

![2019-02-11 18_56_28-window](https://user-images.githubusercontent.com/31890378/52583324-9b93b500-2e2f-11e9-959d-7d9778203d9c.png)

**Comment by jeremystretch** [comment]
From the v2.5-beta1 release notes:

> This is a beta release. It is intended solely for gathering community and developer feedback in preparation for the v2.5 release. Do not run it in production, and do not give it write access to your production database. **As the database schema is subject to change during the beta period, a migration path to the stable release likely will not be provided.** Do not commit any data which you are not willing to lose.
