### ISSUE TITLE
Unused status in choice field for ipaddress

### ISSUE THREAD

**Issue by kobayashi** [digitalocean/netbox#2874]
### Environment
* Python version:  
* NetBox version:  
N/A

### Proposed Functionality
I would like to add `IPADDRESS_STATUS_UNUSED` to `IPADDRESS_CHOICES`.

Like followings in ipam/constants.py. 

```
# IP address statuses
IPADDRESS_STATUS_UNUSED = 0    # <- add this line
IPADDRESS_STATUS_ACTIVE = 1
IPADDRESS_STATUS_RESERVED = 2
IPADDRESS_STATUS_DEPRECATED = 3
IPADDRESS_STATUS_DHCP = 5
IPADDRESS_STATUS_CHOICES = (
    (IPADDRESS_STATUS_UNUSED, 'Unused'),  # <- add this line
    (IPADDRESS_STATUS_ACTIVE, 'Active'),
    (IPADDRESS_STATUS_RESERVED, 'Reserved'),
    (IPADDRESS_STATUS_DEPRECATED, 'Deprecated'),
    (IPADDRESS_STATUS_DHCP, 'DHCP')
)
```

Assigned as 0 is easy to set the color as default.

```
# Bootstrap CSS classes
STATUS_CHOICE_CLASSES = {
    0: 'default',
    1: 'primary',
    2: 'info',
    3: 'danger',
    4: 'warning',
    5: 'success',
}
```

### Use Case
In my case, there are several managed ipaddresses which are not active and not reserved for something. `unused` is better choice for these ipaddresses.

### Database Changes
No

### External Dependencies
No

**Comment by jeremystretch** [comment]
The philosophical approach taken by NetBox is that if an IP address is unused, it should not be defined.
