### ISSUE TITLE
Difference in case sensitivity in API vs WebUI for creating new objects

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#2875]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.5

### Steps to Reproduce
1. Create an object in the WebUI with the name being in all uppercase (same `role`, `site`, etc).
2. Attempt to create the same object using the API but with the name being in all lowercase.
3. This fails with the error returned as follows:
```
{"name":["device with this name already exists."]}
```
4. When attempting to create the same device using in all lowercase via the WebUI, it is created just fine.

### Expected Behavior
Be consistent between the API and the WebUI interfaces for device creation.

### Observed Behavior
Different results (case **in**sensitive in the WebUI vs case sensitive in the API)

**Comment by jeremystretch** [comment]
I'm not able to reproduce this: I can create devices named "TEST" and "test" without issues. Please post the *exact* steps you're taking for both the web UI and the API.

Are you sure you're not running into an issue with duplicate slugs?

**Comment by bdlamprecht** [comment]
It could be duplicate values for the `slug`, I'll have to look into that again.Perhaps the issue is in `pynetbox`.  I will verify if the issue exists using `curl` and then

**Comment by bdlamprecht** [comment]
Well, I just spun up a new instance of `v2.5.6` and I can't seem to get the error to happen again.

I'm not sure exactly where this came up, but I'll close this issue as unable to reproduce.
If I find the same scenario pop up again, I'll re-open this and document the _**exact**_ steps that caused the error to occur before I move-on and forget.

My apologies for adding to your high number of newly opened issues. :grimacing: 
I would much rather have the time spent being to implement new features. :100:
