### ISSUE TITLE
Add Tenant/Customer ID Number

### ISSUE THREAD

**Issue by djmelik** [digitalocean/netbox#2876]
I would like to request the following new feature. 

### Environment
* Python version:  3.5.3
* NetBox version:  2.5.5

### Proposed Functionality
1. Add a new UID field to tenants. 

### Use Case
1. A UID field for Tenants will allow for easier integration and interoperability with other third-party (non-Netbox) applications and services ie. ticketing systems, monitoring systems.

For example, all customers in my company have a unique identifier ID number when they are onboarded. A UID will make it easier to export/import relevant information into our other internal services. 

2. The current tenant name will continue serve as a human readable name while the customer UID will allow us to better integrate netbox with other services. 

### Database Changes
1. Add a new integer field for (UID) to tenant object. Please note that I'm not too familiar with the codebase or database structure. I imagine this is a trivial or easy change. 

### External Dependencies
Not Applicable

**Comment by jeremystretch** [comment]
This issue has been closed as it does not conform to one of the [provided templates](https://github.com/digitalocean/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/digitalocean/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by djmelik** [comment]
Hi Jeremy, I apologize for that. I have made the appropriate changes per your request. Please let me know if you require additional information. I hope that this gets re-opened. Thank you for your help!

**Comment by lampwins** [comment]
While your use case is perfectly valid, I feel it is not universal and thus does not warrant modification of the data model. This sort of situation is exactly why NetBox supports [custom fields](https://netbox.readthedocs.io/en/stable/additional-features/custom-fields/). Is there a reason that would not work for you?

**Comment by djmelik** [comment]
> While your use case is perfectly valid, I feel it is not universal and thus does not warrant modification of the data model. This sort of situation is exactly why NetBox supports [custom fields](https://netbox.readthedocs.io/en/stable/additional-features/custom-fields/). Is there a reason that would not work for you?

I was not aware of this feature, let me run a few tests against our environment. Thanks a lot for this information!

**Comment by LBegnaud** [comment]
For what it's worth, i use the slug as the UID in our org. Seems perfectly suited for that

**Comment by Grokzen** [comment]
CustomFields should be good enough for this use-case.

**Comment by jeremystretch** [comment]
As others have pointed out, there are a couple options for doing this. Going to close this out.
