### ISSUE TITLE
add distinction between OS1 and OS2 for singlemode fiber in constants.py

### ISSUE THREAD

**Issue by fischa** [digitalocean/netbox#2878]
### Environment
* Python version:  3.6 (from netbox-community docker image)
* NetBox version:  2.5.5

### Proposed Functionality
Addition of OS1 and OS2 singlemode fiber options in constants.py. No changes to workflow or user interface needed as far as I can see.  I can add a PR if requested.

### Use Case
This is needed for being able to choose from this two types of singlemode fiber for cable "creation". Till now there is just "Singlemode Fiber" available but four types of multimode fiber.

### Database Changes
Not that I'm aware of. Name and ID come from constants.py and are probably stored as such in the DB.

### External Dependencies
None.

**Comment by fischa** [comment]
![image](https://user-images.githubusercontent.com/11302991/52624809-e228f400-2eaf-11e9-9b44-22f44ac4bcf4.png)

**Comment by DanSheps** [comment]
As discussed in Slack, there are other types beyond OS1 and OS2, so I would propose keep SMF as 3500, then add OS1 and OS2 as something like 3510, 3520 as they are derivative of the SMF type but rename it Singlemode Fiber (Generic)

**Comment by tb-killa** [comment]
http://www.thefoa.org/tech/ref/basic/fiber.html


I prefer using official Names (see Graphic) if we allow to specify them:
http://www.thefoa.org/tech/ref/basic/FiberFamilyTree.jpg

**Comment by jeremystretch** [comment]
For consistency, I'm going to:

1. Add a generic MMF type
2. Keep the existing generic SMF type in place
3. Add two new types for OS1 and OS2

This leaves it up the user whether they want to specify just MMF or SMF, or a specific class.
