### ISSUE TITLE
Specify different power cable types

### ISSUE THREAD

**Issue by skoef** [digitalocean/netbox#2879]
### Environment
* Python version:  3.6.7
* NetBox version:  Example: 2.5.6

### Proposed Functionality
Specify multiple types of power cables. While there is a variety of network cables available to choose from in netbox, there is only 1 generic type for power cables. I'd suggest splitting this up into more specific types. I can think of C13-C14, C13-C20, C19-C20, C13-Schuko etc,

This might imply the type of power outlet and port as well: for instance, my PDU might have 16 C14 outlets and a couple of C20's as well. If netbox would allow to specify the type of power outlet or power port, perhaps specifying the cable to connect both would be redundant.

### Use Case
In our datacenter we use a mixture of C13-C14 and C13-C20 cables to connect our servers to PDU's while we also have some C13-Schuko cables to PDU's. I would like to have these differences visible in netbox

### Database Changes
I've tested locally with updating `dcim/constants.py` by 
creating some additional types and as long as we keep the generic type around as well, I would say this requires no database change. If we need to convert the generic type to one of the specific types, then we probably need a migration step.

The addition I did was:
```python
CABLE_TYPE_POWER_C13C20 = 5132
CABLE_TYPE_POWER_C13C14 = 5134
CABLE_TYPE_POWER_C19C20 = 5192
...
    (
        'Power', (
            (CABLE_TYPE_POWER_C13C14, 'C13 to C14'),
            (CABLE_TYPE_POWER_C13C20, 'C13 to C20'),
            (CABLE_TYPE_POWER_C19C20, 'C19 to C20'),
        ),
    )
```

I'm operating from Europe where these connectors are common, perhaps US DCs use completely different connectors that might be of use here as well.

### External Dependencies
none

**Comment by jeremystretch** [comment]
The cable mdeium does not inform the termination form factors. This will be covered under #792.
