### ISSUE TITLE
Device web view : rear port connection view refers to its own device  

### ISSUE THREAD

**Issue by louis-oui** [digitalocean/netbox#2885]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.5 

### Steps to Reproduce
1. Connect a cable between rear port of two devices

### Observed Behavior
When browsing on both devices with http://XXX/dcim/devices/<id>, the rear port view of both devices refers to the same device name and url in the connection field. That means : on one device, the data in connection field is correct and refers to the correct remote device and on the other one, the output refers to the itself.

However, cable terminations are correct in http://XXX/dcim/cables/<id>

### Expected Behavior

Rear port connection field should always refers to the other termination device not to its device.

**Comment by jeremystretch** [comment]
Already addressed under #2844 and will be fixed in v2.5.6.
