### ISSUE TITLE
Prefill Manufacturer field after adding new manufacturer and Device Type

### ISSUE THREAD

**Issue by TakeMeNL** [digitalocean/netbox#2887]
### Environment
* Python version:  3.6
* NetBox version:  2.5.6

### Proposed Functionality
When on the device-type page with a specific manufacturer selected the add button pre fills the Manufacturer field in the "Add a new device type" form. 

### Use Case
When adding a new Manufacturer you can directly add a device-type. But when the form loads you still have to select the Manufacturer. Prefilling this would enhance the experience .

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
This is one of those things that takes a significant amount of development effort to achieve very little. And if we were to do it for this field, tomorrow I would have requests to do it for others. Sorry but we just don't have the development bandwidth for niceties right now.

**Comment by TakeMeNL** [comment]
Oke i understand, it was just something that was not working "nicely" in the flow of adding device types.
