### ISSUE TITLE
Add LC/APC, SC/APC and LSH/APC port types

### ISSUE THREAD

**Issue by gdelafond** [digitalocean/netbox#2890]
### Environment
* Python version:   3.5.3
* NetBox version:   2.5.6

### Proposed Functionality

Add LC/APC, SC/APC and LSH/APC port types.

### Use Case

We need to track LC PC/APC and SC PC/APC port type on patch panel.

### Database Changes

None.

### External Dependencies

None.

**Comment by jeremystretch** [comment]
Please revise your request to specify the _exact_ types you're proposing and include justification for why the existing types aren't sufficient.

**Comment by gdelafond** [comment]
We have patch panel with 4 differents port types:  LC/PC, LC/APC, SC/PC and SC/APC.

Currently in Netbox there is already LC and SC port types. LC is usually a shortcut for LC/PC and SC for SC/PC. That's why I want to add LC/APC and SC/APC.

As I know that LSH/APC exists too (cf #2569), I have included it in my PR.

So this request and the PR is to add the following port types : 
- LC/APC
- SC/APC
- LSH/APC

If you want, in addition I can rename existing LC to LC/PC and existing SC to LC/PC.
