### ISSUE TITLE
Cable filtering based on status.

### ISSUE THREAD

**Issue by snowie-swe** [digitalocean/netbox#2898]
### **Environment**
NetBox version:  2.5.5

### **Proposed Functionality**
Give the possibility to filter cables based on status (Planned/Connected)
Within the view https://netbox/dcim/cables/

### **Use Case**
Easier to view status for planning on site personnel.

**Comment by tb-killa** [comment]
I even see the "Length" as an additional filter too.

Please implement "Status" and "Length" Filter (Select2) in the "Search" Bar.
