### ISSUE TITLE
Upgrade to V2.5.3 loses changelog records

### ISSUE THREAD

**Issue by CraigRMoore** [digitalocean/netbox#2900]
We performed an upgrade from V2.4.6 -> V2.5.3 and have only just now noticed that we have lost any previous changelog records.
### Steps to Reproduce
1. Upgrade from V2.4.6 -> V2.5.3
2. Upgrade successfully with no obvious errors reported
3.

##
Changelog records to be retained

Changelog records lost

**Comment by stuntguy3000** [comment]
Both versions you stated are now outdated and probably unsupported. I did an upgrade from 2.5.5->2.5.6 last night no worries. 

Did you run the migration script?

**Comment by CraigRMoore** [comment]
ok, assuming you mean the upgrade.sh script? then yes.

**Comment by stuntguy3000** [comment]
I can't comment on schema changes from 2.4 -> 2.5 so you will have to sit tight until another contributor can comment.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
