### ISSUE TITLE
Region view sort by Sites error

### ISSUE THREAD

**Issue by johanreinalda** [digitalocean/netbox#2901]
In Regions view, clicking on the Sites header to sort results in error:

```
<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'site_count' into field. Choices are: children, created, id, last_updated, level, lft, name, parent, parent_id, rght, sites, slug, tree_id
If further assistance is required, please post to the NetBox mailing list.
```

### Environment
Netbox version 2.5.5
Python 3.6

### Steps to Reproduce
1. go to Organization menu
2. click on Regions
3. click on Sites column to sort

### Expected Behavior
Sort regions display/view sorted by site count

### Observed Behavior
Crash...

**Comment by stuntguy3000** [comment]
Can replicate in 2.5.6.

**<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'site_count' into field. Choices are: children, created, id, last_updated, level, lft, name, parent, parent_id, rght, sites, slug, tree_id**

**Comment by johanreinalda** [comment]
just upgraded to 2.5.6, and same problem :-)

**Comment by robbagithub** [comment]
also an issue in 2.5.4
