### ISSUE TITLE
Add non-image attachements to nodes/elements

### ISSUE THREAD

**Issue by pobk** [digitalocean/netbox#2904]
### Environment
* NetBox version:  2.5.6

### Proposed Functionality
Add additional uploads and document management to devices.

### Use Case
I have a number a contracts, licenses, certifications and other miscellaneous documents for devices, sites, regions, circuits, virtual machines etc. It would be advantageous if these documents can be stored within NetBox as the 'single source of truth'.

### Database Changes
Addition of an "Attachment" object and generic relations to other nodes.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
This was raised and rejected under #1039
