### ISSUE TITLE
40G QSFP in breakout mode

### ISSUE THREAD

**Issue by dnyt84** [digitalocean/netbox#2905]
* NetBox version:  2.5.2

We are using Switches with 40G QSFP in breakout mode making it 4 x 10G.
However we take a single cable to a patch Panel and then break it out to 4 x Duplex LC ports.

How can I connect a cable in Netbox from 1 x 40G via MTP on the switch to 4 x Duplex LC on the patch panel?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
