### ISSUE TITLE
40G QSFP

### ISSUE THREAD

**Issue by dnyt84** [digitalocean/netbox#2906]
* NetBox version:  2.5.2

We are using Switches with 40G QSFP in breakout mode making it 4 x 10G.
However we take a single cable to a patch Panel and then break it out to 4 x Duplex LC ports.

How can I connect a cable in Netbox from 1 x 40G via MTP on the switch to 4 x Duplex LC on the patch panel?
Switch QSFP MTP (Port on switch are Eth 1/1 - Eth 1/4) -> Casset MTP Back -> 8 x LC Front

**Comment by jeremystretch** [comment]
Do not open duplicate tickets. You were directed to raise this question on the mailing list under #2905. It is not a feature request or bug.
