### ISSUE TITLE
View all interfaces

### ISSUE THREAD

**Issue by rekkoner** [digitalocean/netbox#291]
Wondering what people think about viewing interfaces specifically (and only), and viewing groups, ability to filter by type (based on name, "form factor", use status, etc).

Would be nice to see what interfaces are available, and not just connected interfaces.

**Comment by bellwood** [comment]
@rekkoner can you clarify? When I view a device or device type I am able to see every interface defined regardless of its connected status.

Are you speaking to interface connections found on `/dcim/interface-connections/`?

**Comment by rekkoner** [comment]
@bellwood sure, basically, listing all defined interfaces, regardless of connected status.

currently, you can see all connected interfaces, and that's it. that's the highest level you can go, and it's limited to view only interfaces connected to something.

it'd be nice if we had visibility into _all_ interfaces, regardless of status or use.

second to that, if we had that visibility, the ability to then filter down based on whatever criteria (core switches blue and green, etc), so we then can look at, potentially, multiple devices' interfaces. then we'd be able to compare primary/secondary port usage, etc.

**Comment by jeremystretch** [comment]
As I understand it, you're asking for a list of _all_ interfaces defined in NetBox, from all devices. A typical NetBox installation will have thousands of interfaces. I'm not sure I see what purpose this would serve. What would you do with a list of every interface?

**Comment by rekkoner** [comment]
true, viewing a list of all 3000 or whatever interfaces wouldn't be very useful. but, if you can drill down to type, location, device model, primary/secondary/backup/etc, and show brief interface details, (if name, device, state (in use, unused, reserved, disabled, planned, decommed, etc)), i think it would be helpful.

i know my datacenter infrastructure teams would use that to track our core switch interface usage, storage switch interface usage, and so on, for capacity planning, physical configuration verification, etc.

**Comment by jeremystretch** [comment]
I'm going to close this out as it seems like a pretty esoteric request. It can likely be accomplished with a few API calls anyway.
