### ISSUE TITLE
Cables Type Filter prefiled with wrong Type

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#2912]
### Environment
* Python version: 3.6
* NetBox version: 2.5.6

### Steps to Reproduce
1. Create two Device for e.g. Patchpanel
2. Connect both Rear Ports with Cable and Select for Type e.g. CAT7
3. Go to Devices -> Cables and read the created Connection in Table View compare to the Predefined Search Element in the Right Searchbar.

### Expected Behavior
The Cable Type in the Search-Bar should be match to the Connections in the Table themselve.

### Observed Behavior
It shows as default "CAT3" in the Type Field of the Search Box.

![image](https://user-images.githubusercontent.com/932481/52999053-1c047800-3425-11e9-9025-a4daa2f233bc.png)

**Comment by jeremystretch** [comment]
To clarify, this behavior is irrelevant to the types of cables defined: The form field should always be empty by default.
