### ISSUE TITLE
Update cable metod put.

### ISSUE THREAD

**Issue by VictorPavlushin** [digitalocean/netbox#2919]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.5

1. Create cable, Length length_unit do not fill.
2. If use class NetboxMapper in netboxapi and change termination.
3. Сalling the put method, returns an error that length_unit cannot be empty. Even if you first remove the attributes from the object. They are added to the to_dict functions class NetboxMapper. Here is an example of what is being transmitted in json:

> {'id': 612, 'termination_a_type': 'dcim.interface', 'termination_a_id': 10488, 'termination_b_type': 'dcim.interface', 'termination_b_id': 8491, 'type': 3040, 'status': True, 'label': '', 'color': '', 'length': None, 'length_unit': None, 'termination_a': 10488, 'termination_b': 8492}

If I fill in the Length and length_unit and call the put method, then everything is fine, except that something strange happens on the device pages, I cannot describe it, but I can show:[https://ibb.co/6B7kdwf](https://ibb.co/6B7kdwf)

**Comment by jeremystretch** [comment]
NetboxMapper is not a part of this project. Please raise an issues against that project if you believe it has a bug. We can only accept bug reports that can be reproduced without the use of a third-party tool.
