### ISSUE TITLE
Add part number field to DeviceType

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#292]
I know that this tool will use RPC (ssh/netconf/etc.) instead of SNMP when interacting with devices, but with other DCIM I have seen issues with model numbers polled do not even resemble the official model numbers.  As such, this has forced the need for model names, model numbers, an aliases for when odd SNMP model numbers are presented.

Regardless, I am just thinking about how we can enhance this object.  Furthermore, how should we handle the various variations of switch like the Catalyst 3750?  What are your thoughts on:
- device type alias (to handle model numbers as well as potentially variations)
- model/part number to handle the technical part number (normally hyphenated) - This would force you to create a device type for every variation of a model (not necessarily bad given the port count and speed variations)

**Comment by bellwood** [comment]
For my cisco switches I do a `show version` and use say:

-WS-C3750E-24
-WS-C4948-10GE
-WS-C3750E-48

I don't have any POE models and am agnostic to IPbase vs IPservices so I don't bother to store the bits after that typically indicate the licensing included, POE, or other - but - if I did I would include them - there are though as you say so many variations that it's not (in my application) worth tracking it that granularly.

Each of these are their own device type with corresponding interfaces pre-set (sans VLANs)

**Comment by jeremystretch** [comment]
> How should we handle the various variations of switch like the Catalyst 3750?

Each variation is its own device type. Even a minimal difference between models (e.g. PoE versus non-PoE) is still a difference and needs to be accounted for. At most we might introduce the concept of a series to group similar devices, but that would just be for convenience.

**Comment by ryanmerolle** [comment]
Yea I'm with you on series for connivence, its really not absolutely needed.  But what are your thoughts on model / part number.  IE Part Name (Catalyst 3750X 48T-S) vs the official part number (WS-C3750X-48T-S).

**Comment by bellwood** [comment]
I can see value in having a field for part/model.

We have some Cisco 3500 series switches that all say on the chassis they are `WS-3500-something` but show version could be a WS-3524 or WS-3548, etc

Not sure how other manufacturers stack up another use case to validate would be great otherwise we're essentially storing redundant information.

**Comment by jeremystretch** [comment]
Intending to implement this as a new (optional) free-form `part_number` field on `DeviceType`.
