### ISSUE TITLE
Rename Interface form_factor to type

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#2920]
### Proposed Changes
Rename the `form_factor` field on the dcim.Interface model to `type`, and update forms and serializers accordingly.

### Justification
"Form factor" is a misnomer given the field's purpose in conveying specific network technologies. For example, 100 Mbps and 1 Gbps Ethernet can both utilize the 8P8C copper form factor, but provide two different types of services and employ different wire protocols.

**Comment by lampwins** [comment]
@jeremystretch  I think we should we allow a period of backward compatibility in the API. Say go ahead and change the model field but in the API continue to allow the use of `form_factor` for a period of time (I suggest until 2.7)? I foresee this being one of those nasty breaking changes for a lot of people and thus a reason to delay 2.6 adoption.

**Comment by jeremystretch** [comment]
Yeah, I've been asking myself whether it's honestly worth the hassle. I suppose we could migrate the field name, then add a getter/setter named `form_factor` with a deprecation warning to retain backward compatibility until v2.7.

**Comment by jeremystretch** [comment]
I've renamed `form_factor` to `type` but added a new `form_factor` field to replicate the functionality of `type` for backward compatibility. This field will be removed in NetBox v2.7.
