### ISSUE TITLE
Circuit Providers filter prefiled with Site

### ISSUE THREAD

**Issue by jbakklund** [digitalocean/netbox#2923]
The Circuit Providers search filter should be blank by default.

### Environment
* Python version:  3.5.3
* NetBox version:  2.5.7

### Steps to Reproduce
1. Go to Organization > Sites and make sure that there is at least one site registered
2. Go to Circuits > Providers

### Expected Behavior
The search form should be blank by default.

### Observed Behavior
The search form input field for 'Site' show you the name of the site that comes first alphabetically. This issue seems to have some similarity to issue #2912.

**Comment by DanSheps** [comment]
Took a look at this, and there are a couple ways this could be fixed:

* Add null_label='' to the FilterChoiceField
* Change it to a APIMultipleSelect

When looking at this, I also found a few forms that aren't using Select2.
