### ISSUE TITLE
Form factor for 50G QSFP28

### ISSUE THREAD

**Issue by shivam2612** [digitalocean/netbox#2924]
### Environment
* Python version:  
* NetBox version:  

### Proposed Functionality
Additon of form factor for 50G QSFP28 for interfaces.
Code line change in file _netbox/dcim/constants.py_, (only addition of two lines, for example)
```
# Ethernet
IFACE_FF_50GE_QSFP28 = 1450
...
IFACE_FF_CHOICES = [
'Ethernet (modular)',
        [
         [IFACE_FF_50GE_QSFP28, 'QSFP28 (50GE)'],
... 
```

### Use Case
50G is also common like 25G, 40G in Ethernet(modular). 

### Database Changes
No change in database

### External Dependencies
No dependencies

**Comment by jeremystretch** [comment]
I could be mistaken but I don't think 50GE uses SFP28. I'm also having a hard time tracking down a commercially-available transceiver for reference.

**Comment by DanSheps** [comment]
@jeremystretch I did check this out myself, I couldn't find any transceivers and couldn't definitively find out whether it is QSFP28 or SFP56/QSFP56 (which is what it seems to suggests).

Doing a little more digging:

According to [this](https://www.cadence.com/content/dam/cadence-www/global/en_US/documents/company/Events/summits/photonics/photonics-juniper-maki.pdf), it looks like it might be:

* QSFP28 (2x25g)
* SFP56 (1x50g)

**Comment by dnyt84** [comment]
http://eoptolink.com/products/qsfp28-pam4-50g
http://www.10gtek.com/QSFP28-to-2x-50G-QSFP28-DAC-283.html
100G QSFP28 is 4 x 25G

**Comment by shivam2612** [comment]
Thanks @dnyt84
