### ISSUE TITLE
specify the "Rack Group" when creating a termination point

### ISSUE THREAD

**Issue by gjvc** [digitalocean/netbox#2929]
### Environment
* Python version: 3.7
* NetBox version: 2.5.7

### Proposed Functionality

I would like to be able to (optionally or not) specify the "Rack Group" when creating a termination point (A- or Z-side) of a Circuit in Netbox, because "Site" alone is not specific enough.

### Use Case

if there are multiple cages (each cage having its own patch panel, and being represented by a "Rack Group") within a datacentre ("Site"), and cross-connects between them, there needs to be some way to specify the cage ("Rack Group") on each side, and currently (v2.5.7), there is only a dropdown for "Site".

### Database Changes

Add Foreign Key to CircuitTermination for Rack Group

### External Dependencies

None

**Comment by DanSheps** [comment]
Is there a reason you cannot connect this circuit directly to a device?

**Comment by gjvc** [comment]
Good question :-).  I wish to model switch port to local patch panel to remote patch panel.  This is two connections in the real world, and I'd like to reflect that in netbox.

**Comment by DanSheps** [comment]
> Good question :-). I wish to model switch port to local patch panel to remote patch panel. This is two connections in the real world, and I'd like to reflect that in netbox.

Personally, I would model this as a regular connection, however you can also model this as a circuit, but it isn't 100% proper:

* Create Circuit
* Create "A" side
* Connect "A" side to rear port on PP1
* Create "Z" side
* Connect "Z" side to rear port on PP2

**Comment by jeremystretch** [comment]
This limitation will be addressed in v2.6. For now, you can make the connection to the circuit termination starting from the patch panel side.
