### ISSUE TITLE
Allow for RIR links or Github Markdown Styled Comments

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#293]
It would make sense to RIR links to RFCs or RIR portals.  Furthermore, comments could be used to further an RIR.  You could just use comments instead of a new link field.

**Comment by jeremystretch** [comment]
Users should have at most a handful of RIRs defined. In 99% of cases, these will be actual RIRs and RFC 1918/6598. What additional information is worth storing about these objects?

**Comment by ryanmerolle** [comment]
RIR object owners, contacts, admins, links, etc.

It makes sense for when cross connects or circuits from third parties that may leverage public ip space.

**Comment by ryanmerolle** [comment]
I never saw your comment sorry! It only makes sense for firms that have a heavy crossconnect infrastructure where they are peering to multiple 3rd parties and need some additional metadata to validate prefixes are owned by said third party or associate prefixes to a tenant that they were not notified of.

**Comment by jeremystretch** [comment]
The RIR only represents the top-level owner of a prefix. So for example, ARIN or RIPE, not Widgets, Inc. NetBox supports tenancy now for tracking per-prefix ownership.
