### ISSUE TITLE
Device List Role filter duplicates first item

### ISSUE THREAD

**Issue by stuntguy3000** [digitalocean/netbox#2936]
### Environment
* Python version: 2.7.5
* NetBox version:  v2.5.7

### Steps to Reproduce
1. Go to *Devices* overview page
2. Try to filter by _Role_

### Expected Behavior
The device roles should appear only once.

### Observed Behavior
![image](https://user-images.githubusercontent.com/1522389/53541746-26341e00-3b6b-11e9-87bd-6a7568afbca4.png)

**Comment by zelfix** [comment]
There is the same bug
![image](https://user-images.githubusercontent.com/10135380/53561065-e2d3b280-3b5e-11e9-844f-aff6e0df92d3.png)

**Comment by jeremystretch** [comment]
@lampwins think you'd be able to take a look at this?

**Comment by lampwins** [comment]
Yes, I will take care of this.

**Comment by lampwins** [comment]
For reference, this occurs when `null_option` is True on the widget but the field does not specify a `null_label`.

```
    role = FilterChoiceField(
        queryset=DeviceRole.objects.all(),
        to_field_name='slug',
        widget=APISelectMultiple(
            api_url="/api/dcim/device-roles/",
            value_field="slug",
            null_option=True
        )
    )
```
