### ISSUE TITLE
Editing objects without a summary page redirect to the child (Region, RIR, Rack Groups, Manufacturer) instead of the object Table

### ISSUE THREAD

**Issue by stuntguy3000** [digitalocean/netbox#2937]
### Environment
* Python version: 2.7.5
* NetBox version:  v2.5.7

### Steps to Reproduce
1. Edit a RIR
2. Click "Cancel" or "Update"

### Expected Behavior
The page should navigate back to the RIRs summary.

### Observed Behavior
The page navigates to the Aggregates summary.

**Comment by DanSheps** [comment]
This behaviour is consistent with other objects that do not have an object view (Regions, Rack Groups, Manufacturers).

I am not sure if we want to change this behaviour.

**Comment by goebelmeier** [comment]
As i wrote in #3004 i would like to return back to the objects summary not into the child summary.

**Comment by mmahacek** [comment]
The current flow (v2.5.8) is:
1. /ipam/rirs  (Click Edit)
2. /ipam/rirs/SLUG/edit (Click update/cancel)
3. /ipam/aggreagtes/?rir=SLUG

I would expect the update/cancel action to take me back to /ipam/rirs where I started.  I would prefer that these go back to the page I started from, not show me related records.
