### ISSUE TITLE
Prefix import with VRF information is not possible when RD is not configured

### ISSUE THREAD

**Issue by markkuleinio** [digitalocean/netbox#2940]
### Environment
* Python version:  3.5.3
* NetBox version:  2.5.7

### Steps to Reproduce
1. Go to prefix import
2. vrf field requires VRF RD, the VRF name is not usable
3. Import to the correct VRF is not possible if VRF does not have RD configured

### Expected Behavior
It should be possible to use either the internal ID of the VRF (shown in the URL as in `/ipam/vrfs/4/`) or the VRF name in the vrf field.

### Observed Behavior
If trying to use VRF name or ID in the vrf field: "Row 1 vrf: VRF not found."

**Comment by jeremystretch** [comment]
Can't use VRF name as it's not guaranteed to be unique. Will have to enable using the primary key as we do for unnamed devices.
