### ISSUE TITLE
Setting VLAN Group/VLAN of Child Prefixes based on VLAN Group/VLAN assignment of parent prefix

### ISSUE THREAD

**Issue by ironick09** [digitalocean/netbox#2943]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.1

### Proposed Functionality
This proposal is to add functionality to automatically assign the VLAN Group/VLAN ID to child prefixes that are created under a prefix that is already assigned a VLAN Group and VLAN ID.

### Use Case
I create an IP prefix of 192.168.0.0/24, and I assign this IP prefix to the following:
* Tenant: ironick09
* VLAN Group: ServerNetwork
* VLAN ID: 5

Next, I create a child prefix that is under my previous prefix of 192.168.0.0/24. The child prefix I create is 192.168.0.0/26 (192.168.0.0-63). This might just be a pool, or something similar.

Current behavior when creating this child prefix is the fields `VLAN Group` and `VLAN ID` are by default left empty. 

This feature request proposes auto populating these fields based on the `VLAN Group` and `VLAN ID` fields from the parent prefix. 

### Database Changes
None that I am aware of 

### External Dependencies
None that I am aware of.

**Comment by DanSheps** [comment]
Please see Jeremy's comments on #2887 (Prefilling Manufacturer for DeviceType).

As this would take considerable more effort, I don't think this is in the cards right now.  Once the backlog is cleared, I this could be re-visited.

**Comment by ironick09** [comment]
Thanks, I tried looking through the code to see if it was something I could tackle myself but I figured I’d post here first.
