### ISSUE TITLE
Device CSV Import: Add field to import Primary IP address

### ISSUE THREAD

**Issue by anthonyeden** [digitalocean/netbox#2946]
### Environment
* Python version:  3.7.2
* NetBox version:  2.5.7

### Proposed Functionality

I'd like to modify the Device Import CSV screen (/dcim/devices/import/) to allow importing a Primary IPv4 and/or IPv6 address along with devices.

This would include adding two new optional column headers, which can be detected by the CSV importer.

I'd also like to include these two new columns in the Device Export CSV template.

I am willing to implement this myself and create a pull request.

### Use Case

This would assist with on boarding new users to Netbox, especially where they have existing de-normalised spreadsheets containing devices and their Primary IP Addresses in the same spreadsheet.

### Database Changes

I do not believe this change would require any change to the database.

### External Dependencies

N/A

**Comment by DanSheps** [comment]
Just to point out, this is not an easy thing to do.  The primary IP is simply an IP tied to an interface designated as primary.

You would have to import an interface as well.

There is currently a backlog of feature requests that need to be addressed first.  It is unlikely that this will be an accepted FR in the short term.

**Comment by DouglasHeriot** [comment]
Yeah I realise there's a few steps to implementing this as it spans a few model objects, but it would be a big usability win for us to get more users entering devices into NetBox properly.

If we do the work on it and submit a pull request, I hope that this is a feature that fits with the project and will be accepted?

**Comment by jeremystretch** [comment]
Unfortunately the data model won't allow for this to be implemented in any sane way. As @DanSheps notes, designating a primary IP requires several steps:

1. Create the device
2. Create an interface on that device
3. Assign an IP address to that interface
4. Update the device to reflect the new primary IP

This isn't feasible inside the CSV import workflow, which is limited to working with a single object type. However, it would be pretty straightforward to script these operations out using the REST API or command shell.

**Comment by candlerb** [comment]
Maybe a first step would be to allow the REST API to allow creation of composite objects from JSON: i.e. a Device with nested Interfaces with nested IP Addresses.
