### ISSUE TITLE
Saving a search as a filter

### ISSUE THREAD

**Issue by champidead** [digitalocean/netbox#2950]
### Environment
* Python version: 3.6
* NetBox version:  61003208e802 (v2.4.8)

### Proposed Functionality

Add the ability to save a search in the NetBox menu and name it.

### Use Case

An example :

- We commonly use the filter `q=Pool&vrf=0&status=1&role=service-inet` to get all our public IP pools.
- Each user has to bookmark this link in its browser.
- The ability to save a search in the NetBox menu for all users would be very convenient:

![save_search_as_filter](https://user-images.githubusercontent.com/4362224/53636051-3574a380-3c1f-11e9-9535-09f975c3c91c.png)

### Database Changes

This change requires to add a new table that stores the search (e.g., `q=Pool&vrf=0&status=1&role=service-inet`) and the name (e.g., `public IP pools`) as well as an admin section to maintain the saved searches.

**Comment by jeremystretch** [comment]
I'm sorry but we're not able to accept requests for any new features until the current backlog has been reduced.

**Comment by champidead** [comment]
I understand and this is not an important feature.
Maybe we are going to develop it ourselves and send a pull request.
Thanks for your work on NetBox!

**Comment by tb-killa** [comment]
If you use this type of search in periodic way, the simple solution would be for the first you build your search links via the

```
BANNER_TOP
BANNER_BOTTOM
Setting these variables will display content in a banner at the top and/or bottom of the page, respectively. HTML is allowed.
```

as this is show everywhere.

**Comment by champidead** [comment]
Hello @tb-killa,

Yes, we will often use these filters. They are quite permanent so a static solution like you described is totally fine. I will try this when I'm going back to work, thanks!

**Comment by champidead** [comment]
@tb-killa, I tried what you suggested and it does the trick like a charm! Thanks again.
Too bad I didn't find this feature earlier in the doc ([optional-settings/#banner_top](https://netbox.readthedocs.io/en/latest/configuration/optional-settings/#banner_top)).
