### ISSUE TITLE
Does netbox support multiple users with independent networks?

### ISSUE THREAD

**Issue by hankok** [digitalocean/netbox#2951]
I want to provide different customers access to a single netbox setup that manages different networks from each customer.

The built-in tenants doesn't support independent networks, they all share the same network.

**Comment by lampwins** [comment]
What you are looking for is not directly supported by NetBox. NetBox is intended to track assets that you own. The Tenant model is meant to be used in situations where "I own this thing but Customer X uses it." Furthermore, NetBox does not support the granular RBAC controls you would be looking for as a part of this.

Also, questions like this are much better suited on the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss), not GitHub issues.
