### ISSUE TITLE
The functional role of this IP (Gateway/Broadcast)

### ISSUE THREAD

**Issue by Maxkaha** [digitalocean/netbox#2953]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.6

### Proposed Functionality

Is it possible to have the roles "Gateway" and "broadcast" for IP addresses?

### Use Case

N/A
### Database Changes

N/A

**Comment by jeremystretch** [comment]
The gateway "role" is entirely dependent on configured routes: One prefix may have different gateways for different hosts and/or different destinations. It's not a function of the IP address model to declare whether an IP is a gateway for some subset of hosts.

Similarly, broadcast functionality is informed by the assigned address and mask: It's not something that can be toggled. Typically, you won't create IP addresses in NetBox to represent the broadcast address anyway.
