### ISSUE TITLE
Trailing slash on STATIC_ROOT and template DIRS breaks on Windows

### ISSUE THREAD

**Issue by axnsan12** [digitalocean/netbox#2954]
### Environment
* Python version:  3.7.1
* NetBox version:  2.5.8-dev

### Steps to Reproduce

1. Run `manage.py collectstatic` on Windows
2. Weep

### Expected Behavior

Working app.

### Observed Behavior

Paths with trailing slashes do not work on windows, they cause errors such as `django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Projects\netbox\netbox\static\clipboard-2.0.4.min.js) is located outside of the base path component (C:\Projects\netbox\netbox\static\)`.

**Comment by jeremystretch** [comment]
Fixed by #2955
