### ISSUE TITLE
Interface_connections creation: Method "POST" not allowed

### ISSUE THREAD

**Issue by berahtlv** [digitalocean/netbox#2958]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.7

### Steps to Reproduce
Make POST request to `api/dcim/interface-connections/` with data like `'{"interface_a":59581, "interface_b":59580, "connection_status":true}'`

### Expected Behavior
Interface connection created

### Observed Behavior
`Method "POST" not allowed` error returned instead. Behavior is the same with Curl and Pynetbox. Netbox v2.4.4 works as expected.

**Comment by awlx** [comment]
The API endpoint was deprecated in favour of the Cables endpoint:
https://github.com/digitalocean/netbox/issues/2680

**Comment by berahtlv** [comment]
Thanks,
Managed to create connection, now it looks like:
`{'termination_a_type': 'dcim.interface', 
'termination_a_id': 1518, 
'termination_b_type': 'dcim.interface', 
'termination_b_id': 1519, 
'connection_status':True}`
