### ISSUE TITLE
Add interface support for "virtual" cable types

### ISSUE THREAD

**Issue by ganawaj** [digitalocean/netbox#2959]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.3

### Proposed Functionality

Add a "virtual" cable type 

### Use Case

Most of my environment is using NSX. I have found a workaround for our virtual switches and routers by creating them as "devices" (as non-rackable devices) rather than virtual machines. This way I can create a actual cable from one device to another, which I can't do as a VM since all interfaces are virtual interfaces (which cant be connected). 

With a virtual cable (wire, as NSX describes it) I'll be able to use the filters in the sidebar instead of leaving the blank and losing out on that function. It's also a step towards some SDN support without extending the functionality too much (Too many products out there to account for). 

### Database Changes

"virtual" as a new category of cable type

**Comment by DanSheps** [comment]
This was requested and rejected in #2797 due to the current backlog.  In the future, once the backlog has cleared, there might be time to revisit this.
