### ISSUE TITLE
[Usability] Confusion over "Model" vs "Device Type"

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#296]
When you create a new device, Netbox prompts you for "Manufacturer" and "Model".

However it is non-obvious how to create a "Model". After some head scratching, it turns out that actually you need to create a "Device Type"

This could be made clearer by using the same name consistently throughout the interface, or at least giving a hint:

~~~
Manufacturer         [Apple      ]
Model (device type)  [           ]
~~~

Also: if you have not created any device types, this stops you creating a device. So another approach would be to display a message if you select it, in place of an empty drop-down list:

~~~
Manufacturer    [Apple      ]
Model           No device types yet created for Apple
~~~

(or this could be an option list with one greyed-out member)

**Comment by cstueckrath** [comment]
already fixed. Did you pull the latest version and run ./upgrade.sh?

**Comment by candlerb** [comment]
You guys are too quick for me :-)

The upgrade went without a problem, except the running manage.py died:

~~~
usage: manage.py runserver [-h] [--version] [-v {0,1,2,3}]
                           [--settings SETTINGS] [--pythonpath PYTHONPATH]
                           [--traceback] [--no-color] [--ipv6] [--nothreading]
                           [--noreload]
                           [addrport]
manage.py runserver: error: unrecognized arguments: --insecure
~~~

But oddly, I was able to restart it with the `--insecure` option just fine, despite what the error message said.

BTW: I have just done a demo of netbox at the [Rwanda Network Operators Group](https://nsrc.org/workshops/2016/rwnog-nmm/) network monitoring and management workshop. Thank you for the great work!
