### ISSUE TITLE
15 symbols is not enough for "application/json" mime type

### ISSUE THREAD

**Issue by zelfix** [digitalocean/netbox#2962]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.7

### Steps to Reproduce
1. Open Admin -> Export templates -> ADD EXPORT TEMPLATE
2. Try to write "application/json" in the "Mime type" field

### Expected Behavior
The text "application/json" is written

### Observed Behavior
It is written "application/jso"

**Comment by DanSheps** [comment]
Field is limited to 15.

Migration will likely be required to increase the field length.
