### ISSUE TITLE
Ability to link services on devices

### ISSUE THREAD

**Issue by trunet** [digitalocean/netbox#2964]
### Environment
* Python version:  3.6
* NetBox version:  2.5.7

### Proposed Functionality
Netbox should have a way to link services on devices. If one device provides a service, it should be able to link (connect) it on another device.

### Use Case
I have a storage cluster with multiple 4U nodes, each with its own IP address, network interfaces, memory, CPUs, .... On netbox, I created an NFS service on each storage node (device).

Than, I have my servers that access this devices, they can mount the NFS of one specific storage node.

I would like to link multiple servers connecting to each storage device so we can track what is connected where.

**Comment by DanSheps** [comment]
This would amount to a major new feature, and unfortunately we're not currently accepting requests which would extend NetBox's scope (see the contributing guide). It's a topic we'll almost certainly revisit at some point in the future once the current backlog of feature requests has been addressed.
