### ISSUE TITLE
API endpoint available-ips not working anymore

### ISSUE THREAD

**Issue by nue-melexis** [digitalocean/netbox#2965]
### Environment
* Python version:  3.4.8
* NetBox version:  2.5.5

### Steps to Reproduce
1. create a prefix
2. make Post request to /api/ipam/prefixes/<PF_PK>/available-ips/

No IP address is returned but an Exception is thrown

Exception:
AttributeError: This QueryDict instance is immutable
Internal Server Error: /api/ipam/prefixes/<PF_PK>/available-ips/

similar to [1334](https://github.com/digitalocean/netbox/issues/1334)

Best Regards

**Comment by DanSheps** [comment]
Please upgrade to the latest version of netbox (2.5.7).  If you still have issues, you may re-open the issue.
