### ISSUE TITLE
Select nodes for topography maps by tag

### ISSUE THREAD

**Issue by sjuxax** [digitalocean/netbox#2970]
### Environment
* Python version: 3.7.2
* NetBox version: tested against latest `develop` (7294f43fa3601a59d4a80fcb35958290ffbfe1f7 at the time of this writing) and the tag for v2.5.7 (ac1e4b8e8f4f320471676cd2f47b61bb42ad0fc4).

### Proposed Functionality
Support topography map node selection by tag with a special annotation.

Already implemented at https://github.com/sjuxax/netbox/tree/topo-by-tag.

### Use Case
Simplify selection of nodes for topography maps. This way, I can select `@tag:power` and `@tag:storage` to easily draw a map of power -> storage, rather than dealing with regex matching on a variety of potentially-disparate naming schemes.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by DanSheps** [comment]
Topography maps are most likely being deprecated in the coming releases and removed after that.

As such it doesn't make sense to develop this feature more.

**Comment by sjuxax** [comment]
Thanks Dan, that's good info. Is there a plan to replace topography maps with something similar? Where can I find a copy of the roadmap such that I have an idea of what's being deprecated and what isn't?
