### ISSUE TITLE
Generate PDF Reports for auditing physically

### ISSUE THREAD

**Issue by Maxkaha** [digitalocean/netbox#2981]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.6

### Proposed Functionality

Adding a button to generate a PDF report of a RACK representation the graphical view (Front / Back) and the list of devices in a table

### Use Case

For example, a NetBox user wants to generate a PDF report from a rack to perform a physical inspection and to detect anomalies as part of an audit, inspection, or intervention

### Database Changes

Probably, it requires a new bouton in the Netbox model.

### External Dependencies

There are no external dependencies

**Comment by jeremystretch** [comment]
Rack elevation renderings are being reworked under #2258.
