### ISSUE TITLE
Changelog for Cable Creation Shows Object as "#None"

### ISSUE THREAD

**Issue by hSaria** [digitalocean/netbox#2984]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.7

### Steps to Reproduce
1. Create a Cable
2. Go to /extras/changelog/
3. The changelog entry there shows `#None` in the Object column

### What did you expect to happen?
As with the short changelog on the main page, the extras/changelog/ page should show the correct object ID for the cable.

### What happened instead?
On the extras/changelog/ page, it will show `#None` in the Object column, instead of `#123` (123 being the ID of the cable). (the changelog on the main page shows the correct ID)

**Comment by DanSheps** [comment]
I haven't dove into this yet, but it appears to be related to using a null label on the cable
