### ISSUE TITLE
IP prefix export only exporting VLAN ID, not VLAN ID + VLAN Name

### ISSUE THREAD

**Issue by GianniSchmidt** [digitalocean/netbox#2989]
### Change Type
[X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

When exporting IP Prefixes in Netbox v2.5.6 the csv file does not include the VLAN Name only the VLAN ID. This is problematic when having the same VLAN IDs with different names. 

Please add an extra field to include the VLAN Name when exporting IP Prefixes.

Thanks!

**Comment by jeremystretch** [comment]
This is intentional behavior for related objects. You can create a custom export template if you want to include the VLAN name as well.
