### ISSUE TITLE
Add powerbox to the community SDK section.

### ISSUE THREAD

**Issue by BatmanAMA** [digitalocean/netbox#2995]
### Change Type
[ X] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Proposed Changes
I develop a PowerShell module for Netbox integration named Powerbox. I've gotten a few versions under my belt and we've decided to use netbox internally as our DCIM/IPAM at my company, so I will be maintaining this for the foreseeable future. I'd like to add it to the "Community" section of the netbox readme as indicated in #2419 to make it easier for windows shops to find it.

**Comment by a31amit** [comment]
@BatmanAMA  Those should be added to here - https://github.com/netbox-community
