### ISSUE TITLE
API Request - id_changed_object_type/action

### ISSUE THREAD

**Issue by zmaster7** [digitalocean/netbox#3001]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.8

### Proposed Functionality
From what I can tell, there is no way to pull possible values for "id_changed_object_type" ("content_type") for the changelog via API (/api/extras/object-changes/), and the "action" field only lists available ids without a description of said id (e.g. 1 = Created, 2 = Updated, 3 = Deleted)

I propose, if possible, to add the available options for "changed_object_type" and/or "action" under "/api/extras/_choices/", or a new "/api/extras/object-changes/_choices/" path with both an id and description/name.

Also, the "content_type" does not show up with a Get request on "/api/extras/object-changes/", so you cannot filter after the fact based on object type.

## Use Case

Currently, in order to determine the id value of the object type for a change log entry, you would have to go to "/extras/changelog/" (not the API), select the object type you want to filter by, and look at the URI for "changed_object_type=#" (or inspect the dropdown field) for possible options.

It would be beneficial to gather the options via API, rather then hard coding the options and having them change.

**Comment by zmaster7** [comment]
It looks like the content type values I would be looking for are pulled via the SQL table: django_content_type.

**Comment by jeremystretch** [comment]
Corrected `action` to use ChoiceField serialization and added its key/value pairs to the `_choices` endpoint.

While the serializer had a `content_type` field defined, it was not being included in serialized output for some reason. I've changed this to `changed_object_type` and it now includes the content type of the changed object. (The content types are not included under the `_choices` endpoint.)

**Comment by zmaster7** [comment]
Thank you for correcting/adding these. However, it appears their may be a bug with the new changed_object_type field, specifically when trying to pull records that are of a "template" object type (power port template and interface template are two I seemed to have narrowed it down to, possibly others). 

When trying to pull these types records from the generic [/api/extras/object-changes/] and directly via [/api/extras/object-changes/id/] I receive the following server error (code 500):

> 
> <!DOCTYPE html>
> <html lang="en">
> 
> <head>
>     <title>Server Error</title>
>     <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
>     <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.min.css">
>     <meta charset="UTF-8">
> </head>
> 
> <body>
>     <div class="container-fluid">
>         <div class="row">
>             <div class="col-md-6 col-md-offset-3">
>                 <div class="panel panel-danger" style="margin-top: 200px">
>                     <div class="panel-heading">
>                         <strong>
>                             <i class="fa fa-warning"></i>
>                             Server Error
>                         </strong>
>                     </div>
>                     <div class="panel-body">
>                         
>                             <p>
>                                 There was a problem with your request. Please contact an administrator.
>                             </p>
>                         
>                         <hr />
>                         <p>
>                             The complete exception is provided below:
>                         </p>
> <pre><strong>&lt;class &#39;utilities.api.SerializerNotFound&#39;&gt;</strong><br />
> Could not determine serializer for dcim.InterfaceTemplate with prefix &#39;Nested&#39;</pre>
>                         <p>
>                             If further assistance is required, please post to the <a href="https://groups.google.com/forum/#!forum/netbox-discuss">NetBox mailing list</a>.
>                         </p>
>                         <div class="text-right">
>                             <a href="/" class="btn btn-primary">Home Page</a>
>                         </div>
>                     </div>
>                 </div>
>             </div>
>         </div>
>     </div>
> </body>
> </html>

Should I open a new issue for this?

**Comment by DanSheps** [comment]
Please open a new issue for this
