### ISSUE TITLE
do not allow removing any permissions from last and only user

### ISSUE THREAD

**Issue by gnowxilef** [digitalocean/netbox#3002]
### Environment
* Python version:  3.6.8
* NetBox version:  2.5.8

### Steps to Reproduce
1. go to admin interface
2. click on admin superuser
3. uncheck "superuser status", "staff", and/or "active"
4. save

### Expected Behavior
error message to show operation is not allowed

### Observed Behavior
operation allowed and locked out of superuser

**Comment by jeremystretch** [comment]
This is a purely operational concern and not something on which NetBox takes a stance. If you need to create a new superuser account, this can be done at the command line: `manage.py createsuperuser`. Please refer to the [Django documentation](https://docs.djangoproject.com/en/2.1/ref/django-admin/#createsuperuser) for details.

**Comment by gnowxilef** [comment]
just to make sure, it is expected behavior that if there was only one user left in netbox and superuser/staff/active status is revoked, to be locked out of the ui?

**Comment by gnowxilef** [comment]
@jeremystretch

**Comment by DanSheps** [comment]
This is expected
