### ISSUE TITLE
RouterOS integration Server Error

### ISSUE THREAD

**Issue by giorgiolago** [digitalocean/netbox#3003]
### Environment
* Python version:  3.5.3
* NetBox version:  v2.5.8

### Steps to Reproduce
On devices> STATUS when clicked displays the following error:
![image](https://user-images.githubusercontent.com/35151682/54329641-41823d00-45f1-11e9-98c9-664203dbce3c.png)
![image](https://user-images.githubusercontent.com/35151682/54333333-df313880-4600-11e9-919f-bbeb2218a58b.png)

Server Error
I have already installed the routeros driver:
root @ netbox: ~ # pip install napalm-ros
Requirement already satisfied: napalm-ros in /usr/local/lib/python3.5/dist-packages (0.4.0)
root @ netbox: ~ # pip install librosuteros
Requirement already satisfied: librosuteros in /usr/local/lib/python3.5/dist-packages (2.2.0)
I did the test using the napalm via cli and it works normal:
root @ netbox: ~ # python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm
>>> from napalm_ros import ros
>>> router_ip = '10 .25.25.201 '
>>> router_port = 8728
>>> router_user = 'netbox'
>>> router_pass = '*******'
>>> driver = napalm.get_network_driver ('ros')
>>> device = driver (hostname = router_ip, username = router_user, password = router_pass, optional_args = {'port': router_port})
>>> print ('Opening ...')
Opening ...
>>> device.open ()
(I.e.
... print (device.is_alive ())
{'is_alive': True}
>>> print (device.get_facts ())
{'vendor': 'MikroTik', 'os_version': '6.44 (stable)', 'uptime': 493056, 'hostname': 'SW-CORE', 'fqdn': '', 'model': 'CRS317- 'Sfp-sfpplus2', 'sfp-sfpplus3', 'sfp-sfpplus4', 'sfp-sfpplus2', 'sfp-sfpplus3', 'sfp-sfpplus2', ' 'sfp-sfpplus5', 'sfp-sfpplus6', 'sfp-sfpplus7', 'sfp-sfpplus8', 'sfp-sfpplus9', 'sfp-sfpplus10', 'sfp-sfpplus11', 'sfp-sfpplus12', 'sfp -sfpplus13 ',' sfp-sfpplus14 ',' sfp-sfpplus15 ',' sfp-sfpplus16 ']}

**Comment by DanSheps** [comment]
This form is only for reproducible bugs. If you need assistance with NetBox installation, or if you have a general question, DO NOT open an  issue. Instead, post to our mailing list:

https://groups.google.com/forum/#!forum/netbox-discuss

Please describe the environment in which you are running NetBox. Be sure that you are running an unmodified instance of the latest stable release before submitting a bug report.
