### ISSUE TITLE
Saving a rack group edit will redirect you into the edited rack group, not to the rack group overview

### ISSUE THREAD

**Issue by goebelmeier** [digitalocean/netbox#3004]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.8

### Steps to Reproduce
1. Open rack group overview (/dcim/rack-groups/)
2. Edit a rack group using yellow edit button (/dcim/rack-groups/<ID>/edit/)
3. Click Update

### Expected Behavior
Return to rack group overview (/dcim/rack-groups/)

### Observed Behavior
Racks of the edited rack group is displayed (/dcim/racks/?group_id=<ID>)

**Comment by DanSheps** [comment]
Duplicate of #2937
