### ISSUE TITLE
Increase tenant name field to greater than 30 chars

### ISSUE THREAD

**Issue by pobk** [digitalocean/netbox#3006]
### Environment
* Python version:  3.7
* NetBox version:  2.5.8

### Proposed Functionality
I've a number of tenants with names > 30 characters. I propose that the name field for tenants be increased to 60 characters

### Use Case
I've a number of locations and tenant objects with names longer than 30 chars.

### Database Changes
Increase max_length on Tenant.name field to 60chars 

### External Dependencies
No dependencies.

**Comment by pobk** [comment]
I've made this minor change to my own fork. Seems a bit minor to do a pull request for?

**Comment by jeremystretch** [comment]
This was addressed in #1817
