### ISSUE TITLE
Other image storage mechanisms; i.e. PostgreSQL BYTEA, etc.

### ISSUE THREAD

**Issue by nward** [digitalocean/netbox#3013]
### Environment
* Python version:  3.6
* NetBox version:  2.5.8

### Proposed Functionality
Image uploads are stored in files. This is OK for many uses, however, makes HA (particularly active/active) complicated. 
A somewhat pluggable image storage system would permit options other than just files - I personally would like PostgreSQL BYTEA storage, but perhaps S3-type storage and others would useful.
Note that PostgreSQL large object storage is not suitable, as this is not supported by existing replication systems.

My intent is to submit this issue for discussion, and if accepted, I will put the work in to add this functionality and submit a PR.

### Use Case
HA will be more achievable, with database or other cluster-able systems able to store images.

### Database Changes
For PostgreSQL storage, either an additional BYTEA "data" column in the ImageAttachment table, or, a new "AttachmentData" table+model with a 1:1 relationship to rows in the ImageAttachment table. A second table would permit different replication, storage, etc. if required by the DBA.
I expect no database changes for other storage systems.

### External Dependencies
For PostgreSQL, no.
Other storage system options, probably - but dependant on the storage system.

**Comment by jeremystretch** [comment]
> Image uploads are stored in files. This is OK for many uses, however, makes HA (particularly active/active) complicated.

There are many solutions available for syncing files among multiple instances. Please see #152 for discussion on why we do not store files in the database.

**Comment by nward** [comment]
Hi,

Thanks for your feedback and reference to that issue.

There is discussion in that thread about an abstraction layer. Would you mind if I submitted a PR implementing that, so we can build other storage mechanisms (like S3, Swift, etc.)?
