### ISSUE TITLE
Add support for Routed Ports

### ISSUE THREAD

**Issue by nicko170** [digitalocean/netbox#302]
The concept of VLANs don't really work for routed switchports.

It would be nice to be able to assign an IP address to a network device interface, as well as assigning the IP address to a racked device.

**Comment by chonty** [comment]
You can add an IP to an interface once the interface has been created on the device by going to Assign IP Address

**Comment by nicko170** [comment]
Yeah, realised this after the fact and reading some more documentation. Closing as the current setup works well.
