### ISSUE TITLE
Filter cables by connected device

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#3023]
### Environment
* Python version:  3.5.6
* NetBox version:  2.5.8

### Proposed Functionality
Extend the Cable filter set to allow filtering by the connected parent object at either end. For example: `/api/dcim/cables/?connected_device=switch42`.

### Use Case
This would allow an operator to easily return a list of all cables connected to a device.

### Database Changes
N/A

### External Dependencies
N/A

**Comment by jbakklund** [comment]
I have been thinking about suggesting a filter allowing the return of a list of all cables connected at a spesific site, rack, or device - adding two more options to your Use Case description, but I am not sure whether or not this justifies adding two more feature requests or expanding this one?
