### ISSUE TITLE
Be able to view port type (front, back, interface) in Cables view

### ISSUE THREAD

**Issue by kitocole** [digitalocean/netbox#3024]
Environment
Python version: 3.5.6
NetBox version: 2.5.8

**Proposed Functionality**
In Devices -> Cables, add a column that shows the port type (front/back/interface) for fast and easy viewing.

**Use Case**
This would allow an operator to easily know which side of each patchpanel a cable is connected to. Even someone new would be able to get this information quickly and accurately. 

Database Changes
N/A

External Dependencies
N/A

**Comment by jeremystretch** [comment]
This is typically going to be conveyed by context (device and component name). Adding columns to state the types explicitly strikes me as overly verbose.

**Comment by jeremystretch** [comment]
Closing this out as there's been no further feedback in the past month.
