### ISSUE TITLE
search for prefixes within a VRF does not work

### ISSUE THREAD

**Issue by JuergenKammer** [digitalocean/netbox#3026]
### Environment
* Python version:  3.6.8
* NetBox version:  2.5.8

### Steps to Reproduce
1. Create VRFs
2. Create Prefixes in different VRFs
3. Select "IPAM"->"Prefixes"
4. Use the search area on the right side, select a VRF from which prefixes should be shown, and select "apply"

### Expected Behavior
5. Prefixes in only the selected VRF(s) are shown

### Observed Behavior
5. Prefixes from all VRFs are shown

### REASON for the error:
- the URL which is called when clicking on "apply" ends in something like:
.../ipam/prefixes/?q=&within_include=&family=&mask_length=&vrf=8&is_pool=

### SOLUTION:
it should be:
../ipam/prefixes/?q=&within_include=&family=&mask_length=&vrf_id=8&is_pool=

I.e. the selected vrf is mapped to its id, but the search looks for a vrf named such, not for the vrf_id with that number.

The URL with "vrf_id=..." results in the expected behavior.

**Comment by DanSheps** [comment]
I am unable to duplicate this on 2.5.8.

Data Load:

```name, rd
VRF1, 1:1
VRF2, 2:2

prefix,vrf,status
192.168.1.0/24,1:1,Active
192.168.1.0/24,2:2,Active```

Query:

IPAM->Prefixes
Filter for VRF1
"Search"

Results:

192.168.1.0/24,1:1,Active

**Comment by JuergenKammer** [comment]
Ah.
I have NOT defined any rd.
Thus, try again, and define your VRFs without an rd.

This also explains why it could creep in, because RDs have not been optional for along time...

**Comment by DanSheps** [comment]
I see...

This is related to the way ModelMultipleChoiceFilter works, because when it comes up against an invalid value, it returns null to the filter (which filters on nothing so you get everything)

**Comment by DanSheps** [comment]
Any form using vrf rd will be affected.
