### ISSUE TITLE
Using just quotes in a device's local context data causes AttributeError

### ISSUE THREAD

**Issue by bdlamprecht** [digitalocean/netbox#3027]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.8

### Steps to Reproduce
1. Edit an existing device
2. In the `Local Config Context Data` field, just add empty quotes (i.e. `""`)
3. Click `Update`.  No validation error is reported.
4. When you then view the `Config Context` tab, the following error occurs:
```
The complete exception is provided below:
<class 'AttributeError'>

'str' object has no attribute 'items'
```

Technically, there is no reason to have just quotes in the `Local Config Context Data` (which is where I assume this error is originating from), there should either:
1. Have a validation error when attempting to save the object
2. Display `None` for bad or invalid data when viewed instead of raise an `AttributeError`

### Expected Behavior
Explained above.

### Observed Behavior
Explained above.

**Comment by jeremystretch** [comment]
The JSON data is stored using `django.contrib.postgres.fields.JSONField`, so I'd rather avoid messing with input validation. I'll tweak our custom `deepmerge()` function to ignore empty data.
