### ISSUE TITLE
In all csv exports that has a color column, add human understandable color name

### ISSUE THREAD

**Issue by Grokzen** [digitalocean/netbox#3029]
### Environment
* Python version: 3.6.x  
* NetBox version: 2.5.x  

### Proposed Functionality
All models that has a color value/field and that has a csv export where color is included should be extended with a new column named `color_name` where the stored color string is matched against the already defined vairable `COLOR_CHOICES`. When exporting, check the string against the choices and if there is a match then use the defined name. If there is no match then either put empty or some default value like `---`.

I can provide all needed code for this feature as we have this implemented in our fork.

### Use Case
Humans do not understand the hex color codes and what it really translates to. 

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
The built-in CSV export will always return the RGB value for a color. If you need the (arbitrary) human-friendly name presented in the UI, you can create a custom export template and call `.get_color_display()`.
