### ISSUE TITLE
Make Devices and VMs columns sortable in Cluster view

### ISSUE THREAD

**Issue by Grokzen** [digitalocean/netbox#3030]
### Environment
* Python version: 3.6.x  
* NetBox version: 2.5.8  

### Proposed Functionality
Make the columns for `Devices` and `VMs` sortable by the number value they represent.

Code ready to be merged if accepted 

https://github.com/digitalocean/netbox/compare/develop...Grokzen:feature/sortable_columns_in_cluster_view

### Use Case
Title and propsed functionality describes it all

### Database Changes
None

### External Dependencies
None

**Comment by DanSheps** [comment]
Duplicate #492

**Comment by Grokzen** [comment]
@DanSheps I do not get why they are duplicate tho? the mentioned ticket only talks about the feature of being able to select what fields of each model that you want to view. This issue only handles columns that is already present that is today unsortable. Making columns choosable will not make them automatically sortable.
