### ISSUE TITLE
[RFE] Shibboleth/SAMLv2 support for user authentication

### ISSUE THREAD

**Issue by jcpunk** [digitalocean/netbox#3035]
### Environment
* Python version:  3.7.2
* NetBox version:  v2.5.9

### Proposed Functionality

Shibboleth/SAMLv2 support for user authentication.

### Use Case

Sites with a good SSO system such as Shibboleth or Keycloak generally prefer to not permit LDAP auth or in general anything that accepts passwords.

### Database Changes

I don't believe anything would be required.

### External Dependencies

I believe there are a few SAML providers for django that could be considered.

**Comment by jeremystretch** [comment]
Please see #1677
