### ISSUE TITLE
Utilisation for rack space

### ISSUE THREAD

**Issue by nicko170** [digitalocean/netbox#304]
Can we see utilisation per rack, just like the IP page please.

Would be good to see how many RU used next to number of devices.

**Comment by bellwood** [comment]
An issue, front and rear faces can have different utilizations.

I have it working locally but how do we want to address this, two columns or a different css template with one colored bar atop another?

**Comment by nicko170** [comment]
@bellwood  I have just merged this into local and it's working a charm! thank you!

I do like how it displays and adds everything up - I think it's a good way to leave it.

**Comment by bellwood** [comment]
@nicko170, @jeremystretch is going to make a modification to prefetch the per-rack consumption as my method is calculating that number on page load

**Comment by bellwood** [comment]
This is now merged in... 

If you have any questions or suggestions please let me know.

Thanks for your help @jeremystretch =)
