### ISSUE TITLE
Deep merge for Config Context Data Set via API

### ISSUE THREAD

**Issue by dnyt84** [digitalocean/netbox#3040]
**Environment**
* Python version:  3.6.3
* NetBox version: 2.5.8

**Proposed Functionality**
Currently when doing an API Patch to /extras/config-contexts/{id}/ it overwrites all existing Data stored.

**Use Case**
A Deep merge feature would make smaller changes easier as I would not necessary need to know what else is stored in the Data set.

I would imagine this could be done via a new API endpoint
/extras/config-contexts-merge/{id}/
or possibly via a flag that would allow a deep merge or overwrite.

We would not want to loose the option to complacently overwrite the current Data Set.
**Database Changes**
None
**External Dependencies**
None

**Comment by jeremystretch** [comment]
This would deviate from the expected behavior of the REST API, which is standard across all objects. You'll need to retrieve the data first and then update accordingly.
