### ISSUE TITLE
Port template (profiles) for set of Interface

### ISSUE THREAD

**Issue by gueryacine** [digitalocean/netbox#3043]
### Environment
* Python version:  3.7.2 
* NetBox version:  Develop

### Proposed Functionality

Functionality :
	A- Add **PortTemplate** on **IPAM** to manage a **VLANs** template and assign them to a Device **Interfaces**
	B- Add **PortTemplate Group** on IPAM to regroup PortTemplates
	C- Assign **PortTemplate Group** to a **Device** then, the interfaces linked with this device can choose a Port Template than to insert VLANs

- In the logic of the code, when we **assign** a **PortTemplate** to the **interface** it will **assign** automatically the **VLANs** from the PortTemplate in the Interface, so like that, the features will not affect the workflows.

- When we assign a **PortTemplate** to an interface, a verification between the **Type** of the PortTemplate ( Ethernet, Virtual , LAG) and the **Form factor** of the interface are done.

- You can see the user interfaces here : [ScreenShot](https://goopics.net/a/u8FmRzr8)

### Use Case
If a user wants to manage device's interfaces with the same configuration of VLANs, he can assign port templates.
When the user modifies a port template, all its interfaces linked will change, then the modification will be quicker.

### Database Changes

1- Add PortTemplateGroup Modal on IPAM with :
- name = CharField
- slug = SlugField
- site = ForeignKey 

2- Add PortTemplate Modal on IPAM with :
- site = ForeignKey
- group = ForeignKey
- name = CharField
- tenant = ForeignKey
- status = PositiveSmallIntegerField
- types = PositiveSmallIntegerField
- mode = PositiveSmallIntegerField
- untagged_vlan = ForeignKey
- tagged_vlans = ManyToManyField
- role = ForeignKey
- description = CharField

3- Modify Interface Modal on DCIM :
- Add port_template = ForeignKey

4- Modify Device Modal on DCIM :

- Add port_template_groups = ManyToManyField

**Comment by jeremystretch** [comment]
Sorry, we're not currently accepting any major feature requests.
