### ISSUE TITLE
Device search limited to non-racked devices when creating a new connection

### ISSUE THREAD

**Issue by shugotek** [digitalocean/netbox#3044]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.9

### Steps to Reproduce
1.Go on device
2.Select "Connect" on one interface
3.Search a device with "Search" function

### Expected Behavior
List all device, and can filter if we write anything

### Observed Behavior
List only non-racked device and finally "search" become unusable

**Comment by DanSheps** [comment]
Caused by rack_id=null not showing all racks.

**Comment by DanSheps** [comment]
Looks like this was added in f6345b9a5d503ed72e9f78a7bb0dc6fbd0347b35 inadvertently

**Comment by candlerb** [comment]
Darn, I just picked this up too :-)  When searching for "wrn", tcpdump shows:

```
GET /api/dcim/devices/?q=wrn&brief=1&limit=50&offset=0&rack_id=null
```

... so it only matches unracked devices.
