### ISSUE TITLE
Config Context with list cause http 500 while getting object by id

### ISSUE THREAD

**Issue by eucariot** [digitalocean/netbox#3045]
### Environment
* Python 3.5.2
* NetBox v2.4.4

### Steps to Reproduce
1. Add new config context which container is list (for example: [{"1": "2"}])
2. Get device by id via API.

### Expected Behavior
Get correct http reply

### Observed Behavior
fails with 500 (need more than 1 value to unpack)

**Comment by jeremystretch** [comment]
Please upgrade to the most recent stable release of NetBox (v2.5.9). You can request to re-open this ticket if the problem remains.
