### ISSUE TITLE
Connecting interface not seaching device from seach mode

### ISSUE THREAD

**Issue by gil-obradors** [digitalocean/netbox#3051]
### Environment
* Python version:    3.5.2
* NetBox version:   2.5.9

### Steps to Reproduce
1.I have a rack, with a server, with interfaces. I select one interface to connect to a switch
2. When I'm searching the device, with select mode, the search isn't working
https://******************/dcim/interfaces/1607/connect/?return_url=/dcim/devices/128/
![image](https://user-images.githubusercontent.com/6016929/55729058-b476ac00-5a15-11e9-80bc-bd9eb2d4461b.png)

3. I have to do select mode like: 
![Captura_2019-04-08_15-48-56](https://user-images.githubusercontent.com/6016929/55729274-20591480-5a16-11e9-87b0-b513cbe78848.png)

### Expected Behavior
Select device faster.
This method was working before ( before update i was working on 2.5.1 )

### Observed Behavior
I need to search by site, rack, device

Thanks

**Comment by DanSheps** [comment]
Duplicate #3044
