### ISSUE TITLE
Cable status filter inoperative

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#3054]
### Environment
* Python version:  3.5.6
* NetBox version:  2.5.10

### Steps to Reproduce
1. Navigate to cables list
2. Filter by status (connected or planned)

### Expected Behavior
Only cables of the selected status will be listed.

### Observed Behavior
No cables are listed, regardless of which status is selected.

**Comment by jbakklund** [comment]
I am not able to reproduce this issue in NetBox 2.5.10 on Python 3.5.3. Filtering by status is working just fine in my case.

**Comment by jeremystretch** [comment]
My mistake. This was definitely broken at one point but now I can't create it. Might have been running a dev version by mistake.
