### ISSUE TITLE
Add a new IP address

### ISSUE THREAD

**Issue by 9sm** [digitalocean/netbox#3058]
### Expected Behavior
When you add an IP from
/ipam/prefixes/1/ip-addresses/

![imagen](https://user-images.githubusercontent.com/25819945/55884219-0e928100-5b7e-11e9-971e-01662a209054.png)

Add a new IP address
and you hit "Create and add Another" does not change the ip is in the same direction. It should change to the next address.

### Observed Behavior

Leave the same ip and empty and duplicate them if you don't notice (you should put the following ip address to continue adding one after another)

It would be good to include the Spanish language even if it is understood very well.
Greetings

**Comment by jeremystretch** [comment]
Covered by #648
