### ISSUE TITLE
Add support for a tenant field on interfaces

### ISSUE THREAD

**Issue by yarnocobussen** [digitalocean/netbox#3059]
### Environment
* Python version:  3.5.6
* NetBox version:  2.5.10

### Proposed Functionality
Adding support for a tenant field on interfaces for the purpose of tenant administration.

### Use Case
A tenant can use an interface on a device owned by another tenant. For purposes such as maintenance announcements, monitoring and (traffic) billing on the tenant level, it is useful to connect ownership information to the interface.

Example:
A datacenter provider is the tenant for an access switch. A customer with rackspace in the datacenter is assigned a (virtual) interface on that switch for internet connectivity. For purposes mentioned earlier, the tenancy of this interface needs to be known.

When reviewing this request, consider that gathering this information via other means is inconsistent and may not always be possible. It would require an indirect relation to something owned by the customer tenant, such as a cable, address within a prefix or a VLAN. Those may not exist and may not be owned by that specific tenant either. Therefore, my conclusion was to request this additional field.

### Database Changes
This field already exists for other objects and I can't think of any conflicts with other functionality in Netbox. I guess it would simply mean adding a single column to the interface table?

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
NetBox only supports tenancy assignment at the device level. Tenancy would be inferred from the device connected to the interface.
