### ISSUE TITLE
Matching interface descriptions are not shown in search results

### ISSUE THREAD

**Issue by raddessi** [digitalocean/netbox#3060]
### Environment
* Python version:  Python 3.6.2 :: Continuum Analytics, Inc.
* NetBox version:  2.5.8

### Proposed Functionality
When searching for text that matches a port descripton, that connection (or device? interface?) should be shown in the search results.

### Use Case
Searching for ports, else it seems to me like good info for a general search if it matches

### Database Changes
None AFAIK

### External Dependencies
None AFAIK

**Comment by jeremystretch** [comment]
Please include steps that someone else can take to recreate the issue.

**Comment by raddessi** [comment]
Sure.

1. Create a device with any interface
1. Set the interface desc to `my-iface-desc`
1. Search in the global search field for `my-iface-desc`

No results are shown for me

**Comment by raddessi** [comment]
OK, we will upgrade as well. Will respond asap.

**Comment by raddessi** [comment]
We upgraded to 2.5.10 and the issue still persists

**Comment by jeremystretch** [comment]
The global search does not match on any device components for performance reasons. We could add them to the device search, but I suspect that would end up returning too much noise when people are looking for specific devices.

**Comment by raddessi** [comment]
Ok, I get that. Unfortunately this would be very useful for us at least so it would be great if we could add some method to do this..

How about adding a checkbox to the filter list for something like `Include results for device components` then? This would have the side effect of making it more clear that these are not included by default.

**Comment by jeremystretch** [comment]
Matching on device component attributes in global search is not warranted/feasible. Closing this out.
