### ISSUE TITLE
Unable to assign vlan on LAG with 802.1Q mode "Tagged all"

### ISSUE THREAD

**Issue by gil-obradors** [digitalocean/netbox#3065]
### Environment
* Python version:   3.5.2
* NetBox version:   2.5.9

### Steps to Reproduce
1.Switch with interfaces, physical and Link aggregations
2. Editing Link aggregations, I set to 802.1Q mode Tagged ALL
3.Save and continue editing is OK
4.802.1Q mode saved correctly
5.Adding VLANS at 802.1Q last frame-box
6.Selecting one or more VLANS (with tagged checkbox)
7.Netbox returns to port info page, without saving tagged vids
![image](https://user-images.githubusercontent.com/6016929/56021440-ba1c0c80-5d09-11e9-82bc-660355738387.png)

### Expected Behavior
Save all assigned vlans for a LAG port from Switch. ( as Tagged all mode)

### Observed Behavior
Not saved.
Tested with access and trunk 802.1Q port mode, and working. Only affects with  LAG Tagged all

At the same time I was configuring other 1g type ports, from other device, and working with Acces, Tagged and Tagged All

**Comment by lampwins** [comment]
This is the expected behavior. Tagged all means all VLANs are tagged, so there is no need to assign specific VLANs.

This is equivalent to saying `members all` on Junos or `allowed vlan all` on Cisco.

**Comment by gil-obradors** [comment]
Ok, thanks!
