### ISSUE TITLE
RelatedObjectDoesNotExist at /dcim/devices/import/child-devices/

### ISSUE THREAD

**Issue by ronniefalcon** [digitalocean/netbox#307]
I am trying to mass import child devices and receiving this error:

> Internal Server Error: /dcim/devices/import/child-devices/
> 
> RelatedObjectDoesNotExist at /dcim/devices/import/child-devices/
> Device has no device_type.

Attached the bug report. Do you need anything else?

[bug_report_15072016.txt](https://github.com/digitalocean/netbox/files/366001/bug_report_15072016.txt)

**Comment by ronniefalcon** [comment]
This is what I was trying to import:

xx011,Renderblade,xxx,i7-2770k,,,xx-CHASSIS-002,3

**Comment by ronniefalcon** [comment]
Ignore me. This is user error.

**Comment by jeremystretch** [comment]
Glad you figured it out, but that exception should never be exposed to the user.

**Comment by ronniefalcon** [comment]
It was emailed to the admin. (myself)

**Comment by jeremystretch** [comment]
Oh, sure, I mean it shouldn't cause a server error. It should instead return a validation error within the import form. Working on a fix right now.

**Comment by ronniefalcon** [comment]
Oh, I see. OK. Cool.
