### ISSUE TITLE
Disassociate OS manufacturer from Hardware manufacturer

### ISSUE THREAD

**Issue by louis-oui** [digitalocean/netbox#3071]
### Environment
Python version: 3.6.6
NetBox version: 2.5.10

### Steps to Reproduce
1. Assign a device to a manufacturer "HP"
2. Create a platform "Linux Core 7" assigned to manufacturer "RedHat"
3. Assign platform "Linux Core 7" to device ("Linux Core 7" appears in the select list)
4. click update

### Expected Behavior
The device is updated with the platform.

### Observed Behavior
Update is rejected. Reason :

"Select a valid choice. That choice is not one of the available choices.
The assigned platform is limited to RedHat device types, but this device's type belongs to HP."

**Comment by jeremystretch** [comment]
This is working as intended. Assigning a platform with a particular manufacturer limits it to devices associated with that manufacturer. In your example, RedHat is not considered a manufacturer.
