### ISSUE TITLE
Front/Back racks mirroring (option)

### ISSUE THREAD

**Issue by deku-m** [digitalocean/netbox#3073]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.8

### Proposed Functionality
When you stand in front of racks it depends on how you number the racks, if for example you start numbering your racks from 1,2,3,4,5 (front) with left hand 1 and on your right hand 5.

**FRONT:**
| 1 | 2 | 3 | 4 | 5 |

When you change position in reality, it would be.

**BACK:**
| 5 | 4 | 3 | 2 | 1 |

**Summary:**
On the  left it is 1 and right is 5. If you change your position to the back of the rack. It is normally reversed. On the right you start with 1 and on the left is 5.
So if you now choose your rack groups and you have like 2 or more racks in it and switch between front/back its not as the view in reality when you are standing in front of it.

A option/button could be to mirror/reflect it. 
So it will rearrange numbering backwards depends on what the start rack view is.

Other option is to use to fields above and state in there what left or right is. and reverse this on changing from fron to back or other way around. All depends on the devices positions.
 
This may sound stupid indead. Hope it makes some sense.

### Use Case
As told above you dont make mistakes when you stand in front of the racks (back/front) because it matches the reality. Some people in netbox look at a site select this and then select a rackgroup which is in our environment a MER or SER with racks in it. If they change there position and look at the racks it doesn't match the overview with numbering when you think of it.

### Database Changes
Dont know this exactly.

### External Dependencies
N/A

**Comment by jeremystretch** [comment]
NetBox does not know how racks are physically ordered on a floor, thus it is not possible to provide this. (We can't assume that they are physically in order by facility ID or name.)
