### ISSUE TITLE
Better support for single host virtualization servers

### ISSUE THREAD

**Issue by kasimon** [digitalocean/netbox#3075]
### Issue type
[X] Feature request 
[ ] Bug report 
[ ] Documentation

### Environment
* Python version: 3.5.3
* NetBox version: 2.5.2

### Proposed Functionality

Currently for single-host virtualization servers (like a one-node vmware setup), the only solution is to create both a device and a cluster object for this server. It would make management of these systems simpler if these two aspects could be combined into one object. Probably the easiest way would be to have a flag for devices that would allow them to host virtual machines directly.

### Use Case

Describing single node virtualisation clusters without having to manage two object (device and cluster).

### Database Changes

Most likely changes in the Device, Cluster and/or Virtual Machine models.

### External Dependencies

None I would be aware of.

**Comment by jeremystretch** [comment]
This was raised during the discussion under #142 and the consensus was to go with the current model.

**Comment by kasimon** [comment]
Sorry, I looked for existing tickets but did not find that one.
