### ISSUE TITLE
Custom fields on more models

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#3083]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.10

### Proposed Functionality

Allow custom fields to be added to:

* dcim_devicerole
* dcim_inventoryitem

### Use Case

On dcim_devicerole: add contact details for responsible team

On dcim_inventoryitem: add purchase date, warranty expiry, usage (e.g. OS disk / data disk)

### Database Changes

None that I can see: `extras_customfield` can link to any `django_content_type`.

### External Dependencies

None

**Comment by jeremystretch** [comment]
Custom fields are only supported on primary models for performance reasons. [The FAQ](https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models) offers more context on this.

**Comment by paravoid** [comment]
Would it perhaps meaningful to use a JSONField (PostgreSQL's jsonb) instead for those cases? It would allow for reading these without extra queries (and thus show up in the listing), as well as searches in them. On the flip side I suppose it would make validation and multiple-choices fields more difficult.

I came across this task while looking on how to add a couple of our custom fields (e.g. ticket number) to inventory items like Juniper linecards.
