### ISSUE TITLE
ERROR when doing GET request for vm with cluster name as filter

### ISSUE THREAD

**Issue by Mellow420** [digitalocean/netbox#3084]
### Environment
* Python version: 3.6.7 
* NetBox version:  2.5.8

### Steps to Reproduce
1. Doing a GET request with the following
![get_vm](https://user-images.githubusercontent.com/22003260/56365594-7d608180-61f1-11e9-8709-7ca16185a74f.png)
2 .Execute

### Expected Behavior

Response code 200 with either a: 
* Empty response if None found
or
* Corresponding VM

### Observed Behavior
 Error code 400 Bad request
![get_vm2](https://user-images.githubusercontent.com/22003260/56365585-746fb000-61f1-11e9-9b91-b90055661ef8.png)

**Comment by jeremystretch** [comment]
This is expected behavior. The request is specifying a cluster which does not exist. There's some discussion in #2819 about whether this error message should be improved, but as it stands currently this is not a bug.
