### ISSUE TITLE
Improve listing of tagged inventory items

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#3086]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.10

### Proposed Functionality

At the moment, when you browse to `/extras/tags/<name>/` and you are looking at tagged Inventory Items, you are only shown the name of the inventory item - but this name only has local significance within a device, so you can't tell the difference between identically-named items.

![image](https://user-images.githubusercontent.com/44789/56367819-04135f80-61ee-11e9-8cf2-06a74e7c2c92.png)

I would like to see the fully qualified name of the inventory item as at least "device name + inventory item name".  (Devices don't necessarily have names, so the device ID could be shown for unnamed devices)

The same applies to Interfaces I think, although I'm not currently tagging any interfaces.

It would be nice to see the site+rack too, for any objects which have those attributes.

### Use Case

Browsing inventory items, e.g. all disks tagged as "os-drive" - being able to see what device each one relates too.

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
The list of tagged items is intentionally brief as it will return all types of objects. If you're interested in seeing inventory items specifically, it's more efficient to filter the inventory items list by tag: `/dcim/inventory-items/?tag=foo`
