### ISSUE TITLE
Rack rank

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#3088]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.10

### Proposed Functionality

Currently, Netbox displays racks sorted left-to-right by name in the elevations view.

I propose adding a "rank" value, so that racks are sorted by rank.  (Similar to: rank value for custom field choices).  That is: you can set the rank to control the sequence of racks displayed.

Alternative: add a right-to-left ordering flag as an attribute of Rack Group.  This is less general-purpose, but would be sufficient for my use case.

### Use Case

In one particular site we have two rows of racks, but they are numbered in opposite directions when facing them:

* S18 S17 S16 S15 S14
* T14 T15 T16 T17 T18

Netbox shows the S row in the "wrong" order.

Workaround: I could rename the racks to 01-S18, 02-S17, 03-S16 etc.

### Database Changes

Add "Rank" column to rack (or reverse ordering flag to Rack Group)

### External Dependencies

None

**Comment by jeremystretch** [comment]
This should be covered by #114. I don't want to add anything now that we might have to undo down the road.
