### ISSUE TITLE
GET from API dvices by filter platform

### ISSUE THREAD

**Issue by VictorPavlushin** [digitalocean/netbox#3098]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.10

### Steps to Reproduce
1. Create platform 'Red Hat Enterprise Linux 7'
2. Assign the platform "Red Hat Enterprise Linux 7" to any device.
3. Through the API, select all devices by the platform filter "Red Hat Enterprise Linux 7"
curl -X GET "http://netbox/api/dcim/devices/?platform=Red%20Hat%20Enterprise%20Linux%207" -H "accept: application/json" -H "X-CSRFToken: ....."

### Expected Behavior
json with a list of devices

### Observed Behavior
Received:
```
{
  "platform": [
    "Select a valid choice. %(value)s is not one of the available choices."
  ]
}
```

### PS
Everything works if passed to `platform` `slug`
If this was the case, then the filter should be `platform_slug` and not just a `platform`

**Comment by jeremystretch** [comment]
The correct request would be `GET /api/dcim/devices/?platform=<slug>`. The available platforms and their slugs are listed at `/api/dcim/platforms/`. If you need further assistance please post to the mailing list.
