### ISSUE TITLE
Broken validation on the new IP-address field "DNS Name"

### ISSUE THREAD

**Issue by phurrelmann** [digitalocean/netbox#3100]
### Environment
* Python version:  3.5.7
* NetBox version:  2.6-dev

### Steps to Reproduce
1. Add the "DNS Name" test.example.com to either an existing or new IP-address 
2. A validation error is shown

### Expected Behavior

The validation to pass and the "DNS Name" is saved

### Observed Behavior

The Validation fails and a validation error is shown:

![2019-04-23_14-14](https://user-images.githubusercontent.com/10113716/56580263-74492900-65d2-11e9-9b33-49587a6f3ee9.png)

**Comment by jeremystretch** [comment]
Please don't open bugs against the `develop-2.6`. It is still in active development.
