### ISSUE TITLE
FieldError on filtering power connections by site

### ISSUE THREAD

**Issue by phurrelmann** [digitalocean/netbox#3101]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6-dev

### Steps to Reproduce
1. Browse to power connections
2. Try to filter by selecting a site from the dropdown

### Expected Behavior

An error is shown:
```python
class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'connected_endpoint' into field. Choices are: _cabled_as_a, _cabled_as_b, _connected_powerfeed, _connected_powerfeed_id, _connected_poweroutlet, _connected_poweroutlet_id, allocated_draw, cable, cable_id, connection_status, description, device, device_id, id, maximum_draw, name, poweroutlets, tagged_items, tags
```

### Observed Behavior

The list of power connections is properly filtered by the site.

**Comment by phurrelmann** [comment]
The same error happens on filter by device name

**Comment by jeremystretch** [comment]
Please don't open bugs against the `develop-2.6` branch. It is still in active development.
