### ISSUE TITLE
Device Inventory Asset Tag not searchable through main search bar

### ISSUE THREAD

**Issue by alexandrebgallant** [digitalocean/netbox#3105]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.10

### Proposed Functionality

Kudos to Netbox!

I created many devices, mainly Cisco switches in netbox. I'm currently doing a revamp of the inventory system also and checking if what's on the floor matches what's in the current inventory.
I added within a device in Netbox some inventory, mainly Stacking Module for the Cisco Switches. Each Stacking Module has an asset tag. I'm trying to search with the main search bar the asset tag of the inventory Item, but nothing is returned. If I search for the device itself, the parent, it returns the device obviously.

### Use Case

Being able to search for every asset tag within Netbox should be a default feature imo. There is even a validation that no asset tag shouldn't be the same, even with Inventory items. 

Thanks for taking time to check if it's possible to do!

**Comment by jeremystretch** [comment]
Device components such as inventory items are not included in the global search view to avoid excessive overhead and extraneous search results. You can search inventory items using the dedicated search at `/dcim/inventory-items/` or via the API at `/api/dcim/inventory-items/?q=foo`.

**Comment by aventrax** [comment]
This is not working for me, https://netbox.local/api/dcim/inventory-items/?q=cespite reports 0 results but I have an item with asset_tag=cespite001. Instead, if with the full name, it reports 1 result.

This is not what is expected as #2166

**Comment by DanSheps** [comment]
@aventrax 

Please open a separate issue for this using the template.  This appears to affect both API and Gui.  It will be a similar fix to #2166 which only dealt with devices I believe

**Comment by aventrax** [comment]
Opened #3788
