### ISSUE TITLE
Allow hiding unused features

### ISSUE THREAD

**Issue by alan412** [digitalocean/netbox#3108]
### Environment
* Python version:  3.7
* NetBox version:  2.5.10

### Proposed Functionality
Allow the user to turn off pieces they aren't using.

### Use Case
We don't use all of the functionality and it would be nice to be able to hide the pieces we on't use.

### Database Changes
It could be a table which what pieces are visible

### External Dependencies
none

**Comment by jeremystretch** [comment]
NetBox v2.6 will allow enforcing view permissions for different object types, but that's as close as we'll get to implementing this. There's a very high degree of integration among the components within NetBox and separating them conditionally would require an unreasonable amount of development effort.

**Comment by alan412** [comment]
I think making it not viewable accomplishes everything I need.   (If I can't see it, then I don't care if it exists or not. :-) )
