### ISSUE TITLE
Cable length cannot exceed 32767 units

### ISSUE THREAD

**Issue by johanreinalda** [digitalocean/netbox#3110]
### Environment
* Python version: 3.6.6  
* NetBox version: 2.5.10  or 2.5.11-dev

Adding cables (thank you, great feature!), the cable length cannot exceed 32767 units.
### Steps to Reproduce
1. add cable with proper connection points
2.set length > 32767

### Expected Behavior
We would like to be able to set lengths up to 120,000 or so. We use Netbox to document our fiber plant for the university. We have some fiber runs to remote sites that are up to 110km (optical long-haul transceivers without amplification). This is a 'would be nice' feature. This can be solved by adding the 'km' unit, but for more details, it would be nice to document the actual length more accurately in "m" (or "ft" for shorter runs around town that still go beyond 32767 ft)

### Observed Behavior
The input is limited to max value 32768 right in html field value. Hence you cannot submit.
&lt;input type="number" name="length" value="32768" min="0" class="form-control" placeholder="Length" id="id_length"&gt;

Note sure if this requires changed in datatypes in the database, but thank you for considering this!

**Comment by jeremystretch** [comment]
Cables are intended to model local connections within a site. Long-haul circuits are better represented as, well, circuits.

FYI the 32767 limit is a characteristic of the database field: 32767 is the maximum value of a signed 16-bit integer. (I'm not clear on why Django forces a signed integer for a PositiveSmallIntegerField; something to do with compatibility across other databases, I believe.)
