### ISSUE TITLE
manage.py rqworker doesn't exist

### ISSUE THREAD

**Issue by Otterian** [digitalocean/netbox#3113]
### Environment
* Python version:  Python 3.5.2
* NetBox version: 2.5.10 (Latest stable)

### Steps to Reproduce
1. Install NetBox using the steps provided in the official documentation

### Expected Behavior
I expected manage.py to have a subcommand to allow the spawning of rqworker.

### Observed Behavior
There is no command available to support the execution done by Supervisor as described in the Supervisor config file for Netbox
`command = python3 /opt/netbox/netbox/netbox/manage.py rqworker
`

### From the Supervisor stderr log:

> Unknown command: 'rqworker'

> Type 'manage.py help' for usage.

### And the output of manage.py:
```
Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[contenttypes]
    remove_stale_contenttypes

[debug_toolbar]
    debugsqlshell

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[drf_yasg]
    generate_swagger

[extras]
    nbshell
    runreport

[rest_framework]
    generateschema

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

[utilities]
    makemigrations
    migrate
```

**Comment by Otterian** [comment]
After tearing my hair out and honestly believing this to be an issue, I managed to get NetBox to work by editing (drumroll) the Nginx config for the site.

As far as I am concerned the steps involving rqworker and Supervisor in the documentation should be deprecated, as I see no use in a command that doesn't exist - since it apparently works without it.

**Comment by lampwins** [comment]
rqworker is a command used in `django-rq` which is only needed when you wish to use Webhooks. `django-rq` is not included in the base NetBox requirements and this means the administrator has to manually pip install it if they wish to use Webhooks. This will change to a base requirement in the upcoming 2.6 release.

If you are not using Webhooks, simply remove the rq worker process from your supervisor config.

**Comment by xelarate86** [comment]
@Otterian , what exactly did you tweak to get this working?

**Comment by Grokzen** [comment]
@xelarate86 @Otterian The following supervisord config works for me locally to run `python manage.py rqworker`

```
[program:rqworker]
command = /usr/bin/python3 /opt/netbox/netbox/manage.py rqworker

; If you want to run more than one worker instance, increase this
numprocs = 3
user = www-data

process_name = rqworker1-%(process_num)s

environment = DJANGO_SETTINGS_MODULE=netbox.settings-prod

; This is the directory from which RQ is ran. Be sure to point this to the
; directory where your source code is importable from
directory = /opt/netbox/netbox/

; RQ requires the TERM signal to perform a warm shutdown. If RQ does not die
; within 10 seconds, supervisor will forcefully kill it
stopsignal = TERM

autostart = true
autorestart = true
```
