### ISSUE TITLE
Error posting to /api/ipam/vlans/

### ISSUE THREAD

**Issue by michaelmfranz** [digitalocean/netbox#3119]
----------------------------------------------------------------------------------------
### Environment
* Python version:  2.7.15rc1
* NetBox version:  2.4.2
----------------------------------------------------------------------------------------
### Steps to Reproduce
1. Set up netbox through the front end to so front end user is able to add VLANS to VLAN groups
2. Make an API call to read in the new VLAN e.g. GET /api/ipam/vlans/1/
3. Make modifications to the returned data to create a new name, new slug and new Id so it is able to be POSTed back to create a new vlan
----------------------------------------------------------------------------------------

New VLAN record created by POSTing to  /api/ipam/vlans/
----------------------------------------------------------------------------------------

an error occurred (see below), the same error occurs through the Swagger UI

TypeError at /api/ipam/vlans/
int() argument must be a string, a bytes-like object or a number, not 'dict'
----------------------------------------------------------------------------------------

**Comment by jeremystretch** [comment]
NetBox v2.4.2 is very old. You'll need to upgrade to the current stable release (v2.5.10) as well as upgrade to Python 3. Please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you need assistance with this.
