### ISSUE TITLE
dcim/interfaces missing vm link in api

### ISSUE THREAD

**Issue by ossark** [digitalocean/netbox#3120]
### Environment
* NetBox version: 2.5.8

### Expected Behavior
I expect to have a link from an interface to its VM exposed in the api, similar to how the link to device is done.

### Observed Behavior
No explicit link from interface to virtual machine is exposed.

**Comment by jeremystretch** [comment]
There is a link:

```
{
    "id": 162989,
    "virtual_machine": {
        "id": 1,
        "url": "https://netbox.internal.digitalocean.com/api/virtualization/virtual-machines/1/",
        "name": "net-util01.nyc3"
    },
    "name": "eth0",
    ...
}
```

Make sure you are using the VM interfaces endpoint at `/api/virtualization/interfaces`, not the DCIM endpoint.

**Comment by ossark** [comment]
Thanks. This works. 

Just out of interest, why separate interfaces on virtual machines from interfaces on devices?

**Comment by jeremystretch** [comment]
The two endpoints utilize slightly different serializers for the same model: The DCIM serializer treats `device` as a required field, and the other uses `virtual_machine`.
