### ISSUE TITLE
Exclude /metrics from LOGIN_REQUIRED

### ISSUE THREAD

**Issue by larsweiler** [digitalocean/netbox#3123]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6-beta1

### Proposed Functionality
With Prometheus Metrics from #3104 enabled and also `LOGIN_REQUIRED` enabled, the URL `/metrics` will redirect to the login page. This merge request will exclude `/metrics` from `LOGIN_REQUIRED` in the same way as `/api` is excluded.

### Use Case
For monitoring with Prometheus a user login on a webpage is not feasible. Prometheus should access the metrics without login.

### Database Changes
None.

### External Dependencies
None.

**Comment by lampwins** [comment]
Closed in #3124
