### ISSUE TITLE
Available power should decrement when downstream devices consume it.

### ISSUE THREAD

**Issue by depereo** [digitalocean/netbox#3143]
### Environment
* Python version: 3.6.6 
* NetBox version:  develop-2.6 

### Proposed Functionality
Currently, when viewing power utilization on a device that is feed-connected, Available Power doesn't change when power ports that consume it are connected.

This requires the user to perform some mental arithmetic to figure out the remaining resource.

As an example, on a single-phase feed allocated 5760W (240v, 30A feed, 80% utilization cap), when a device is attached to an outlet consuming a maximum of 800 watts, the available power  of that feed will always display 5760, instead of reducing by the consumption value of attached power ports.

### Use Case
When planning for new devices, it would be convenient to be able to view the 'remaining' wattage available from a PDU or phase.

Currently:
1. User views PDU or UPS style device (feed-connected, with available outlets)
2. User sees that the available power on the feed is 5760W, but that 3230W are currently allocated.
3. User is trying to plan for a device that consumes 2500W
4. User reaches for a calculator

Proposed:
1. User views PDU or UPS style device (feed-connected, with available outlets)
2. User sees that the available power on the feed is 2530W, because 3230W are currently allocated.
3. User needs to install a device that consumes 2500W, and now understands that this is available.

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
I believe this has been sufficiently addressed in the final v2.6 release.
