### ISSUE TITLE
Field names for Export Templates

### ISSUE THREAD

**Issue by moritz0906** [digitalocean/netbox#3149]
What is the Easiest way to find out which Field names are available for a given Export Template (e.g. dcim -> cable)?

Thanks,
m

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
