### ISSUE TITLE
After deleting primary IP from device, no way to set other predefined IPs as primary

### ISSUE THREAD

**Issue by rekkoner** [digitalocean/netbox#315]
Probably need the ability to edit any/all IPs assigned to a device. At the very least, the option to set/unset IP as primary for device.

I'm on 1.2.1, though it doesn't appear this was fixed in the 1.2.2 release (I'll confirm later this weekend), and I didn't see an open issue about it.

Had no issue updating the DB manually to reflect the change (deleted old primary IP, set old secondary to primary).

**Comment by jeremystretch** [comment]
You can edit the device and select a new primary IP from the list of assigned IPs.
