### ISSUE TITLE
Manufacturer listing to include count of Inventory Items

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#3151]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.12

### Proposed Functionality

In the "Manufacturer's" listing (`/dcim/manufacturers/`), there are columns giving counts of Device Type and Platform.

But I would also like to see a count of Inventory Items which use this Manufacturer.

### Use Case

At the moment, you might see a manufacturer with count of zero Device Type and zero Platform, and assume it can be deleted (unused).  But actually it's being used for inventory items.

Reproducer:

* Create manufacturer Broadcom
* Add a Broadcom NIC as an Inventory Item on a Device
* Return to Manufacturer's list

![image](https://user-images.githubusercontent.com/44789/57197167-bb80d380-6f5b-11e9-9894-c973e9912bee.png)

### Database Changes

None

### External Dependencies

None

**Comment by tb-killa** [comment]
This would be a great extension, because we work a lot with inventory items to make it easier for the tech team to work with targeted information handouts.
