### ISSUE TITLE
Device Filter - Virtual Chassis

### ISSUE THREAD

**Issue by darcynz** [digitalocean/netbox#3154]
## Environment

Python version: 3.6
NetBox version: 2.5.11)

## Proposed Functionality

Would like the ability to filter devices that are virtual chassis.
something like:

http://netbox/api/dcim/devices/?virtual_chassis_id=True

## Use Case

Easier to provide ('brief') list of devices that are virtual chassis via url filter query. This would enable requests/queryies against the Netbox device list from other tools (eg Prime).

## Database Changes

None

## External Dependencies

None

**Comment by jeremystretch** [comment]
This behavior already exists.

**Comment by jeremystretch** [comment]
`virtual_chassis_id` is the filter used to identify a particular virtual chassis. A new filter would need to be introduced if determining virtual chassis membership as a boolean.

**Comment by jeremystretch** [comment]
Adding a boolean filter named `virtual_chassis_member`.
