### ISSUE TITLE
Site location - bulk edit

### ISSUE THREAD

**Issue by darcynz** [digitalocean/netbox#3155]
## Environment

Python version: 3.6
NetBox version: 2.5.11)

## Proposed Functionality

Would like the ability to bulk change devices site location using the edit selected button. 

## Use Case

Whilst this is possible via API having this feature would enable support teams to update devices as changes are made during a project. EG Devices moved from a storeroom or lab to a production site. Or vice versa devices returned to a storeroom.

## Database Changes

None

## External Dependencies

None

**Comment by a31amit** [comment]
This would very helpful rather doing via api. We have many servers which we move between location. Doing bulk changes with site and racks will be helpful.

**Comment by jeremystretch** [comment]
NetBox doesn't do this currently because there's no simple way to move multiple devices to a new rack, which would require specifying a unique position for each device. This would only work for site assignment.

**Comment by dal00** [comment]
You could show a table of the devices where one field would be the rack unit which could be editable. That would make it faster at least.

(Further down the road what would be cool is if we could search for a device and then drag and drop it into its place in a rack all on the same page, one after another, also drag and drop cables between devices would speed things up especially for power and ethernet (this should probably be its own ticket))
