### ISSUE TITLE
Implement RQ Queues Failure Email Reporting

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#3157]
### Environment
* Python version: 3.6 
* NetBox version: 2.5.11 

### Proposed Functionality
Implement some Error Reporting Logic for ``failed`` RQ-Workers.

### Use Case
If you use Webhooks with RQ and they seems to failure you have to go to the Admin-Panel Overview and filter by ``Django RQ`` > ``RQ Queues`` > ``failed`` and check them step by step with ``Trace-View`` what happened.

If this would be reporting by Email like other Errors do them acutually it would be easier to track and change / repair.

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
This can probably be addressed through the [`LOGGING`](https://netbox.readthedocs.io/en/stable/configuration/optional-settings/#logging) parameter (see the linked Django documentation for details). If not, it'll need to be raised with the [django-rq project](https://github.com/rq/django-rq) directly.

**Comment by tb-killa** [comment]
Hi @jeremystretch I build some ``LOGGING`` Code who works great :)

```
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "rq_console": {
            "format": "%(asctime)s %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
       "mail_admins": {
          "level": "ERROR",
          "class": "django.utils.log.AdminEmailHandler",
          "include_html": "True",
        },
        "rq_console": {
            "level": "ERROR",
            "class": "rq.utils.ColorizingStreamHandler",
            "formatter": "rq_console",
            "exclude": ["%(asctime)s"],
        },
    },
    'loggers': {
        "rq.worker": {
            "handlers": ["rq_console","mail_admins"],
            "level": "ERROR"
        },
    }
}
```
Question 1: Does we should publish this ones on the ``docs`` if someone need failure reporting via logging ? Maybe some extra Section for ``Webhook`` ?

Question 2: How does i could format the logging output to be in the same way as the default error email reporting from netbox looks like ? Do you use some sort of special template or another Class ?
