### ISSUE TITLE
Version 1.2.2 - No Extras Menu

### ISSUE THREAD

**Issue by sschwetz** [digitalocean/netbox#316]
I have a version of 1.2.2 that is not showing the extra's menu. I have looked at the documentation that states that this should exist. 

How do I enable it?

Cheers

**Comment by jeremystretch** [comment]
The extras are currently only available under the admin UI. I haven't decided yet how best to support them on the front end.

**Comment by bellwood** [comment]
yet another top level menu is going to pretty much ensure its collapsed most of the time unless users have a wide viewport

someone with a laptop or 19-21" widescreen is going to forced to use the hamburger menu which isnt ideal

with this many navigational categories we may need to use side navigation / off-canvas / drawer to facilitate it better for a larger range of devices and view ports

**Comment by jeremystretch** [comment]
Should we consider switching to a full-screen layout with a lefthand navigation menu? Or keep the existing horizontal menu and condense it to use a multi-level hierarchy?

**Comment by jvolt** [comment]
I vote for keep the existing horizontal menu.

2016-07-19 13:13 GMT-04:00 Jeremy Stretch <notifications@github.com>:

**Comment by bellwood** [comment]
We could go with (Across the top)

-SITES
-DCIM
-IPAM
-CIRCUITS
-SECRETS
-EXTRAS

I'm not in love with "DCIM" and "IPAM", but those are the logical groups.

Maybe "Infrastructure" and "Networking" respectively?

**Comment by Gelob** [comment]
I like the current horizontal navigation and prefer that over a vertical, however I think there is much improvement that could be done overall to the Nav. It takes so many clicks to get to things when you are populating data. What about at least not requiring a click to activate each dropdown menu but just a hover.

Any UI UX experts reading? :)

**Comment by jeremystretch** [comment]
In an effort to clean up the issues backlog, I'm closing all issues labelled as "discussion." If there is interest in continuing this topic, please start a thread on the [NetBox subreddit](https://www.reddit.com/r/netbox). Thanks!
