### ISSUE TITLE
Feature Request - Filter for duplicated prefixes

### ISSUE THREAD

**Issue by Alestor** [digitalocean/netbox#3164]
### Environment
* Python version:  3.4.6
* NetBox version:  2.5.8

### Proposed Functionality
Filter Function to identify duplicated prefixes within an VRF.

### Use Case
Due to an data import or automated creating of prefixes via API, it may come to duplicates. For housekeeping purpes, it would be handy to have a filter funktion for duplicate prefixes to get an quick overview of these.

### Database Changes
Not that I'm aware of.

### External Dependencies
None

**Comment by jeremystretch** [comment]
This is not something that can be implemented as a query filter, however you have the option of writing a custom validation report to look for duplicate prefixes.

**Comment by Alestor** [comment]
ok, thank you for the hint. I'll try to solve it that way.
