### ISSUE TITLE
Anycast IP address multiple interface binding

### ISSUE THREAD

**Issue by njgarfield** [digitalocean/netbox#3167]
### Environment
* Python version:  3.6
* NetBox version:  2.5.12

### Proposed Functionality
This request is to allow a single IP address in a VRF to be bound to multiple devices. The currently functionality does not allow this. If I bind an IP address to a specific device interface and then navigate to another second device interface, when I bind an IP address on that second device interface the IP address is deleted from the first device.

### Use Case
For hundreds of servers running a routing daemon (e.g. FRR/quagga/bird), the same anycast address could be configured on a loopback interface. This is very common in CDN and DNS provider networks.
Similarly for anycast RP in multicast networks.

### Database Changes
Perhaps. not sure.

### External Dependencies
None.

**Comment by DanSheps** [comment]
@njgarfield,

I think what you want actually is "relaxed IP uniqueness enforcement with certain IP address roles".

**Comment by njgarfield** [comment]
@DanSheps is "relaxed IP uniqueness enforcement with certain IP address roles" a current feature.

I have created a new vrf, created IP objects within that VRF, ensured ENFORCE_GLOBAL_UNIQUE is set to false. 

Technically the IP address is unique in the IP address schema, but in the network graph it has multiple bindings.

**Comment by DanSheps** [comment]
No, it is not a current feature, I am suggesting this is what you want.

However, if the object is in a VRF, you need to have the VRF's enforcement of unique addresses also turned off (when you create the VRF)

**Comment by njgarfield** [comment]
@DanSheps yes, Unique IP Space is not enforced on the VRF I created.

And yes, you are suggesting correctly that I believe this is effectively an enhancement request (albeit a  minor one).
Thanks,
Nick

**Comment by jeremystretch** [comment]
> This request is to allow a single IP address in a VRF to be bound to multiple devices.

Each IP address may only be bound to one interface. You'll need to create multiple IP addresses and assign each to its own interface. Note that NetBox does support creating duplicate IPs with the anycast role within a VRF, even if unique enforcement is enabled for the VRF.

> If I bind an IP address to a specific device interface and then navigate to another second device interface, when I bind an IP address on that second device interface the IP address is deleted from the first device.

This does not happen. NetBox will under certain circumstances prevent the creation of a duplicate IP address, but it will not delete an existing IP address.
