### ISSUE TITLE
Missing string substitution in API response - "%(value)s is not one of the available choices"

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#3170]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.12

### Steps to Reproduce

```
curl 'http://localhost/api/ipam/ip-addresses/?vrf=invalid'
```

### Expected Behavior

A meaningful error message is returned

### Observed Behavior

```
{"vrf":["Select a valid choice. %(value)s is not one of the available choices."]}
```

It looks like some string substitution is missing: `%(value)s` is not something that the end user should see.

**Comment by jeremystretch** [comment]
Covered by #2819
