### ISSUE TITLE
Change Cable.status field from Boolean to Int type

### ISSUE THREAD

**Issue by Grokzen** [digitalocean/netbox#3171]
### Proposed Changes

The status field on the Cable model is the only status field across all models that is a Boolean type and not a Integer type. This makes it impossible to extend the status property on this model to include other statuses in the future. And it is not streamlined that all status fields is of the same type and works in the same way.

```
    status = models.BooleanField(
        choices=CONNECTION_STATUS_CHOICES,
        default=CONNECTION_STATUS_CONNECTED
    )

...

# Console/power/interface connection statuses
CONNECTION_STATUS_PLANNED = False
CONNECTION_STATUS_CONNECTED = True
CONNECTION_STATUS_CHOICES = [
    [CONNECTION_STATUS_PLANNED, 'Planned'],
    [CONNECTION_STATUS_CONNECTED, 'Connected'],
]
```

### Justification

Streamline all status fields to the same type and make it possible to extend the status field.

**Comment by yarnocobussen** [comment]
Might be good to comment on this in https://github.com/digitalocean/netbox/issues/3145

**Comment by jeremystretch** [comment]
This would be covered by #3145 if accepted.
