### ISSUE TITLE
Add Fiber-Type "pigtail"

### ISSUE THREAD

**Issue by tb-killa** [digitalocean/netbox#3172]
### Environment
* Python version: 3.6
* NetBox version: 2.5.11

### Proposed Functionality
Extend the ``Fiber Optic`` inside ``netbox/dcim/constants.py``
with one new Value:

- **PIGTAIL**

### Use Case
This allows to reproduce an actual physical situation to be found.:
- front connector is a real connector (LC/LSH/LC/SC/ST)
- back connector is a pigtail which is spliced to a fiber cable

### Database Changes
None.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
Are you splicing a female end directly onto each strand of the cable? Can you provide a photo?

**Comment by tb-killa** [comment]
In our patchpanel we use this confected cable (sample) with open end who would be spliced inside the box to the cable. 
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR8_-7z5SXRm7a29IecLBRTYUk0Hg8yZpLZFuMbBeLTyt9A4wfG

https://www.lxtelecom.com/images/fiber-optics/splice-tray/st-2d24e-24-cores-fiber-optic-splice-tray-longxing-d.jpg

The cable themselves terminate directly on the cable.

**Comment by jeremystretch** [comment]
That's not a panel though. Splicing an end onto a cable just makes a longer cable.

**Comment by tioan** [comment]
![](https://www.elektro4000.de/images/product_images/popup_images/Telegaertner-Spleissbox-bestueckt-TNSB-Be-6LCD-50-OM3-198358_0.jpg)

**Comment by jeremystretch** [comment]
Here is a typical fiber patch panel:

![fiber-patch-panel](https://user-images.githubusercontent.com/13487278/57532086-fb9fd780-7308-11e9-9f4c-344dbf534cb7.jpg)

Each individual strand is terminated to a male type, which connects to a passive female-to-female coupler housed by the panel. These would be modeled as SC rear ports in NetBox. Patches (also male type) are then connected to the outside of the panel.

How does your use case differ from this?

**Comment by tb-killa** [comment]
> Each individual strand is terminated to a male type, **which connects to a passive female-to-female coupler housed by the panel. These would be modeled as SC rear ports in NetBox.** Patches (also male type) are then connected to the outside of the panel.

This looks cool but isn´t a normal situation because the type of patch-panel themselve is variable.

All our Patchpanel are loaded with (TYPE) adapters, ready for splicing, with prepared pigtails (per 2 m).
Splice cassettes are hinged, can be easily folded up.

Each of this individual strand is terminated to a pigtail-splice (inside the casetta) housed by the panel. **These would be modeled as PIGTAIL rear port in NetBox.** where you connect your "Cable" on back to the other side who is the contrary of the first ones.

**Comment by jeremystretch** [comment]
Still not following. Please provide a photo for reference.

**Comment by tb-killa** [comment]
This video show the needing informations
https://youtu.be/rrR6IOZRPb8

**Comment by jeremystretch** [comment]
The video you linked shows exactly what I described.

![screenshot](https://user-images.githubusercontent.com/13487278/57553579-f3fa2600-733c-11e9-91b4-e8c41669d463.png)

> Each individual strand is terminated to a male type, which connects to a passive female-to-female coupler housed by the panel. These would be modeled as SC rear ports in NetBox. Patches (also male type) are then connected to the outside of the panel.

**Comment by tb-killa** [comment]
This is only one example, I will show you another ones.

**Comment by jeremystretch** [comment]
No, this has been resolved. If the model I explained doesn't work for you, NetBox simply does not fit your needs.
