### ISSUE TITLE
Allow rack elevations to flow

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#3175]
### Environment
* Python version:  3.5.2
* NetBox version:  2.5.12

### Proposed Functionality

At the moment, rack elevations are shown as as single horizontal row, with style `overflow-x: scroll` (meaning that if there are more than will fit horizontally, you have to scroll).  The right-hand part is overlaid by the search box.

I would like the racks to "flow": that is, to fill left to right and then move onto the next row left to right, and so on.  At least, I would like it to work like this in print media.

However I think this would work well for visual media too.  The number of racks displayed per row would naturally change as you expand and shrink the screen; and if you zoom out you would be able to see more racks.  On narrow screens like phones you'd no longer have to scroll horizontally.

### Use Case

It would be really helpful to have printed (or PDF) rack elevations from Netbox, but right now I find this extremely difficult.

At the moment I'm having to manually hack the HTML in inspect mode.  I can hide the side bar by setting `display: none`, and I also have to set `col-md-12` on the main container - but no matter how wide I drag my screen, I only see about five and a half racks.  Zooming in and out (command +/-) I see the same number of racks, just larger or smaller.

So then I take screenshots of 5 racks at a time, and paste them into another document. Argh!

### Database Changes

None

### External Dependencies

None

**Comment by jeremystretch** [comment]
No further work is being done on rack elevations until SVG rendering (#2248) has been implemented.
