### ISSUE TITLE
delete all the locations

### ISSUE THREAD

**Issue by ogdionik** [digitalocean/netbox#3178]
Hi,

I noticed that we can't delete all the Locations (Sites) in the same time. They're not the delete all button when we selected all.  We have to did it one by one. And i don't know if it's normal.

kind regards

Netbox v2.5.10

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.
