### ISSUE TITLE
Search failing in circuits

### ISSUE THREAD

**Issue by robbagithub** [digitalocean/netbox#3181]
### Environment
* Python version:   3.6
* NetBox version:  2.5.12 

### Steps to Reproduce
1. Ensure circuit has tenant information against a circuit
![circuit info](https://user-images.githubusercontent.com/22147754/57563317-dd58db00-73df-11e9-83b4-e88b91d45ac1.jpg)

2. search for that tenant name from homepage and fails in all-object search
![search from home](https://user-images.githubusercontent.com/22147754/57563324-e8137000-73df-11e9-8199-26d7845604b3.jpg)

3. Fails to find circuit in circuits page too
![search from circuit 1](https://user-images.githubusercontent.com/22147754/57563330-05483e80-73e0-11e9-8d08-a02209aee806.jpg)

![search from circuit 2](https://user-images.githubusercontent.com/22147754/57563332-07aa9880-73e0-11e9-918d-2fa4026b7ba9.jpg)

### Expected Behavior
1. Expected circuit to be discovered

### Observed Behavior
1. Circuit was not discovered

**Comment by jeremystretch** [comment]
Searching for a tenant by name won't return any related objects, unless the tenant name happens to occur in another field on the object. This is true for all objects with tenancy.

**Comment by robbagithub** [comment]
Quite limited use of tenant then.
