### ISSUE TITLE
Associate combo ports

### ISSUE THREAD

**Issue by s-fu** [digitalocean/netbox#3189]
### Environment
* Python version: 3.6.7
* NetBox version: 2.5.12

### Proposed Functionality
Currently all combo ports are treated independently (#355). For instance, I have a switch with a combo port of RJ45 and SFP+, I have to name them 1/52-RJ45 and 1/52-SFP+. I propose to add a function to associate them and when one of the two ports is connected/disconnected, the status of the other one is changed to disabled/enabled automatically.

### Use Case
* Switch with combo Ethernet ports (RJ45/SFP/SFP+)
* Switch with combo console ports (RJ45/DB9/mini USB)

### Database Changes
Perhaps

### External Dependencies
No

**Comment by jeremystretch** [comment]
The model for this type of interface has already been decided on.
