### ISSUE TITLE
Ability to remove all cables in cable trace except cables between rear ports

### ISSUE THREAD

**Issue by louis-oui** [digitalocean/netbox#3191]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.12

### Proposed Functionality

I would have the ability in GUI to remove all cables (as seen in cable trace) except cables between rear ports :
    - addition of a button to do so beside cable remove in device interface view. To remove cable starting from the interface
    - when deleting a device, add the suggestion to remove all cable starting from their interfaces

**Comment by jeremystretch** [comment]
The logic needed to support this would be unduly cumbersome to maintain, not to mention extremely prone to user error.

> when deleting a device, add the suggestion to remove all cable starting from their interfaces

Connected cables are automatically deleted when a device is deleted.

**Comment by louis-oui** [comment]
I have made a script to do so but it would have been appreciated to have this feature

> not to mention extremely prone to user error.
Why not put a user confirmation in which user see all the cables that are being to be deleted ?

> Connected cables are automatically deleted when a device is deleted.
I meant all the cables up to connected devices. Only connected cables are deleted but if patchpanel (with front port and rear port) is used in the cable path, they won't be deleted
