### ISSUE TITLE
Query string not preserved after redirect to login page

### ISSUE THREAD

**Issue by eliezerlp** [digitalocean/netbox#3192]
### Environment
* Python version:  2.7
* NetBox version:  vx2.3.3

### Steps to Reproduce
1. Ensure you have auth enabled in Netbox
2. Ensure you are logged out.
3. Try opening a URL similar to the following: http://netbox/dcim/devices/add/?status=1&manufacturer=1&name=Device-Name&asset_tag=Asset-Tag
4. You will be redirected to the Login page. Enter your credentials and login.
5. You will be taken to http://netbox/dcim/devices/add/ without any of the originally submitted query string parameters.

### Expected Behavior
Query string parameters should be preserved and passed after logging in.

### Observed Behavior
Query string parameters were discarded and not passed after logging in.

**Comment by tb-killa** [comment]
I don't know if this would be a good point because if this is allowed (if it's a bug it is okay for me) this could bring in strange things because this allowed to be modify object directly without your do after login. 
For this type of manipulation I prefer the API usage.

**Comment by eliezerlp** [comment]
Keep in mind that if you are already logged in prior to opening the link it will work without issue. As such the concern is likely moot.

In my case I am specifically looking to add new objects to Netbox with some fields pre-poulated in the _Add a new device_ page. Not all fields are being populated by the query string, only some. The rest are filled in by the user manually, and then they click on "Create" to actually add the device. In my example (which matches my use case) nothing is automatically being done aside from pre-filling specified fields.

**Comment by DanSheps** [comment]
I don't think we should be accepting this behavior for certain things, however:

https://netbox/dcim/devices/?site=S1

does not work either.

**Comment by jeremystretch** [comment]
> NetBox version: vx2.3.3

I am not able to replicate this on the current stable release of NetBox (v2.5.12). Please upgrade try again.
