### ISSUE TITLE
Custom field for platforms and device_models

### ISSUE THREAD

**Issue by louis-oui** [digitalocean/netbox#3198]
### Environment
* Python version:  3.6.6
* NetBox version:  2.5.12

### Proposed Functionality

I would have the ability add custom fields for platforms and device_models. The use case is to add end-of-live custom fields.

**Comment by jeremystretch** [comment]
Please see [the FAQ](https://github.com/digitalocean/netbox/wiki/Frequently-Asked-Questions#can-we-add-custom-fields-to-more-models) on custom fields.
