### ISSUE TITLE
Power outlets vs Power ports - Clarification?

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#32]
For an APC 0U strip with 24 outlets am I guessing correctly that customer assignable outlets are just that, "Power outlets" and that the "power port" would be the breaker the PDU is interlocked with?

If you have a slack channel or another way you wish to handle general discussion versus opening issues I'm all ears.

Thanks =)

**Comment by jeremystretch** [comment]
That's correct. Power flows from outlets to ports. (And console access is provided _from_ console server ports _to_ console ports.)

We've set up #netbox on irc.freenode.net for discussion. I'll add a not about it to the README.
