### ISSUE TITLE
Add to cable management: flip terminations/interfaces, Disconnected, locations (of ends or cable)

### ISSUE THREAD

**Issue by Jackbennett** [digitalocean/netbox#3201]
### Environment
* image: netboxcommunity/netbox:${VERSION-latest}

### Proposed Functionality
* Support to flip cable connection A/B termination sides
* Support to flip interface A/B Sides
* Support "Disconnected" cable Termination A **or** B
    * Show Status "Disconnected" in addition to "Connected" or "planned"
    * Support Termination Location if disconnected.
* Support inventoried cables? That being disconnected A **and** B
    * Support Setting Termination Locations to the same location if both are disconnected, i.e. storage.
* Support an inventory location that isn't a device.

### Use Case
* Personally I'd like all my cables terminations from one device to all be on the same side to make it easier to read. i.e Termination A being the switch device, Termination B being the server device.

* You can connect a cables B->A but the interface A->B just makes following details a little clunky, See screenshots

* When documenting an existing rack, for some reason I have cables in a switch port, that route to another rack and have been left dangling.
    * Of course change the status to reflect an obvious termination state. As there's no device location.
    * Termination in rack A device xyz would be nice to see it's Disconnected in Rack B

* Given Termination A and B as disconnected, could there be a quick button to set both locations to the same value.
    * Some cables I don't care about, like I'll just reliable any old ethernet patch. But our direct attach SFP+ cables still exist and are always labelled, even in the store room. If both ends are disconnected could I set the cables location to storage shelves inventory item? Something like that.
* Maybe just a location and ID field and add an inventory item list to it, pretty much almost like the device inventory tab.

Related I found #3145 for deprecated cables. I see reversing cables #2700 has come up, but didn't mention the use case when trying to scan through the connection list is a tiny bit less easy and doesn't match interfaces (screenshot):

![image](https://user-images.githubusercontent.com/791134/58109748-182fef80-7be6-11e9-96b3-35e273e29d43.png)

While writing this I've found #2994. Perhaps this is what a can of worms looks like.

![image](https://user-images.githubusercontent.com/791134/58110118-cfc50180-7be6-11e9-94cd-355000036b68.png)

Also note in the screenshot is my cobbled together "Not Connected" Device assigned to no rack but I have to make each interface before assigning the cable.

It seems odd to me to delete a cable, it introduces a chance of re-entering a label incorrectly, It also keeps a history of cable connections attached to the label to identify a bad cable over time.

If I had cables routed through the building floors but not connected to anything, they still exist. If they used to be used for X but no longer, that's useful information.

On reflection does netbox have no concept of patch panels? If I add a panel as a device, labeling the interface, and the link into the switch interface, the "interface connections" page isn't going to abstract away that device to device path? I might as well look at the cables connection page anyway. 

I'm still evaluating/setting up netbox, so I apologize if there's a stupid question.

### Database Changes
* Adds location (Rack) to cable termination
* Add Inventory locations to group inventory items not in a device

I realise this is dangerously close to inventory tracking in general, so maybe not all of these bulleted points are appropriate. I don't think it's too out there or unreasonable.

**Comment by jeremystretch** [comment]
Inventory for cables and other consumables is out of scope for NetBox.

Additionally, please note that the A/B sides are intended to be completely interchangeable: There is no significance to which end is connected to which termination point.
