### ISSUE TITLE
Get serial info from API instead of adding manually

### ISSUE THREAD

**Issue by sri2007** [digitalocean/netbox#3202]
### Environment
* Python version:  3.5.0
* NetBox version:  2.5.12

### Proposed Functionality

The serial info obtained via API (facts) about a device shall update the serial info of the same device, instead of adding this info manually.

### Use Case

At the beginning the serial can be added manually, however if that device goes down or it just get burned, we'll need to replace the device and update that serial again and it can generate some human errors by not updating that or mistyping that info. The best solution will be get that info directly from the remote router so that info can't be damaged in the middle.

**Comment by DanSheps** [comment]
Are you referring to NAPALM?

**Comment by sri2007** [comment]
Yep, that info is receiving from the device using napalm, that’s working great, but it will be interesting when this info can be added automatically to the device without adding that manually.

Saludos
Andres Ocampo D
Enviado desde mi iPhone

El 21 may. 2019, a la(s) 14:34, Daniel Sheppard <notifications@github.com<mailto:notifications@github.com>> escribió:


Are you referring to NAPALM?

**Comment by jeremystretch** [comment]
Dynamic inventory discovery is out of scope for NetBox. The NAPALM proxy is provided only as a convenience.
