### ISSUE TITLE
Select endpoint for interface, which are located in same rack

### ISSUE THREAD

**Issue by mdpuma** [digitalocean/netbox#3203]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.12

### Proposed Functionality
Well, every time when we have to connect interfaces to second device (server and switch with cat5 cable), we have only two options, to choose Site, Rack, Device, Interface type and finally interface name and to choose Device, interface type, interface name. But most of time (by me) cables are connected in same rack, even a rack with patchpanels will have to connect in the same rack.

Will be great to have toggleable option, which may store state (checkbox) per user session on 
Connect page

### Use Case
To speed up work.

### Database Changes
No.

**Comment by jeremystretch** [comment]
> Will be great to have toggleable option, which may store state (checkbox) per user session on
Connect page

This isn't something NetBox can support currently. We may revisit this suggestion at some point in the future after we've established a per-user preferences store.
