### ISSUE TITLE
Change rack ordering in rack list and elevations list

### ISSUE THREAD

**Issue by brusilov** [digitalocean/netbox#3208]
### Environment
* Python version:  3.6.7
* NetBox version:  2.5.12

### Proposed Functionality
Currently, Netbox displays racks sorted like this,
`### NetBox interactive shell (test-office-1)`
`### Python 3.6.7 | Django 2.2.1 | NetBox 2.5.12`
`### lsmodels() will show available models. Use help(<model>) for more info.`
`>>> for i in Rack.objects.filter(site__name='DC2'):`
`...     print(i)`
`...`
`R1/1/7 (R4/1/7)`
`R1/1/9 (R4/1/9)`
`R1/1/8A (R4/1/8A)`

![Racks-NetBox1](https://user-images.githubusercontent.com/30766229/58236501-b4bfd200-7d4b-11e9-8115-1670ac0e3812.png)

Any letter present in the end of the rack name, sends this rack in the bottom of list.
Alternative: use sorting by name:
`### NetBox interactive shell (test-office-1)`
`### Python 3.6.7 | Django 2.2.1 | NetBox 2.5.12`
`### lsmodels() will show available models. Use help(<model>) for more info.`
`>>> for i in Rack.objects.filter(site__name='DC2').order_by('name'):`
`...     print(i)`
`...`
`R1/1/7 (R4/1/7)`
`R1/1/8A (R4/1/8A)`
`R1/1/9 (R4/1/9)`
`>>> `

![Racks-NetBox2](https://user-images.githubusercontent.com/30766229/58236735-357ece00-7d4c-11e9-9389-2e0321bd97eb.png)

### Use Case
Ordiring by name is more human readable.

### Database Changes
None

### External Dependencies
None

**Comment by jeremystretch** [comment]
Racks and several other objects in NetBox employ [NaturalOrderingManager](https://github.com/digitalocean/netbox/blob/develop/netbox/utilities/managers.py#L8) to order names as a human would expect to see them. This presents, for example, Rack 11 from appearing in the list before Rack 2, which would happen if racks were ordered alphabetically by name as you suggest.

Unfortunately you've run into a corner case using dissimilar names, where the natural ordering logic doesn't work well. I'm open to suggestions for improvement to the logic with NaturalOrderingManager, however ordering by `name` only would break ordering for far more common uses cases, so I'm going to close this out.

**Comment by DanSheps** [comment]
Could we allow plugable order Managers per model maybe?

Default would be the regular NaturalOrderingManager and users could extend it as they see fit (or swapping it out for another default one).
