### ISSUE TITLE
Exporting/Importing Virtual Machines without interfaces

### ISSUE THREAD

**Issue by MrDiba** [digitalocean/netbox#3212]
### Environment
* Python version:  3.5.3
* NetBox version:  2.5.12

### Steps to Reproduce

1. When exporting and importing virtual machines the interfaces are not exported/imported.
2. When exporting and importing IP addresses the interfaces of a virtual_machine are exported/imported.
3. Virtual machines has to be imported first be connected to a IP address at import.
4. Trying to import IP addresses fails because the interface of the virtual machine can't be found because it was not exported/imported.

### Expected Behavior
1. Interfaces of virtual machines are being exported and imported so they match up to the interfaces of IP addresses.

and/or

2. The import of IP address needs to be able to add interfaces to existing virtual machines when submitting the import.

### Observed Behavior
When the VM's are imported, the interfaces are not being imported.
When importing the IP addresses with virtual_machine tag and interface_name the import will fail because the virtual machine has no interfaces.

**Comment by jeremystretch** [comment]
The import/export views each only deal with a single model (although you can write custom export templates invoking multiple models). To create virtual machines:

1. Create/import the virtual machines
2. Add interfaces (individually on in bulk)
3. Create/import IP addresses

#1492 is open to address the templatization of virtual machine interfaces (similar to device types).
