### ISSUE TITLE
Howto uninstall Netbox?

### ISSUE THREAD

**Issue by Noiden** [digitalocean/netbox#3214]
### Change Type
[ X ] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

I have tried Netbox on a Linux server but I was choosing another IPAM. So now I wan't to remove all Netbox things, but I can't find how to do that in the documention.

I have manually removed,

- The folder for the website
- pip3 removed gunicorn
- Removed Postgresql database
- Nginx configuration for Netbox

But is there something more?

Thanks.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using one of the templates provided [here](https://github.com/digitalocean/netbox/issues/new/choose). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) instead.

**Comment by Noiden** [comment]
Well, you have an option called "Documention Change" there, so I tought it was for suggestion about the documention... but that was maybe for some other documention then.

I will try in that "mailing list", thanks.

![image](https://user-images.githubusercontent.com/4354201/58353155-0ceef500-7e6e-11e9-9286-83c23b4851fa.png)
