### ISSUE TITLE
Add checkbox "mark as 100% utilized" for prefix

### ISSUE THREAD

**Issue by trrunde** [digitalocean/netbox#3218]
### Environment

* NetBox version:  2.5.12

### Proposed Functionality

Add checkbox to mark a subnet as 100% utilized

### Use Case

As an isp we have subnets allocated to end users. We would like to mark entire subnet as 100% utilized without have to add all the single ipadresses in that subnet.

### Database Changes

not sure

### External Dependencies
none

**Comment by jeremystretch** [comment]
Looks like you want to track utilization of the containing prefix, rather than the individual allocations. Container utilization is based on child prefixes; other prefixes count individual IP addresses.
