### ISSUE TITLE
Cannot create new VLAN

### ISSUE THREAD

**Issue by tcprst** [digitalocean/netbox#322]
Hi all,

First off, thanks everyone for all of your hard work on this awesome tool, and to your company for giving you the time to develop this and allowing you to open it up to the community.

I have an issue when attempting to create a new VLAN on the latest development version v1.2.3-dev after the implementation of VLAN Groups.  I understand that I'm running a dev version, but I just wanted to put this out there in case this is something you haven't seen.  

I've been running the development branch since the release and upgrading every few days.  I updated again this morning to v1.2.3.  A few minutes ago I tried creating a new VLAN and I assigned all of the fields, however, I left VLAN group empty as it doesn't appear to be a required field, and I don't have any VLAN groups created.

When I attempt to submit the form I receive the following error:

```
<type 'exceptions.AttributeError'>

'VLAN' object has no attribute 'vlan_group'
```
If there's any way I can help please let me know.

Thank you and best regards,
tcprst

**Comment by jeremystretch** [comment]
Whoops. This is due a misnamed attribute on VLAN (`vlan_group` should be `group`). Thanks for the report!
