### ISSUE TITLE
Cable trace does not follow correctly

### ISSUE THREAD

**Issue by Pelt10** [digitalocean/netbox#3220]
(Sorry for my bad English...)
### Environment
* Python version:  Python 2.7.13
* NetBox version:  netbox-2.5.12

### Steps to Reproduce
1. Create 2 Devices (Device-A and Device B) : 1 interface on each device
2. Create 2 MUXs*
3. Create 2 Patch Panels**
4. Create 2 duplex-adaptators***
5. Connect output of duplex-adaptator to interfaces of device
6. Connect the 2 inputs of duplex-adaptator to the MUXs : input-1 to Tx-CH28 and input-2 to Rx-CH28
7. Connect the 2 COM ports of the MUXs to Patch Panels : Tx-COM to A1 and Rx-COM to A2
8. Connect the Rear Port of the Patch Panels together
<details>
  <summary>Click to expand</summary>

\* MUX device page
![MUX](https://user-images.githubusercontent.com/7582586/58444670-90704680-80f9-11e9-8a4d-807e10d25ee5.png)

\** Patch Panel device page
![PP](https://user-images.githubusercontent.com/7582586/58444818-19877d80-80fa-11e9-9fc0-ec76fc515267.png)

\*** duplex-adaptator device page
![duplex](https://user-images.githubusercontent.com/7582586/58444884-72efac80-80fa-11e9-8347-16395fa5c603.png)
</details>

### Expected Behavior
The follow path tool on the interface of device connect to other device.

### Observed Behavior
The follow path tool stop to the MUX, on the MON port.

![image](https://user-images.githubusercontent.com/7582586/58445165-daf2c280-80fb-11e9-81b7-f2bf9d7ed6ea.png)

**Comment by DanSheps** [comment]
I am 99.999% sure we cannot support this scenario (yet, who knows in the future) and this is why you are getting the results you are..

Perhaps @lampwins or @jeremystretch can confirm for me

**Comment by fablabo** [comment]
This is similar to #3193. You can't have patchpanels between MUXes without loosing the ability to trace channel to channel.  My workaround for this is creating a 'physical common'  and a 'virtual common' on the MUXes.  Connecting the phycial common to the patchpanels and a virtual common directly between the MUXes.

**Comment by DanSheps** [comment]
Exactly, it is just the way the trace mechanism works
