### ISSUE TITLE
change display to utilization percentages for prefixes 

### ISSUE THREAD

**Issue by krjang** [digitalocean/netbox#3221]
### Environment
* Python version:  3.5.6
* NetBox version:  2.5.12

### Proposed Functionality

It is based on the number of IP addresses generated when calculating Prefixes Utilization.
We propose to calculate Utilization by (Active + Reserved + DHCP) / (Prefixes bandwidth IP quantity) referring to the status of the IP address.

### Use Case
This will help you quickly find out what IP address you are actually using

**Comment by krjang** [comment]
Can Aggregates Take into account IP Addresses not just Prefixes? #237

A similar question.

**Comment by krjang** [comment]
I look for and add similar content.

Can Aggregates Take into account IP Addresses not just Prefixes? #237

**Comment by jeremystretch** [comment]
The current approach has already been discussed and decided on.
