### ISSUE TITLE
Search enhancement

### ISSUE THREAD

**Issue by aamsaleg** [digitalocean/netbox#3229]
* NetBox version: 2.5.11

Hello

In the rack section, when filtering by site, is it possible to present in the rack group drop down menu, only possible selection and not all the possible rack groups of all sites?

In the attached example, Filter is on Equinix PA6 site and drop down menu for rack group let me see Equinix PA6, Equinix PA7 and other sites.

![search-example](https://user-images.githubusercontent.com/25366020/58699900-f4676900-839e-11e9-907b-f5024fc50ee4.png)

Best regards,Alex

**Comment by DanSheps** [comment]
This is a fairly simple change, just need the filter_for.
