### ISSUE TITLE
Add View Permissions

### ISSUE THREAD

**Issue by dinoocch** [digitalocean/netbox#323]
It would be nice to have the ability to add the following functionality to restrict viewing of data

For example User A might not need to view Rack information, and therefore shouldn't have access to it.

(In an ideal world, we could be even more granular, specifying user group permission by global tag for example, #132, but I don't think this is necessary...)

Adding view permissions allows us to expand the users who have access to the Netbox database, which would make the tool much more flexible for us.

**Comment by rekkoner** [comment]
Team permissions would be great, maybe tied to device types or device type tags, such that the ops team sees servers and related info, network team sees network and circuit gear and servers, datacenter server team sees servers and network and storage gear, etc, some/all other groups can see IP address info, etc. Possibly tied to AD group membership?

**Comment by jeremystretch** [comment]
@rekkoner You're describing object-level permissions, which is a different ballgame. NetBox supports group-based permissions and, given its nature as an internal infrastructure tool, I think that's as far as we'll go.

**Comment by fltchr** [comment]
@jeremystretch, would you consider permissions on the site level? We have multiple disparate sites with folks responsible for each. Aside from our infrastructure team, there's really no need for anyone to see the other sites and we definitely don't want them to have the ability to edit the other sites. If we could assign a user to a site and allow them to only see items scoped to their site, that would take care of this. Awesome product by the way. I look forward to seeing it grow.

**Comment by jvolt** [comment]
I would like to strengthen their requests.
We do not trust anyone accessing any site or rack group, because the field team (hallways racks) do not know data center details.

**Comment by Lucho66** [comment]
Hi , This tool is great!! Just one question, once installed ,netbox allows anyone visiting the site see my inventory information. It is possible to authenticate the user first? and add view permissons ?, for example , some user can only the IPAM view

**Comment by fltchr** [comment]
@Lucho66, you may set LOGIN_REQUIRED to TRUE (FALSE by default) to require a login to Netbox before viewing any data. This is in ./netbox/netbox/configuration.py.

**Comment by Lucho66** [comment]
thanks fltchr, this fix my problem

**Comment by jeremystretch** [comment]
Django 2.1 introduced model-level view permissions, which permit access to a type of object (not individual objects) alongside the existing add/change/delete permissions. While enforcing these new view permissions should be fairly straightforward, I'm not sure how we'd handle their initial assignment.

If we begin enforcing but don't automatically assign the view permissions, regular users (non-superusers) won't be able to access any objects until an administrator manually assigns the permissions. However, we also don't want to blindly assign the new permissions to all users, as some organizations prefer to manage permissions at the group level.

A compromise might be to assign view permissions to any user or group with an existing add/change/delete permissions for each model, but that would still potentially block access for some users who should have it.

We could also just ignore the view permissions for the v2.5 release, giving admins time to assign permissions as they see fit before they're enforced. I'm open to suggestions.

**Comment by swerveshot** [comment]
Just to be clear. I just read the link you posted on Django view permissions. This feature only controls read only access? So what about add/change/delete? Or is this not within the scope of this issue?

Either way adopting a permissions model from a framework you are already using this seems only logical to me. It's good that you describe the potential impact so admins of existing installs have some time to make the necessary changes for the 2.6 release. I'm glad you haven't forgotten about this issue since it is over two years old.

**Comment by swerveshot** [comment]
Could it be that what I'm looking for is actually issue #554?

**Comment by DanSheps** [comment]
Add/Change/Delete was already present, this just adds view permissions.

**Comment by swerveshot** [comment]
Okay so this feature just adds the ability to assign view permissions to a particular section of the inventory. Right?

**Comment by DanSheps** [comment]
Correct

**Comment by mdaviesnz** [comment]
@jeremystretch 
In the release notes for 2.5.0 you said:
> Users are encourage to begin assigning view permissions as desired in preparation for their eventual enforcement.

How is this actually done?

**Comment by jeremystretch** [comment]
@mdaviesnz The same as with other permissions. Assign them to groups and/or users through the NetBox admin UI.

**Comment by fnordpojk** [comment]
Today, if the user does not have view permissions for Secrets, that module disappears off the front page.

I assume this will also be the case for the other modules, come 2.6.0?

We are only using the Tenant and IPAM modules and this would significantly lower user confusion for us.

**Comment by candlerb** [comment]
Right now our existing "browsing" users are not member of any group.  In fact we don't have any groups created: there are browsing users, and there are admins.

So as part of the migration, if it finds there are enabled users who are not members of any group, at minimum I think Netbox should create a default "View Everything" group, and assign those users to that group.

If no other groups have any "view" permissions, then either "view" can be added to those existing groups - or all users can be added to the "View Everything" group.

**Comment by jeremystretch** [comment]
It occurs to me that view permissions should be evaluated only if `LOGIN_REQUIRED` is True. Otherwise, it would be impossible to grant any useful access to anonymous users.
