### ISSUE TITLE
Add support for phone patch panels

### ISSUE THREAD

**Issue by Hossy** [digitalocean/netbox#3234]
### Environment
* Python version:  
* NetBox version:  2.5.12

### Proposed Functionality
Add ability to add telephone patch panels and specify that all ports are connected to each other.

### Use Case
To extend https://github.com/digitalocean/netbox/issues/20, I would like to track telephone wiring and how it connects to network devices (like VoIP devices and servers/PCs).

**Comment by DanSheps** [comment]
There is nothing fundamentally different between patch panels for network devices or telephone devices.  VoIP devices, servers, PCs will all use the same connectors.  If you need a new connector (6P2C, 6P4C, 6P6C) that is something that can be looked at and see if the need is there.

Is there something specific that is missing?

In the meantime, the issue request doesn't provide enough information to be actionable so it is going to be closed.

**Comment by Hossy** [comment]
The issue with the current system is that I can only map a single front
port to a single rear port.  That is how a network patch panel works.
However, with a phone patch panel, all ports are connected to each other.
I'm not sure how to represent this is.


On Jun 3, 2019 at 9:06 AM, <Daniel Sheppard <notifications@github.com>>
wrote:

There is nothing fundamentally different between patch panels for network
devices or telephone devices. VoIP devices, servers, PCs will all use the
same connectors. If you need a new connector (6P2C, 6P4C, 6P6C) that is
something that can be looked at and see if the need is there.

Is there something specific that is missing?

In the meantime, the issue request doesn't provide enough information to be
actionable so it is going to be closed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/digitalocean/netbox/issues/3234?email_source=notifications&email_token=AANM5LUZAXEN5UJQX5AOQXLPYUQNXA5CNFSM4HSD5PHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWZQHLQ#issuecomment-498271150>,
or mute the thread

**Comment by DanSheps** [comment]
Netbox isn't meant to model anything beyond network infrastructure.

You may want to take this to the mailing list to see if there is a way to properly model this.
