### ISSUE TITLE
Please re-open #3116

### ISSUE THREAD

**Issue by pm17788** [digitalocean/netbox#3235]
Sadly, the behaviour in #3116 still exists. 

### Environment
* Python version: 3.5.2 
* NetBox version: 2.5.8

### Steps to Reproduce
1. Browse to: https://NetBoxURL/extras/tags, see count of tags (ex: 25)
2. Browse to: https://NetBoxURL/api/extras/tags, see count which is an aggregate of *all* tagged items, rather then the count of distinct tags in NetBox

### Expected Behavior
API count of tags should match the WebUI and the API

### Observed Behavior
API count of tags doesn't match the WebUI, or the behavior of `count` variable on other API endpoints.

**Comment by DanSheps** [comment]
Please upgrade to the latest version of netbox.

**Comment by pm17788** [comment]
@DanSheps: Sadly, NetBox 2.5.13 has the same behavior.
