### ISSUE TITLE
IP Roles

### ISSUE THREAD

**Issue by alexey-kirillov** [digitalocean/netbox#3237]
### Environment

* NetBox version:  2.5.13

### Proposed Functionality

First of all, thanks for NetBox.
I know there is a number of relevant issues, but let's try one more time :)

Router
It's not uncommon to have a single gateway on a subnet, which is a default gw for devices, why should we avoid documenting this? Let's call it a "router" role which means this IP can route ip packets to other networks. This would be an attribute of this IP (ability to route), not devices, which use this IP as a gateway.
In case you have multiple routers, it's up to you to mark them all.

Custom Role
There are cases when you want to highlight another role, such as DNS,DHCP. Someone will require another set of roles. Why don't you implement configurable list of roles? This is done for prefixes,vlans,racks,devices, but not for IPs.

Ok, we can use tags, but:
a) some are not relevant for IPs (list of tags can be reduced by using IP roles instead)
b) tags are not shown in IP list, which makes them hardly usable

And there's no comment field for all IPAM items :(

Thank you.

ps: duplicate of #3109, but verified on newer netbox version.

### Use Case
Use case: you've allocated a prefix for remote office, prepared a router/switch/dns configuration and remote office admin needs all related info on a single page. You could share a link to netbox/ipam/prefixes/NN/ip-addresses as a documentation. 

### Database Changes
required

### External Dependencies
none

**Comment by jeremystretch** [comment]
Both of these topics have already been proposed and rejected.

> Router

Please see my comments on #2953

> Custom Role

Addressed in #2163
