### ISSUE TITLE
Inventory wording of "part number" and "part ID" inconsistency 

### ISSUE THREAD

**Issue by dg2assassin** [digitalocean/netbox#3241]
Environment
-----
- Python version: 3.5.2

- NetBox version: 2.5.13

Found Locations 
-----
1. https://NETBOXURL/dcim/devices/#/inventory/
2. https://NETBOXURL/dcim/inventory-items/#/edit/ 
3. https://NETBOXURL/dcim/inventory-items/

Expected Behavior
-----------------------------
Having the same wording for the part number between different locations

Observed Behavior
------
At location 1, the word choice is "Part Number", were as location 2 and 3 use the wording of "Part ID".

Opinion
-----
I personally would like to see "Part Number" used instead of "Part ID".

**Comment by jeremystretch** [comment]
Changing the table header to "Part ID." "ID" was selected over "number" because many part IDs are alphanumeric.
