### ISSUE TITLE
Edit button for Circuit Type

### ISSUE THREAD

**Issue by wols** [digitalocean/netbox#3243]
### Environment
* Python version:  3.6.5
* NetBox version:  2.5.13

### Proposed Functionality
Add to 'Circuit Types' list the edit buttons please.

### Use Case
The current 'Circuit Types' should also be editable as in other lists.

### Database Changes
no

### External Dependencies
no

**Comment by DanSheps** [comment]
I am showing the circuit types as editable.  Could you provide a more concrete example of why you believe they are not?

**Comment by jeremystretch** [comment]
Circuit types are editable individually. There is no bulk edit operation for these, because the only two fields on this model (name and slug) are unique.

**Comment by wols** [comment]
Current master branch 1a97a1c - logged in as `admin` - no edit buttons shown:

![netbox_circuit-types_list](https://user-images.githubusercontent.com/764167/58978997-5b38b800-87cd-11e9-8042-768e67d505c3.png)

**Comment by jeremystretch** [comment]
@wols What is the version number displayed at the bottom of the page?

**Comment by wols** [comment]
`v2.5.13`

**Comment by jeremystretch** [comment]
So you need to assign permission to edit circuit types to the current user (or group) in the admin UI. This isn't a bug.

**Comment by wols** [comment]
My group is missing only the `admin/*` and `auth/*` rights...

![netbox_group_admin](https://user-images.githubusercontent.com/764167/59095171-1cfbdf80-8918-11e9-96f0-85fe22b7b3f7.png)

...only me...

![netbox_users](https://user-images.githubusercontent.com/764167/59095182-24bb8400-8918-11e9-8157-1a6610655844.png)

... in group:

![netbox_user_me](https://user-images.githubusercontent.com/764167/59095191-284f0b00-8918-11e9-8f2f-dc917e19669f.png)

**Comment by wols** [comment]
Another problem discovered: I can not secrets created by myself read.

**Only with super user right**, I can do **both** - read 'Secrets' AND edit 'Circuit Types'!
