### ISSUE TITLE
Searching for virtual machines or devices omits config context in results (api)

### ISSUE THREAD

**Issue by ossark** [digitalocean/netbox#3244]
### Environment
* NetBox version:  2.5.8

### Steps to Reproduce
1. fetch a virtual machine or device via api (https://netbox/api/virtualization/virtual_machines/?name=your-machine-name)
2. config_context is not present in the results

### Expected Behavior
config_context to be present as it is when one uses the direct id reference to the object like so:
https://netbox/api/virtualization/virtual_machines/<id>/

### Observed Behavior
No config_context was returned in the results

**Comment by lampwins** [comment]
This is expected behavior in 2.5, but this will be changing in 2.6 such that `config_context` will be included by default.
