### ISSUE TITLE
Expand Interface Functionality & Views

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#325]
A few enhancements I imagine for interfaces:
- Select all to delete interfaces in a template for a device type or for interfaces assigned to a device
- Display all options configured in a device type interface template (in the GUI there is no way to check if you defined the interfaces correctly from the device type screen)
- Abbreviated view of description next to an interface on a device

**Comment by jeremystretch** [comment]
Seems like these got completed through various changes in the past. The interface description text is included as a bubble with title text next to the interface icon (when present).

**Comment by ryanmerolle** [comment]
Agreed.
