### ISSUE TITLE
VLAN Pool and ranges support

### ISSUE THREAD

**Issue by eddiehaug** [digitalocean/netbox#3251]
### Proposed Functionality

In the VLAN ID Field, allow to select whether it's a single VLAN or a VLAN Pool.  Using a parent-child relationship, we could have a single VLAN Pool with one or more VLANs or VLAN Ranges.

1) Logic change:  Single or Pool
2) If Single -> Enter ID
3) If Pool -> Enter Pool Name -> Add ranges

### Use Case

In Cisco's SDN solution, ACI, and I guess in other SDN solutions as well, it's possible to create VLAN Pools, which contain either static or dynamic VLAN allocations using VLAN ranges.  Being able to document this would be really helpful in order to properly plan the VLAN allocations, specially in multi-tenant environments.

![chapter-10-vlan-pool](https://user-images.githubusercontent.com/13933303/59159340-891d4580-8ac8-11e9-8782-fd0b5329e30a.png)

### Database Changes

Add Pool Name Column
Add Ranges Column
Create relationship between Pool Names and Ranges

### External Dependencies

None

**Comment by jeremystretch** [comment]
The NetBox data model requires each VLAN to be modeled independently. We are unable to deviate from this model for many reasons.
