### ISSUE TITLE
Add maintenance as device status

### ISSUE THREAD

**Issue by soer7022** [digitalocean/netbox#3252]
### Environment
* Python version:  3.7.3
* NetBox version:  2.5.10

### Proposed Functionality
We want to add a "Maintenance" status to the device status list. At the moment we are using tags to manage the status, which isn't ideal.

### Use Case
When a technician is doing maintenance on a device, the device will be going online and offline multiple times. This will make a monitoring tool think that the device is down or has problems. If we add a maintenance status to netbox the device can be ignored by the monitoring tool, since the monitoring tool can see the status of the device.

### Database Changes
Line 318-336 in `/netbox/netbox/dcim/constants.py` will be extended to:
```
# Device statuses
DEVICE_STATUS_OFFLINE = 0
DEVICE_STATUS_ACTIVE = 1
DEVICE_STATUS_PLANNED = 2
DEVICE_STATUS_STAGED = 3
DEVICE_STATUS_FAILED = 4
DEVICE_STATUS_INVENTORY = 5
DEVICE_STATUS_DECOMMISSIONING = 6
DEVICE_STATUS_MAINTENANCE = 7
DEVICE_STATUS_CHOICES = [
    [DEVICE_STATUS_ACTIVE, 'Active'],
    [DEVICE_STATUS_OFFLINE, 'Offline'],
    [DEVICE_STATUS_PLANNED, 'Planned'],
    [DEVICE_STATUS_STAGED, 'Staged'],
    [DEVICE_STATUS_FAILED, 'Failed'],
    [DEVICE_STATUS_INVENTORY, 'Inventory'],
    [DEVICE_STATUS_DECOMMISSIONING, 'Decommissioning'],
    [DEVICE_STATUS_MAINTENANCE, 'Maintenance']
]
```

### External Dependencies
No external dependencies added.

**Comment by DanSheps** [comment]
Netbox is meant to be a steady state of the current system.

Maintenance is a transient state and shouldn't be documented.

**Comment by lampwins** [comment]
> When a technician is doing maintenance on a device, the device will be going online and offline multiple times.
To clarify, the device would be `offline` in a maintenance window by this description.

I have also accomplished this in the past with a `monitoring` custom field.
