### ISSUE TITLE
Toggle "allow duplicate vlans" in each group

### ISSUE THREAD

**Issue by clinta** [digitalocean/netbox#3257]
### Environment
* Python version:  3.6.7
* NetBox version:  v2.5.14-dev

### Proposed Functionality

Allow each VLAN group to have a boolean indicating whether or not to enforce uniqueness.

### Use Case

I am using VLANs to track VXLAN overlays with a custom field for VXLAN ID. I'd like to create a VLAN group for my VXLANs, but all the VXLANs have the same VLAN ID so this is not possible.

**Comment by clinta** [comment]
Perhaps a VLAN role is more appropriate for this, so maybe this isn't necessary.

**Comment by jeremystretch** [comment]
VLAN groups were added primarily to enforce uniqueness among member VLANs. Role/site assignment and tags can also be used for organization as you note.
