### ISSUE TITLE
Extend cable schema to support assigning a site

### ISSUE THREAD

**Issue by ajknv** [digitalocean/netbox#3260]
### Environment
* Python version:  2.7.5
* NetBox version:  2.5.13

### Proposed Functionality
Would like to have a field that can be used to assign a cable to a site.

### Use Case
Provides a convenient and filterable association for this type of equipment to a site, which in turn enables querying of complete inventories of equipment for a particular site. It seems fair to posit that the vast majority of cables will be entirely internal to a particular site, making this the common use case. And even for cross-site connects, it could conceivably be useful to define the site as "Intersite" or similar for quick filtering on such cables. See also  https://github.com/digitalocean/netbox/issues/3259, which could help solve the problem in a more indirect way, if this RFE cannot convince of the benefit of the (simpler) schema change.

### Database Changes
Add a new field for the cable type.

### External Dependencies
None.

**Comment by jeremystretch** [comment]
Cables are connected to device components, which in turn belong to devices that are assigned to sites. It is not necessary or logical to introduce a direct relationship between the cable and site models.

**Comment by ajknv** [comment]
> It is not necessary or logical to introduce a direct relationship between the cable and site models.

It's not logical (or useful?) for the product to be able to answer a question of the form "This cable can be found at ___<WHERE>___?"
