### ISSUE TITLE
server error trying to view rack

### ISSUE THREAD

**Issue by jcollie** [digitalocean/netbox#3265]
### Environment
* Python version:  3.6.8
* NetBox version:  netbox-5995b64f7d-4rm6f (v2.6-beta1) (netbox community docker)

### Steps to Reproduce
1. click on rack in list

### Expected Behavior
View of rack

### Observed Behavior
 Server Error

A database programming error was detected while processing this request. Common causes include the following:

Database migrations missing - When upgrading to a new NetBox release, the upgrade script must be run to apply any new database migrations. You can run migrations manually by executing python3 manage.py migrate from the command line.

Unsupported PostgreSQL version - Ensure that PostgreSQL version 9.4 or higher is in use. You can check this by connecting to the database using NetBox's credentials and issuing a query for SELECT VERSION().

The complete exception is provided below:

<class 'django.db.utils.ProgrammingError'>

column dcim_powerfeed.max_utilization does not exist
LINE 1: ...owerfeed"."voltage", "dcim_powerfeed"."amperage", "dcim_powe...
                                                             ^

If further assistance is required, please post to the NetBox mailing list.

**Comment by jeremystretch** [comment]
We're not able to troubleshoot development using the community docker image. I can confirm that this is not a problem on the `develo-2.6` branch currently. It's likely that some recent migration changes (i.e. renaming `power_factor` to `max_utilization` on the PowerFeed model) have disrupted your current dev environment. Try rebuilding the database and reapplying the migrations.
