### ISSUE TITLE
Convention on DNS Name Field

### ISSUE THREAD

**Issue by hSaria** [digitalocean/netbox#3278]
### Environment
* Python version: Example: 3.6.8
* NetBox version: Example: 2.6.0

This issue is just to point out the difference in case you missed; if this is intentional, just close the issue :)

### Steps to Reproduce
1. Edit an IP address (e.g. `netbox.example.com/ipam/ip-addresses/1/edit`)

### Expected Behavior
It follows the current field naming convention and says (notice `name` is lower case):
```
DNS name
```

The help text reads:
```
Hostname or FQDN (case-insensitive)
```

### Observed Behavior
Field name is:
```
DNS Name
```

Help text is:
```
Hostname or FQDN (not case-sensitive)
```

**Comment by hSaria** [comment]
Any required changes should be at line 581 in `./netbox/ipam/models.py`.

**Comment by jeremystretch** [comment]
This is fine as-is.
