### ISSUE TITLE
Documentation not update after 2.6 release

### ISSUE THREAD

**Issue by a31amit** [digitalocean/netbox#3280]
### Environment
* Python version:  3.7
* NetBox version:  2.6

### Steps to Reproduce
1. go to https://netbox.readthedocs.io/en/stable/
2.
3.

### Expected Behavior
Should show documentation for 2.6 for latest

### Observed Behavior
its documentation doesn't show any updated for 2.6 include required setting, Prometheus and new changes for power. 
I can see those in git develop branch /docs directory.

**Comment by lampwins** [comment]
Normally when this has happened in the past, the docs fail to build on the RTD side.

I don't have access to check it, so @jeremystretch will have to have a look.

**Comment by jeremystretch** [comment]
I've manually rebuilt the docs, so they should be good for now. Looking at the integrations too. Looks like we were using GitHub services, which have been deprecated, to trigger the rebuild. Working on setting up a webhook for RTD now but I'm not sure whether it's working.

**Comment by jeremystretch** [comment]
Docs are being rebuilt now on changes to both `master` and `develop`.
