### ISSUE TITLE
Conditional custom link inclusion

### ISSUE THREAD

**Issue by ktims** [digitalocean/netbox#3281]
### Environment
* Python version:  3.6.3
* NetBox version:  2.6.0

### Proposed Functionality

A facility to filter which custom links appear on the rendered page based on the object's attributes. I think the best implementation would be to provide an optional field in custom link creation which would accept a Jinja2 'if' clause body (e.g. `obj.primary_ip is not none`). If not included, the link would always be rendered. If included, the link block in the final rendered template would be wrapped in `{% if %} {% endif %}` to avoid rendering and evaluation of the URL and link text templates.

### Use Case

Currently all custom links matching the object's type will be included in the page. In many cases this may not be appropriate (es.g. rack furniture is a 'dcim / device' but wouldn't be in an NMS / devices with no IP information can't have links to their console generated / custom link may depend on an optional custom field), or may lead to rendering oddities due to the chosen template for link text. It also necessitates carefully and obnoxiously adding conditionals on attributes used in the link text and URL templates to ensure that missing attributes don't break rendering of the entire page.

### Database Changes

The CustomLink model would require a new CharField to store the conditional. Defaulting to null or the empty string for existing custom links should have no change in behaviour as the suggested implementation wouldn't filter if the field is empty.

### External Dependencies
None

**Comment by jeremystretch** [comment]
We can tweak the template so that the link is only included if the Jinja2 in the CustomLink's `text` field renders to a non-empty string. So, you could do something like this:

```
{% if obj.device_role.slug == 'foo' %}Clicky{% endif %}
```

And the custom link would be displayed only if the device's role is Foo.
