### ISSUE TITLE
Support Lockers/Cabinets sub-divided racks

### ISSUE THREAD

**Issue by marcoceppi** [digitalocean/netbox#3286]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.0

### Proposed Functionality

Support for sub-dividing Racks into logical partitions. Often time in facilities, especially collocation facilities, racks are split into cabinets / lockers to provide a smaller RU footprint for tenants. When creating a rack, a netbox admin would be able to split a rack into smaller units which have independent rack statuses (planned, active, reserved, available, etc).

### Use Case

We currently offer facilities where we provide 0RU lockers which divide our racks in 1/2 or 1/4 increments. Each locker is assigned to a tenant. We currently do not have a method for modeling this idea of a sub-divided rack in Netbox to review allocated locker spaces, available lockers, and which tenant occupies a spot.

The closes we've gotten is to place a "parent" device in a rack the size of the locker, in this case a 36RU rack split 4 ways at 9RU a piece.

![Selection_696](https://user-images.githubusercontent.com/70613/59956537-f339d100-945e-11e9-8b0c-8f9c2e97baba.png)

The downside to this though, is the rack appears fully allocated when it is in fact empty (in this example)

![Selection_697](https://user-images.githubusercontent.com/70613/59956572-1bc1cb00-945f-11e9-9f46-b83eb1ccd5cf.png)

### Database Changes

May need to support the idea of a Rack Child <=> Parent relationship, or to allow for Devices to be a partition, with it's own unique status.

**Comment by jeremystretch** [comment]
We're not entertaining any major changes to the data model at this time. If you need to model subsections of racks, consider modeling each "locker" as an independent rack, using a RackGroup to organize related lockers.

**Comment by marcoceppi** [comment]
@jeremystretch Can Rack groups encompass Rack Groups? For example we have a unique design where three racks compose a wedge, So Wedge 1 is comprised of a full rack, then two racks divided into four customer zones. So Wedge 1 Rack A has four lockers, and Wedge 1 Rack B has four lockers then Wedge 1 F is our facility rack. These are all a Wedge 1 Rack Group, is is possible to have a Wedge 1 Rack Group then have it contain a rack plus two other rack groups which are the four lockers per rack?

Also, I'm happy to contribute this feature, would it be rejected if I did so?

**Comment by jeremystretch** [comment]
> Can Rack groups encompass Rack Groups?

Not currently, but #1754 has been opened for this.

> Also, I'm happy to contribute this feature, would it be rejected if I did so?

To be clear, this FR has already been rejected. Pull requests can be submitted only for accepted FRs. Of course, you're welcome to help with any of the 100+ other FRs we have in the backlog (including #1754).
