### ISSUE TITLE
Allow assining VLANs to regions

### ISSUE THREAD

**Issue by Alex-Souslik** [digitalocean/netbox#3287]
### Environment
* Python version:  3.7.1
* NetBox version:  2.5.13

### Proposed Functionality
Being able to assign VLANs to entire Regions and not being have to recreate and re-edit them in each site

### Use Case
We usually assign the same major VLANs in entire regions 

### Database Changes
Add Region field in the VLAN object

### External Dependencies
None

**Comment by jeremystretch** [comment]
We're not currently accepting any feature requests that would require substantial changes to the data model. We might re-evaluate this at some point in the future.
