### ISSUE TITLE
Server error when viewing cascaded PDUs

### ISSUE THREAD

**Issue by sleeplessnight2** [digitalocean/netbox#3290]
### Environment
* Python version:  3.6.7-1~18.04
* NetBox version:  2.6.0
### Steps to Reproduce
1.Just open a previous cable Power port connected Device
2.
3.

Generate a Server Error.

The complete exception is provided below:

> **<class 'django.template.base.VariableDoesNotExist'>**
> 
> Failed lookup for key [available_power] in <PowerOutlet: 6>
> 

It seems, that something is forgotten on migrating to 2.6.0

I roll back to the older version (2.5.12), because i can't call some Devices in this Version.

**Comment by jeremystretch** [comment]
Please provide the exact steps someone can take to reproduce the problem.

**Comment by phurrelmann** [comment]
This issue only pops up when one device has power ports _and_ power outlets _and_ is connected with its power port to another power outlet. The use case is to model cascaded power strips:
Strip A (1U) is connected to Feed A via its power port and has 7 power outlets. Strip B (1U) has 7 power outlets and is cascaded with Strip A (e.g. power outlet 7 of Strip A is connected the power port of Strip B).

**Steps to Reproduce**
1. Update a pre Netbox 2.6 that has the described power connection configured
2. Update to Netbox 2.6
3. Try to edit/view the device that has the connected power-port

The following error is shown:

![2019-06-24_09-24](https://user-images.githubusercontent.com/10113716/60023940-1e0e6a00-9697-11e9-8403-fb841ebe73bd.png)
