### ISSUE TITLE
Error on applying filter in circuits

### ISSUE THREAD

**Issue by quentinsch** [digitalocean/netbox#3292]
### Environment
* Python version:  3.5.3
* NetBox version:  2.6.0

If you apply or clear any filter in the circuits section I receive an error message:
<class 'ValueError'>
invalid literal for int() with base 10: ''

![Screenshot 2019-06-24 at 15 25 24](https://user-images.githubusercontent.com/7438854/60022562-5c565a00-9694-11e9-96c7-bdabdbe7a37c.png)

Other filters in other sections work just fine.

### Steps to Reproduce
1. Go to Circuits
2. Apply any filter on the right side
3. An error is shown

### Expected Behavior
I expected to apply the filter that I've chosen.

### Observed Behavior
An error message was shown and an email was sent by NetBox.

**Comment by jeremystretch** [comment]
This issue seems to occur whenever an integer filter field is passed with no value (in this case, `commit_rate`). As a workaround, you can omit `&commit_rate=` from the query parameters in the URL and the request should succeed normally.

I'm still trying to track down what changed to cause this.

**Comment by jeremystretch** [comment]
Found it. This is a bug related to #3038.
