### ISSUE TITLE
API : Add possibility to see ip adress without mask on Device

### ISSUE THREAD

**Issue by shugotek** [digitalocean/netbox#3298]
### Environment
* Python version: 3.6.7
* NetBox version:  2.6.1

### Proposed Functionality
Actually all fields for Ip address on a device return ip/mask.
But for example if I want to add a custom link with Ip Address, I can't because we always have mask in custom link.

do you think it's possible to separate ip address and mask in 2 fields or add reference to ip address only or ?

Regards,
Shugotek

### Use Case
If we want to use a custom link for acces to management we will add a custom link https://{{ obj.primary_ip }}

**Comment by jeremystretch** [comment]
You can reference `{{ obj.primary_ip.address.ip }}` to get the raw host address without its mask. If you need any further assistance, please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
