### ISSUE TITLE
Custom link can create a server error if attribute not exist

### ISSUE THREAD

**Issue by shugotek** [digitalocean/netbox#3299]
### Environment
* Python version:  3.6.7
* NetBox version:  2.6.1

### Steps to Reproduce
1.Create a custom link (for exemple on all device with url https://{{ obj.primary_ip.address.ip }}
2.Go on device who don't have a primary IP, receive error : 

### Expected Behavior
Don't have custom link on device without Primary IP

### Observed Behavior
Error message : 
<class 'jinja2.exceptions.UndefinedError'>

'None' has no attribute 'address'

**Comment by jeremystretch** [comment]
The error is expected: Your template code needs to account for this. Wrap in a conditional statement:

```
{% if device.primary_ip %}https://{{ obj.primary_ip.address.ip }}{% endif %}
```

**Comment by candlerb** [comment]
Related feature request: #3461
