### ISSUE TITLE
Add Services and Images to Device Type

### ISSUE THREAD

**Issue by GreenGorych** [digitalocean/netbox#3301]
### Environment

Python version: 3.6.8
NetBox version: 2.6.1

### Proposed Functionality

Please add the option that allows uploading images and creating Services for device type. This will allow creating same-type device fast.

### Use Case

At the moment we are creating a Smart-UPS SRT 3000 device type in the NetBox, then we will create a device, specifying its type and only after that we will be able to add services and images, though the devices are of the same type.

**Comment by jeremystretch** [comment]
Device types are templates for hardware; services and images don't apply. You might be interested in deployment templates (#1364).
