### ISSUE TITLE
Adding new port type - I/O Port

### ISSUE THREAD

**Issue by GreenGorych** [digitalocean/netbox#3302]
### Environment

Python version: 3.6.8
NetBox version: 2.6.1

### Proposed Functionality

Please add the option that allows creating a I/O type port for connecting various humidity or temperature sensors.

### Use Case

Currently, we are creating a  Smart-UPS SRT 3000 device type in the NetBox and specify it as Parent. We add a Device Bay to it, to which we add a UPS Network Management Card 2 device, which is a Child device.
The UPS Network Management Card 2 has two Universal I/O ports to which humidity or temperature sensors will be connected.
If the Universal I/O is specified as a console port you can connect to it only the port of another device, but not the end device.

Adding a new port type  - I/O Port - would allow connecting humidity or temperature sensors for various devices.

**Comment by jeremystretch** [comment]
These are not considered network interfaces. Modeling these is out of scope for NetBox.
