### ISSUE TITLE
Adding ConfigContext to DeviceType

### ISSUE THREAD

**Issue by sconwayubb** [digitalocean/netbox#3305]
### Environment
* Python version:  3.5.2
* NetBox version:  2.6.1

### Proposed Functionality
Please add ConfigContext to DeviceType that would appear in the nested Device.config_context.

### Use Case
Often there are certain models of equipment that have certain attributes that apply to all devices of that model but not necessarily to all of that Platform/Role. Adding ConfigContext will allow that information to be accessible when querying for a list of Devices without additional API calls to get Custom Field data for each type.

### Database Changes
```
class ConfigContext(models.Model):
...
    device_types = models.ManyToManyField(
        to='dcim.DeviceType',
        related_name='+',
        blank=True
    )
```

### External Dependencies
None.

**Comment by jeremystretch** [comment]
Device types define physical hardware. Config context data has no relevance to them.

**Comment by sconwayubb** [comment]
If that's the case, then can Custom Fields be exposed on the Device list API?
