### ISSUE TITLE
Add Power Port to PDU After Device Creation

### ISSUE THREAD

**Issue by vcsalex** [digitalocean/netbox#336]
Hello,

We have a few Tripp-Lite PDUs that connect to UPSs. I would like to show that devices are connected to the PDU and the PDU is connected to the UPS. I added the PDUs prior realizing that I would need power ports for them. I cannot add a power port after the fact as can be done with other devices.

Is this by design or is this a bug?

**Comment by jeremystretch** [comment]
This is an intentional limitation. We don't currently have a way to represent power circuits being delivered to a rack (see #54) so there's no sense in defining a power port on a PDU. (Otherwise, you could connect PDUs in a circle.) This will be addressed as part of #54.
