### ISSUE TITLE
Trouble upgrading to v1.3.0

### ISSUE THREAD

**Issue by jbro209070** [digitalocean/netbox#338]
Hi guys,

Just want to start out by saying that I love the product, it is already an amazing tool this early in it's release and I look forward to future updates. My particular issue involves upgrading to v1.3.0 from v1.2.1. I followed your upgrading doc and after using the upgrade command it said the upgrade was successful, but when I went back to the web gui, it said it was still on v1.2.1. Using ls /opt/netbox I see three files: netbox, netbox-1.2.1 and netbox-1.3.0. After doing some digging I noticed that the machine was using the netbox-1.2.1 file to run, because when i changed the name netbox-v1.2.1 to netbox-old, I received the bad gateway error on the gui. How can I get the machine to use netbox-v1.3.0? 

Thank you for your time

**Comment by cstueckrath** [comment]
how do you upgrade your installation? Do you git pull into the working directory or do you download a new package to extract and link?
Please provide detailed information regarding your configuration (the files you modified) and your file/folder hierarchy regarding netbox

**Comment by jbro209070** [comment]
I think mistakes were made during the first installation, I rebuilt the machine and im on v1.3.0

Thank you for trying to help, you can close this ticket.
