### ISSUE TITLE
v1.2.1 adding management interfaces and utilizing vlans

### ISSUE THREAD

**Issue by jbro209070** [digitalocean/netbox#339]
After creating a management interface on a device, when I click on the device to look at the interface I just created, it still says that a management interface is not defined. Has anyone encountered this problem? 

Also, is there any way to connect an interface to a vlan?

Thanks!

**Comment by jeremystretch** [comment]
Make sure the "OOB Management" box is checked when creating the management interface. Otherwise, it will appear in the list of regular interfaces to the right.

> Also, is there any way to connect an interface to a vlan?

Not currently.

**Comment by jbro209070** [comment]
Thank you Jeremy, that fixed my issue. 

Do you think that connecting interfaces to vlans may be a future possibility?

**Comment by jeremystretch** [comment]
That might get a little too complicated to be useful. An interface can participate in zero, one, or multiple VLANs. Further, we have a roundabout association between interface and VLAN as interface <- IP address -> prefix -> VLAN, which could potentially conflict with a direct mapping. Would have to give this a lot more thought.

**Comment by jeremystretch** [comment]
Looks like #150 already covers this.
