### ISSUE TITLE
Development instance throwing dot_parser error

### ISSUE THREAD

**Issue by yostie** [digitalocean/netbox#34]
I'm trying to install Netbox on a minimal Centos 7 system and having some issues when I go to launch the development instance.  It launches and says no issues were identified however it throws a 'Couldn't import dot_parser, loading of dot files will not be possible.' error.  When I browse to the website, I get a Bad Request (400) error.

```
sudo ./manage.py runserver 0.0.0.0:8000 --insecure
Performing system checks...

Couldn't import dot_parser, loading of dot files will not be possible.
System check identified no issues (0 silenced).
June 27, 2016 - 19:07:50
Django version 1.9.7, using settings 'netbox.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[27/Jun/2016 19:07:51] "GET / HTTP/1.1" 400 26
[27/Jun/2016 19:07:52] "GET /favicon.ico HTTP/1.1" 400 26
[27/Jun/2016 19:07:53] "GET / HTTP/1.1" 400 26
[27/Jun/2016 19:07:53] "GET /favicon.ico HTTP/1.1" 400 26
```

In order to get to this point, I had to install additional dependencies such as gcc, openssl-devel, and postgresql-devel at which point I got past pip install section.  Not sure what to troubleshoot at this point.

**Comment by yostie** [comment]
I resolved the dot_parser errors by uninstalling pyparsing and reinstalling with pyparsing 1.5.7 but since you said I can ignore it, I will likely upgrade it again.

Now here is the interesting part....if I add the debug statement, the web interface loads correct.  When I take it off, I get the Bad Request (400) error.

**Comment by jeremystretch** [comment]
Could be your `ALLOWED_HOSTS` setting in configuration.py. What do you have it set to?

See if it works in non-debug mode with `ALLOWED_HOSTS = ['*']`.

**Comment by yostie** [comment]
That seems to have worked.  I tried doing '0.0.0.0' not knowing it was looking for an asterik as the wildcard (is that in the docs somewhere?).  I think I also read that section too quickly thinking that was a list of IPs allowed to access the web interface.  That is probably more of a function of nginx though.  Now i have to troubleshoot gettingg nginx to display the page :)
Thanks for the help.  

Get Outlook for iOS




On Mon, Jun 27, 2016 at 3:56 PM -0400, "Jeremy Stretch" <notifications@github.com> wrote:












Could be your ALLOWED_HOSTS setting in configuration.py. What do you have it set to?



See if it works in non-debug mode with ALLOWED_HOSTS = ['*'].
