### ISSUE TITLE
Toggle the display of consumed rack units when creating a device

### ISSUE THREAD

**Issue by jbro209070** [digitalocean/netbox#340]
Is there anyway to only show the available positions in the rack position drop down list instead of showing the full list whether it is occupied or not? I think that would be really useful.

**Comment by jeremystretch** [comment]
Personally, I like having the occupied units included in the list, as it provides something of a sanity check. But we'll see what others say.

**Comment by bellwood** [comment]
I think this would probably be best addressed with a user definable configuration.

I'm going to presume we'll have many things that work for some and not for others and if they are somewhat trivial to implement (see #285) and don't creep the scope badly it would be beneficial for the user base to have them.

**Comment by Gelob** [comment]
Having mentioned this on IRC I understand the reasoning of the way it is but at the same time would like to have the option.

**Comment by mjclancy83** [comment]
Maybe just a format change (e.g. bold) on currently occupied RUs?  Or some sort of flag character or icon?

**Comment by jeremystretch** [comment]
@mjclancy83 Unfortunately, there's not much we can do as far as styling the stock pull-down widget. We'd have to replace it with a custom widget, which probably isn't worth the effort.

**Comment by bellwood** [comment]
I will note on Mac's dropdown styles (background colors) are not visible so text styling is really the only option if we're to change the look.

I would honestly make a setting to hide consumed U's when adding a device to a rack and let the administrator decide but ultimately it may need to be a user level setting (what works for the admin doesn't always work for the end-user)

**Comment by jeremystretch** [comment]
Closing this out as I don't see any progress being made on it. However, we're sure to implement something along this vein in a (distant) future release once the web UI becomes API-driven.
