### ISSUE TITLE
"Select all" should only select all objects on the current page

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#345]
Currently, checking the "select all" checkbox at the top of an object list will select _all_ objects in the query, rather than just the ones displayed on the current page. This is not intuitive.

Checking the "select all" checkbox should select all objects on the page, and present an additional widget to allow the user to optionally select all objects in the query. Here's how Gmail does it as an example:

![gmail_select_all](https://cloud.githubusercontent.com/assets/13487278/16993303/beb9b422-4e70-11e6-9e26-0959538cb128.png)

**Comment by filiperegis** [comment]
Please, this should be prioritized. I just accidentaly changed 310 circuit speeds, but intended to change only 50. There is a way to undo?

**Comment by LBegnaud** [comment]
Not sure if there's a way to undo, but fyi if you hit select all, then deselect one item it will then only have items on the current page selected.
