### ISSUE TITLE
Full Layer 1 path maps and internal circuit id's

### ISSUE THREAD

**Issue by jtdub** [digitalocean/netbox#349]
For the purpose of having complete visibility of a cable path, I propose that we treat all cross-connects as circuits, assigning them with internal circuit ID's and identifying the connection from each source port on a patch panel to each destination port on a patch panel.

For example:

```
pp1_port1 <-> pp2_port2
```

Then when you establish a cross-connect between two devices, you can map out the complete path of the cable and assign the 'circuit' with a circuit ID.

```
CID: INT000001

spine1_port1 <-> pp1_port1 <-> pp2_port1 <-> leaf1_port1
```

You could also define the cross-connect role, which would also serve in assisting in deploying device configs, using netbox as a source of truth, an external system to pull the variables, compile templated configs, and push configs to a device.

**Comment by jeremystretch** [comment]
Seems like this is covered by #20 and/or #49.
