### ISSUE TITLE
[1.3.0] Fails on specific environments

### ISSUE THREAD

**Issue by dowlingw** [digitalocean/netbox#354]
Following upgrade from version 1.2.2 to 1.3.0 our netbox installation stops working with the following error:

```
NoReverseMatch at /
Reverse for 'vlangroup_list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```

Django Version: 1.9.7
Python Version: 2.7.3

Full error available here:
https://gist.github.com/dowlingw/afc9a7f56e27f6be3f1085f3f30df02d

**Comment by dowlingw** [comment]
Actually, I've attempted a fresh installation of 1.3.0 and am also receiving this error.

**Comment by jeremystretch** [comment]
I just installed 1.3.0 on a new Ubuntu 16.04 installation following the documentation and did not encounter any problems. It looks like you might be have updated the code base without restarting the WSGI service.

Do you see this error when you connect to NetBox directly (using the following command)?

```
./manage.py runserver 0.0.0.0:8000 --insecure
```
