### ISSUE TITLE
Combo ports

### ISSUE THREAD

**Issue by andreas1o** [digitalocean/netbox#355]
Hi !Would it be possible to add combo ports as a feature request to the interface selection for a device ? 
Some ports are either SFP or Copper.

thanks for a great  project.

**Comment by jeremystretch** [comment]
The data model requires each interface to have exactly one form factor. You can edit an interface and toggle its form factor based on which of the two physical ports is in use. Most people tend to stick with one or the other anyway. Trying to support multiple form factors would add undue complexity.

**Comment by ryanmerolle** [comment]
Yea this came up on irc.  The best way to handle it is via the SFP 1G form factor.  Technically that can do copper or fiber sfps.

**Comment by andreas1o** [comment]
Ok thanks sounds resonable.
