### ISSUE TITLE
Add support for reserving rack space

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#36]
Currently, space within a rack can only be either unoccupied or occupied (having been consumed by a device). It would be helpful to allow users to reserve arbitrary swaths of rack space with a comment indicating its intended use. This could also be used to designate unallocated rack space (for instance, because the rack has been damaged).

**Comment by colawebrunner** [comment]
Think this would be a great feature, as working for an MSP we want to be able to reserve racks/rack space for potential customers.

**Comment by MaXwellFalstein** [comment]
I think this feature should be worked on sooner than some of the other "issues" raised.

Support for rack space reservation will enable blanking and adding of future network provisions in rack or in dedicated network racks.
