### ISSUE TITLE
Pagination Changes

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#362]
The default pagination provided by Django is very basic. I find it very annoying to have to click through pages to view all my data sometimes when I could just have a dropdown to change the items per page. I understand this is configurable globally in settings but this should be session based.

Given we are going to be using jQuery at some point this should be doable. There is a django application we could install that should do this (haven't tested it) but I also know we don't want more dependencies.

https://github.com/alsoicode/pagination

**Comment by jeremystretch** [comment]
This would be trivial to implement; no additional app necessary. But why not just set your default page length higher?

**Comment by Gelob** [comment]
Setting the default page length changes it for all pages and other users may not want the same page length. There may be cases that I'm searching for information and clicking a few pages is fine, but when I'm comparing data and importing/exporting I want to see all of the data on 1 page.
