### ISSUE TITLE
VLAN description

### ISSUE THREAD

**Issue by andreas1o** [digitalocean/netbox#363]
Hi would it be possible to add a description field to vlan ? 
In some switches you tend to use vlanmanes more than tags so name becomes very significant and vlanid is something you configure once. 
Then a description added to the vlan would make sense  ?

**Comment by jeremystretch** [comment]
I think a description field would be redundant since VLANs already have a name. There isn't usually much other context that needs to be provided around a VLAN. Can you provide a specific use case where a description would provide additional information not conveyed by the name?

**Comment by ryanmerolle** [comment]
I think @andreas1o is just asking for this given some platforms (JUNOS) allow for their config of a vlanid, name, and description separately.

**Comment by andreas1o** [comment]
yes exactly vlanname is usually limited in the lenght but descriptions are not.
For instans vlan id 100 name FINANCIALSERVICE - description Financial Service EastCoast 
vlan id 100 name FINANCIALSERVICE - description Financial Service Westcoast.

**Comment by jeremystretch** [comment]
Added a description to the VLAN model in d241cce.
