### ISSUE TITLE
Default user and password

### ISSUE THREAD

**Issue by s3cur3n3t** [digitalocean/netbox#364]
Hello guys!

Installed netbox. But can't login what is the default user and password and where can I define it inside netbox.

Thanks in advance.

**Comment by jallakim** [comment]
Did you follow the [installation instructions](https://github.com/digitalocean/netbox/blob/develop/docs/installation/netbox.md)?

Specifically the part where it says there are no default user/password, and where you have to create the user "manually"?

```
# ./manage.py createsuperuser
Username: admin
Email address: admin@example.com
Password: 
Password (again): 
Superuser created successfully.
```

**Comment by s3cur3n3t** [comment]
Thank you very much for your help.

Done. All working as expected for now ;) ;)
