### ISSUE TITLE
New form factor interface types

### ISSUE THREAD

**Issue by alarido** [digitalocean/netbox#365]
Hello,

It would be nice to have Coaxial and a way to differentiate fiber type, single-mode and multi-mode.

Thanks in advance.

**Comment by jeremystretch** [comment]
Duplicate of #361. Please search for existing issues before creating a new one.

**Comment by alarido** [comment]
I did, but none of this words showed any matches:
coaxial
smc
sma
tmc
...

Also I tried without acronym (that was my mistake) single and multi mode, also without matches:
single-mode
multi-mode
