### ISSUE TITLE
Fix display of Utilisation when above 9% in Aggregates

### ISSUE THREAD

**Issue by JosephRPalmer** [digitalocean/netbox#366]
Utilisation percentage incorrectly displayed above 9% in Aggregates. 

![screen shot 2016-07-22 at 13 45 10](https://cloud.githubusercontent.com/assets/2736840/17057553/9f8cd9aa-5012-11e6-9d1e-3bb2d33f4d44.png)

**Comment by jeremystretch** [comment]
Please upgrade to the latest release, v1.3.1.
