### ISSUE TITLE
Adding child prefixes, why does it auto populate "available". Can this be toggled off?

### ISSUE THREAD

**Issue by ronniefalcon** [digitalocean/netbox#367]
Hi,
Adding child prefixes to a /16 prefix, a number of 'available' subnets appear. 

Why is this? Can this behaviour be disabled? It makes the presentation of the child prefixes messy, IMO.

**Comment by jeremystretch** [comment]
The "available" lines show unused space. This makes it easier to find gaps between child prefixes. It cannot be toggled off.

**Comment by ronniefalcon** [comment]
OK.. Thanks.  My next question was about 'expanding' the prefix but I see that tick box.
