### ISSUE TITLE
v1.3.1 Utilization percentages are showing up weird

### ISSUE THREAD

**Issue by jbro209070** [digitalocean/netbox#368]
![v1 3 1 utilization](https://cloud.githubusercontent.com/assets/20539182/17059436/b673a270-4fea-11e6-851c-2d946c4f33a3.png)

**Comment by jeremystretch** [comment]
The first rack in your list says it has 12 devices installed occupying 117U of space. What device types have you defined for these and what is the `u_height` of each?

**Comment by jbro209070** [comment]
I found the problem, I have two 208 PDUs that are on both sides of the multiple racks. The 208s are considered unracked equipment in netbox so I didn't think putting their true height would matter. Since they span the length of the 44U rack, I labeled them as 44U in device types, which im assuming, was calculated into the rack utilization percentage. 

Which brings me to a question, should unracked equipment effect utilization of rack space?

**Comment by jeremystretch** [comment]
Each device type should have its height to the number of rack Us which it occupies. Vertical PDUs do not consume an rack Us, so their height should be 0. Every device with a U height of 1 or more counts against the rack's utilization.

**Comment by jbro209070** [comment]
Say I were to take down a cisco 1921 router (1U) and put it on a shelf. Unless I were to change it to 0U in device types, it would still say that im utilizing rack space even when unracked. When I want to put it back on the shelf, I would have to go into device types and change it back to 1U again. Is there a way to set utilization to only pull percentage off devices that are "racked" and ignore "unracked" device U height?
