### ISSUE TITLE
Interface Groups and Port Grouping

### ISSUE THREAD

**Issue by jbro209070** [digitalocean/netbox#373]
I would like to see an option to throw a specific selection of interfaces in an interface group when looking at the device interfaces. Some devices, such as a Nexus 7706, can have up to 70 ports total (48 1/10 (SFP+) ports and 24 40GE (QSFP+) ports). As for the functionality, instead of listing all 48 1/10 SFP+ interfaces (Ethernet 1/1 - Ethernet 1/48) spanning for miles down the page, you would see an interface group such as "Line Card 1 Interface Group" or "Line Card 2 Port Group". Each interface group would be a link to a page that shows all of the interfaces or ports associated with that group only like how the rack groups are set up. This would be a very useful feature for work places that use VDCs to group a selection of ports using an adapter cable, connecting to one port. (Example: Cisco 9396PX 1/10 GE ports eth 1/1-1/5 connected to Cisco 7706 40 GE port 2/1.) We can then create interfaces 2/1/1-2/1/5 to simulate the virtual ports, label them as virtual interfaces, and group them to the 40 GE port 2/1.

Creating and connecting interfaces would work exactly the same, with the only difference being that they can be grouped together and displayed as a grouped interface.

Just a suggestion, but im sure you have been getting swarmed with them, so ill end this by saying thank you for the amazing product, Netbox is a very powerful, well designed tool and I can tell a lot of thought went into this product. 

Thanks again.

**Comment by jeremystretch** [comment]
It's a neat idea, but practically speaking it's probably going to be more trouble to implement than it's worth. That said, I'd like to start on #284 in the near future, to allow intelligent sorting of interfaces based on a device's platform, to ensure that they are listed in their native order. It should be possible to dynamically generate interface groups based on slot number as part of that work.
