### ISSUE TITLE
./manage.py createsuperuser

### ISSUE THREAD

**Issue by dampfhamm3r** [digitalocean/netbox#375]
when running "./manage.py createsuperuser" there's always an error "your passwords didn't match" after entering the two passwords (correctly...  :-) )
this is on a fresh install (git clone from July 24th, version 1.3.1) on CentOS 7.2

**Comment by dampfhamm3r** [comment]
I think there goes something wrong in django - if I comment out the section to enter a second password in "createsuperuser.py" the user will be created. A "select * from public.auth_user" returns the user, but I can still not login...

For me, the same thing happened also on a fresh install of Ubuntu 16.04 LTS

**Comment by jeremystretch** [comment]
The creation of a superuser is handled entirely by the Django framework. It's very, very unlikely that this is a bug, but if you believe it is, please raise it with [the Django team](https://code.djangoproject.com/wiki/IrcFAQ).
