### ISSUE TITLE
unicode "Device type"

### ISSUE THREAD

**Issue by milentrifonov** [digitalocean/netbox#380]
Adding non ascii character in "Device type" field causes the exception:
<type 'exceptions.UnicodeEncodeError'>
'ascii' codec can't encode character u'\u042f' in position 0: ordinal not in range(128)

Not sure if this is intentional or not to use only ascii symbol for "Device type" name, but after this this record is unusable and cannot be deleted. 
Steps to reproduce:
1. Go to "Device Types" -> "+Add a device type"
2. For device Model type something in cyrillic letters
3. Click "Create"
4. You get the error: 
      type 'exceptions.UnicodeEncodeError'
      'ascii' codec can't encode character u'\u042f' in position 0: ordinal not in range(128)

**Comment by milentrifonov** [comment]
After some debugging I found that this is due to handling nonunicode strings in some python functions. Like print formating in examle:
here in netbox/dcim/models.py on line 407 if I change:
    def __unicode__(self):
        return "{} {}".format(self.manufacturer, self.model)

to 

    def __unicode__(self):
        return u"{} {}".format(self.manufacturer, self.model)

it works without exception.

As a workaround I decided to put 
from __future__ import unicode_literals
in the beginning of all (or most) python files in the applicatin

**Comment by jeremystretch** [comment]
This was fixed in v1.3.1. Please upgrade to the latest code.
