### ISSUE TITLE
Error: 'Rack' object has no attribute 'u_consumed'

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#381]
(Netbox 8cb38de7 running under ubuntu 16.04 with gunicorn and apache2)

Trying to do a bulk import of racks I get the following error:

~~~
<type 'exceptions.AttributeError'>

'Rack' object has no attribute 'u_consumed'
~~~

![image](https://cloud.githubusercontent.com/assets/44789/17102356/1e7a5ac0-5271-11e6-92e5-844865ffccdb.png)

I can see this field in the model, but not in the migrations. It looks like the model was updated in commit 2e821139 but no new migration has been generated?

Workaround: I have done `git checkout v1.3.1` to revert to the last tagged version.

Aside: I note that the [installation instructions](http://netbox.readthedocs.io/en/latest/installation/netbox/#option-b-clone-the-git-repository) just tell you to checkout the master branch. Maybe it should suggest checking out the latest tag instead?

**Comment by jeremystretch** [comment]
Confirmed in v1.3.1
