### ISSUE TITLE
Device Bay Component Missing Entirely

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#383]
There is no option to include device bays as a component of a device type as outlined here: [Netbox DCIM Components](http://netbox.readthedocs.io/en/latest/data-model/dcim/#components)
Furthermore there doesn't seem to be a template file available for it under `/opt/netbox/netbox/templates/dcim` (although this may be intended).

**Comment by jeremystretch** [comment]
Did you set the device type's subdevice role to "parent?"

**Comment by swickstrom** [comment]
As you can see in these images, there's no subdevice role in either the device type or device roll pages. [Device Roll/Type](http://imgur.com/a/zBWye)
No idea if I'm just blind or if it truly is missing; any assistance would be grand!

**Comment by jeremystretch** [comment]
Are you running the latest release (v1.3.1)?

**Comment by swickstrom** [comment]
According to `git status` it currently is at the master version:
`/opt/netbox$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	gunicorn_config.py
	netbox/static/

nothing added to commit but untracked files present (use "git add" to track)`

**Comment by jeremystretch** [comment]
What does it say at the bottom of the page?

**Comment by swickstrom** [comment]
Bottom of the page states `v1.0.7-r1` which is clearly not the latest version...

**Comment by swickstrom** [comment]
Issue has been resolved by updating to v1.3.1; issue updating was related to use of Apache instead of Nginx (required some finagling).
