### ISSUE TITLE
Exception when deleting user

### ISSUE THREAD

**Issue by milentrifonov** [digitalocean/netbox#385]
When trying to delete user an exception is thrown: 
type 'exceptions.TypeError'>
sequence item 0: expected string, User found

Release: v1.3.1

Steps to reproduce:
1. Go to Admin -> Authentication and Authorization -> Users
2. Select user and choose delete
3. TypeError is thrown.

**Comment by jeremystretch** [comment]
This bug occurs when the use has one or more recorded UserActions.
