### ISSUE TITLE
Create interface while importing devices

### ISSUE THREAD

**Issue by dsolson1** [digitalocean/netbox#387]
Would it be possible to specify an optional interface name to be created while bulk importing devices?  Since an interface is required when bulk importing IP addresses associated with a device this would be very helpful.

**Comment by jeremystretch** [comment]
Interfaces are automatically created according to the specified device type, which is completely user-defined. So for example, say you create a switch named "Juniper EX4300-48T" with interfaces ge-0/0/[0-47]. When you import a new device of that type, those 48 interfaces get created automatically.

**Comment by dsolson1** [comment]
Excellent!  I didn't know that worked that way.  Tested it out and that works great.
Thanks!
