### ISSUE TITLE
Problem as the Device Type

### ISSUE THREAD

**Issue by doug14** [digitalocean/netbox#388]
After inserting a new Device Type can no longer make the change or deletion of it. Furthermore, by making the registration of this equipment in a rack lose the change of access and exclusion at the same too. Could you give me an opinion as to what should I do?

Thank you

**Comment by jeremystretch** [comment]
Please describe exactly what it is you're doing and the behavior you expect.

**Comment by doug14** [comment]
Após o cadastro de um novo Device Type não estou conseguindo acessar para alteração ou exclusão. Quando tento acesso a este novo Device Type o servidor me retorna um erro.
E ao cadastrar este Device Type em um Rack perco o acesso a ele também.

**Comment by doug14** [comment]
After registering a new Device Type I'm not getting access to change or deletion. When I try to access to this new Device Type the server returns me an error.
And by signing this Device Type in a rack lose access to it too.

**Comment by jeremystretch** [comment]
Seems like you might be running into an old Unicode bug. Please ensure that you're running the latest version of code (v1.3.2).

**Comment by doug14** [comment]
Thank you. It really was about the update. By the time I was making the update was giving problem. I installed from the beginning with the new version and decided.

Thank you very much.
