### ISSUE TITLE
translation to other languages?

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#39]
Do you guys need to translate documentation or any other stuff in other languages? I'll be willing to do spanish.

**Comment by jeremystretch** [comment]
That would be awesome, though I'm not sure what degree of work would be required. I know that Django supports translations and localizations, but we'd need to go back over the whole project and build it in. That itself wouldn't be _too_ much work, I'm not sure how providing the actual translations works.

**Comment by bellwood** [comment]
The initial change would be some work to get all strings into variables and language file containings the definitions (a lot of text is re-used here though so might not be too bad) but after that its nothing more than a definition file for each language and a setting for which language you want to use and a default for the provided en-US.

**Comment by chagara** [comment]
I can start doing the documentation all the readme files you got on this github project. The actual is more complicated and will take longer but, is a start! 

If you can, is it possible to get an account on https://www.transifex.com/ ? they offer projects for free to open source programs/teams. This one will help gather the strings and other things you guys mentioned. The foreman uses this and it works great! https://www.transifex.com/foreman/foreman/ I'll start working at least on the Spanish part.

**Comment by jeremystretch** [comment]
Our documentation is still experiencing a high degree of flux and non-existence, so I'd discourage any translation efforts in the near future. Probably something to re-evaluate in a month or so.
