### ISSUE TITLE
Process for updating in Docker Container?

### ISSUE THREAD

**Issue by pettcomputers** [digitalocean/netbox#391]
Hi, I've asked on IRC Channel, Reddit, and poked around on google but haven't been able to discern the process for updating netbox when deployed via docker-compose.  Anyone here have a preferred method of doing so?  Thanks!

**Comment by pettcomputers** [comment]
After checking the demo site, it appears the docker version installed as version 1.2.0, not sure if this matters on upgrade paths/methods.

**Comment by mitchos** [comment]
Hi, I deployed Netbox in Docker prior to the official Docker release (i.e. I built my own Docker version). When I want to upgrade, I just attach to the container `docker attach [container-name/ID]` and then go to my Netbox directory `/opt/netbox`. From there it's a simple matter of following the standard upgrade process:
```
# git checkout master
# git pull origin master
# ./upgrade.sh
```

Then restart Nginx and Supervisord, detach from the container `Ctrl-P Ctrl-Q` and you're done.

If you're running daemonised then you can use `docker exec` to run those commands in the container. 

Caveat: There's always a better way to do something, so I'm not saying this is the definitive way to upgrade but might help you out for the time being.

**Comment by jeremystretch** [comment]
@pettcomputers Does this answer your question?

**Comment by pettcomputers** [comment]
I helped, but I couldn't get it going.  I ended up spinning up a new VM and
got it going the standard way.  Thank you again for the awesome app!

**Comment by jeremystretch** [comment]
I'm going to close this out. It'd be great if someone with Docker experience could extend the documentation.
