### ISSUE TITLE
Child Devices Assigned to a Parent Remain in Non-Racked Devices

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#392]
When you create a child device, it's required that you create it as a `Non-Racked Device`; once you assign the child to a parent it remains in the `Non-Racked Device` table.
Would it be possible to have it no longer appear in the `Non-Racked Device` table?
Also, it would be quite excellent if you could add a childe device on-the-fly directly from the device bays and circumvent having to create it in the `Non-Racked Device` table.

**Comment by jeremystretch** [comment]
This was done intentionally, to ensure that child devices would still appear on the rack view. However, I can see that it is confusing, and may show too much if there are many child devices within a rack. The child devices will still be shown on the rack's device list anyway, so I think it makes sense to remove the child devices from the "Non-Racked Devices" table.
