### ISSUE TITLE
Utilization Improvements

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#40]
I'd like to see some improvements to the utilization measurements.
1. The utilization bar should be shown not only under aggregate but under each Prefix and Child Prefix.
   This helps with the fact that currently the aggregate view will show 100% if you have completely subnetted out that aggregate prefix. This is nice but its not a real accurate representation of that utilization. 
2. I'd like to see an option where you could change the above to either show the utilization based off of the aggregate utilization of the prefixes rather than if you have subnetted the aggregate.

This can be annoying if you make an aggregate prefix called 192.168.0.0/21. Carve up two prefixes 192.168.0.0/22 and 192.168.4.0/22 because one will be for SITE1 and the other for SITE2. Mark those both containers. Now, my /21 shows 100% utilization because I've made containers to contain my child prefixes of 192.168.0.0/24 and 192.168.4.0/24, etc.

**Comment by frasercarter** [comment]
Yep nicely said!

**Comment by jeremystretch** [comment]
> This can be annoying if you make an aggregate prefix called 192.168.0.0/21. Carve up two prefixes 192.168.0.0/22 and 192.168.4.0/22 because one will be for SITE1 and the other for SITE2. Mark those both containers. Now, my /21 shows 100% utilization because I've made containers to contain my child prefixes of 192.168.0.0/24 and 192.168.4.0/24, etc.

I strongly prefer this behavior. It shows that the parent /21 has been fully allocated and there there is no unallocated portion of it remaining. The alternative would be to display a parent with only empty children as 0% allocated. This would be very confusing from a high-level view.

For example, suppose I define a /24 and within it 64 individual /30 prefixes representing point-to-point links. The /24 is for all purposes fully allocated, even though none of its children have IP addresses or child prefixes.

I think we're dealing with two slightly different concepts of utilization, one being the _allocation_ of address space and the other being its _provisioning_. The key might lie in counting only active prefixes for the later.

**Comment by frasercarter** [comment]
I suggest the following

Aggregates - In addition to an Allocated Prefix Utilization function, another Utilization Field Summarizing Utilized IP addresses within the Aggregate (Summary of Utilization across all Prefixes within that Aggregate)

Prefixes - Add an Utilization Field to see available IP's within a defined Prefix

This will be more comprehensive and provide better reporting for people using this to monitor network devices or 10000's of customers

**Comment by hellbringer** [comment]
Yes! Summary of Utilization per prefix would be very helpful! I think for that to work there needs to be a flag per IP 'active'  yes/no (or like with prefix: active / reserved / free / depricated)

**Comment by zachmoody** [comment]
@jeremystretch Made a quick patch that adds a configuration item where you can list the child prefix statuses you might want to exclude from the aggregate's utilization percentage. I'll make a PR if that's something you're interested in merging.
