### ISSUE TITLE
Missing Devices

### ISSUE THREAD

**Issue by ronaldkaufmann** [digitalocean/netbox#400]
When not logged in, I can see devices as normal.  When I'm logged in, I cannot see devices.  When I go to racks and click on a device I get an error:

<class 'django.core.urlresolvers.NoReverseMatch'>

Reverse for 'interface_bulk_delete' with arguments '()' and keyword arguments '{u'pk': 9}' not found. 0 pattern(s) tried: []

**Comment by jeremystretch** [comment]
What version of code are you running?

**Comment by ronaldkaufmann** [comment]
V1.3.2

v/r
Ronald Kaufmann
iPh 512.968.1974

**Comment by jeremystretch** [comment]
I'm not able to replicate this issue. Could you please provide the entire traceback?

**Comment by ronaldkaufmann** [comment]
Thanks.  Destroyed docker container and spun up another.  Issue resolved.

v/r
Ronald Kaufmann
iPh 512.968.1974
