### ISSUE TITLE
bug editing device types & parent/child status

### ISSUE THREAD

**Issue by ryanmerolle** [digitalocean/netbox#401]
I was able to produce the issue with this [device on the demo site](http://netbox-demo01.packetlife.net/dcim/device-types/24/edit/).  When you go to edit the device, make a change, and then save it, I get the following error:

> Must delete all device bay templates associated with this device before declassifying it as a parent device.

I was only trying add part numbers to existing device types.

**Comment by jeremystretch** [comment]
This device type had device bays created for some reason. It probably got into that state under a prior release before the validation was improved. The demo server is a mess.

The workaround is to set the device to "parent" status, then delete the device bays (which aren't displayed when the parent/child status is "none."
