### ISSUE TITLE
Issue with supervisord "Unit supervisor.service entered failed state"

### ISSUE THREAD

**Issue by anthraxau** [digitalocean/netbox#402]
Hello, lovely tool you have here. Im trying to get it up and running on a debian install i get all the way to the supervisord part and the service just wont run.

Has anyone had this issue?

I cant get to the front page of the website.

`
-- Logs begin at Fri 2016-07-29 15:28:14 AEST, end at Fri 2016-07-29 15:31:35 AEST. --
Jul 29 15:31:21 netbox systemd[987]: Reached target Default.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: XXXX
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is done.
Jul 29 15:31:21 netbox systemd[987]: Startup finished in 23ms.
-- Subject: System start-up is now complete
-- Defined-By: systemd
-- Support: XXXX
--
-- All system services necessary queued for starting at boot have been
-- successfully started. Note that this does not mean that the machine is
-- now idle as services might still be busy with completing start-up.
--
-- Kernel start-up required KERNEL_USEC microseconds.
--
-- Initial RAM disk start-up required INITRD_USEC microseconds.
--
-- Userspace start-up required 23094 microseconds.
Jul 29 15:31:27 netbox su[1001]: Successful su for root by user
Jul 29 15:31:27 netbox su[1001]: + /dev/pts/0 user:root
Jul 29 15:31:27 netbox su[1001]: pam_unix(su:session): session opened for user root by user(uid=1000)
Jul 29 15:31:35 netbox supervisor[1007]: Stopping supervisor: supervisord.
Jul 29 15:31:35 netbox supervisor[1011]: Starting supervisor:
Jul 29 15:31:35 netbox systemd[1]: supervisor.service: control process exited, code=exited status=1
Jul 29 15:31:35 netbox systemd[1]: Failed to start LSB: Start/stop supervisor.
-- Subject: Unit supervisor.service has failed
-- Defined-By: systemd
-- Support: XXXX
--
-- Unit supervisor.service has failed.
--
-- The result is failed.
Jul 29 15:31:35 netbox systemd[1]: Unit supervisor.service entered failed state.
`

**Comment by anthraxau** [comment]
i forced the service to stop and start again by using 

`/etc/init.d/supervisor force-stop && \
/etc/init.d/supervisor stop && \
/etc/init.d/supervisor start`

but still cant get it to work, netbox works when i use the command

`./manage.py runserver 0.0.0.0:8000 --insecure`

But thats no good for prod.

**Comment by anthraxau** [comment]
Disregard it was my bad, in the nginx setup i created "netbox" as netbox.conf

**Comment by shtouff** [comment]
On my side, I chose to run the wsgi part with gunicorn + supervisord, and let nginx serve the static files.

Here's my supervisord config fragment:

[program:gunicorn_netbox]
directory=/opt/netbox/netbox
autostart=true
autorestart=true
stdout_logfile=/var/log/netbox.log
redirect_stderr=true
command=/home/netbox/.virtualenvs/netbox/bin/gunicorn netbox.wsgi:application
    -w 4 --bind 127.0.0.1:8000 --log-level=debug
user=netbox
group=nogroup
killasgroup=true
startsecs=5
stopwaitsecs=10

Hope it'll help.
