### ISSUE TITLE
UserActions not being recorded when connecting interfaces

### ISSUE THREAD

**Issue by LordBoBCUP** [digitalocean/netbox#403]
Not sure if its intended or not, but I notice that on v.1.3.2 recent activity isn't updated when adding connections between interfaces or adding interfaces to devices, however it seems to be updated for things like VLANs and modifying circuits. Not sure if it was intended for connections & interfaces to be omitted or this is an unexpected behavior?

**Comment by jeremystretch** [comment]
UserActions are currently only being created by the generic utility views which are extended by most views in NetBox. However, a handful of views don't use these; notably the DCIM views for manipulating individual device components. Those views should be rewritten, not only to properly record UserActions but to clean up the code base.
