### ISSUE TITLE
Editing Device Type Does Not Cascade to Existing Devices

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#405]
If you edit a `Device Type` (add new interfaces, remove a power outlet, update interface info, etc) it will not cascade to the existing devices using that `Device Type`.
If this is intended, would it be possible to have an OVERRIDE option to force the update to existing devices?
Also, there is no way to update existing outlets/interfaces/console port names/properties; only delete them. Could that functionality possibly be added?

**Comment by jeremystretch** [comment]
> If you edit a Device Type (add new interfaces, remove a power outlet, update interface info, etc) it will not cascade to the existing devices using that Device Type.

Yep, this is intentional. It's called out in [the docs](http://netbox.readthedocs.io/en/latest/data-model/dcim/#device-types).

> Also, there is no way to update existing outlets/interfaces/console port names/properties; only delete them. Could that functionality possibly be added?

#353 was opened for this recently.

**Comment by swickstrom** [comment]
Apologies for my ignorance, could have easily been solved if I had RTFM...
