### ISSUE TITLE
Adding an IP to a device throws an error

### ISSUE THREAD

**Issue by JamesHarrison** [digitalocean/netbox#407]
When adding an IP at /dcim/devices/1/ip-addresses/assign/ I get the following error:

```
<type 'exceptions.AttributeError'>

'unicode' object has no attribute 'ip'
```

This is on CentOS 7 with Python 2.7.5 and nginx/gunicorn.

**Comment by jeremystretch** [comment]
What version of NetBox?

**Comment by JamesHarrison** [comment]
Sorry, should've said - 1.3.2.

**Comment by JamesHarrison** [comment]
Having enabled DEBUG, it's in this line in ipam/models.py:
```python
            duplicate_ips = IPAddress.objects.filter(vrf=self.vrf, address__net_host=str(self.address.ip))\ 
```

**Comment by JamesHarrison** [comment]
OK - if I actually specify ip/mask instead of just ip, no error. Probably should enforce mask being specified in the form, or assume /32 for v4 or /128 for v6 if no mask is specified.

**Comment by jeremystretch** [comment]
The IP address creation form does validate that a mask has been provided:

![netbox_-_add_an_ip_address_-_2016-08-01_10 40 37](https://cloud.githubusercontent.com/assets/13487278/17297600/666addba-57d4-11e6-9c0e-4af8362a7dd0.png)

IIRC even if you created an IP without a mask, it should default to /32. I'm not sure what could be causing this error. Could you post the full traceback please?

**Comment by hnk** [comment]
I think I ran into this as well and it happened when I did not have any Aggregates or Prefixes defined.

Though I did just test that scenario against the master branch and it seems to work now. I may be able to test against the older version tomorrow.

**Comment by JamesHarrison** [comment]
Yeah, lack of aggs/prefixes looks to be it, it's all good if I have some aggregates and prefixes defined - if that's fixed in master then I guess this is done.
