### ISSUE TITLE
Filtering prefixes by tenant

### ISSUE THREAD

**Issue by chonty** [digitalocean/netbox#409]
v1.4.0

When filtering prefixes by tenant, you get no results because it sends a numeric tenant ID rather than the slug.

VLAN/site/rack etc tenant filtering all function correctly as does browsing to Org>Tenants>[tenant]>
Prefixes.

Workaround is to replace tenant=<#> with tenant=<slug> in the URL:
http://netbox/ipam/prefixes/?parent=&tenant=2 >> http://netbox/ipam/prefixes/?parent=&tenant=xyz

**Comment by jeremystretch** [comment]
This was due to using the primary key of the Tenant model instead of the slug. (FYI `tenant_id=2` would also suffice as a workaround.) Fixing.
