### ISSUE TITLE
Assigning prefixes and VLANs to multiple sites

### ISSUE THREAD

**Issue by chonty** [digitalocean/netbox#410]
It'd be fantastic if prefixes (even VLANs :0...) could be assigned to multiple sites.  In our case, we have DSL subscribers with static IPs who could connect to LNSs in different sites meaning that, for example a.b.c.d/19 must exist in both sites.

Likewise for vlans for L2 trunks between sites.

**Comment by anthraxau** [comment]
this would be amazing as i have this issue also, i think it has been requested about 15 times, there are a few posts on it.

**Comment by chonty** [comment]
Ah. had a quick search and couldn't find anything

**Comment by jeremystretch** [comment]
Assignment of a prefix to a particular site isn't mandatory. It is for VLANs; #235 was opened to add support for "global" VLANs.
