### ISSUE TITLE
Make tenant groups optional

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#412]
Inspired by [this comment](https://www.reddit.com/r/Netbox/comments/4vnrhr/netbox_v140_released_introduces_multitenancy/d610rxc).

Currently, every tenant must be assigned to a tenant group. There is no real justification for this mandate; it should be fine to have ungrouped tenants as well.

**Comment by anthraxau** [comment]
I want to be able to disable tenant groups altogether. I can defiantly see the benefit of it for a lot of dc's but some of us want to hide the unwanted features.
