### ISSUE TITLE
INTERFACE TEMPLATES batch adding interfaces

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [digitalocean/netbox#413]
interface batch add is available on device but not device template

**Comment by jeremystretch** [comment]
Adding interfaces in bulk works the same for both devices and device types.

**Comment by jkldgoefgkljefogeg** [comment]
When I add Gi1/0/[0-47]	 interface in device type interface template, it does not create interfaces like it does in device interface.

**Comment by gustavo-peres** [comment]
Can you post an example of configuration to import the interfaces conections, I've tried something like this:

device_a,interface_a,device_b,interface_b,connection_status
Core B,ten-2/3/0/1,Switch 1,Ten-0/0/27,Connected

But always receive this message:

Row 1 interface_a: Invalid interface (Core B ten-2/3/0/1)

Devices edited by obvious reasons.

The interface i have copied from the device.

Thank's in advance!
