### ISSUE TITLE
Parent Prefix in Global with Child Prefix in VRF creates orphan Prefix

### ISSUE THREAD

**Issue by DanSheps** [digitalocean/netbox#414]
When adding child prefixes to parent prefixes where the child is in a separate VRF then the parent, this causes a orphan prefix where the only access to it is through that VRF.  The orphan prefix isn't visible in the prefix list, because the prefix list table considers it a child even though it is in a different VRF.

I ran into this where I placed a parent prefix (/22) in the global VRF, because it isn't assigned to any one single VRF and then put in the child prefix in the individual VRF's.

I am assuming this is based on the fact that you determine a child/parent relationship by VRF and prefix.

#395 discusses changing the functionality of the global prefix, and this is a separate issue from that

**Comment by DanSheps** [comment]
Forgot to add, list also indicates a child prefix (the arrow), however the child prefix is not visible once you actually view the parent.

**Comment by jeremystretch** [comment]
This will be covered by whatever work is done to resolve #395 so I'm going to mark this as a duplicate.
