### ISSUE TITLE
Enable assignment of VLAN during Prefix import

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#42]
The Prefix Import functionality does not currently accept the VLAN field

**Comment by jeremystretch** [comment]
This was intentional. Since a site can have multiple VLANs with the same VID and name, there's no way to specify a unique VLAN in CSV. I suppose we could implement it anyway, and simply return an error if duplicate VLANs are found.

**Comment by topside844** [comment]
IMHO, you should not be allowing multiple VLANs that have the exact same identifying information (VLAN name, VLAN ID, site) without adding some other piece of identifying information to the table.

Maybe we utilize a 'Default' VLAN database that's used automatically within each site, with the ability to instantiate additional VLAN (or VXLAN) domains in a location if necessary? This would allow network admins to create "PODs" within each site that contain their own unique set of L2 networks.
