### ISSUE TITLE
Add an asset tag field for devices

### ISSUE THREAD

**Issue by NetBod** [digitalocean/netbox#421]
Hi, I've been trying netbox out for a few weeks now and its looking good and coming along nicely. One of the things that is missing for me is a field to put the device asset Tag details in, where I work everything gets tagged with a unique value, number and letters, it would be nice to be able to add this to the device in netbox to complete its details. I did a quick search but could see if this had been suggested before or maybe its already there and I'm just missing something.... :-)
Thanks
Tim

**Comment by jeremystretch** [comment]
This is something that would be addressed by #129 (custom fields). I'd imagine it's a common enough requirement to justify adding a built-in field to the Device model, but I'll let others weigh in.

**Comment by csfreak** [comment]
Maybe the middle ground would be to have the initial_data load an assset tag field,  then those that dont want it can easily remove it.

**Comment by jeremystretch** [comment]
@csfreak Each field of the model is actually a discrete column in the SQL table. The initial data just populates some rows as a convenience for new users.

**Comment by robclarkey** [comment]
+1 for this. 

And expanding on this slightly... A dedicated view for searching only by the asset tag? Think this would be useful for those who have barcode scanners, to scan asset tags. Returning the information in the "Device" table on "/dcim/devices/xx" would be great for checking the device is in the right place.
