### ISSUE TITLE
Add Warranty field

### ISSUE THREAD

**Issue by ScrimForever** [digitalocean/netbox#424]
Hi, Is really intersting add warranty field on device options. What you mean about it ?

**Comment by ScrimForever** [comment]
Jeremy, why you think it's invalid ?

**Comment by ryanmerolle** [comment]
It also seems like it would go hand in hand with #182.  Most teams care more about support contracts over warranties for network gear.

**Comment by ebrahim** [comment]
I'd like to know about official decision regarding addition of this feature to netbox.
