### ISSUE TITLE
Ability to disable individual apps (tenancy, secrets, etc.)

### ISSUE THREAD

**Issue by anthraxau** [digitalocean/netbox#426]
Would be nice if we can disable the new tenants part as not all of us work on a customer basis.

**Comment by fltchr** [comment]
It might be nice to be able to disable individual modules as well. For example, we would likely not use the secrets feature and will want to ensure that nothing is entered there. For the majority of our folks, they will likely be setup in a user group which disallows creating secrets, but it would be nice to just administratively disable it.

**Comment by lukerussell** [comment]
I could see disabling modules being really useful for many people.

**Comment by DirtyCajunRice** [comment]
+1 for disabling modules. Our company uses netbox for the IPAM greatness only, and would love to disable DCIM/Secrets.

**Comment by jeremystretch** [comment]
Given how much NetBox has grown and how intertwined its features are, this would take far too much development effort for the modest benefit. Closing this out.
