### ISSUE TITLE
IP addresses display error in some prefixes

### ISSUE THREAD

**Issue by alarido** [digitalocean/netbox#427]
I'm not sure why this happens I can't find anything that prefixes which are failing share, but clicking in IP addresses on some prefixes show this error:
![clipboard01](https://cloud.githubusercontent.com/assets/1955581/17394069/8440866e-5a27-11e6-8196-98a8edc5f7e8.png)
```
<type 'exceptions.IndexError'>

result outside valid IP address boundary!
```

I don't see any errors in netbox log,

**Comment by thorsteinbn** [comment]
Had the same issue. Discovered that the Prefix in question had a duplicate IP registered, when I deleted one of them the error went away. Perhaps you have the same issue?

**Comment by alarido** [comment]
Yep, this is it.

Thx
