### ISSUE TITLE
Parent/child status for one device.

### ISSUE THREAD

**Issue by Farataa** [digitalocean/netbox#428]
At present we can set only one state for device:

* None
* Parent
* Child

Some devices can be parent and child at one time. For example

* Blade chassis is a Parent.
* Blades is a Child for chassis and a Parent for virtual machines
* Virtual machine is a Child on the blade.

Is possible to add Parent/Child state for device?

**Comment by jeremystretch** [comment]
A device represents a piece of physical equipment. NetBox does not currently support the concept of a virtual machine. It wouldn't make sense to use the parent/child relationship anyway, since it employs a fixed number of discrete device bays, which aren't applicable to VMs running on a hypervisor.
