### ISSUE TITLE
Allow circuits to be added to site map

### ISSUE THREAD

**Issue by jakesuellentrop** [digitalocean/netbox#430]
It'd be really nice if I could add my circuits to my site maps (for example a connection from my firewall out to my internet provider).

Any possibility of adding this?

**Comment by mitchos** [comment]
I think the map/topology feature could do with a revamp using something like the Cisco NeXt UI. This would not only look much better, but also add a lot of flexibility for displaying auto-generated topology with different layers. You could have a layers for physical connections, power, WAN circuits etc.

**Comment by aveloz** [comment]
@mitchos Maybe integrate something like this? https://github.com/interop-dev/django-netjsongraph
