### ISSUE TITLE
I'm running netbox under an alias of /netbox - after logging in I get redirected to / instead of /netbox

### ISSUE THREAD

**Issue by marvnrawley** [digitalocean/netbox#431]
All other links off the menus etc automatically detect and use the URI, however when logging in it redirected me to / instead of /uri.

**Comment by Gelob** [comment]
You can fix this by making these changes. https://gist.github.com/Gelob/0914c3ee5219b70e63d15b2b70b9d9bc. Eventually this won't be necessary once https://github.com/digitalocean/netbox/issues/212 is fixed.

**Comment by jeremystretch** [comment]
Duplicate of #212
