### ISSUE TITLE
Add Cassettes (fiber/copper) device types to Netbox

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#432]
Request to add cassette device types.
The user would create the cassette device type in two different racks and then specify the interconnection trace the cassette group hosts. 
e.g.:
The user would create a cassette in rack101, specify the cassettes mate was in rack 102. Next they would specify the two device interfaces the cassettes host i.e.: `serial.console.server.01-rack101/port.01` is connected to `server.01-rack102/serial.01`.
So `cassette.01-rack101/port.01` would show `serial.console.server.01-rack101/port.01` and `cassette.02-rack102/port.01` would show `server.01-rack102/serial.01`.
It is most important that the cassette interfaces have no associated type; that they would be able to host whatever interface type the user specifies; this would allow representation of serial-over-RJ45 and Ethernet over RJ45 in the same interface list.

**Comment by swickstrom** [comment]
This issue could also be solved by creating a `passthrough` interface type.
A `passthrough` interface setup would look like:
`Device.01-Interface.01`->`Cassette.01-Passthrough.01`<-->`Cassette.02-Passthrough.01`<-`Device.02-Interface.01`
This means the `passthrough` interface type would have connections on either side to illustrate the full linkage.
It is imperative that the `passthrough` interface type have no required port type; allowing anything to be represented as passed through (this includes console/management/interface/PSU connections).

**Comment by jeremystretch** [comment]
It sounds like you're describing physical plant tracking, which is covered by #20
