### ISSUE TITLE
Unable to assign device bay to tenant

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#433]
When trying to assign a device bay to a tenant we get the following error. This happens even if the parent device is not set to anything.

![screen shot 2016-08-05 at 1 05 05 pm](https://cloud.githubusercontent.com/assets/422752/17446140/77e7562c-5b0d-11e6-8766-813de8d103c2.png)

However, we would like the functionality of being able to assign a device/chassis to one Tenant and then assign device bays to a different tenant.

**Comment by jeremystretch** [comment]
Individual device bays can't be assigned to tenants; only devices can. What steps did you take to trigger that error?

**Comment by csfreak** [comment]
FWIW,  I have lots of situations where it makes sense for device bays to have a different tenant than the parent device.  Most common occurrence is Blade Servers and Blade Chassis.  The Chassis always belongs to our IT "tenant",  but individual servers can belong to any "tenant".

**Comment by Gelob** [comment]
@jeremystretch I went to Devices > picked a device with device bays > then clicked on the name of one of the device bays which brought me to its device page, then clicked edit this device and attempted to change the tenant field.

**Comment by jeremystretch** [comment]
I think it might help to clarify some terminology. There are three components relevant here:

* Parent device
* Device bay
* Child device

Both parent and child devices can belong to any tenant (or no tenant) independent of each other. Device bays within a parent device have no tenant assignment capability. So you can't say "Slot 1 of this device is reserved for Tenant A," but you can say "The device installed in slot 1 belongs to Tenant A."

**Comment by jeremystretch** [comment]
This is a bug in the DeviceForm initialization for child devices; nothing specifically related to tenancy.

**Comment by jeremystretch** [comment]
Adding the text of the error for searchability:

```
<class 'django.utils.datastructures.MultiValueDictKeyError'>

"'site'"
```
