### ISSUE TITLE
DHCP Pools

### ISSUE THREAD

**Issue by anthraxau** [digitalocean/netbox#437]
What is the preferred method to add DHCP pools?

I cant seem to add 10.10.0.0-10.10.0.200/22 as a pool am i doing something wrong or is it not supported yet ?

**Comment by jeremystretch** [comment]
Although not yet supported, this is going to be handled by creating individual IP addresses with a status of "DHCP". #87 was opened to address implementing a `status` field and #181 discussed the bulk creation of IP addresses.
