### ISSUE TITLE
Can't add prefix when have same vlan id

### ISSUE THREAD

**Issue by saxieyu** [digitalocean/netbox#439]
I have same vlan id on production network and out-of-band network on same site, I can add these 2 vlan with different vlan name, but when I add a prefix to one vlan, netbox display an error if another vlan have signed a prefix.How to resolve it ? Thanks

**Comment by jeremystretch** [comment]
It's not clear what you're doing. Please describe the exact steps you're taking that result in an error.

**Comment by saxieyu** [comment]
sorry, it was caused by my spelling error，please close this issue.
