### ISSUE TITLE
Can't import child devices

### ISSUE THREAD

**Issue by rikigst** [digitalocean/netbox#442]
Hi,
when I try to bulk import child devices from csv, the template is made of 8 fields (e.g. Blade12,Blade Server,Dell,BS2000T,Linux,CAB00577291,Server101,Slot4), but when I enter my data, I get the error "Line 1: Field(s) missing (found 8; expected 9)"

**Comment by jeremystretch** [comment]
The tenant field is missing from the instructions and example for child device import. If you insert a blank field after the device role it should work:

```
Blade12,Blade Server,,Dell,BS2000T,Linux,CAB00577291,Server101,Slot4
```

**Comment by rikigst** [comment]
Thank you!
