### ISSUE TITLE
Rack display page breaks when you create rack 0 unit height

### ISSUE THREAD

**Issue by kozl** [digitalocean/netbox#445]
Hi guys! Thank you very much for this cool project!
It seems that I found a bug. When you have a rack with 0 units height (dummy rack for office equipment located not in rack) rack display page breaks and doesn't show any racks at all.

**Comment by jeremystretch** [comment]
Racks are meant to represent physical equipment racks that exist in the real world. As such, it doesn't make sense to have a 0U rack. In fact you shouldn't even be able to create a 0U rack. I should fix that.
