### ISSUE TITLE
Extend rack model to define outer width and depth

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#450]
This was spun off from #180, which introduced rack type and rail-to-rail width.

Rack/cabinet width and depth is defined in either millimeters or inches, depending on the manufacturer. We have three options for handling this.
### Option A: Store dimensions in millimeters only

We could simply store a 24" wide cabinet as 610mm, and a 30" wide cabinet as 762mm, for example. This would require displaying both metric and imperial units to the user.
### Option B: Store the unit along with the dimensions

This would entail adding three fields to the Rack model:
- outer_width
- outer_depth
- outer_unit
### Option C: Define a list of standard widths and depths

This option forces the user to select from a static list of common rack widths and depths. For example, the list of rack widths might look like this:
- Metric
  - 600mm
  - 750mm
  - 800mm
- Imperial
  - 24"
  - 30"

Obviously, it would be impractical to include _all_ possible values, but this might be an acceptable solution if users are satisfied with choosing the options nearest to the actual dimensions.

**Comment by jeremystretch** [comment]
This link has some examples of varying rack dimensions: http://www.42u.com/42U-cabinets.htm

**Comment by lukerussell** [comment]
My vote is for Option C - with administratively defined rack sizes, like a template. As an example, we make extensive use of Class C racks, which are generally externally oversized compared to typical.

**Comment by marvnrawley** [comment]
Vote Option C, although perhaps with the flexibility Django gives, you might be able to make the rack types customizable from default in the backend for superuser access only?

**Comment by trikinov** [comment]
Is it possible to add  10'' wide racks, sometime used in SOHO etc ? 
Such as : [http://www.netshop.co.uk/product/170/mpe08f](url)

**Comment by jeremystretch** [comment]
@trikinov Never seen that before. What would you use it for?

**Comment by trikinov** [comment]
Used in Europe for smaller offices and homes, for patchpanel, switch, small routers, TV distribution etc etc.   Allows for smaller racks / cabinets in apartments etc..
