### ISSUE TITLE
SFP+ Breakout cables

### ISSUE THREAD

**Issue by rikigst** [digitalocean/netbox#452]
Currently one-to-one connections match one network port of a device with another port. I'm currenly employing 4x10g breakout cables from my juniper vcf to four different servers, how can i represent this?

**Comment by jeremystretch** [comment]
Your device should treat each cable as a separate interface, so I'd create four 10GE interfaces. For example, on Junos et-0/0/0 would become xe-0/0/0:[0-3].

**Comment by jbro209070** [comment]
You could also create a device called "Breakout Cable" and add the four interfaces going to your servers and add a fifth interface connecting to your juniper. This is how i simulated that type of connection.

**Comment by jeremystretch** [comment]
Definitely don't do that. The breakout cable is treated by the device as four normal interfaces; there's nothing in between.

**Comment by jbro209070** [comment]
You can't simulate a 4 to 1 connection in netbox unless you make the cable as a device and have both devices connect to the cable. Yes you could make each individual port and connect them as a 1 to 1 connection, but that leaves the single port that the physical cable is actually connected to on the second device show as unconnected.

**Comment by Tagnard** [comment]
You could add the breakout cables connections and not the physical one.

**Comment by jeremystretch** [comment]
> You can't simulate a 4 to 1 connection in netbox

It's not a four-to-one connection; it's four independent one-to-one connections. Installing a breakout cable "breaks out" the four discrete 10G channels, replacing the 40GE interface with four 10GE interfaces. Each has its own cable; they just happen to terminate in the same transceiver. Each interface is treated exactly the same as a normal 10GE interface from the device's perspective, they're just numbered a bit differently.

Here's an example from Junos with a normal 40GE transceiver:

```
et-0/0/32               up    up
et-0/0/32.0             up    up
```

The same port with a breakout cable:

```
xe-0/0/32:0             up    up
xe-0/0/32:0.0           up    up
xe-0/0/32:1             up    up
xe-0/0/32:1.0           up    up
xe-0/0/32:2             up    down
xe-0/0/32:2.0           up    down
xe-0/0/32:3             up    down
xe-0/0/32:3.0           up    down
```

If you try to abstract the cable itself, you remove these real interfaces from the device, breaking the data model.
