### ISSUE TITLE
Rack items dont show

### ISSUE THREAD

**Issue by jonathan2493** [digitalocean/netbox#455]
hi,

The rack items that ive added cannot be viewed when I go to: http://MyServersIP/dcim/racks. It just shows the word "Racks". I have to apply filters for the rack items to show. I checked the netbox demo sites the racks automatically appear when you I go to:

http://netbox-demo01.packetlife.net/dcim/racks/

**Comment by cstueckrath** [comment]
I dont even see them if I apply filters.

**Comment by jeremystretch** [comment]
What version of code are you running? And if you upgraded recently, did you also restart the WSGI service?

**Comment by rdujardin** [comment]
On v1.4.2 (dev) there is no problem, but on 1.5.0 I don't know.

**Comment by jonathan2493** [comment]
already restarted supervisor, gunicorn and apache2 services. Still the rack items dont show.
Im running netbox (v1.4.2)

**Comment by jeremystretch** [comment]
Gonna need more info in order to try replicating this.

**Comment by cstueckrath** [comment]
what kind of information do you need?

**Comment by cstueckrath** [comment]
found the reason:
we had some "virtual Racks" for VMs configured with a height of 0, but a height of 0 is not supported anymore. After we deleted these racks, the other show up again.
Now we need another solution for virtual machines (VM clusters span over racks and sub-sites, e.g. buildings)

**Comment by jeremystretch** [comment]
#142 covers support for virtual machines.
