### ISSUE TITLE
Type Rack

### ISSUE THREAD

**Issue by doug14** [digitalocean/netbox#458]
Hello, I would like to take a question relating to the types of rack that have been entered in this new version. There is possibility to be inserted a new type? In case it would open type that has only the front. As an example the image that is the link (http://www.furukawa.com.br/arquivos/galerias/90/274_3.jpg).

Thank you very much.

**Comment by jeremystretch** [comment]
@doug14 Unless I'm missing something, that would be the "2-post frame" type.

**Comment by doug14** [comment]
True, translation error on my part.

Thank you the support.
