### ISSUE TITLE
Ports created in device type not reflected in devices

### ISSUE THREAD

**Issue by harsh-kotak** [digitalocean/netbox#464]
I created a new device type and added few devices of that type. Then I went to the device type and added console and management port but it did not reflect on the devices I already created. It does reflect  on devices I create now. Bug? I would like it to be reflected on all devices created before and after.

**Comment by jeremystretch** [comment]
This behavior is intentional to avoid unintended consequences. From [the docs](http://netbox.readthedocs.io/en/latest/data-model/dcim/#device-types):

> Note that assignment of components from templates occurs only at the time of device creation: If you modify the templates of a device type, it will not affect devices which have already been created. However, you always have the option of adding, modifying, or deleting components of existing devices individually.

**Comment by harsh-kotak** [comment]
Can we have an option to slect if we want to reflect the template on all the devices or only for future devices. This will save a lot of effort for people like me who have already created 150 devices.

**Comment by LBegnaud** [comment]
you can bulk-add interfaces from the devices listing

select multiple devices, click add interface

**Comment by harsh-kotak** [comment]
Thank you. This helps in adding interfaces but not console ports.

**Comment by jeremystretch** [comment]
To be clear, device types are supposed to be defined once and rarely (if ever) modified. A device type represents a make and model of physical device, which never changes. For instance, every Juniper EX4300-48T ever made has the exact same console port, power supplies, and interfaces. There should be no need to ever modify these unless you made a mistake when originally creating them (but I'm hoping to mitigate that in the near future with #451).

**Comment by padavrexi** [comment]
Just a quick heads up: at least on v1.6.2, when creating a new device type, the buttons to add interfaces/console ports/power ports/device bays are missing. In order to reinstate them, I had to go to admin site, add a dummy template and then go back. Same thing works fine on a v1.1.0 installation (not sure about interims).

**Comment by jeremystretch** [comment]
See #591 for above. Will be fixed shortly.
