### ISSUE TITLE
Duplicate Connection/Circuit Error

### ISSUE THREAD

**Issue by bradical987** [digitalocean/netbox#472]
When assigning a circuit to an interface, the ability to add a connection to another device still exists, as if no connection is assigned to this interface (i.e. Gi0/0/0 is assigned to circuit xyz, but I can still click the + to add a device connection). It does give a server error after clicking _create_:

```
<class 'django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist'>
InterfaceConnection has no interface_a.
```

I don't need to assign a device to the same interface as a circuit, just wanted to see what would happen if I tried. I didn't see any other issues open or closed, so reporting the issue in case it was not known.

**Comment by jeremystretch** [comment]
Thank you for the bug report!
