### ISSUE TITLE
UI Change for button placement in panels

### ISSUE THREAD

**Issue by WilliamMarti** [digitalocean/netbox#475]
So it looks like the normal convention for button placement in panels is in the panel-footer in Netbox.  For most areas this isn't a big deal, but the 'Interfaces' panel for Devices gets rather lengthy for some larger chassis based switches.  It seems to be a fairly established UI convention to have buttons placed at the top of the resource they control. 

Here is an example of what I am thinking:

![capture](https://cloud.githubusercontent.com/assets/4473602/17708146/b49c3036-63b1-11e6-9cca-a8374f3cbde5.PNG)

Now I don't have to scroll to the bottom of the page to make additions or delete selected interfaces.  This also might be a good place for a "Select All" checkbox as well.

I wouldn't mind making this change, but wanted your(stretch) opinion first

**Comment by sts** [comment]
-1 on how this currently looks like.

I feel the buttons would rather be placed on the right side. 'Add interface' right to 'delete interface' button and the padding between those should be fixed too.

**Comment by WilliamMarti** [comment]
I would be fine with having the buttons right aligned.  I think the greater issue is moving the buttons to the top of the resouce

**Comment by jeremystretch** [comment]
The "add <object>" buttons are now displayed in the bottom right corner of all device and device type component panels. The are also displayed in the top right corner if the panel contains more than ten objects.
