### ISSUE TITLE
Weight / Thermal Dissipation / Electrical consomation for Device / Rack

### ISSUE THREAD

**Issue by nothing-fr** [digitalocean/netbox#479]
Is it possible to add those specs for devices ?

- to know how many kw/h (average) my rack will consume (https://en.wikipedia.org/wiki/Kilowatt_hour)
- how many btu/h (average) it will produce (https://en.wikipedia.org/wiki/British_thermal_unit)
- how much weight my rack will have

Very useful informations for moving racks, air conditionning, electrical balance...

Maybe add the Max Weight specs for a rack, to be warned if we have too much servers in it too ?

(and sorry for my bad english =/ )

May be usefull : http://essa.us.dell.com/dellstaronline/Launch.aspx/ESSA?c=us&l=en&s=biz

**Comment by jeremystretch** [comment]
#54 has been opened to track the available power within a rack, but I think that's about as far as we'll extend NetBox.

**Comment by lodpp** [comment]
Hello Jeremy,
Would you confirm that the power capacity will be limited to  a rack and not going deeper ?

In the same extend than nothing-fr, I would like to fill the typical/peak power draw per equipment, then matched it up with the total power available in my rack to make sure I can safely turn them up or if we can survive a power loss on one feed. ( Yes mistake happens .. )

Also it can tell us if we can charge more a rack or not. We are usually  limited with the power in the rack than the space.

Thanks and Regards,

**Comment by puck** [comment]
Power consumption needs to be aware that there can be multiple circuits into a rack - for example I have 2x A and 2x B circuits into most of my racks. Some only have 1x A and 1x B, and some also have a static switch backed power rail...

**Comment by jeremystretch** [comment]
The boundary of NetBox's scope will be the power circuits that are delivered to a rack. Beyond that we'd be getting into facilities management territory.
