### ISSUE TITLE
Force Interface creation before allowing IP assignment

### ISSUE THREAD

**Issue by LordBoBCUP** [digitalocean/netbox#481]
I've noticed, when trying to assign an IP address to a device, if there are no interfaces assigned to it, you are still able to load the assign IP form. You can enter in the IP, VRF etc, and when you click create it prompts you to select an interface of which there are none. There should be logic either flagging a warning, or, forcing you to the add interface page if there isn't at least 1 free interface that the IP can be assigned to when you first click on the add IP address button on the device view page. This is in v1.5.1.

**Comment by marvnrawley** [comment]
There are several places when the same check could be added; just a few examples:

1. Add a device type before device.
2. Add a manufacturer before a device type.
3. Anywhere else you have a required field from a user created table.
