### ISSUE TITLE
Display Utilization of prefixes likeunder Aggregates

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#482]
Hi,

I Working for a small network and I search since fews years now a IPAM which is math witch an ISP needs.
Your product seems promissing !

Is it possible to add this fonctionnality ?

Regards

**Comment by jeremystretch** [comment]
Prefix utilization is already shown on the aggregates list. #237 has been opened for tracking the utilization of IP addresses as well, if that's what you mean.
