### ISSUE TITLE
Add a request section

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#483]
Hi,

Is it possible to add a section in order make a request of an IP address ?

Thanks in advance

Regards,

**Comment by jeremystretch** [comment]
This crosses into the realm of ticket management, which is outside NetBox's scope. I imagine most organizations would prefer to use whatever ticketing or provisioning system they have in place. NetBox will be much easier to integrate with these once we implement a writable API in v2.0.

**Comment by thoms27** [comment]
Hi Jemery !

Thank you for your quick answer ! You're right about this request. I search for a long time now an IPAM for manage ours ressources (IPv4, soon IPv6, VLANs, VRF, VFI etc...).

I'm working for a small network provider in France and I have to confess that your blog packetlife is like a bible of network for me :-) I don't have any certification like you, but I so learned with yours post to product the backbone of the ISP !

So many thanks !

Thomas Vahé
