### ISSUE TITLE
Django 1.10 prevents by default deletion of large numbers of records

### ISSUE THREAD

**Issue by ingeba** [digitalocean/netbox#484]
After pulling Netbox yesterday, an upgrade was made to Django 1.10. After this it was no longer possible to do a bulk delete of ~2500 prefixes (I got "Internal server error").  The Netbox log error was:

TooManyFieldsSent: The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.
[2016-08-17 13:15:54 +0000] [15415] [ERROR] Error handling request /ipam/prefixes/delete/

and a traceback was generated. According to the Django docs, the number of HTTP fields are on 1.10 limited by default to 1000. I resolved the issue by adding to netbox/netbox/settings.py:

DATA_UPLOAD_MAX_NUMBER_FIELDS = None

**Comment by jeremystretch** [comment]
How were you performing the bulk deletion? Deleting objects using the "select all" box should only send one field with a list of objects IDs. Otherwise, the number of fields sent should be limited to the maximum page size IIRC.

**Comment by ingeba** [comment]
I used the check box over the list - "Name" in "Devices", "Prefix" in "Prefixes" etc. It then prompts me with a list of objects to delete and asks me to confirm. After the confirmation it gives the error I cited above. Deleting 500-600 items at the time worked well, but not > 1000. After changing the Django config, deleting work regardless of the number of items.

**Comment by jeremystretch** [comment]
Right, ok. On the second submission (post-confirmation), each object ID is passed independently.

I suppose I don't really see a reason for `DATA_UPLOAD_MAX_NUMBER_FIELDS` as far as NetBox is concerned. I'm going to disable it in `settings.py`.

**Comment by kusumkumari** [comment]
TooManyFieldsSent at /admin/coupon/221/change/
The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.
showing this error when  I have enter 2000 value in limit field for generate coupon code 2000 times on submit button . its using django   inlines = [CodeInline] code in admin.py. how to resolve it??
