### ISSUE TITLE
Allow connection of devices between remote sites

### ISSUE THREAD

**Issue by callumbnz** [digitalocean/netbox#49]
not sure if this is by design or a bug - but I am unable to connect devices together that are not in the same location.

Also on the circuits management stuff - it would be good if you could have an A-Port and a B-Port - as we have several leased lines that go between facilities

**Comment by jeremystretch** [comment]
You're not missing anything. Circuits currently only support a single endpoint, with the other endpoint being "the cloud" (e.g. provider backbone or the public Internet). I'd like to extend this, but it's a fair amount of work and I didn't want to delay the release any longer.

**Comment by callumbnz** [comment]
Ah - sweet as then!

Feature request ahoy!

On Tue, Jun 28, 2016 at 12:21 PM, Jeremy Stretch <notifications@github.com>
wrote:

> You're not missing anything. Circuits currently only support a single
> endpoint, with the other endpoint being "the cloud" (e.g. provider backbone
> or the public Internet). I'd like to extend this, but it's a fair amount of
> work and I didn't want to delay the release any longer.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/digitalocean/netbox/issues/49#issuecomment-228930737>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMzglyJBBxTo4jCHV9iNowBK4DuJpVMjks5qQIUXgaJpZM4I_oFH>
> .
>



-- 
Callum Barr
me@callumb.com

**Comment by mjclancy83** [comment]
Just adding my support for this feature.  Very useful for guys who have a lot of L2 Access tails, or even DF/ME between DCs etc.

**Comment by markve-sa** [comment]
+1

**Comment by robwasteground** [comment]
+1 :)
