### ISSUE TITLE
Commit rate displaying as N/A when set

### ISSUE THREAD

**Issue by anthraxau** [digitalocean/netbox#490]
i have found a bug in the circuits.

I created a circuit and gave it a committed rate of 50000 and saved it. when reviewing over the circuit i have noticed that the committed rate is now N/A.

I went to edit the circuit thinking that i had missed it but the field is populated with "50000"

**Comment by jeremystretch** [comment]
Derp. Had the template variable as `commit_speed` instead of `commit_rate`.
