### ISSUE TITLE
Ability to use asset tags in rack view instead of device names

### ISSUE THREAD

**Issue by ingeba** [digitalocean/netbox#494]
For our DC's, the current solution of using names in the graphical overview of racks does not work too well:
- Not all devices have any names beyond their asset tags.
- Those devices that do have names, have FQDN's as names which exceed the width of the rack drawings, making the rack entries impossible to read. We have no good way of shortening these FQDNs to a length that would fit the rack drawings.

We may of course duplicate the asset tag in the name field, but then we are no longer able to find hardware given its currently assigned FQDN.

Instead we prefer to use asset tags in rack view but keep FQDN's as names for those devices that has it. All devices at our sites are regarded as assets and registered with a unique tag with reasonable length upon arrival, following the hardware to its death. We have made a small patch to Netbox to use asset tags instead of names in rack views and instead include the name with the other information given in the mouse-over hover bubble. We have also increased the maximum name size to support all our FQDN's.

Of course what suits us may not suit all, but having this as an option would be good for us and maybe others?

**Comment by jeremystretch** [comment]
This feature request hasn't gotten any traction in a year. I've added the asset tag to the pop-up bubble, which should be sufficient.
