### ISSUE TITLE
Tenant Import

### ISSUE THREAD

**Issue by LBegnaud** [digitalocean/netbox#498]
We have a multi-tenant datacenter and would like to associate VLANs to those tenants. Manually creating 150 to start with doesn't sound like a fun time. Keeping up with the list should be no problem, though.

I toyed around with the idea of doing inserts directly into the db, but I decided against it as I'm not sure what would be affected.

I suspect a read/write API would solve this problem, but any suggestions until then?

**Comment by ingeba** [comment]
We use the "Import Tenant" functionality in the GUI to import our customers (a few hundred) - works like a charm. We use the development branch.

**Comment by LBegnaud** [comment]
Oh neat... i did a quick search and didn't see that mentioned. Thanks for the info.

**Comment by LBegnaud** [comment]
For completeness, it is a feature in the 1.5.2 release (might have been included before that release, but i don't see it mentioned in release notes)
