### ISSUE TITLE
Adding Rack > Edit Rack Name > Server Error

### ISSUE THREAD

**Issue by troxil** [digitalocean/netbox#50]
When Adding a rack to a site - I edit the friendly org name and it fails. 

> There was a problem with your request. This error has been logged and administrative staff have been notified. Please return to the home page and try again.

Process to fault
0. Login as super user
1. Sites > Add a Site
2. Racks > Add a Rack > Provide Name "Active"
3. Racks > Racks > Click "Active" > Edit this rack
4. Change name from "Active" to "ORGACTIVE" > Update
5. See Error

**Comment by Gelob** [comment]
This also happens when editing the rack height.

**Comment by jeremystretch** [comment]
@Gelob is spot on. This is my fault. Fixing.

**Comment by jeremystretch** [comment]
Fixed in 4dd31497e52013ec45d3b766d9b8345e2dd238bb
