### ISSUE TITLE
Device type dose no load 

### ISSUE THREAD

**Issue by belaoulidris** [digitalocean/netbox#501]
Hi Everyone . 

i have a problem when i try to create a new Device => Hardware => Manufacturer cisco for example then i get nothing on the Device type filed , how that can be fixed ?

Best Regards

**Comment by Tagnard** [comment]
First you need to add manufacturers by going to "Devices -> Manufacturers" and then click the blue button "Add a manufacturer".

After you have done this then you can add a device with that manufacturer.
