### ISSUE TITLE
Additional tenant stat "Ports" 

### ISSUE THREAD

**Issue by evgstanev** [digitalocean/netbox#502]
Good evening,

I would like to request an additional Tenant stat called "Ports" , showing the number and the list of ports assigned to each Tenant. It will be really useful for us and i hope for others.

Thank you!

**Comment by jeremystretch** [comment]
Individual interfaces and other components cannot be assigned per tenant; only devices can be assigned to tenants. It wouldn't make sense to sum the total number of interfaces across all devices belonging to a tenant because interfaces are used for different functions.
