### ISSUE TITLE
Add authorized persons and contacts to tenants

### ISSUE THREAD

**Issue by mobydick122** [digitalocean/netbox#503]
Good evening,

I would like to request an additional Tenant information fields as authorized persons who should be able to visit the tenant equipment in the data center and  authorized mail and phone contacts from which the tenant will be able to ask for equipment restart, re-configuration and so on. It will be really useful for us and i hope for others.

Thank you!

**Comment by jeremystretch** [comment]
This seems like the sort of thing where everyone is going to want something slightly different, and trying to force information into a particular format is going to do more harm than good. We also don't want to creep outside NetBox's focus on infrastructure management. I think it's sufficient to store such information in the comments field of the Tenant object.
