### ISSUE TITLE
Menu graphical issues

### ISSUE THREAD

**Issue by LBegnaud** [digitalocean/netbox#507]
When running netbox on a vertical monitor, one is forced to use the menu button. This is fine, however, the background doesn't extend to fit all the menu items:

![image](https://cloud.githubusercontent.com/assets/15981748/17970980/73b034ca-6a9e-11e6-998f-6fd6f5c28086.png)

I did a little searching and couldn't find something related to this. Not a huge deal for us, but just want to make the right people aware of it

**Comment by chagara** [comment]
this is the problem I'm having with https://github.com/digitalocean/netbox/issues/511
