### ISSUE TITLE
issue after upgrade

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#508]
I upgrade from the original release of netbox to the 1.4.2 and all of my devices are gone. I followed the instructions on the readmedocs. This are the errors I get in postgres:

ERROR: column dcim_device.primary_ip_id does not exist at character 2036
ERROR: column dcim_device.primary_ip_id does not exist at character 449
ERROR: column dcim_device.primary_ip_id does not exist at character 2045

**Comment by zachmoody** [comment]
Looks like it's querying for columns that were deprecated a few versions back. I would guess the WSGI is still running old code or it wasn't restarted.

**Comment by chagara** [comment]
umm I restarted nginx, I restart supervisord, I restart also netbox using supervisorctl restart netbox. Did I miss something?

**Comment by chagara** [comment]
figured it out. I had to change the gunicorn and supervisord config to the netbox-1.4.2 dir instead of the old one.
