### ISSUE TITLE
using TLS/SSL between postgresql and netbox

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#509]
helo,

in our org we are forced to set up postgresql to use TLS and certain ciphers regardless if we are letting remote connections or not. I configured the postgresql.conf with the certs and turned SSL on. I also added the database and user with md5 to pg_hba.conf. Now I get a server error:

<class 'django.db.utils.OpertaionalError'>
FATAL: password authentication failed for user "dude"

maybe i'm missing a step or is something I have to change in netbox.

**Comment by jeremystretch** [comment]
This wouldn't be a NetBox-specific issue, but rather one related to general Django configuration. A quick search didn't yield anything helpful. I'm not sure if it's not supported or just not a common use case.

I'm going to close this issue, but if you happen across a configuration change needed to support it, please let me know and I'll work on integrating it.

**Comment by AlexanderS** [comment]
You can add `{'sslmode': 'require'}` in the [OPTIONS setting of your database backend](https://docs.djangoproject.com/el/1.10/ref/settings/#std:setting-OPTIONS).
