### ISSUE TITLE
Feature: Add ZeroU devices to racks.

### ISSUE THREAD

**Issue by visbits** [digitalocean/netbox#513]
Currently there is no method to *rack* a zero U device.

How it is illustrated in racktables.
![image](https://cloud.githubusercontent.com/assets/873498/18060511/a089c816-6dec-11e6-98a5-1e813fea8cb5.png)

**Comment by zachmoody** [comment]
Netbox does something similar to this with non-racked devices. You'd create your PDU device types with a 0-u height and add them to the rack as a non-racked device.
