### ISSUE TITLE
permission error in Docker for Windows

### ISSUE THREAD

**Issue by smaeda-ks** [digitalocean/netbox#514]
Hi,

This is just FYI but in Docker for Windows environment,
by default Windows can not keep original linux file permission like `docker-entrypoint.sh`, so docker-compose will fail with permission denied error because of it has no execute permission.

As my environment, I need to add `RUN chmod +x /docker-entrypoint.sh` to Dockerfile.

Of course this is not issue of your side and developer should be resolve kind of this issue themselves.
But If there is some document about this, maybe it will help someone who is Docker beginner.

Thanks,
Shohei

**Comment by jeremystretch** [comment]
Closing this out as it doesn't seem to pertain directly to the code base. Please consider posting to the [netbox-discuss](https://groups.google.com/forum/#!forum/netbox-discuss) mailing list for assistance.
