### ISSUE TITLE
Device import states "face" is optional, but if position is set it's required

### ISSUE THREAD

**Issue by puck** [digitalocean/netbox#515]
Just hit this when trying to import some devices.

**Comment by LBegnaud** [comment]
I'm not discounting the possibility of a bug, but are you perhaps putting something in the position column and not the face column? Would probably help to give a sample line that's stating the error or a screenshot

**Comment by puck** [comment]
I had a value in the position column, and the face column was empty as the documentation said that field was optional. When I added front to the face column I was able to import the data.
