### ISSUE TITLE
Raft of Enhancements to Power - capacity management, unique ports, utilization view

### ISSUE THREAD

**Issue by marvnrawley** [digitalocean/netbox#520]
# Add power utilization bar to Power Connections, options to group or filter by Site, Rack-Group, Rack or PDU Device 
When viewing Racks, you get a utilization in %, being a ratio of free space minus occupied space. Doing the same for power bars would be useful.

Ideally you'd want to be able to filter or group by Site, Rack-Group, Rack or PDU Device.

# Power Capacity Management
This also implies an extra field on PDU type devices which would be "max power". I'd suggest this be freeform to allow people to manage it in either amps or watts. Further, it implies custom fields on device types and devices for peak power draw, steady power draw, and heat dissipation in BTU/hr.

It might even benefit a 'weight' field on device types and devices.

# Make Power Connections 'unique' (and console and management)
When viewing a device, and selecting to add a new power (/console/management) connection you search for a CI or select it from a list, and then the API loads the valid ports for the device. The API call here should instead only return all non-connected ports, or if that's not possible, it should return any current assignment in addition to the port ID; instead of just being a list of "<port name>" it would be "<port name> - <connected device>" for ports with a connection.

I don't know if this requires a new API call, or just requires the page to be configured to load a different API call, which would already return this data.

**Comment by jeremystretch** [comment]
Power management is covered by #54. Please break the other two requests into their own issues.

**Comment by marvnrawley** [comment]
Sure thing.
