### ISSUE TITLE
Top-of-the-window menu spacing problem when the browser is just the right width

### ISSUE THREAD

**Issue by GreyGnome** [digitalocean/netbox#521]
I just installed netbox 1.5.2 and my browser window was just wide enough to make the top menu bar shift to double-spaced, but not so narrow that it caused it to be replaced by the menu. The ensuing partially-missing components confused me so I thought it was that Chrome was broken, because the display was fine on Firefox (although I did get bit by bug #507). It turns out, my Firefox was simply wider.

Here's a screenshot:
![netbox1](https://cloud.githubusercontent.com/assets/3449497/18138296/adc4abc8-6f71-11e6-98e5-199f5933dc9d.png)

If I pull the window wider, the display looks fine. If I pull the window narrower, it jumps to the menu. If the window is juuuust right... 2 lines, and partially covered up screen components. See this shot for another view:
![netbox2](https://cloud.githubusercontent.com/assets/3449497/18138633/49987bd2-6f73-11e6-92c2-d75d645f1170.png)

This problem came about because my screen is in portrait orientation, so it's 1200 pixels wide. I imagine that a person with a 1280x1024 screen with a browser window that's just slightly narrower than full width would see this issue.

**Comment by chagara** [comment]
same problem going on #507 and #511

**Comment by jeremystretch** [comment]
This should be fixed in v1.6.0. The menu now collapses entirely in the screen is less than 1200px wide.
