### ISSUE TITLE
Power utilization percentage of max, akin to the rack utilization percentage of max

### ISSUE THREAD

**Issue by marvnrawley** [digitalocean/netbox#524]
When viewing Racks, you get a utilization in %, being a ratio of free space minus occupied space. Doing the same for power bars would be useful. In this I am suggestiong both having a view of a %age of maximum power in watts or amps and having a view of consumed vs available outlets.

Ideally you'd want to be able to filter or group by Site, Rack-Group, Rack or PDU Device.

This probably requires at least some of the features of #54 to be completed first.

(Sorry maintainers if this created additional paperwork linking issues, I thought you wanted this one separated out per comments in #520.)

**Comment by jeremystretch** [comment]
I think we can just fold this into #54, as I'm sure it will come up as part of that work.

**Comment by lampwins** [comment]
@jeremystretch I think we still have room to get this done in 2.6. I feel this is really what makes the new power functionality super useful. Space utilization is important, but a lot of my racking decisions in the past have been based on power.
