### ISSUE TITLE
Bulk editing should support setting all non-required fields to "none"

### ISSUE THREAD

**Issue by cdemi** [digitalocean/netbox#527]
In bulk edit, unchosen drop downs mean that the field is not to be edited. This makes it impossible to bulk edit a field to the default state

**Comment by frg** [comment]
Same here :/

**Comment by natashafenech** [comment]
Having the same issue +1

**Comment by jeremystretch** [comment]
This is something I've been meaning to get to. v1.6 will include a "none" option for many fields, but eventually I'd like to add a separate "set to none" checkbox for every non-required field in every bulk edit form.

**Comment by frg** [comment]
Thanks for the update @jeremystretch. Any idea on release date of 1.6?

**Comment by jeremystretch** [comment]
This week. Would have been earlier but I was away for a couple weeks.

**Comment by natashafenech** [comment]
Thanks. Sounds like a good solution!
