### ISSUE TITLE
Always Logged in on Web UI

### ISSUE THREAD

**Issue by bradical987** [digitalocean/netbox#528]
Maybe I just didn't notice it in earlier releases, but it seems like once I upgraded to v1.5.2 I have remained logged in to the web ui. I've tested this on Chrome and Firefox with the same result. I can close my browser and even restart my computer, but I remain logged in. I do, however, land on the login page when I first navigate to the URL, but everything else appears the same (admin access to everything and the option to _log out_). The only way I can actually log out is to click _log out_. It seems to me like this shouldn't be happening, so maybe it is user error or just expected behavior for this platform?

Currently, I have `LOGIN_REQUIRED = True`, but I did have it set to `False` for a period of time. I started noticing this behavior while login was not required, so I set it back to `True`, `sudo supervisorctl restart netbox`, no change in behavior.

**Comment by jeremystretch** [comment]
Not sure I understand the problem. The authentication cookie issued upon login is valid for 15 days; you will continue to stay logged in across browser restarts until the cookie expires or you log out manually.

**Comment by bradical987** [comment]
Fair enough. If that is the expected behavior, there is no problem then.
