### ISSUE TITLE
Utilization of rack with blades calculates U per 0U device

### ISSUE THREAD

**Issue by visbits** [digitalocean/netbox#532]
Rack has 4x 10U blade centers (parents) and 64 blades (0U children)

![image](https://cloud.githubusercontent.com/assets/873498/18258083/152dda62-739d-11e6-9036-79952f72bca1.png)

![image](https://cloud.githubusercontent.com/assets/873498/18258080/0ab72e3a-739d-11e6-93e7-3702a3fcb718.png)

**Comment by jeremystretch** [comment]
Can you post the complete list of devices in this rack please?

**Comment by visbits** [comment]
![image](https://cloud.githubusercontent.com/assets/873498/18275081/7d22be00-7413-11e6-9cde-dee080804380.png)

![image](https://cloud.githubusercontent.com/assets/873498/18275088/863457ce-7413-11e6-8afc-bdc2afe8e1f4.png)


![image](https://cloud.githubusercontent.com/assets/873498/18275067/735d4ac0-7413-11e6-9b1c-4187e77e2dca.png)

**Comment by jeremystretch** [comment]
The four 10U chassis account for 40U worth of space. 0U devices do not contribute to the sum of utilized space (this is literally a `SUM()` operation which adds 0 for each 0U device). However, it _does_ include the height of non-0U devices which have been assigned to the rack without a position, e.g. the Dell M1000e switch you have defined. What is the defined height of that device type?

**Comment by jeremystretch** [comment]
It seems that the extra U space can be attributed to the non-racked devices listed. I'm going to close this out but feel free to respond if you find otherwise.

**Comment by visbits** [comment]
Hi @jeremystretch  the dell m1000e switch is 0U.   I've went through all the devices and everything that is not the M1000e is set to 0U.
