### ISSUE TITLE
Circuit with two endpoints (and associated cross-connects)

### ISSUE THREAD

**Issue by kirk444** [digitalocean/netbox#534]
Forgive me if I am just misunderstanding how this works, as I am new to netbox. It seems like the "circuits" feature is only really useful for a DIA circuit, or something else with only one endpoint.

The majority of my circuits are from site "A" to site "Z". Each site has a cross-connect associated with it. For example, a wave circuit from Equinix CH2 to Equinix NY4 will have a cross-connect/patch-panel at CH2, and another at NY4. The current implementation seems to limit me to one cross-connect and one patch-panel field.

It seems like a circuit (or at least some subset of circuits) should support an "A" and "Z" side cross-connect (at a minimum, there are situations where one circuit has 3, or even 4, associated cross-connects).

**Comment by zachmoody** [comment]
You're not missing anything. That feature is on the roadmap in #49 .
