### ISSUE TITLE
feature request: allow to use front AND back rack on same rack unit

### ISSUE THREAD

**Issue by alejojo** [digitalocean/netbox#536]
Hi there,

would it be possible to allow to use the front **AND** back of a rack units?

We have several devices that share same unit, 1 in the front and 1 in the back of the rack.

Thank you!

**Comment by cioby23** [comment]
This is already implemented. When you add a new device type you need to uncheck the "Is Full depth" option and this will allow you to add devices on both side of the same rack unit.

**Comment by alejojo** [comment]
Hi @cioby23,

thanks for quick reply.

yes, you are correct. closing ticket
