### ISSUE TITLE
Add tenants to interface connections

### ISSUE THREAD

**Issue by fabiana275** [digitalocean/netbox#537]
Hello,

Is it possible tenant to be assigned to interface connection and the number of them to be showed in the tenant stats?

It will be really useful for us if we can see how many connections are used from one tenant.

Thank you in advance!

**Comment by jeremystretch** [comment]
Trying to associate a connection with a tenant would be overly complex, but we can infer tenancy from the tenant assigned to a connected device. How would you want this information to be conveyed?

**Comment by fabiana275** [comment]
Hi again,

I've thought, actually we need to know (count) only how many uplinks are assigned to some tenant, not all of the tenant's connections. So probably if we could mark some connections as uplinks and they could be counted to the tenant assigned to a connected device will be good.

**Comment by jeremystretch** [comment]
I think that marking individual connections as "uplinks" would be too subjective: the concept of an uplink is dependent upon context. For example, an access switch see its connection to a distribution switch as an uplink, but the distribution switch does not.

It seems that what you want to do is count the number of connections that terminate to a device owned by a particular tenant. This information exists in the data model, you just need to determine how you want to retrieve it.
