### ISSUE TITLE
Track available power per rack

### ISSUE THREAD

**Issue by Gelob** [digitalocean/netbox#54]
Power Connections feels like an afterthought right now. There is no interface to add a PDU with a # of outlets, but you can import this information.

I think there should be a separate Power tab that is tied back to the individual rack. This would help greatly with tracking power circuits per rack (30A phase, etc) and their IDs.

**Comment by jeremystretch** [comment]
PDUs are treated like any other device in NetBox. You can simply create a device type to represent the model of PDU you'd like to install (for example, an APC AP7900). Vertically-mounted PDUs which don't consume rack space should be treated as 0U devices. Then, you can add the appropriate number of outlets to the device type.

NetBox doesn't currently support any mechanism for tracking power circuits outside of a rack. This would be a pretty substantial feature expansion.

**Comment by Gelob** [comment]
Thanks, I see that now PDUs are part of devices. My bad.

I think it could easily be accomplished by having a field on the rack in terms of how much power it has, but it would be nice to track the individual power circuits.

**Comment by jeremystretch** [comment]
I'd love to get more detail around specifically what you'd like to track. We're planning to implement custom fields in the near future, but I think it makes sense to add a dedicated field or two to the Rack model to track power if there's interest. I don't know enough about power to know what it should look like.

**Comment by bellwood** [comment]
Typically when it comes to power you have:

1) amps (15/20/30/etc)

free form field would be fine

2) phase (1 or 3)

2a) phase ID

single phase breakers on a 3 phase capable busway are either A/B/C in terms of the leg they are powered from

3) volts (120/208/etc)

free form field would be fine, some prefer 110 over 120 and there are odd voltages out there

4) breaker ID

5) possibly breaker PDU/panel ID

we use overhead busway for breakers so our breaker ID's are the rack ID + pdu number in the rack

6) A, B, C, etc power

my junipers hold four PSU's and each is fed from a different UPS/busway/breaker so denoting power "type" would be nice

**Comment by Gelob** [comment]
Bellwood hit a lot of it spot on.  What about 2b) bank id? In 3 phase you have 3 banks of outlets tied back to the 2 phases which is tied back to the breakers. Its deep, but it would be nice to have the option to track that my device is plugged into outlet 24 which is tied back to bank 3 which is tied back to phases 1 + 2. It helps with knowing and understanding at a glance where my heavy power usage is per device.

I don't know much about DC power but that should be an option too (AC or DC).

Example Use Case:
I have a row of 3 racks:
Rack 1 has 2x 30A 3phase power circuits and two PDUs installed. 
Rack 2 has 4x 30A 3phase power circuits and two PDUs installed.
Rack 3 has 2x 20A single phase power circuits installed and two PDU installed

The power circuits live under raised tile. I want to be able to track that the PDU A in Rack 1 is plugged into a specific 30A circuit. The datacenter has their own labeling scheme that I want to notate for my reference. For Rack 2 I have had the datacenter install 4x circuits, but only two are active at this time. Having tracking would help with capacity planning of unused power or future power if we have available racks but no power yet.

**Comment by dinoocch** [comment]
@jeremystretch Is there monitoring included in this plan - to monitor and perhaps visualize real power consumption (via snmp) seems like a useful feature to me, although it would introduce a lot more complexity.  I understand that Netbox is not designed to be a monitoring platform - however having this data, especially power usage, all in one place makes sense to me...what do you think?

**Comment by jeremystretch** [comment]
@dinoocch Definitely not. Monitoring is firmly out of scope for NetBox. But you can quite feasibly pull data from NetBox to inform a monitoring system.

**Comment by puck** [comment]
Not sure if people are visualising their distribution boards currently, but I have each distribution board as a rack and I've added a "device" which has the appropriate number of outputs for each circuit (both 1P and 3P).

**Comment by travisn08** [comment]
It would be most helpful if we could see a convenient rack view of the power budget (used/total) kW in a rack.  Even if total kW is a static field define per rack and used is an accumulation of watts defined per device [type].

**Comment by nmp0906** [comment]
I would also like to see power capacity planning added via the following:

- Implement a "circuits" model for power (that the PDUs can plug into).  I am reading consensus in tracking upstream details like outlet type and specs.  I am looking at this from a colocation customer, but I could see how the colocation provider may need a lot more details.  (Maybe support multiple power paths as part of the power circuit model?  We could sort power system A and B separately and use below.)

- Allow per rack power utilization % similar to physical Us used.  This is covered in Issue #524.  We should be able to statically set a rack's power capacity or do some calculation off circuits located within.  We should work in a notation of watts to determine capacity since it can be normalized despite amp and voltage differences between circuits.  We need to consider A+B side (redundant) power path circuits with which we would want to mark one circuit as redundant so calculations are accurate.  This needs some more thought behind handling this.  See above for suggestion on adding A & B to a power circuit model.

- Each device should have a power spec defined.  I suggest a field for "max draw" or "design spec".  We see the vendors publishing higher maximum draws than real world so a second field for "average" or "expected" draw may also make sense.

**Comment by ksuuk** [comment]
@jeremystretch Can You provide ETA for this?

**Comment by rduffner** [comment]
I assume because Netflix is mostly in AWS (except for the OCA-boxes, and with them, it's most likely rarely Netflix' problem), there's no need internally for any sort of environmental monitoring (power, heat) and the capacity planning associated with it?
The joys of physical servers....

**Comment by mmahacek** [comment]
I'm late to this conversation, but tracking power assigned to a rack doesn't make sense to me.  Many of our racks have two PDUs attached to different circuits.  We would like to track amps/phase/voltage/breaker/etc as above, but at the PDU level, not the rack level.  
Am I interpreting this issue correctly?

**Comment by jeremystretch** [comment]
Apparent power will be associated with a new PowerFeed model, instances of which may be assigned to a rack. In a typical datacenter environment you'd have two feeds per rack (primary and redundant), but that's entirely up to the user.

**Comment by nmp0906** [comment]
Some high density configurations have multiple redundant circuits.  The
last company i worked in we deployed dual A+B circuits per rack (30A each,
for 60A total available to the rack).    This is where my initial
description came from, having 4 circuits, two marked as redundant, and two
summed to show available power.  Tracking power allocated per device (by
design) against this total would be extremely useful.  NetBox is supposed
to be the reference of how things should be, so this is a good baseline to
compare actual power draw against.

**Comment by jeremystretch** [comment]
The bulk of this work has been completed and merged into `develop-2.6`. :tada:
