### ISSUE TITLE
Document LLDP / RPC support

### ISSUE THREAD

**Issue by eliezerlp** [digitalocean/netbox#541]
In `configuration.py` I came across this:

```
# Credentials that NetBox will use to access live devices.
NETBOX_USERNAME = os.environ.get('NETBOX_USERNAME', '')
NETBOX_PASSWORD = os.environ.get('NETBOX_PASSWORD', '')
```

It made me curious what this was about since I hadn't come across it in the documentation aside from the [optional settings](http://netbox.readthedocs.io/en/latest/configuration/optional-settings/#netbox_username) that relate.

I did find some details from @jeremystretch in the reddit thread [here](https://www.reddit.com/r/networking/comments/4k89ty/i_built_an_ipamdcim_thing/d3czlmx), [here](https://www.reddit.com/r/networking/comments/4k89ty/i_built_an_ipamdcim_thing/d3d7z7e) and [here](https://www.reddit.com/r/networking/comments/4k89ty/i_built_an_ipamdcim_thing/d3dc8bp).

**Comment by byrnbaker** [comment]
Have you gotten a device to pull successfully?

**Comment by jeremystretch** [comment]
Documentation and support will be provided once the RPC system has been re-implemented. The current implementation is not production-ready.
