### ISSUE TITLE
Prevent duplicate vlans

### ISSUE THREAD

**Issue by harsh-kotak** [digitalocean/netbox#546]
I was adding vlans for tentants using Import vlan feature but accidentally I imported the same csv data multiple time. Can we have an option to prevent duplicate vlan or at least an option to select mutiple vlans and then delete?

**Comment by jeremystretch** [comment]
NetBox will allow the creation of duplicate VLANs within a site, except within a defined VLAN group. This is to allow sufficient flexibility to represent the real world, where VLAN IDs may be reused within a site. Each VLAN ID within a VLAN group, however, must be unique. You can enforce unique VLAN IDs per site by creating a single VLAN group per site.
