### ISSUE TITLE
Add Comments to Device After Creation

### ISSUE THREAD

**Issue by bradical987** [digitalocean/netbox#548]
Currently, adding comments to a device seems to be limited to device creation. It would be very helpful to modify comments on a device after creation from the `/dcim/devices/<device_id>/` page of the web UI.

**Comment by jeremystretch** [comment]
Not sure I follow. Comments can be edited along with all other parameters of a device by clicking the "edit device" button.

**Comment by bradical987** [comment]
It's a Monday...
