### ISSUE TITLE
Prefixes with children, caret doesnt expand list

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#55]
I have a /20 prefix with 16 child prefixes underneath

When I view my prefix table this /20 shows a caret that should expand to show me my 16 /24's (the screenshots show this is how it should work)

In both the latest Chrome and Safari I am not able to expand the view by clicking the caret

**Comment by jeremystretch** [comment]
This is expected behavior. The carat merely signifies that the prefix contains one or more children. Although it's reasonable to expect the carat to expand the parent. We don't have any jQuery in place for that currently, but I'll mark this as an enhancement.

**Comment by jeremystretch** [comment]
Seems that by now most people are used to the way the prefix list works. I'd still like to enable responsive expansion of the hierarchy, but it'll have to come as part of a future API-driven UI (perhaps in v3.0).

**Comment by traveler3468** [comment]
adding my +1 here. I think the carat should expand the child prefixes. Makes it alot more user friendly to be able to just find them in the list rather then loading different pages.

**Comment by bdlamprecht** [comment]
Added a +1 also as I agree with both `bellwood`  and `traveler3468`, but I'm okay waiting for until v3.0 time frame for this to happen.

**Comment by nschmalenberger** [comment]
I think this would be super nice also :)

**Comment by snowie-swe** [comment]
Would love to see this feature.
Having a /16 with multiple /24 that is then divided up in /30s.
Current way of expanding all is not usable in our case.
