### ISSUE TITLE
Upgrade but version not change

### ISSUE THREAD

**Issue by anhnvname** [digitalocean/netbox#553]
Hello,

I download the latest version (1.6.0) and replace to older source but it's still show 1.5.2

**Comment by jeremystretch** [comment]
Please follow the [upgrade instructions](http://netbox.readthedocs.io/en/latest/installation/upgrading/).

**Comment by leandroteleco** [comment]
I have the same problem... I followed the upgrade instructions, for a Netbox docker container version.
