### ISSUE TITLE
Upgrade Netbox with Docker

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#560]
Hi,

Can you tell me how to upgrade Netbox when I use Docker ?

Thanks in advance.

Thomas

**Comment by leandroteleco** [comment]
I have the same problem too. I think that the only solution is to delete the old container and setup a new one.

**Comment by rfdrake** [comment]
This should rebuild the container and reuse the data you already have.  You should make a backup of the containers before you do this, just in case.

     git pull
     docker-compose build --no-cache
     docker-compose up -d

**Comment by thoms27** [comment]
Thank you very much :-)

**Comment by leandroteleco** [comment]
Thank you very much :-)
