### ISSUE TITLE
Custom field values should be accessible in export templates

### ISSUE THREAD

**Issue by jeremystretch** [digitalocean/netbox#561]
Currently, there is no way to access an object's custom fields from within an export template. Ideally, these fields should be accessible similar to any real attribute. For example, an object with a custom field named `color` should be accessible as such:

```
{% for obj in queryset %}
    Color: {{ obj.cf.color }}
{% endfor %}
```

We want to use a designated attribute (`cf`) to avoid collisions with existing attributes.

**Comment by jeremystretch** [comment]
Of course, immediately after releasing v1.6.1, I realize that I never finished renaming the `get_custom_fields` method, so `cf()` doesn't actually work inside export templates.

**Comment by jeremystretch** [comment]
Fixed in 325d96dabb050ac6edb937cb7210598fff83a265

**Comment by DevilWAH** [comment]
Hi I know this is closed but what if the custome fieled has space in name? "CDE Scoped"

{{ device.name }} ,{{ device.serial }},{{ device.primary_ip }},{{ device.cf }} 
works, if a bit messy. 
but 
{{ device.name }} ,{{ device.serial }},{{ device.primary_ip }},{{ device.cf.cde-scoped ]] 

gives a rendering error?

**Comment by jeremystretch** [comment]
Didn't think spaces were valid in the name but it appears they are. They shouldn't be. Just use an underscore or hyphen in the field name instead of a space. You can set a separate human-friendly label to be displayed on the UI.
