### ISSUE TITLE
Feature request: Way to export rack loadout

### ISSUE THREAD

**Issue by R4v3nH0lm** [digitalocean/netbox#565]
Love what you guys have setup here. Been playing with it for the last two weeks and was looking for a way I could share what was in Netbox with my integrator. Ideally something that shows both the rack drawing and a table with devices installed. Not finding a way to do that. If this could be added as a feature that would turn this project into one of my staple utilities.

**Comment by jeremystretch** [comment]
It sounds like the rack elevation view and per-rack device list would suffice. Could you go into more detail about the format you'd like to see please?

**Comment by R4v3nH0lm** [comment]
Right, the elevation view would work but I need a way to share it with people outside of my org. When I try to print it off from the webpage directly it gets jumbled up and removes color from the devices. 
[NetBox - LAS1 - Rack 159.pdf](https://github.com/digitalocean/netbox/files/496844/NetBox.-.LAS1.-.Rack.159.pdf)

Totally open to hearing how you accomplish this.

**Comment by AlexanderS** [comment]
@R4v3nH0lm You may want to select "Background graphics" in the advanced options of the printing dialog.

**Comment by jeremystretch** [comment]
Sorry, this was closed by mistake earlier.

**Comment by jeremystretch** [comment]
I'm going to fold this one in with #160. Assigning the duplicate label mostly just to indicate that the discussion is being continued elsewhere.
