### ISSUE TITLE
Not able to use LDAP Auth

### ISSUE THREAD

**Issue by blortox** [digitalocean/netbox#566]
Hi there,

I'm currently not able to get LDAP auth working. I seem to have set it up correctly, and have worked with our sysadmin who usually sets up LDAP.

Our current configuration is as follows: http://pastebin.com/DhMA5ny2

the documentation on this is so scarce, it's pretty hard to figure out as to whether this is an LDAP issue

(dc's and passwords have been removed).

We cannot see any kind of authentication hitting out ldap server.

TIA,

**Comment by jeremystretch** [comment]
Closing this out as it doesn't appear to pertain directly to the code base. Please consider posting on the [netbox-discuss](https://groups.google.com/forum/#!forum/netbox-discuss) mailing list for assistance.
