### ISSUE TITLE
Backing up production data.

### ISSUE THREAD

**Issue by lachlanjholmes** [digitalocean/netbox#567]
Hey,

Just wanting to know what is recommend the best way to export/backup the data that has been placed into netbox system?

The wiki and docs doesn't really talk about it.

thanks.

**Comment by eronlloyd** [comment]
Because the data is stored in PostgreSQL, the best thing to do is become familiar with standard [PostgreSQL backup and restore procedures](https://www.postgresql.org/docs/9.5/static/backup.html). As for exports, that could be implemented as a CSV download link from Netbox.

**Comment by jeremystretch** [comment]
As @eronlloyd said, a simple PostgreSQL dump will do it. For example:

```
sudo -u postgres pg_dump netbox > netbox.sql
```

To restore the data to an empty database:

```
sudo -u postgres psql netbox < netbox.sql
```

**Comment by Ra1esh** [comment]
Hi, 
I am trying to migrate netbox but I am failing at the restoring part.
I ran the command "sudo -u postgres psql netbox < netbox.sql" for restoring and I am getting the following error. I think it has to do with some permissions but not sure. I am not much familiar with postgres db, docker etc. but somehow I was able to get netbox running. 

Thanks.

After I run the command I am getting the following error 


qsudo -u postgres psql netbox < db_dump_2018-12-03.sql 
could not change directory to "/root/netbox-docker"
SET
SET
ERROR:  unrecognized configuration parameter "idle_in_transaction_session_timeout"
SET
SET
SET
SET
ERROR:  unrecognized configuration parameter "row_security"
S

**Comment by mchlumsky** [comment]
Just for completeness, you should probably also backup the media and report directories.

**Comment by AllenEllis** [comment]
In case it's helpful, this is the bash script I'm using to push database exports to Dropbox. It's smart enough to compare the checksum against the last backup and only save & push dumps that are changed from the last one.

I cloned [Dropbox-Uploader](https://github.com/andreafabrizi/Dropbox-Uploader) to `/opt/Dropbox-Uploader` and followed his installation steps.

Then I created this file in the home directory of the `postgres` user (`var/lib/postgresql/backup.sh`)

```bash
#!/bin/bash

time=$(date +%Y%m%d-%H-%M-%S)
filename=/tmp/netbox-backups/netbox-$time.sql
pathtochecksum=/tmp/netbox-backups/latest.md5

echo "Running Netbox backup at $time"

# backup the database
/usr/bin/pg_dump netbox > $filename

# generate a checksum of the backup
md5=($(md5sum $filename))

# compare against last checksum
lastmd5="`cat $pathtochecksum`"
if [ "$md5" = "$lastmd5" ]; then
        echo "Backups match, removing this instance"
        rm $filename
else
        echo "New checksum, pushing to Dropbox"
        /opt/Dropbox-Uploader/dropbox_uploader.sh upload /tmp/netbox-backups/netbox-$time.sql .
        echo "$md5" > $pathtochecksum
fi
```

To automate it, I switched over to the postgres user (`su - postgres`) and added this to its crontab (`crontab -e`)
```bash
* * * * * /var/lib/postgresql/backup.sh >> /tmp/netbox-backup/backup.log 2>&1
```

Per @mchlumsky, this doesn't include the `media` or `reports` directories and my script doesn't include those.
