### ISSUE TITLE
Device List and Rack Group Filter

### ISSUE THREAD

**Issue by MrDragon** [digitalocean/netbox#571]
Minor little thing (probably a typo):

In 1.6.1-r1 I noticed that when I show a device list (Devices -> Devices), the filter choices under "Rack Group" aren't a list of the Rack Groups, but a list of the Sites.

The "Rack Group" filter under "Racks -> Racks" is perfectly fine.
Sorry - I don't know if it's a new thing or if it has been there and I just didn't notice sooner

**Comment by jeremystretch** [comment]
_Sigh_

**Comment by LBegnaud** [comment]
Don't beat yourself up @jeremystretch 

Just want to chime in to thank you for the hard work. Our company appreciates the wonderful software.
