### ISSUE TITLE
Multi-Site Topology Maps

### ISSUE THREAD

**Issue by sp0rus** [digitalocean/netbox#578]
Having a way to view a multi-site topology map would be fantastic.  We have multiple connections going to different sites for different networks.  We are a small ISP, and we have each hub and building around town as a separate site.  Being able to see all of our connections between sites would be fantastic.

**Comment by jeremystretch** [comment]
Site assignment is optional for topology maps. In theory, you could create a topology map which includes devices from multiple sites and it will be rendered. There are two issues that we need to address, however:

* Topology maps without a site assignment are not currently referenced anywhere. This is easily remedied by linking to them on the NetBox home view.
* Topology maps do not render circuits. It should be fairly easy to extend the rendering logic to include circuits (which are now modeled very similar to interface connections).
