### ISSUE TITLE
LLDP Question

### ISSUE THREAD

**Issue by R4v3nH0lm** [digitalocean/netbox#580]
Have a question about getting LLDP to work.

I am putting a multi-slot chassis in Netbox. Specifically a Cisco 9508. Created a device for the chassis with 8 slots and put a mgmt IP on it. After that I created a new device for each line card but did not give them mgmt IP's as they would all have the same one as the chassis. Will Netbox still pull LLDP for the chassis and show the neighbor information for the individual line card interfaces?

**Comment by jeremystretch** [comment]
> I created a new device for each line card

Line cards aren't devices; they don't have their own control plane. You should create a single device to represent the entire switch, and optionally create modules to represent the individual line cards.

I'm going to close this out as it doesn't pertain to the code base, but please feel free to raise the issue on the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by R4v3nH0lm** [comment]
Ah! Thank you very much for answering my question. I will move over to the mailing list for future questions.
