### ISSUE TITLE
update comment field for dcim_device

### ISSUE THREAD

**Issue by nielipin** [digitalocean/netbox#582]
I've got the following exception after updating device comment:

> type 'exceptions.ImportError'>
> 
> Failed loading extension 'mdx_gfm' from 'mdx_gfm', 'markdown.extensions.mdx_gfm' or 'mdx_mdx_gfm'

Any idea why ?

**Comment by jeremystretch** [comment]
Looks like you're missing `py-gfm`. You can run `pip install -r requirements.txt` from the root NetBox directory to install it and any other missing dependencies.

I'm going to close out this issue, but please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you need further assistance.

**Comment by nielipin** [comment]
Yes, that's it!
Perfect, thanks
