### ISSUE TITLE
Implemente VFI ressources

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#583]
Hi,

Is it possible to implemente VFI concept like VRF to manage VPLS area ?

Thanks in advance.

Regards,

Thomas Vahé

**Comment by jeremystretch** [comment]
I'm not too familiar with VPLS, but that seems like it'd be a little too esoteric. NetBox supports the concept of a VRF primarily because it's needed to organize IP space.

**Comment by thoms27** [comment]
Hi,

You 're right, it's not essential in a datacenter environment. For the ISPs, I think.
I ask because I want to set up VPLS in our MPLS network to provide L2VPN to the customers.

Thanks for your answer.

Thomas Vahé
