### ISSUE TITLE
User login Issue

### ISSUE THREAD

**Issue by pankaj00733** [digitalocean/netbox#585]
I am unable to open the site and yesterday I was not able to login with username:- admin and password:- demo

**Comment by monu-daffodil** [comment]
same problem occurs to me,i am also unable to login with username:admin and password:demo

**Comment by jeremystretch** [comment]
The demo has been taken offline until further notice. Closing this as it does not pertain to the NetBox code base.

**Comment by pankaj00733** [comment]
Hi Jeremy,

When will be the demo online. Please let us know.

Best Regards,

Pankaj | Sr. Software Engineer
*Daffodil Software Ltd.*
