### ISSUE TITLE
Add APIs that use unique slug instead of ID

### ISSUE THREAD

**Issue by dqminh** [digitalocean/netbox#586]
I dont feel like uniquely generated ID is the right abstraction for restful API given that most entities already have unique human-readable name (i.e. slug/name etc.). I think being able to use slug as part of the queries to identify resources instead of IDs would improve the API.

Since we already have API with ids, wdyt about adding `api_prefix/slug/<slug>` for this ?

**Comment by jeremystretch** [comment]
Adding entry points for slugs duplicates much of the API. This also leads to inconsistencies as not all objects have slugs. Slugs were only implemented in the web UI to make the URLs a bit easier to understand at a glance.

**Comment by dqminh** [comment]
@jeremystretch thanks. Duplicating the api is certainly one valid reason. This is not too important now actually so i will close the issue.
