### ISSUE TITLE
Add "Cable ID" field between connections and a search option

### ISSUE THREAD

**Issue by edgaraafelix** [digitalocean/netbox#589]
When connecting two interfaces we need to identify which unique "Cable ID" is used.

![425706880_7405930269347016642](https://cloud.githubusercontent.com/assets/3910766/19001493/5fe3c3e0-873f-11e6-8ec3-d0cb48906c74.jpg)

With this implemented a search option by "Cable ID" in NETBOX's main page would useful.

The same can be applied to all "connect" options, e.g.: console, power...

**Comment by jeremystretch** [comment]
This would be covered by #20.

**Comment by robbagithub** [comment]
Any chance of putting this feature in?

**Comment by lancesdavis** [comment]
+1

On Thu, 4 Oct 2018 at 06:31, robbagithub <notifications@github.com> wrote:

> Any chance of putting this feature in?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/e922160ecca78fe55bdd25af504f87486fb8dcc5?url=https%3A%2F%2Fgithub.com%2Fdigitalocean%2Fnetbox%2Fissues%2F589%23issuecomment-426890349&userId=1764703&signature=c33508ba54b60a90>,
> or mute the thread
> <https://mailtrack.io/trace/link/7f071b3fce2ddbb16e1e2767b6c840f235c31d74?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAkXHkp2QmuW00V6eoqxJ7cV3iQX71i30ks5uhZ0pgaJpZM4KLWa3&userId=1764703&signature=c00641a5d6492f95>
> .
>


-- 

*Lance Davis  MSc MIET MBCS*

*Technical Director - Teledata Group*

TeleData UK www.teledata.co.uk
<https://mailtrack.io/trace/link/481f917f06a0b140b620e6cd518cf38478719a09?url=http%3A%2F%2Ft.sidekickopen06.com%2Fe1t%2Fc%2F5%2Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg64kqDCW2BgLPT3N1Hh4W643TLH56dKpbf4c5KcT02%3Ft%3Dhttp%253a%252f%252fwww.teledata.co.uk%252f%26si%3D6565329426710528%26pi%3Ddbc8ed2d-5ced-489b-bd24-d68d6e347fd8&userId=1764703&signature=0f63b8da4823e80e>
|
Enterprise Class Data Centres & Colocation

Advanced Signal Monitoring www.asmuk.net
<https://mailtrack.io/trace/link/a6001d06595374d7c23496aa7f74d8ca81122b03?url=http%3A%2F%2Ft.sidekickopen06.com%2Fe1t%2Fc%2F5%2Ff18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg64kqDCW2BgLPT3N1Hh4W643TLH56dKpbf4c5KcT02%3Ft%3Dhttp%253a%252f%252fwww.asmuk.net%252f%26si%3D6565329426710528%26pi%3Ddbc8ed2d-5ced-489b-bd24-d68d6e347fd8&userId=1764703&signature=07f92f1f4185c71d>
 | NSI Gold Approved Alarm Receiving Centre


*T:* *0333 888 4083*

*M:* *07703 196010*

*E: lance.davis@teledata.co.uk <matt.edgley@teledata.co.uk>  *

This message is private and confidential. If you have received this message
in error, please notify us and remove it from your system. Teledata UK Ltd
is registered in England and Wales no 5656736 registered office: Delta
House, Wavell Road, Manchester, M22 5QZ

**Comment by cioby23** [comment]
This is already in progress check this commit https://github.com/digitalocean/netbox/commit/3eddeeadc56a24e4b7574ea918159c0660943e05

**Comment by robbagithub** [comment]
Outstanding. Great news. Don't suppose there is a rough ETA?
