### ISSUE TITLE
add interface/port buttons missing on device type

### ISSUE THREAD

**Issue by bleything** [digitalocean/netbox#591]
In v1.6.2 the Add Interface/Console Port/etc links are missing from the device type show page. Here's what I am seeing:

![screenshot 2016-10-02 13 57 24](https://cloud.githubusercontent.com/assets/270/19023644/59784552-88a8-11e6-877b-15531bf5d35e.png)

And here's what I'm pretty sure I'm meant to be seeing:

![screenshot 2016-10-02 13 57 45](https://cloud.githubusercontent.com/assets/270/19023647/6256b424-88a8-11e6-889b-e32d05c40486.png)

Through the magic of git bisect I have identified 30c7c2d359f59165093274d6f560bbce1a62f1da as the commit which broke this. It looks like it's the [conditional on line 8 of `netbox/templates/dcim/inc/devicetype_component_table.html`](https://github.com/digitalocean/netbox/commit/30c7c2d359f59165093274d6f560bbce1a62f1da#diff-9bd2b5a22068ed7c8f53e931cc5ebf98R8)... if I remove that conditional block, I get the buttons back.

I'm guessing that the idea there was to make that button disappear if there were between one and ten rows in the table and then reappear if there were ten or more. If that's right, then I think that changing it to `{% if table.rows|length > 10 or table.rows|length == 0 %}` will do the trick. I can submit a PR if y'all want.

**Comment by therealjoshuad** [comment]
I just noticed that I'm getting the same behavior.

**Comment by jeremystretch** [comment]
Derp. I'll try to get a fix out today. Thanks for catching this!

**Comment by jeremystretch** [comment]
This has been fixed in [release v1.6.2-r1](https://github.com/digitalocean/netbox/releases/tag/v1.6.2-r1). Still need to apply the patch to the `develop` branch.

**Comment by bleything** [comment]
Great! Thank you so much :grinning:
