### ISSUE TITLE
Feature Request - Assign Services to Devices

### ISSUE THREAD

**Issue by pettcomputers** [digitalocean/netbox#597]
In our organization, we would like to be able to assign multiple services to devices and tenants in Netbox so that we can quickly identify all devices related to a particular service/product we offer.  

I was thinking this could be accomplished two different ways, what are your thoughts?
1.  Add a new service category within the application that lists services, then attach the services to each device that the service relies on, or 
2.  Add a listbox custom field that allows multiple selections so we can add a custom field to each device that allows us to select one or more services that rely on the device like the screenshot attached. 

![selections](https://cloud.githubusercontent.com/assets/20682729/19080623/41179b22-8a1d-11e6-8054-f7351513ea01.png)

**Comment by jeremystretch** [comment]
This sounds like a good use case for custom fields. The concept of a "service" is going to vary drastically among organizations.

**Comment by pettcomputers** [comment]
Is there a way to possibly add a custom field that allows multiple selections like in the screen shot?

**Comment by jeremystretch** [comment]
Unfortunately, no: custom selection fields are single value only. Sorry, but we can't extend NetBox to fit every need.

**Comment by pettcomputers** [comment]
No worries, I understand.

**Comment by jeremystretch** [comment]
I'll leave this open for a while to see if there's any other interest in something like this, just in case.

**Comment by pettcomputers** [comment]
Thanks!

**Comment by askbow** [comment]
Won't this need be (at least partly) addressed by #132 ?

**Comment by jeremystretch** [comment]
True, #132 will probably be sufficient to address this.
