### ISSUE TITLE
Create new Rack in Rack Group

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#60]
Can we please have a button that allows you to create a new rack while in the rack group view.

Saves exiting that view itself.

Thanks
Shaun

**Comment by jeremystretch** [comment]
The rack group view is just the rack list with a filter applied. It has an "add a rack" button at top right. Can you paste the URL of the view at which you'd like to see the button?

**Comment by rackcentral** [comment]
HI Jeremy,

Actually after looking at how we use this further - i do not think this is required.

Thank you.
