### ISSUE TITLE
Allow referencing object attributes within custom fields

### ISSUE THREAD

**Issue by nothing-fr** [digitalocean/netbox#600]
Is it possible to implement use of variables for important info from a device ? for example :
- In custom fields : the use of %ip% insert the principal ip
- In comment : "%devicename% have a problem with %bay1%, have to contact %manufacturer% support"

This kind of things...

May be useful for connection schemes like ssh://%ip%
or even support links like http://dell.com/support/home/us/en/04/product-support/servicetag/%asset_tag%/research

So, in case of informations change, we don't have to change manually the custom fields.

**Comment by jeremystretch** [comment]
I can see this being useful for custom URL fields, but can't think of any other use cases.

**Comment by LBegnaud** [comment]
I second this idea. I'm not sure how useful it would be to all custom fields, but a simple extension of this idea would be custom fields with default format/syntax. Something that comes to mind would be a calculated link on all devices that sent you to some other system with information about the device (we have a configuration management system that could easily be tied in with something like this)

I.E. a custom field applied to all devices of a certain type that is uneditable on the device itself, but simply a link with replacement fields: https://config.management.server/q=%devicemgmtip%

**Comment by jeremystretch** [comment]
@LBegnaud that sounds more like a custom template that could be embedded in a view. For example, you could include a new panel on the device view with a like to `https://config.management.server/q={{ device.primary_ip }}`. Which would be cool, but probably something we'd want to handle separate from this particular issue.

**Comment by LBegnaud** [comment]
That is how I interpreted this original request, but if you think it should be a separate enhancement that's fine. Want me to create the request?

**Comment by jeremystretch** [comment]
Let's just leave this issue as it is. We might be able to address both uses with a simple template filter.

**Comment by jeremystretch** [comment]
I'm going to close this out as it seems to be pretty much identical to #969 (and #969 has more discussion).
