### ISSUE TITLE
Add Customer Section under Organization menu

### ISSUE THREAD

**Issue by thoms27** [digitalocean/netbox#603]
Hi,

I'm working for a small ISP, and I would like a customer section which reference the sites.

For exemple, a router of collect (in a DC) mutualize many customers under different interfaces (VLAN, ATM, PPP etc..)? I would like to attach an interface to a customer.

Do you see what I want to say ?

Thanks in advance.

Thomas V.

**Comment by thoms27** [comment]
To complete :

A CPE Device is attached to a Circuit (Link) which one is attached to a PE Device (Providers Circuit + interface), which one is attached to a Customer Site, which is attached to a Customer.

It is a simple vision of an ISP from beginning to end,

Regards,

Thomas V.

**Comment by jeremystretch** [comment]
It sounds like assigning tenants to objects will accomplish what you want. ("Tenant" is just a more generic term for customer.) You can assign tenants to sites, devices, and circuits.
