### ISSUE TITLE
Automatically discover IP addtresses

### ISSUE THREAD

**Issue by elauriault** [digitalocean/netbox#605]
The request is to add functionality to automatically add IP addresses by either scanning subnets with nmap in ipv4 or by snmp querying router for arp/neighbor tables for ipv4/ipv6. DNS requests could be made to fill the description field.

**Comment by jeremystretch** [comment]
Please see https://github.com/digitalocean/netbox/wiki/Why-NetBox-Doesn't-Scan-IPs
