### ISSUE TITLE
Too many extra movements when working with interface

### ISSUE THREAD

**Issue by Farataa** [digitalocean/netbox#610]
Hello.

Simplify please IPAM interface, if possible. When I want to add some IP, I need 
- to open window with prefix (http://netbox/ipam/prefixes/…)
- to search a free IP
- to open another one window with device (http://netbox/dcim/devices/…)
- to add a new interface
- copy&paste or to type new address via "assign address".

When I add a new IP without a prefix I have to manually check for existence of the prefix.

Is it possible to more than a simple algorithm for the most part of the action? 

For example:
- when I added a new IP on interface, automatically create a prefix if it does not exist

or
- to open window with prefix (http://netbox/ipam/prefixes/…)
- to search a free IP
- to select device, interface name and bind new ip for device interface from http://netbox/ipam/ip-addresses/add/?address=….  if the interface is not on device it is necessary to automatically create an interface and after that autmatically bind address on this interface.

Also, it would be good to add checkboxes to bulk delete or edit IP addresses on http://netbox/dcim/devices/… page.

Thank you for your project and work.

With best regards.

**Comment by Know1** [comment]
When I add a device it would be nice to select from a drop down of prefixes then drill into it and click the free IP
![image](https://cloud.githubusercontent.com/assets/7904452/19375848/035393b8-9224-11e6-8ba0-4987ee312cad.png)

rather than taking me to /dcim/devices/45/ip-addresses/assign/ where it currently goes

**Comment by jeremystretch** [comment]
> Is it possible to more than a simple algorithm for the most part of the action?

Creating an interface on a device and assigning an IP address to a device are two unrelated actions. It would not make sense to combine them.

> when I added a new IP on interface, automatically create a prefix if it does not exist

The user might not wish to create a prefix for every IP they track. We leave this up to the user.

> Also, it would be good to add checkboxes to bulk delete or edit IP addresses on http://netbox/dcim/devices/… page.

You can edit or delete IP addresses in bulk in the IP list view.
