### ISSUE TITLE
Feature Request: Show Prefixes in VLAN List

### ISSUE THREAD

**Issue by engageant** [digitalocean/netbox#613]
It would be helpful to show a list of prefixes associated with a VLAN on the /ipam/vlans page (and conversely, the associated VLAN on the /ipam/prefixes page).

**Comment by klkriegel** [comment]
Part of the same Feature Request would be to have the "Available" addresses show when I expand the prefix list.  This would save a few clisk when searching for space to assign to a new customer / device.

**Comment by eronlloyd** [comment]
How about assigning a range of VLANs to a prefix, too?

**Comment by jeremystretch** [comment]
There really isn't room in the table to show a list of prefixes for each VLAN in the list, or vice versa. That might change if we adopt a full-width layout, but we also have to consider the performance implications.

@eronlloyd A prefix can only be assigned to one VLAN. A VLAN can have multiple prefixes assigned to it.
