### ISSUE TITLE
Feature request: Cable serial numbers, type and length

### ISSUE THREAD

**Issue by lizard626** [digitalocean/netbox#619]
Hello, at my workplace we've started tracking cable connections with serial numbers. Would love to see this in Netbox.

For example, we may have a connection from a data center access switch to a server in another rack. There would be two cables involved - one from an interface on the switch to a patch panel port, then one from the other side of the patch panel port to an interface on the server. We would label the two cables as "C6-000001" and "C6-000002" (Cat 6 cable number 000001). Both cables could be looked up in a central spreadsheet to identify the full path of the connection.

Example CSV from our spreadsheet:
Device A,Device A Port,Cable #1 SN,Length,Patch 1 A,Cable #2 SN,Length2,Patch 2 A,Cable #3 SN,Length3,Device B,Device B Port
CoreSW9K01,Eth101/1/1,C6-000035,7 feet,14A/7A-1,C6-000061,3 feet,,,,HQDHCP01,Eth101/1/1
CoreSW9K02,Eth102/1/1,C6-000036,7 feet,14A/7A-2,C6-000062,3 feet,,,,HQDHCP01,Eth102/1/1

Other serial number examples:
C5e-000098 (Cat 5e)
MM-000024 (MultiMode fiber)
TW-000010 (Twinax)

Thanks!

**Comment by jeremystretch** [comment]
Please see #20
