### ISSUE TITLE
Cannot Edit Rack after creation

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#62]
Hi There,

If you try to edit a rack after it has been created - even without making a change and just hitting the save button we get the following error on the screen

![image](https://cloud.githubusercontent.com/assets/15832892/16404104/2f423ef0-3d3f-11e6-8f18-bec5c3b6259e.png)

**Comment by Gelob** [comment]
Please update to release 1.0.3 and see if that solves the issue. It was a bug fixed with https://github.com/digitalocean/netbox/pull/56

**Comment by jeremystretch** [comment]
This should be fully resolved in 1.0.3-r1, which is currently the latest release. A `git pull origin master` will pull that down.
