### ISSUE TITLE
[Feature Request] Hardware and Logical port on device with parent/child relation

### ISSUE THREAD

**Issue by nothing-fr** [digitalocean/netbox#620]
We are using 40G QSFP+ to 4x10G SFP+ cables and fiber :

![qsfp-4sfp10-01c-v2](https://cloud.githubusercontent.com/assets/3938579/19491686/2e27f3c4-9574-11e6-9284-6adb47ba24f4.jpg)
![quadwire_orange_fan_out_0](https://cloud.githubusercontent.com/assets/3938579/19491685/2e13570c-9574-11e6-850b-3a36fbcec50d.jpg)

Our switches are Force10 S6000 with 32x40G but with the possibility to "split" each port to 4x10G. We want to have the "real" view: 1-to-4 connection but also the "virtual" view: 4-to-4.

Is it possible to implement the use of Parent/Child port on a device ?
I'm thinking something like this : 

- fo-0/0 (Parent - Hardware)
  - te-0/0 (Child - Logical)
  - te-0/1
  - te-0/2
  - te-0/3

On a switch device :

![mockup1](https://cloud.githubusercontent.com/assets/3938579/19492453/04844bfa-9577-11e6-9542-fdcc9f0c2d03.png)

On a server device, the port would be the "hardware" one...

_Or make possible to connect 1 port to "n" devices (i'm ok if it's not possible to make the logical view, I know it's a lot of work and maybe not used by a lot of people)_

**Comment by jeremystretch** [comment]
Typically in this scenario, the parent port is replaced with its children ports. For example, on Junos, a 40GE port named `et-0/0/0` configured to function as 4x10GE would be replaced with four child ports named `xe-0/0/0:0` through `xe-0/0/0:3`. Does the Dell/Force10 stuff not do this?

I'd rather avoid introducing any more complex logic to the interfaces. If we added the concept of parent/child interfaces it would become very difficult to efficiently validate connections.

**Comment by nothing-fr** [comment]
It's the same on Force10, the fo-0/0 turn to te-0/0 - 3, but if i do this, it's only the "logical" part of the connection... not the physical one.

When i'm in front of my rack and netbox, i need to know the physical port (i know, i can deduct the physical from the logical but with a lot of port maybe not so practical)

Is it possible to connect 1 port to "n" devices otherwise ? (maybe a "i know what i do" button when making connections ? 😉  )

**Comment by jeremystretch** [comment]
> but if i do this, it's only the "logical" part of the connection... not the physical one.

When you install a 4x10GE fanout, you are actually replacing one physical port with four new ones. They're not just logical constructs like an SVI: each 10GE port is an independent physical link and can be brought up or down independent of its peers. The previous physical interface ceases to exist at this point.

NetBox intends to mirror this real-world behavior, by allowing you to define either a 40GE interface _or_ four 10GE interfaces. It seems that Force10's interface numbering in this case might not be ideal, but attempting to represent an interface that doesn't actually exist anymore would greatly complicate things.

**Comment by nothing-fr** [comment]
so, netbox is more for representating the logical network and only partially the physical one ? because my qsfp+ don't turn into four sfp+ physically speaking.
my qsfp+ connector is still the same on the switch end.

I think this need to be the reflected somewhere,but i maybe wrong. i'm not really used to dcim software.

**Comment by jeremystretch** [comment]
NetBox doesn't have any means of tracking fanout cables, no. These are essentially an extension of the switch chassis. I don't think we'll add anything like that as it would greatly complicate connection tracking while providing little benefit. Conceptually, there is no difference between a 32x40GE switch filled with 4x10GE fanouts and a 128x10GE switch (you'd just be hard-pressed to fit 128 embedded 10GE ports in a 1RU box).

**Comment by nothing-fr** [comment]
Ok, closing the issue then 😢

**Comment by nothing-fr** [comment]
Will do with the port naming :

- fo0/0
- fo0/0 - te0/0
- fo0/0 - te0/1
- fo0/0 - te0/2
- fo0/0 - te0/3
