### ISSUE TITLE
Sexier GraphViz view...

### ISSUE THREAD

**Issue by nothing-fr** [digitalocean/netbox#621]
Is it possible to add those to the graphviz view to have something more like [vis.js](http://visjs.org/examples/network/nodeStyles/circularImages.html) can do: 

![screen shot 2016-10-19 at 08 04 46](https://cloud.githubusercontent.com/assets/3938579/19507379/c4abe2ca-95d2-11e6-87a8-5226dbb1fb9f.png)

or [Like this](http://visjs.org/examples/network/exampleApplications/nodeLegend.html)

**Comment by jeremystretch** [comment]
> Add icon to device type
> Add color to vlans
> Change the droplist for choosing color for a color picker (10 colors vs. 16M)
> Add those to the graphviz view to have something more like vis.js can do

These are four unrelated requests. Please keep issues narrow and concise. I'll keep this open for the last item; I've removed the first three from your initial post.

**Comment by nothing-fr** [comment]
duly noted, sorry for that...

**Comment by jeremystretch** [comment]
There doesn't seem to be much interest in this, and practically speaking it's probably going to be a lot more effort than it's worth. I'm not sure the topology maps are a very popular feature of NetBox to begin with.

Closing this out for now but maybe we can resurrect it in the future.
