### ISSUE TITLE
[Enhancement] Copying ports from Device Type when the device already exist without it

### ISSUE THREAD

**Issue by nothing-fr** [digitalocean/netbox#629]
Example : 

- I've created a `device` with a `device type` without ports a this time
- I've added ports on my `device type`

Is it possible to copy the ports from a `device type` when the `device` was created before the ports existed in the `device type` ?

(sorry, if it's not crystal clear, i'm french and i don't know how to explain this clearly in english)

**Comment by jeremystretch** [comment]
New components that are added to an existing device type will not be automatically created on existing instances of that device type. This behavior is intentional, to avoid unintended modifications to devices.

You can, however, select a list of devices and add interfaces to them in bulk.
