### ISSUE TITLE
Integration with PHPIPam 

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#63]
Hi There,

We use phpipam for all our ip / vlan / dns management.

It would be great if we could link the systems together so we can provision from netbox and have it talk back to phpipam to link both systems together.

This would allow for the following to take place as an example;

1. Create customer in rack space
2. Assign device to rack space.
3. Allocate IP / Subnet / Vlan to device which makes a call back to phpipam API
4. Phpipam then allocates the subnet and it has connections from there to manage DNS so it would if setup like ours will auto provision PTR records etc for that device.

A scenario like this would allow for primary management to be handled by netbox rather than phpipam with netbox having more control and functionality other than being (for how we are using it) an asset system at the moment. 

Fantastic what you have done - really great project :)

Regards
Shaun

**Comment by bellwood** [comment]
IMHO I think extending Netbox to API your DNS would be much better than two systems with similar data.

We use PHPIPAM right now and while I find it flexible, it's not very polished or complete enough a solution for an ISP/DC.

The only thing that is has going for it is custom fields, but, it's turned the schema into a nightmare with everyone crowbarring every little thing into it

**Comment by jeremystretch** [comment]
Personally, I would advise strongly against running NetBox and phpIPAM in parallel. Redundant data never ends well. There's also a good chance we'll extend NetBox to support DNS records in manner similar to phpIPAM in the near future.

I'm going to close this issue in favor of the more generic #81 request for webhooks.
