### ISSUE TITLE
v1.6.3 select all feature will only refresh the page

### ISSUE THREAD

**Issue by jbro209070** [digitalocean/netbox#631]
When I click the select all button, no interfaces get selected. I selected a few interfaces manually and then hit select all and it removes all of my selections, so im assuming it is only refreshing the page.

**Comment by jeremystretch** [comment]
Sounds like you might not have rebuilt static files after the upgrade. Try running `./manage.py collectstatic` and forcing a refresh in your browser.

**Comment by jbro209070** [comment]
that fixed the issue, thanks Jeremy.
