### ISSUE TITLE
Is it possible to enter a child device without device name?

### ISSUE THREAD

**Issue by serg2002** [digitalocean/netbox#636]
Hi,
Thanks for the great application. I've just started using it and i have a few questions.
Could you please tell me how to deal properly with child modules that don't have a device name?
Let say we have HP ProCurve 5412zl switches. The switch has 12 slots. I created a parent device type with 12 bays, then I created child device type with 24 interfaces. Then I realized that I need to create a separate device for each module to populate bays, but that is not very convenient. Another way is to create network switch with 288 network interfaces, what is not very good as well.
Another example is HP BladeSystem 7000 chassis. Each of our chassis has two inserted GbE2c Ethernet Blade Switches with 5 interfaces each. It would be nice do not treat them as separate devices, but as parts of a parent device.
Is it possible to create child devices without creation separate network devices?
What should I do with devices that are temporary not in use. Create 'storage' rack to keep not used devices?
Thank you.

**Comment by jeremystretch** [comment]
Hi. The issues here are primarily for bug reports and feature requests related to the development of NetBox. For general discussion, please raise your questions on the [NetBox mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). Thanks!
