### ISSUE TITLE
Device import RU size field.

### ISSUE THREAD

**Issue by Mattallmighty** [digitalocean/netbox#64]
Under 'Devices' -> 'Import Devices', can you please have a field for height type.
This would drastically reduce my time in manually having to go into each device and specify the height of each device.
Currently importing 1000's of devices and without this, it is going to be a time-consuming process.

got to say a very good job! Thanks again for taking the time to make this.

**Comment by jeremystretch** [comment]
The height of a device is defined by its device type. For example, if I create a device type called "Juniper SRX650" with a U height of 2, each instance of that device type will have a height of 2U. It's not possible to set the height of individual devices.
