### ISSUE TITLE
Invalid Key detected: list index out of range

### ISSUE THREAD

**Issue by haup** [digitalocean/netbox#640]
When i am trying to add a secret to a device, netbox is raising an exception with list index out of range message. According to forms.py in secrets module this exception is beeing raised while the private key gets checked. But i generated the key in my profile settings, so the key should be ok. Which information should i provide?

**Comment by haup** [comment]
I updated to the latest github version and re-tested it with Chrome and Firefox and now it is working on Firefox and Chrome with empty cache.

**Comment by jeremystretch** [comment]
Going to close this out as it seems you've got it working now.
