### ISSUE TITLE
Problem with selecting and sorting

### ISSUE THREAD

**Issue by serg2002** [digitalocean/netbox#645]
Hi,
1. When I click 'select all' nothing happens. No interfaces or bays are selected.
2. Created a few interfaces for testing A[1-4], then B[1-4]. Sorting order is:
A1
B1
B2
A2
B3
A3
A4
B4
When I added C[1-4] it was even worse. It was sorted but numbers first, letters just randomly. Is it possible to order them in alphabetical order?
Thank you.

**Comment by jeremystretch** [comment]
Please see #284
