### ISSUE TITLE
Option to reference a Authentication Server

### ISSUE THREAD

**Issue by barbosm** [digitalocean/netbox#650]
Hi,

It's possible to reference an authentication server in the device settings ? 

So in addition to putting the device admin credentials it would be possible to know that the device is able to authenticate against a specific RADIUS/TACACS server.

Best Regards

**Comment by jeremystretch** [comment]
You can easily create a custom field to do that.

**Comment by barbosm** [comment]
Yes, that was my first thought, but from what I saw it's not possible to link to an existing device in the selection field, but I guess that the same logic would apply for things like link a ESX server to an Storage etc... So maybe the value vs complexity in this issue is low.

I'll follow through using the custom fields as suggested, thanks!
