### ISSUE TITLE
Nginx returns "502 Bad Gateway"

### ISSUE THREAD

**Issue by tmack8080** [digitalocean/netbox#651]
I followed the install instructions line for line but after installing the Nginx http server and navigating to http://hostname, nginx returns a 502 Bad Gateway error.

#nginx -t nginx.conf passes its test.

Anyone have any ideas?

**Comment by jeremystretch** [comment]
GitHub issues should really be reserved for feature requests and bug reports. If you've encountered an issue with installation, please seek help on the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) or IRC (#netbox on Freenode).

**Comment by tmack8080** [comment]
Thanks
