### ISSUE TITLE
'ascii' codec can't encode character u'\u0421' in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by galaxydata** [digitalocean/netbox#657]
<type 'exceptions.UnicodeEncodeError'>

'ascii' codec can't encode character u'\u0421' in position 6: ordinal not in range(128)
![_065](https://cloud.githubusercontent.com/assets/4956197/19840416/2dbdbcd2-9f17-11e6-8f44-207b4e7fdc16.png)

**Comment by jeremystretch** [comment]
Fixed in d97dd26
