### ISSUE TITLE
Interface Form Factors for Storage

### ISSUE THREAD

**Issue by m4c3** [digitalocean/netbox#659]
Hello,
please add Interface Form Factors for serial attached scsi:

SFF-8470 / SAS
SFF-8088 / Mini SAS
SFF-8644 / Mini SAS HD

Thanks

**Comment by jeremystretch** [comment]
IMO non-networked storage is out of scope for NetBox.

**Comment by m4c3** [comment]
i only want to keep track of the physical connections between disk shelfs and the storage controller..

**Comment by jeremystretch** [comment]
NetBox currently tracks only console, power, and networked interfaces. This would add an entirely new class of connection, which I think extends beyond the scope we want to focus on in the near term. I can see how it would be beneficial to incorporate, however there is no shortage of feature requests competing for implementation.

**Comment by madmouser1** [comment]
@jeremystretch is there any chance of revisiting this request? even if it is just added as stacking types? I am sure there is many users that will benefit from this (everyone with DAS, NAS and SAN implementations that has some type of SAS in the infrastructure).

Thanks
