### ISSUE TITLE
Child device using multiple bays

### ISSUE THREAD

**Issue by quentinsch** [digitalocean/netbox#662]
In some cases it is necessary to occupy multiple bays with one child device in a parent device. For example, if you have a blade with uses two bays in an enclosure.
So it would be nice if you can select which bays are occupied by the child device.
In the screenshot below the first blade use bay 5 and bay 13, the next one 6 and 14 and so on.

![schermafbeelding 2016-11-01 om 15 25 03](https://cloud.githubusercontent.com/assets/7438854/19892977/b69907f6-a047-11e6-841c-05bac3777591.png)

**Comment by jeremystretch** [comment]
I'm not sure it's worth extending the data model and validation to support what I imagine is a fairly uncommon use case. A reasonable workaround might be to simply assign the installed modules to the lower-numbered bays and optionally delete the higher-numbered bays from NetBox.

**Comment by quentinsch** [comment]
Thanks for the workaround, I'll take a look if this could work for me.
I do think this is mainstream hardware and will be quite common in a lot of situations for other people. In this case it is a standard HP C7000 enclosure with HP BL685c blades which are used quite a lot around the world.

**Comment by mlorentz75** [comment]
Consider the DELL M1000e which has 16 slots in 2 rows (1-8, 9-16). There are double height CPU blades like the M820 and there's a double width storage blade, the Equallogic PSM4110E. It would be nice if this could be documented correctly in Netbox. A single DELL M820 occupying for example slots 1 and 9 can also make use of the backplane, usually ethernet ports of both slots. Wouldn't be right to leave slot 9 empty or delete it as suggested or put a fake blade into that slot in Netbox in my opinion.

IBM Bladecenter has optional storage extensions housing two hard disks which are mounted onto CPU blades and occupy the next slot but these don't use backplane ports of the second slot.

Though not that common, there are some network elements in the telecoms world like DSLAMs where line cards in chassis are sometimes double wide.

**Comment by jeremystretch** [comment]
After thinking about this some more, it's too much complexity to introduce just to track a corner case. The suggested workaround is to simply leave the secondary slot blank, or just delete it from the parent device.

> Though not that common, there are some network elements in the telecoms world like DSLAMs where line cards in chassis are sometimes double wide.

These are line cards, though, which would be represented as modules, not as child devices with their own control planes.

**Comment by ThePJMan** [comment]
Hello,
Just to clarify, Blades are not "uncommon" Almost every datacenter has these and in every case the chassis are shared with full high or half height Blades.

The code for this is not very complex but I think you might be looking at it from the wrong perspective.

To accomplish this what you need do to is in the Device type creation, if the "child" option is selected you need to add an additional field to select FULL or Half height

The code logic is then simple, if its FULL it means it used 2 slots, if its Half it uses only 1 slot.
You might even add a field called "span" witch choices Horizontal or Vertical.

You'd also have to add a field for the Chassis where you would specify the "span" to be horizontal or vertical. This depends on the chassis.  Most cases are Vertical though.

Anyways the code from there would be quite simple. If the child is FULL then to populate the bottom Bay with a blank that says "Extension of Slot-X" and prevent the ability to add a device in that slot.
To know which slot is the extension is also quite simple.  Divide the total Slot number by 2 this give you the total number of bays in each "row" for example a chassis with 16 bays has 2 rows of 8 bays (Half height)
If you populate bay 5 with a FULL height blade, simply add 8 (total number of bay per row) and you get 13 which is the bottom row. And assign a blank extension to slot 13.

Pretty simple

**Comment by jeremystretch** [comment]
@ThePJMan You're certainly welcome to submit a pull request and I'll take a look.
