### ISSUE TITLE
Search for MAC address

### ISSUE THREAD

**Issue by quentinsch** [digitalocean/netbox#663]
It can be very useful to have a search functionality for mac addresses. (Maybe build in the same field as the IP address search field?)
This can come in handy when troubleshooting L2 issues. Would be perfect with some wildcard functionality.

**Comment by eronlloyd** [comment]
Some MAC addresses are formatted differently, so it would be helpful to account for this when searching.

**Comment by hwinkel** [comment]
sorry!
