### ISSUE TITLE
custom fields for all data types

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#670]
It would be great if you could extend custom fields to all data types. Currently it is not possible to add custom fields for rack roles, device roles, tenants and so on.
If we could add those, we could add more fields to keep more specific information e.g. for our device roles.

**Comment by xenuser** [comment]
I second this. I have a specific device role (e.g. DB server) and would like to attach a custom field to servers with only this role. It would be confusing if all devices would have this custom field..

**Comment by jeremystretch** [comment]
Custom fields should be used sparingly, as they introduce a significant performance overhead. This overhead is reasonable when dealing with primary objects, but attempting to extend custom fields to secondary objects would introduce a much higher performance penalty. Further, it doesn't yield much value over assigning the custom field to an object directly.

> Currently it is not possible to add custom fields for rack roles, device roles, tenants and so on.

You can add custom fields to tenants.

**Comment by xenuser** [comment]
I understand that you don't want users to experience any performance impact. However, I think they should be able to decide for themselves if they take the risk or not. Not being able to assign custom fields to a certain device type or role is clearly a disadvantage.
