### ISSUE TITLE
Importing IP Addresses with DHCP status import as Active

### ISSUE THREAD

**Issue by Anthony25** [digitalocean/netbox#674]
Hello,
With the new status field added for IP Addresses in 1.7.0, I tested to import a range of DHCP addresses:
```
192.168.128.3/26,,,DHCP,,,,
192.168.128.4/26,,,DHCP,,,,
192.168.128.5/26,,,DHCP,,,,
192.168.128.6/26,,,DHCP,,,,
192.168.128.7/26,,,DHCP,,,,
192.168.128.8/26,,,DHCP,,,,
192.168.128.9/26,,,DHCP,,,,
```

It imports my addresses, but does not set their status to "DHCP", instead they are all marked as "Active".

Netbox 1.7.0
ArchLinux

Thanks!

**Comment by Anthony25** [comment]
Great, thanks a lot!

**Comment by jeremystretch** [comment]
Thanks for filing the bug! Will be out in v1.7.1, probably early next week.
