### ISSUE TITLE
Ability to bind graphs to certain objects

### ISSUE THREAD

**Issue by dimakus** [digitalocean/netbox#675]
Or objects to certain graphs.
Especially to interfaces.

**Comment by jeremystretch** [comment]
NetBox supports graphs for interfaces, sites, and providers. What specifically are you asking for?

**Comment by dimakus** [comment]
NetBox show **all** graphs for certain category.
Not so neccessary for sites and providers, but for huge amount of interfaces
its almost useless future.

**Comment by jeremystretch** [comment]
Sorry, still not understanding what the goal of this issue is.

**Comment by dimakus** [comment]
If i have 1000 interfaces, netbox show me all 1000 images. A lot of time to load them and hard to find
needed one.
Would be properly if by clicking on particular interface it show proper image(one or a few),
but not all 1000 images.

**Comment by jeremystretch** [comment]
> If i have 1000 interfaces, netbox show me all 1000 images.

Where are you seeing this?

**Comment by dimakus** [comment]
Device view, interface list on the right side, show graph button.
By pressing it pop up window with all graphs.
Maybe I don't understand something, but how it should show only needed graph,
if graph doesn't have corresponding field?
Button link has interface id, but graphs has only name, weight and urls in creation form.

**Comment by jeremystretch** [comment]
Graphs are templatized; you only need to define one and it gets displayed for every interface. Please see [the documentation](http://netbox.readthedocs.io/en/stable/data-model/extras/#graphs). You can create multiple graphs if you want to display different information and/or time periods.
