### ISSUE TITLE
Add newer setuptools to requirements.txt for Installation and possibly update installation documentation

### ISSUE THREAD

**Issue by zapotah** [digitalocean/netbox#677]
The current debian repo provided python-setuptools doesnt work with the pip installation. Python setuptools needs to be added or installed/upgraded first before the rest of the modules can be pulled with pip. Otherwise the installation will end with an error.

If adding setuptools to requirements.txt is enough, that will be that, but if it needs to be updated before pulling the rest of the dependencies, a step needs to be added to the installation documentation.

Platform debian 8.6 LXC
Netbox version: 1.7.0

**Comment by jeremystretch** [comment]
Adding an explicit entry for `cffi` (a dependency of `cryptography`) to `requirements.txt` seems to resolve the installation error. Verified on Debian 8.6.
