### ISSUE TITLE
Device history (user activity) / searchable history

### ISSUE THREAD

**Issue by quentinsch** [digitalocean/netbox#683]
It would be great if the history user activity can be shown for a device. This can be useful for auditing purposes and keeping track of changes.
For example if the 'last updated' is made clickable that you can see the history of the device.

![schermafbeelding 2016-11-11 om 10 55 54](https://cloud.githubusercontent.com/assets/7438854/20211227/d98a36f0-a7fd-11e6-80e8-068410dabf59.png)

**Comment by chagara** [comment]
agree. some of the logs and changes does not necessary mention what was changed but, that something happened.

**Comment by john-arvid** [comment]
I think this could be very usefull when a non-technical user is making an error. Which will happen several times.

**Comment by croax** [comment]
Same for circuits and such. A fully searchable audit history log would be great so it would be possible to drill down which entities have been changed, when, how, by who etc..

**Comment by Zimeon-** [comment]
We've received the same request from our users to have a log of who updated the device/ip/prefix/vlan. A more in depth log with what has changed could be a long term addition.

**Comment by MHammett** [comment]
Would a snapshot of what a rack\device\circuit\etc. was like at a certain prior date\time be an acceptable extension of this? IE: What was in this rack and how was it cabled three weeks ago?

**Comment by Zimeon-** [comment]
That would be cool for racks. Was more thinking of showing the log rows. Like "User x added device nnn". User Y modified device nnn" and user x removed device".

**Comment by MHammett** [comment]
*nods* You could essentially have a diff of beginning and end date\times of things that affected the scope of your search (rack, device, etc.). How it's presented isn't incredibly important.

**Comment by mk311d** [comment]
Also logging the device port allocation, who added/changed/modified something... Would be nice to have it right there for each port showing when and who modified it last time and let's say a button on which the user could click and would show the whole history of changes including the previous status.
The same type of logging could be applicable for IPs, racks, ports, child devices, ...

**Comment by awfki** [comment]
+1
This would be fine as a NetBox feature but sending syslogs with relevant info would be even better.

**Comment by jeremystretch** [comment]
Looks like this was covered by #1898 (change logging). This functionality will be incorporated in the v2.4 release.
