### ISSUE TITLE
Auto-create Device Type when bulk importing Devices from CSV

### ISSUE THREAD

**Issue by askbow** [digitalocean/netbox#684]
We are trying to import data on a number of sites that were growing over several years resulting in a zoo of different device types. At the moment that seems to require pre-creating individual device types prior to import.

Even considering #451 it might be useful to auto-create device types during import. At least for some it would speed up migration and adoption of netbox.

**Comment by jeremystretch** [comment]
A device type is more than a manufacturer and model number. It entails the physical characteristics of a device and what console, power, and network resources it has. This information must be provided by creating a device type prior to instantiating it as a device.
