### ISSUE TITLE
Modifying a Device Type doesn't update existing devices?

### ISSUE THREAD

**Issue by roblarose** [digitalocean/netbox#687]
We realized after creating several PDUs that they did not have Power Ports, but we do want to be able to track which UPS they're fed from.

Adding a Power Port to the device type didn't show one on existing devices, though.  We had to re-create all the PDUs.

Is there a way to update existing devices w/ changes to the underlying type?

**Comment by therealjoshuad** [comment]
Editing a device type doesn't edit the devices, you should be able to go to the device itself, and add a power port there

**Comment by roblarose** [comment]
Doesn't look like we were able to add power ports on our PDU device types.

--
*rob larose* | engineer | rock paper scissors | 212-255-6446 |
www.rockpaperscissors.com <http://rockpaperscissors.com/>

**Comment by therealjoshuad** [comment]
Do you have the little plus signs near the connections? Or am I thinking of something different?
![image](https://cloud.githubusercontent.com/assets/3893036/20232972/a241abea-a831-11e6-8937-3894b9978945.png)

**Comment by roblarose** [comment]
Nope.  I create a new device type with "PDU" checked and then create a
device of that type, then when I look at "critical connections" on the
device, power port is not an option.  Screenshots attached.

Other device types (non-PDU) allow me to add power ports.

[image: Inline image 3][image: Inline image 2][image: Inline image 1]

--
*rob larose* | engineer | rock paper scissors | 212-255-6446 |
www.rockpaperscissors.com <http://rockpaperscissors.com/>

**Comment by LBegnaud** [comment]
when you specify something as a pdu, the interfaces are considered power ports

**Comment by roblarose** [comment]
Which do you mean?  Interfaces still seems to be NICs.

I can add Power Outlets to the a PDU device, but I can only add a power
port (under "Critical Connections") on the Device Type.

--Rob

--
*rob larose* | engineer | rock paper scissors | 212-255-6446 |
www.rockpaperscissors.com <http://rockpaperscissors.com/>

**Comment by LBegnaud** [comment]
![image](https://cloud.githubusercontent.com/assets/15981748/20233768/ce08fcc2-a838-11e6-9a00-bf04e307fbd8.png)

When you define the device type, you uncheck "this is a network device" I believe

**Comment by roblarose** [comment]
Your screenshot shows outlets though, not plugs/ports.

We're doing UPS with outlets connected to PDU power ports/plugs, then the
PDU outlets connect to the device power ports/plugs.


--Rob

====
This message was composed
entirely with my right thumb.
Please excuse any typos.

On Nov 11, 2016, at 7:02 PM, LBegnaud <notifications@github.com> wrote:

[image: image]
<https://cloud.githubusercontent.com/assets/15981748/20233768/ce08fcc2-a838-11e6-9a00-bf04e307fbd8.png>

When you define the device type, you uncheck "this is a network device" I
believe

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/digitalocean/netbox/issues/687#issuecomment-260083696>,
or mute the thread

**Comment by jeremystretch** [comment]
Modifying the components of a device type does not retroactively modify existing devices. This is an intentional limitation to avoid conflicts.

NetBox doesn't currently allow you to add power ports to a device which is classified as a PDU, because there's no way to model the power circuits that feed PDUs. This is sort of a place holder for when we incorporate structured power (see #54).

This raises a bug in that a PDU device type can be assigned power port templates. I've opened #691 to address this. For now, we simply don't model anything upstream of the PDU; again, #54 is open to extend the data model for this eventually.

**Comment by roblarose** [comment]
Hi Jeremy,

   I see -- you're saying the lack of power ports is intentional and the
fact that i can add one to the type itself is the bug?  :-)

   We recognize that you don't model the AC source circuits, but I imagine
in the majority of use cases, you have at least 2 PDU devices in line (UPS
-> PDU -> Device) so I'd argue in favor of ability to assign PDU power
ports for that reason regardless of the state of #54.

   We're going ahead with our PDUs having power ports.  If/when you decide
to fix that "bug," will we have trouble, or just not be able to do it
anymore going forward from there?

--Rob


--
*rob larose* | engineer | rock paper scissors | 212-255-6446 |
www.rockpaperscissors.com <http://rockpaperscissors.com/>

**Comment by jeremystretch** [comment]
That's a fair point. NetBox was originally developed to represent data center environments in which power feeds external to each rack are delivered directly to PDUs. #691 will allow the assignment of power ports to PDUs; this will be available in v1.7.1.

Once we get around to #54, we'll likely model power feeds the way we do data circuits: a power port can be connected to either a power outlet (upstream device) or to a power circuit.

**Comment by roblarose** [comment]
Sounds great.  Thanks.  :-)

We love the product, btw -- just the thing for a smallish server room setup
like ours.

--Rob

--
*rob larose* | engineer | rock paper scissors | 212-255-6446 |
www.rockpaperscissors.com <http://rockpaperscissors.com/>
