### ISSUE TITLE
IP address of devices doesnt show up

### ISSUE THREAD

**Issue by soamz** [digitalocean/netbox#688]
I have added a device and also made an interface and assigned IP. 
You can see it here, 
http://prntscr.com/d6ap13

But when I goto devices, it shows blank on IP address column, 
http://prntscr.com/d6apbo

Whats the issue ?

What am I missing ?

Also, why cant I simply add IP to the IP address block ?
Why does it ask for /xx to use ?

I need to only show as 10.10.12.3 , not as 10.10.12.3/32
<img width="887" alt="screen shot 2016-11-12 at 4 55 02 pm" src="https://cloud.githubusercontent.com/assets/2391697/20237452/c6955ee8-a8f8-11e6-87cb-7323815b8638.png">
<img width="1031" alt="screen shot 2016-11-12 at 4 54 56 pm" src="https://cloud.githubusercontent.com/assets/2391697/20237453/c6f0537a-a8f8-11e6-908a-04146f8eebbb.png">

**Comment by jeremystretch** [comment]
> What am I missing?

You need to set the assigned IP as the primary address for the device. (This happens by default when you assign the first IP to a device.)

> Also, why cant I simply add IP to the IP address block? Why does it ask for /xx to use?

The subnet mask is part of the IP address.

**Comment by soamz** [comment]
Sorry did not get you. 
Whats the workflow ?
