### ISSUE TITLE
Reservation / booking system

### ISSUE THREAD

**Issue by nielipin** [digitalocean/netbox#698]
Hi, 
thanks a lot for the great netbox !
One of the features I would like to see and I hope not only me ;) is some kind of booking calendar.
At the moment I am manually assigning devices to tenants and this method works fine, but I have to use some external calendar to plan in advance all activities.
I think I've seen a similar request some time ago but now I am not able to find it and check the status. 
So I will kingly ask again, is there any plan to implement such feature in nearest future ?
thanks & regards, 
Maciek

**Comment by jeremystretch** [comment]
I'm afraid this isn't actionable as a feature request. Per the contributing guidelines:

> Good feature requests are very narrowly defined. Be sure to enumerate specific functionality and data schema. The more effort you put into writing a feature request, the better its chances are of being implemented. Overly broad feature requests will be closed.
