### ISSUE TITLE
Enable subnetting child prefixes when adding child prefixes

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#70]
Let's say I add a /18 prefix and assign it's status as container.

Now let's say I want to add the 64 /24 child prefixes under it.

Could there be an option when adding a child prefix to:

```
(radio option) enter manually

(radio option) subnet container prefix into (drop down)[30,29,28,27,26,25,24]'s
```

Where "enter manually" is the current system in place.

This would allow a much quicker workflow for subnetting and breaking up IP space

**Comment by kasimon** [comment]
See also #66 where I suggested something similiar.

**Comment by bradical987** [comment]
I agree this would be super helpful. One thing I would also suggest, with this, is to add a button next to `Add an IP Address` that is to `Add a Prefix`.

**Comment by jeremystretch** [comment]
Closing this out due to lack of activity.
