### ISSUE TITLE
Custom field UnicodeEncodeError

### ISSUE THREAD

**Issue by pinets** [digitalocean/netbox#702]
Hello.

I have an issue, when trying to write in custom Text type field letters on Russian language. We need to add Physical Address to our designated IP. 

Error looks like that:
`<type 'exceptions.UnicodeEncodeError'>
'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)`

**Comment by jeremystretch** [comment]
Can you please provide the steps needed to reproduce this error?

**Comment by pinets** [comment]
Yes, of course.

1. Go to http://localhost/admin/extras/customfield/
2. Add Custom Field
![screen1](https://cloud.githubusercontent.com/assets/23629859/20553286/682a5ce0-b164-11e6-9a01-95ecb1d08af4.PNG)
3. Add new IP address with custom field, filled in Russian language
![screen2-1](https://cloud.githubusercontent.com/assets/23629859/20553288/682b10ae-b164-11e6-861c-c7b73c5f0809.PNG)
![screen2-2](https://cloud.githubusercontent.com/assets/23629859/20553287/682acc98-b164-11e6-9f26-0a24e730ad06.PNG)
4. Click on Create button and see an error message (Screen3)
![screen3](https://cloud.githubusercontent.com/assets/23629859/20553290/6e61d732-b164-11e6-82b6-1639a781c20a.PNG)

I hope, this will be helpfull.
Thank you for your really good job.
