### ISSUE TITLE
Allow filtering VLANs by group when editing prefixes

### ISSUE THREAD

**Issue by NetTinkerer** [digitalocean/netbox#704]
I might use vlan groups the wrong way but I use them to identify a L2 domain within a site. This allows me to handle overlapping vlans within a site. When I assign a prefix to a particular vlan I see all vlans created for that site. I would like to be able to narrow down the selection by first selecting the vlan group and then select the vlan available in that group.

**Comment by lampwins** [comment]
What I propose is grouping VLANs in the dropdown by their VLAN Group membership, using the simple html optgroup (or similar, but I believe django has native support for this so long as the data is formatted as such). VLAN's in the Global namespace will be grouped as 'Global' At the top of the list.
