### ISSUE TITLE
Intersection between VLANs on Site

### ISSUE THREAD

**Issue by pinets** [digitalocean/netbox#705]
In main office we have L3 Access Design, where our switches have local vlans and on floors they are mirrored each other. For example, on 1 fl. we have 10 for data (marketing) and 110 for voice (marketing), 11 for data (sales) and 111 for voice (sales). On each floor we have exact same scheme. L3 links looks at the Collapsed Core. What we need to do to enable intersection between vlans on one site?

Thank you in advance.

**Comment by NetTinkerer** [comment]
Each L2 domain is a vlan group. This way you can separate the multiple L2 domains within a site from each other.

**Comment by jeremystretch** [comment]
As @NetTinkerer said, VLAN groups can be used to differentiate VLANs with redundant numbers within a site. So in your case @pinets you'd probably want to create a VLAN group for each floor. This is optional, though: You can create multiple VLANs with the same ID and use unique to distinguish them if you'd prefer. Hope that helps.
