### ISSUE TITLE
DCIM: Battery Backup

### ISSUE THREAD

**Issue by aveloz** [digitalocean/netbox#710]
I have defined a device type named UPS3000...then I added a device named UPS-Rack1 and assigned that device type...within I defined 8 Power Outlets and 1 PowerPort...The issue here is there no way to define Power Circuits in order to assign it to a Device...in this case I can only assign the Power Ports to the Powers Outlets...

**Comment by jeremystretch** [comment]
Duplicate of #54.

This is the fourth issue of yours that I've had to close as a duplicate. Please utilize the search function before opening new issues.

**Comment by aveloz** [comment]
Sorry I think...
