### ISSUE TITLE
Allow object to have multiple tenants

### ISSUE THREAD

**Issue by eacheach** [digitalocean/netbox#711]
We'd like to have objects like Sites and Prefixes support multiple Tenants.  So Site A has two Tenants, Tenant Y and Tenant Z that occupy that location.  Prefix B is used by Tenants T, U and V.  Etc.

**Comment by aveloz** [comment]
Im asking for that exactly here:

https://groups.google.com/forum/#!topic/netbox-discuss/985YOncQEo0

Theres an option to create Tenants Groups but thats all...You cant assign a tenant group to a site, device etc....

**Comment by eacheach** [comment]
Our use case is a little different I think.  We are an Enterprise and are documenting our WAN.  A Site is a building with a WAN circuit and there are multiple Tenants in that building separated into their own VRF's.  We'd like to be able to filter Sites for a given Tenant and have all the Sites where that Tenant resides show up.  We also have some (though few) cases where a Prefix is shared between Tenants.  We have shared Circuits as well.

**Comment by aveloz** [comment]
Thats my case too.

**Comment by jeremystretch** [comment]
The concept of tenancy was added to NetBox to allow for tracking resources (devices or sites, for example) which are owned by or associated with only one specific specific tenant. If a resource is shared by multiple tenants, it shouldn't be considered as belonging to any of them, but rather to the primary organization which uses NetBox (e.g. the managed services provider).

Mapping multiple tenants to a single resource conflates the concept of ownership with that of dependency, which is a much more difficult trait to define and track. It would also greatly impede efforts to implement tenant-based security roles for NetBox users (see #554).

I'll keep this request open for some time to see if other have feedback to offer, but at this time I'm not expecting to implement it.

**Comment by ack-martijng** [comment]
I would like to confirm the need for dependencies, or the here described multi tennant usage.
But i believe that the note of @jeremystretch is better, however dependencies are just another parameter that should be able to be tracked within Netbox.

We are also offering services to multiple tennants in one building (site) And provide a circuit that is assigned to us as provider However we would like to make clear which tennants/customers are depending on the equipment.

**Comment by jeremystretch** [comment]
What happens if you have a site with a hundred tenants? For example, maybe you're an MSP with a hundred customers represented in one of your colocation centers. Most people are going to decide that it's not worth the trouble to assign so many explicit relationships. But then you have a logical conflict where _some_ sites (those with only a handful of tenants) have relationships assigned but others don't, even though they're all multitenant sites. For this reason I believe it's more practical to limit tenancy assignments to a single tenant.

**Comment by MrDragon** [comment]
Just adding my $.02 :)
We have data centers at multiple locations and lease space to our customers. I'd like to track where our customers are - some have space in more than one data center.
I don't want to assign a whole site (datacenter) to a tenant (it's our site, after all), but only add the tenant to a site (so-to-speak) - basically a field within the tenant where I can select 0-to-several of the sites to indicate that the tenant is "there".
I could conceivable make tenant-groups, call them "Site-A-customer", "Site-B-Customer", etc, but then I'd need to be able to put a tenant into multiple groups (which I currently can't, either).
Ideally there'd be an additional box in the "Stats" box (groups/sites/whatever) where I can quickly click and see where they rent space.
I see, though, that things aren't as easy as I imagined them. Still, I'm giving a "me too" to this feature-request / wish-list

I hear there are custom fields I can define somewhere (really haven't messed with that) - could those offer a work-around?

**Comment by jsenecal** [comment]
Maybe having a way to query / display tenants referenced by objects in site
or in rack could help?

**Comment by jeremystretch** [comment]
Closing this out as I'm going to keep the "single tenant" constraint. I'm open to providing ways to query for tenant presence, but that would need its own feature request.

**Comment by LukeRussell** [comment]
If I have a site with 100 tenants, I will provision 100 tenants on the site.
