### ISSUE TITLE
Assign Device Primary IP from the only interface IP

### ISSUE THREAD

**Issue by askbow** [digitalocean/netbox#718]
Given #685, when we add a single (first) IP to a a device with a single interface, an option to make this IP the Primary for the device seems logical. 

That would improve usability (not having to go to the Device Edit dialog to set it).

As an extension, that option might be On by default if the interface is set as Management.

I've noticed a comment by @jeremystretch in #688

> You need to set the assigned IP as the primary address for the device. (This happens by default when you assign the first IP to a device.)

 and felt happy and rushed to try it, but it didn't work. We're running release 1.7.1, just upgraded today directly from 1.6.0. Might be a bug?

**Comment by jeremystretch** [comment]
This was working in a previous version. Looks like the form field got omitted from the template.
