### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MethodFilter'

### ISSUE THREAD

**Issue by coolool** [digitalocean/netbox#721]
So I am a rookie when it comes to anything Linux based. I am trying to run  ./manage.py migrate but I keep getting ImportErrors.  I have been able to work through all of them, but I finally got stuck on this one: 

```
<Hiding the rest...> 
File "/opt/netbox/netbox/circuits/filters.py", line 14, in ProviderFilter
    q = django_filters.MethodFilter(
AttributeError: 'module' object has no attribute 'MethodFilter'
```

Any help would be amazing!
Thanks

**Comment by jeremystretch** [comment]
It looks like something went horribly wrong during the installation. I'd suggest redoing the [entire NetBox portion](http://netbox.readthedocs.io/en/latest/installation/netbox/) of the installation. (PostgreSQL and your httpd should be unaffected.)

**Comment by coolool** [comment]
Yeah, I tried following the installing process again and everything went through. Thanks!
