### ISSUE TITLE
Swagger doesn't appear to work with BASE_DIR

### ISSUE THREAD

**Issue by dorkmatt** [digitalocean/netbox#723]
When defining a `BASE_PATH = 'netbox/'` the API doesn't appear to work.

![image](https://cloud.githubusercontent.com/assets/139549/20903284/9834bd38-baef-11e6-8e77-83931a8a0c68.png)

I did adding a [CORS](http://enable-cors.org/server.html) response header. Nothing is returned, just "fetching resource list". I don't see any obvious error logging support, thoughts on how to debug this further?

**Comment by jeremystretch** [comment]
Note that swagger is merely the frontend documentation generator for the API. The API itself should work fine.

**Comment by dorkmatt** [comment]
Does not resolve the issue, patch applied - same problem.
