### ISSUE TITLE
Updating from V.1.7.1 to V.1.7.2 removes device colours on rack

### ISSUE THREAD

**Issue by Tigger2014** [digitalocean/netbox#727]
updated from git and ran upgrade.sh.

This appears to have broken device colours on the rack views.
![image](https://cloud.githubusercontent.com/assets/2319079/20941993/23f5812a-bbf1-11e6-8f5e-59ac0878b39d.png)

**Comment by jeremystretch** [comment]
Force your browser to refresh (ctrl+F5 on most platforms).

**Comment by Tigger2014** [comment]
I have already tried that, ive also tried another browser.

**Comment by jeremystretch** [comment]
Looks like a template file was missed in the release. I'm trying to get a patched release out, but GitHub seems to be having issues at the moment.
