### ISSUE TITLE
Add option to display a banner on all pages

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#73]
Need to have a banner for certain requirements and was wondering if one can be configured or a feature can be added for it.

**Comment by jeremystretch** [comment]
What would you want it to look like? Similar to the maintenance banner? (Set `MAINTENANCE_MODE = True` in configuration.py and restart NetBox to show the banner.) Or something glued to the top or bottom edge of the window?

**Comment by chagara** [comment]
We need something glued at the top and bottom in every page. We need to have an expecific message that will always show up.

**Comment by jeremystretch** [comment]
Fixed in #222
