### ISSUE TITLE
Multiple Circuit Terminations Per Port

### ISSUE THREAD

**Issue by brianblac** [digitalocean/netbox#731]
I am wondering if it would be possible to allow the Termination of Circuits to to allow multiple Circuits on a single port of a device? I notice that once you add a circuit and Terminate it to a devices port it grays that port out on any additional circuits.

Example, if I am handing multiple Ethernet circuits to an upstream provider on a single interface, it would be nice to specify them all on that switches single interface and then be able to view all circuits that port is responsible for.

Thanks in advance.

**Comment by jeremystretch** [comment]
A circuit in NetBox represents a discrete physical connection. It's not possible to connect more than one circuit to a single interface. It sounds like you might be referring to virtual circuits encapsulated using 802.1Q; in NetBox, only the physical link carrying this traffic would qualify as a circuit. NetBox doesn't currently have the ability to track virtual circuits.
