### ISSUE TITLE
issue with custom field boolean (true/false)

### ISSUE THREAD

**Issue by chagara** [digitalocean/netbox#739]
Hello,

I have noticed that when I create a boolean custom field, every time I update  a device I have to make a selection for that custom boolean since it does not keep the update changed previously. For example:

Latest Updates? True
when I go to update the same device for something else, that custom field "Latest Updates?" will be ------- and not True like I selected before.

**Comment by jeremystretch** [comment]
I'm not able to replicate this behavior. What version are you running?

**Comment by chagara** [comment]
v1.6.3

**Comment by jeremystretch** [comment]
The latest release is v1.7.3. It's likely the bug has already been fixed.

**Comment by chagara** [comment]
ok, i'll upgrade tomorrow and give an update.

**Comment by chagara** [comment]
ok, the latest version I was able to upgrade is v1.7.2-r1 and that seems to have fixed the issue. thank you!

**Comment by jeremystretch** [comment]
You don't want to run 1.7.2; it has some noticeable bugs. 1.7.3 is [here](https://github.com/digitalocean/netbox/releases/tag/v1.7.3).

**Comment by chagara** [comment]
alright I will upgrade when I can.
