### ISSUE TITLE
Allow exporting all data from UI

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#74]
I'm running netbox in a dev VPS right now and have entered a sizable amount of data.

I'm going to want to move this to a production server and would really prefer not to have multiple exports (not sure if everything exports?)

**Comment by jeremystretch** [comment]
If you want to replicate the entire installation, you can just dump the SQL database:

```
sudo -u postgres pg_dump netbox > netbox.sql
```

And then load it on the new server:

```
sudo -u postgres psql -c 'create database netbox'
sudo -u postgres psql netbox < netbox.sql
```

**Comment by bellwood** [comment]
Definitely an option but my issue/use case was perhaps those either not comfortable on the command line or may not even have access.

For my specific purposes this obviously works just fine

**Comment by ryanmerolle** [comment]
I would agree that not all users of tool may be given access to the underlying DB.  

I am exporting some of my data into the packetlife demo to make it more robust for some testing and new users to play around with.  If a user wanted to export said data from the site, to their local install, they would not be able to for all sections.  I know this would could also be tackled by #176, but I am all about UI standardization.

**Comment by jeremystretch** [comment]
I don't think it makes sense to implement what is essentially a wrapper around a PostgreSQL dump. It's just more code to maintain that doesn't achieve anything a native PostgreSQL dump wouldn't. I understand that some people might not have direct access to the database, but that's an operational concern for the user.
