### ISSUE TITLE
Netbox - Adding information for a circuit running through 1 rack to another

### ISSUE THREAD

**Issue by himanisilva** [digitalocean/netbox#740]
Currently I am adding information on Netbox on Patch ports. There are circuits which runs from one rack to another rack (internally). when trying to add details it is duplicate circuits as I cannot add information  on either the A -end or Z-end.  Is there anywhere I could add this sort of information in the circuit?

**Comment by jeremystretch** [comment]
Work is underway on #49 to extend the Circuit model to connect two discrete interfaces. However, data circuits typically run between buildings, not adjacent racks. Are you sure you want to represent this connection using a circuit (with a provider and circuit ID)? If you just want to establish a connection, you can create a regular interface connection.

**Comment by himanisilva** [comment]
Thank you for your response. The cross connects goes from one rack to another and in a regular interface there are no options to add the cross connect information or the patch panel information. That is the reason why I was trying to use a circuit instead. Also I have Inter rack cross connects which are not used but its for backups. Is there any best practices  you suggest for this sort of issue? Your feedback is very helpful as I am new to Netbox.
Thank you.

**Comment by jeremystretch** [comment]
You probably want to stick with normal interface connections. We don't yet have the ability to track cross-connect information in NetBox, but it's on the roadmap.

**Comment by jeremystretch** [comment]
Going to close this out, but if you need any more help please post on the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
