### ISSUE TITLE
Bulk editing for all users in administrators group

### ISSUE THREAD

**Issue by darthmdh** [digitalocean/netbox#742]
When I login as the original admin user I am able to bulk edit items by checking the checkbox next to the targets and then selecting an action from a menu near the top of the page.

If I login as another user in the administrators group, this bulk edit capability doesn't exist - the checkboxes are there but the menu buttons do not display.

There also doesn't seem to be a capability for bulk edit in the admin interface (i.e. it seems hardcoded to original admin user).

Ideally:
* Add RBAC capability to bulk edit
* Let users / group members with this capability perform bulk edit actions
* Assign this capability to original admin user and administrators group by default

**Comment by jeremystretch** [comment]
I'm not clear on what you're trying to do. Are you using the normal frontend or the admin interface?

**Comment by darthmdh** [comment]
@jeremystretch Oh, sorry, via the normal frontend.  I've done something perhaps left-field and ignored the DCIM component, just bulk-added data into the IPAM section only.  Some of the input data is historically inaccurate so I want to e.g. select multiple IP addresses and then tag them with the correct Tenant, VLAN, etc. rather than having to visit them individually.  This works fine as the original admin user but not as any other user.

For example,
IP Space -> Prefixes -> click on a prefix
As the original admin user, there's buttons below the child prefixes table "edit selected" and "delete selected"
**These buttons do not exist for another user in an administrators group with full rights.**

The same happens in the IP Address view, in fact I can't recall the buttons appearing anywhere for anyone other than the original admin user.

**Comment by jeremystretch** [comment]
There is no "administrators" group. A user must be explicitly assigned superuser status in order to inherit all permissions. Otherwise, permissions must be assigned per user or per group in the admin UI.

**Comment by jsenecal** [comment]
I think @darthmdh meant users with the superuser boolean set to false but with enough permissions on the model.

**Comment by darthmdh** [comment]
I did.  And I think this was re-raised as #845 and fixed.
