### ISSUE TITLE
LOGIN_REQUIRED

### ISSUE THREAD

**Issue by pinets** [digitalocean/netbox#745]
Hello!

I found a parameter, that I need to change from False to True, but cannot find the correct file in tree and steps to activate it. What exactly steps do I need to do to get login and password prompt before I can see any info in web-interface? I found only file "configuration.docker.py". I was changed one to True, restart docker-compose and nothing has changed.

**Comment by jeremystretch** [comment]
Please see [the optional settings documentation](http://netbox.readthedocs.io/en/stable/configuration/optional-settings/). If you need any further assistance, please post to [the mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
