### ISSUE TITLE
Allow comments on device type

### ISSUE THREAD

**Issue by konetzed** [digitalocean/netbox#746]
It would be nice to have a section to allow comments on device type.  This way a user could add things like links to the hardware details along with firmwares.

**Comment by konetzed** [comment]
Looks like this commit solves my request. https://github.com/digitalocean/netbox/commit/b451ece05736156bb204b2ab26f487d50aa3b5cd

If it does please ignore. Sorry I didn't read current commits to the develop branch.

**Comment by jeremystretch** [comment]
Yep, by pure coincidence I implemented this on Friday. It will included in v1.8.0.
