### ISSUE TITLE
Problem with moving device in rack

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#75]
Create a device for example something that has 5RU in height and you add it to a rack.

Say for example you assigned the device RU 10-15 but after adding the device you realise it should have been RU11-16. 

If you then want to move this device up 1RU in the rack you have to move the device completely out of the 5RU allocated for the device. Save changes then go back and edit the device and move it to the correct RU location. 

This does not work when the rack is near full - you would have to remove the device and then re-allocate the device to the rack.

**Comment by bellwood** [comment]
I dont have this issue... I just moved a 4U juniper up 2U and had no issues.

Are you running the latest commit to master?
