### ISSUE TITLE
Documentation addition

### ISSUE THREAD

**Issue by contemno** [digitalocean/netbox#753]
I'd like to add a small section to the installation instructions about troubleshooting 5xx errors. Thought it might save time for anyone installing it for the first time. What would be the best way to do this?

**Comment by jeremystretch** [comment]
There are a lot of things that can go wrong with a NetBox installation, many of which don't pertain to NetBox itself. Rather than attempt to maintain a catalog of all of these, I'm happy to point people to the discussion list archives to search for known issues.

**Comment by contemno** [comment]
I can definitely appreciate wanting to limit scope creep. 

Thanks for taking this project public; it's well on it's way to being an invaluable tool for the data center. Let me know if there's anything I can do to help.
