### ISSUE TITLE
Move search to top

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#754]
To get more space for the filters on the right side of the list pages, it would be good to move the search box to the top of the device/rack/... list. So the filters could be moved up and the users don't need to scroll down to use/see more filters. It's also a more continous design because the searches on the start page are aligned the same way.

I made an example for the device list page:
![netbox_moved_search](https://cloud.githubusercontent.com/assets/6536990/21454481/4f61d0a4-c919-11e6-9fc5-229390b9fbdb.png)

Merry christmas and keep up the great work! :smile:

**Comment by jeremystretch** [comment]
The search box takes up very little room as it is. Moving it tot he left side pushes the main content further down the page. I'd like to keep it where it is.
