### ISSUE TITLE
Add fields to site for contact details

### ISSUE THREAD

**Issue by SineDave** [digitalocean/netbox#756]
Jeremy - thank you for developing this awesome tool, my team and I love it.

One thing that would be absolutely amazing for us to have added to Netbox would be the ability to store a site contact name, phone and email under each site. That is really useful when we don't have actual technical folks at all locations.

Here's a terrible mockup of how i'd love Sites to look:

![netbox-suggestion](https://cloud.githubusercontent.com/assets/24735954/21457952/88d109ca-c8f8-11e6-8f91-871142442b95.jpg)

**Comment by jeremystretch** [comment]
This probably ties in with #173 but I'll have to give some more thought to how we can best model the relationship between a site and its owner.

**Comment by mikebrandl** [comment]
This really would be nice, just to add a +1

**Comment by Armadill0** [comment]
A most welcome feature for me, too! :smiley:
