### ISSUE TITLE
Revision

### ISSUE THREAD

**Issue by john-arvid** [digitalocean/netbox#758]
May be a duplicate of #683 

Would like brainstorming around revision and how this could be solved today or with a new enhancement.

I have several users that are human, and they as I will make mistakes. I need a way to revert changes done to "anything" so that when another user or me finds an faulty registration, we could change back and do the proper update.

Is this something I could implement in the existing version? (in postgres, django, a routine or php?)

**Comment by jsenecal** [comment]
This feature could be implemented using
https://github.com/etianen/django-reversion

I used it in the past and it is flexible enough to achieve very powerful
results.

**Comment by jeremystretch** [comment]
I looked into the possibility of using django-reversion early on in the development of NetBox. Unfortunately, it's not well-suited for a data model so complex as what we have.

For example, suppose a user deletes a device, and then some time later wants to restore it. We'd need to validate not on the device object, but all of its related connections, addresses, rack space, etc. _and_ have a plan to elegantly handle every potential conflict. It'd be an amazing feature, for sure, but it's not something that we can dedicate effort to in the near future.
