### ISSUE TITLE
Show rack preview when adding new devices

### ISSUE THREAD

**Issue by rackcentral** [digitalocean/netbox#76]
When on the add device page.

http://XXX/dcim/devices/add/

It would be beneficial to be able to preview the rack itself showing available placement after selecting the rack from the drop down list.

It would also be great once selected the RU location to show the device pending placement location in the rack being shown and then only committing to that location once it has been saved.

**Comment by jeremystretch** [comment]
This is pretty easily accomplished by navigating first to the rack in which you want to install a device and then selecting the desired position to add it. Including a live preview of a rack on the "add a device" page would require quite a bit of new code and not provide any real new value.
