### ISSUE TITLE
Redirect back to the device when you delete IP addresses from it.

### ISSUE THREAD

**Issue by galaxydata** [digitalocean/netbox#760]
Netbox 1.7.3

1. Go to contact the selected device.
Delete the IP address of the device.

![_088](https://cloud.githubusercontent.com/assets/4956197/21579882/7becaddc-cfeb-11e6-8392-81e1f02c2319.png)

2. Then we get to the window to confirm the deletion.

![_089](https://cloud.githubusercontent.com/assets/4956197/21579885/a2982614-cfeb-11e6-92f7-52404e8a93d3.png)

3. And then we get to the list of all IP addresses.

![_090](https://cloud.githubusercontent.com/assets/4956197/21579889/ba7c172c-cfeb-11e6-8227-9a32c72181bf.png)

**Questions:**
Now how do I get back to the device from which I removed the IP address?
Back to go to the list and look for them among thousands of devices? And if I have forgotten the name of the device?

**Improvement:**
You can make sure that when you delete IP address is returned to the same device that produces its modification. Removing IP address, user and other device settings.

**Comment by jeremystretch** [comment]
This was one of those things that I've wanted to fix for a long time, but just never made a conscious effort to focus on. I'm sure there are other instances where this sort of behavior can be improved as well. Thanks for opening the issue.

**Comment by galaxydata** [comment]
Many thanks!
