### ISSUE TITLE
Export: add field value delimiter to string fields

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#764]
If you export data and reimport it and there are description fields containing commas, those would lead to wrong data imports.

On fields which can contain user defined strings, it would be great to have a double quote field value delimiter, to avoid such problems. This is also covered by the CSV RFC: https://tools.ietf.org/html/rfc4180 (paragraph 2.5 and 2.6)

**Comment by jeremystretch** [comment]
> it would be great to have a double quote field value delimiter, to avoid such problems.

This has already been implemented (#422). Have you found a specific area where it isn't working?

**Comment by Armadill0** [comment]
I explicitly found it for "Description" of the Prefixes export. I'll have a look in my other exports tomorrow if there are more occurences.

**Comment by jeremystretch** [comment]
Oh my mistake, I was only looking at import. Yeah, we can add this to the `to_csv()` method on models with export capability.

**Comment by Armadill0** [comment]
Great, thanks! :smile:
