### ISSUE TITLE
Error when searching circuits in 1.8.0

### ISSUE THREAD

**Issue by patrickfish** [digitalocean/netbox#767]
Searching for a circuit with: $URL/circuits/circuits/?q=test results in an error:

```
<class 'django.core.exceptions.FieldError'>

Cannot resolve keyword 'xconnect_id' into field. Choices are: cid, comments, commit_rate, created, custom_field_values, id, install_date, last_updated, provider, provider_id, tenant, tenant_id, terminations, type, type_id
```

**Comment by patrickfish** [comment]
Verified fix, cheers!

**Comment by jeremystretch** [comment]
Thanks for the report. Seems like there's always something lurking in an x.y.0 release lately. I might start running them internally for a week or so before the public release.
