### ISSUE TITLE
VLAN “Service Identifier” field (VXLAN or ISID)

### ISSUE THREAD

**Issue by DouglasHeriot** [digitalocean/netbox#777]
We have an Avaya fabric core network, where ISIDs are mapped to VLANs on the access switches. We have many VLANs created in Netbox, and need a way to map them back to unique ISIDs.

When we have the same VID used across multiple sites, they each have unique ISIDs.
This is similar to VXLAN trunks, or Q-in-Q ​​#116 service VLANs.

I propose a "Service Identifier" field that can be used to track this unique number. (VXLAN and ISIDs are both 24-bit)

I plan to have a go at implementing this myself.

**Comment by jeremystretch** [comment]
Tagging this as potentially related to #116.

**Comment by candlerb** [comment]
Would creating a "Custom Field" on the ipam > VLAN object be usable for this? Or if not, maybe the Custom Field functionality can be enhanced to make it usable?

**Comment by DouglasHeriot** [comment]
I think you’re right – a custom field probably is the right way to do this. Most people don’t need to track ISIDs or VXLANs, so it doesn’t make sense to have it cluttering up the interface.

There are a few enhancements to custom fields that would be good to make it more usable however:
* #568 bulk import
* #492 organising columns, or option to display custom fields as columns
* #609 validator on custom fields (ie. want to restrict ISID and VXLAN to 24-bit positive integer)

But for now, I think custom fields will work well enough for us to get started tracking this information better.
I’ll start investigating how difficult it would be to implement some of these things.
