### ISSUE TITLE
circuit creation failed

### ISSUE THREAD

**Issue by john-arvid** [digitalocean/netbox#779]
Hi,

Just updated from v1.7.3 to v1.8.1, then when I tried to create a circuit it failed with this message:

```
<class 'django.utils.datastructures.MultiValueDictKeyError'>

"'site'"
```
There is input in all the mandatory fields, and no input in the others. Same with provider and circuit type.

\John-A

**Comment by jeremystretch** [comment]
@john-arvid Could you provide full stack trace please?

**Comment by jeremystretch** [comment]
Also, did you run `upgrade.sh` after downloading the new code? It sounds like maybe the database migrations weren't applied.

**Comment by john-arvid** [comment]
Yes I did run the `upgrade.sh` but I did not run the `supervisorctl restart netbox`..
Tested and works.
