### ISSUE TITLE
Enable creation of topology maps for PDUs and Console connections

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#78]
It could be interesting (maybe even useful) to visualise PDU and Console connections, even if they are only just star topologies. It would at least let you see which boxes are not served.

Simple solution: add checkboxes in the Map definition for which types of connection to show - and use different edge colours, in case displaying multiple types in the same diagram.

Aside: filtering by Device Role, rather than regexps of device name, might be simpler.

**Comment by jeremystretch** [comment]
> It would at least let you see which boxes are not served.

This is better handled by validation reports today.

> Simple solution: add checkboxes in the Map definition for which types of connection to show - and use different edge colours, in case displaying multiple types in the same diagram.

Trying to incorporate all types of connections in a single map isn't going to work well. Each map can only have one type.

> Aside: filtering by Device Role, rather than regexps of device name, might be simpler.

It would, but it would also be much less flexible. Sometimes we only want to include a subset of a type of devices (e.g. the first rack or two in a site).
