### ISSUE TITLE
Add description field to Circuit model

### ISSUE THREAD

**Issue by brianblac** [digitalocean/netbox#783]
It would be nice to have a comment or description column when listing circuits, as I'm sure you know, a lot of circuit ID's - especially when using an upstream providers - don't mean much at a glance.

I have been using a custom field for descriptions but am unaware of a way to show it when listing.

Thanks!

**Comment by brianblac** [comment]
I realize this could be taken care of by more descriptive names in the A or Z fields.

**Comment by jeremystretch** [comment]
The "A side" and "Z side" are de facto standard names in the industry, so I'd like to keep them as-is. Adding a one-line description to the circuit model seems like it would be sufficient.

**Comment by brianblac** [comment]
Absolutely, I wasn't asking to change A and Z, I was stating that maybe you didnt have this feature because you were expecting people to know what the circuit was based on the A and Z locations. A single line description that would show up when listing the circuits would fit what I was asking for perfectly.
