### ISSUE TITLE
(Prefix) subnet lookup

### ISSUE THREAD

**Issue by quentinsch** [digitalocean/netbox#784]
It would be nice if you could lookup the subnet when entering an IP address to a device.
If you've a lot of prefixes defined it can be hard to remember the defined prefix when you enter the IP address.
Maybe the input field could show a short list of prefixes in a kind of pop-up next to the input field to help you out which prefix to select.

I am aware this could be complex to figure this out how this should work, especially with IPv6, but it would be a great enhancement.
Maybe some one else can add some suggestions?

**Comment by jeremystretch** [comment]
I'm not sure I understand how this would help. How would showing a list of all your prefixes help you determine what the device's IP should be? Why wouldn't you just use the existing prefix to find the desired prefix first?

**Comment by quentinsch** [comment]
I understand the way you're thinking with adding it through the prefix the other way around. I just thought it would be convenient if you could look it up the other way around when adding a device.
It might also be too complex to build in. It was just my two cents for improvement.
