### ISSUE TITLE
Prefix Import: Error message if VLAN_id is not found

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#785]
Hi I just imported a bunch of prefixes into netbox 1.8.1. It was a bit hard to track down some issues with missing VLANs (some didn't exist at all, some only at a different site) which gave me this error message:
![netbox-prefix-import-error](https://cloud.githubusercontent.com/assets/6536990/21767618/7fe3ad7e-d675-11e6-9e90-cc0eaea59bac.png)

Would be great if we could have a specific error handling (like the other errors, e.g. description too long, too) which shows what it was searching for and in which line this happened, because it's no fun to debug 500 lines by hand. :smile:

**Comment by jeremystretch** [comment]
To confirm, importing even invalid data should never yield a server error. (Invalid data should trigger a validation error and return the user to the populated form.)
