### ISSUE TITLE
Custom fields when viewing devices/racks

### ISSUE THREAD

**Issue by RyanMonkey** [digitalocean/netbox#79]
We have asset tags for all of our equipment.

The ability to add custom fields to the device/rack screen would be excellent.
It would be more beneficial (for reports etc) to have specific fields.

The option to make them required would be good too.

Thanks.

**Comment by bellwood** [comment]
This was touched upon here:

https://www.reddit.com/r/networking/comments/4k89ty/i_built_an_ipamdcim_thing/d3iw6sr

There isn't a specific enhancement for custom fields yet but it certainly has merits

**Comment by RyanMonkey** [comment]
Ahh, excellent!

I'll close this for now.
