### ISSUE TITLE
Export circuit template

### ISSUE THREAD

**Issue by hornetgr** [digitalocean/netbox#793]
Is it possible to export a template with all the details of the circuits, eg the termination A and Z of a circuit.
What i mean is that the new feature to make a circuit with termination A and Z it is very nice, but it would be better if we can print all the details of all circuits in a CSV.

**Comment by jeremystretch** [comment]
The export templates are designed to be compatible with the bulk import forms. We can extend the export template to include the terminations, but this means extending the import function as well (which isn't a bad thing).

In the interim, it is possible to define a custom [export template](http://netbox.readthedocs.io/en/stable/data-model/extras/#export-templates) to do this.

**Comment by jeremystretch** [comment]
Going to fold this into #815, which has been opened for circuits import.
