### ISSUE TITLE
Prefixes appearing out of order

### ISSUE THREAD

**Issue by CFRR** [digitalocean/netbox#798]
Hi,

We have for example a 10.172.0.0/16 and child prefixes 10.172.0.0/18, 10.172.64.0/18 and 10.172.128.0/17 and in Prefixes main page appears like this:

![prefix_1](https://cloud.githubusercontent.com/assets/17024363/21982852/32a6cf02-dbe6-11e6-8957-475f2e772257.PNG)

When I add a new prefix for example 10.220.0.0/16 appears like this:

![prefix_2](https://cloud.githubusercontent.com/assets/17024363/21982881/48e7f660-dbe6-11e6-9b93-210f7dbda90c.PNG)

This is a normal situation?

**Comment by jeremystretch** [comment]
What version of NetBox are you using? I'm not able to replicate this on v1.8.1.

**Comment by CFRR** [comment]
Hi  jeremystretch,
I'm using the last version v1.8.1.

**Comment by jeremystretch** [comment]
Are you filtering or sorting the prefixes somehow? Can you explain the steps needed to recreate this please?

**Comment by CFRR** [comment]
Jeremy,

> Are you filtering or sorting the prefixes somehow?
No.

> Can you explain the steps needed to recreate this please?
1. Add a prefix: 10.172.0.0/16 VRF Global
2. Add a child prefixes 10.172.0.0/18, 10.172.64.0/18 and 10.172.128.0/17 VRF A
1. Add a prefix: 10.220.0.0/16 VRF Global

But the "issue" is that, the VRF are different, when I change to the same VRF the prefix are in order.
We have the concept of define a major prefix and divide in minor prefix by several VRF.

Is it possible to achieve this?
Thx.

**Comment by jeremystretch** [comment]
Oh, I see. Yes, this is expected behavior. The global table and the VRF table are treated as entirely separate IP spaces. NetBox lists all the prefixes from the global table first, followed by all the prefixes from VRF A.

Clicking the "Prefix" header of the table will sort all prefixes by their IP, without regard to VRF assignment.
