### ISSUE TITLE
Racks - errors

### ISSUE THREAD

**Issue by CFRR** [digitalocean/netbox#799]
I added several racks but the in main page did not appear listed:

![racks](https://cloud.githubusercontent.com/assets/17024363/21983264/4c99b01c-dbe8-11e6-954e-6553354d10fa.PNG)

When I try view the rack information via "Recent Activity", I get the following error:

![racks_error](https://cloud.githubusercontent.com/assets/17024363/21983292/6ede775c-dbe8-11e6-80b5-9cd437e8558c.PNG)

```
<class 'django.db.utils.ProgrammingError'>
column "dcim_device.created" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...er)) AS "_dcim_device_name1", "dcim_device"."id", "dcim_devi...
```

**Comment by jeremystretch** [comment]
It looks like you're missing database migrations. Please try reinstalling NetBox.

**Comment by jeremystretch** [comment]
I'm going to close this issue but please post to [the mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you need further assistance.
