### ISSUE TITLE
Report on duplicate addresses and prefixes

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#801]
Unless you have ENFORCE_GLOBAL_UNIQUE configured, it is possible to add duplicate IP addresses. Once they have been added, they may no longer be noticed.

Suggest having some sort of report which highlights duplicate IPs.  Could also be done on a per-VRF basis (for VRFs which don't have enforce uniqueness)

**Comment by Armadill0** [comment]
I just wanted to ask the same.

Maybe this could be solved by a "Duplicates" filter on the IP addresses list page where the duplicates are grouped or something like that.

**Comment by candlerb** [comment]
Workaround:

~~~
echo "select vrf_id,address,count(*) from ipam_ipaddress group by vrf_id,address having count(*) > 1;" | su -c 'psql netbox' postgres
~~~

Maybe a solution is to have a "custom reports" table in the Admin section, where you just enter a report name and some SQL; then have a drop-down menu in the main UI to run any of the chosen reports.

**Comment by jeremystretch** [comment]
This functionality will be provided via custom validation reports (#1511) in v2.2.
