### ISSUE TITLE
Site is not linked from Device Search results

### ISSUE THREAD

**Issue by patrickfish** [digitalocean/netbox#805]
Not sure if this is by design, but since you can't search by Site from the home page, I often type in a device name that matches a site name to quickly pull up a site.

From the results page, "Site" is the one of the few fields not hyperlinked, so I click into the device and then click the site.

Small workflow thing I've noticed over a few months of usage.

**Comment by jeremystretch** [comment]
Tangentially related: #159 is open to introduce a global search function.
