### ISSUE TITLE
Add IP Address Roles

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#819]
We're currently investigating how to mark IP addresses for a specific role, for instance as a gateway. Currently this is only possible via the address description if you want to see the gateway "role" e.g. on the list of ip addresses on the Prefix page.
It's also not possible to filter for a Prefix on the IP address list and combine it with a search in the address description which makes it even harder to find a specific gateway.

The best solution for this in my opinion would be an IP address role field, like we already have it e.g. for devices. This would allow us to mark IP addresses for special use cases like gateways, VRRP, Cluster-IPs, Loopback addresses and so on and to easily find them through filters.
Also the possibility to mark them with a specific color which is also possible for device roles would be great to easily find a gateway in the IP address list of a single Prefix.

What do you think?

**Comment by jeremystretch** [comment]
I think it might make sense to include some hard-coded operational roles for IP addresses:

* Default gateway
* NHRP client (VRRP/HSRP/GLBP/etc.)
* Virtual IP (generic clustering)

I'm not sure if a loopback role would be appropriate, since that's more a function of the interface to which an IP address is assigned.

**Comment by candlerb** [comment]
Aside: there is already a Prefix role, and VLAN roles re-use Prefix roles.

So they could be shared with IP Address too, although in practice roles like 'default gateway' wouldn't make any sense at the Prefix/VLAN level.

**Comment by jeremystretch** [comment]
@candlerb Right, the prefix/VLAN roles are user-customizable and functional in nature, whereas IP address roles would pertain to the status of an IP relative to other IPs within its parent prefix.

**Comment by Armadill0** [comment]
To be honest, using prefix/vlan roles also for IP addresses, would be fine for us. This would also make the implementation much less work I assume.

To emphasize the more generic usage within the IPAM functionalities, we could rename them to "IPAM roles" or something similar instead of "Prefix/VLAN roles".

And I would really appreciate the color selection which we already have for device roles.

**Comment by jeremystretch** [comment]
As mentioned in #906, it might make sense to include an "anycast" role for IP addresses. This role could be used to exempt anycast IPs from duplicate address validation.

**Comment by jeremystretch** [comment]
Implemented in f427c00d946a6253ce7b4fe9997d8dfc4c05d664

**Comment by tioan** [comment]
Please add also CARP as an role option

**Comment by porkstoners** [comment]
would be possible to add VARP as a role ?
