### ISSUE TITLE
Support comma in interface bulk creation

### ISSUE THREAD

**Issue by dav3860** [digitalocean/netbox#821]
Currently we can use numeric ranges like `ge-0/0/[0-47]` to bulk create interfaces, which is great. I would be very nice if we could also use commas, like `Vlan[51,54,80,90-95]`. It would allow to create non-continuous ranges of interfaces (very handy for VLANs).

**Comment by adamtbeames** [comment]
Good Idea.  That's something I'd use too.

**Comment by jonathanantoine** [comment]
I like the idea too.
