### ISSUE TITLE
Missing css files for admin/

### ISSUE THREAD

**Issue by sirtux** [digitalocean/netbox#826]
Hi,

I installed the latest master branch of netbox, 
but when accessing $netbox_url/admin, all css information is missing.

The browser tries to load "$netbox_url/static/admin/css/base.css" and "$netbox_url/static/admin/css/dashboard.css", but I can't find these files in the repo - there is a base.css, but it's not in the right path.

Am I missing something?

Thanks,
Tom

**Comment by jeremystretch** [comment]
Please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you'd like assistance with installation.
