### ISSUE TITLE
Form Factor on Interface Template

### ISSUE THREAD

**Issue by fabio-git** [digitalocean/netbox#829]
I need to add different typos of form factor.

Is it possible to enable the possibility to add/rem/edit, please?

**Comment by NetBod** [comment]
or could custom fields be enabled in the interface section, that way people could add a custom field and then create there own list of interface types. Just thinking........

**Comment by jeremystretch** [comment]
Form factors pertain to the physical manifestation of interfaces in the real world, of which there is a finite set. As such, form factors are hard-coded into NetBox. There should never be a reason for a user to add a custom interface form factor.

What are you planning to add? If it's a legitimate form factor that isn't in NetBox, we can add it.

**Comment by fabio-git** [comment]
Uhmm, you are right. Thinking about you've said, how can we set up this need:
There are some devices/modules with "combo" interfaces (1000BASE-T + SFP).
Today is not possible to add eth0 for 1000BASE-T and SFP at same time, thats why I thought, first, the possibility to add a combo.

**Comment by jeremystretch** [comment]
Yeah, I know exactly what you mean. The combo ports are a pain to model. My solution has been to create the interface with the form factor of whichever physical port is being used (you can always change it later if needed).

**Comment by fabio-git** [comment]
This is what I'm doing. But if you find a way to implement this combo it would be very nice, so I could create a device template exactly as it is.
Just to register some devices with combo interfaces: Edgerouter (Ubiquiti), Routerboard (Mikrotik), Catalyst switches (Cisco), Huawei routers, Datacom switches, etc. 
Tks

**Comment by jeremystretch** [comment]
AFAICT there's no great solution to this. Despite the presence of two physical ports on a device, it only sees a single interface internally. IMO it's best to simply ignore the presence of the nonfunctional port entirely.
