### ISSUE TITLE
getting-started.md - Apache howto error

### ISSUE THREAD

**Issue by mysterfr** [digitalocean/netbox#83]
Hello,

Following the installation howto, I noticed an error in the Apache configuration section.

The` ProxPass` and `ProxyPassReverse` lines have an ending semi-column, wich leads to an error when restarting apache.

Additionnaly, it might be worth mentioning that the Apache proxy module should be enabled as well, throug 
`a2enmod proxy`

**Comment by jeremystretch** [comment]
Fixed the Apache config in b37503ed8fec7ee3d88e6cca7924fd10c08e5705

**Comment by bzoellers** [comment]
Running Apache 2.4, and I had to make the following changes to what was suggested in getting-started.md

(add "/" to the end of the guincorn URL)
`ProxyPass / http://127.0.0.1:8001/`
 `ProxyPassReverse / http://127.0.0.1:8001/`

(remove "/" from the alias for static)
`Alias /static /opt/netbox/netbox/static`

**Comment by jeremystretch** [comment]
Could someone please confirm that this change works fully with Apache? This will be the third time I've had to modify it.

**Comment by dberube1** [comment]
Doing a clean install now. I will let you know.

**Comment by bzoellers** [comment]
I'm on a clean install of Ubuntu 14.04.4 LTS and can confirm that this is my Apache 2.4.7 config file:

```
<VirtualHost *:80>
    ProxyPreserveHost On

    ServerName ipam.ddaftech.com

    Alias /static /opt/netbox/netbox/static

    <Directory /opt/netbox/netbox/static>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Require all granted
    </Directory>

    <Location /static>
        ProxyPass !
    </Location>

    ProxyPass / http://127.0.0.1:8001/
    ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>
```

I also had to enable both of the following modules
```
a2enmod proxy
a2enmod proxy_http
```

**Comment by dberube1** [comment]
I can confirm bzoellers apache configuration. Running the same configuration on a clean install of Ubuntu 14.0.4.4 LTS.

**Comment by ssgzeke** [comment]
Here is my apache config...it differs a little bit than bzoellers but is close:

`<VirtualHost *:80>
    ProxyPreserveHost On

    ServerName netbox.lan.esu10.org

    Alias /static /opt/netbox/netbox/static

    <Directory /opt/netbox/netbox/static>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Order allow,deny
        Allow from all
        #Uncomment below if running Apache 2.4
        Require all granted
    </Directory>

    <Location /static>
        ProxyPass !
    </Location>

    ProxyPass / http://127.0.0.1:8001/
    ProxyPassReverse / http://127.0.0.1:8001/
</VirtualHost>`

**Comment by jeremystretch** [comment]
Also received a report that the `Alias` line should read:

```
Alias /static/ /opt/netbox/netbox/static/
```

(with the trailing slash).

**Comment by mysterfr** [comment]
Hi,

I had to remove the trailing slash in the Alias directive, and add trailing slashes to the ProxyPass statements to have it work. 
My config looks exactly like Billizoellers'.
