### ISSUE TITLE
Connection Reference / Description

### ISSUE THREAD

**Issue by dezeeb** [digitalocean/netbox#831]
Hi, just wondering how much work it would take to add a description to the connections page... we use unique reference numbers for patch cables and it would be great to see a description for the patch along with the two interfaces/devices.

**Comment by jeremystretch** [comment]
Each interface can be assigned a freeform description, but not the connection itself. Attributes relevant to the physical cable plant will be implemented as part of #20. (Marking this as a duplicate for reference.)
