### ISSUE TITLE
Delete confirmation to include more details

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#838]
Suppose you have duplicate IP addresses:

* 10.0.0.64/32 (description "foo")
* 10.0.0.64/32 (description "bar")

When you delete one of these, you get the following confirmation:

> Are you sure you want to delete these IP addresses?
>
> * 10.0.0.64/32

It would be helpful if it displayed more information about the address here (at least the description) so there's more certainty that you're deleting the right one.

**Comment by jeremystretch** [comment]
I'd like to replace the bulleted list with a table including all relevant details. Not just for IP addresses, but for all objects.

**Comment by jeremystretch** [comment]
Implemented in dd1991f
