### ISSUE TITLE
Enable CORS on API

### ISSUE THREAD

**Issue by mraerino** [digitalocean/netbox#843]
Right now one can't use the Netbox API for frontend/js apps without setting up an api proxy, because the preflight OPTIONS request of the browser is not recognized by the API and therefore not successful.

This could be handled by a custom DjangoRestFramework permission class like here: http://stackoverflow.com/questions/30460409/how-do-i-check-for-options-request-in-django-rest-framework-3-0-serializer

**Comment by jeremystretch** [comment]
The current API is mostly read-only anyway. Write ability will be introduced in 2.0 (#113).

**Comment by mraerino** [comment]
This is not a matter of read or write.
I also need CORS if I want to show data from the API in some JS Application.

**What do I want to do with it?**
I want to make a simple site, where all the racks of a site are displayed next to each other with their devices in them.
Right now this is not possible if I don't host this site on the same origin as netbox.

**Comment by jeremystretch** [comment]
As I understand it (and I could easily be wrong), preflight checks aren't required for simple GET requests. Can you provide an example request that your application is sending?

**Comment by mraerino** [comment]
Unfortunately Preflight requests are made for all requests that have special headers like "Authentication": https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests
I think this is true for most cases, since people tend to enable `login_required`.

But even if there is no preflight, the server still needs to return `Access-Control-Origin: *` for all requests.

**Comment by jeremystretch** [comment]
Noting here for reference: https://github.com/ottoyiu/django-cors-headers/
