### ISSUE TITLE
Interfaces on "connect interface" page out of order

### ISSUE THREAD

**Issue by hsychla** [digitalocean/netbox#844]
Hi, 

we updated from 1.7.1 to v1.8.2 and in the menu to select the other end of a connection (Device => Interface => "+") the interfaces of the remote device are sorted 1,10,11 ... 2,20,21 ...

![screenshot_2017-01-25_11-55-26](https://cloud.githubusercontent.com/assets/540317/22288212/27d94980-e2f6-11e6-99c7-4632ac33137d.png)

I am not 100% sure but think that this was not the case before the update. 
Could this come from #284  ?

**Comment by jeremystretch** [comment]
Yep, this was a regression introduced by #284. Should be an easy fix.

**Comment by hsychla** [comment]
Awesome, thanks!
