### ISSUE TITLE
Customise 'Tenants' name

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#846]
I'd like to be able to dynamically change the name 'Tenants' to something more relevant to our organisations infrastructure deployment. An example would be 'Customers'. 

We use Netbox to manage all our remote CPE and Switching infrastructure at our customers sites rather than hosting centers. 

Would something like this be considered in the future?

**Comment by jeremystretch** [comment]
The term _tenancy_ was chosen for its ambiguity, to ensure that it would apply to most use cases. "Customers" might make more sense for your case, but it would make less sense for a NetBox installation tracking subsidiary companies, internal departments, schools, etc. A customer is still a tenant of your network even if you don't physically house any of their resources.
