### ISSUE TITLE
No option to remove groups and users from Secret Roles in Admin interface

### ISSUE THREAD

**Issue by specialcircumstances** [digitalocean/netbox#847]
When trying to adjust the groups associated with Secret Roles, I can't see any way to remove groups or users. All users and groups appear to have access to the Secret Role, and while there is an + (add) button, I can't see a way to remove users/groups.

**Comment by jeremystretch** [comment]
De-select in the list the user/groups you want to remove and click save. Hold control/command to toggle options individually.
