### ISSUE TITLE
Tenant sorting

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#848]
It seems that by default Netbox sorts the list of Tenants using the Group name instead of the Tenant name? Where there are multiple groups, the list is built per Group and not as a total list.

Example:

ABC001 - GROUP1
ABC002 - GROUP1
DEF001 - GROUP1
ABC002 - GROUP2
DEF002 - GROUP2

**Comment by jeremystretch** [comment]
Yes, that's correct. This is intended behavior. Of course, you can always sort tenants by name by clicking the "Name" column header.
