### ISSUE TITLE
Import/Export on python 3 fails

### ISSUE THREAD

**Issue by flycam** [digitalocean/netbox#851]
On python 3.5 imports and exports are failing with an exception.

Trying to export anything (connections, prefixes, devices etc) returns:
```
<class 'NameError'>

name 'unicode' is not defined
```

On Import any input triggers this error:
```
<class '_csv.Error'>

iterator should return strings, not bytes (did you open the file in text mode?)
```
running the same netbox installation on 2.7 works just fine. 
Repo cloned on 2017-01-28

**Comment by hnk** [comment]
We run into the same issue during import, django debug says the exact spot of the error is here:
https://github.com/digitalocean/netbox/blob/develop/netbox/utilities/forms.py#L247
