### ISSUE TITLE
Add "status" to Import Devices

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#853]
I would like to be able to import "comments" as part of bulk device import. Also device "status" (Active or Offline)

Related:

* #568 - Bulk import custom fields
* #655 - Convert CSV import to use headers

If #655 were implemented, then presumably it would be trivial to allow all fields of the device to be imported.

**Comment by jeremystretch** [comment]
I've shied away from enabling the import/export of free-form comments because we may run into issues concerning line breaks and formatting. I'm sure it's workable, I just haven't had the time to test it.

**Comment by candlerb** [comment]
Should be OK now #422 is done I think

**Comment by jeremystretch** [comment]
We still need to devise a method for dealing with line breaks in comments.

**Comment by candlerb** [comment]
The CSV format supports it by means of line breaks within quoted fields, even though such CSV files aren't amenable to normal Unix tools like grep.

e.g. a cell with a line-break in Excel:

![image](https://cloud.githubusercontent.com/assets/44789/24254116/f6673f04-0fd9-11e7-9128-b5ea3423dcb5.png)

Exported as CSV:

~~~
$ cat Workbook1.csv
"Foo
Bar"

$ hexdump -C Workbook1.csv
00000000  22 46 6f 6f 0a 42 61 72  22                       |"Foo.Bar"|
00000009
~~~

Imported into Python:

~~~
>>> import csv
>>> for r in csv.reader(open('Workbook1.csv')): print repr(r)
...
['Foo\nBar']
>>>
~~~

**Comment by jeremystretch** [comment]
I'm limiting the scope of this issue to the addition of the "status" field. We don't currently support the importation of comments for any models; that can be addressed separately in the future.
