### ISSUE TITLE
Include Recent Activity in the API

### ISSUE THREAD

**Issue by AngusP** [digitalocean/netbox#855]
Recent activity presented on the homepage is not accessible through the API. Being able to monitor changes could reduce the amount of traffic to the API if a third party is just looking for changes.

**Comment by jeremystretch** [comment]
Do we want an API endpoint for this? Or would it be more appropriate to generate an RSS feed?

**Comment by lampwins** [comment]
I could see a use case for both. For instance, I am working on an api client and would obviously want an endpoint for that but and RSS feed would be useful for more human centric digesting.

**Comment by jeremystretch** [comment]
I've included a "recent activity" endpoint in API 2.0. A new feature request can be opened if there's interest in an RSS feed.
