### ISSUE TITLE
Ability to collapse/minimize DHCP addresses in IP address view

### ISSUE THREAD

**Issue by fourg** [digitalocean/netbox#857]
Would like to see a way to collapse, hide, or minimize the IP's which are listed as DHCP for a prefix.  While it's important to track our DHCP scope(s), it's much less important to list all of them when 99% of the time we're working on entries for those outside of DHCP.

**Comment by jeremystretch** [comment]
#834 would introduce IP ranges, replacing a consecutive set of discrete IPs with a single range object. But in the interim, it would make sense to include a simple filter panel to allow hiding IPs by status/role.

**Comment by snazy2000** [comment]
This would be a very handy feature!

**Comment by mikeysouthwell** [comment]
Is there any word on when this change will be implemented? We have just started using NetBox in our environment and adding a DHCP range for a large number of IP addresses is messy when you need to scroll through multiple pages considering not all IP addresses are always in use.

**Comment by jeremystretch** [comment]
Not sure why this issue is still open. We already have status and role filters for IP addresses. You can hide DHCP IPs by selecting only the other three statuses in the list.

**Comment by mikeysouthwell** [comment]
Hi Jeremy,

Can you please be more specific regarding the ability to hide DHCP IPs?
The only option I can see is to sort by status.

Is the option to condense DHCP ranges such as in phpIPAM still in development and do you know if there is an ETA on this yet?

Thanks again for your help with this, it is much appreciated!

**Comment by netpanic** [comment]
Would it be possible to hide all of the dhcp addresses when you look at the prefix's without having to filter them out each time, it is very tedious and messy atm. Or make it possible to condense all dhcp addresses into one object so you dont have to scroll through multiple pages. Thanks
