### ISSUE TITLE
Child devices define location

### ISSUE THREAD

**Issue by jamesdonnell** [digitalocean/netbox#860]
Currently, on v1.8.3, it is not possible to have a single device span multiple Us inconsistently. For example, I have a Juniper Virtual Chassis comprised of 4 Juniper 1U switches that logically act as one. One routing engine, one IP, one configuration. If that doesn't make sense, hopefully this will, I have them in a cabinet as followed:
7 - Patch Panel
6 - Juniper EX4200 Switch
5 - Juniper EX4200 Switch
4 - Patch Panel
3 - Patch Panel
2 - Juniper EX4200 Switch
1 - Juniper EX4200 Switch
0 - Patch Panel

In the terms of the closet, it keeps it neat as shorter cables can be used. In terms of NetBox, there is no way to document 4 individual switches in various positions as one single device. What I am requesting is a way to allow us to document Parent devices with the interfaces/configuration/etc and the child devices as the location. In the "Network Rack" view, it would show the parent device information in all child device locations.

Let me know if anything needs clarity! Would love to see this possible!

**Comment by candlerb** [comment]
A "stack" of multiple devices could be another application for the "cluster" concept (#142)

**Comment by jeremystretch** [comment]
I looked into the possibility of modeling virtual chassis a while back (see #99) and it would be a enormous undertaking to get working, assuming it's even feasible. I'm not saying it'll never happen, but there are many other popular feature requests with much lower barriers to implementation.
