### ISSUE TITLE
Report on missing primary addresses

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#863]
It would be helpful to identify:

* Devices which have at least one IPv4 address, but no Primary IPv4 address has been chosen
* Devices which have at least one IPv6 address, but no Primary IPv6 address has been chosen

These can be identified using an ad-hoc query:

~~~
select dev.name,addr.family,addr.address
from dcim_device dev
join dcim_interface intf on dev.id = intf.device_id
join ipam_ipaddress addr on intf.id = addr.interface_id
where (dev.primary_ip4_id is null and addr.family = 4)
   or (dev.primary_ip6_id is null and addr.family = 6)
order by dev.name;
~~~

Ideally if there is only one choice, I'd like to be able to connect the primary address automatically. These candidates can be identified:

~~~
select dev.name,addr.family,min(addr.address),count(*)
from dcim_device dev
join dcim_interface intf on dev.id = intf.device_id
join ipam_ipaddress addr on intf.id = addr.interface_id
where (dev.primary_ip4_id is null and addr.family = 4)
   or (dev.primary_ip6_id is null and addr.family = 6)
group by dev.id,addr.family
having count(*) = 1;
~~~

However my SQL knowledge doesn't extend to nesting this with an UPDATE :-)

**Comment by jeremystretch** [comment]
There's a _lot_ of stuff we could do reporting on, and I've purposely avoided opening that can of worms for now. However, if you're reasonably versed in Python and interested in learning [Django's ORM](https://docs.djangoproject.com/en/1.10/intro/overview/), it's pretty easy to generate whatever form of report you'd like. Here's an example.

> Devices which have at least one IPv4 address, but no Primary IPv4 address has been chosen

```
./manage.py shell
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from dcim.models import Device
>>> Device.objects.filter(primary_ip4=None).exclude(interfaces__ip_addresses__isnull=True)
```
