### ISSUE TITLE
Upgrading from v1.7.3 to v.1.8.3 Error

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#864]
Haven't had the chance to upgrade (using the documented option B process) for a while.
During the upgrade process received the following error during the lxml uninstall/install:

> Found existing installation: lxml 3.7.0
>     Can't uninstall 'lxml'. No files were found to uninstall.
>   Running setup.py install for lxml
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
>         import setuptools.version
>       File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
>         import pkg_resources
>       File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
>         import packaging.version
>     ImportError: No module named packaging.version
>     Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2yNGXh-record/install-record.txt --single-version-externally-managed --compile:
> 

This resulted in a traceback call of:

> Traceback (most recent call last):
> 
>   File "<string>", line 1, in <module>
> 
>   File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
> 
>     import setuptools.version
> 
>   File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
> 
>     import pkg_resources
> 
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
> 
>     import packaging.version
> 
> ImportError: No module named packaging.version
> 

Since lxml wasn't properly uninstalled due to the error, received:

> Can't roll back lxml; was not uninstalled

Which resulted in the entire process of rolling back the install failing.
Currently this install is dead in the water, any assistance would be grand.

**Comment by jbro209070** [comment]
I didn't have the exact same issue, but I had the issue where it was saying that there was no module named packaging.version. Here is what I used to correct it:

Uninstall pip:
sudo apt-get purge python pip

Re-install pip:
curl https://bootstrap.pypa.io/get-pip.py | sudo python

When you try to run your web server it will tell you to run this command:

python manage.py migrate

After this netbox will start working as intended.

FYI, this is the 3rd or 4th post stating there are problems upgrading the 1.7 train to the 1.8. This may indeed be a Netbox issue.

**Comment by elJoeyJojo** [comment]
hello, i tried upgrading v 1.7 to 1.8.3 and get lots of errors! 

Could not find .egg-info directory in install record for cryptography>=1.4 from https://pypi.python.org/packages/99/df/71c7260003f5c469cec3db4c547115df39e9ce6c719a99e067ba0e78fd8a/cryptography-1.7.2.tar.gz#md5=fade66de437392ed1ba6980768626204 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))

Could not find .egg-info directory in install record for django-tables2>=1.2.5 (from -r requirements.txt (line 7))

Could not find .egg-info directory in install record for Markdown>=2.6.7 (from -r requirements.txt (line 10))

 Could not find .egg-info directory in install record for psycopg2>=2.6.1 from https://pypi.python.org/packages/7b/a8/dc2d50a6f37c157459cd18bab381c8e6134b9381b50fbe969997b2ae7dbc/psycopg2-2.6.2.tar.gz#md5=4a392949ba31a378a18ed3e775a4693f in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))


ImportError: No module named packaging.version

----------------------------------------
  Can't roll back lxml; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tJdXI7-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
Storing debug log for failure in /home/netbox/.pip/pip.log
Traceback (most recent call last):

is it best to wait for a fix in the upgrade script?

**Comment by rburkholder** [comment]
I am having problems install 1.8.3 on a debian stretch system.  I'm having lots of problems with the requirements.txt file.  An example for trying only one element of the list:

```opt#  https_proxy=http://10.155.0.10:3128 pip install Django
Collecting Django
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

**Comment by swickstrom** [comment]
I have confirmed jbro209070's solution fixes the issue; proceed at your own risk.

**Comment by jeremystretch** [comment]
Unfortunately, this is an issue with Python's pip/setuptools, and not something I can fix from within the NetBox codebase.

**Comment by elJoeyJojo** [comment]
@jbro209070 thanks dude! without your HUGE HELP I'd never gotten this thing to work! appreciate everyone else's input as well! i am now on Netbox 1.8.3 (Y)

**Comment by jbro209070** [comment]
No problem guys, happy to help!

**Comment by jeremystretch** [comment]
I ran into this issue myself while building a new Python 3 virtualenv. It seems that the trick was to upgrade pip and setuptools prior to installing any packages:

```
$ pip install --upgrade pip setuptools
...
$ pip freeze
appdirs==1.4.0
packaging==16.8
pyparsing==2.1.10
six==1.10.0
```

From here, `pip install -r requirements.txt` completed with no issues.
