### ISSUE TITLE
Add ID/Description/Comments field to circuit terminations

### ISSUE THREAD

**Issue by alexjhart** [digitalocean/netbox#867]
In addition to a circuit having an ID (that field already exists), it is common for each termination (A and Z sides) to have their own unique IDs as well (think UNI ID). This could just be added as a text field with the name "ID", but I could see the benefit of having a more generic field if people have other information they want to track.

**Comment by jeremystretch** [comment]
As it is, we've got description and text fields on the circuit itself. Might this be overkill?

**Comment by alexjhart** [comment]
The description and text fields are only for the circuit. I'm talking about the termination, not circuit (A/Z side). I certainly don't think this is overkill. I'd be curious to hear from others. I hope I did a good enough job of stating the case for this. 

Without making this enhancement, I'm left entering something like this in the comments field of the circuit:
Site X (termination A) ID: xxxyyyzzz
Site Y (termination Z) ID: yyyzzzxxx

That seems like more data entry than should be required and doesn't tie the information to the object it pertains to. 

I imagine this will get added right below the patch panel/port field.

**Comment by muddus** [comment]
Or the option to add custom fields to circuit termination form just like the circuit.

**Comment by alexjhart** [comment]
That would work too
