### ISSUE TITLE
Connected/Planned Buttons Non-Functional v1.8.3

### ISSUE THREAD

**Issue by swickstrom** [digitalocean/netbox#868]
After updating from v1.7.3 to v1.8.3 the Connected/Planned buttons on all interfaces/connections only function to mark as Planned; after clicking it you cannot set it to Connected. Only solution at the moment is to delete/reconnect said connections.

Confirmed in OS X 10.9.5
-Chrome 56.0.2924.87
-Safari 9.0.3 (9537.86.4.4)
-Vivaldi 1.6.689.40

**Comment by jeremystretch** [comment]
Duplicate of #859. Will be fixed in 1.8.4.

**Comment by swickstrom** [comment]
Sorry for the duplicate, forgot to do a search before posting.

**Comment by jeremystretch** [comment]
No worries, thanks for taking the initiative to file a bug report in the first place!
