### ISSUE TITLE
Add support for IP address statuses

### ISSUE THREAD

**Issue by billyzoellers** [digitalocean/netbox#87]
Similar to request #36 for reserving rack space without a device, it would be useful to be able to reserve a range of IP space without needing to have an associated device (or 200 separate IP address entries).

For example, in most of our access segments we use a /24. 20-220 are generally handed out by a DHCP server, so we want to be able to note that without specifically tracking devices.

**Comment by jeremystretch** [comment]
Redefining this slightly to entail the addition of a `status` field to the IPAddress model, similar to what exists on Prefix and VLAN. It should be sufficient to create a number of individual IP address objects to denote reserved IPs.

**Comment by billyzoellers** [comment]
One thought from me on this - I think the status field does address this issue, but I'm thinking about this from an ease of use perspective.

Sure, I can create 200 IP address objects via bulk creation with the description "DHCP pool" and "used" status, but when I need to decease that pool by 20 IPs, do I have to hit 20 checkboxes? Wondering if there is a better way UI wise to do that.

**Comment by jeremystretch** [comment]
Ideally you'll be able to search for e.g. 192.168.0.[180-199], select all, and delete. Still working on the address expansion bit.
