### ISSUE TITLE
Bug in IP address -> bulk add (1.8.4, Python 3)

### ISSUE THREAD

**Issue by Mk-00** [digitalocean/netbox#872]
Hi,

looks like there is a bug when trying to add an IP range in "bulk" tab.

Exception Type: TypeError at /netbox/ipam/ip-addresses/bulk-add/
Exception Value: 'KeysView' object does not support indexing Request information:

**Comment by Armadill0** [comment]
Works for me with "127.0.0.[1-5]/8".

Which string did you try to bulk add?

**Comment by Mk-00** [comment]
I tried now also "127.0.0.[1-5]/8" and got the same error.
