### ISSUE TITLE
Hide "VRF" column when browsing addresses under IP prefix

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#874]
Minor suggestion for improvement:

When you are browsing the IP addresses within a prefix, there is no need to show the "VRF" column, because all the addresses by definition belong to the VRF of the prefix.

For example, say:

* prefix id 44 is 192.168.5.0/24 VRF 'Global'
* prefix id 69 is 192.168.5.0/24 VRF 'Test'

When you are browsing the IP addresses within these prefixes, you are browsing:

* `/ipam/prefixes/44/ip-addresses/`
* `/ipam/prefixes/69/ip-addresses/`

The first link shows only addresses within 'Global', while the second only shows addresses within 'Test', so the 'VRF' is implied.

**Comment by jeremystretch** [comment]
If we exclude the VRF column, the VRF is not mentioned anywhere on the page. The user would need to navigate back to the parent prefix view to confirm its VRF. Additionally, we're not pressed for horizontal space in the table. I don't see any reason to exclude it.

**Comment by candlerb** [comment]
> If we exclude the VRF column, the VRF is not mentioned anywhere on the page

When viewing a prefix, it's in the breadcrumbs:

![image](https://cloud.githubusercontent.com/assets/44789/22819565/9c0d6f90-ef6a-11e6-9912-36e210dd2335.png)

But agreed it's not very visible.

I think it would be a good idea for the VRF to be displayed as part of the prefix label (i.e. the h1 in big black letters).

![image](https://cloud.githubusercontent.com/assets/44789/22819706/3d8dab64-ef6b-11e6-8e6b-0fc37a64b189.png)

Otherwise, if you have overlapping addresses with VRFs, it's very easy to be looking at a prefix and not realise which one it is.

> Additionally, we're not pressed for horizontal space in the table.

Fair enough.

I did think it was unnecessary duplication. However I subsequently found there is one case where it's not:

* You're looking at a *prefix* in the *global* VRF
* You're looking at *child prefixes* (not child addresses)

In this particular case, netbox shows child prefixes in all VRFs, not just the global one. So the VRF column is required there.  And it's needed there, it may as well be consistently everywhere, even if not required in the other cases.
