### ISSUE TITLE
Display rack utilisation

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#877]
When listing racks, display space utilisation (units used / total height). Preferably nice coloured bars like aggregate utilisation does.

A little care is needed with front/back mounting. I think you could overlay bars. Suppose you have 6U where both front and back are used, another 6U where only front are used, and 10U where only back are used. This is 6U (both) and 10U (maximum of front-only or back-only), giving utilisation of 16U, and could display as:

~~~
XXXXXXxxxxxxxxxx........
 |        |
both   front-or-back only
~~~

This is less than perfect, since adding a 4U box may not be possible without serious juggling if the available space is 4 x 1U. However, a figure for the largest contiguous gap could also be shown.

Relates to reserving rack space (#36), floorplan visualisation (#114)

**Comment by jeremystretch** [comment]
There's a lot of overhead in calculating utilized rack space. We already report on percentage of free space available; I'm pretty happy with that.

**Comment by candlerb** [comment]
> We already report on percentage of free space available

OK, operator error - I didn't find it initially. Thanks.
