### ISSUE TITLE
Search for IP address by device name

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#879]
When I am searching for IP addresses e.g. at `/ipam/ip-addresses/` or at the front page, I would like to be able to enter a device name (or part of device name) and see all the IP addresses associated with that device.

At the moment, this only matches if the IP address description includes the device name.

Workaround: return to front page, enter text in 'Device' search instead.

More general solution: global search #159 / #873

**Comment by jeremystretch** [comment]
This will be addressed by #159
