### ISSUE TITLE
Expose ModelMultipleChoiceFilter query parameters in swagger

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/netbox#88]
Show users that some API endpoints can accept the same parameter several times to enable further filtering.  Could be nice to expose this with swagger if possible. For example: `GET /api/ipam/aggregates?slug=apnic&slug=ripe`.

**Comment by jeremystretch** [comment]
This doesn't seem possible using Swagger. We might have better luck using the new built-in docs under Django REST Framework 3.6 (if I can get them working).
