### ISSUE TITLE
Grid edit (spreadsheet) view?

### ISSUE THREAD

**Issue by candlerb** [digitalocean/netbox#880]
There are two ways to view a table of devices:

* `/dcim/devices/`
* `/admin/dcim/device/`

But neither allows in-place editing, which would be extremely helpful when reviewing a subset of devices and making updates.

Currently this involves going through two more pages (`/dcim/devices/<N>/`, then '/dcim/devices/<N>/edit/`) then navigating back to where you were.

Quick and dirty option: add edit button to each row which directly opens `/dcim/devices/<N>/edit/` in a pop-up window (and ideally refreshes parent when it is closed)

**Comment by jeremystretch** [comment]
This will be a lot easier to implement once API 2.0 is in place. Django does support editing multiple objects at once via [formsets](https://docs.djangoproject.com/en/1.10/topics/forms/formsets/) but I try to avoid them.

**Comment by jeremystretch** [comment]
Let's revisit this idea once we have a more responsive, API-driven front end in place.
