### ISSUE TITLE
Device view should have a next device, previous device button

### ISSUE THREAD

**Issue by ghost** [digitalocean/netbox#883]
Similarly to the rack view which has a next rack, previous rack, this should be there for the device view. 

(adding as an issue to see if there's desire for the feature, before I work on the PR)

**Comment by jeremystretch** [comment]
What criteria would you use for selecting the "next" device?

**Comment by patrick-livestream** [comment]
Perhaps assume the numbering. When you're at say 42, and it goes in standard orientation, remove the next button (if it's a 42U rack), and if you're at 1, remove the previous button? swap this around based on the checkbox for descending units.

**Comment by jeremystretch** [comment]
I don't think it makes much sense to page through a rack one device at a time. You can just go to the rack elevation view and open the desired devices.
