### ISSUE TITLE
Add "duplicate" Rack, Device, etc...

### ISSUE THREAD

**Issue by patrick-livestream** [digitalocean/netbox#885]
It'd be much easier to duplicate the device in some of the more complex devices than to start over.

(adding as an issue to see if there's desire for the feature, before I work on the PR)

**Comment by jeremystretch** [comment]
This is the function of device types. Each instantiation of a device type will automatically create the associated components. Is there specific functionality you're looking for?

**Comment by patrick-livestream** [comment]
Sorry! I meant Device Type. As an example, lets say I have 3 different models of Dell 2U's, and I want to be able to add each of them as a device type, right now I'd have to fill in each of the items from scratch, it'd be great to be able to "create another" and pre-populate the previous successful creation.

**Comment by jeremystretch** [comment]
Sounds like #33 would cover this, do you agree?

**Comment by patrick-livestream** [comment]
yep! closing!
