### ISSUE TITLE
Ability to update default rack size (or add additional racks)

### ISSUE THREAD

**Issue by patrick-livestream** [digitalocean/netbox#887]
We can edit most of the items within a rack, but we can't seem to edit the default size of a rack. We should probably make this something we can do :)

(adding as an issue to see if there's desire for the feature, before I work on the PR)

**Comment by jeremystretch** [comment]
Seems excessive to me. I want to avoid adding too many configuration parameters.

**Comment by patrick-livestream** [comment]
I guess the logic for me was that I have a few sites, some with 42, some with 45, and updating the rack field each time is annoying, but honestly it shouldn't happen more than a few dozen times in most installations that it may not actually be worth the effort. Closing unless someone else someone else pipes up in the thread.
