### ISSUE TITLE
Default focus to the name block on new device, etc... views

### ISSUE THREAD

**Issue by ghost** [digitalocean/netbox#888]
Right now there's no default block, it'd be a little faster if we defaulted the view to setting focus in the name block of the view.

(adding as an issue to see if there's desire for the feature, before I work on the PR)

**Comment by jeremystretch** [comment]
Personally, I'm not a big fan of autofocus, but let's see what others think.

**Comment by jeremystretch** [comment]
I'm going to close this out as I don't really see the value in it.
