### ISSUE TITLE
OAuth Support?

### ISSUE THREAD

**Issue by ghost** [digitalocean/netbox#889]
It'd be really neat if we could login using facebook, google, github, etc... instead of using local / ldap auth. 

(adding as an issue to see if there's desire for the feature, before I work on the PR)

**Comment by jeremystretch** [comment]
I'd like to avoid extending native support for any authentication methods beyond the built-in and LDAP methods already supported. Any additional authentication methods will need to be implemented via the httpd front end (e.g. nginx or Apache) and user information passed to NetBox via a header. There's been some talk of this already in #118 so I'm going to close this issue out in favor of continuing the discussion there.
