### ISSUE TITLE
Bulk edit buttons missing from ipam/prefixes/.../ip-addresses/

### ISSUE THREAD

**Issue by royvegard** [digitalocean/netbox#892]
When opening the IP Addresses list under the Prefix form, the bulk edit buttons do not appear.

![image](https://cloud.githubusercontent.com/assets/54801/22843609/a08d216c-efda-11e6-8e8b-da8073cbafc5.png)
I have marked up where I would expect them to appear.

Seems to be related to #845. Before the fix to #845, the buttons appear for superuser.

**Comment by rmuehl** [comment]
Not only at IP-Addresse! Also at the prefixes itself are missing these buttons.

Additional: the "select all not visible too" checkbox does not pop up.
