### ISSUE TITLE
Ability to filter for unnamed devices

### ISSUE THREAD

**Issue by Armadill0** [digitalocean/netbox#893]
Currently devices which have no name specified can only be found fast by sorting them by name in inverted order. This is ok if there are only a few systems without a name. If their number increases this is getting quite cumbersome.

To enhance this it would be handy if we could get a filter switch to filter for unnamed devices.

**Comment by jeremystretch** [comment]
Added `NullableCharFieldFilter` for rack facility IDs, device names and asset tags, and inventory item asset tags. This allows us to filter by, for example, `/api/dcim/devices/?name=NULL` to return only unnamed devices.
