### ISSUE TITLE
Increase "name" field maxmimum length from 50 characters

### ISSUE THREAD

**Issue by InsaneSplash** [digitalocean/netbox#894]
The current limit for characters in the name of a tenant,site,rack, device is set to a maximum of 50 characters. Can this be increased to say 100?

Example Import:
```
Record 11 (name): Ensure this value has at most 50 characters (it has 58).
Record 12 (name): Ensure this value has at most 50 characters (it has 55).
Record 13 (name): Ensure this value has at most 50 characters (it has 60).
Record 14 (name): Ensure this value has at most 50 characters (it has 59).
Record 15 (name): Ensure this value has at most 50 characters (it has 59).
Record 16 (name): Ensure this value has at most 50 characters (it has 51).
Record 17 (name): Ensure this value has at most 50 characters (it has 56).
Record 18 (name): Ensure this value has at most 50 characters (it has 53).
Record 19 (name): Ensure this value has at most 50 characters (it has 55).
Record 20 (name): Ensure this value has at most 50 characters (it has 52).
Record 21 (name): Ensure this value has at most 50 characters (it has 58).
Record 22 (name): Ensure this value has at most 50 characters (it has 58).
Record 23 (name): Ensure this value has at most 50 characters (it has 56).
Record 25 (name): Ensure this value has at most 50 characters (it has 61).
Record 26 (name): Ensure this value has at most 50 characters (it has 59).
Record 28 (name): Ensure this value has at most 50 characters (it has 58).
Record 29 (name): Ensure this value has at most 50 characters (it has 52).
Record 30 (name): Ensure this value has at most 50 characters (it has 55).
Record 31 (name): Ensure this value has at most 50 characters (it has 57).
Record 32 (name): Ensure this value has at most 50 characters (it has 52).
```

**Comment by jeremystretch** [comment]
Can you provide an example of a name that's too long? I'm curious.

**Comment by InsaneSplash** [comment]
As an example, we chose to make use of a router hostname that contains identifying information. Due to the vast number of devices, sites and tenants we have, it helps locate the device across databases, monitoring and the like. Below is an example CPE hostname that we may use.

Example:
CUSTCODE-BUSINESSUNIT-BRANCHCODE-CPETYPE-LOCATION

As you can imagine this can quite easily become a name larger than 50 characters. Just the above vanilla example is 49 characters.

We are in the process of importing all our disparate technical information (1st Tier ISP) in to Netbox and have so far over 3500+ sites, 1500+ tenants which is easily expected to double once we get closer to completing the import. Each site could have more than 10 devices at times.

Great product btw!

**Comment by rlaneyjr** [comment]
I see this problem all too often.  Why do we need that much information from one name?  All of the info can be easily gathered by digging just a little deeper.  We have gotten so lazy, we expect to look at one name and identify location, business unit, site, building, floor, closet, cage, rack, serial number, IP address, MAC address, fqdn,...  Sorry, I got carried away.  I needed to vent.

**Comment by adamcooley** [comment]
I've personally not had this problem as we've always kept identifying information on interface descriptions or in the snmp sections on configs, but this shouldn't really be a problem to change can it? I can't come up with any dependencies that would break and would give the greater community more flexibility.

**Comment by jeremystretch** [comment]
Even if we widened the field, we'd have to implement truncation in many places when displaying the device name (such as in the device list) to keep the layout readable.

Interestingly, [RFC 1035](https://tools.ietf.org/html/rfc1035#section-2.3.1) suggests a limit of 63 characters for host names, and my Ubuntu-based system seems to enforce a 64-character limit:

```
$ getconf HOST_NAME_MAX
64
```

**Comment by jeremystretch** [comment]
@InsaneSplash how do you feel about a 64-character limit?

**Comment by V5ctor** [comment]
higher is better

**Comment by jeremystretch** [comment]
64 characters should be more than sufficient. This is the maximum hostname length for many platforms.

**Comment by InsaneSplash** [comment]
Thanks for the increase in characters!
