### ISSUE TITLE
Additional IP Address Column

### ISSUE THREAD

**Issue by bradical987** [digitalocean/netbox#895]
It would be great to add a "parent" or "prefix" column to the view for IP Addresses so it would be easier to determine which IP's are, for lack of a better word, orphaned from a prefix. When I click on the `IP Address` menu to view all the "host" IP's, one thing I can't determine without a great deal of effort is which IP's belong to a prefix and which ones have been added without a prefix.

**Comment by jeremystretch** [comment]
I'm not sure this makes sense to include in the IP addresses table. There's a significant performance hit to make an additional query for each IP in the list, and it's not information that's going to be needed most of the time. (We're also a bit pressed for horizontal space.)

Orphan IP addresses are probably better detected using a yet-to-be-developed reporting feature that could be run without interfering with the main table.

**Comment by bradical987** [comment]
To prevent the performance hit of the additional query, maybe it is a better idea to just require a prefix to be created before a host IP can be added. It just seems like there is a pretty big disconnect between the host IP's and the prefixes.

**Comment by jeremystretch** [comment]
> maybe it is a better idea to just require a prefix to be created before a host IP can be added

Not everyone wants to use NetBox this way. It's a perfectly valid use case to have IPs which don't belong to a parent prefix. For example, you might want to track the IPs assigned to WAN interfaces on CPE devices, but don't care about the prefixes in use on those circuits. (Also, it wouldn't do anything to address the performance concern when listing IP addresses.)
