### ISSUE TITLE
info on automation related to netbox

### ISSUE THREAD

**Issue by adamcooley** [digitalocean/netbox#899]
Hey there, this isn't an issue per-say but I didn't see much other places to post a request for more info. I see you have some hints of automation sprinkled throughout, such as LLDP on device interfaces, and a netbox username for network gear under py configs. Is there some documentation or info on what is being developed right now into netbox for network automation?

**Comment by jeremystretch** [comment]
This was recently discussed on [the mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). Please feel free to join the conversation there.
