### ISSUE TITLE
Anycast IP address multiple device assignments

### ISSUE THREAD

**Issue by contemno** [digitalocean/netbox#906]
Minor request: Be able to assign an IP address to more than one device.

**Comment by jeremystretch** [comment]
Just to clarify, IP addresses are assigned to interfaces in NetBox, not devices.

There's nothing special about an anycast IP address other than that it has been intentionally instantiated multiple times. Thus, it should be sufficient to create multiple IP address objects (each with the same IP) to represent anycast address assignment.

It _might_ be appropriate to create an "anycast" role for IP addresses, which is a proposed feature, but discussion on that should be held in #819.

**Comment by specialcircumstances** [comment]
Would this not be prevented by the prevent duplicate option within a VRF?

**Comment by contemno** [comment]
@specialcircumstances That's correct, it would not be possible if the 'prevent duplicate' option is enabled on a VRF.

The issue I was addressing is when viewing the IP address details page there's no indication that it's an anycast (or virtual) IP address assigned to multiple interfaces (on different devices) within the same VRF. The IP address details page will only list the device and interface associated with the single IP address instance currently being viewed.

The workaround is to disable the 'prevent duplicate' option (if applicable) and label the IP addresses as anycast somewhere in the description field as a cue to the user to manually search for the IP address to find all interfaces (and associated devices) assigned the same IP address in the same VRF.

**Comment by ossark** [comment]
It would be awesome if one can link the same IP to multiple interfaces for Anycast, VRRP, HSRP, CARP etc address types. As the "prevent duplicates" option is somewhat mandatory imo this invalidates the usefulness of the above mentioned address types to almost zero.

**Comment by njgarfield** [comment]
+1
