### ISSUE TITLE
Proposal: Ability to assign and track MAC addresses and pools.

### ISSUE THREAD

**Issue by phobiadhs** [digitalocean/netbox#909]
I propose that MAC address pools, assignment and tracking should all be a part of Netbox. While this likely won't matter quite so much with normal hardware devices, VM's can be assigned dynamic MAC's within a variety of different reserved and private pools. The ability to both define pools, and assign new addresses within these pools will be useful from both a functionality and security standpoint.

Thoughts?

**Comment by Zorlin** [comment]
Personally I don't think this belongs in the core NetBox suite as it doesn't fall into the right side of the 80% rule.

**Comment by jeremystretch** [comment]
NetBox already supports the assignment of MAC addresses to interfaces. It doesn't support VMs though, so introducing support for MAC address pools wouldn't make much sense. Maybe we can revisit this idea after VM support gets implemented.
