### ISSUE TITLE
Allow multiple machines in 1U Chassis

### ISSUE THREAD

**Issue by irasnyd** [digitalocean/netbox#91]
Fantastic application. It is by far the best that I've tried.

I have a significant number of 1U servers that actually house two independent computers within a single chassis. They are arranged side-by-side. Here is an example: http://www.supermicro.com/products/system/1U/6015/SYS-6015TW-T.cfm

The computers are completely independent: they have their own network, USB, IPMI, etc. The one thing they share is the power supply. This may be a complication to consider in the design of a "chassis" system which houses one or more computers.

**Comment by puck** [comment]
It isn't just servers like this, for Open Compute Project racks, we often have 3 servers in a 2U shelf. With some systems 4.

This would also be useful for shelves where you might have multiple modems or other bits of equipment.

**Comment by loganbest** [comment]
or any Cisco UCS chassis or SuperMicro FatTwin chassis

**Comment by ronniefalcon** [comment]
I too vote for this feature!

**Comment by peelman** [comment]
Dell FX2 goes on this list as well.  You can get 8 FC430s in a single FX2 Chassis.

**Comment by paradoxni** [comment]
Another example Dell M1000e can contain up to 32 quarter height blades in 10U.

**Comment by peelman** [comment]
Related to #51

**Comment by peelman** [comment]
Blade chassis in general might have to get fudged; it would probably be unnecessarily complicated to represent vertical blades...but I'd love to see somebody prove me wrong :)

**Comment by puck** [comment]
I was thinking about this on the way into work this morning. Perhaps the model of having "sites", "racks", "devices" and "modules" isn't quite right. Perhaps all sites, racks and devices should be "containers" which can have sub-containers.

This would people to create a structure like this (if they wanted to!):

country -> region -> town -> building -> floor -> room -> pod -> row -> rack -> chassis -> device -> component

Sites, racks, devices etc could be types of containers that can have the relevant metadata that is relevant to that kind of container and allow suitable filtering.

**Comment by peelman** [comment]
@puck see [over here](https://github.com/digitalocean/netbox/issues/198#issuecomment-230858940)

**Comment by puck** [comment]
@peelman ah ha, sounds very familiar. ;)  Same approach to solve two different limitations. ;)

**Comment by jeremystretch** [comment]
The scope of this issue is limited to the installation of subdevices into a rack-mounted chassis (e.g. blade servers). Marking this closed since #197 has been implemented.
