### ISSUE TITLE
Web site demo

### ISSUE THREAD

**Issue by V5ctor** [digitalocean/netbox#910]
Hello, 

I just want to know if there is a demo web site and if not , are you planning to make one again ? It will be very helpful for my configuration. 
If you don't want to provide a demo, can you share some screenshots ?

Best regards.

Ps: Sorry for my English, this isn't my native language.

**Comment by fdebonneval** [comment]
Hi there,

Jeremy just launched a request for contributors on the net box ML : https://groups.google.com/forum/#!topic/netbox-discuss/zgAs8x7pnJk
Seems that making a public demo is not a compute resource issue, but a time issue to produce a relevant dataset for the demo.

Meanwhile if you cannot run the docker-compose stack locally, I tested with http://play-with-docker.com and you can get a running instance for a few hours.
Just get to the page
  * enable a new instance with the button "+ add new instance"
  * launch tmux `# tmux`
  * clone the repository : `# git clone https://github.com/digitalocean/netbox.git`
  * get into netbox folder `# cd netbox`
  * you can stay on 'develop' branch or checkout to a specific tag
  * run the stack with `# docker-compose up`
  * open the page using the link to port '80' on top of the page
  * login and change the admin password

Hope that will help.
Foucault

**Comment by V5ctor** [comment]
Thank you for replying but I'm interested but how you organize all your Netbox.  Just to see how well  organize my data.

**Comment by changux** [comment]
Should be great if Netbox has a complete demo data to import, not only to dcim.

**Comment by altokarev** [comment]
2019. Is there any demo or full dump with dummy data (DCIM and IPAM) yet?

There are a few difficulties in IPAM organization that I can't handle without an example.

Rather, I can, but with an example, it would be much easier for me. Thanks.

**Comment by altokarev** [comment]
@jeremystretch ?

**Comment by DanSheps** [comment]
There is no demo currently, I don't know if one is planned or not.

**Comment by sasschary** [comment]
@jeremystretch Did anything ever come of the discussion of a demo site in the Google group? If not, I would be willing to come up with demo data, provided the resources for actually hosting the demo site.

**Comment by PackeTsar** [comment]
I set up netboxdemo.com for this purpose. Username and password is `netbox`. There is some test data in there as an example for new users to see. The database resets every night to remove any modifications made. If anybody here is interested in becoming an admin of the site to assist with adding to the example data, let me know.

**Comment by sasschary** [comment]
@PackeTsar I would be more than happy to help with providing example data, if you'd like the help.

**Comment by hSaria** [comment]
Maybe use the data in the `demo-data` branch.
