### ISSUE TITLE
Need more information extras/export templates

### ISSUE THREAD

**Issue by Sarkaniok** [digitalocean/netbox#911]
1) This example below creates only *.txt file :
{% for d in queryset %}{% if d.status and d.primary_ip %}define host{
        use                     generic-switch
        host_name               {{ d.name }}
        address                 {{ d.primary_ip.address.ip }}
}
{% endif %}{% endfor %}
How can I create *.csv with the same template?

2) For example I have an export template for "content type: device":
device name,address,S/N
{% for d in queryset %}
{{ d.name }},{{ d.primary_ip4.address }},{{ d.serial }} 
{% endfor %}
How can I add to this template information from other database tables like "dcim_site" table? For example "dcim_site.name" or "dcim_site.physical_address"?

Thanks.

**Comment by jeremystretch** [comment]
Please post on the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you'd like help writing export templates.
