### ISSUE TITLE
Patch panel 

### ISSUE THREAD

**Issue by V5ctor** [digitalocean/netbox#912]
I just want to know if there is or there will be a patch panel device in netbox ? 
It will be very usefull for me. This will be to store information in patch panel in racks. 

Best regards.

Victor

**Comment by rlaneyjr** [comment]
I agree with Victor in the sense where you could have a placeholder for a device in the rack.  This would prevent other devices from being added when there is already something there.  Use case would be the Network Team and the Server Team shares the rack.  These placeholders would be arbitrarily named and sized.

**Comment by therealjoshuad** [comment]
I created a device role for it. Even added ports so I can label what's what.

**Comment by rlaneyjr** [comment]
Good idea however, you also have to create a manufacturer, device-type, tenant, platform.  I was wanting to stay away from cluttering my NetBox with stuff I do not manage.

**Comment by therealjoshuad** [comment]
I just use the following

Manufacturer: Generic
Device Type: Patch Panel
Tenant is optional
Platform is optional

I believe there's. even discussion about patch panels in other issue, there might be more suggestions there too

**Comment by V5ctor** [comment]
@therealjoshuad when you says, you labels what's what, you mean you write in description's interface ? because the description isn't directly visible. I can't display what I want in name's interface but it's too long for me.

**Comment by rlaneyjr** [comment]
@therealjoshuad Thanks!  I have created my 1U, 2U, 3U, 4U placeholders.  I feel so dumb...lol.

**Comment by jeremystretch** [comment]
Patch panels will be included in #20. I strongly advise against trying to represent patch panels in NetBox until explicit support has been added.

**Comment by therealjoshuad** [comment]
@v5ctor It's not visible, but if you hover over the comment bubble, it shows it. 

It's definitely not ideal, but we have a Visio diagram with the patch panel port numbers layer over the floor plan. In netbox, I have a patch panel with an interface with the corresponding patch panel number. I then connect the patch panel interface to the appropriate switch interface. So it's represented as two devices connecting to each other, and once #20 is implemented, I'll just re-add the patch panels. It'll be a little extra work, but we're a small company, so we don't have a crazy amount of IDFs
