### ISSUE TITLE
Prefix exports aren't importable

### ISSUE THREAD

**Issue by alexjhart** [digitalocean/netbox#914]
I exported Prefixes, turned around and tried to import and get an error because the export doesn't include all of the fields required for import. I believe this is because none of them had a description entered (because after adding one and exporting again, the right number of fields were  #present).

**Comment by jeremystretch** [comment]
I'm not able to replicate this behavior; exported prefixes match the import format. Note that the description field is present even if blank.

Could you please provide an example?

**Comment by alexjhart** [comment]
Well, I have a copy of the downloaded csv that has the missing commas/fields. However, now that I try to reproduce, it is exporting differently. I'm not sure what triggered it to do that, but I guess you can close this as it is no longer reproducible for me either.
