### ISSUE TITLE
Display/CSS issue

### ISSUE THREAD

**Issue by Mercusio** [digitalocean/netbox#915]
Hi,

I juste installed Netbox on Ubuntu 16.04 and followed the documentations.
It seems to work, but I have an issue with the fonts and display.

![image](https://cloud.githubusercontent.com/assets/8880390/23292745/53b0c884-fa7b-11e6-8932-70365b851c65.png)

I didn't skip any step, so I ran **./manage.py collectstatic** as advised

I hope you can help me.

Regards.

**Comment by jeremystretch** [comment]
Please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you'd like assistance with installation.
