### ISSUE TITLE
Non-Racked Devices

### ISSUE THREAD

**Issue by trikinov** [digitalocean/netbox#916]
It should be possible to assign Non-Racked Devices to a site, and not only to a Rack.

If you have 4 racks with equipment, and some Non-Racked Devices on the same site, you have to add the equipment to one of the racks, or make a Placeholder rack for Non-Racked Devices-

**Comment by therealjoshuad** [comment]
Did you know you can create a Zero U device? You still need to assign it to a rack, but for towers and such, just put 0 for the U count, and then add them to the rack w/o assigning a U position.

**Comment by trikinov** [comment]
Yes, I do that today. But I still have to assign it to a rack.  And if I got several racks in the same room/site, it would be nice to assign it to the site, not rack (it is not inside any of the racks, but mounted on the wall or other.)

Today I add a 1U Rack for all "Non-Racked Devices" just as a container for it, and put Zero U devices not inside a rack to this rack. It is a  workaround, but not optimal.

**Comment by trikinov** [comment]
I didn't see  #198 , I see that the issue has been discussed, and I'll just keep doing my workaround with a Placeholder Rack...  

Closing this issue..
