### ISSUE TITLE
Feature request: keyboard shortcuts

### ISSUE THREAD

**Issue by alexjhart** [digitalocean/netbox#917]
I would like to have keyboard shortcuts to make things easier to navigate. For starters, hitting 'e' should edit the resource(s) I am viewing/have selected. I could also see adding 'a' or 'c' to add/create new items based on the context you are in at the time (ie if you are on the sites page, create a new site). If you are going to do those, I guess it also makes sense to do 'd' for delete. It probably makes sense to have a modal box appear for '?' giving you a guide (see attached image if your not familiar with what sites like gmail show)
![image](https://cloud.githubusercontent.com/assets/216209/23318373/ffb7a1c4-fa86-11e6-856c-fe52e894bb7f.png)

**Comment by jeremystretch** [comment]
This would only complicate the interface without adding any significant value. I'm going to close this out.

**Comment by jsenecal** [comment]
It does have value to those who are using mostly their keyboard to
navigate. It's a feature that could be contributed maybe?
