### ISSUE TITLE
Address fields site import

### ISSUE THREAD

**Issue by adamcooley** [digitalocean/netbox#921]
Can we enhance the import function for sites to include the address fields?

**Comment by adamcooley** [comment]
Actually this was really easy to implement locally in forms.py and updating the sites_import template, I can submit a diff if this would be useful, or if there are some other ideas here.

**Comment by jeremystretch** [comment]
How would you handle line breaks?

**Comment by adamcooley** [comment]
Yeah I'll have to figure that out. my import was just a single line no breaks, we're kind of limited using a csv import aren't we...is an excel format on the horizon?

**Comment by jeremystretch** [comment]
JSON is a possibility in the future, but I don't see us expanding beyond that and CSV.

**Comment by adamcooley** [comment]
awesome lets wait on this then. :)
