### ISSUE TITLE
manage.py migrate unknown command

### ISSUE THREAD

**Issue by muggahtee** [digitalocean/netbox#925]
The install docs refer to running `manage.py migrate`, but this command does not exist

```
[root@host netbox]# ./manage.py migrate
Unknown command: 'migrate'
Type 'manage.py help' for usage.
```

**Comment by jeremystretch** [comment]
GitHub issues are intended for bug reports and feature requests only. If you'd like assistance with installing NetBox, please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). Thanks!
