### ISSUE TITLE
Assign VLANs to Tenants instead of Sites

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#926]
I would like to the ability to assign a vlan or vlan group to either a site _or_ a tenant. My use case is in a university campus. In this design a L3 distribution encompasses several buildings. So this means a vlan defined at the distribution is available in all the buildings of that distribution. The approach we have taken is to define our L3 distributions as tenants and assign the buildings as sites under that tenant. 

To facilitate this, I want to assign a vlan or vlan group at the tenant level as not to have to recreate them all at the site level. Is this something that can be done today and I am just missing it?

**Comment by jeremystretch** [comment]
I may not be following, but it sounds like you're misusing the concept of tenancy. Tenants are intended to represent organizations supported by the network; they can be assigned many types of objects. If you just need to organize sites, v1.9.0 will feature hierarchical regions (see #164).

**Comment by lampwins** [comment]
Yes it is a deliberate misuse of tenants to implement some of the same type of aggregation of sites, etc. Perhaps a better way to state my point is that I want to extend a vlan to many sites without having to recreate it. So if I can assign different objects other than sites to these new regions, that will work.

**Comment by jeremystretch** [comment]
So if I understand correctly, you have, for example, five buildings, each with VLANs 101-105. If this is the case, you _should_ create 25 VLAN objects in NetBox, each assigned to its respective building. This allows you to assign (presumably unique) prefixes to each VLAN within each building. It also allows you to deviate from the devised if and when the need arises (for example, if one building needs an extra two VLANs).

**Comment by lampwins** [comment]
Almost. What I am saying is that the vlan is the same in each of the 5 buildings. The same prefex (the same L2 domain). So in this case, our regions define our L2 domains, they just happen to encompass several sites (which we want for grouping devices, asset management, etc). So what I am asking for is the ability to assign a vlan to site aggregate (region) or an individual site. When it is assigned to a region, it is available to all the nested sites.

**Comment by jeremystretch** [comment]
Oh, I see. Well, v1.9.0 will also decouple VLANs from site assignment (#235), which should help. I think we'll have to stop short of assigning VLANs to regions though, as that would get rather complex. I suggest trying v1.9.0 when it comes out (hopefully by the end of the week) and see if it offers sufficient flexibility.

**Comment by lampwins** [comment]
I believe my needs are covered by #235 in the new release!
