### ISSUE TITLE
Support both IPv4 and IPv6 "Primary IP" for devices

### ISSUE THREAD

**Issue by bellwood** [digitalocean/netbox#93]
As the subject indicates, you cannot have both a v4 and v6 primary IP for a device.

Would be nice to have both =)

**Comment by jeremystretch** [comment]
Currently we use a single `primary_ip` field on Device to indicate which IP should be used to reach it. As you point out, this can be either IPv4 _or_ IPv6, but not both.

We could replace this with `primary_ip4` and `primary_ip6`, but then we need some way to decide which address family should be used. For instance, when NetBox reaches out to a device to gather inventory data, should it try IPv4 or IPv6 first? Is this answer the same for _all_devices?

Seems like it would be reasonable to create a `PRIMARY_AF` configuration variable to indicate whether IPv4 or IPv6 should be preferred, but I'm open to suggestions.

**Comment by rackcentral** [comment]
I would suggest as the internet has done it for years.

if ipv6 exist use ipv6 first then followed by ipv4.

**Comment by jeremystretch** [comment]
Just thinking out loud, I see this as entailing three distinct migrations:

1. Add fields `primary_ip4` and `primary_ip6` to the Device model.
2. Copy the value of `primary_ip` to one or the other, depending on the address family of `primary_ip`, for all Devices (this is a [data migration](https://docs.djangoproject.com/en/1.9/topics/migrations/#data-migrations) as opposed to a schema migration).
3. Delete the `primary_ip` field from the Device model.

The `primary_ip` field would become a property on Device which returns `primary_ip6` if set, or falls back to `primary_ip4`.

**Comment by MaXwellFalstein** [comment]
Your last comment is exactly how this should be.

You could do this by keeping the existing variable and setting it to IPv6 or you could do it by finding out if IPv6 is set to anything and then trying that first or reverting to IPv4, again if set, if IPv6 is not supported on that device.

**Comment by LBegnaud** [comment]
@jeremystretch  can you comment on what you mean about "For instance, when NetBox reaches out to a device to gather inventory data"? I didn't think netbox was built for that kind of thing.

**Comment by bellwood** [comment]
@LBegnaud please see:

https://github.com/digitalocean/netbox/blob/develop/netbox/extras/management/commands/run_inventory.py

That runs inventory for devices via RPC

**Comment by jeremystretch** [comment]
Yeah, it's still a beta-level undocumented feature. It was a rushed implementation that needs more love and care before it can be deemed part of NetBox proper.

**Comment by LBegnaud** [comment]
Neat. Thanks for the info!
