### ISSUE TITLE
Allow the connection between console ports

### ISSUE THREAD

**Issue by gkoerdt** [digitalocean/netbox#930]
Hi,

we have some problems with the connection of console ports.
In all our datacenters and location we have conneted many Cisco devices under each other via the console ports(con/aux).
But we can not connect them. I found in the documentation the following information:
"Console ports connect only to console server ports" 

It would be nice if you can allow the connection between console ports.

Thanks
Gregor

**Comment by jeremystretch** [comment]
NetBox only support connections between console ports and console server ports. You can recreate the console port on one device as a console server port if necessary.
