### ISSUE TITLE
Problem With Python package installer

### ISSUE THREAD

**Issue by haptismo** [digitalocean/netbox#931]
Hello,
i have discover ur "software" some day ago and want to try him for a project for make more clear the infrastructures of a place for a project. I will give all the info i can for try to found the problem

I use Debian 8.7.1 (amd64) and have follow the guide http://netbox.readthedocs.io/en/latest/installation/netbox/
But i have a problem when i try to install the required python packages required using PIP.
It gave me an error during the compilation : 
ImportError: No module named packaging.version

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-P0IZzy/PyYAML/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zGslSY-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-P0IZzy/PyYAML
Storing debug log for failure in /root/.pip/pip.log

I use the latest version of Netbox (v1.8.4 - 2017-02-03 )

I will not lie, i'm not a master in these part so i have followed the guide exactly and so don't understand what is the problem, i have think maybe it's because of the debian i use so i want to know if the guide follow an old build ?
If not i'm open to all suggestion who can help me to resolve this problem because i would really love to try this "soft" and familiarize with him because he seem to be very good and will arise my field

**Comment by jeremystretch** [comment]
GitHub issues are intended for bug reports and feature requests only. If you'd like assistance with installing NetBox, please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). Thanks!
