### ISSUE TITLE
without enabling the development server in django I cannot access the server

### ISSUE THREAD

**Issue by Wheaties466** [digitalocean/netbox#932]
[Thu Mar 02 11:31:22.679974 2017] [proxy:error] [pid 13304] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:8001 (127.0.0.1) failed
[Thu Mar 02 11:31:22.680087 2017] [proxy:error] [pid 13304] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Thu Mar 02 11:31:22.680105 2017] [proxy_http:error] [pid 13304] [client (CLIENTIP):12065] AH01114: HTTP: failed to make connection to backend: 127.0.0.1
[Thu Mar 02 11:31:22.999542 2017] [proxy:error] [pid 13305] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:8001 (127.0.0.1) failed
[Thu Mar 02 11:31:22.999600 2017] [proxy:error] [pid 13305] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Thu Mar 02 11:31:22.999613 2017] [proxy_http:error] [pid 13305] [client (CLIENTIP):12067] AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: http://(SERVERIP)

i am on centos and this is from /var/log/httpd/error_log

I added the (CLIENTIP) and (SERVERIP) Field.

when i do not have the django dev server running I get 503 errors. Let me know if any configuration file will help.

**Comment by jeremystretch** [comment]
GitHub issues are intended for bug reports and feature requests only. If you'd like assistance with installing NetBox, please post to the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss). Thanks!
