### ISSUE TITLE
Can't connect interfaces

### ISSUE THREAD

**Issue by alexjhart** [digitalocean/netbox#935]
Issue type: bug report

**Python version:**
2.7.6
**NetBox version:**
1.9.0

1. Open device
2. Click green "connect" + button next to interface
3. Type name of device in search and select from list
4. Select interface from dropdown
5. Click "Connect" button

I'm returned to the same page. 

If I click "connect" again (fields above still populated with same data), I get this:
ValueError at /dcim/devices/6/interface-connections/add/
invalid literal for int() with base 10: ''
Request Method:	POST
Request URL:	http://netbox/dcim/devices/6/interface-connections/add/
Django Version:	1.10.6
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: ''
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py in get_prep_value, line 946
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/opt/netbox/netbox/netbox',
 '/opt/netbox/netbox',
 '/usr/bin',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Thu, 2 Mar 2017 14:56:57 -0800

If I click "cancel" instead at that step, I'm returned to the same device but don't see the connection I attempted made.

**Comment by kmiller7851** [comment]
Same error/behavior. Issue only happened after upgrade to 1.9.0.

Python Version:2.7.5
NetBox Version: 1.9.0

Steps to reproduce:

1)Go to any device 
2)Click on add interface connection to any interface. URL goes to: /dcim/devices/489/interface-connections/add/?interface_a=874
3)Choose B side device and interface.
4)Click Connect. Connection does not add, and URL changes to: /dcim/devices/489/interface-connections/add/ (same page as above with devices filled out, however URL changes)
5)Click Connect again, and get the same error. (traceback listed below):


ValueError at /dcim/devices/489/interface-connections/add/
invalid literal for int() with base 10: ''
Request Method:	POST
Request URL:	https://netbox.XXXXXXXXX.net/dcim/devices/489/interface-connections/add/
Django Version:	1.10.6
Exception Type:	ValueError
Exception Value:	
invalid literal for int() with base 10: ''
Exception Location:	/usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py in get_prep_value, line 946
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/opt/netbox/netbox',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages']
Server time:	Thu, 2 Mar 2017 15:45:00 -0800

Traceback:

Environment:


Request Method: POST
Request URL: https://netbox.XXXXXXXXX.net/dcim/devices/489/interface-connections/add/

Django Version: 1.10.6
Python Version: 2.7.5
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'debug_toolbar',
 'django_tables2',
 'mptt',
 'rest_framework',
 'rest_framework_swagger',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'secrets',
 'tenancy',
 'users',
 'utilities')
Installed Middleware:
('debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'utilities.middleware.LoginRequiredMiddleware')



Traceback:

File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/opt/netbox/netbox/dcim/views.py" in interfaceconnection_add
  1420.         form = forms.InterfaceConnectionForm(device, request.POST)

File "/opt/netbox/netbox/dcim/forms.py" in __init__
  1492.             device_b_interfaces = Interface.objects.filter(device=self.data['device_b']).exclude(

File "/usr/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/db/models/query.py" in filter
  796.         return self._filter_or_exclude(False, *args, **kwargs)

File "/usr/lib/python2.7/site-packages/django/db/models/query.py" in _filter_or_exclude
  814.             clone.query.add_q(Q(*args, **kwargs))

File "/usr/lib/python2.7/site-packages/django/db/models/sql/query.py" in add_q
  1227.         clause, _ = self._add_q(q_object, self.used_aliases)

File "/usr/lib/python2.7/site-packages/django/db/models/sql/query.py" in _add_q
  1253.                     allow_joins=allow_joins, split_subq=split_subq,

File "/usr/lib/python2.7/site-packages/django/db/models/sql/query.py" in build_filter
  1183.             condition = lookup_class(lhs, value)

File "/usr/lib/python2.7/site-packages/django/db/models/lookups.py" in __init__
  19.         self.rhs = self.get_prep_lookup()

File "/usr/lib/python2.7/site-packages/django/db/models/fields/related_lookups.py" in get_prep_lookup
  100.                 self.rhs = target_field.get_prep_value(self.rhs)

File "/usr/lib/python2.7/site-packages/django/db/models/fields/__init__.py" in get_prep_value
  946.         return int(value)

Exception Type: ValueError at /dcim/devices/489/interface-connections/add/
Exception Value: invalid literal for int() with base 10: ''
