### ISSUE TITLE
Devices count on site page does not include unracked devices

### ISSUE THREAD

**Issue by mjclancyau** [digitalocean/netbox#941]
### Issue type: Bug Report

**Python version:** Python 2.7.10
**NetBox version:** 1.9.0-r1

It appears that the devices count on site page does not include unracked devices, the following screencap lists 0 devices:
![image](https://cloud.githubusercontent.com/assets/11141825/23593282/96bb8030-0258-11e7-8e95-d1bd2acfbb5e.png)

But then clicking on the devices count lists the unracked devices, as follows:

![image](https://cloud.githubusercontent.com/assets/11141825/23593347/7d316c28-0259-11e7-86bd-06d443272c25.png)

Seems to an issue with the way stats.device_count is calculated?

Thanks for any help you can provide.

Kind regards,
Matt

**Comment by jeremystretch** [comment]
Looks like I missed some ORM references while implementing #198. Easy fix.
