### ISSUE TITLE
Allow to filter aggregate usage per VRF

### ISSUE THREAD

**Issue by blajah** [digitalocean/netbox#947]
### Issue type:feature request

**Python version:**
**NetBox version:**1.9.0.r1

Hello and thanks for great piece of software :)
I have little suggestion:
While listing usage inside specific aggregate, i would love to be able to list address usage inside specific VRF or maybe if it is easier just to exclude all VRF's and see just global routing table prefixes.

**Comment by jeremystretch** [comment]
Aggregates define the root of your IP hierarchy, irrespective of VRF assignment. You can filter prefixes by VRF assignment.
