### ISSUE TITLE
Child Device Import fail

### ISSUE THREAD

**Issue by elmmare** [digitalocean/netbox#950]
### Issue type: bug report

**Python version:2.7.5
**NetBox version:1.9.1  and 1.9.0r1

Importing a child device list I obtain:
*  *Record 1: null value in column "site_id" violates not-null constraint...*

but "side id" is not a required field for child devices, it should be gathered from the parent device.
I'm quite sure that the feature was working in 1.8.4

**Comment by pstanczak-vidscale** [comment]
Same issue here
**NetBox version:1.9.1 

When trying to import child object

`
,Patch Panel,,Panduit,FAP - SMF LC 6 port,,,,FT-103-01,FAP1`
`

`
Record 1: null value in column "site_id" violates not-null constraint DETAIL: Failing row contains (384, 2017-03-08, 2017-03-08 20:54:57.716456+00, null, , null, null, t, , 14, 42, null, 22, null, null, null, null, null).
`


Trying to connect new child object to a parent object ID: 377 in dcim_device table.

```
 id  |  created   |         last_updated          |   name    | serial | position | face | status | comments | device_role_id | device_type_id | platform_id | rack_id | primary_ip4_id | primary_ip6_id | tenant_id | asset_tag | site_id
-----+------------+-------------------------------+-----------+--------+----------+------+--------+----------+----------------+----------------+-------------+---------+----------------+----------------+-----------+-----------+---------
 377 | 2017-03-08 | 2017-03-08 20:14:57.961739+00 | FT-103-01 |        |       45 |    1 | t      |          |             14 |             27 |             |      22 |                |                |           |           |       2
```
