### ISSUE TITLE
Side-by-side rack elevations

### ISSUE THREAD

**Issue by VictorJ76** [digitalocean/netbox#951]
Hi, 

It would be great to see all the racks in one view by site (maybe like on the picture below). Netbox is a very great tool but (In my opinion) I find it not visual enough. 

Best regards. 

Victor 

![fr1-netbox](https://cloud.githubusercontent.com/assets/18124387/23758288/9b8fdf8c-04e9-11e7-9623-d58c1efba0c7.png)

**Comment by jeremystretch** [comment]
This request needs more detail to be actionable.

**Comment by VictorJ76** [comment]
Ok I will prepare you a more precise request

**Comment by VictorJ76** [comment]
Well I recapitulate my request.

It will be great to have more visual stuff in dcim's part. To be more precisely, my demand is to have a global view of my racks classed by site. 

 For exemple my when I choose one POP in site we already have  a dashboard with contact info, stats, topology etc.  So maybe in racks tab or even in the dashboard's site tab  we can see all the POP's racks (See the paint Art below). 

This is my main request but I can imagine in the future to display  power consumption of each rack below the racks and link between them. 


![frnetbox2](https://cloud.githubusercontent.com/assets/18124387/23787932/a9204796-0574-11e7-92c7-ff8e9fa24d59.PNG)

**Comment by nktl** [comment]
+1, being able to see all the racks in the site and their content on a single screen would be super useful.

**Comment by darrelclute** [comment]
Agree that this would be useful to some extent.  Having some logic to only include the front view, or a toggle between front and rear view would be better than trying to render out both in this composite view. 
 Setting a limit to the first N instances (5-7 is probably reasonable) would keep from being overly cluttered.  If more than the N instances of racks is available in the scope could present some sort of paging to be able to pan.

**Comment by elmmare** [comment]
Loading all the rack elevation in the site form can be not so pretty and usefull if you have a lot of rack.
I think that the feature should be activated by request in the site form (Add/Import/Export/Elevation)

The same function should be placed in the rack list, so you cant set the filter, select the "interesting" rack, hit the button and generate a new window with the vertical layout.
The new window layout should be printable/exportable.

**Comment by jbro209070** [comment]
My company uses Netbox on a daily basis, and I had just discussed this with a co-worker today that it would be incredibly useful to have a global rack view where we can see all of the racks side by side. We would be happy just to be able to see the front side of the racks and have all of them side by side per site. Just thought I would put my two cents in here, I think this feature would be amazing to have.

**Comment by Lonecrowe** [comment]
Add me in.  If you have to make a side scrolling window that would be fine.  

Possibly even a top down view too for large amounts in a room you can just click on to take you directly to the rack.
