### ISSUE TITLE
Unnamed Device Error

### ISSUE THREAD

**Issue by therealjoshuad** [digitalocean/netbox#956]
### Issue type:
Bug Report

**Python version:** 2.7.12
**NetBox version:** 1.9.0-r1
**OS version:** Ubuntu 16.04.2

I was creating a device, and accidentally left the device name blank. I got this error:
![image](https://cloud.githubusercontent.com/assets/3893036/23801361/810d31dc-0575-11e7-9583-e3ba51a1386f.png)

I now have a "unnamed device" 
![image](https://cloud.githubusercontent.com/assets/3893036/23801416/b8b1ca44-0575-11e7-9833-5fb5df7b65d8.png)

If I try to edit, or delete the device, I get the same error from above
![image](https://cloud.githubusercontent.com/assets/3893036/23801435/c6db6ee0-0575-11e7-99ac-8d24f957934b.png)

**Comment by jeremystretch** [comment]
This bug occurs when an unnamed device has no rack assigned. The `display_name` method had not been updated to allow for rackless devices.
