### ISSUE TITLE
Add Juniper VCP interface type to stacking choices

### ISSUE THREAD

**Issue by lampwins** [digitalocean/netbox#960]
### Issue type: feature request

Minor request to have Juniper VCP (Virtual Chassis Port) added as an interface type choice under the "Stacking" section.

**Comment by jeremystretch** [comment]
As far as I'm aware, Juniper utilizes standard Ethernet interfaces for stacking. The Cisco types are included only because they are physical interface definitions.

**Comment by jsenecal** [comment]
Not all the switches use standard types.

For instance, EX4200 series switches use a proprietary Twinax cable.

**Comment by specialcircumstances** [comment]
Is it worth considering this being changed to be a table? That way the code wouldn't require updates every time a new speed of Gigabit Ethernet is announced!

**Comment by AlexanderS** [comment]
See #167 for the reasoning, why this is hard coded and not configurable.

**Comment by lampwins** [comment]
To add to what @jsenecal said, Juniper does have proprietary interfaces for many models like Cisco but they do also allow the use of regular interfaces for stacking as well, like @jeremystretch said. It should be noted that when this is the case, the interface in converted so that it no longer looks or acts like a standard interface to the system (it is renamed and renumbered). So they look and act like traditional (proprietary) stacking interfaces.

But in short, yes Juniper does have proprietary VCP interfaces.

**Comment by jeremystretch** [comment]
I'm fine with adding any of the physical types if we can determine the canonical names.

**Comment by lampwins** [comment]
They are simply called Virtual Chassis Ports or more commonly referred to as VCP's.

http://www.juniper.net/documentation/en_US/release-independent/junos/topics/reference/requirements/cable-ex4200-virtual-chassis-cabling-examples.html
