### ISSUE TITLE
Comment field : When adding URL as a comment the test do not wrap 

### ISSUE THREAD

**Issue by himanisilva** [digitalocean/netbox#961]
### Issue type:
When adding a URL in the comments the URL does not wrap to the comment box size 
  We could fix it by editing the HTML code "wrap text"on the web page. But can we get it fixed in Netbox code please

![image](https://cloud.githubusercontent.com/assets/24537122/23881232/436b3aa0-08ad-11e7-8291-ab9644cb4b9d.png)

-->
**Python version:**
**NetBox version:** V1.9.1

**Comment by jeremystretch** [comment]
This is simply how the browser renders text that it cannot wrap. Instead of showing the full link, I'd suggest using [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to give the link a shorter hypertext. For example:

```
Full path MAP is [available on Sharepoint](https://reallylonglinkgoeshere/)
```
