### ISSUE TITLE
Add HP IRF interface type to stacking choices

### ISSUE THREAD

**Issue by afics** [digitalocean/netbox#962]
### Issue type: feature request

Minor request to have HP IRF (Intelligent Resilient Framework) added as an interface type choice under the "Stacking" section.

**Comment by jeremystretch** [comment]
If this is a physical interface type, can you please provide a link to its documentation? If not, you'll want to create an interface using the appropriate physical type instead.

**Comment by leandroteleco** [comment]
HP IRF is for Comware switches and the physical interface is normal service port like RJ45, but DAC cables with SFP+ (10 Gbps) o QSFP+ (40 Gbps) is more frecuent. http://h20566.www2.hpe.com/hpsc/doc/public/display?sp4ts.oid=5230358&docId=emr_na-c03187005&docLocale=en_US

**Comment by afics** [comment]
As @leandroteleco said, this is no physical interface type.
