### ISSUE TITLE
When creating an interface can't add it to the 'Parent LAG'

### ISSUE THREAD

**Issue by joxz** [digitalocean/netbox#967]
### Issue type: Bug

**Python version:** 2.7.12
**NetBox version:** 1.9.1

When I try to create an interface and add the 'Parent LAG', there's an error message 'Select a valid choice'. 

![lag creation](http://i.imgur.com/ExNijPE.png)

![interface creation](http://i.imgur.com/cHxFITU.png)

Creating the interface without Parent LAG and adding it after that to the LAG manually works.

![success](http://i.imgur.com/UApmju3.png)

**Comment by jeremystretch** [comment]
Fixed in 3ce2f0d
