### ISSUE TITLE
Show available VLAN IDs within a group

### ISSUE THREAD

**Issue by ktims** [digitalocean/netbox#971]
Feature request to show available VLAN IDs within a group, similar to the way available prefixes are shown in aggregates/parent prefixes. Currently allocating a new VLAN requires manually browsing the list to find an available ID, remembering it, and manually entering in the Add a VLAN form. It would be nice to streamline this.

**Comment by jeremystretch** [comment]
How would you display this? Could you provide a mock-up?

**Comment by ktims** [comment]
Sure, I'm imagining something very much like what exists when viewing a prefix on the IP addresses tab. I guess this would involve creating a new view for VLAN groups, rather than just linking to the VLAN search. I've mocked something up based on the mentioned prefix page.
![netbox-vlans-mockup](https://cloud.githubusercontent.com/assets/1471533/24025607/ac234fca-0a78-11e7-9f81-0a08eeb12fc3.png)

**Comment by jeremystretch** [comment]
Oh, ok. I thought you were talking about inserting the VLAN list in the form somehow. I like it.

**Comment by jeremystretch** [comment]
Thinking about this further, we don't have a view for VLANGroup because it's not a primary object. (It's used only for the organization of primary objects.) Not sure we really want to deviate from that pattern.

**Comment by esajo** [comment]
For auto-allocation it would be awesome to get this info via an API call.

**Comment by mmahacek** [comment]
How would this know what VLANs to show as available?  You assign a group to a VLAN, not the other way around.  A VLAN group is for organization inside Netbox and for filtering the drop down lists.  There isn't a specific assumption of what VLANS should be in the group to determine what is missing, unless you are checking the site's entered VLANs against all possible VLAN IDs.
