### ISSUE TITLE
add support of custom fields for Regions

### ISSUE THREAD

**Issue by askbow** [digitalocean/netbox#975]
### Issue type: feature request
Regions ( #164 ) are a very neat way of grouping sites, but they currently lack any informational fields beyond Name and nesting.
I think that adding Custom field capability to Regions would cover for most needs in that respect.

For example, some users might want to store Time Zone where the Region operates, or some other information (_characterizing how hard it is to reach the region, for instance: regular, mountainous, polar, undersea, orbital, asteroid belt, gamma quadrant, etc_).

**Comment by jeremystretch** [comment]
Regions are secondary objects similar to rack groups and VLAN groups, which are used solely for the organization of primary objects. They aren't intended to store additional information. Rather, that information should be applies to sites directly.

**Comment by askbow** [comment]
@jeremystretch I agree. 
I had an idea and decided to open an "issue" about it, so it won't be lost.

Adding this feature might also result in duplicate and/or conflicting information down the road.

**Comment by jeremystretch** [comment]
Ok, cool. I'm going to close this out then.
