### ISSUE TITLE
Sort by name alphabetically desc in all views by default

### ISSUE THREAD

**Issue by afics** [digitalocean/netbox#976]
### Issue type: feature request

Sort by name alphabetically desc in all views by default.

While clicking on the name column to sort is just a minor inconvenience imho sorting by default results in a better user experience.

**Comment by jeremystretch** [comment]
Please provide more detail. What specific views would you change?

**Comment by afics** [comment]
I don't know which views are affected. I noticed when I was adding our datacenters like (DC4, DC5, DC3) and they were sorted like that instead of (DC3, DC4, DC5) in the Sites view.

**Comment by jeremystretch** [comment]
If I add three sites named DC3, DC4, and DC5, they show up in order as expected. This should be the case for all sites. Which version of NetBox are you running?

**Comment by afics** [comment]
Argh, I named the first two DC4/DC5 and the third one "DC3 / Something". Of course it is sorted after the first two then.

Sorry, closing…
