### ISSUE TITLE
Can't expand each ip_prefix, only expand all

### ISSUE THREAD

**Issue by zeomegazord** [digitalocean/netbox#977]
### Issue type:
feature request

**Python version:**
2.7
**NetBox version:**
1.9.0

I can't expand needed ip_prefix if I click on triangle near ip_prefix. I can expand all ip_prefixes only. It's very unuseful. Could you please fix it.

**Comment by jeremystretch** [comment]
Duplicate of #55. This is intended behavior (for now).
