### ISSUE TITLE
Record user name along with created/updated times for CreatedUpdatedModels

### ISSUE THREAD

**Issue by CassioFabius** [digitalocean/netbox#979]
Feature Request:

Here, some people have access to Netbox to update the IP's we are using, or to register new devices in each rack. But some of them forget to update when a device is removed or when an IP is free again/deprecated.

It would be nice to see after the date and time of the creation/update of that item who made that modification (e.g. Created Jan. 19, 2017 · Updated 3 days, 19 hours ago · **John Smith**).

And/or maybe a new field (like "Description") to keep the name of the person responsible for that device/IP, so, if necessary, we can ask that person directly about it, instead of asking each person of our workgroup. :)

**Comment by jeremystretch** [comment]
The second part (essentially an "owner" field) would be a separate feature. Let's limit this issue to the addition of an "updated_by" field to all `CreatedUpdatedModels`.

**Comment by CassioFabius** [comment]
Great!

**Comment by quentinsch** [comment]
Yeah, this would be great and is an addition to my earlier issue regarding searchable history for auditing purposes: #683

**Comment by InsaneSplash** [comment]
Would help to know who added the record, and who last edited it. This way one can track the original source of information and any incremental changes that were made to the original record.

Maybe an easier way would be to display last edit, but allow a click through to search all changes on that record (currently held within the event table) and displaying the original author of the record.

**Comment by jeremystretch** [comment]
There's a lot of overlap between this extension and #1127, which calls for revamping the UserAction logging mechanism. If that works out well, associating the "last modified by" user with objects directly should be redundant.

I had originally tagged this for v2.3 but I'm going to hold off until #1127 has been completed and re-evaluate.

**Comment by DevilWAH** [comment]
Would this allow a change that rather then showing under the Device name 

"Created Feb. 28, 2018 · Updated 8 minutes ago"

it could instead show 

"Created Feb. 28, 2018 by John Smith · Last updated by DevilWAH on March 12th 2018"

With these being searchable so it is easy to find any device not updated for X number of days? 

This would be extremaly helpfor for complience where we need to be able to show auditors we are keeping assest up to date. Espicaly if this is exported when you export a list of devices.

**Comment by jeremystretch** [comment]
While I'm leaving the `last_created` and `last_updated` times on individual models, ownership of each change has been established via the new ObjectChange model introduced under #1898. A new "change log" tab will appear under each applicable object, which will display its entire change history.
