### ISSUE TITLE
Feature Request: Show visual rackspace reservations in graphical view

### ISSUE THREAD

**Issue by timcoop3r** [digitalocean/netbox#980]
Currently rack reservations show in the reservations table on a rack page, and when using mouse-over on the graphical rack view it displays the reservation as a comment.

Ideally we would also like to see some sort of shading or visual representation of rack-space reservations that are not yet filled with equipment in the graphical rack view. currently it is easy for someone untrained to believe the space is actually available when viewing the rack-space graphical view alone as without the mouse-over it does not show the space is reserved.

**Comment by jeremystretch** [comment]
Rack reservations are represented with blue diagonal stripes, like this:

![rack_reservation](https://cloud.githubusercontent.com/assets/13487278/24153713/9852a300-0e25-11e7-9050-7a9b8fbb14b5.png)

If you don't see that, try forcing a refresh of the cached CSS file by hitting ctrl+F5 (or equivalent) or navigating to `/static/css/base.css` directly.

**Comment by timcoop3r** [comment]
Oh well that is embarrassing. I'm sure I tried a forced refresh, but clearly not.... /facepalm.

Thanks for the quick response
