### ISSUE TITLE
Permit local configuration of Django LOGGING

### ISSUE THREAD

**Issue by ktims** [digitalocean/netbox#990]
It would be useful to permit local configuration of the Django `LOGGING` setting. Currently if custom LOGGING is desired, it must be configured in `settings.py`, but this is part of the distribution. Simple change, as the facility to import local settings is already there.

```patch
diff --git a/netbox/netbox/settings.py b/netbox/netbox/settings.py
index ae81d26..c1daf42 100644
--- a/netbox/netbox/settings.py
+++ b/netbox/netbox/settings.py
@@ -15,7 +15,7 @@ except ImportError:
 VERSION = '1.9.3'
 
 # Import local configuration
-for setting in ['ALLOWED_HOSTS', 'DATABASE', 'SECRET_KEY']:
+for setting in ['ALLOWED_HOSTS', 'DATABASE', 'SECRET_KEY', 'LOGGING']:
     try:
         globals()[setting] = getattr(configuration, setting)
     except AttributeError:
```

**Comment by jeremystretch** [comment]
FYI the code above would make `LOGGING` a mandatory setting, which is not what we want.
