### ISSUE TITLE
Netbox Server Error after upgrade from v1.8.4 to v1.9.3

### ISSUE THREAD

**Issue by blackstrip** [digitalocean/netbox#994]
### Issue type: bug report

**Python version: 2.7.13**
**NetBox version: 1.9.3**

Server Error as follows when i ran the upgrade.sh:

```
<class 'django.urls.exceptions.NoReverseMatch'>

u'users' is not a registered namespace
```

**the error is trigged when i sign-in to my netbox website.**
How can i slove it?

**Comment by jeremystretch** [comment]
Please provide the steps to replicate this bug. What were you doing when you encountered the error?

**Comment by blackstrip** [comment]
I dont know what problem, but it's work find now when i reinstall netbox, thx.
