### ISSUE TITLE
NoReverseMatch Exception: Add Interface Connection

### ISSUE THREAD

**Issue by zachmoody** [digitalocean/netbox#996]
### Issue type: Bug Report

**Python version:** 2.7.13
**NetBox version:** v2-develop

Trying to connect an interface in `v2-develop` raises an [exception](http://dpaste.com/3R1HNJV). 

Think I've tracked it down to an old API url being given to the livesearch field. Will submit a PR shortly with a fix.

**Comment by jeremystretch** [comment]
Merged #997. Thanks!
